const DISPOSABLE_DOMAINS = new Set([
  'mailinator.com', 'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.de', 'grr.la', 'guerrillamailblock.com', 'pokemail.net',
  'sharklasers.com', 'spam4.me', 'tempmail.com', 'temp-mail.org', 'temp-mail.io',
  'throwaway.email', 'yopmail.com', 'yopmail.fr', 'yopmail.net',
  'dispostable.com', 'maildrop.cc', 'mailnesia.com', 'mailcatch.com',
  'trashmail.com', 'trashmail.me', 'trashmail.net', 'trashmail.org',
  'fakeinbox.com', 'fakemail.net', 'tempail.com', 'tempmailaddress.com',
  'emailondeck.com', 'getnada.com', 'mohmal.com', 'discard.email',
  'minutemail.com', 'emailfake.com', 'crazymailing.com',
  'mailsac.com', 'inboxkitten.com', 'mytemp.email',
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  '20minutemail.com', 'guerrillamail.info', 'mailexpire.com', 'tempinbox.com',
  'burnermail.io', 'harakirimail.com', 'jetable.org',
  'mailnull.com', 'spamgourmet.com', 'spamgourmet.net',
  'temporarymail.com', 'throwawaymail.com',
  'bugmenot.com', 'deadaddress.com', 'despammed.com',
  'devnullmail.com', 'dodgeit.com', 'dodgit.com',
  'dontreg.com', 'ephemail.net', 'filzmail.com',
  'getonemail.com', 'getonemail.net',
  'haltospam.com', 'incognitomail.com',
  'incognitomail.net', 'incognitomail.org',
  'maileater.com', 'mailforspam.com',
  'mailin8r.com', 'mailinator.net', 'mailinator2.com',
  'mailinator.us', 'mailmetrash.com', 'mailmoat.com',
  'mailshell.com', 'mailsiphon.com',
  'mailslite.com', 'mailzilla.com', 'mailzilla.org',
  'meltmail.com', 'mintemail.com',
  'mytrashmail.com', 'nervmich.net',
  'netmails.com', 'netmails.net', 'neverbox.com', 'no-spam.ws',
  'nobulk.com', 'noclickemail.com',
  'nomail2me.com', 'nomorespamemails.com',
  'notmailinator.com', 'nowmymail.com',
  'oneoffemail.com', 'onewaymail.com',
  'pookmail.com', 'proxymail.eu',
  'quickinbox.com', 'rcpt.at',
  'regbypass.com', 'rejectmail.com', 'rhyta.com',
  'safe-mail.net', 'safetymail.info',
  'selfdestructingmail.com', 'sendspamhere.com',
  'shitmail.me', 'shortmail.net',
  'slopsbox.com', 'spam.la',
  'spamavert.com', 'spambob.com', 'spambob.net',
  'spambob.org', 'spambog.com', 'spambog.de',
  'spambox.us', 'spamcannon.com',
  'spamcero.com', 'spamcowboy.com',
  'spamday.com', 'spamex.com',
  'spamfree24.com', 'spamgoes.in',
  'spamhole.com', 'spamify.com',
  'spaml.com', 'spammotel.com',
  'spamoff.de', 'spamslicer.com', 'spamspot.com',
  'spamstack.net', 'spamtrail.com', 'spamtrap.ro',
  'teleworm.com', 'teleworm.us', 'tempalias.com',
  'tempemail.com', 'tempemail.net',
  'tempinbox.co.uk', 'tempo-mail.com',
  'temporaryemail.net', 'temporaryemail.us',
  'temporaryinbox.com', 'temporarymailaddress.com',
  'thisisnotmyrealemail.com', 'throam.com', 'throwam.com',
  'tmailinator.com', 'tradermail.info',
  'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
  'trashdevil.com', 'trashemail.de', 'trashemails.de',
  'trashmail.at', 'trashmail.de', 'trashmail.in', 'trashmail.io',
  'trashmail.ws', 'trashmailer.com', 'trashymail.com',
  'trashymail.net',
  'venompen.com', 'veryreallyfakemail.com',
  'whyspam.me', 'willselfdestruct.com',
  'xagloo.com', 'xemaps.com',
  'yapped.net', 'zehnminutenmail.de', 'zippymail.info',
  'zoaxe.com', 'zoemail.org',
  'smartnator.com', 'emvil.com', 'tmail.com',
  'tmpmail.net', 'tmpmail.org', 'bupmail.com',
  'tmpbox.com', 'moakt.com', 'moakt.ws',
  'moakt.co', 'ahem.email', 'ezztt.com',
  'mailkept.com', 'dropmail.me',
  'inboxes.com', 'emlhub.com', 'emlpro.com',
  'fixmail.tk', 'flurred.com',
  'mailcuk.com', 'mailde.de', 'mailde.info',
  'maildu.de', 'maileimer.de',
  'mailfs.com', 'mailhub.pro', 'mailhz.me',
  'mailimate.com', 'mailinater.com',
  'simplelogin.co', 'simplelogin.com',
  'anonaddy.com', 'anonaddy.me',
  'relay.firefox.com', 'mozmail.com',
  'privaterelay.appleid.com',
])

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase()
  return domain ? DISPOSABLE_DOMAINS.has(domain) : false
}
