import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const flashcards = [
  // ============================================================
  // DISEASE STATES - OBSTRUCTIVE (cards 201-220)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the hallmark spirometry finding in COPD?',
    answer: 'A reduced FEV1/FVC ratio below 0.70 that does not fully reverse with bronchodilator therapy. This distinguishes COPD from asthma, which typically shows significant reversibility after bronchodilator administration.',
    difficulty: 2,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 201,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the pathological difference between emphysema and chronic bronchitis?',
    answer: 'Emphysema involves permanent destruction of alveolar walls distal to the terminal bronchioles, causing loss of elastic recoil and air trapping. Chronic bronchitis is defined by productive cough for at least three months in two consecutive years, caused by hypertrophy of mucus-secreting glands and chronic airway inflammation.',
    difficulty: 2,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 202,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the two anatomical subtypes of emphysema and their associations?',
    answer: 'Centrilobular (centriacinar) emphysema affects the respiratory bronchioles primarily in the upper lobes and is strongly associated with cigarette smoking. Panlobular (panacinar) emphysema destroys the entire acinus uniformly, predominantly affects the lower lobes, and is associated with alpha-1 antitrypsin deficiency.',
    difficulty: 3,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 203,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Why do patients with severe emphysema use pursed-lip breathing?',
    answer: 'Pursed-lip breathing creates back pressure that splints the airways open during exhalation, preventing premature airway collapse caused by the loss of elastic recoil. This helps reduce air trapping, improves gas exchange, and decreases the work of breathing.',
    difficulty: 1,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 204,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the GOLD classification system for COPD severity?',
    answer: 'The GOLD system classifies COPD severity by post-bronchodilator FEV1 percent predicted: GOLD 1 (mild) is FEV1 at or above 80%, GOLD 2 (moderate) is 50-79%, GOLD 3 (severe) is 30-49%, and GOLD 4 (very severe) is below 30%. It guides treatment escalation decisions.',
    difficulty: 1,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 205,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What triggers an acute exacerbation of COPD and how is it managed?',
    answer: 'COPD exacerbations are most commonly triggered by respiratory infections (viral or bacterial) and air pollution. Management includes short-acting bronchodilators, systemic corticosteroids for 5-7 days, antibiotics if purulent sputum is present, and supplemental oxygen titrated to an SpO2 of 88-92%.',
    difficulty: 1,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 206,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Why should oxygen therapy be carefully titrated in COPD patients with chronic CO2 retention?',
    answer: 'In chronically hypercapnic COPD patients, the central chemoreceptors become blunted to elevated CO2 levels, and the hypoxic drive via peripheral chemoreceptors becomes the primary stimulus for ventilation. Excessive oxygen can suppress this drive, worsening hypoventilation and CO2 retention. Target SpO2 is 88-92%.',
    difficulty: 3,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 207,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What distinguishes an asthma attack from a COPD exacerbation clinically?',
    answer: 'Asthma attacks are typically episodic with symptom-free intervals, triggered by allergens or exercise, occur in younger patients, and show significant bronchodilator reversibility (12% and 200 mL improvement in FEV1). COPD exacerbations occur on a background of persistent symptoms in older patients with a smoking history and show limited reversibility.',
    difficulty: 1,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 208,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is status asthmaticus?',
    answer: 'Status asthmaticus is a severe, life-threatening asthma exacerbation that does not respond to standard bronchodilator therapy. It is characterized by progressive respiratory distress, severe air trapping, and potential respiratory failure. Management requires continuous nebulized beta-agonists, IV corticosteroids, possibly IV magnesium sulfate, and preparation for intubation.',
    difficulty: 3,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 209,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a "silent chest" in the context of a severe asthma attack?',
    answer: 'A silent chest refers to the absence of wheezing during a severe asthma exacerbation. It is an ominous sign indicating that airflow is so severely restricted that turbulent flow cannot be generated. This signals impending respiratory failure and requires immediate aggressive intervention.',
    difficulty: 2,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 210,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the stepwise approach to long-term asthma management?',
    answer: 'Asthma therapy is stepped up or down based on symptom control. Step 1 uses a rescue inhaler as needed. Steps 2-3 add low-to-medium dose inhaled corticosteroids. Steps 4-5 add long-acting beta-agonists, leukotriene modifiers, or biologic therapies. The goal is the lowest step that maintains control with minimal side effects.',
    difficulty: 2,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 211,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is bronchiectasis and what causes it?',
    answer: 'Bronchiectasis is permanent, abnormal dilation of the bronchial walls due to chronic infection and inflammation that destroys the elastic and muscular components. Common causes include cystic fibrosis, recurrent severe infections, immune deficiency, and ciliary dyskinesia. Patients produce large volumes of purulent sputum daily.',
    difficulty: 2,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 212,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the key respiratory therapy interventions for bronchiectasis?',
    answer: 'Management focuses on aggressive airway clearance techniques including chest physiotherapy, oscillatory PEP devices, and high-frequency chest wall oscillation. Aerosolized hypertonic saline may thin secretions. Inhaled antibiotics such as tobramycin may be used for chronic Pseudomonas colonization. Bronchodilators are added if airflow obstruction is present.',
    difficulty: 3,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 213,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the genetic defect in cystic fibrosis and how does it affect the lungs?',
    answer: 'Cystic fibrosis is caused by mutations in the CFTR gene encoding a chloride channel on epithelial cells. Defective chloride transport leads to dehydrated, abnormally thick and sticky mucus that obstructs airways, impairs mucociliary clearance, and promotes chronic bacterial infections, particularly with Pseudomonas aeruginosa and Staphylococcus aureus.',
    difficulty: 3,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 214,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the role of dornase alfa (Pulmozyme) in cystic fibrosis?',
    answer: 'Dornase alfa is a recombinant DNase enzyme that cleaves extracellular DNA released from neutrophils in CF sputum. By breaking down this DNA, it reduces sputum viscosity and improves airway clearance. It is administered via nebulizer once daily, typically before airway clearance therapy.',
    difficulty: 3,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 215,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is alpha-1 antitrypsin deficiency and how does it cause emphysema?',
    answer: 'Alpha-1 antitrypsin is a protease inhibitor that protects lung tissue from neutrophil elastase. When deficient, unchecked elastase activity destroys alveolar walls, causing panlobular emphysema predominantly in the lung bases. It typically presents in younger adults who are non-smokers or light smokers. Augmentation therapy with pooled human AAT is available.',
    difficulty: 3,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 216,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What chest X-ray findings are characteristic of COPD with emphysema?',
    answer: 'Chest X-ray findings include hyperinflation with flattened diaphragms, increased anteroposterior diameter (barrel chest), widened intercostal spaces, increased retrosternal air space on lateral view, and hyperlucent lung fields. The heart may appear small and elongated due to the hyperinflated lungs.',
    difficulty: 1,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 217,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the role of long-acting muscarinic antagonists (LAMAs) in COPD management?',
    answer: 'LAMAs such as tiotropium block acetylcholine at M3 muscarinic receptors in airway smooth muscle, producing sustained bronchodilation lasting 24 hours. They reduce exacerbation frequency, improve exercise tolerance, and are recommended as first-line maintenance therapy in COPD. They are delivered via dry powder or soft mist inhaler.',
    difficulty: 3,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 218,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is exercise-induced bronchoconstriction and how is it managed?',
    answer: 'Exercise-induced bronchoconstriction is transient airway narrowing triggered by heat and moisture loss from airways during vigorous exercise. Symptoms peak 5-10 minutes after stopping exercise. Prevention includes using a short-acting beta-agonist 15 minutes before exercise and warming up gradually. A daily inhaled corticosteroid is added if episodes are frequent.',
    difficulty: 1,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 219,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is auto-PEEP (intrinsic PEEP) and why is it problematic in obstructive lung disease?',
    answer: 'Auto-PEEP is unintentional positive pressure remaining in the alveoli at end-expiration due to incomplete exhalation, common in severe obstruction and high respiratory rates. It increases work of breathing because the patient must overcome auto-PEEP before inspiratory flow begins, can cause hemodynamic compromise by reducing venous return, and may cause ventilator dyssynchrony.',
    difficulty: 3,
    topic: 'Disease States - Obstructive',
    isFree: false,
    orderIndex: 220,
  },

  // ============================================================
  // DISEASE STATES - RESTRICTIVE (cards 221-235)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What spirometry pattern is characteristic of restrictive lung disease?',
    answer: 'Restrictive lung disease shows a proportional reduction in both FEV1 and FVC, resulting in a normal or elevated FEV1/FVC ratio (above 0.70). Total lung capacity (TLC) measured by body plethysmography is reduced below 80% predicted, which is the definitive diagnostic finding.',
    difficulty: 1,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 221,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is idiopathic pulmonary fibrosis (IPF) and how does it affect gas exchange?',
    answer: 'IPF is a progressive interstitial lung disease causing fibrotic scarring of the alveolar walls without a known cause. The thickened interstitium impairs oxygen diffusion, resulting in a decreased DLCO and hypoxemia that worsens with exertion. It typically presents in older adults with dry cough and progressive dyspnea.',
    difficulty: 2,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 222,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What auscultation finding is classic for pulmonary fibrosis?',
    answer: 'Bilateral, basilar, end-inspiratory fine crackles (often described as "Velcro-like" crackles) are the hallmark auscultation finding in pulmonary fibrosis. They occur because fibrotic, stiff alveoli snap open during inspiration. Digital clubbing is also commonly seen on physical exam.',
    difficulty: 1,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 223,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the Berlin criteria for diagnosing ARDS?',
    answer: 'The Berlin criteria require: acute onset within one week of a known insult, bilateral opacities on chest imaging not fully explained by effusions or atelectasis, respiratory failure not fully explained by cardiac failure or fluid overload, and PaO2/FiO2 ratio categorization (mild 200-300, moderate 100-200, severe below 100) measured with at least 5 cmH2O of PEEP.',
    difficulty: 3,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 224,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What ventilator strategy is recommended for ARDS?',
    answer: 'Lung-protective ventilation is the standard of care: tidal volume of 4-8 mL/kg ideal body weight, plateau pressure below 30 cmH2O, adequate PEEP guided by a FiO2/PEEP table or esophageal pressure monitoring, and permissive hypercapnia if needed to maintain low volumes. Prone positioning for 16 or more hours daily is recommended for moderate to severe ARDS.',
    difficulty: 3,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 225,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the common risk factors for developing ARDS?',
    answer: 'Direct pulmonary causes include pneumonia, aspiration of gastric contents, pulmonary contusion, inhalation injury, and near-drowning. Indirect causes include sepsis (the most common), pancreatitis, massive transfusion, major trauma, and drug overdose. Sepsis carries the highest risk among all etiologies.',
    difficulty: 3,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 226,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does a pleural effusion affect respiratory mechanics?',
    answer: 'Pleural effusion compresses the underlying lung parenchyma, reducing lung volume and causing a restrictive ventilatory defect. Patients develop dyspnea, decreased breath sounds, and dullness to percussion over the effusion. Large effusions shift the mediastinum toward the opposite side. Thoracentesis removes fluid to restore lung expansion.',
    difficulty: 3,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 227,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What distinguishes a tension pneumothorax from a simple pneumothorax?',
    answer: 'A tension pneumothorax involves a one-way valve mechanism where air enters the pleural space but cannot escape, causing progressive pressure buildup. Unlike a simple pneumothorax, tension pneumothorax causes mediastinal shift away from the affected side, tracheal deviation, hypotension, and jugular venous distension. It requires immediate needle decompression.',
    difficulty: 2,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 228,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the three types of atelectasis and their mechanisms?',
    answer: 'Resorption (obstructive) atelectasis occurs when a mucus plug or foreign body blocks the airway and trapped gas is absorbed. Compression atelectasis results from external pressure on the lung such as pleural effusion or tumor. Passive (relaxation) atelectasis occurs when the normal negative intrapleural pressure is lost, as in pneumothorax.',
    difficulty: 3,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 229,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does Guillain-Barre syndrome affect respiratory function?',
    answer: 'Guillain-Barre syndrome causes ascending demyelinating polyneuropathy that can weaken the diaphragm and intercostal muscles, leading to progressive ventilatory failure. Serial measurements of negative inspiratory force (NIF) and vital capacity are critical: intubation is considered when NIF weakens to less negative than -20 cmH2O or vital capacity drops below 15 mL/kg.',
    difficulty: 3,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 230,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is myasthenia gravis and how does it impair ventilation?',
    answer: 'Myasthenia gravis is an autoimmune disorder in which antibodies attack acetylcholine receptors at the neuromuscular junction, causing progressive skeletal muscle weakness. Respiratory failure occurs when the diaphragm and accessory muscles fatigue, manifesting as declining vital capacity, weak cough, and eventual CO2 retention. Treatment includes anticholinesterase agents and immunotherapy.',
    difficulty: 3,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 231,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between community-acquired and hospital-acquired pneumonia?',
    answer: 'Community-acquired pneumonia (CAP) develops outside the hospital, most often caused by Streptococcus pneumoniae, and is treated with macrolides or respiratory fluoroquinolones. Hospital-acquired pneumonia (HAP) develops 48 hours or more after admission and involves more resistant organisms such as MRSA and Pseudomonas, requiring broader-spectrum antibiotics.',
    difficulty: 3,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 232,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is ventilator-associated pneumonia (VAP) and how is it prevented?',
    answer: 'VAP is pneumonia developing 48 hours or more after endotracheal intubation. Prevention includes elevating the head of bed 30-45 degrees, daily sedation vacation and spontaneous breathing trials, oral care with chlorhexidine, maintaining adequate cuff pressure (20-30 cmH2O), and avoiding unnecessary reintubation.',
    difficulty: 2,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 233,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What respiratory changes occur in obesity hypoventilation syndrome?',
    answer: 'Obesity hypoventilation syndrome involves chronic daytime hypercapnia (PaCO2 above 45 mmHg) in obese patients (BMI above 30) without another identifiable cause. Excess abdominal weight restricts diaphragm excursion, reducing FRC and ERV. It causes sleep-disordered breathing and is treated with nocturnal noninvasive ventilation and weight management.',
    difficulty: 2,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 234,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a flail chest and how does it impair ventilation?',
    answer: 'Flail chest occurs when three or more adjacent ribs are fractured in at least two places, creating a free-floating segment. This segment moves paradoxically (inward during inspiration, outward during expiration), impairing the chest wall ability to generate negative pressure. The underlying pulmonary contusion often contributes more to respiratory failure than the mechanical flail.',
    difficulty: 2,
    topic: 'Disease States - Restrictive',
    isFree: false,
    orderIndex: 235,
  },

  // ============================================================
  // PATIENT EDUCATION & COMMUNICATION (cards 236-250)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the steps for teaching proper metered-dose inhaler (MDI) technique without a spacer?',
    answer: 'Instruct the patient to shake the inhaler, exhale completely, place the mouthpiece between the lips, begin a slow deep inhalation while pressing the canister, continue inhaling for 3-5 seconds, hold the breath for up to 10 seconds, then exhale slowly. Wait at least 30-60 seconds between puffs if more than one is prescribed.',
    difficulty: 1,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 236,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Why is a spacer (valved holding chamber) recommended with an MDI?',
    answer: 'A spacer reduces the need for coordinating actuation with inhalation, decreases oropharyngeal deposition of the drug (reducing local side effects such as thrush from corticosteroids), and increases the respirable fraction reaching the lower airways. It is particularly beneficial for children, elderly patients, and those with poor coordination.',
    difficulty: 1,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 237,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What technique should be taught for using a dry powder inhaler (DPI)?',
    answer: 'The patient should exhale away from the device (never into it, as moisture degrades the powder), then inhale quickly and deeply through the mouthpiece to generate sufficient inspiratory flow to disperse the powder. Breath holding for 5-10 seconds follows. A spacer is never used with a DPI. Minimum inspiratory flow of 30-60 L/min is required.',
    difficulty: 2,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 238,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What oral hygiene instructions accompany inhaled corticosteroid therapy?',
    answer: 'Patients should rinse their mouth with water and spit after each use to prevent oropharyngeal candidiasis (thrush) and dysphonia. Using a spacer with an MDI also reduces oral deposition. If using a DPI, mouth rinsing is equally important as the drug deposits directly in the oropharynx.',
    difficulty: 1,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 239,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the key components of an asthma action plan?',
    answer: 'An asthma action plan uses a traffic light system: Green zone (well-controlled, take maintenance medications), Yellow zone (worsening symptoms, add rescue inhaler and possibly increase controller), and Red zone (severe symptoms, use rescue inhaler immediately and seek emergency care). It includes personal best peak flow values and specific medication instructions.',
    difficulty: 1,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 240,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the five "As" of smoking cessation counseling?',
    answer: 'Ask about tobacco use at every visit, Advise to quit in a clear and personalized manner, Assess willingness to make a quit attempt, Assist with a quit plan (including pharmacotherapy like nicotine replacement, varenicline, or bupropion), and Arrange follow-up contact within the first week. Even brief interventions improve quit rates.',
    difficulty: 3,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 241,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What should patients be taught about home oxygen safety?',
    answer: 'Patients must keep oxygen at least 6-10 feet from open flames, heat sources, and electrical devices that may spark. No smoking while using or near oxygen equipment. Store cylinders upright and secured. Post "Oxygen in Use" signs. Avoid petroleum-based products near the face. Ensure adequate ventilation in the room.',
    difficulty: 1,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 242,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What education is needed when discharging a patient with a home oxygen concentrator?',
    answer: 'Explain that the concentrator uses room air and electricity, not stored gas. Teach how to set the prescribed flow rate, clean the filter weekly, use a backup cylinder during power outages or transport, and recognize alarm conditions. Ensure nasal cannula tubing length does not exceed recommended limits that reduce delivered concentration.',
    difficulty: 2,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 243,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the teach-back method in patient education?',
    answer: 'The teach-back method asks patients to explain in their own words what they have been taught, verifying comprehension rather than simply asking if they understand. If the explanation is incorrect, the educator re-teaches using different language and checks again. This technique significantly improves retention and adherence to treatment plans.',
    difficulty: 1,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 244,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is an advance directive and why is it relevant to respiratory care?',
    answer: 'An advance directive is a legal document specifying a patient preferences for medical treatment if they become unable to communicate. It may include wishes regarding intubation, mechanical ventilation, and CPR. Respiratory therapists must be aware of these directives and honor do-not-intubate (DNI) and do-not-resuscitate (DNR) orders.',
    difficulty: 1,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 245,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What principles guide effective communication with patients who have limited health literacy?',
    answer: 'Use plain language avoiding medical jargon, limit information to two or three key points per session, use visual aids and demonstrations, employ the teach-back method to verify understanding, speak slowly with adequate pauses, and provide written materials at a 5th-6th grade reading level. Always confirm understanding without condescension.',
    difficulty: 2,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 246,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the Patient Bill of Rights as it relates to respiratory care?',
    answer: 'Patients have the right to informed consent before procedures, the right to refuse treatment, the right to privacy and confidentiality of medical information, the right to receive care regardless of race or socioeconomic status, and the right to be informed about their diagnosis and treatment options in understandable terms.',
    difficulty: 1,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 247,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How should a respiratory therapist counsel a COPD patient about pulmonary rehabilitation?',
    answer: 'Explain that pulmonary rehabilitation combines supervised exercise training, education about disease management, breathing techniques (pursed-lip and diaphragmatic breathing), nutritional counseling, and psychosocial support. Emphasize that it improves exercise capacity, reduces dyspnea, and decreases hospitalizations even though it does not reverse the underlying lung damage.',
    difficulty: 2,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 248,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What education should be given to a patient being discharged on home CPAP for obstructive sleep apnea?',
    answer: 'Teach proper mask fitting to minimize leaks, daily cleaning of the mask and weekly cleaning of tubing and humidifier chamber, the importance of using the device every night for the entire sleep period, how to adjust humidity to reduce nasal dryness, and to report persistent mask discomfort, air leaks, or return of daytime sleepiness.',
    difficulty: 2,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 249,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is motivational interviewing and when should it be used in respiratory care?',
    answer: 'Motivational interviewing is a collaborative, patient-centered counseling technique that explores and resolves ambivalence about behavior change. It uses open-ended questions, affirmations, reflective listening, and summarizing. It is particularly effective for smoking cessation, medication adherence, and lifestyle modifications in chronic disease management.',
    difficulty: 3,
    topic: 'Patient Education & Communication',
    isFree: false,
    orderIndex: 250,
  },

  // ============================================================
  // BLOOD GAS SAMPLING & ANALYSIS (cards 251-265)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of the modified Allen test and how is it performed?',
    answer: 'The modified Allen test assesses collateral ulnar circulation before radial artery puncture. Occlude both radial and ulnar arteries while the patient makes a fist, then release the ulnar artery. The hand should flush pink within 5-10 seconds, confirming adequate collateral flow. A negative test (delayed return) indicates poor collateral supply and the radial artery should not be punctured.',
    difficulty: 1,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 251,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the preferred arterial puncture sites in order of preference?',
    answer: 'The radial artery is preferred because of accessible location, good collateral flow via the ulnar artery, and ease of compression. The brachial artery is the second choice but lacks reliable collateral. The femoral artery is used when other sites are unavailable but carries higher risk of hematoma and infection.',
    difficulty: 1,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 252,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What angle should the needle be inserted for a radial artery puncture?',
    answer: 'The needle should be inserted at a 45-degree angle, bevel up, pointing against the direction of blood flow (toward the heart). The wrist should be dorsiflexed at approximately 20-30 degrees over a rolled towel to bring the radial artery closer to the surface and stabilize its position.',
    difficulty: 1,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 253,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does an air bubble in an arterial blood gas sample affect the results?',
    answer: 'Air bubbles in the sample allow room air (PO2 of approximately 150 mmHg, PCO2 near 0 mmHg) to equilibrate with the blood. This falsely increases the PaO2 and falsely decreases the PaCO2. Bubbles should be expelled immediately, and the sample should be capped and analyzed within 30 minutes or placed on ice.',
    difficulty: 2,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 254,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What effect does excess liquid heparin in the ABG syringe have on results?',
    answer: 'Excess liquid heparin dilutes the sample, falsely lowering PaCO2, HCO3, and base excess values. Since heparin is acidic, it can also slightly decrease the pH. This is why pre-heparinized dry lithium heparin syringes are preferred over manually heparinized syringes for arterial blood gas collection.',
    difficulty: 3,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 255,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does a venous sample mistakenly analyzed as arterial blood appear on ABG results?',
    answer: 'A venous sample shows a lower PO2 (typically 35-45 mmHg compared to arterial 80-100 mmHg), a higher PCO2 (typically 41-51 mmHg vs 35-45 mmHg), and a slightly lower pH (7.31-7.37 vs 7.35-7.45). If the blood did not pulsate into the syringe during collection, a venous sample should be suspected.',
    difficulty: 2,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 256,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is co-oximetry and what additional values does it provide beyond a standard ABG?',
    answer: 'Co-oximetry uses multiple wavelengths of light to directly measure total hemoglobin, oxyhemoglobin (O2Hb), deoxyhemoglobin, carboxyhemoglobin (COHb), and methemoglobin (MetHb). Standard pulse oximetry cannot distinguish these hemoglobin species, making co-oximetry essential for suspected carbon monoxide poisoning or methemoglobinemia.',
    difficulty: 2,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 257,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Why does a standard pulse oximeter give falsely elevated readings in carbon monoxide poisoning?',
    answer: 'Standard pulse oximeters use only two wavelengths of light and cannot differentiate oxyhemoglobin from carboxyhemoglobin because both absorb light similarly at these wavelengths. The SpO2 reading therefore includes COHb as if it were O2Hb, resulting in falsely reassuring readings. Co-oximetry is required for accurate assessment.',
    difficulty: 2,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 258,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the normal ETCO2 value on capnography and what does it reflect?',
    answer: 'Normal end-tidal CO2 (ETCO2) is 35-45 mmHg, typically 2-5 mmHg lower than PaCO2 due to dead space ventilation. It reflects the adequacy of alveolar ventilation and pulmonary perfusion. A sudden drop to near zero after intubation suggests esophageal placement, while a gradual rise may indicate hypoventilation.',
    difficulty: 2,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 259,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What waveform abnormalities on a capnogram indicate bronchospasm?',
    answer: 'Bronchospasm produces an upsloping or "shark fin" shaped phase III (alveolar plateau) on the capnogram instead of the normal flat plateau. This occurs because uneven emptying of lung units with different time constants causes a gradual rise in CO2 concentration throughout exhalation. The ETCO2 value may also be elevated.',
    difficulty: 3,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 260,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is transcutaneous monitoring and when is it used?',
    answer: 'Transcutaneous monitoring uses heated sensors placed on the skin surface to estimate PaO2 (tcPO2) and PaCO2 (tcPCO2) noninvasively. The heated element (42-44 degrees C) arterializes capillary blood beneath the sensor. It is most reliable in neonates due to thin skin, and the sensor site must be rotated every 3-4 hours to prevent thermal injury.',
    difficulty: 2,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 261,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the contraindications to arterial puncture?',
    answer: 'Contraindications include a negative modified Allen test (inadequate collateral circulation), local infection at the puncture site, presence of an arteriovenous fistula or shunt, severe coagulopathy or anticoagulation therapy (relative), and previous vascular surgery at the site. An alternative site should be used when any contraindication is present.',
    difficulty: 1,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 262,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the proper technique for applying pressure after an arterial puncture?',
    answer: 'Apply firm, steady pressure with gauze directly over the puncture site for at least 5 minutes (10-15 minutes if the patient is on anticoagulants). Do not occlude the artery completely. After releasing pressure, check for bleeding and distal pulse. If hematoma forms, reapply pressure for an additional period.',
    difficulty: 1,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 263,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does patient temperature affect ABG results if not corrected?',
    answer: 'A hypothermic patient actual in-vivo PaO2 and PaCO2 are lower than what the blood gas analyzer reports at 37 degrees C, because gas solubility increases as temperature decreases. Conversely, a febrile patient actual values are higher than reported. Most clinicians interpret uncorrected (37-degree) values using the alpha-stat method.',
    difficulty: 2,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 264,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does an increased PaO2-to-ETCO2 gradient (P(a-ET)CO2) indicate?',
    answer: 'An increased P(a-ET)CO2 gradient (normally 2-5 mmHg) indicates increased dead space ventilation, meaning more ventilated alveoli are not being adequately perfused. This is seen in pulmonary embolism, low cardiac output states, and excessive PEEP. In these conditions, ETCO2 underestimates the true PaCO2.',
    difficulty: 3,
    topic: 'Blood Gas Sampling & Analysis',
    isFree: false,
    orderIndex: 265,
  },

  // ============================================================
  // NONINVASIVE VENTILATION (cards 266-280)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between CPAP and BiPAP?',
    answer: 'CPAP delivers a single continuous pressure during both inspiration and expiration, primarily splinting the airway open. BiPAP delivers two separate pressures: a higher inspiratory positive airway pressure (IPAP) and a lower expiratory positive airway pressure (EPAP). The difference between IPAP and EPAP provides ventilatory support (pressure support).',
    difficulty: 1,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 266,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the primary indications for noninvasive positive-pressure ventilation?',
    answer: 'NIV is strongly indicated for acute exacerbation of COPD with respiratory acidosis, acute cardiogenic pulmonary edema, and immunocompromised patients with respiratory failure. It is also used for post-extubation support in high-risk patients and to facilitate weaning in COPD patients who fail spontaneous breathing trials.',
    difficulty: 2,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 267,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the absolute contraindications for noninvasive ventilation?',
    answer: 'Absolute contraindications include cardiac or respiratory arrest, inability to protect the airway, excessive secretions that cannot be cleared, uncooperative or agitated patient unable to tolerate the mask, hemodynamic instability requiring vasopressors, facial trauma or surgery preventing mask fit, and upper airway obstruction.',
    difficulty: 2,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 268,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What types of interfaces are used for noninvasive ventilation?',
    answer: 'Common interfaces include nasal masks (cover the nose only, more comfortable but allow mouth leak), oronasal masks (cover nose and mouth, preferred for acute respiratory failure), full-face masks (cover the entire face, minimize leak but increase claustrophobia risk), and nasal pillows (sit at nares, used mainly for OSA). Proper sizing and fit are critical.',
    difficulty: 1,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 269,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are typical initial BiPAP settings for a COPD exacerbation with hypercapnic respiratory failure?',
    answer: 'Start with IPAP of 8-12 cmH2O and EPAP of 4-5 cmH2O, then titrate IPAP upward by 2 cmH2O every 5-10 minutes to achieve adequate tidal volume, reduced respiratory rate, and improved comfort. The IPAP-EPAP difference (pressure support) drives ventilation and CO2 clearance. Maximum IPAP is typically 20-25 cmH2O.',
    difficulty: 2,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 270,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What CPAP level is typically used for obstructive sleep apnea?',
    answer: 'CPAP for obstructive sleep apnea is titrated during a sleep study, typically ranging from 5-20 cmH2O. The optimal pressure is the lowest level that eliminates apneas, hypopneas, snoring, and oxygen desaturations across all sleep stages and body positions. Auto-titrating CPAP devices can adjust pressure in real time within a set range.',
    difficulty: 1,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 271,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does CPAP benefit a patient with acute cardiogenic pulmonary edema?',
    answer: 'CPAP increases intrathoracic pressure, which reduces venous return (preload) and decreases left ventricular transmural pressure (afterload), improving cardiac output in the failing heart. It also recruits flooded alveoli, improves oxygenation, and reduces the work of breathing. Studies show CPAP at 10-12 cmH2O reduces the need for intubation.',
    difficulty: 3,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 272,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are signs that noninvasive ventilation is failing and intubation should be considered?',
    answer: 'Signs of NIV failure include worsening or unchanged ABG values after 1-2 hours of therapy, persistent tachypnea and accessory muscle use, inability to tolerate the mask, declining level of consciousness, hemodynamic instability, worsening hypoxemia, and inability to manage secretions. Early recognition and timely intubation improve outcomes.',
    difficulty: 2,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 273,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What complications can occur from noninvasive ventilation?',
    answer: 'Common complications include skin breakdown and pressure ulcers on the nasal bridge, air leaks around the mask, aerophagia (gastric distension from swallowed air), eye irritation from mask leak, claustrophobia, nasal congestion and dryness, aspiration risk, and rarely pneumothorax from excessive pressure.',
    difficulty: 1,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 274,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How should mask leak be managed during noninvasive ventilation?',
    answer: 'Adjust the mask straps to achieve a proper seal without overtightening (which can cause pressure injury). Ensure correct mask size, try a different mask style if needed, and apply barrier dressings on pressure points. Some leak is acceptable on bilevel devices with leak-compensating algorithms, but excessive leak reduces the delivered pressure support.',
    difficulty: 3,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 275,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the role of heated humidification during noninvasive ventilation?',
    answer: 'Heated humidification prevents drying of the nasal and oral mucosa from the high flow of dry gas, which improves patient comfort and adherence. It is particularly important for patients using NIV for extended periods, those with mouth leaks on nasal CPAP, and when supplemental oxygen is blended into the circuit.',
    difficulty: 2,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 276,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between spontaneous and spontaneous/timed (S/T) mode on BiPAP?',
    answer: 'In spontaneous mode, the device only delivers breaths triggered by the patient. In S/T mode, a backup respiratory rate is set so that if the patient does not trigger a breath within the set interval, the device delivers a mandatory breath. S/T mode is preferred for patients at risk of apnea or with unreliable respiratory drive.',
    difficulty: 2,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 277,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is noninvasive ventilation used to facilitate weaning from invasive mechanical ventilation?',
    answer: 'In select COPD patients who fail spontaneous breathing trials, early extubation to NIV can reduce total ventilator days, lower VAP risk, and decrease ICU and hospital length of stay. The patient should have adequate cough, manageable secretions, and hemodynamic stability before attempting this transition.',
    difficulty: 3,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 278,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is average volume-assured pressure support (AVAPS) on a bilevel device?',
    answer: 'AVAPS automatically adjusts the IPAP between a minimum and maximum setting to achieve a target tidal volume. This ensures consistent ventilation despite changes in patient effort, respiratory mechanics, or body position. It is useful for patients with neuromuscular disease or obesity hypoventilation syndrome where ventilatory needs may vary.',
    difficulty: 3,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 279,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is high-flow nasal cannula (HFNC) therapy and how does it differ from traditional NIV?',
    answer: 'HFNC delivers heated, humidified oxygen at flow rates up to 60 L/min through large-bore nasal prongs. Unlike traditional NIV, it does not require a sealed mask and generates only modest positive pressure (2-5 cmH2O). It washes out nasopharyngeal dead space, reduces work of breathing, and is better tolerated for prolonged use.',
    difficulty: 2,
    topic: 'Noninvasive Ventilation',
    isFree: false,
    orderIndex: 280,
  },

  // ============================================================
  // RESPIRATORY CALCULATIONS (cards 281-295)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the alveolar air equation and how is it used?',
    answer: 'The alveolar air equation is PAO2 = FiO2(Pb - PH2O) - (PaCO2 / RQ). At sea level on room air: PAO2 = 0.21(760 - 47) - (PaCO2 / 0.8). It calculates the ideal alveolar oxygen tension and is used to determine the A-a gradient, which helps identify the cause of hypoxemia.',
    difficulty: 2,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 281,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the A-a gradient and what is a normal value?',
    answer: 'The A-a gradient (P(A-a)O2) is the difference between alveolar oxygen (PAO2) and arterial oxygen (PaO2). A normal value for a young adult on room air is 5-15 mmHg. An elevated A-a gradient suggests V/Q mismatch, shunt, or diffusion impairment. A normal A-a gradient with hypoxemia points to hypoventilation as the cause.',
    difficulty: 1,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 282,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is static compliance calculated and what is the normal value?',
    answer: 'Static compliance (Cst) = Tidal Volume / (Plateau Pressure - PEEP). Normal static compliance is 60-100 mL/cmH2O. Decreased static compliance indicates stiff lungs or chest wall (ARDS, pulmonary fibrosis, pneumonia, pulmonary edema). It specifically measures lung and chest wall distensibility without the influence of airway resistance.',
    difficulty: 2,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 283,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is dynamic compliance calculated and how does it differ from static compliance?',
    answer: 'Dynamic compliance (Cdyn) = Tidal Volume / (Peak Inspiratory Pressure - PEEP). Normal is 50-80 mL/cmH2O. Unlike static compliance, dynamic compliance is affected by both airway resistance and lung compliance because PIP includes the resistive component. A drop in Cdyn with unchanged Cst suggests increased airway resistance (bronchospasm, secretions, kinked tube).',
    difficulty: 3,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 284,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is airway resistance calculated on a mechanically ventilated patient?',
    answer: 'Airway resistance (Raw) = (PIP - Plateau Pressure) / Flow. Normal airway resistance is 0.5-2.5 cmH2O/L/sec. Elevated resistance is caused by bronchospasm, secretions, mucosal edema, or a narrow or kinked endotracheal tube. The difference between PIP and plateau pressure isolates the resistive component.',
    difficulty: 2,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 285,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is minute ventilation calculated and what is the normal value?',
    answer: 'Minute ventilation (VE) = Tidal Volume x Respiratory Rate. Normal minute ventilation is approximately 5-10 L/min. It represents the total volume of gas moved in and out of the lungs per minute. Increased minute ventilation is required in states of increased CO2 production such as fever, sepsis, or high carbohydrate intake.',
    difficulty: 1,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 286,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is alveolar ventilation calculated?',
    answer: 'Alveolar ventilation (VA) = (Tidal Volume - Dead Space Volume) x Respiratory Rate. It represents the volume of gas per minute that actually participates in gas exchange. Since anatomic dead space is approximately 1 mL/lb of ideal body weight, shallow rapid breathing decreases alveolar ventilation even if minute ventilation remains constant.',
    difficulty: 2,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 287,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is the I:E ratio calculated from ventilator settings?',
    answer: 'I:E ratio is calculated by dividing total cycle time by inspiratory time to find the ratio. Total cycle time = 60 / respiratory rate. For example, at a rate of 15 and inspiratory time of 1 second: cycle time is 4 seconds, expiratory time is 3 seconds, giving an I:E ratio of 1:3. An I:E ratio shorter than 1:2 may cause air trapping in obstructive disease.',
    difficulty: 3,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 288,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is the PaO2/FiO2 (P/F) ratio used to assess oxygenation?',
    answer: 'The P/F ratio is calculated by dividing PaO2 by FiO2 (as a decimal). A normal P/F ratio is 400-500. A P/F ratio below 300 indicates acute lung injury, and below 200 indicates severe ARDS by the Berlin criteria. For example, a PaO2 of 80 on an FiO2 of 0.40 yields a P/F ratio of 200.',
    difficulty: 1,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 289,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is the Bohr equation used to calculate dead space?',
    answer: 'The Bohr equation calculates dead space fraction: VD/VT = (PaCO2 - PECO2) / PaCO2. Normal VD/VT is 0.20-0.40 (dead space is 20-40% of tidal volume). An increased VD/VT ratio indicates wasted ventilation due to pulmonary embolism, low cardiac output, or excessive PEEP redistributing blood flow away from ventilated areas.',
    difficulty: 3,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 290,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is the classic shunt equation used and what is a normal shunt fraction?',
    answer: 'The shunt equation is Qs/Qt = (CcO2 - CaO2) / (CcO2 - CvO2), where CcO2 is pulmonary capillary oxygen content, CaO2 is arterial, and CvO2 is mixed venous. Normal shunt fraction is less than 5%. A shunt above 30% typically requires mechanical ventilation. Shunt does not respond to supplemental oxygen because blood bypasses ventilated alveoli.',
    difficulty: 3,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 291,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is oxygen content (CaO2) calculated?',
    answer: 'CaO2 = (Hb x 1.34 x SaO2) + (PaO2 x 0.003). The first term represents oxygen bound to hemoglobin (the major component), and the second term is dissolved oxygen. Normal CaO2 is approximately 18-20 mL O2/dL. This calculation demonstrates why hemoglobin level is critical for oxygen delivery, not just PaO2.',
    difficulty: 2,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 292,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is oxygen delivery (DO2) calculated and what is the normal value?',
    answer: 'DO2 = CaO2 x Cardiac Output x 10. Normal oxygen delivery is approximately 900-1100 mL O2/min. This demonstrates that oxygen delivery depends on three factors: hemoglobin concentration, oxygen saturation, and cardiac output. Optimizing all three components is essential in critically ill patients with tissue hypoxia.',
    difficulty: 2,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 293,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is ideal body weight (IBW) calculated and why is it important for ventilator settings?',
    answer: 'IBW for males = 50 + 2.3(height in inches - 60); for females = 45.5 + 2.3(height in inches - 60). Tidal volume should be based on IBW, not actual weight, because lung size correlates with height, not body mass. Using actual weight in obese patients leads to dangerously high tidal volumes and barotrauma risk.',
    difficulty: 1,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 294,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is the rapid shallow breathing index (RSBI) calculated and what does it predict?',
    answer: 'RSBI = Respiratory Rate / Tidal Volume (in liters), measured during spontaneous breathing. An RSBI below 105 breaths/min/L predicts successful extubation, while above 105 suggests likely weaning failure. For example, a patient breathing 24 times per minute with a tidal volume of 0.35 L has an RSBI of 69, which is favorable.',
    difficulty: 2,
    topic: 'Respiratory Calculations',
    isFree: false,
    orderIndex: 295,
  },

  // ============================================================
  // ETHICS, SAFETY & QUALITY (cards 296-300)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does HIPAA require regarding patient respiratory care information?',
    answer: 'HIPAA requires that all protected health information (PHI), including diagnoses, treatments, and test results, be kept confidential and shared only with authorized individuals involved in the patient care. Information should be discussed in private areas, and electronic records must be secured with access controls and audit trails.',
    difficulty: 1,
    topic: 'Ethics, Safety & Quality',
    isFree: false,
    orderIndex: 296,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is informed consent and when is it required in respiratory care?',
    answer: 'Informed consent requires explaining the procedure, its risks, benefits, alternatives, and potential consequences of refusal in terms the patient can understand. The patient must voluntarily agree before invasive procedures such as arterial line insertion, bronchoscopy, or tracheostomy. Verbal consent may suffice for routine treatments like nebulizers.',
    difficulty: 2,
    topic: 'Ethics, Safety & Quality',
    isFree: false,
    orderIndex: 297,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are sentinel events and how should they be reported in respiratory care?',
    answer: 'Sentinel events are unexpected occurrences involving death or serious physical or psychological injury. Examples in respiratory care include unplanned extubation resulting in death, wrong-patient ventilator disconnection, or air administered into an arterial line. They must be reported through the facility event reporting system and investigated with root cause analysis.',
    difficulty: 2,
    topic: 'Ethics, Safety & Quality',
    isFree: false,
    orderIndex: 298,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is evidence-based practice in respiratory therapy?',
    answer: 'Evidence-based practice integrates the best available research evidence with clinical expertise and patient values to guide clinical decisions. It involves formulating clinical questions, searching the literature, critically appraising studies, applying findings to practice, and evaluating outcomes. Clinical practice guidelines from organizations like the AARC are based on this approach.',
    difficulty: 2,
    topic: 'Ethics, Safety & Quality',
    isFree: false,
    orderIndex: 299,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the Plan-Do-Study-Act (PDSA) cycle in quality improvement?',
    answer: 'The PDSA cycle is a systematic method for continuous quality improvement. Plan identifies a change to test, Do implements the change on a small scale, Study analyzes the results against predictions, and Act either adopts, adapts, or abandons the change based on findings. It is used in respiratory departments to improve protocols such as ventilator weaning and bronchodilator utilization.',
    difficulty: 2,
    topic: 'Ethics, Safety & Quality',
    isFree: false,
    orderIndex: 300,
  },
];

async function main() {
  console.log('Starting TMC Batch 3 seed (cards 201-300)...');
  console.log(`Total flashcards to insert: ${flashcards.length}`);

  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  });

  console.log(`Successfully inserted ${result.count} flashcards.`);
  console.log('TMC Batch 3 seeding complete.');
}

main()
  .catch((e) => {
    console.error('Error seeding TMC Batch 3:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
