import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const cards = [
  // ============================================================
  // ACID-BASE MIXED DISORDERS & COMPENSATION (401-415)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What defines a mixed acid-base disorder?',
    answer: 'A mixed acid-base disorder occurs when two or more primary acid-base disturbances are present simultaneously. Unlike simple disorders where one primary disturbance triggers a predictable compensatory response, mixed disorders involve independent pathological processes that may either worsen or partially offset each other.',
    difficulty: 2,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 401,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is Winter\'s formula used to detect a mixed acid-base disorder?',
    answer: 'Winter\'s formula predicts the expected PaCO2 in a primary metabolic acidosis: expected PaCO2 = (1.5 × HCO3) + 8 ± 2. If the measured PaCO2 is higher than expected, a concurrent respiratory acidosis is present. If the measured PaCO2 is lower than expected, a concurrent respiratory alkalosis exists.',
    difficulty: 3,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 402,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the delta-delta ratio and how is it interpreted?',
    answer: 'The delta-delta ratio compares the change in anion gap (delta AG) to the change in bicarbonate (delta HCO3): delta ratio = (AG − 12) / (24 − HCO3). A ratio less than 1 suggests a concurrent non-anion-gap metabolic acidosis. A ratio greater than 2 suggests a concurrent metabolic alkalosis. A ratio between 1 and 2 indicates a pure anion gap metabolic acidosis.',
    difficulty: 4,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 403,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How do you calculate the corrected anion gap for hypoalbuminemia?',
    answer: 'The corrected anion gap adjusts for low albumin levels using the formula: corrected AG = calculated AG + 2.5 × (4.0 − measured albumin in g/dL). Each 1 g/dL decrease in albumin below 4.0 reduces the anion gap by approximately 2.5 mEq/L, potentially masking an elevated anion gap acidosis.',
    difficulty: 4,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 404,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the three most common causes of elevated anion gap metabolic acidosis?',
    answer: 'The three most common causes are lactic acidosis from tissue hypoxia or sepsis, diabetic ketoacidosis from uncontrolled diabetes, and renal failure with uremic acid accumulation. The mnemonic MUDPILES (Methanol, Uremia, DKA, Propylene glycol, Isoniazid/Iron, Lactic acidosis, Ethylene glycol, Salicylates) covers the broader differential.',
    difficulty: 2,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 405,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the primary causes of metabolic alkalosis in hospitalized patients?',
    answer: 'The most common causes include prolonged nasogastric suction or vomiting (loss of HCl), aggressive diuretic therapy (contraction alkalosis), excessive bicarbonate administration, and hypokalemia. Metabolic alkalosis is maintained by renal bicarbonate retention, often driven by volume depletion and chloride deficiency.',
    difficulty: 2,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 406,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is chloride-responsive metabolic alkalosis distinguished from chloride-resistant metabolic alkalosis?',
    answer: 'Chloride-responsive metabolic alkalosis has urine chloride less than 20 mEq/L and responds to saline infusion; causes include vomiting, NG suction, and diuretics (after discontinuation). Chloride-resistant metabolic alkalosis has urine chloride greater than 20 mEq/L and does not respond to volume repletion; causes include hyperaldosteronism, Cushing syndrome, and severe hypokalemia.',
    difficulty: 4,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 407,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'A patient has pH 7.22, PaCO2 60 mmHg, HCO3 24 mEq/L. What acid-base disorder is present?',
    answer: 'This is an acute respiratory acidosis. The pH is acidemic, PaCO2 is elevated indicating the primary respiratory component, and HCO3 is normal at 24 mEq/L showing no metabolic compensation has occurred yet. In acute respiratory acidosis, HCO3 rises only about 1 mEq/L for each 10 mmHg rise in PaCO2 via tissue buffering.',
    difficulty: 3,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 408,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'A patient has pH 7.35, PaCO2 60 mmHg, HCO3 33 mEq/L. What acid-base disorder is present?',
    answer: 'This represents a chronic (compensated) respiratory acidosis. The elevated PaCO2 of 60 mmHg is the primary disturbance, and the kidneys have compensated by retaining bicarbonate to 33 mEq/L. In chronic respiratory acidosis, HCO3 rises approximately 3.5 mEq/L for each 10 mmHg increase in PaCO2, bringing the pH close to normal.',
    difficulty: 3,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 409,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'A patient with COPD on a ventilator has pH 7.48, PaCO2 30 mmHg, HCO3 28 mEq/L. What mixed disorder is present?',
    answer: 'This is a mixed respiratory alkalosis and metabolic alkalosis. The low PaCO2 indicates respiratory alkalosis (likely from overventilation), and the elevated HCO3 of 28 mEq/L is inappropriately high for respiratory alkalosis compensation (which lowers HCO3). The chronically elevated bicarbonate from prior COPD compensation combined with iatrogenic hyperventilation creates this mixed pattern.',
    difficulty: 4,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 410,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the expected compensation for a primary metabolic alkalosis?',
    answer: 'In metabolic alkalosis, the respiratory system compensates by decreasing ventilation to retain CO2. The expected PaCO2 rises approximately 0.7 mmHg for each 1 mEq/L increase in HCO3 above normal. However, respiratory compensation for metabolic alkalosis is limited because hypoventilation causes hypoxemia, which stimulates the peripheral chemoreceptors; PaCO2 rarely exceeds 55 mmHg as compensation.',
    difficulty: 3,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 411,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the expected compensation for an acute respiratory alkalosis?',
    answer: 'In acute respiratory alkalosis, bicarbonate decreases approximately 2 mEq/L for each 10 mmHg decrease in PaCO2 below 40 mmHg. This initial compensation occurs through cellular buffering mechanisms, primarily the shift of hydrogen ions from intracellular stores in exchange for bicarbonate. The HCO3 typically does not fall below 18 mEq/L from acute compensation alone.',
    difficulty: 3,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 412,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'A DKA patient has pH 7.10, PaCO2 15 mmHg, HCO3 5 mEq/L, Na 140, Cl 105. Calculate the anion gap and assess for mixed disorder.',
    answer: 'Anion gap = 140 − (105 + 5) = 30 mEq/L (elevated, normal 8-12). Delta AG = 30 − 12 = 18. Delta HCO3 = 24 − 5 = 19. Delta-delta ratio = 18/19 ≈ 0.95. Since the ratio is less than 1, a concurrent non-anion-gap metabolic acidosis is present along with the anion gap metabolic acidosis from DKA. Winter\'s expected PaCO2 = (1.5 × 5) + 8 ± 2 = 13.5-17.5, and measured PaCO2 of 15 is within range, so respiratory compensation is appropriate.',
    difficulty: 5,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 413,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the osmolar gap and when is it clinically useful in acid-base assessment?',
    answer: 'The osmolar gap is the difference between measured serum osmolality and calculated osmolality (2×Na + glucose/18 + BUN/2.8). A gap greater than 10 mOsm/kg suggests the presence of unmeasured osmotically active substances. It is particularly useful when evaluating anion gap metabolic acidosis for toxic alcohol ingestion such as methanol or ethylene glycol, where the osmolar gap is elevated early before the anion gap rises.',
    difficulty: 4,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 414,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a triple acid-base disorder and give a clinical example?',
    answer: 'A triple acid-base disorder occurs when three primary acid-base disturbances coexist. A classic example is a patient with COPD exacerbation (chronic respiratory acidosis) who develops sepsis with lactic acidosis (anion gap metabolic acidosis) and has been vomiting (metabolic alkalosis). Identifying triple disorders requires systematic analysis of the anion gap, delta-delta ratio, and expected compensations.',
    difficulty: 5,
    topic: 'Acid-Base Mixed Disorders & Compensation',
    isFree: false,
    orderIndex: 415,
  },
  // ============================================================
  // CHEST RADIOGRAPH INTERPRETATION (416-430)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the systematic approach for evaluating a chest radiograph in respiratory care?',
    answer: 'A systematic approach uses the ABCDEFGH mnemonic: Airway (trachea position, ETT placement), Bones (ribs, clavicles, spine), Cardiac silhouette (size, shape), Diaphragm (position, costophrenic angles), Effusion/Extra-pulmonary (pleural space), Fields (lung parenchyma), Gastric bubble, and Hilum (vascularity). Consistency in approach prevents overlooking findings.',
    difficulty: 1,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 416,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Where should the tip of an endotracheal tube be positioned on a chest radiograph?',
    answer: 'The ETT tip should be positioned 3-5 cm above the carina on a chest radiograph, typically at the level of the T3-T4 vertebral bodies with the head in neutral position. If the tip is too low, it may enter the right mainstem bronchus. Head flexion advances the tube approximately 2 cm, and extension withdraws it approximately 2 cm.',
    difficulty: 2,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 417,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is cardiomegaly assessed on a PA chest radiograph?',
    answer: 'Cardiomegaly is assessed using the cardiothoracic ratio (CTR), which compares the maximal transverse diameter of the heart to the maximal internal thoracic diameter. A CTR greater than 0.50 (50%) on a PA film indicates cardiomegaly. AP films artificially magnify the cardiac silhouette and should not be used to assess heart size reliably.',
    difficulty: 2,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 418,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the radiographic signs of a tension pneumothorax?',
    answer: 'Tension pneumothorax shows a visceral pleural line with absent lung markings beyond it, mediastinal shift away from the affected side, depression (flattening) of the ipsilateral hemidiaphragm, and widening of the intercostal spaces. The contralateral lung may show compression. However, tension pneumothorax is a clinical diagnosis and treatment should not be delayed for imaging.',
    difficulty: 3,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 419,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does a pleural effusion appear on an upright chest radiograph?',
    answer: 'On an upright CXR, pleural effusion appears as a homogeneous opacification at the lung base with a meniscus sign, a concave upward curve at the lateral chest wall. At least 200-300 mL of fluid must accumulate to blunt the posterior costophrenic angle on a lateral film, and about 500 mL to blunt the lateral costophrenic angle on a PA film.',
    difficulty: 2,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 420,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the silhouette sign on a chest radiograph and what does it indicate?',
    answer: 'The silhouette sign occurs when an intrathoracic opacity is in direct contact with a border of the heart, aorta, or diaphragm, causing that border to be obscured. It helps localize pathology: loss of the right heart border suggests right middle lobe disease, loss of the left heart border suggests lingular disease, and loss of the hemidiaphragm suggests lower lobe disease.',
    difficulty: 3,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 421,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the radiographic differences between lobar consolidation and atelectasis?',
    answer: 'Lobar consolidation shows air bronchograms within opacified lung parenchyma with maintained or slightly increased lung volume and no mediastinal shift. Atelectasis shows volume loss with displacement of fissures toward the collapsed lobe, ipsilateral mediastinal shift, elevation of the hemidiaphragm, and compensatory hyperinflation of adjacent lobes. Air bronchograms may be absent in obstructive atelectasis.',
    difficulty: 3,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 422,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What radiographic pattern is characteristic of pulmonary edema from heart failure?',
    answer: 'Cardiogenic pulmonary edema classically shows cephalization of pulmonary vasculature (upper lobe vessel dilation), bilateral perihilar "butterfly" or "bat-wing" opacities, Kerley B lines (short horizontal lines at the lung periphery representing thickened interlobular septa), peribronchial cuffing, and bilateral pleural effusions. The heart is typically enlarged.',
    difficulty: 2,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 423,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does ARDS appear on a chest radiograph and how does it differ from cardiogenic pulmonary edema?',
    answer: 'ARDS shows bilateral, diffuse, non-cardiogenic pulmonary opacities that are typically more peripheral and uniform. Unlike cardiogenic edema, ARDS shows a normal cardiac silhouette, absence of cephalization, no Kerley B lines, and absence of or minimal pleural effusions. Air bronchograms are frequently present within the opacified lung regions.',
    difficulty: 3,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 424,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the air bronchogram sign and what does it indicate?',
    answer: 'An air bronchogram is the visualization of air-filled bronchi within opacified (consolidated) lung parenchyma. It indicates that the surrounding alveoli are filled with fluid, pus, blood, or cells while the airways remain patent. Air bronchograms are seen in pneumonia, pulmonary edema, ARDS, and non-obstructive atelectasis, but are absent in pleural effusion and obstructive atelectasis.',
    difficulty: 2,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 425,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is proper central venous catheter (CVC) placement verified on a chest radiograph?',
    answer: 'The tip of a central venous catheter should be positioned at the junction of the superior vena cava and the right atrium, which corresponds to the level of the carina on a chest radiograph. The catheter should follow the expected course of the vein used for insertion. The CXR should also be checked for complications such as pneumothorax, hemothorax, or catheter malposition into the internal jugular or contralateral subclavian vein.',
    difficulty: 2,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 426,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the radiographic signs of right middle lobe atelectasis?',
    answer: 'Right middle lobe atelectasis on a PA film shows a vague opacity projecting over the right heart border, obscuring the right heart border (positive silhouette sign). On a lateral film, a triangular wedge-shaped opacity is seen with the apex pointing toward the hilum bounded by the minor fissure superiorly and the major fissure inferiorly. Volume loss may be subtle on the PA view.',
    difficulty: 4,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 427,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between an AP and PA chest radiograph and why does it matter?',
    answer: 'In a PA (posteroanterior) film, the x-ray beam enters the patient\'s back and exits the chest, placing the heart close to the film for accurate size representation. In an AP (anteroposterior) film, the beam enters the front, magnifying the cardiac silhouette by 15-20% because the heart is farther from the film. AP films are taken on portable units for critically ill patients and are less ideal for cardiac size assessment.',
    difficulty: 1,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 428,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What radiographic findings suggest a right mainstem intubation?',
    answer: 'Right mainstem intubation is suggested when the ETT tip is below the carina, the left lung shows atelectasis or volume loss with ipsilateral mediastinal shift, and the right lung may show hyperinflation. The left hemidiaphragm may be elevated. Auscultation confirms absent or diminished breath sounds on the left. The tube should be withdrawn until the tip is 3-5 cm above the carina.',
    difficulty: 2,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 429,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a deep sulcus sign on a supine chest radiograph?',
    answer: 'The deep sulcus sign is a radiographic indicator of pneumothorax on a supine film. Air collects in the anterior and inferior pleural space, producing an abnormally deep, lucent costophrenic angle on the affected side. The lateral costophrenic sulcus appears deeper and more radiolucent than normal. This sign is important because supine films cannot show the classic apical pneumothorax finding seen on upright films.',
    difficulty: 4,
    topic: 'Chest Radiograph Interpretation',
    isFree: false,
    orderIndex: 430,
  },
  // ============================================================
  // VENTILATOR WAVEFORM ANALYSIS (431-445)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the three primary ventilator waveforms monitored during mechanical ventilation?',
    answer: 'The three primary waveforms are pressure-time, flow-time, and volume-time scalars. The pressure-time waveform displays airway pressure changes during the respiratory cycle. The flow-time waveform shows inspiratory and expiratory gas flow patterns. The volume-time waveform displays tidal volume delivery and return during each breath.',
    difficulty: 1,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 431,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is auto-PEEP (intrinsic PEEP) detected on ventilator waveforms?',
    answer: 'Auto-PEEP is detected on the flow-time waveform when expiratory flow does not return to baseline (zero) before the next inspiration begins. This indicates that the previous exhalation was incomplete and gas trapping is occurring. Auto-PEEP can be measured using an expiratory hold maneuver, which displays the total PEEP minus the set (extrinsic) PEEP.',
    difficulty: 3,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 432,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does a "shark fin" or upward-sloping pressure waveform during volume-controlled ventilation indicate?',
    answer: 'A shark fin or progressively rising pressure waveform during volume-controlled ventilation with a constant (square) flow pattern indicates increased airway resistance, such as bronchospasm, mucus plugging, or a kinked endotracheal tube. The normal pressure waveform should show a relatively linear rise; the concave upward shape reflects the increased pressure needed to deliver gas through narrowed airways.',
    difficulty: 3,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 433,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the significance of a pressure overshoot or "ringing" at end-inspiration on the pressure-time waveform?',
    answer: 'A pressure overshoot at end-inspiration in volume-controlled ventilation indicates that inspiratory flow is exceeding what the patient needs, often due to excessive flow rate or an inappropriately short inspiratory time. The spike above plateau pressure is caused by the abrupt cessation of high-velocity gas flow. Decreasing the peak flow rate or using a decelerating flow pattern can eliminate this overshoot.',
    difficulty: 3,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 434,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does flow starvation appear on ventilator waveforms and what does it indicate?',
    answer: 'Flow starvation appears as a concave "scooping" or dip in the pressure-time waveform during inspiration in volume-controlled ventilation, where the pressure dips below the expected trajectory. On the flow-time waveform, the set flow may appear insufficient with the patient\'s effort causing flow irregularity. It indicates the delivered flow is inadequate for the patient\'s inspiratory demand, causing increased work of breathing.',
    difficulty: 3,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 435,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between peak inspiratory pressure (PIP) and plateau pressure (Pplat) and what does each reflect?',
    answer: 'PIP is the maximum pressure reached during inspiration and reflects both airway resistance and lung compliance. Pplat is measured during an end-inspiratory hold when flow is zero and reflects only static lung-thorax compliance (elastic recoil). The difference between PIP and Pplat represents the resistive pressure component. An elevated PIP with normal Pplat suggests airway resistance problems, while both elevated suggests decreased compliance.',
    difficulty: 2,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 436,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is overdistension and how is it identified on a pressure-volume loop?',
    answer: 'Overdistension occurs when tidal volume exceeds the upper inflection point of the pressure-volume curve, causing alveolar overstretch. On the dynamic pressure-volume loop, overdistension appears as a "beak" or "penguin beak" shape at the top of the inspiratory limb, where a large increase in pressure produces a diminishing change in volume. This indicates that further volume delivery risks ventilator-induced lung injury.',
    difficulty: 4,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 437,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the lower and upper inflection points on a static pressure-volume curve?',
    answer: 'The lower inflection point (LIP) represents the pressure at which collapsed alveoli begin to recruit and compliance improves, historically used to set optimal PEEP just above this point. The upper inflection point (UIP) represents the pressure at which alveoli become overdistended and compliance decreases. Tidal ventilation ideally occurs between these two points to minimize atelectrauma and volutrauma.',
    difficulty: 4,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 438,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is trigger asynchrony and how does it appear on ventilator waveforms?',
    answer: 'Trigger asynchrony occurs when there is a mismatch between the patient\'s inspiratory effort and ventilator breath delivery. On waveforms, ineffective triggering appears as negative deflections in the pressure-time waveform and corresponding small flow changes on the flow-time waveform that do not trigger a ventilator breath. Delayed triggering shows a prolonged time between the pressure drop and flow delivery.',
    difficulty: 3,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 439,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is double triggering and what causes it?',
    answer: 'Double triggering occurs when the ventilator delivers two consecutive breaths for a single patient effort, appearing as two breaths without adequate exhalation time between them. It is caused by a set inspiratory time that is shorter than the patient\'s neural inspiratory time, so the patient\'s ongoing effort triggers a second breath immediately. Increasing inspiratory time or tidal volume, or adjusting cycle criteria, can resolve it.',
    difficulty: 3,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 440,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does the flow-time waveform differ between constant (square) and decelerating flow patterns?',
    answer: 'A constant (square) flow pattern maintains the same flow rate throughout inspiration, producing a rectangular shape on the flow-time waveform and a linearly rising pressure waveform. A decelerating flow pattern starts at peak flow and progressively decreases to near zero, creating a triangular or ramp-down shape. Decelerating flow generally improves gas distribution, lowers peak airway pressure, and enhances patient comfort.',
    difficulty: 2,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 441,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is reverse triggering and how is it identified on ventilator waveforms?',
    answer: 'Reverse triggering is a form of asynchrony where a mandatory ventilator breath stimulates the patient\'s respiratory center, causing a diaphragmatic contraction during or after the machine breath. On waveforms, it appears as a second negative pressure deflection or a secondary flow distortion during the exhalation phase of a mandatory breath, potentially causing breath stacking or double triggering.',
    difficulty: 5,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 442,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does a flow-volume loop look like during bronchospasm?',
    answer: 'During bronchospasm, the expiratory limb of the flow-volume loop shows a characteristic concave or "scooped out" appearance. Peak expiratory flow may be reduced, and the expiratory flow rate decreases more rapidly than normal with a prolonged tail. The inspiratory limb may be relatively preserved. After bronchodilator therapy, the expiratory limb should become more convex and approach normal shape.',
    difficulty: 3,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 443,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does a leak appear on ventilator waveforms?',
    answer: 'A circuit leak appears on the volume-time waveform as a difference between inspired and expired tidal volumes, with the expiratory volume not returning to baseline. On the flow-time waveform, expiratory flow may not return to zero. On the pressure-time waveform, the baseline pressure may be lower than set PEEP. Leaks can occur at ETT cuff, circuit connections, chest tube sites, or bronchopleural fistulas.',
    difficulty: 2,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 444,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is premature cycling and how does it appear on ventilator waveforms?',
    answer: 'Premature cycling occurs in pressure support ventilation when the ventilator terminates inspiratory flow before the patient\'s neural inspiration is complete. On the flow-time waveform, the expiratory flow shows an abrupt spike at the onset of exhalation. On the pressure-time waveform, there may be a sudden drop followed by a secondary negative deflection as the patient continues to inspire against a closed valve. Lowering the flow cycle criterion (e.g., from 25% to 10% of peak flow) can correct this.',
    difficulty: 4,
    topic: 'Ventilator Waveform Analysis',
    isFree: false,
    orderIndex: 445,
  },
  // ============================================================
  // PULMONARY VASCULAR DISEASE & COR PULMONALE (446-455)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the hemodynamic definition of pulmonary hypertension?',
    answer: 'Pulmonary hypertension is hemodynamically defined as a mean pulmonary artery pressure (mPAP) greater than 20 mmHg at rest, measured by right heart catheterization. Pre-capillary pulmonary hypertension additionally requires a pulmonary vascular resistance (PVR) greater than 2 Wood units and a pulmonary artery wedge pressure (PAWP) of 15 mmHg or less.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease & Cor Pulmonale',
    isFree: false,
    orderIndex: 446,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the five WHO clinical classification groups of pulmonary hypertension?',
    answer: 'Group 1 is pulmonary arterial hypertension (PAH) including idiopathic, heritable, and drug-induced forms. Group 2 is PH due to left heart disease. Group 3 is PH due to lung diseases or hypoxia, including COPD and interstitial lung disease. Group 4 is chronic thromboembolic pulmonary hypertension (CTEPH). Group 5 is PH with unclear or multifactorial mechanisms.',
    difficulty: 3,
    topic: 'Pulmonary Vascular Disease & Cor Pulmonale',
    isFree: false,
    orderIndex: 447,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is cor pulmonale and what are its clinical signs?',
    answer: 'Cor pulmonale is right ventricular hypertrophy and/or dilation resulting from pulmonary hypertension caused by diseases of the lung parenchyma, pulmonary vasculature, or chest wall. Clinical signs include jugular venous distension, peripheral edema, hepatomegaly, a right ventricular heave, a loud pulmonic component of S2, and tricuspid regurgitation murmur. The most common cause is COPD.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease & Cor Pulmonale',
    isFree: false,
    orderIndex: 448,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does chronic hypoxia lead to pulmonary hypertension?',
    answer: 'Chronic hypoxia triggers hypoxic pulmonary vasoconstriction (HPV), which initially serves to divert blood away from poorly ventilated alveoli. With prolonged hypoxia, sustained vasoconstriction leads to vascular remodeling including medial hypertrophy, intimal fibrosis, and eventual obliteration of small pulmonary arterioles. This increases pulmonary vascular resistance permanently, leading to sustained pulmonary hypertension and right ventricular strain.',
    difficulty: 3,
    topic: 'Pulmonary Vascular Disease & Cor Pulmonale',
    isFree: false,
    orderIndex: 449,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the role of supplemental oxygen in treating cor pulmonale from COPD?',
    answer: 'Long-term supplemental oxygen therapy (at least 15 hours per day) is a cornerstone treatment for cor pulmonale secondary to COPD with chronic hypoxemia. Oxygen reduces hypoxic pulmonary vasoconstriction, lowers pulmonary artery pressure, slows the progression of pulmonary hypertension, and has been shown to improve survival in the NOTT and MRC clinical trials.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease & Cor Pulmonale',
    isFree: false,
    orderIndex: 450,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a ventilation-perfusion (V/Q) mismatch and how does it affect gas exchange?',
    answer: 'V/Q mismatch occurs when ventilation and perfusion are not proportionally matched in lung regions. Low V/Q units (perfused but poorly ventilated, as in pneumonia or atelectasis) cause hypoxemia because blood passes through without adequate oxygenation (shunt effect). High V/Q units (ventilated but poorly perfused, as in pulmonary embolism) increase dead space and impair CO2 elimination.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease & Cor Pulmonale',
    isFree: false,
    orderIndex: 451,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the classic signs and symptoms of an acute pulmonary embolism?',
    answer: 'Acute PE presents with sudden-onset dyspnea (most common symptom), pleuritic chest pain, tachycardia, tachypnea, and hypoxemia. A massive PE may cause hemodynamic instability with hypotension, syncope, and right ventricular failure. ABGs typically show respiratory alkalosis with hypoxemia and an elevated A-a gradient. D-dimer is sensitive but not specific, and CT pulmonary angiography is the diagnostic gold standard.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease & Cor Pulmonale',
    isFree: false,
    orderIndex: 452,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What pharmacological agents are used to treat pulmonary arterial hypertension (Group 1)?',
    answer: 'PAH-specific therapies target three pathways: the endothelin pathway (bosentan, ambrisentan, which are endothelin receptor antagonists), the nitric oxide pathway (sildenafil, tadalafil, which are PDE-5 inhibitors; riociguat, a soluble guanylate cyclase stimulator), and the prostacyclin pathway (epoprostenol IV, treprostinil, iloprost inhaled, selexipag oral). Combination therapy using agents from multiple pathways is now standard of care for most PAH patients.',
    difficulty: 4,
    topic: 'Pulmonary Vascular Disease & Cor Pulmonale',
    isFree: false,
    orderIndex: 453,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the role of inhaled nitric oxide in pulmonary hypertension management?',
    answer: 'Inhaled nitric oxide (iNO) is a selective pulmonary vasodilator that reduces pulmonary artery pressure without causing systemic hypotension because it is rapidly inactivated by hemoglobin. It is used primarily in neonates with persistent pulmonary hypertension of the newborn (PPHN) and as a vasoreactivity test during right heart catheterization. Standard dosing is 20 ppm, and it must be weaned gradually to prevent rebound pulmonary hypertension.',
    difficulty: 3,
    topic: 'Pulmonary Vascular Disease & Cor Pulmonale',
    isFree: false,
    orderIndex: 454,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is chronic thromboembolic pulmonary hypertension (CTEPH) and how is it treated?',
    answer: 'CTEPH (WHO Group 4) develops when organized thromboembolic material in the pulmonary arteries causes chronic obstruction and vascular remodeling, leading to progressive pulmonary hypertension. It occurs in approximately 2-4% of patients after acute PE. The definitive treatment is pulmonary thromboendarterectomy (PTE), a surgical procedure with potential for cure. For inoperable cases, balloon pulmonary angioplasty and riociguat are treatment options.',
    difficulty: 4,
    topic: 'Pulmonary Vascular Disease & Cor Pulmonale',
    isFree: false,
    orderIndex: 455,
  },
  // ============================================================
  // RESPIRATORY MONITORING TECHNOLOGY (456-470)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does a normal capnography waveform look like and what do its phases represent?',
    answer: 'A normal capnogram has four phases: Phase I is the inspiratory baseline (zero CO2 as dead space gas is exhaled), Phase II is the rapid upstroke (transition from dead space to alveolar gas), Phase III is the alveolar plateau (alveolar gas with relatively constant CO2), and Phase 0 is the sharp inspiratory downstroke back to baseline. The end-tidal CO2 (PETCO2) value is measured at the end of Phase III.',
    difficulty: 2,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 456,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What causes a prolonged or slurred Phase III (alveolar plateau) on a capnogram?',
    answer: 'A prolonged or upsloping Phase III on capnography indicates uneven emptying of lung units with different V/Q ratios, most commonly seen in obstructive airway diseases like COPD and asthma. Slower-emptying alveoli with higher CO2 concentrations contribute later in exhalation, causing the plateau to continuously rise rather than remain flat. This pattern is sometimes called a "shark fin" capnogram in severe obstruction.',
    difficulty: 3,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 457,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does a sudden drop of PETCO2 to zero on capnography indicate?',
    answer: 'A sudden drop of PETCO2 to zero indicates that no CO2 is being detected by the sensor. The most critical cause is esophageal intubation or complete airway disconnection. Other causes include ventilator malfunction, total airway obstruction proximal to the sensor, cardiac arrest with no pulmonary blood flow, or a kinked or obstructed sampling line in a sidestream capnograph.',
    difficulty: 2,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 458,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the clinical limitations of pulse oximetry?',
    answer: 'Pulse oximetry limitations include inability to detect hyperoxia (plateau of the oxyhemoglobin dissociation curve above PaO2 of 80 mmHg), inaccuracy with dyshemoglobins (carboxyhemoglobin and methemoglobin read falsely), poor signal with low perfusion states, motion artifact, and inaccuracy at SpO2 values below 80%. Dark nail polish, skin pigmentation, and ambient light interference can also cause erroneous readings.',
    difficulty: 2,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 459,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does carboxyhemoglobin affect pulse oximetry readings?',
    answer: 'Standard pulse oximeters use two wavelengths of light (660 nm red and 940 nm infrared) and cannot distinguish carboxyhemoglobin (COHb) from oxyhemoglobin. Because COHb absorbs light similarly to oxyhemoglobin at 660 nm, the pulse oximeter falsely reads SpO2 as normal or near-normal despite significant CO poisoning. CO-oximetry using arterial blood is required for accurate assessment, as it uses multiple wavelengths to differentiate hemoglobin species.',
    difficulty: 3,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 460,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is transcutaneous monitoring (PtcO2 and PtcCO2) and when is it used?',
    answer: 'Transcutaneous monitoring uses heated electrodes placed on the skin to measure oxygen and carbon dioxide diffusing through the dermis. The electrode heats the skin to 42-44°C to arterialize capillary blood flow. It is primarily used in neonates where continuous non-invasive monitoring is valuable and skin perfusion is adequate. In adults, accuracy decreases due to thicker skin and hemodynamic instability, and it is used less frequently.',
    difficulty: 3,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 461,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the PaCO2-to-PETCO2 gradient and what does a widened gradient indicate?',
    answer: 'The PaCO2-to-PETCO2 gradient (P(a-et)CO2) is normally 2-5 mmHg, with PaCO2 slightly higher than PETCO2. A widened gradient indicates increased alveolar dead space, where ventilated alveoli are not adequately perfused, as seen in pulmonary embolism, low cardiac output, or overdistension from excessive PEEP. The non-perfused alveoli contribute low-CO2 gas that dilutes the PETCO2 reading.',
    difficulty: 3,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 462,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is exhaled nitric oxide (FeNO) testing and what does it indicate?',
    answer: 'Fractional exhaled nitric oxide (FeNO) is a non-invasive biomarker of eosinophilic airway inflammation. Normal FeNO is less than 25 ppb in adults. Elevated FeNO (greater than 50 ppb) suggests eosinophilic inflammation responsive to corticosteroids, aiding in asthma diagnosis, phenotyping, and monitoring treatment adherence. It helps differentiate eosinophilic asthma from other causes of airway obstruction.',
    difficulty: 3,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 463,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is indirect calorimetry and how is it used in respiratory care?',
    answer: 'Indirect calorimetry measures oxygen consumption (VO2) and carbon dioxide production (VCO2) to calculate resting energy expenditure (REE) and respiratory quotient (RQ). It is used to guide nutritional support in critically ill patients, determine optimal caloric intake, and assess substrate utilization. The measurement requires a steady state and is performed using a metabolic cart connected to the ventilator circuit or a canopy hood.',
    difficulty: 3,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 464,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is dead space fraction (Vd/Vt) calculated and what is its clinical significance?',
    answer: 'Dead space fraction is calculated using the Bohr equation modified by Enghoff: Vd/Vt = (PaCO2 − PECO2) / PaCO2, where PECO2 is the mixed expired CO2 measured from a collection bag. Normal Vd/Vt is 0.20-0.40. Elevated Vd/Vt indicates increased wasted ventilation and is a marker of disease severity in ARDS (greater than 0.60 is associated with increased mortality), pulmonary embolism, and COPD.',
    difficulty: 4,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 465,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is volumetric capnography and how does it differ from time-based capnography?',
    answer: 'Volumetric capnography plots CO2 concentration against exhaled volume rather than time. This allows direct measurement of CO2 elimination per breath, physiologic dead space, and alveolar ventilation. Phase III slope analysis provides information about V/Q heterogeneity. It is more useful than time-based capnography for evaluating ventilation efficiency, optimizing PEEP, and detecting changes in dead space ventilation.',
    difficulty: 4,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 466,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What factors affect the accuracy of a sidestream capnograph compared to mainstream?',
    answer: 'Sidestream capnographs aspirate gas through a sampling tube to a remote sensor, introducing a transport delay of 1-3 seconds and potential errors from water condensation, secretions clogging the sampling line, and dilution at high respiratory rates. Mainstream capnographs place the sensor directly in the airway circuit, providing faster response time and no sampling issues, but they add dead space and weight to the circuit near the patient\'s airway.',
    difficulty: 3,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 467,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does methemoglobinemia affect pulse oximetry readings?',
    answer: 'Methemoglobin absorbs red and infrared light equally, producing a ratio of approximately 1.0, which corresponds to an SpO2 reading of approximately 85%. Regardless of actual oxygen saturation, pulse oximetry in significant methemoglobinemia tends to read around 85%, overestimating when true saturation is low and underestimating when true saturation is high. CO-oximetry is required for accurate assessment.',
    difficulty: 3,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 468,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of an esophageal pressure (Pes) monitoring catheter in mechanical ventilation?',
    answer: 'Esophageal pressure monitoring uses a balloon catheter in the esophagus to estimate pleural pressure. This allows calculation of transpulmonary pressure (airway pressure minus pleural pressure), which reflects the actual distending pressure across the lung. It helps optimize PEEP settings, distinguish between lung and chest wall compliance contributions, assess patient inspiratory effort, and guide ventilation in obese patients or those with elevated abdominal pressures.',
    difficulty: 4,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 469,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does a curare cleft on a capnogram indicate?',
    answer: 'A curare cleft is a notch or dip in Phase III of the capnogram caused by a spontaneous inspiratory effort by the patient during mechanical ventilation exhalation. The patient\'s attempted breath draws in fresh gas with no CO2, creating a brief drop in the waveform. It indicates that neuromuscular blockade is wearing off or that the patient is beginning to breathe spontaneously, and may signal the need for additional paralytic or sedation adjustment.',
    difficulty: 4,
    topic: 'Respiratory Monitoring Technology',
    isFree: false,
    orderIndex: 470,
  },
  // ============================================================
  // BRONCHOSCOPY & ADVANCED AIRWAY PROCEDURES (471-480)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the primary indications for flexible bronchoscopy?',
    answer: 'Flexible bronchoscopy is indicated for evaluation of hemoptysis, persistent cough, or stridor; assessment of airway patency and anatomy; collection of diagnostic specimens (bronchoalveolar lavage, bronchial brushings, transbronchial biopsy); removal of foreign bodies; management of difficult intubations; inspection of endotracheal tube placement; and therapeutic interventions such as stent placement and control of bleeding.',
    difficulty: 2,
    topic: 'Bronchoscopy & Advanced Airway Procedures',
    isFree: false,
    orderIndex: 471,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is bronchoalveolar lavage (BAL) and what information does it provide?',
    answer: 'BAL involves instilling and retrieving sterile saline through a bronchoscope wedged in a segmental or subsegmental bronchus. The recovered fluid is analyzed for cell counts, differential (macrophages, lymphocytes, neutrophils, eosinophils), microbiology cultures, and cytology. BAL is particularly useful for diagnosing opportunistic infections in immunocompromised patients, eosinophilic lung diseases, pulmonary alveolar proteinosis, and diffuse parenchymal lung diseases.',
    difficulty: 3,
    topic: 'Bronchoscopy & Advanced Airway Procedures',
    isFree: false,
    orderIndex: 472,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the role of the respiratory therapist during bronchoscopy?',
    answer: 'The respiratory therapist monitors oxygen saturation and capnography, administers supplemental oxygen or maintains mechanical ventilation through the bronchoscopy adapter, assists with suctioning and specimen collection, monitors hemodynamics and ECG, administers aerosolized lidocaine for topical anesthesia, manages the bronchoscopy swivel adapter on the ETT, and ensures emergency airway equipment is immediately available.',
    difficulty: 2,
    topic: 'Bronchoscopy & Advanced Airway Procedures',
    isFree: false,
    orderIndex: 473,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a transbronchial biopsy and what are its risks?',
    answer: 'Transbronchial biopsy involves passing forceps through the bronchoscope working channel into the lung parenchyma under fluoroscopic guidance to obtain tissue samples. It is used to diagnose diffuse lung diseases, infections, rejection in lung transplant recipients, and peripheral lung lesions. Major risks include pneumothorax (occurring in approximately 1-6% of cases) and hemorrhage, requiring post-procedure chest radiograph and monitoring.',
    difficulty: 3,
    topic: 'Bronchoscopy & Advanced Airway Procedures',
    isFree: false,
    orderIndex: 474,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difficult airway algorithm and when is it activated?',
    answer: 'The difficult airway algorithm, as outlined by the ASA and DAS guidelines, is a structured decision pathway activated when difficulty is anticipated or encountered with face mask ventilation, laryngoscopy, intubation, or any combination thereof. It includes plans for video laryngoscopy, supraglottic airway devices (LMA), bougie-assisted intubation, fiberoptic intubation, and ultimately an emergency surgical airway (cricothyrotomy) as a final rescue step.',
    difficulty: 3,
    topic: 'Bronchoscopy & Advanced Airway Procedures',
    isFree: false,
    orderIndex: 475,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the indications for percutaneous dilational tracheostomy (PDT)?',
    answer: 'PDT is indicated for patients requiring prolonged mechanical ventilation (typically beyond 10-14 days), those who have failed extubation attempts, patients with upper airway obstruction, and those needing long-term airway access for secretion management. Benefits over prolonged translaryngeal intubation include improved patient comfort, facilitation of oral hygiene, reduced laryngeal injury, easier suctioning, and potential for speech with a speaking valve.',
    difficulty: 2,
    topic: 'Bronchoscopy & Advanced Airway Procedures',
    isFree: false,
    orderIndex: 476,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does bronchoscopy-guided foreign body removal differ in adults versus children?',
    answer: 'In adults, flexible bronchoscopy is the primary approach for foreign body removal using basket forceps, grasping forceps, or cryoprobe extraction through the working channel. In children, rigid bronchoscopy under general anesthesia is preferred because it provides a larger working channel, better ventilation control, and the ability to remove larger objects. Organic foreign bodies (nuts, seeds) may require urgent removal due to inflammatory mucosal reaction.',
    difficulty: 3,
    topic: 'Bronchoscopy & Advanced Airway Procedures',
    isFree: false,
    orderIndex: 477,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of a subglottic suction endotracheal tube?',
    answer: 'A subglottic suction ETT has a separate dorsal lumen with a port positioned just above the cuff that allows continuous or intermittent aspiration of secretions pooling above the cuff. This design reduces microaspiration of contaminated oropharyngeal secretions into the lower airways, which is a major mechanism of ventilator-associated pneumonia (VAP). Studies have shown a significant reduction in VAP incidence with subglottic suction tubes.',
    difficulty: 2,
    topic: 'Bronchoscopy & Advanced Airway Procedures',
    isFree: false,
    orderIndex: 478,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of a cuff leak test before extubation?',
    answer: 'The cuff leak test assesses for upper airway edema or obstruction before removing an endotracheal tube. With the cuff deflated, the difference between inspiratory and expiratory tidal volumes is measured. A cuff leak of less than 110 mL (or less than 10-15% of delivered tidal volume) suggests significant laryngeal edema and increased risk of post-extubation stridor. Patients who fail may benefit from systemic corticosteroids before extubation.',
    difficulty: 2,
    topic: 'Bronchoscopy & Advanced Airway Procedures',
    isFree: false,
    orderIndex: 479,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the contraindications to flexible bronchoscopy?',
    answer: 'Absolute contraindications include an uncooperative patient without sedation, severe refractory hypoxemia, and hemodynamic instability. Relative contraindications include uncorrected coagulopathy (platelet count less than 50,000 or INR greater than 1.5 for biopsy), severe pulmonary hypertension, recent myocardial infarction, unstable angina, and superior vena cava obstruction. FiO2 should be increased during the procedure as the bronchoscope partially obstructs the airway.',
    difficulty: 3,
    topic: 'Bronchoscopy & Advanced Airway Procedures',
    isFree: false,
    orderIndex: 480,
  },
  // ============================================================
  // NUTRITION & METABOLISM IN RESPIRATORY CARE (481-490)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the respiratory quotient (RQ) and what do different values indicate?',
    answer: 'The respiratory quotient is the ratio of CO2 produced to O2 consumed (VCO2/VO2). An RQ of 1.0 indicates pure carbohydrate metabolism, 0.8 indicates pure protein metabolism, 0.7 indicates pure fat metabolism, and 0.85 indicates typical mixed substrate utilization. Values greater than 1.0 indicate lipogenesis (net fat synthesis from carbohydrate overfeeding). RQ is measured by indirect calorimetry and guides nutritional planning.',
    difficulty: 3,
    topic: 'Nutrition & Metabolism in Respiratory Care',
    isFree: false,
    orderIndex: 481,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does carbohydrate overfeeding affect respiratory function in ventilated patients?',
    answer: 'Excess carbohydrate calories increase CO2 production because carbohydrate metabolism has a higher RQ (1.0) than fat (0.7) or protein (0.8). The increased VCO2 raises minute ventilation requirements, potentially making ventilator weaning difficult. The RQ rises above 1.0 when lipogenesis occurs. Reducing total calories or shifting the caloric source toward a higher proportion of fat can decrease CO2 production and facilitate weaning.',
    difficulty: 3,
    topic: 'Nutrition & Metabolism in Respiratory Care',
    isFree: false,
    orderIndex: 482,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does malnutrition impair respiratory muscle function?',
    answer: 'Malnutrition causes diaphragmatic muscle wasting, reducing its mass and contractile strength, which leads to decreased maximal inspiratory pressure and vital capacity. Protein-calorie malnutrition also impairs immune function (increasing infection risk), reduces hypoxic and hypercapnic ventilatory drive, decreases surfactant production, and impairs the cough reflex. These effects contribute to prolonged mechanical ventilation and weaning failure.',
    difficulty: 2,
    topic: 'Nutrition & Metabolism in Respiratory Care',
    isFree: false,
    orderIndex: 483,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is refeeding syndrome and why is it relevant to respiratory care?',
    answer: 'Refeeding syndrome occurs when malnourished patients receive aggressive nutritional repletion, causing rapid insulin release that drives phosphate, potassium, and magnesium into cells. Severe hypophosphatemia (the hallmark finding) impairs ATP production, causing respiratory muscle weakness, cardiac dysfunction, and potentially respiratory failure. Nutrition should be started slowly (10-20 kcal/kg/day) with electrolyte monitoring and supplementation.',
    difficulty: 3,
    topic: 'Nutrition & Metabolism in Respiratory Care',
    isFree: false,
    orderIndex: 484,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the Harris-Benedict equation used for in respiratory care?',
    answer: 'The Harris-Benedict equation estimates basal energy expenditure (BEE) based on age, sex, height, and weight. Stress factors (1.2 for mild stress, 1.5 for moderate, up to 2.0 for severe burns) are multiplied to estimate total caloric requirements. However, indirect calorimetry is the gold standard for determining actual energy needs in critically ill patients, as predictive equations can be inaccurate by 40-60% in ICU populations.',
    difficulty: 2,
    topic: 'Nutrition & Metabolism in Respiratory Care',
    isFree: false,
    orderIndex: 485,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Why is phosphate important for respiratory muscle function?',
    answer: 'Phosphate is a critical component of ATP (adenosine triphosphate) and 2,3-DPG (2,3-diphosphoglycerate). Hypophosphatemia impairs ATP-dependent muscle contraction, leading to diaphragmatic weakness and potential respiratory failure. Low 2,3-DPG shifts the oxyhemoglobin dissociation curve leftward, reducing oxygen release to tissues. Critically ill patients are especially vulnerable, and serum phosphate should be maintained above 2.5 mg/dL.',
    difficulty: 3,
    topic: 'Nutrition & Metabolism in Respiratory Care',
    isFree: false,
    orderIndex: 486,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the recommended macronutrient distribution for ventilated patients who are difficult to wean?',
    answer: 'For ventilated patients with difficulty weaning, a high-fat, low-carbohydrate enteral formula is often recommended: approximately 40-50% of calories from fat, 30-40% from carbohydrate, and 15-20% from protein. This distribution lowers the RQ and reduces CO2 production compared to standard high-carbohydrate formulas. However, total caloric intake should not exceed measured or estimated energy expenditure, as overfeeding of any macronutrient increases VCO2.',
    difficulty: 3,
    topic: 'Nutrition & Metabolism in Respiratory Care',
    isFree: false,
    orderIndex: 487,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is nitrogen balance assessed and what does it indicate for a ventilated patient?',
    answer: 'Nitrogen balance is calculated as nitrogen intake (protein intake in grams divided by 6.25) minus nitrogen output (24-hour urine urea nitrogen plus an estimated 2-4 g for non-urea losses). A negative nitrogen balance indicates protein catabolism (muscle breakdown), while a positive balance indicates anabolism (tissue repair). Critically ill patients often have high nitrogen losses and require 1.2-2.0 g/kg/day of protein to achieve positive balance.',
    difficulty: 3,
    topic: 'Nutrition & Metabolism in Respiratory Care',
    isFree: false,
    orderIndex: 488,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the relationship between obesity-hypoventilation syndrome and respiratory care?',
    answer: 'Obesity-hypoventilation syndrome (OHS, Pickwickian syndrome) is characterized by BMI of 30 or greater, chronic daytime hypercapnia (PaCO2 greater than 45 mmHg), and sleep-disordered breathing in the absence of other causes of hypoventilation. The increased chest wall mass decreases compliance, increases work of breathing, and reduces FRC. Treatment includes weight loss, CPAP or bilevel PAP therapy, and in severe cases, mechanical ventilation with attention to appropriate tidal volume calculations using ideal body weight.',
    difficulty: 3,
    topic: 'Nutrition & Metabolism in Respiratory Care',
    isFree: false,
    orderIndex: 489,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the metabolic consequences of permissive hypercapnia in mechanically ventilated patients?',
    answer: 'Permissive hypercapnia (tolerating elevated PaCO2 to achieve lung-protective tidal volumes) causes respiratory acidosis, sympathetic activation with tachycardia and increased cardiac output, cerebral vasodilation with increased intracranial pressure, rightward shift of the oxyhemoglobin dissociation curve (facilitating oxygen unloading), and renal compensation with bicarbonate retention over 24-72 hours. It is contraindicated in elevated ICP, severe pulmonary hypertension, and significant cardiac arrhythmias.',
    difficulty: 4,
    topic: 'Nutrition & Metabolism in Respiratory Care',
    isFree: false,
    orderIndex: 490,
  },
  // ============================================================
  // EVIDENCE-BASED PRACTICE IN RT (491-500)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the levels of evidence in evidence-based medicine, from strongest to weakest?',
    answer: 'The hierarchy of evidence from strongest to weakest is: systematic reviews and meta-analyses of randomized controlled trials (Level I), individual randomized controlled trials (Level II), controlled trials without randomization or cohort studies (Level III), case-control studies (Level IV), case series and case reports (Level V), and expert opinion or consensus statements (Level VI).',
    difficulty: 2,
    topic: 'Evidence-Based Practice in RT',
    isFree: false,
    orderIndex: 491,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between sensitivity and specificity of a diagnostic test?',
    answer: 'Sensitivity is the ability of a test to correctly identify patients who have a disease (true positive rate), calculated as true positives divided by all patients with the disease. Specificity is the ability to correctly identify patients without the disease (true negative rate), calculated as true negatives divided by all patients without the disease. A highly sensitive test is good for ruling out disease (SnNOut), while a highly specific test is good for ruling in disease (SpPIn).',
    difficulty: 2,
    topic: 'Evidence-Based Practice in RT',
    isFree: false,
    orderIndex: 492,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a clinical practice guideline (CPG) and how is it developed?',
    answer: 'A clinical practice guideline is a systematically developed set of recommendations designed to assist clinician and patient decisions about appropriate healthcare for specific clinical circumstances. CPGs are developed by expert panels that systematically review and grade the available evidence, assess the balance of benefits and harms, and formulate recommendations with strength ratings (strong or conditional). The AARC publishes CPGs specific to respiratory care practice.',
    difficulty: 2,
    topic: 'Evidence-Based Practice in RT',
    isFree: false,
    orderIndex: 493,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between a randomized controlled trial and an observational cohort study?',
    answer: 'In a randomized controlled trial (RCT), participants are randomly assigned to intervention or control groups, minimizing selection bias and confounding variables, which allows causal conclusions. In an observational cohort study, researchers follow groups with and without an exposure over time to compare outcomes, but cannot control for all confounders and can only establish associations, not causation. RCTs provide stronger evidence but are more expensive and may have ethical limitations.',
    difficulty: 2,
    topic: 'Evidence-Based Practice in RT',
    isFree: false,
    orderIndex: 494,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the number needed to treat (NNT) and how is it calculated?',
    answer: 'NNT is the number of patients who must be treated with an intervention for one additional patient to benefit compared to a control. It is calculated as 1 divided by the absolute risk reduction (ARR), where ARR equals the control event rate minus the treatment event rate. A lower NNT indicates a more effective treatment. For example, if a drug reduces mortality from 30% to 20%, the ARR is 10% and the NNT is 10.',
    difficulty: 3,
    topic: 'Evidence-Based Practice in RT',
    isFree: false,
    orderIndex: 495,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a meta-analysis and what are its strengths and limitations?',
    answer: 'A meta-analysis is a statistical technique that combines results from multiple independent studies addressing the same question to produce a single pooled estimate of effect. Strengths include increased statistical power, improved precision of estimates, and the ability to resolve conflicting results. Limitations include publication bias (positive studies are more likely to be published), heterogeneity between studies, and the adage "garbage in, garbage out" when included studies are of poor quality.',
    difficulty: 3,
    topic: 'Evidence-Based Practice in RT',
    isFree: false,
    orderIndex: 496,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the Plan-Do-Study-Act (PDSA) cycle in quality improvement?',
    answer: 'The PDSA cycle is a systematic quality improvement framework. Plan identifies the problem, sets measurable goals, and designs an intervention. Do implements the intervention on a small scale. Study analyzes the collected data to determine whether the intervention achieved the desired outcome. Act decides whether to adopt, modify, or abandon the change based on results. Multiple rapid PDSA cycles allow iterative refinement of clinical processes.',
    difficulty: 2,
    topic: 'Evidence-Based Practice in RT',
    isFree: false,
    orderIndex: 497,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is positive predictive value (PPV) and how does disease prevalence affect it?',
    answer: 'Positive predictive value is the probability that a patient with a positive test result actually has the disease, calculated as true positives divided by all positive results (true positives plus false positives). PPV is heavily influenced by disease prevalence: in a low-prevalence population, even a highly specific test will have a low PPV because false positives outnumber true positives. This is why screening tests perform differently in different populations.',
    difficulty: 3,
    topic: 'Evidence-Based Practice in RT',
    isFree: false,
    orderIndex: 498,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are respiratory care protocols and what evidence supports their use?',
    answer: 'Respiratory care protocols are evidence-based, therapist-driven algorithms that allow RTs to initiate, modify, or discontinue therapy based on patient assessment within physician-approved guidelines. Research has shown that protocols improve consistency of care, reduce unnecessary treatments (such as bronchodilator overuse), decrease costs, shorten ventilator days through standardized weaning protocols, and maintain or improve patient outcomes compared to physician-only order-driven care.',
    difficulty: 2,
    topic: 'Evidence-Based Practice in RT',
    isFree: false,
    orderIndex: 499,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between a Type I error and a Type II error in clinical research?',
    answer: 'A Type I error (alpha error) is a false positive, concluding that a treatment effect exists when it actually does not; the probability is set by the significance level, typically 0.05. A Type II error (beta error) is a false negative, failing to detect a real treatment effect; its probability is related to statistical power (1 minus beta, usually targeted at 0.80 or 80%). Underpowered studies with small sample sizes are prone to Type II errors.',
    difficulty: 3,
    topic: 'Evidence-Based Practice in RT',
    isFree: false,
    orderIndex: 500,
  },
];

export async function seedTmcBatch5() {
  console.log('Seeding TMC Batch 5 (cards 401-500)...');
  console.log(`Total cards to insert: ${cards.length}`);

  const result = await prisma.flashcard.createMany({
    data: cards,
    skipDuplicates: true,
  });

  console.log(`Successfully inserted ${result.count} flashcards.`);
  console.log('TMC Batch 5 seeding complete.');
}
