import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding CPFT flashcards batch 4 (cards 301-400)...')

  await prisma.flashcard.createMany({
    data: [
      // === Maximal Voluntary Ventilation (MVV) Testing (10 cards) ===
      {
        question: 'What does MVV stand for and what does it measure?',
        answer: 'Maximal Voluntary Ventilation. It measures the maximum volume of air a patient can inhale and exhale over a specified period, typically 12 seconds, then extrapolated to one minute (L/min). It reflects ventilatory capacity and respiratory muscle endurance.',
        difficulty: 1,
        topic: 'Maximal Voluntary Ventilation',
        isFree: false,
        orderIndex: 301,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How long is the standard MVV maneuver performed and how is the result expressed?',
        answer: 'The patient breathes as rapidly and deeply as possible for 12 seconds. The accumulated volume is multiplied by 5 to extrapolate to liters per minute (L/min).',
        difficulty: 1,
        topic: 'Maximal Voluntary Ventilation',
        isFree: false,
        orderIndex: 302,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the commonly used formula to estimate MVV from FEV1?',
        answer: 'MVV is estimated as FEV1 multiplied by 35 to 40 (MVV ≈ FEV1 × 35–40). This indirect estimate is sometimes used when a patient cannot perform the MVV maneuver, though directly measured MVV is preferred when feasible.',
        difficulty: 2,
        topic: 'Maximal Voluntary Ventilation',
        isFree: false,
        orderIndex: 303,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Name three conditions that would contraindicate performing an MVV test.',
        answer: '(1) Recent pneumothorax, (2) unstable angina or recent myocardial infarction, and (3) recent thoracic or abdominal surgery. The vigorous effort required can exacerbate these conditions.',
        difficulty: 2,
        topic: 'Maximal Voluntary Ventilation',
        isFree: false,
        orderIndex: 304,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient\'s directly measured MVV is significantly lower than the estimated MVV (FEV1 × 40). What conditions might explain this discrepancy?',
        answer: 'Neuromuscular disease, respiratory muscle weakness, poor effort or motivation, upper airway obstruction, or chest wall restriction. These conditions reduce ventilatory endurance disproportionately to FEV1.',
        difficulty: 3,
        topic: 'Maximal Voluntary Ventilation',
        isFree: false,
        orderIndex: 305,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the breathing reserve and how is MVV used to calculate it?',
        answer: 'Breathing reserve = MVV minus maximum minute ventilation achieved during exercise (VEmax). It is often expressed as a percentage: (MVV − VEmax) / MVV × 100. A normal breathing reserve is typically greater than 20%, indicating the patient did not reach ventilatory limitation during exercise.',
        difficulty: 3,
        topic: 'Maximal Voluntary Ventilation',
        isFree: false,
        orderIndex: 306,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What coaching instructions should the technologist give a patient before starting an MVV test?',
        answer: 'Instruct the patient to breathe as hard and fast as possible for the entire test period, using deep breaths rather than shallow panting. Demonstrate the maneuver and encourage the patient to maintain effort throughout the 12-second collection period.',
        difficulty: 1,
        topic: 'Maximal Voluntary Ventilation',
        isFree: false,
        orderIndex: 307,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What are acceptable repeatability criteria for MVV testing?',
        answer: 'The two largest MVV values from acceptable maneuvers should be within 20% of each other. At least two acceptable maneuvers should be obtained with adequate effort throughout the breathing period.',
        difficulty: 2,
        topic: 'Maximal Voluntary Ventilation',
        isFree: false,
        orderIndex: 308,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why might a patient develop lightheadedness or syncope during MVV testing?',
        answer: 'Hyperventilation during the MVV maneuver causes a rapid decrease in PaCO2 (respiratory alkalosis), which leads to cerebral vasoconstriction and can result in lightheadedness, dizziness, or syncope. The technologist should monitor the patient and stop the test if symptoms develop.',
        difficulty: 2,
        topic: 'Maximal Voluntary Ventilation',
        isFree: false,
        orderIndex: 309,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does an obstructive disease pattern typically affect MVV compared to a restrictive disease pattern?',
        answer: 'In obstructive disease, MVV is typically reduced disproportionately to vital capacity because airflow limitation slows emptying and reduces achievable breathing frequency. In restrictive disease, MVV is reduced roughly in proportion to the reduction in vital capacity, since tidal volumes are limited but breathing frequency can be maintained.',
        difficulty: 3,
        topic: 'Maximal Voluntary Ventilation',
        isFree: false,
        orderIndex: 310,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // === Respiratory Muscle Strength – MIP/MEP (10 cards) ===
      {
        question: 'What do MIP and MEP measure?',
        answer: 'MIP (Maximal Inspiratory Pressure) measures the strength of the inspiratory muscles, primarily the diaphragm. MEP (Maximal Expiratory Pressure) measures the strength of the expiratory muscles, primarily the abdominals and intercostals. Both are expressed in cmH2O.',
        difficulty: 1,
        topic: 'Respiratory Muscle Strength',
        isFree: false,
        orderIndex: 311,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'At what lung volume should MIP and MEP be measured for maximal values?',
        answer: 'MIP should be measured at or near residual volume (RV), because inspiratory muscles are at optimal length-tension relationship at low lung volumes. MEP should be measured at or near total lung capacity (TLC), because expiratory muscles generate the greatest force at high lung volumes.',
        difficulty: 2,
        topic: 'Respiratory Muscle Strength',
        isFree: false,
        orderIndex: 312,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the minimum sustained pressure duration required for an acceptable MIP or MEP maneuver?',
        answer: 'The peak pressure must be sustained for at least 1 second (sometimes reported as 1.0 to 1.5 seconds). This ensures the measurement reflects true muscular effort rather than a transient pressure spike from cheek or mouth muscles.',
        difficulty: 2,
        topic: 'Respiratory Muscle Strength',
        isFree: false,
        orderIndex: 313,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why does the mouthpiece or connector for MIP/MEP testing include a small leak?',
        answer: 'A small leak (approximately 2 mm internal diameter) prevents the patient from using their cheek and buccal muscles to generate falsely elevated pressures. The leak ensures that glottic closure alone cannot sustain pressure and that the measurement reflects diaphragm and chest wall muscle strength.',
        difficulty: 2,
        topic: 'Respiratory Muscle Strength',
        isFree: false,
        orderIndex: 314,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What clinical conditions commonly warrant MIP and MEP testing?',
        answer: 'Neuromuscular diseases (ALS, myasthenia gravis, muscular dystrophy), diaphragm paralysis or weakness, unexplained dyspnea, ventilator weaning assessment, pre-operative evaluation for patients at risk of respiratory failure, and monitoring disease progression in neuromuscular disorders.',
        difficulty: 1,
        topic: 'Respiratory Muscle Strength',
        isFree: false,
        orderIndex: 315,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How many acceptable maneuvers are typically required for MIP and MEP, and how is the best value selected?',
        answer: 'A minimum of 3 acceptable maneuvers should be obtained, with the two highest values within 20% of each other. The highest value from an acceptable maneuver is reported. Some protocols require up to 5 or more attempts to ensure maximal effort.',
        difficulty: 2,
        topic: 'Respiratory Muscle Strength',
        isFree: false,
        orderIndex: 316,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient has a normal FVC but an MIP of −30 cmH2O (predicted −80 cmH2O). What is the most likely clinical significance?',
        answer: 'This indicates significant inspiratory muscle weakness despite preserved lung volumes. Early neuromuscular disease can present with reduced MIP before spirometric abnormalities appear. The patient is at risk for hypoventilation, especially during sleep, and should be evaluated for neuromuscular or diaphragmatic pathology.',
        difficulty: 3,
        topic: 'Respiratory Muscle Strength',
        isFree: false,
        orderIndex: 317,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is SNIP and how does it differ from MIP?',
        answer: 'SNIP (Sniff Nasal Inspiratory Pressure) is measured through a plug in one nostril during a maximal sniff maneuver through the contralateral nostril. It is a more natural maneuver than MIP, may be easier for some patients, and specifically assesses diaphragm function. It is particularly useful in patients who have difficulty with the mouthpiece-based MIP maneuver.',
        difficulty: 3,
        topic: 'Respiratory Muscle Strength',
        isFree: false,
        orderIndex: 318,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Normal MIP values for healthy young adults are typically in what range?',
        answer: 'Healthy young adult males typically generate MIP values of −100 to −150 cmH2O, and healthy young adult females typically generate −70 to −100 cmH2O. Values less negative than −60 cmH2O in males or −40 cmH2O in females generally suggest clinically significant inspiratory muscle weakness.',
        difficulty: 1,
        topic: 'Respiratory Muscle Strength',
        isFree: false,
        orderIndex: 319,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A ventilated patient has an MIP of −15 cmH2O. What does this suggest about weaning potential?',
        answer: 'An MIP of −15 cmH2O suggests very poor weaning potential. Generally, an MIP more negative than −20 to −30 cmH2O is considered a minimum threshold for successful ventilator weaning. At −15 cmH2O, the patient lacks sufficient inspiratory muscle strength to sustain spontaneous breathing and likely needs continued ventilatory support and possible respiratory muscle training.',
        difficulty: 3,
        topic: 'Respiratory Muscle Strength',
        isFree: false,
        orderIndex: 320,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // === Exhaled Nitric Oxide (FeNO) Testing (10 cards) ===
      {
        question: 'What does FeNO stand for and what does it indicate?',
        answer: 'FeNO stands for Fractional Exhaled Nitric Oxide. It is a biomarker of eosinophilic airway inflammation. Elevated FeNO levels suggest type 2 (Th2-driven) inflammation commonly seen in allergic or eosinophilic asthma.',
        difficulty: 1,
        topic: 'Exhaled Nitric Oxide Testing',
        isFree: false,
        orderIndex: 321,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the standard exhalation flow rate for FeNO measurement according to ATS/ERS guidelines?',
        answer: '50 mL/s (0.05 L/s). This standardized flow rate ensures consistent and reproducible FeNO measurements. The device provides visual or auditory feedback to help the patient maintain this target flow rate during exhalation.',
        difficulty: 2,
        topic: 'Exhaled Nitric Oxide Testing',
        isFree: false,
        orderIndex: 322,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What FeNO level (in ppb) is generally considered elevated in adults?',
        answer: 'In adults, FeNO greater than 50 ppb is considered high and strongly suggests eosinophilic inflammation. Values of 25-50 ppb are intermediate, and values less than 25 ppb are considered normal or low. Interpretation should be made in clinical context.',
        difficulty: 1,
        topic: 'Exhaled Nitric Oxide Testing',
        isFree: false,
        orderIndex: 323,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why must the patient inhale through a NO-scrubbing filter before exhaling during FeNO measurement?',
        answer: 'Ambient air contains variable concentrations of nitric oxide. Inhaling through a NO-scrubbing filter removes ambient NO from the inspired air, ensuring that the measured exhaled NO reflects only endogenous production from the lower airways rather than contaminated ambient NO.',
        difficulty: 2,
        topic: 'Exhaled Nitric Oxide Testing',
        isFree: false,
        orderIndex: 324,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Name three factors other than asthma that can elevate FeNO levels.',
        answer: '(1) Allergic rhinitis, (2) eosinophilic bronchitis without asthma, and (3) viral upper respiratory infections. Additionally, dietary nitrate intake (leafy vegetables, beets) can also temporarily increase FeNO. These confounders should be considered when interpreting results.',
        difficulty: 2,
        topic: 'Exhaled Nitric Oxide Testing',
        isFree: false,
        orderIndex: 325,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What factors can cause a falsely low FeNO result?',
        answer: 'Active smoking, recent use of inhaled corticosteroids, recent spirometry (should be done after FeNO), consumption of alcohol within the preceding 12 hours, and bronchoconstriction. FeNO should ideally be measured before spirometry to avoid the effect of forced maneuvers on NO levels.',
        difficulty: 2,
        topic: 'Exhaled Nitric Oxide Testing',
        isFree: false,
        orderIndex: 326,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'In what order should FeNO and spirometry be performed when both are ordered, and why?',
        answer: 'FeNO should be performed BEFORE spirometry. Forced expiratory maneuvers during spirometry can transiently reduce FeNO levels, potentially leading to falsely low results. Performing FeNO first avoids this confounding effect.',
        difficulty: 1,
        topic: 'Exhaled Nitric Oxide Testing',
        isFree: false,
        orderIndex: 327,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'An asthma patient on inhaled corticosteroids has a persistently elevated FeNO of 65 ppb despite reported medication adherence. What should the technologist consider?',
        answer: 'Poor inhaler technique is a common reason for persistently elevated FeNO despite reported adherence. Other considerations include: patient non-adherence despite claims, inadequate corticosteroid dose, ongoing allergen exposure, or steroid-resistant eosinophilic inflammation requiring biologic therapy. The technologist should document the result and alert the ordering clinician.',
        difficulty: 3,
        topic: 'Exhaled Nitric Oxide Testing',
        isFree: false,
        orderIndex: 328,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What exhalation duration is required for a valid FeNO measurement in adults?',
        answer: 'Adults must exhale for at least 6 seconds at the target flow rate of 50 mL/s. The FeNO plateau is typically achieved after 4-5 seconds, and the measurement is taken from the plateau phase. Children aged 5-12 may have a minimum exhalation of 4 seconds.',
        difficulty: 2,
        topic: 'Exhaled Nitric Oxide Testing',
        isFree: false,
        orderIndex: 329,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does the exhalation flow rate affect FeNO concentration, and why is this clinically important?',
        answer: 'FeNO concentration is inversely related to flow rate: higher flow rates yield lower FeNO values and vice versa. This is because at lower flow rates, exhaled air has longer contact time with the airway mucosa, allowing more NO to diffuse into the airstream. This is why the standardized flow of 50 mL/s must be maintained for comparable results.',
        difficulty: 3,
        topic: 'Exhaled Nitric Oxide Testing',
        isFree: false,
        orderIndex: 330,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // === Six-Minute Walk Test (6MWT) Procedures (10 cards) ===
      {
        question: 'What is the primary outcome measured in a six-minute walk test?',
        answer: 'The primary outcome is the six-minute walk distance (6MWD), measured in meters. It reflects the patient\'s functional exercise capacity and integrates responses from the pulmonary, cardiovascular, and musculoskeletal systems.',
        difficulty: 1,
        topic: 'Six-Minute Walk Test',
        isFree: false,
        orderIndex: 331,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the recommended length and layout of the walking course for a 6MWT?',
        answer: 'The recommended course is a flat, straight, enclosed corridor at least 30 meters (100 feet) in length. Turnaround points should be clearly marked with cones. The course should be free of foot traffic during the test. Shorter corridors require more turns and can reduce the measured distance.',
        difficulty: 1,
        topic: 'Six-Minute Walk Test',
        isFree: false,
        orderIndex: 332,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What standardized encouragement phrases are used during the 6MWT and at what intervals?',
        answer: 'Standardized encouragement is given each minute. Examples: at 1 min: "You are doing well. You have 5 minutes to go." At 2 min: "Keep up the good work. You have 4 minutes to go." At 3 min: "You are doing well. You are halfway done." Phrases should be delivered in an even tone without coaching the patient to speed up or slow down.',
        difficulty: 2,
        topic: 'Six-Minute Walk Test',
        isFree: false,
        orderIndex: 333,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What vital signs and assessments should be recorded before and after the 6MWT?',
        answer: 'Before and after: heart rate, blood pressure, SpO2, and dyspnea and fatigue ratings (typically using the Borg scale, 0-10). SpO2 should also be monitored continuously or at regular intervals during the walk. The number of laps and any rest periods should be documented.',
        difficulty: 2,
        topic: 'Six-Minute Walk Test',
        isFree: false,
        orderIndex: 334,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What are the absolute contraindications for performing a 6MWT?',
        answer: 'Absolute contraindications include: unstable angina during the previous month, myocardial infarction during the previous month, and resting heart rate greater than 120 bpm. Relative contraindications include resting SpO2 less than 85% on room air and uncontrolled hypertension (systolic >180 or diastolic >100 mmHg).',
        difficulty: 2,
        topic: 'Six-Minute Walk Test',
        isFree: false,
        orderIndex: 335,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Should the technologist walk with the patient during the 6MWT?',
        answer: 'The technologist should NOT walk alongside the patient, as this can influence walking pace (pacing effect). The technologist should stand near the starting line or follow behind the patient at a distance, close enough to monitor the patient and respond to any adverse events but not close enough to set a pace.',
        difficulty: 1,
        topic: 'Six-Minute Walk Test',
        isFree: false,
        orderIndex: 336,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the minimal clinically important difference (MCID) for the 6MWD?',
        answer: 'The MCID for the six-minute walk distance is approximately 25-33 meters (often cited as 30 meters). A change of at least this magnitude is considered clinically meaningful, indicating a real change in functional capacity rather than test-to-test variability.',
        difficulty: 3,
        topic: 'Six-Minute Walk Test',
        isFree: false,
        orderIndex: 337,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'If a patient stops walking during the 6MWT, what should the technologist do?',
        answer: 'The technologist should note the time and allow the patient to rest (sitting or standing) while the clock continues running. Encourage the patient to resume walking when able. Do NOT stop the timer. If the patient cannot resume, note the reason and the distance achieved. The test is stopped only if absolute stop criteria are met.',
        difficulty: 2,
        topic: 'Six-Minute Walk Test',
        isFree: false,
        orderIndex: 338,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What criteria should prompt the technologist to immediately stop a 6MWT?',
        answer: 'Stop criteria include: chest pain, intolerable dyspnea, leg cramps, staggering or appearance of impending fall, diaphoresis, pale or ashen appearance, and SpO2 dropping below 80% (some protocols use 85%). The technologist should be prepared with a wheelchair and supplemental oxygen.',
        difficulty: 2,
        topic: 'Six-Minute Walk Test',
        isFree: false,
        orderIndex: 339,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why is a practice 6MWT sometimes recommended, and how should repeated tests be handled?',
        answer: 'A practice test is sometimes recommended because a learning effect can increase the 6MWD by 20-30 meters on the second test. When serial tests are performed (e.g., to track treatment response), they should be done at the same time of day, with the same encouragement, on the same course, and after the same rest period. At least 30 minutes of rest is recommended between repeat tests.',
        difficulty: 3,
        topic: 'Six-Minute Walk Test',
        isFree: false,
        orderIndex: 340,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // === Pulse Oximetry Principles and Limitations (10 cards) ===
      {
        question: 'What two wavelengths of light does a conventional pulse oximeter use?',
        answer: 'Red light at approximately 660 nm and infrared light at approximately 940 nm. Oxyhemoglobin and deoxyhemoglobin absorb these wavelengths differently, allowing the oximeter to calculate the ratio and determine SpO2.',
        difficulty: 1,
        topic: 'Pulse Oximetry',
        isFree: false,
        orderIndex: 341,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does a pulse oximeter distinguish arterial blood from venous blood and tissue?',
        answer: 'The pulse oximeter analyzes only the pulsatile (AC) component of the light absorption signal, which corresponds to arterial blood flow. The non-pulsatile (DC) component from venous blood, tissue, and bone is subtracted out. This is why adequate pulse amplitude is essential for accurate readings.',
        difficulty: 2,
        topic: 'Pulse Oximetry',
        isFree: false,
        orderIndex: 342,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the effect of carboxyhemoglobin (COHb) on pulse oximetry readings?',
        answer: 'Carboxyhemoglobin absorbs light similarly to oxyhemoglobin at 660 nm, causing the pulse oximeter to overestimate SpO2. In carbon monoxide poisoning, SpO2 may read falsely normal or high while the patient is significantly hypoxemic. Co-oximetry from an arterial blood gas is needed for accurate assessment.',
        difficulty: 2,
        topic: 'Pulse Oximetry',
        isFree: false,
        orderIndex: 343,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the effect of methemoglobin (MetHb) on pulse oximetry readings?',
        answer: 'Methemoglobin absorbs red and infrared light equally, causing the R/IR ratio to approach 1.0, which corresponds to an SpO2 reading of approximately 85%. As MetHb increases, SpO2 readings tend toward 85% regardless of true oxygen saturation. Co-oximetry is required for accurate assessment.',
        difficulty: 3,
        topic: 'Pulse Oximetry',
        isFree: false,
        orderIndex: 344,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'At what SpO2 range are pulse oximeters most accurate, and what is their typical accuracy?',
        answer: 'Pulse oximeters are most accurate in the 70-100% SpO2 range, with a typical accuracy of ±2-3%. Below 70%, accuracy decreases significantly because calibration algorithms are based on data from healthy volunteers, and ethics prevent inducing such low saturations experimentally.',
        difficulty: 2,
        topic: 'Pulse Oximetry',
        isFree: false,
        orderIndex: 345,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Name three clinical conditions or factors that can cause inaccurate pulse oximetry readings.',
        answer: '(1) Poor peripheral perfusion (hypotension, hypothermia, vasoconstriction), (2) excessive patient motion artifact, and (3) nail polish or artificial nails (particularly dark colors like black, blue, or green). Other factors include ambient light interference and severe anemia.',
        difficulty: 1,
        topic: 'Pulse Oximetry',
        isFree: false,
        orderIndex: 346,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the difference between SpO2 and SaO2?',
        answer: 'SpO2 is the oxygen saturation estimated noninvasively by pulse oximetry. SaO2 is the arterial oxygen saturation measured directly from an arterial blood sample using co-oximetry. SpO2 estimates functional saturation (oxyhemoglobin relative to oxyhemoglobin plus deoxyhemoglobin), while co-oximetry measures fractional saturation, accounting for all hemoglobin species.',
        difficulty: 1,
        topic: 'Pulse Oximetry',
        isFree: false,
        orderIndex: 347,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does severe anemia affect pulse oximetry accuracy?',
        answer: 'In severe anemia (hemoglobin less than 5 g/dL), pulse oximetry may remain normal because SpO2 measures the percentage of available hemoglobin that is saturated, not total oxygen content. A patient can have a normal SpO2 but critically low oxygen delivery due to insufficient hemoglobin to carry adequate oxygen to tissues.',
        difficulty: 3,
        topic: 'Pulse Oximetry',
        isFree: false,
        orderIndex: 348,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is a penumbra effect in pulse oximetry?',
        answer: 'The penumbra effect occurs when the pulse oximeter sensor is improperly positioned so that light from the emitter does not pass directly through the tissue to the detector. Light bypasses the arterial bed (optical shunting), leading to inaccurate SpO2 readings. Proper sensor alignment and placement prevents this artifact.',
        difficulty: 3,
        topic: 'Pulse Oximetry',
        isFree: false,
        orderIndex: 349,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why should the technologist document the probe site and perfusion status when recording pulse oximetry?',
        answer: 'Probe site (finger, earlobe, forehead) and perfusion status (warm/cool extremities, capillary refill) directly affect measurement accuracy. Documenting these factors allows clinicians to assess the reliability of the SpO2 reading and compare serial measurements obtained under similar conditions.',
        difficulty: 1,
        topic: 'Pulse Oximetry',
        isFree: false,
        orderIndex: 350,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // === Arterial Blood Gas Pre-analytics and Quality (10 cards) ===
      {
        question: 'What is the preferred artery for arterial blood gas sampling and why?',
        answer: 'The radial artery is the preferred site because it is superficial, easily accessible, has collateral circulation from the ulnar artery via the palmar arch, and the area is easy to compress after sampling to achieve hemostasis. The brachial and femoral arteries are alternative sites.',
        difficulty: 1,
        topic: 'Arterial Blood Gas Quality',
        isFree: false,
        orderIndex: 351,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the modified Allen test and why is it performed?',
        answer: 'The modified Allen test assesses collateral circulation to the hand via the ulnar artery before radial artery puncture. The patient clenches the fist while both arteries are occluded. Upon releasing the ulnar artery, the hand should flush pink within 5-10 seconds, indicating adequate collateral flow. A negative result (delayed flushing) suggests the ulnar artery may not adequately perfuse the hand if the radial artery is damaged.',
        difficulty: 2,
        topic: 'Arterial Blood Gas Quality',
        isFree: false,
        orderIndex: 352,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What type of anticoagulant is used in ABG syringes and why?',
        answer: 'Lyophilized (dry) lithium heparin is the preferred anticoagulant. Liquid heparin should be avoided because it dilutes the sample, potentially lowering PaCO2 and PaO2 values. Lithium heparin does not interfere with electrolyte measurements. The heparin prevents clotting, which would make the sample unanalyzable.',
        difficulty: 2,
        topic: 'Arterial Blood Gas Quality',
        isFree: false,
        orderIndex: 353,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What are the effects of air bubbles in an ABG sample?',
        answer: 'Air bubbles cause the PaO2 to increase (equilibrate toward room air PO2 of ~150 mmHg) and the PaCO2 to decrease (equilibrate toward near-zero ambient CO2). This is especially significant when the patient is hypoxemic, as the PaO2 error will be proportionally larger. All visible air bubbles must be expelled immediately after collection.',
        difficulty: 2,
        topic: 'Arterial Blood Gas Quality',
        isFree: false,
        orderIndex: 354,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How should an ABG sample be transported to the analyzer if analysis will be delayed?',
        answer: 'The sample should be placed in an ice-water slurry (not dry ice) and analyzed within 30 minutes. Ice slows cellular metabolism, which would otherwise consume O2 (lowering PaO2) and produce CO2 (raising PaCO2). If analyzed within 10-15 minutes, icing may not be necessary for most samples, but iced transport is always preferred for leukocytosis or elevated WBC counts.',
        difficulty: 2,
        topic: 'Arterial Blood Gas Quality',
        isFree: false,
        orderIndex: 355,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why does a significantly elevated white blood cell count (leukocytosis) affect ABG results?',
        answer: 'White blood cells are metabolically active and continue to consume oxygen and produce CO2 in the sample after collection (leukocyte larceny). In patients with markedly elevated WBC counts (e.g., leukemia), this metabolism can rapidly lower PaO2 and raise PaCO2 if the sample is not analyzed promptly or iced. Immediate analysis or ice-water transport is critical.',
        difficulty: 3,
        topic: 'Arterial Blood Gas Quality',
        isFree: false,
        orderIndex: 356,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What should a technologist document when submitting an ABG sample?',
        answer: 'Documentation should include: patient identification, date and time of collection, patient temperature, FiO2 or oxygen flow rate at the time of collection, ventilator settings if applicable, patient position, time of any recent FiO2 changes (steady state requires at least 20-30 minutes), and the puncture site used.',
        difficulty: 1,
        topic: 'Arterial Blood Gas Quality',
        isFree: false,
        orderIndex: 357,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does patient temperature affect ABG interpretation?',
        answer: 'ABG analyzers measure samples at 37°C. In hypothermic patients, actual in vivo PaO2 and PaCO2 are lower than the measured values (gases are more soluble in cold blood). In hyperthermic patients, actual in vivo values are higher. Temperature correction may be applied, though the clinical approach to temperature correction remains debated.',
        difficulty: 3,
        topic: 'Arterial Blood Gas Quality',
        isFree: false,
        orderIndex: 358,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the difference between a venous and arterial sample in terms of blood gas values?',
        answer: 'Compared to arterial blood, venous blood has a lower PO2 (approximately 40 mmHg vs. 80-100 mmHg), higher PCO2 (approximately 46 mmHg vs. 35-45 mmHg), and lower pH (approximately 7.36 vs. 7.35-7.45). An inadvertent venous sample is suspected when PO2 is unexpectedly low and the blood appears dark rather than bright red.',
        difficulty: 1,
        topic: 'Arterial Blood Gas Quality',
        isFree: false,
        orderIndex: 359,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient on 40% FiO2 has an ABG showing PaO2 of 250 mmHg. What pre-analytical error should be suspected?',
        answer: 'A PaO2 of 250 mmHg on 40% FiO2 is physiologically implausible (expected maximum ~235 mmHg even with perfect gas exchange). Air contamination of the sample is the most likely cause — a large air bubble equilibrated the PaO2 toward room air levels, or the sample was exposed to air during collection or handling. The sample should be redrawn with careful attention to air exclusion.',
        difficulty: 3,
        topic: 'Arterial Blood Gas Quality',
        isFree: false,
        orderIndex: 360,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // === Body Plethysmography Airway Resistance (Raw/sGaw) (10 cards) ===
      {
        question: 'What do Raw and sGaw stand for in body plethysmography?',
        answer: 'Raw stands for airway resistance, measured in cmH2O/L/s. sGaw stands for specific airway conductance, which is the reciprocal of Raw (conductance = 1/Raw) divided by the lung volume at which it was measured (thoracic gas volume). sGaw accounts for the volume-dependence of airway resistance.',
        difficulty: 1,
        topic: 'Body Plethysmography Airway Resistance',
        isFree: false,
        orderIndex: 361,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the normal range for airway resistance (Raw) in healthy adults?',
        answer: 'Normal Raw in healthy adults is typically 0.6 to 2.4 cmH2O/L/s. Values above this range indicate increased airway resistance, commonly seen in obstructive airway diseases such as asthma and COPD.',
        difficulty: 1,
        topic: 'Body Plethysmography Airway Resistance',
        isFree: false,
        orderIndex: 362,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How is airway resistance measured in a body plethysmograph?',
        answer: 'The patient pants gently at a frequency of about 1-2 Hz against a closed shutter while box pressure changes are recorded. The shutter then opens and the patient continues panting while both flow and box pressure are measured simultaneously. The ratio of alveolar pressure change to flow (derived from the box pressure-flow relationship) yields Raw.',
        difficulty: 2,
        topic: 'Body Plethysmography Airway Resistance',
        isFree: false,
        orderIndex: 363,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why is specific airway conductance (sGaw) preferred over Raw for comparing results between patients?',
        answer: 'Airway resistance is inversely related to lung volume — at higher lung volumes, airways are more distended and resistance is lower. sGaw corrects for this volume dependence by dividing conductance (1/Raw) by the thoracic gas volume at which it was measured. This allows meaningful comparisons between patients of different sizes and lung volumes.',
        difficulty: 2,
        topic: 'Body Plethysmography Airway Resistance',
        isFree: false,
        orderIndex: 364,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What panting frequency is recommended during Raw measurement and why?',
        answer: 'A panting frequency of approximately 1-2 Hz (60-120 breaths per minute) is recommended. Panting too fast (>2 Hz) can cause the glottis to narrow, artificially increasing measured resistance. Panting too slowly may not generate adequate pressure changes for accurate measurement. The cheeks should be supported to prevent artifact.',
        difficulty: 2,
        topic: 'Body Plethysmography Airway Resistance',
        isFree: false,
        orderIndex: 365,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why should a patient support their cheeks during body plethysmography resistance measurements?',
        answer: 'Supporting the cheeks with the hands prevents cheek compliance from affecting the measurement. Without support, the compliant cheeks can expand and contract during panting, absorbing some of the pressure changes and introducing artifact that falsely elevates the measured airway resistance.',
        difficulty: 1,
        topic: 'Body Plethysmography Airway Resistance',
        isFree: false,
        orderIndex: 366,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does an upper airway obstruction (e.g., vocal cord dysfunction) affect Raw measurements versus spirometry?',
        answer: 'Upper airway obstruction increases Raw measured by plethysmography since it reflects total airway resistance including upper airways. However, it may produce variable or normal spirometric results if the obstruction is intermittent. The combination of elevated Raw with relatively preserved FEV1/FVC ratio or a flattened inspiratory loop on the flow-volume curve suggests an upper airway etiology.',
        difficulty: 3,
        topic: 'Body Plethysmography Airway Resistance',
        isFree: false,
        orderIndex: 367,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the relationship between airway conductance (Gaw) and airway resistance (Raw)?',
        answer: 'Gaw is the mathematical reciprocal of Raw: Gaw = 1/Raw. Conductance is expressed in L/s/cmH2O. While resistance increases with obstruction, conductance decreases. sGaw is calculated as Gaw divided by the lung volume (Vtg) at which it was measured: sGaw = Gaw/Vtg.',
        difficulty: 2,
        topic: 'Body Plethysmography Airway Resistance',
        isFree: false,
        orderIndex: 368,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient with asthma undergoes bronchial challenge testing using sGaw as the endpoint. What percentage decrease in sGaw is typically considered a positive response?',
        answer: 'A decrease in sGaw of 35-45% (varies by protocol, often cited as 35-40%) from baseline is considered a positive response to bronchial challenge, indicating airway hyperresponsiveness. sGaw is more sensitive to early airway narrowing than FEV1, making it useful for detecting mild bronchial hyperreactivity.',
        difficulty: 3,
        topic: 'Body Plethysmography Airway Resistance',
        isFree: false,
        orderIndex: 369,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What thermal artifact can affect plethysmographic Raw measurements and how is it minimized?',
        answer: 'The BTPS (body temperature and pressure, saturated) conditioning artifact occurs because inhaled air is warmed and humidified in the airways, changing its volume. This can introduce error in the box pressure signal. It is minimized by having the patient pant through a bacterial filter, breathe at a controlled rate, and allowing adequate thermal equilibration time in the box before testing.',
        difficulty: 3,
        topic: 'Body Plethysmography Airway Resistance',
        isFree: false,
        orderIndex: 370,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // === Cardiopulmonary Exercise Testing Basics (CPET) (10 cards) ===
      {
        question: 'What does CPET stand for and what is its primary purpose?',
        answer: 'CPET stands for Cardiopulmonary Exercise Testing. Its primary purpose is to evaluate the integrated response of the cardiovascular, pulmonary, and musculoskeletal systems to exercise. It helps determine the cause of exercise intolerance, quantify functional capacity, and differentiate cardiac from pulmonary limitations.',
        difficulty: 1,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 371,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is VO2max and what does it represent?',
        answer: 'VO2max (maximal oxygen consumption) represents the maximum rate at which the body can take up and utilize oxygen during exercise. It is expressed in mL/min or mL/kg/min. A true VO2max is identified by a plateau in VO2 despite increasing workload. If no plateau is reached, the term VO2peak is used instead.',
        difficulty: 1,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 372,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the anaerobic threshold (AT) and how is it identified during CPET?',
        answer: 'The anaerobic threshold is the exercise intensity at which anaerobic metabolism begins to supplement aerobic metabolism, causing lactate accumulation. It is identified noninvasively by the V-slope method (plotting VCO2 vs. VO2 to find the inflection point), or by identifying the point where VE/VO2 increases without a concurrent increase in VE/VCO2 (ventilatory equivalents method).',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 373,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What exercise protocols are commonly used in CPET?',
        answer: 'The most common protocols include incremental ramp protocols on a cycle ergometer (preferred for gas exchange analysis because of stable upper body) or treadmill (higher VO2max typically achieved). Ramp protocols increase workload continuously (e.g., 10-25 watts/minute on a cycle) and typically last 8-12 minutes. The Bruce protocol is a common treadmill protocol.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 374,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What measurements does the technologist need to monitor during a CPET?',
        answer: 'The technologist monitors: continuous 12-lead ECG, blood pressure (every 2-3 minutes), SpO2, expired gas analysis (VO2, VCO2, VE, respiratory rate, tidal volume), workload, heart rate, symptoms (dyspnea and leg fatigue via Borg or similar scale), and overall patient appearance for signs of distress.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 375,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What are the absolute indications to stop a CPET?',
        answer: 'Absolute stop criteria include: ST elevation greater than 1 mm in leads without Q waves, drop in systolic blood pressure greater than 10 mmHg from baseline with signs of ischemia, moderate to severe angina, sustained ventricular tachycardia, signs of poor perfusion (cyanosis, pallor), patient request to stop, technical failure of monitoring equipment, and SpO2 below 80%.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 376,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does the breathing reserve help determine whether exercise limitation is pulmonary or cardiovascular?',
        answer: 'Breathing reserve = (MVV − VEmax) / MVV × 100. Normal breathing reserve is >20-30%. A low breathing reserve (<15-20%) suggests ventilatory limitation (pulmonary cause). If breathing reserve is normal but the patient reaches maximal predicted heart rate, the limitation is likely cardiovascular. Both may be abnormal in combined disease.',
        difficulty: 3,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 377,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the heart rate reserve and how is it interpreted in CPET?',
        answer: 'Heart rate reserve = predicted maximum heart rate (220 − age) minus the maximum heart rate achieved during exercise. A normal response is achieving >80% of predicted max heart rate. A large heart rate reserve (not reaching predicted max) may indicate pulmonary or peripheral limitation, poor effort, beta-blocker use, or chronotropic incompetence.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 378,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the VE/VCO2 slope and what does an elevated value indicate?',
        answer: 'The VE/VCO2 slope represents the ventilatory efficiency — how many liters of ventilation are required to eliminate one liter of CO2. Normal values are approximately 25-30. An elevated slope (>34-36) indicates ventilatory inefficiency, commonly seen in heart failure, pulmonary hypertension, and increased dead space ventilation.',
        difficulty: 3,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 379,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the oxygen pulse and what does it reflect during CPET?',
        answer: 'Oxygen pulse = VO2 / heart rate (mL O2/beat). It is a noninvasive surrogate for stroke volume multiplied by the arteriovenous oxygen difference. A plateau or decrease in oxygen pulse during exercise suggests cardiac output limitation, potentially from ischemia, left ventricular dysfunction, or valvular disease.',
        difficulty: 3,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 380,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // === Disability and Impairment Evaluation (10 cards) ===
      {
        question: 'What is the difference between impairment and disability in the context of pulmonary function evaluation?',
        answer: 'Impairment is a medical assessment of loss of function determined by objective testing (e.g., reduced FEV1 or DLCO). Disability is a legal/administrative determination of reduced capacity to meet occupational or personal demands. A physician determines impairment; disability determination involves additional non-medical factors such as job requirements and is often decided by regulatory agencies.',
        difficulty: 1,
        topic: 'Disability and Impairment Evaluation',
        isFree: false,
        orderIndex: 381,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Which pulmonary function tests are most commonly used in impairment evaluation according to AMA guidelines?',
        answer: 'The three primary tests are: FVC (or FEV1), DLCO, and VO2max (from CPET). FVC and FEV1 assess ventilatory capacity, DLCO assesses gas exchange ability, and VO2max provides an objective measure of overall functional capacity. These three parameters together classify impairment severity.',
        difficulty: 2,
        topic: 'Disability and Impairment Evaluation',
        isFree: false,
        orderIndex: 382,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why is maximal exercise testing (VO2max) considered the most objective measure for pulmonary impairment evaluation?',
        answer: 'VO2max is considered the most objective because it integrates the full chain of oxygen delivery and utilization, cannot be easily manipulated by the patient (unlike spirometry effort), and directly measures functional capacity. It provides an effort-independent endpoint (reaching the anaerobic threshold provides evidence of adequate effort regardless of the peak value).',
        difficulty: 2,
        topic: 'Disability and Impairment Evaluation',
        isFree: false,
        orderIndex: 383,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What quality assurance considerations are especially important when PFTs are performed for disability evaluation?',
        answer: 'Tests must meet all ATS/ERS acceptability and repeatability criteria. The technologist should document the number of attempts, quality grades, patient effort and cooperation, and any factors that may have affected performance. Consistent suboptimal effort should be noted but not assumed to be intentional. Calibration records should be available for legal review.',
        difficulty: 2,
        topic: 'Disability and Impairment Evaluation',
        isFree: false,
        orderIndex: 384,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Using AMA guidelines, a patient with FVC 55% predicted, DLCO 50% predicted, and VO2max of 18 mL/kg/min would generally fall into what impairment class?',
        answer: 'This would generally classify as moderate to moderately severe impairment. An FVC of 55% and DLCO of 50% both indicate significant functional loss, while a VO2max of 18 mL/kg/min falls in the moderate impairment range. The most severe single parameter typically determines the overall impairment rating.',
        difficulty: 3,
        topic: 'Disability and Impairment Evaluation',
        isFree: false,
        orderIndex: 385,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What role does the pulmonary function technologist play in disability evaluations?',
        answer: 'The technologist ensures tests are performed to the highest quality standards, documents patient effort and cooperation, notes any factors affecting test validity, maintains equipment calibration records, and provides complete technical quality information. The technologist does NOT make impairment or disability determinations — that is the role of the physician and/or administrative body.',
        difficulty: 1,
        topic: 'Disability and Impairment Evaluation',
        isFree: false,
        orderIndex: 386,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How should bronchodilator response be interpreted in the context of impairment evaluation?',
        answer: 'Post-bronchodilator values are typically used for impairment classification since they represent the best achievable lung function after treatment. If there is a significant bronchodilator response, it may indicate that the impairment is partially reversible with appropriate therapy. Some guidelines specify that impairment should be assessed on maximal medical therapy.',
        difficulty: 2,
        topic: 'Disability and Impairment Evaluation',
        isFree: false,
        orderIndex: 387,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the significance of the resting SpO2 and exercise desaturation in impairment evaluation?',
        answer: 'Resting SpO2 below 89% at sea level or exercise desaturation below 88-90% are markers of significant gas exchange impairment. Exercise-induced desaturation (typically a drop of ≥4% to below 88%) indicates impaired oxygen transfer and may qualify a patient for supplemental oxygen therapy. These findings can increase the impairment classification severity.',
        difficulty: 3,
        topic: 'Disability and Impairment Evaluation',
        isFree: false,
        orderIndex: 388,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why is it important to use an appropriate reference equation set when performing PFTs for impairment or disability evaluation?',
        answer: 'Reference equations must be appropriate for the patient\'s age, sex, height, and race/ethnicity to ensure accurate percent-predicted values. Using inappropriate references could over- or underestimate impairment. GLI-2012 equations are increasingly recommended as they are multi-ethnic and cover a wide age range, reducing bias in impairment classification.',
        difficulty: 2,
        topic: 'Disability and Impairment Evaluation',
        isFree: false,
        orderIndex: 389,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A worker exposed to asbestos has an FVC of 72% predicted and a DLCO of 58% predicted. Which result is more significant for impairment classification and why?',
        answer: 'The DLCO of 58% predicted is more significant because it indicates greater functional impairment. In asbestos-related disease, DLCO often declines before FVC due to interstitial fibrosis affecting gas transfer. The most abnormal parameter typically determines the impairment class. Additionally, the combination of both reduced FVC and markedly reduced DLCO supports the diagnosis of restrictive disease with impaired gas exchange.',
        difficulty: 3,
        topic: 'Disability and Impairment Evaluation',
        isFree: false,
        orderIndex: 390,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // === Board-Style Integration Scenarios (10 cards) ===
      {
        question: 'A 45-year-old patient has: FEV1 85% predicted, FVC 84% predicted, FEV1/FVC 78%, DLCO 45% predicted, and TLC 92% predicted. What is the most likely diagnosis pattern?',
        answer: 'Normal spirometry and lung volumes with an isolated, markedly reduced DLCO suggests pulmonary vascular disease (pulmonary hypertension or pulmonary embolism), early emphysema (destruction of alveolar-capillary surface area without significant airflow obstruction yet), or anemia. The technologist should verify the hemoglobin level for DLCO correction and confirm test quality.',
        difficulty: 3,
        topic: 'Board-Style Integration',
        isFree: false,
        orderIndex: 391,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'During spirometry, a patient produces an FEV1 of 2.5 L on the first attempt but values of 1.8 L on the next four attempts with good effort. What should the technologist consider?',
        answer: 'This pattern of declining FEV1 with repeated efforts may indicate exercise-induced bronchospasm triggered by the forced maneuvers, or it could suggest vocal cord dysfunction. The technologist should note the pattern, consider allowing additional rest between maneuvers, and alert the physician. The highest acceptable value (2.5 L) is reported, but the pattern of decline should be documented as clinically significant.',
        difficulty: 3,
        topic: 'Board-Style Integration',
        isFree: false,
        orderIndex: 392,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient undergoing a 6MWT has a baseline SpO2 of 95% on room air. At minute 3, SpO2 drops to 82%, but the patient reports only mild dyspnea (Borg 3/10). What should the technologist do?',
        answer: 'The technologist should stop the test because SpO2 has dropped below 85% (or 80% depending on protocol), which is an absolute stop criterion regardless of symptom severity. Document the distance walked, the desaturation nadir, recovery time, and vital signs. The disconnect between severe desaturation and mild symptoms may suggest chronic hypoxemia adaptation and should be communicated to the physician.',
        difficulty: 2,
        topic: 'Board-Style Integration',
        isFree: false,
        orderIndex: 393,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient has the following results: FVC 60% predicted, FEV1 62% predicted, FEV1/FVC 82%, TLC 58% predicted, and DLCO 55% predicted. After bronchodilator, FVC improves to 68% predicted. What is the interpretation?',
        answer: 'This is a restrictive pattern: reduced FVC and TLC with a preserved or elevated FEV1/FVC ratio. DLCO is reduced proportionally, consistent with parenchymal restriction (interstitial lung disease, chest wall disease). The modest bronchodilator response does not change the classification. The restriction is confirmed by the reduced TLC. Combined findings suggest interstitial or parenchymal disease.',
        difficulty: 2,
        topic: 'Board-Style Integration',
        isFree: false,
        orderIndex: 394,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'During CPET, a patient achieves 95% of predicted max heart rate, breathing reserve of 40%, but VO2max is only 60% predicted. Oxygen pulse plateaus at 8 mL/beat. What is the most likely cause of exercise limitation?',
        answer: 'The normal breathing reserve (40%) excludes pulmonary limitation. Achieving 95% predicted max heart rate indicates adequate effort. The reduced VO2max with an early oxygen pulse plateau suggests cardiovascular limitation — specifically impaired stroke volume response (possible left ventricular dysfunction, ischemia, or valvular disease). The cardiac output cannot increase sufficiently to meet metabolic demand.',
        difficulty: 3,
        topic: 'Board-Style Integration',
        isFree: false,
        orderIndex: 395,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient\'s FeNO is 72 ppb, spirometry shows FEV1 92% predicted with FEV1/FVC 80%, and methacholine challenge is positive at PC20 of 2 mg/mL. What do these results collectively suggest?',
        answer: 'These results collectively confirm asthma: elevated FeNO (>50 ppb) indicates eosinophilic airway inflammation, normal baseline spirometry is common in mild-to-moderate asthma between exacerbations, and a positive methacholine challenge at a low PC20 (2 mg/mL) confirms bronchial hyperresponsiveness. This patient has eosinophilic asthma with significant hyperreactivity and would likely respond well to inhaled corticosteroids.',
        difficulty: 2,
        topic: 'Board-Style Integration',
        isFree: false,
        orderIndex: 396,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'An ABG drawn from a patient on a ventilator shows pH 7.48, PaCO2 30 mmHg, PaO2 110 mmHg, HCO3 22 mEq/L, on FiO2 0.40. The technologist notices small air bubbles in the syringe. How might the air bubbles have affected these results?',
        answer: 'Air bubbles would increase PaO2 (toward ~150 mmHg ambient PO2) and decrease PaCO2 (toward ~0 mmHg ambient PCO2). However, the results already show respiratory alkalosis (low PaCO2, high pH) which could be clinical. The elevated PaO2 of 110 on 40% FiO2, while possible, could be slightly inflated by air contamination. The sample should be redrawn if clinical decisions depend on precise PaO2 values. The pH elevation is unlikely to be caused by air bubbles alone.',
        difficulty: 3,
        topic: 'Board-Style Integration',
        isFree: false,
        orderIndex: 397,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient with neuromuscular disease has FVC 50% predicted in the upright position and 32% predicted when supine. MIP is −25 cmH2O. What do these findings indicate?',
        answer: 'A drop in FVC of >20-25% from upright to supine strongly suggests diaphragm weakness or paralysis, because in the supine position the abdominal contents push against the weakened diaphragm. The severely reduced MIP (−25 cmH2O) confirms marked inspiratory muscle weakness. This patient is at high risk for nocturnal hypoventilation and respiratory failure, and may need noninvasive ventilatory support, especially during sleep.',
        difficulty: 3,
        topic: 'Board-Style Integration',
        isFree: false,
        orderIndex: 398,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A technologist is calibrating a body plethysmograph and the measured volume of the 3-liter calibration syringe consistently reads 2.85 L. What should the technologist do?',
        answer: 'A reading of 2.85 L represents a 5% error, which exceeds the acceptable ±3% (or ±3.5% per some standards) tolerance. The technologist should NOT proceed with patient testing. Troubleshooting steps include: checking for leaks in the system, verifying the syringe itself is accurate, checking transducer calibration, inspecting tubing connections, and ensuring the box door seal is intact. Re-calibration and verification must succeed before clinical testing resumes.',
        difficulty: 2,
        topic: 'Board-Style Integration',
        isFree: false,
        orderIndex: 399,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient referred for pre-operative PFTs before lung resection surgery has: FEV1 1.8 L (65% predicted), DLCO 60% predicted. The surgeon wants to know if the patient can tolerate a right pneumonectomy. The right lung receives 55% of perfusion on quantitative perfusion scan. What is the predicted post-operative FEV1?',
        answer: 'Predicted post-operative (ppo) FEV1 = pre-operative FEV1 × (1 − fraction of perfusion to the resected lung). ppoFEV1 = 1.8 × (1 − 0.55) = 1.8 × 0.45 = 0.81 L. This is approximately 29% predicted, which falls below the generally accepted threshold of 40% predicted (or 0.8 L absolute) for pneumonectomy, suggesting high surgical risk. Additional testing such as CPET for ppoVO2max would be recommended before final surgical decision.',
        difficulty: 3,
        topic: 'Board-Style Integration',
        isFree: false,
        orderIndex: 400,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
    ],
    skipDuplicates: true,
  })

  console.log('Successfully seeded 100 CPFT flashcards (batch 4).')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
