import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const NPS_DIVISION_ID = 'cmsm41fvb0001zf54yp8r6skl'

const flashcards = [
  // ============================================================
  // NEONATAL PHARMACOLOGY (cards 201-220)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the loading dose and maintenance dose for caffeine citrate in preterm infants?',
    answer: 'The loading dose of caffeine citrate is 20 mg/kg intravenously or orally (equivalent to 10 mg/kg of caffeine base). The maintenance dose is 5 to 10 mg/kg/day of caffeine citrate (2.5 to 5 mg/kg/day of caffeine base) given once daily, started 24 hours after the loading dose. Therapeutic serum levels range from 5 to 25 mcg/mL. Caffeine citrate is twice the weight of caffeine base, so clinicians must verify whether the ordered dose refers to the citrate salt or the base.',
    difficulty: 2,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 201,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the primary pharmacologic effects of caffeine in preterm neonates?',
    answer: 'Caffeine is a methylxanthine that stimulates the central respiratory drive by antagonizing adenosine receptors in the brainstem. It increases minute ventilation, enhances chemoreceptor sensitivity to carbon dioxide, improves diaphragmatic contractility, and reduces periodic breathing. Beyond treating apnea of prematurity, large trials have shown caffeine decreases the incidence of BPD, shortens the duration of mechanical ventilation, and improves neurodevelopmental outcomes at 18 to 24 months.',
    difficulty: 1,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 202,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is doxapram and when is it used in neonatal care?',
    answer: 'Doxapram is a respiratory stimulant that acts on both peripheral chemoreceptors (carotid body) and central medullary respiratory centers to increase tidal volume and respiratory rate. It is used as a second-line agent for apnea of prematurity that is refractory to caffeine therapy. Doxapram is administered as a continuous intravenous infusion. Side effects include jitteriness, irritability, hypertension, tachycardia, abdominal distension, and hyperglycemia. Its use varies by institution and is not universally available.',
    difficulty: 3,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 203,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does sildenafil work in the treatment of persistent pulmonary hypertension of the newborn?',
    answer: 'Sildenafil is a phosphodiesterase type 5 (PDE-5) inhibitor that prevents the breakdown of cyclic GMP in pulmonary vascular smooth muscle cells. By maintaining elevated cyclic GMP levels, sildenafil promotes sustained pulmonary vasodilation. It is used as an adjunct to inhaled nitric oxide or when iNO is not available, particularly in resource-limited settings. It can be given orally or intravenously. Common side effects include systemic hypotension and feeding intolerance.',
    difficulty: 2,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 204,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is milrinone and what role does it play in neonatal cardiac management?',
    answer: 'Milrinone is a phosphodiesterase type 3 inhibitor (inodilator) that increases cardiac contractility through elevated intracellular cyclic AMP and produces both systemic and pulmonary vasodilation. In neonates, it is used for low cardiac output syndrome after cardiac surgery, as adjunctive therapy in PPHN (especially when right ventricular dysfunction is present), and for hemodynamic support in septic shock with myocardial depression. It is given as a continuous intravenous infusion with careful monitoring for systemic hypotension and thrombocytopenia.',
    difficulty: 3,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 205,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the starting infusion rate for prostaglandin E1 and what are its major side effects?',
    answer: 'Prostaglandin E1 (alprostadil) is initiated at 0.05 to 0.1 mcg/kg/min intravenously to maintain ductal patency in duct-dependent congenital heart lesions. Once the ductus arteriosus reopens or stabilizes, the infusion may be decreased to the lowest effective rate, often 0.01 to 0.03 mcg/kg/min. Major side effects include apnea (occurring in 10 to 12 percent of neonates, more common in those under 2 kg), hypotension, fever, and jitteriness. Intubation equipment must be immediately available when starting the infusion.',
    difficulty: 2,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 206,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Why is prostaglandin E1 essential in certain congenital heart defects?',
    answer: 'PGE1 maintains patency of the ductus arteriosus, which is critical for survival in duct-dependent lesions. In right-sided obstructive lesions (pulmonary atresia, critical pulmonary stenosis, tricuspid atresia), the PDA provides the only source of pulmonary blood flow. In left-sided obstructive lesions (hypoplastic left heart syndrome, critical coarctation, interrupted aortic arch), the PDA provides systemic blood flow. In transposition of the great arteries, ductal patency promotes mixing of oxygenated and deoxygenated blood until surgical correction.',
    difficulty: 1,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 207,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How do indomethacin and ibuprofen differ in their approach to pharmacologic PDA closure?',
    answer: 'Both are cyclooxygenase inhibitors that reduce prostaglandin synthesis to promote ductal constriction. Indomethacin is given intravenously in three doses every 12 to 24 hours, with dosing adjusted by postnatal age. Ibuprofen lysine is given as three IV doses (10 mg/kg then 5 mg/kg at 24 and 48 hours). Ibuprofen produces equivalent closure rates but with less reduction in renal, mesenteric, and cerebral blood flow compared to indomethacin. Both carry risks of oliguria, NEC, and gastrointestinal perforation.',
    difficulty: 2,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 208,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the contraindications to pharmacologic PDA closure with NSAIDs?',
    answer: 'Contraindications include active or recent significant bleeding (especially intraventricular hemorrhage within 48 hours), thrombocytopenia (platelets below 50,000), proven or suspected necrotizing enterocolitis, significant renal impairment (elevated creatinine, oliguria less than 1 mL/kg/hr), untreated infection, and duct-dependent congenital heart disease where systemic or pulmonary blood flow relies on the PDA. Coagulation disorders and hyperbilirubinemia requiring exchange transfusion are additional relative contraindications.',
    difficulty: 2,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 209,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are antenatal corticosteroids and when should they be administered?',
    answer: 'Antenatal corticosteroids (betamethasone or dexamethasone) are given to pregnant women at risk of preterm delivery between 24 and 34 weeks gestation to accelerate fetal lung maturation. Betamethasone is given as two intramuscular doses of 12 mg each, 24 hours apart. Dexamethasone is given as four 6 mg doses every 12 hours. Optimal benefit occurs when delivery happens between 24 hours and 7 days after the first dose. They reduce the incidence and severity of RDS, intraventricular hemorrhage, and neonatal mortality.',
    difficulty: 1,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 210,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the risks and benefits of postnatal dexamethasone in the prevention of BPD?',
    answer: 'Postnatal systemic dexamethasone reduces inflammation, improves pulmonary compliance, and facilitates earlier extubation in ventilator-dependent preterm infants. However, it is associated with significant adverse effects including hyperglycemia, hypertension, gastrointestinal perforation, infection, poor weight gain, and most concerning, impaired neurodevelopmental outcomes with increased risk of cerebral palsy. Current guidelines recommend reserving systemic dexamethasone for infants who cannot be weaned from mechanical ventilation after the first 7 to 14 days of life, using the lowest effective dose for the shortest duration.',
    difficulty: 3,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 211,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is hydrocortisone used as an alternative to dexamethasone in neonatal BPD prevention?',
    answer: 'Low-dose hydrocortisone (starting at 0.5 to 1 mg/kg/day, tapered over 10 to 14 days) begun in the first postnatal week has been studied as a less potent alternative to dexamethasone for BPD prevention. It has shown modest reduction in BPD risk without the significant neurodevelopmental concerns associated with dexamethasone. However, concurrent use with indomethacin increases the risk of gastrointestinal perforation, so the two drugs should not be given simultaneously. Hydrocortisone also provides physiologic stress-dose cortisol replacement for infants with relative adrenal insufficiency.',
    difficulty: 3,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 212,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What opioid analgesics are commonly used in the NICU and what are their key differences?',
    answer: 'Fentanyl and morphine are the primary opioids used in the NICU. Morphine has a slower onset (5 to 10 minutes IV), longer duration (3 to 5 hours), and causes more histamine release leading to hypotension and bronchospasm. Fentanyl has a rapid onset (1 to 2 minutes IV), shorter duration (30 to 60 minutes for single doses), and produces less hemodynamic instability, making it preferred in critically ill neonates. Both cause respiratory depression, urinary retention, decreased gut motility, and tolerance with prolonged use. Chest wall rigidity can occur with rapid fentanyl boluses.',
    difficulty: 2,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 213,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What neonatal abstinence syndrome develops from prolonged opioid exposure and how is it managed?',
    answer: 'Neonatal abstinence syndrome (NAS) or iatrogenic withdrawal presents with irritability, high-pitched cry, tremors, hypertonicity, poor feeding, vomiting, diarrhea, tachypnea, yawning, sneezing, and autonomic instability. It develops after prolonged opioid infusions (typically more than 5 to 7 days). Management involves gradual weaning of the opioid (reducing dose by 10 to 20 percent per day), transitioning from IV to enteral opioid (methadone or morphine), environmental modifications (swaddling, reduced stimulation), and scoring with tools such as the Finnegan scale to guide therapy adjustments.',
    difficulty: 2,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 214,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the role of midazolam in neonatal sedation and what are its risks?',
    answer: 'Midazolam is a short-acting benzodiazepine used for procedural sedation and as an adjunct for continuous sedation in mechanically ventilated neonates. It provides anxiolysis, amnesia, and muscle relaxation but has no analgesic properties. Risks include respiratory depression, paradoxical agitation, hypotension (especially when combined with opioids), and myoclonus that may be mistaken for seizures. Continuous midazolam infusions in preterm infants have been associated with adverse neurological outcomes and are generally avoided. It should not be used as a first-line sedative agent in neonates.',
    difficulty: 3,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 215,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is oral sucrose used for procedural pain management in neonates?',
    answer: 'Oral sucrose (24 percent solution) is placed on the anterior tongue 2 minutes before a painful procedure such as heel lance, venipuncture, or immunization. The sweet taste activates endogenous opioid pathways, reducing pain responses measured by validated pain scales. The dose is 0.1 to 0.5 mL for preterm infants and up to 1 to 2 mL for term neonates. The analgesic effect lasts approximately 5 to 8 minutes. Combining sucrose with nonnutritive sucking (pacifier) provides additive pain reduction. It is ineffective for prolonged or surgical pain.',
    difficulty: 1,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 216,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What validated pain assessment tools are used in the NICU?',
    answer: 'The CRIES scale (Crying, Requires oxygen, Increased vital signs, Expression, Sleeplessness) is used for postoperative pain in neonates. The PIPP-R (Premature Infant Pain Profile-Revised) assesses acute procedural pain incorporating gestational age, behavioral state, heart rate changes, oxygen saturation changes, brow bulge, eye squeeze, and nasolabial furrow. The N-PASS (Neonatal Pain, Agitation and Sedation Scale) evaluates both pain/agitation and sedation levels. Regular pain assessment using a validated tool guides appropriate pharmacologic and non-pharmacologic interventions.',
    difficulty: 1,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 217,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the mechanism of action and clinical use of inhaled epinephrine for neonatal stridor?',
    answer: 'Inhaled racemic epinephrine (2.25 percent solution, 0.5 mL diluted in 3 mL normal saline) or L-epinephrine (1:1000, 0.5 mL/kg up to 5 mL) acts on alpha-adrenergic receptors in the subglottic mucosa to produce vasoconstriction, reducing mucosal edema and improving airflow. In neonates, it is used for post-extubation stridor and subglottic edema. The effect begins within minutes and lasts 1 to 2 hours, after which rebound edema may occur. Patients should be observed for at least 2 to 4 hours after administration for recurrence of symptoms.',
    difficulty: 2,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 218,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What neuromuscular blocking agents are used in neonatal intensive care and what monitoring is required?',
    answer: 'Vecuronium and pancuronium are nondepolarizing neuromuscular blockers used to facilitate mechanical ventilation in neonates with refractory hypoxemia, active air leak syndromes, or during surgical procedures. Pancuronium has a longer duration and may cause tachycardia and hypertension. Vecuronium has fewer cardiovascular effects and shorter duration. Since these agents eliminate voluntary muscle movement but have no sedative or analgesic properties, concurrent sedation and analgesia must always be provided. Train-of-four monitoring assesses the degree of paralysis.',
    difficulty: 3,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 219,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the role of diuretics in the management of neonatal chronic lung disease?',
    answer: 'Furosemide (a loop diuretic) is used acutely at 1 to 2 mg/kg/dose to reduce pulmonary edema and improve lung compliance in infants with evolving or established BPD. Chronic diuretic therapy uses chlorothiazide (20 to 40 mg/kg/day) with spironolactone (1 to 3 mg/kg/day) to minimize electrolyte losses. Furosemide carries risks of hypokalemia, hyponatremia, hypochloremic metabolic alkalosis, hypercalciuria leading to nephrocalcinosis, and ototoxicity. Electrolytes, calcium, and renal ultrasound should be monitored during prolonged diuretic therapy.',
    difficulty: 2,
    topic: 'Neonatal Pharmacology',
    isFree: false,
    orderIndex: 220,
  },

  // ============================================================
  // NEONATAL FLUID & ELECTROLYTE MANAGEMENT (cards 221-235)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the typical fluid requirements for term neonates during the first week of life?',
    answer: 'Term neonates start at approximately 60 to 80 mL/kg/day on the first day of life, advancing by 10 to 20 mL/kg/day to reach 120 to 150 mL/kg/day by day 4 to 7. Initial fluids are usually dextrose 10 percent in water (D10W) without added electrolytes for the first 24 hours, then sodium and potassium are added once urine output is established and serum electrolytes are confirmed. The goal is to allow a physiologic weight loss of 5 to 7 percent of birth weight during the first few days while maintaining adequate hydration and urine output of 1 to 3 mL/kg/hr.',
    difficulty: 1,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 221,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How do fluid requirements differ for extremely preterm infants compared to term neonates?',
    answer: 'Extremely preterm infants (less than 28 weeks gestation) have significantly higher fluid requirements due to increased insensible water loss from their thin, immature skin with high transepidermal water loss, larger body surface area to weight ratio, and immature renal concentrating ability. Initial fluid rates may start at 80 to 120 mL/kg/day or higher. Expected weight loss may be 10 to 15 percent of birth weight. Fluid management must be individualized based on serial weights, serum sodium, urine output, and urine specific gravity.',
    difficulty: 2,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 222,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What factors increase insensible water loss in preterm neonates?',
    answer: 'Insensible water loss is increased by lower gestational age (thinner skin with poor keratinization), open radiant warmers compared to humidified incubators, low ambient humidity, phototherapy (increases IWL by 30 to 50 percent), elevated body temperature, tachypnea, and skin breakdown or defects. Strategies to reduce insensible water loss include using humidified incubators at 80 to 90 percent humidity for the first week, applying transparent adhesive skin barriers in extremely preterm infants, and using plastic wrapping or bags immediately after delivery.',
    difficulty: 2,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 223,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Why is polyethylene wrap or bag used for extremely preterm infants immediately after birth?',
    answer: 'Polyethylene wrapping (placing the infant in a food-grade plastic bag or wrap from the neck down without drying first) immediately after delivery prevents evaporative heat and water loss through the immature skin. This is standard practice for infants born below 32 weeks gestation as part of thermoregulation guidelines. Studies demonstrate improved admission temperatures, reduced hypothermia, and decreased insensible water loss. The wrap remains in place until the infant is in a humidified incubator. It does not replace other warming measures such as radiant heat and warmed surfaces.',
    difficulty: 1,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 224,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the normal serum sodium levels in neonates and what causes hypernatremia?',
    answer: 'Normal neonatal serum sodium is 135 to 145 mEq/L. Hypernatremia (above 145 mEq/L) in the first postnatal days is most commonly caused by inadequate free water intake relative to insensible losses, especially in very preterm infants on radiant warmers or phototherapy. Other causes include excessive sodium administration in IV fluids or sodium bicarbonate boluses, diabetes insipidus, and osmotic diuresis from glucosuria. Signs include lethargy, hypotonia, seizures, and intracranial hemorrhage from brain shrinkage and vessel tearing. Correction should be gradual (no faster than 0.5 mEq/L per hour) to avoid cerebral edema.',
    difficulty: 2,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 225,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the causes and clinical significance of hyponatremia in neonates?',
    answer: 'Hyponatremia (serum sodium below 130 mEq/L) in neonates results from excessive free water administration, dilutional causes (SIADH from pneumothorax, IVH, meningitis, or positive pressure ventilation), renal sodium losses (immature tubular function in preterms, diuretic therapy), and inadequate sodium supplementation in growing preterm infants. Chronic hyponatremia impairs growth. Acute severe hyponatremia (below 120 mEq/L) causes lethargy, seizures, and cerebral edema. Correction should not exceed 10 to 12 mEq/L per 24 hours to prevent osmotic demyelination.',
    difficulty: 3,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 226,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'When should potassium supplementation be started in neonatal IV fluids?',
    answer: 'Potassium is typically withheld from IV fluids until adequate urine output is established (at least 1 mL/kg/hr) and the initial serum potassium level is confirmed to be within normal range. Preterm infants frequently develop nonoliguric hyperkalemia in the first 24 to 72 hours due to transcellular potassium shifts from immature sodium-potassium ATPase function, acidosis, and catabolism. Once renal function is established and potassium levels normalize, supplementation at 1 to 2 mEq/kg/day is added to maintenance fluids. Serum potassium should be monitored every 6 to 12 hours in the first days of life.',
    difficulty: 2,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 227,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the clinical manifestations and treatment of nonoliguric hyperkalemia in preterm neonates?',
    answer: 'Nonoliguric hyperkalemia (potassium above 6.5 mEq/L despite adequate urine output) typically occurs in the first 24 to 72 hours after birth in extremely preterm infants. ECG changes include peaked T waves, widened QRS, and potentially fatal arrhythmias. Treatment includes discontinuing all potassium sources, IV calcium gluconate (10 percent, 1 to 2 mL/kg) for cardiac membrane stabilization, sodium bicarbonate (1 to 2 mEq/kg) or insulin with glucose infusion (0.1 unit/kg insulin with 2 mL/kg D10W) to shift potassium intracellularly, and albuterol nebulization. Kayexalate is used with caution due to NEC risk.',
    difficulty: 3,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 228,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the signs and causes of hypocalcemia in neonates?',
    answer: 'Neonatal hypocalcemia is defined as total calcium below 7 mg/dL (or ionized calcium below 4 mg/dL, 1.0 mmol/L). Early-onset hypocalcemia (first 72 hours) occurs in preterm infants, infants of diabetic mothers, and birth asphyxia due to interrupted placental calcium supply and immature parathyroid function. Late-onset hypocalcemia is associated with high phosphate intake (cow milk formulas), maternal vitamin D deficiency, or hypoparathyroidism (DiGeorge syndrome). Signs include jitteriness, tremors, seizures, laryngospasm, prolonged QT interval, and poor feeding.',
    difficulty: 2,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 229,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is symptomatic neonatal hypocalcemia treated?',
    answer: 'Acute symptomatic hypocalcemia (with seizures or cardiac arrhythmias) is treated with slow IV infusion of 10 percent calcium gluconate at 1 to 2 mL/kg (100 to 200 mg/kg) over 10 to 20 minutes with continuous cardiac monitoring for bradycardia. The infusion must be given slowly through a central or well-functioning peripheral IV because extravasation causes severe tissue necrosis and calcification. Maintenance calcium supplementation (oral or IV at 50 to 75 mg/kg/day of elemental calcium) follows the acute correction. Magnesium levels should also be checked since hypomagnesemia can cause refractory hypocalcemia.',
    difficulty: 2,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 230,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is metabolic bone disease of prematurity and what are its risk factors?',
    answer: 'Metabolic bone disease of prematurity (also called osteopenia of prematurity) is inadequate bone mineralization resulting from insufficient calcium and phosphorus accretion after preterm birth. The majority of fetal calcium and phosphorus accretion occurs during the third trimester, which is lost when birth occurs prematurely. Risk factors include extreme prematurity, prolonged TPN without adequate mineral supplementation, chronic furosemide use (increases urinary calcium loss), delayed enteral feeding, vitamin D deficiency, and use of unfortified breast milk without mineral supplementation.',
    difficulty: 1,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 231,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is metabolic bone disease of prematurity diagnosed and prevented?',
    answer: 'Diagnosis involves monitoring serum alkaline phosphatase (elevated above 500 to 800 IU/L suggests significant demineralization), serum phosphorus (often low, below 4 mg/dL), and serum calcium. Radiographic findings of osteopenia and fractures appear late. Prevention includes early initiation of human milk fortifier or preterm formula with adequate calcium (120 to 200 mg/kg/day) and phosphorus (60 to 100 mg/kg/day), vitamin D supplementation (400 IU daily), minimizing furosemide use, and encouraging gentle physical activity (passive range of motion) to promote bone mineralization.',
    difficulty: 3,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 232,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the syndrome of inappropriate antidiuretic hormone secretion in neonates?',
    answer: 'SIADH occurs when excessive ADH release causes water retention and dilutional hyponatremia with urine that is inappropriately concentrated relative to the low serum osmolality. In neonates, triggers include pneumothorax, intracranial hemorrhage, meningitis, asphyxia, pneumonia, and positive pressure ventilation. Laboratory findings include low serum sodium, low serum osmolality (below 280 mOsm/kg), high urine osmolality (above serum), and elevated urine sodium. Management centers on fluid restriction (typically 60 to 75 percent of maintenance) and treating the underlying cause.',
    difficulty: 3,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 233,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does glucose homeostasis differ in preterm versus term neonates?',
    answer: 'Preterm infants are prone to hypoglycemia due to limited glycogen and fat stores, immature hepatic gluconeogenesis and glycogenolysis, and relatively high metabolic demands. Conversely, they frequently develop hyperglycemia (above 150 mg/dL) because of insulin resistance, limited insulin secretion, and the glucose infusion rates required in parenteral nutrition. Term neonates generally have adequate glycogen stores but remain at risk in the first hours after birth until enteral feeding is established. Infants of diabetic mothers are at particular risk for rebound hypoglycemia from hyperinsulinism.',
    difficulty: 3,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 234,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the glucose infusion rate calculation and what values are targeted in neonates?',
    answer: 'The glucose infusion rate (GIR) is calculated as: GIR (mg/kg/min) = [IV rate (mL/hr) x dextrose concentration (g/dL)] / [6 x weight (kg)]. Neonates typically require a GIR of 4 to 6 mg/kg/min initially to maintain euglycemia (blood glucose 50 to 110 mg/dL). Preterm infants may need adjustments up to 8 to 12 mg/kg/min for persistent hypoglycemia. Persistent hypoglycemia despite GIR above 12 mg/kg/min suggests hyperinsulinism and warrants endocrine evaluation. GIR is modified by changing the IV rate, dextrose concentration, or both.',
    difficulty: 3,
    topic: 'Neonatal Fluid & Electrolyte Management',
    isFree: false,
    orderIndex: 235,
  },

  // ============================================================
  // PEDIATRIC PULMONARY DISEASE (cards 236-255)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the PALICC criteria for pediatric acute respiratory distress syndrome?',
    answer: 'The Pediatric Acute Lung Injury Consensus Conference (PALICC) criteria define pediatric ARDS as: acute onset within 7 days of a known clinical insult, respiratory failure not fully explained by cardiac disease or fluid overload, new chest imaging consistent with parenchymal lung disease (bilateral opacities), and impaired oxygenation. Severity is classified using the oxygenation index (OI) or oxygen saturation index (OSI): mild (OI 4 to less than 8 or OSI 5 to less than 7.5), moderate (OI 8 to less than 16 or OSI 7.5 to less than 12.3), severe (OI 16 or greater or OSI 12.3 or greater).',
    difficulty: 2,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 236,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How do the PALICC criteria for pediatric ARDS differ from the adult Berlin definition?',
    answer: 'Key differences include: PALICC uses oxygenation index (OI) or oxygen saturation index (OSI) for severity stratification rather than PaO2/FiO2 ratio alone, allowing noninvasive assessment via pulse oximetry. PALICC does not require bilateral infiltrates on chest imaging in unilateral lung disease with a known trigger. PALICC applies to patients on any form of mechanical ventilation (including noninvasive support with CPAP 5 cm H2O or greater) rather than requiring invasive ventilation with a minimum PEEP. The age range excludes perinatal-related lung disease.',
    difficulty: 3,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 237,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What ventilatory strategies are recommended for pediatric ARDS?',
    answer: 'Lung-protective ventilation is the cornerstone: tidal volumes of 5 to 8 mL/kg ideal body weight (3 to 6 mL/kg for patients with poor respiratory compliance), plateau pressures below 28 to 32 cm H2O, moderate PEEP titrated to optimize recruitment and oxygenation, permissive hypercapnia (pH above 7.20) when necessary, and FiO2 titrated to maintain SpO2 of 92 to 97 percent. Prone positioning improves oxygenation in severe cases. HFOV is considered rescue therapy when conventional ventilation fails. Exogenous surfactant has not shown consistent benefit in pediatric ARDS.',
    difficulty: 2,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 238,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the oxygenation index and how is it calculated?',
    answer: 'The oxygenation index (OI) quantifies the severity of hypoxemic respiratory failure relative to the ventilatory support required. OI = (mean airway pressure x FiO2 x 100) / PaO2. A higher OI indicates worse oxygenation requiring greater ventilatory support. An OI above 25 in neonatal PPHN often prompts consideration of inhaled nitric oxide. An OI above 40, sustained and refractory, is an indication for extracorporeal membrane oxygenation. The oxygen saturation index (OSI) substitutes SpO2 for PaO2 when arterial access is unavailable: OSI = (mean airway pressure x FiO2 x 100) / SpO2.',
    difficulty: 1,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 239,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the indications for prone positioning in pediatric ARDS?',
    answer: 'Prone positioning is indicated for moderate to severe pediatric ARDS (OI 8 or greater) when oxygenation remains inadequate despite optimized conventional ventilation. Benefits include improved ventilation-perfusion matching by redistributing perfusion to better-ventilated anterior lung regions, reduced atelectasis in dorsal lung segments, decreased chest wall compliance promoting more homogeneous ventilation, and improved drainage of secretions. Sessions of 12 to 16 hours are recommended. Contraindications include unstable spine injuries, recent abdominal surgery, and hemodynamic instability that precludes repositioning.',
    difficulty: 2,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 240,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'When is pediatric lung transplantation considered and what are the primary indications?',
    answer: 'Pediatric lung transplantation is considered when life expectancy is less than 2 years despite maximal medical therapy, the underlying condition is isolated to the lungs (or combined heart-lung transplant for cardiac involvement), and the child has acceptable nutritional status and psychosocial support. Primary indications include cystic fibrosis (the most common reason in children over 6 years), idiopathic pulmonary arterial hypertension, interstitial lung disease, obliterative bronchiolitis following stem cell transplant, and surfactant protein deficiency disorders in infancy.',
    difficulty: 3,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 241,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is primary ciliary dyskinesia and how does it present in children?',
    answer: 'Primary ciliary dyskinesia (PCD) is an autosomal recessive disorder characterized by dysmotile or immotile cilia throughout the body. Respiratory manifestations include chronic wet cough from birth, recurrent sinusitis and otitis media, progressive bronchiectasis, and neonatal respiratory distress in approximately 75 percent of affected newborns. About 50 percent have situs inversus totalis (Kartagener syndrome when combined with bronchiectasis and sinusitis). Diagnosis requires nasal nitric oxide measurement (characteristically very low), high-speed video microscopy of ciliary beat pattern, and transmission electron microscopy of ciliary ultrastructure.',
    difficulty: 2,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 242,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is primary ciliary dyskinesia managed from a respiratory perspective?',
    answer: 'There is no cure for PCD. Respiratory management focuses on aggressive airway clearance using chest physiotherapy, oscillatory PEP devices, high-frequency chest wall oscillation, and exercise. Prompt antibiotic treatment of respiratory infections prevents progressive lung damage. Regular sputum cultures guide antibiotic selection, as patients frequently become colonized with Haemophilus influenzae, Staphylococcus aureus, and eventually Pseudomonas aeruginosa. Routine monitoring with pulmonary function testing and periodic chest CT helps track disease progression. Lung transplantation is an option for end-stage disease.',
    difficulty: 2,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 243,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is a congenital pulmonary airway malformation and how is it classified?',
    answer: 'Congenital pulmonary airway malformation (CPAM, formerly CCAM) is a developmental anomaly consisting of abnormal lung tissue with cystic or adenomatous overgrowth. Type 0 involves the trachea or bronchi and is typically lethal. Type 1 (most common, 60 to 70 percent) features large cysts (greater than 2 cm) and has the best prognosis. Type 2 has smaller cysts (less than 2 cm) and is often associated with other anomalies. Type 3 presents as a solid, bulky mass causing mediastinal shift. Type 4 contains large peripheral cysts. Most are diagnosed prenatally by ultrasound.',
    difficulty: 3,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 244,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What respiratory complications can occur with congenital pulmonary airway malformation?',
    answer: 'CPAMs can cause respiratory distress at birth from mass effect with mediastinal shift and lung compression, hydrops fetalis in large lesions due to venous obstruction, recurrent pneumonias from poor drainage and air trapping within cystic spaces, pneumothorax from ruptured cysts, and there is a small but recognized risk of malignant transformation (pleuropulmonary blastoma). Many smaller asymptomatic lesions are discovered incidentally on imaging. Surgical resection (lobectomy) is generally recommended even for asymptomatic lesions to prevent infection and malignancy.',
    difficulty: 2,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 245,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is pulmonary sequestration and how does it differ from CPAM?',
    answer: 'Pulmonary sequestration is a mass of nonfunctioning lung tissue that does not communicate with the normal tracheobronchial tree and receives its blood supply from an aberrant systemic artery (usually from the aorta). Intralobar sequestrations (75 percent) are within the visceral pleura, drain via pulmonary veins, and present with recurrent infections. Extralobar sequestrations have their own pleural covering, drain via systemic veins, and are often discovered incidentally or prenatally. Unlike CPAM, sequestrations have a systemic arterial blood supply and are not connected to the airway.',
    difficulty: 3,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 246,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What defines pediatric pulmonary hypertension and what are its clinical categories?',
    answer: 'Pediatric pulmonary hypertension is defined as a mean pulmonary artery pressure greater than 20 mmHg beyond the first 3 months of life (or greater than 25 mmHg in older definitions), confirmed by cardiac catheterization. Clinical categories include Group 1 (pulmonary arterial hypertension, either idiopathic, heritable, or associated with congenital heart disease), Group 2 (left heart disease), Group 3 (chronic lung disease including BPD), Group 4 (chronic thromboembolic disease, rare in children), and Group 5 (multifactorial or unclear mechanisms). Congenital heart disease-associated PAH is the most common cause in pediatrics.',
    difficulty: 2,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 247,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does BPD-associated pulmonary hypertension develop in preterm infants?',
    answer: 'BPD-associated pulmonary hypertension results from disrupted pulmonary vascular development alongside impaired alveolarization. Chronic inflammation, oxygen toxicity, and mechanical ventilation cause abnormal muscularization of small pulmonary arteries, reduced vascular cross-sectional area, and endothelial dysfunction. The diminished pulmonary vascular bed and increased vascular reactivity elevate pulmonary vascular resistance. BPD-PH affects 15 to 25 percent of infants with moderate to severe BPD and significantly increases mortality. Screening echocardiography is recommended at 36 weeks postmenstrual age for at-risk infants.',
    difficulty: 3,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 248,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What pharmacologic therapies are used for pediatric pulmonary arterial hypertension?',
    answer: 'Treatment targets three vasodilatory pathways: the nitric oxide pathway with PDE-5 inhibitors (sildenafil, tadalafil) and soluble guanylate cyclase stimulators (riociguat); the endothelin pathway with endothelin receptor antagonists (bosentan, ambrisentan); and the prostacyclin pathway with prostacyclin analogues (epoprostenol, treprostinil, iloprost). Combination therapy is common in moderate to severe disease. Calcium channel blockers are used only in the small subset of patients who demonstrate acute vasoreactivity during catheterization testing. Oxygen therapy targets SpO2 above 92 percent to avoid hypoxic vasoconstriction.',
    difficulty: 3,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 249,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What respiratory management principles apply to a child with pulmonary hypertension during mechanical ventilation?',
    answer: 'Goals include avoiding factors that increase pulmonary vascular resistance: hypoxemia, hypercarbia, acidosis, hypothermia, excessive lung volumes, and agitation or pain. Ventilatory strategy targets mild alkalosis or normal pH, adequate oxygenation (SpO2 above 92 percent), avoidance of excessive PEEP or mean airway pressure that compresses pulmonary vasculature, low to moderate tidal volumes, and appropriate sedation and analgesia. Inhaled nitric oxide provides selective pulmonary vasodilation during acute crises. Careful suctioning technique and pre-oxygenation prevent desaturation-triggered pulmonary hypertensive crises.',
    difficulty: 2,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 250,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is a pulmonary hypertensive crisis and how is it managed acutely?',
    answer: 'A pulmonary hypertensive crisis is a sudden, life-threatening elevation in pulmonary artery pressure with right ventricular failure, manifesting as acute hypoxemia, systemic hypotension, bradycardia, and cardiovascular collapse. Triggers include suctioning, pain, agitation, hypoxemia, acidosis, and hypothermia. Acute management includes 100 percent oxygen, sedation with neuromuscular blockade, correction of acidosis with hyperventilation or sodium bicarbonate, inhaled nitric oxide (20 ppm), IV milrinone or epoprostenol for refractory cases, and volume support for right ventricular preload. Prevention through trigger avoidance is essential.',
    difficulty: 3,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 251,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is congenital lobar emphysema and how does it present?',
    answer: 'Congenital lobar emphysema (CLE) is progressive hyperinflation of one or more lobes due to bronchial cartilage deficiency, mucus plugging, or extrinsic bronchial compression causing a ball-valve mechanism. The left upper lobe is most commonly affected (about 40 percent of cases), followed by the right middle lobe. Infants present with progressive respiratory distress, tachypnea, and unilateral hyperexpansion with mediastinal shift on chest radiograph. Mild cases may be monitored conservatively, but severe presentations with respiratory compromise require surgical lobectomy. It is important to distinguish CLE from pneumothorax on imaging.',
    difficulty: 1,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 252,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the role of flexible bronchoscopy in evaluating pediatric airway disorders?',
    answer: 'Flexible bronchoscopy allows direct visualization of airway anatomy and dynamics in spontaneously breathing or sedated children. Indications include evaluating stridor (to diagnose laryngomalacia, tracheomalacia, vocal cord paralysis, subglottic stenosis), chronic or recurrent cough, suspected airway compression from vascular rings or masses, persistent atelectasis, hemoptysis, and bronchoalveolar lavage for infectious or inflammatory sampling. It can be performed through an endotracheal tube or laryngeal mask. Complications include desaturation, bronchospasm, laryngospasm, and bleeding, requiring careful monitoring and appropriate sedation.',
    difficulty: 1,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 253,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is tracheomalacia and how does it affect ventilator management in children?',
    answer: 'Tracheomalacia is dynamic collapse of the trachea due to weakened cartilaginous support or excessive posterior membrane compliance. It causes expiratory airflow obstruction, wheezing, barking cough, and difficulty clearing secretions. In ventilated children, tracheomalacia manifests as air trapping, flow limitation during exhalation, and difficulty achieving adequate ventilation. Management strategies include using adequate PEEP (typically 8 to 12 cm H2O) to stent open the airway during expiration, longer expiratory times to reduce air trapping, and avoiding negative pressure suctioning techniques that can worsen collapse. Severe cases may require aortopexy or tracheal stenting.',
    difficulty: 2,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 254,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the impact of obesity on respiratory function in pediatric patients?',
    answer: 'Obesity reduces functional residual capacity and expiratory reserve volume through increased abdominal and chest wall mass, predisposing to atelectasis, ventilation-perfusion mismatch, and hypoxemia, especially in the supine position. Obese children have increased prevalence of obstructive sleep apnea, asthma with reduced responsiveness to standard therapy, and obesity hypoventilation syndrome. During mechanical ventilation, higher PEEP, recruitment maneuvers, and positioning (reverse Trendelenburg) may be needed. Dosing of respiratory medications should use ideal body weight rather than actual weight for many drugs to avoid toxicity.',
    difficulty: 1,
    topic: 'Pediatric Pulmonary Disease',
    isFree: false,
    orderIndex: 255,
  },

  // ============================================================
  // TRANSPORT & STABILIZATION (cards 256-270)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the essential components of a neonatal transport team?',
    answer: 'A neonatal transport team typically includes a registered nurse with NICU experience, a respiratory therapist, and a physician or neonatal nurse practitioner (who may be physically present or providing telemedicine support). The team must be trained in neonatal resuscitation, stabilization, ventilator management, and emergency procedures. Essential equipment includes a transport incubator with servo-controlled temperature regulation, portable ventilator with blender, cardiac monitor with pulse oximetry, IV pumps, emergency airway and vascular access supplies, and medications including prostaglandin E1, surfactant, and resuscitation drugs.',
    difficulty: 1,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 256,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What stabilization steps should be completed before neonatal transport?',
    answer: 'Pre-transport stabilization includes securing the airway (intubation if needed with confirmation by chest radiograph and capnography), establishing reliable vascular access (peripheral IV, umbilical lines, or intraosseous if necessary), maintaining thermal stability (prewarmed transport incubator, skin temperature probe), confirming correct ventilator settings with blood gas verification, decompressing the stomach with an orogastric tube, ensuring adequate glucose infusion, starting prostaglandin E1 for suspected duct-dependent cardiac lesions, and administering surfactant if indicated. Parental consent and communication with the receiving center should be completed.',
    difficulty: 1,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 257,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What features are important in transport ventilators used for neonatal patients?',
    answer: 'Neonatal transport ventilators must deliver accurate small tidal volumes (as low as 2 to 5 mL), have precise FiO2 control via an integrated air-oxygen blender, provide multiple modes (conventional volume and pressure modes, plus CPAP), have an internal battery with extended life (minimum 2 to 4 hours), be lightweight and compact for ambulance and aircraft mounting, tolerate vibration and altitude changes, have visible and audible alarms for high/low pressure, disconnect, and battery status, and include graphics displays for waveform monitoring. Examples include the Hamilton T1 and the Dräger Oxylog 3000 Plus.',
    difficulty: 2,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 258,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What challenges exist in maintaining neonatal temperature during transport?',
    answer: 'Temperature instability during transport is a major risk because neonates, especially preterm infants, lose heat rapidly through convection (drafts from open ambulance doors), radiation (cold vehicle walls), evaporation (wet skin or airways), and conduction (cold surfaces). Mitigation strategies include a servo-controlled transport incubator preheated before patient loading, chemical warming mattresses as backup, polyethylene wraps for extremely preterm infants, warmed and humidified inspired gases, minimizing incubator opening, insulated covers over the incubator, and continuous skin temperature monitoring with alarm thresholds set at 36.5 to 37.5 degrees Celsius.',
    difficulty: 2,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 259,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does altitude affect a neonate during air transport?',
    answer: 'As altitude increases, barometric pressure decreases according to Boyle law, causing gas expansion in enclosed body spaces. This is clinically significant for pneumothoraces (which will enlarge), bowel distension (especially in NEC or intestinal obstruction), and cuffed endotracheal tubes (cuff pressure increases, risking mucosal damage). Additionally, the reduced partial pressure of inspired oxygen at altitude can worsen hypoxemia, requiring increased FiO2. Cabin pressurization in fixed-wing aircraft typically limits altitude effects to the equivalent of 5,000 to 8,000 feet, but helicopter transport is unpressurized, requiring direct management of these physiologic changes.',
    difficulty: 2,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 260,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What specific actions should be taken before air transport of a neonate with a pneumothorax?',
    answer: 'A pneumothorax must be definitively treated with a chest tube and underwater seal or Heimlich valve before air transport. A needle aspiration alone is insufficient because air will reaccumulate and expand at altitude. The chest tube should be confirmed to be functioning with an air-tight seal and verified by repeat chest radiograph showing lung re-expansion. An untreated or unrecognized pneumothorax can become a tension pneumothorax during ascent as trapped gas expands, causing rapid hemodynamic compromise. If chest tube placement is not feasible, the transport should occur at the lowest safe altitude or with a pressurized cabin.',
    difficulty: 3,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 261,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the STABLE program and what does each letter represent?',
    answer: 'The STABLE program is a neonatal education program designed for post-resuscitation and pre-transport stabilization. Each letter represents a module: S (Sugar and Safe Care, addressing glucose management), T (Temperature, maintaining normothermia), A (Airway, ensuring adequate ventilation and oxygenation), B (Blood Pressure, assessing and managing cardiovascular stability), L (Lab Work, critical laboratory evaluations including blood gas, glucose, and hematocrit), E (Emotional Support, providing family-centered communication and support). It provides a standardized framework for community hospitals preparing sick neonates for transport to tertiary centers.',
    difficulty: 1,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 262,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What communication should occur between the referring and receiving facilities during neonatal transport?',
    answer: 'Communication includes an initial referral call with patient demographics, gestational age, diagnosis, current clinical status, interventions performed, and urgency level. The receiving medical control physician provides telephone guidance for stabilization before the team arrives. Upon transport team arrival, a structured handoff using tools like SBAR (Situation, Background, Assessment, Recommendation) occurs with the referring providers. During transport, the team maintains communication with the receiving center regarding clinical changes or complications. At arrival, a second structured handoff to the receiving team includes transport events, interventions, and current patient status.',
    difficulty: 1,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 263,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the role of point-of-care ultrasound during neonatal transport?',
    answer: 'Point-of-care ultrasound (POCUS) is increasingly used during neonatal transport for rapid clinical assessment including evaluation of endotracheal tube position, detection of pneumothorax (absent lung sliding sign), assessment of cardiac function and pericardial effusion, estimation of intravascular volume status through inferior vena cava assessment, confirmation of umbilical catheter position, and detection of pleural effusions. Portable ultrasound devices with small-footprint, high-frequency probes are suitable for the transport environment and can supplement clinical assessment when radiography is unavailable.',
    difficulty: 3,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 264,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What gas supply considerations are critical for neonatal transport?',
    answer: 'Transport teams must calculate the total gas supply needed for the anticipated transport duration plus a safety reserve (typically 30 to 60 minutes additional). The calculation accounts for ventilator flow requirements, blender consumption, and potential for escalation in oxygen needs. Compressed gas cylinders must be secured to prevent projectile hazards during vehicle movement. An air-oxygen blender is essential to avoid exposing preterm infants to unnecessarily high FiO2. Backup gas supply is required in case of primary supply failure. Teams should verify cylinder pressures and valve function during pre-transport equipment checks.',
    difficulty: 2,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 265,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How should a transport team prepare for managing a difficult airway during transport?',
    answer: 'Preparation includes carrying multiple sizes of endotracheal tubes (0.5 mm above and below the expected size), a video laryngoscope or alternative airway device (laryngeal mask airway in sizes 1 and 1.5), stylets, a bougie, and a bag-mask device with appropriate-sized masks. The team should have a pre-established difficult airway algorithm, surfactant if reintubation is needed for an RDS patient, capnography for tube confirmation, and adhesive securing devices. Repositioning and suctioning supplies must be immediately accessible. At minimum two individuals competent in neonatal intubation should be present on the transport team.',
    difficulty: 2,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 266,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the back-transport (return transport) criteria for a recovering NICU patient?',
    answer: 'Back-transport to the referring hospital is appropriate when the infant no longer requires the specialty services of the tertiary NICU. Criteria include stable respiratory status (room air or low-flow oxygen, no ventilator support), tolerating full enteral feeds with consistent weight gain, no pending surgical procedures or specialty consultations that require the tertiary center, stable thermoregulation in an open crib, and no intravenous medications. Benefits include proximity to the family (reducing travel burden), promoting parent-infant bonding, and freeing tertiary NICU capacity. Communication and a standardized handoff protocol between centers are essential.',
    difficulty: 1,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 267,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What vibration and motion concerns affect neonates during ground and air transport?',
    answer: 'Whole-body vibration during transport can cause physiologic stress in neonates, including alterations in heart rate, respiratory rate, and oxygen saturation. Specific concerns include exacerbation of intraventricular hemorrhage risk in preterm infants from repetitive head acceleration-deceleration, interference with monitoring equipment accuracy from motion artifact, potential displacement of tubes and lines from vehicular vibration, and noise exposure from ambulance sirens and helicopter rotors (exceeding 80 to 100 dB). Mitigation includes gel mattresses or air-filled mattresses within the incubator, secure fastening of all equipment, ear protection, and maintaining minimal transport speed consistent with clinical urgency.',
    difficulty: 3,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 268,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What safety considerations apply to securing a transport incubator in an ambulance or aircraft?',
    answer: 'The transport incubator and its loading system must meet federal crash test standards for ambulance-mounted equipment. The incubator is secured to the ambulance stretcher or aircraft-specific mounting system with rated restraint hardware capable of withstanding deceleration forces. All ancillary equipment (monitors, pumps, ventilator, gas cylinders) must be fastened within or to the incubator system, not placed loosely. The infant is secured within the incubator with straps or a harness. Team members must be restrained in their seats during vehicle movement. Equipment should not obstruct emergency egress paths.',
    difficulty: 1,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 269,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What quality metrics are used to evaluate a neonatal transport program?',
    answer: 'Quality metrics include response time (from referral call to team departure), time to bedside (arrival at referring facility), total transport time, unplanned events during transport (accidental extubation, equipment failure, clinical deterioration), hypothermia on arrival (admission temperature below 36.5 degrees Celsius), procedural success rates (intubation, vascular access), mortality during transport, and patient outcomes compared to inborn patients. Team performance is also assessed through crew resource management, adherence to stabilization protocols, documentation completeness, and family satisfaction surveys. Regular case review and simulation training support continuous improvement.',
    difficulty: 3,
    topic: 'Transport & Stabilization',
    isFree: false,
    orderIndex: 270,
  },

  // ============================================================
  // ETHICS & FAMILY-CENTERED CARE (cards 271-285)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the core principles of palliative care in the NICU?',
    answer: 'Core principles include symptom management to minimize pain and suffering, holistic care addressing physical, emotional, and spiritual needs of the infant and family, honest and compassionate communication about prognosis, shared decision-making that respects parental values and cultural beliefs, concurrent provision alongside curative interventions when appropriate, bereavement support for families before and after death, and interdisciplinary collaboration among physicians, nurses, respiratory therapists, social workers, chaplains, and child life specialists. Palliative care is not synonymous with withdrawing treatment but rather with ensuring comfort and quality of life.',
    difficulty: 1,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 271,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What ethical frameworks guide end-of-life decision-making in the NICU?',
    answer: 'Key ethical principles include beneficence (acting in the infant best interest), nonmaleficence (avoiding harm, including the burden of prolonged futile interventions), autonomy (respecting parental authority as surrogate decision-makers), and justice (fair allocation of resources). The best interest standard is applied when making decisions for neonates who cannot express preferences. Ethical considerations include whether continued treatment offers reasonable benefit versus prolonging suffering, prognostic uncertainty, quality of life projections, and the distinction between withholding and withdrawing treatment (considered ethically equivalent). Ethics committees provide consultation for complex cases.',
    difficulty: 2,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 272,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the difference between withdrawing and withholding life-sustaining treatment in neonates?',
    answer: 'Withholding treatment means not initiating a new intervention (such as not starting mechanical ventilation or not performing resuscitation), while withdrawing means discontinuing an intervention already in place (such as extubating a ventilator-dependent infant). Although emotionally different for caregivers, both are considered ethically and legally equivalent when the decision is based on the infant best interest. The decision process, documentation, and family involvement should be the same for both. Comfort care measures (pain management, warmth, parental holding) are always provided regardless of the decision to limit other interventions.',
    difficulty: 2,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 273,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What role do parents play in shared decision-making for critically ill neonates?',
    answer: 'Parents are recognized as the primary decision-makers for their infant, working in partnership with the medical team. Shared decision-making involves providing parents with honest, understandable information about diagnosis, prognosis, treatment options, and expected outcomes. The medical team offers recommendations based on clinical expertise while exploring the family values, cultural beliefs, religious considerations, and goals of care. Parents should never feel pressured or abandoned in the decision process. Multiple conversations over time, consistent messaging from all team members, and psychosocial support facilitate informed decisions. Decisions are documented and revisited as the clinical situation evolves.',
    difficulty: 1,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 274,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How should the respiratory therapist approach compassionate extubation in a neonate?',
    answer: 'Compassionate extubation (withdrawal of mechanical ventilation as part of comfort care) should be planned with the family and care team. Before extubation, adequate analgesia and sedation are administered to prevent distress, the environment is made private and comfortable, and parents are offered the opportunity to hold their infant. The respiratory therapist reduces ventilator support or removes the endotracheal tube based on the care plan, ensures supplemental comfort measures are available (humidified oxygen by blow-by if desired), and remains available to the team. Clear documentation of the process and clinical events is essential. Debriefing is offered to staff afterwards.',
    difficulty: 2,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 275,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the benefits of family-centered care in the NICU?',
    answer: 'Family-centered care improves outcomes for both the infant and family. Benefits include enhanced parent-infant bonding and attachment, increased parental confidence and competence in caregiving, higher rates of breastfeeding, reduced parental stress, anxiety, and depression, shorter hospital stays, improved neurodevelopmental outcomes through parental involvement in developmental care, better adherence to discharge plans, and improved staff satisfaction. Key elements include unrestricted parental access, active parental participation in care (diaper changes, feeding, bathing), parental involvement in medical rounds, and transparent communication.',
    difficulty: 1,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 276,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does cultural sensitivity affect respiratory care delivery in the NICU?',
    answer: 'Cultural sensitivity requires awareness that families from different backgrounds may have varying beliefs about medical intervention, suffering, death, gender roles in decision-making, bodily integrity, spiritual healing practices, and family structure. Some cultures may defer decisions to elders or community leaders. Language barriers necessitate professional interpreter services (never family members for medical discussions). Religious practices (baptism, blessing ceremonies, prayer rituals) should be accommodated. Cultural preferences about handling of the infant, dietary restrictions affecting expressed breast milk practices, and post-mortem rituals must be respected. Cultural competency training for all staff is essential.',
    difficulty: 2,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 277,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What bereavement support should be offered to families after a neonatal death?',
    answer: 'Bereavement support includes offering memory-making opportunities (photographs, footprints, handprints, locks of hair, naming certificates), private time with the infant, skin-to-skin contact, and involvement of siblings and extended family as desired. After death, condolence communication from the care team, referral to perinatal loss support groups, social work follow-up, and connection with chaplaincy or spiritual care should be provided. A follow-up meeting with the medical team several weeks later to review the clinical course and answer questions helps with the grieving process. Staff who cared for the infant also need emotional support through debriefing and access to employee assistance programs.',
    difficulty: 1,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 278,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the concept of moral distress in NICU healthcare providers?',
    answer: 'Moral distress occurs when a healthcare provider knows the ethically appropriate action to take but is unable to carry it out due to institutional constraints, hierarchical barriers, conflicting opinions among the care team, or legal and policy limitations. In the NICU, common sources include continuing aggressive treatment perceived as futile, disagreement with family decisions, resource allocation conflicts, and witnessing infant suffering without the authority to change the care plan. Consequences include burnout, emotional exhaustion, job dissatisfaction, and staff turnover. Mitigation strategies include ethics consultations, team debriefings, supportive leadership, and institutional forums for discussing ethical concerns.',
    difficulty: 3,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 279,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the ethical considerations surrounding resuscitation at the threshold of viability?',
    answer: 'The threshold of viability (typically 22 to 25 weeks gestation) presents ethical dilemmas because outcomes are uncertain and range from death to intact survival. Considerations include the best available outcome data for the specific gestational age, birth weight, sex, singleton versus multiple gestation, and whether antenatal corticosteroids were given. Prenatal counseling should present balanced outcome statistics, discuss the range of options from comfort care to full resuscitation, explore parental values and preferences, and acknowledge prognostic uncertainty. Some institutions allow parental choice in the gray zone while providing consistent intervention at established viability thresholds.',
    difficulty: 3,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 280,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does kangaroo care (skin-to-skin contact) benefit the parent-infant relationship in the NICU?',
    answer: 'Kangaroo care strengthens attachment through direct physical contact, stimulating oxytocin release in both parent and infant, which promotes bonding behaviors and reduces parental anxiety and depressive symptoms. It empowers parents as active caregivers rather than passive observers, increasing their sense of competency and connection. Physiologic benefits for the infant include improved cardiorespiratory stability, thermoregulation, sleep organization, and reduced pain responses. Mothers who practice kangaroo care consistently have higher breastfeeding rates and produce more breast milk. Fathers who participate show stronger paternal attachment and involvement in long-term caregiving.',
    difficulty: 1,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 281,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is a perinatal palliative care plan and when should it be initiated?',
    answer: 'A perinatal palliative care plan is a written document created during pregnancy or shortly after birth for infants diagnosed with life-limiting conditions. It outlines the family wishes regarding resuscitation at delivery, level of intervention desired, comfort care measures, pain management protocols, family involvement preferences, spiritual care needs, and memory-making activities. It should be initiated as soon as a life-limiting diagnosis is made, whether prenatally (lethal congenital anomalies, severe chromosomal abnormalities) or postnatally. The plan is a living document, updated as the clinical situation changes, and shared with all team members to ensure consistent care.',
    difficulty: 2,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 282,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the role of the respiratory therapist in family education during NICU stay?',
    answer: 'The respiratory therapist educates families about their infant respiratory condition, the purpose and function of respiratory equipment (ventilators, CPAP, oxygen delivery devices, monitors), alarm meanings and appropriate responses, and the expected trajectory of respiratory improvement. For infants requiring home respiratory equipment, the therapist provides hands-on training in equipment operation, troubleshooting, emergency procedures, CPR, and when to seek medical attention. Teaching should be tailored to the family learning style, literacy level, and preferred language, with return demonstration to verify competency. Written educational materials supplement verbal instruction.',
    difficulty: 1,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 283,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What communication strategies help families understand complex respiratory diagnoses?',
    answer: 'Effective strategies include using plain language free of medical jargon (or defining terms when used), providing information in manageable portions rather than overwhelming families at once, checking understanding through teach-back methods (asking families to explain the information in their own words), using visual aids (diagrams, models, written handouts), offering consistent messaging from all team members to avoid confusion, scheduling dedicated family meetings rather than conveying critical information during chaotic clinical moments, and providing information in the family preferred language through qualified interpreters. Acknowledging emotions and allowing time for questions demonstrate respect and build trust.',
    difficulty: 1,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 284,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the ethical implications of resource allocation in neonatal and pediatric intensive care?',
    answer: 'Resource allocation raises questions of distributive justice: how to fairly distribute limited NICU beds, specialized equipment (ECMO circuits, transport teams), expensive therapies (surfactant, iNO), and staff expertise. Ethical tension arises between the obligation to individual patients and the responsibility to the broader patient population. Decisions should be guided by transparent criteria (clinical need, likelihood of benefit), not by socioeconomic status, race, or ability to pay. Triage protocols, developed in advance with ethical oversight, help guide decisions during resource scarcity. Rationing decisions should involve institutional ethics support and be documented transparently.',
    difficulty: 3,
    topic: 'Ethics & Family-Centered Care',
    isFree: false,
    orderIndex: 285,
  },

  // ============================================================
  // INFECTION PREVENTION IN NICU (cards 286-300)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the key components of a central line-associated bloodstream infection prevention bundle in the NICU?',
    answer: 'CLABSI prevention bundles include hand hygiene before line access, maximal sterile barrier precautions during insertion (cap, mask, sterile gown, sterile gloves, full-body drape), chlorhexidine skin antisepsis (alcohol-based in infants over 2 months, aqueous chlorhexidine or povidone-iodine in preterm infants with caution), optimal catheter site selection (avoiding femoral in non-neonates), daily assessment of line necessity with prompt removal when no longer needed, standardized line maintenance with scrub-the-hub technique (15-second alcohol or chlorhexidine scrub before each access), and use of an insertion checklist with empowerment of any team member to stop the procedure for sterile breaks.',
    difficulty: 2,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 286,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the components of a ventilator-associated pneumonia prevention bundle in pediatric patients?',
    answer: 'Pediatric VAP bundles include elevation of the head of bed to 30 to 45 degrees (unless contraindicated), daily assessment of readiness for extubation with spontaneous breathing trials, oral care with age-appropriate antiseptic (chlorhexidine in children over 2 months, sterile water or breast milk for neonates), suctioning only when clinically indicated (not on a fixed schedule), maintaining appropriate endotracheal tube cuff pressure (20 to 25 cm H2O when cuffed tubes are used), use of in-line suction catheters, hand hygiene before and after airway manipulation, preventing ventilator circuit condensate from entering the airway, and changing ventilator circuits only when visibly soiled.',
    difficulty: 2,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 287,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Why is hand hygiene the single most important infection prevention measure in the NICU?',
    answer: 'Hand hygiene is the most effective intervention because the predominant mode of pathogen transmission in the NICU is via the contaminated hands of healthcare workers moving between patients. Compliance with hand hygiene before and after every patient contact, before aseptic procedures, after body fluid exposure, and after touching patient surroundings reduces healthcare-associated infections by 25 to 50 percent. Both alcohol-based hand rub (preferred for routine decontamination, effective in 15 to 20 seconds) and soap-and-water handwashing (required when hands are visibly soiled or after contact with spore-forming organisms like Clostridioides difficile) are acceptable methods.',
    difficulty: 1,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 288,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the recommended maternal GBS prophylaxis protocol and why is it important?',
    answer: 'Group B Streptococcus (GBS) is a leading cause of early-onset neonatal sepsis and meningitis. Universal maternal screening by vaginal-rectal culture is performed at 36 to 37 weeks gestation. GBS-positive mothers (or those with GBS bacteriuria during pregnancy, a previous GBS-affected infant, or unknown status with risk factors) receive intrapartum antibiotic prophylaxis, typically IV penicillin G (5 million units initially, then 2.5 to 3 million units every 4 hours) or ampicillin until delivery. Adequate prophylaxis requires at least 4 hours of antibiotics before delivery. This strategy has reduced early-onset GBS disease by approximately 80 percent.',
    difficulty: 2,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 289,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the TORCH infections and how do they affect the neonate?',
    answer: 'TORCH is an acronym for congenital infections: Toxoplasmosis, Other (syphilis, varicella, parvovirus B19), Rubella, Cytomegalovirus (CMV), and Herpes simplex virus. These infections are transmitted transplacentally or during delivery and can cause intrauterine growth restriction, microcephaly, intracranial calcifications, hepatosplenomegaly, jaundice, thrombocytopenia, hearing loss, chorioretinitis, and skin lesions. CMV is the most common congenital infection. Rubella and syphilis are preventable through vaccination and prenatal screening. Neonatal herpes requires urgent antiviral treatment with IV acyclovir. Many TORCH infections cause long-term neurodevelopmental disability.',
    difficulty: 1,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 290,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does congenital cytomegalovirus infection affect the respiratory system?',
    answer: 'Congenital CMV, the most common congenital infection (affecting 0.5 to 1 percent of live births), can cause pneumonitis with interstitial infiltrates, respiratory distress, and oxygen dependence in severely affected neonates. CMV pneumonitis is characterized by diffuse interstitial or reticulonodular infiltrates on chest radiograph, progressive respiratory failure, and may require mechanical ventilation. Treatment with IV ganciclovir or oral valganciclovir for 6 months improves hearing and neurodevelopmental outcomes. In preterm infants, postnatal CMV acquisition through breast milk can cause a sepsis-like syndrome with pneumonitis, hepatitis, and thrombocytopenia.',
    difficulty: 3,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 291,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is necrotizing tracheobronchitis and how does it relate to mechanical ventilation?',
    answer: 'Necrotizing tracheobronchitis is severe airway mucosal damage and necrosis resulting from prolonged mechanical ventilation, inadequate humidification of inspired gases, high airway pressures, and recurrent suctioning trauma. It manifests as thick, tenacious secretions, mucous plugging, atelectasis, and potentially complete airway obstruction from pseudomembrane formation. Pseudomembranes composed of necrotic mucosa, fibrin, and inflammatory cells can be visualized on bronchoscopy. Prevention centers on adequate humidification (100 percent relative humidity at 37 degrees Celsius for all intubated patients), minimizing suction trauma, and using the lowest effective ventilator pressures.',
    difficulty: 3,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 292,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What organisms are most commonly responsible for late-onset neonatal sepsis in the NICU?',
    answer: 'Late-onset sepsis (occurring after 72 hours of life) in the NICU is predominantly caused by coagulase-negative staphylococci (accounting for nearly 50 percent of cases, particularly Staphylococcus epidermidis), which colonize indwelling catheters and form biofilms. Staphylococcus aureus (including MRSA), Enterococcus species, gram-negative organisms (Escherichia coli, Klebsiella, Pseudomonas, Serratia, Enterobacter), and Candida species are also significant pathogens. Risk factors include prematurity, central venous catheters, prolonged antibiotic exposure, TPN, surgical procedures, and overcrowding. Empiric therapy typically includes vancomycin plus an aminoglycoside or third-generation cephalosporin.',
    difficulty: 2,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 293,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What risk factors predispose preterm infants to invasive fungal infections?',
    answer: 'Risk factors for invasive candidiasis in preterm infants include extreme prematurity (especially below 1000 g birth weight), prolonged broad-spectrum antibiotic therapy (particularly third-generation cephalosporins), presence of central venous catheters, TPN administration, H2-receptor antagonist use (which reduces gastric acidity allowing fungal colonization), postnatal corticosteroid exposure, NEC or gastrointestinal perforation, and prolonged intubation. Candida albicans and Candida parapsilosis are the most common species. Invasive candidiasis carries high mortality (20 to 30 percent) and significant morbidity including neurodevelopmental impairment.',
    difficulty: 2,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 294,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the role of fluconazole prophylaxis in preventing invasive fungal infections in extremely preterm infants?',
    answer: 'Fluconazole prophylaxis (3 to 6 mg/kg given twice weekly for 4 to 6 weeks) has been shown to reduce invasive candidiasis by 80 to 90 percent in extremely low birth weight infants (below 1000 g) in NICUs with high baseline fungal infection rates (above 5 percent). It targets Candida colonization of the skin and gastrointestinal tract before systemic invasion occurs. Concerns about resistance emergence have not been substantiated in studies. Current recommendations advise prophylaxis in NICUs with fungal infection rates exceeding 5 percent among ELBW infants. Antifungal stewardship programs monitor institutional rates and resistance patterns.',
    difficulty: 3,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 295,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What infection control practices should respiratory therapists follow when managing ventilator circuits?',
    answer: 'Ventilator circuits should be changed only when visibly soiled or malfunctioning, as routine circuit changes do not reduce VAP and may increase infection risk. Condensate in ventilator tubing must be drained away from the patient (never toward the patient or back into the humidifier) and disposed of as contaminated waste. Closed suction systems reduce environmental contamination and are preferred for patients on contact or droplet precautions. Heat-moisture exchangers should be replaced per manufacturer guidelines (every 24 to 48 hours) and immediately if contaminated with secretions or blood. Hand hygiene is performed before and after any circuit manipulation.',
    difficulty: 1,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 296,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does antibiotic stewardship apply in the neonatal intensive care unit?',
    answer: 'Antibiotic stewardship in the NICU aims to optimize antibiotic use while minimizing resistance, drug toxicity, and disruption of the developing microbiome. Principles include narrowing empiric coverage based on culture results within 48 to 72 hours, discontinuing antibiotics when infection is ruled out (negative cultures, improving clinical status), using the shortest effective treatment duration, avoiding unnecessary broad-spectrum agents (particularly third-generation cephalosporins that promote candidal colonization), and tracking antibiotic utilization metrics (days of therapy per 1000 patient-days). Prolonged empiric antibiotic exposure in the absence of proven infection is associated with increased rates of NEC, late-onset sepsis, and mortality.',
    difficulty: 2,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 297,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What isolation precautions are used for respiratory syncytial virus in the pediatric setting?',
    answer: 'RSV requires contact precautions (gown and gloves upon entering the room) in addition to standard precautions. RSV is transmitted primarily through large respiratory droplets and fomites rather than true airborne transmission, but droplet precautions are often added as well. Infected patients should be placed in single rooms or cohorted with other RSV-positive patients. Strict hand hygiene is essential as RSV survives on hands for approximately 30 minutes and on environmental surfaces for up to 6 hours. Environmental cleaning with hospital-approved disinfectants is critical. Cohorting of staff (assigning specific nurses to RSV-positive patients) further reduces nosocomial transmission.',
    difficulty: 1,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 298,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the significance of the neonatal microbiome and how do NICU practices affect it?',
    answer: 'The neonatal microbiome (the community of microorganisms colonizing the infant skin, gut, and respiratory tract) plays a critical role in immune system development, pathogen resistance, and long-term health. NICU practices that disrupt normal microbiome establishment include cesarean delivery (bypassing vaginal flora colonization), formula feeding instead of breast milk, prolonged antibiotic exposure, limited skin-to-skin contact, and the NICU environment itself (with its unique microbial ecology). Disrupted microbiome development is associated with increased risk of NEC, late-onset sepsis, allergic disease, and possibly BPD. Breast milk feeding, kangaroo care, and antibiotic stewardship support healthier colonization.',
    difficulty: 3,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 299,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What environmental cleaning and disinfection practices reduce infection risk in the NICU?',
    answer: 'Environmental infection control includes daily cleaning of all high-touch surfaces (monitors, ventilator panels, IV pump buttons, bed rails, incubator surfaces) with hospital-approved disinfectants, terminal cleaning of the bed space between patients, regular disinfection of shared equipment (stethoscopes, laryngoscope handles, transport incubators), and maintaining clean supply storage separate from contaminated areas. Respiratory equipment including resuscitation bags, flow sensors, and patient circuit components undergo high-level disinfection or sterilization between patients. Environmental cultures may be performed during outbreak investigations. Adequate staffing ratios and avoiding overcrowding reduce transmission by preventing rushed and compromised infection control practices.',
    difficulty: 1,
    topic: 'Infection Prevention in NICU',
    isFree: false,
    orderIndex: 300,
  },
]

async function main() {
  console.log('Seeding NPS flashcards (batch 3)...')
  console.log(`Total cards: ${flashcards.length}`)

  // Verify the division exists
  const division = await prisma.division.findUnique({
    where: { id: NPS_DIVISION_ID },
  })

  if (!division) {
    console.error(
      `Division ${NPS_DIVISION_ID} not found. Run seed-divisions.ts first.`
    )
    process.exit(1)
  }

  console.log(`Found division: ${division.name}`)

  // Insert all flashcards (do NOT clear existing cards — previous batch data must remain)
  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })

  console.log(`Successfully inserted ${result.count} NPS flashcards (batch 3).`)

  // Log summary by topic
  const topicCounts: Record<string, number> = {}
  const difficultyCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0 }
  let freeCount = 0

  for (const card of flashcards) {
    topicCounts[card.topic] = (topicCounts[card.topic] || 0) + 1
    difficultyCounts[card.difficulty]++
    if (card.isFree) freeCount++
  }

  console.log('\n--- Summary ---')
  console.log('By topic:')
  for (const [topic, count] of Object.entries(topicCounts)) {
    console.log(`  ${topic}: ${count} cards`)
  }
  console.log('By difficulty:')
  console.log(`  Easy (1): ${difficultyCounts[1]}`)
  console.log(`  Medium (2): ${difficultyCounts[2]}`)
  console.log(`  Hard (3): ${difficultyCounts[3]}`)
  console.log(`Free cards: ${freeCount}`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
