import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const ACCS_DIVISION_ID = 'cmsm41fw40002zf5463d399ps'

const flashcards = [
  // ============================================================
  // ECMO DEEP DIVE (cards 201-220)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the fundamental difference between VV-ECMO and VA-ECMO in terms of physiological support?',
    answer: 'VV-ECMO (venovenous) provides gas exchange support only, draining and returning blood to the venous system without directly augmenting cardiac output. VA-ECMO (venoarterial) provides both gas exchange and hemodynamic support by draining venous blood and returning oxygenated blood to the arterial system, effectively bypassing both the lungs and the heart.',
    difficulty: 1,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 201,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the primary indications for VV-ECMO in adult patients?',
    answer: 'VV-ECMO is indicated for severe, potentially reversible respiratory failure refractory to conventional management, including severe ARDS (PaO2/FiO2 less than 80 despite optimization), status asthmaticus with refractory hypercapnia, bridge to lung transplant, and primary graft dysfunction after lung transplant. The Murray Lung Injury Score of 3 or greater or uncompensated hypercapnia with pH less than 7.20 are common triggers for consideration.',
    difficulty: 2,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 202,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the primary indications for VA-ECMO?',
    answer: 'VA-ECMO is indicated for cardiogenic shock refractory to conventional therapy (including post-cardiotomy shock, fulminant myocarditis, massive pulmonary embolism with hemodynamic collapse), cardiac arrest (ECPR or extracorporeal cardiopulmonary resuscitation), bridge to ventricular assist device or heart transplant, and drug overdose causing severe cardiac depression. The key distinction from VV-ECMO is the need for circulatory support.',
    difficulty: 2,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 203,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'Describe the typical cannulation configuration for VV-ECMO.',
    answer: 'The most common VV-ECMO configuration uses a femoral vein drainage cannula (positioned in the IVC near the right atrium) and an internal jugular vein return cannula (positioned at the SVC-RA junction). Alternatively, a dual-lumen bicaval cannula (such as the Avalon Elite) can be placed via the right internal jugular vein, with drainage ports in the SVC and IVC and a return port directed toward the tricuspid valve. Proper positioning is confirmed with echocardiographic or fluoroscopic guidance.',
    difficulty: 2,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 204,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is recirculation in VV-ECMO and how does it affect oxygenation?',
    answer: 'Recirculation occurs when oxygenated blood returned to the venous system is immediately re-drained by the drainage cannula before it can pass through the systemic circulation. This reduces the effective oxygen delivery to the patient. Recirculation is increased by close proximity of drainage and return cannulas, high ECMO flow rates relative to cardiac output, and malpositioned cannulas. It is suspected when pre-oxygenator saturations are unexpectedly high (above 80%) despite low patient SpO2.',
    difficulty: 3,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 205,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the essential components of an ECMO circuit?',
    answer: 'An ECMO circuit consists of: (1) drainage cannula(s), (2) a centrifugal blood pump that generates flow, (3) a membrane oxygenator (polymethylpentene hollow-fiber membrane) for gas exchange, (4) a heat exchanger integrated into or near the oxygenator to maintain normothermia, (5) a return cannula, and (6) circuit tubing connecting these components. Additional elements include pressure monitoring sensors, flow meters, bubble detectors, and access ports for blood sampling.',
    difficulty: 1,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 206,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is the sweep gas flow on the ECMO membrane oxygenator used to control CO2 removal?',
    answer: 'Sweep gas flow is the primary determinant of CO2 removal during ECMO. Increasing sweep gas flow rate increases CO2 elimination, while decreasing it reduces CO2 removal. This is analogous to adjusting the respiratory rate on a mechanical ventilator. The FiO2 of the sweep gas is adjusted to control oxygenation. CO2 removal is highly efficient across the membrane, so even modest sweep flows can significantly lower PaCO2.',
    difficulty: 1,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 207,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What anticoagulation strategies are used during ECMO and what is monitored?',
    answer: 'Unfractionated heparin is the most common anticoagulant, titrated to maintain an activated clotting time (ACT) of 180-220 seconds or an anti-Xa level of 0.3-0.7 IU/mL. Bivalirudin, a direct thrombin inhibitor, is an alternative used in cases of heparin-induced thrombocytopenia (HIT) or heparin resistance, titrated to aPTT of 1.5-2.5 times normal. Argatroban is another direct thrombin inhibitor option. The goal is to balance thrombosis prevention against hemorrhagic risk.',
    difficulty: 2,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 208,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the major hemorrhagic complications of ECMO and their risk factors?',
    answer: 'Major hemorrhagic complications include intracranial hemorrhage (most devastating, occurring in 3-5% of adult cases), cannulation site bleeding, surgical site bleeding, pulmonary hemorrhage, and gastrointestinal bleeding. Risk factors include systemic anticoagulation, thrombocytopenia from platelet consumption and shear stress, acquired von Willebrand syndrome (loss of high-molecular-weight multimers), coagulopathy from hepatic dysfunction, and recent procedures or trauma.',
    difficulty: 2,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 209,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does circuit thrombosis present and how is it managed?',
    answer: 'Circuit thrombosis may present as rising transmembrane pressure gradient across the oxygenator, decreased oxygenation efficiency despite adequate flows, visible clot in the circuit or oxygenator, hemolysis (elevated plasma-free hemoglobin, LDH, decreased haptoglobin), or consumptive coagulopathy (falling fibrinogen, rising D-dimer). Management includes increasing anticoagulation if safe, circuit or oxygenator exchange if clot burden is significant, and addressing underlying causes such as subtherapeutic anticoagulation or low flow states.',
    difficulty: 3,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 210,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is hemolysis during ECMO, how is it detected, and what causes it?',
    answer: 'Hemolysis is the destruction of red blood cells within the ECMO circuit. It is detected by elevated plasma-free hemoglobin (greater than 50 mg/dL is concerning), elevated LDH, decreased haptoglobin, hemoglobinuria, and elevated indirect bilirubin. Causes include high pump speeds (excessive negative inlet pressures or excessive RPMs), circuit thrombus creating turbulent flow, kinking or obstruction in the circuit, small cannula size relative to flow, and cavitation events from inadequate drainage.',
    difficulty: 2,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 211,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is differential hypoxemia (Harlequin syndrome) in VA-ECMO, and how is it resolved?',
    answer: 'Differential hypoxemia occurs in peripheral VA-ECMO when oxygenated blood from the femoral arterial return cannula perfuses the lower body while poorly oxygenated blood ejected from the recovering heart supplies the upper body (including the brain and coronary arteries). It is detected by comparing right upper extremity SpO2 to lower extremity SpO2. Resolution strategies include adding a return cannula to the internal jugular vein (creating a VAV configuration), improving native lung function, or converting to central cannulation.',
    difficulty: 3,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 212,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the recommended ventilator settings during VV-ECMO ("lung rest" strategy)?',
    answer: 'During VV-ECMO, the ventilator is set to ultra-protective lung rest settings: tidal volume of 4 mL/kg or less (or pressure control generating low tidal volumes), plateau pressure of 25 cmH2O or less, PEEP of 10-15 cmH2O to maintain alveolar recruitment, FiO2 of 0.3-0.5 (reduced from pre-ECMO levels), and a respiratory rate of 10-15 breaths per minute. The goal is to minimize ventilator-induced lung injury while ECMO provides gas exchange.',
    difficulty: 1,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 213,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What criteria suggest a patient on VV-ECMO is ready for a weaning trial?',
    answer: 'Weaning readiness criteria include: improving lung compliance and chest radiograph, ECMO flow rates below 2-3 L/min with acceptable gas exchange, sweep gas FiO2 below 0.5, sweep gas flow rate below 2-3 L/min, adequate oxygenation and ventilation on moderate ventilator settings, hemodynamic stability, resolution or significant improvement of the underlying disease process, and absence of significant circuit complications. A sweep-off trial (turning sweep gas to zero while maintaining blood flow) is the standard weaning trial.',
    difficulty: 2,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 214,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the significance of left ventricular distension during VA-ECMO?',
    answer: 'VA-ECMO increases left ventricular afterload by returning oxygenated blood to the arterial system. If the left ventricle cannot eject against this increased afterload (especially in severely impaired LV function), left ventricular distension occurs, leading to increased myocardial oxygen demand, subendocardial ischemia, pulmonary edema despite ECMO support, and potential LV thrombus formation. Interventions include adding an LV vent (surgically or via Impella), atrial septostomy, intra-aortic balloon pump, or inotropic support.',
    difficulty: 3,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 215,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does ECMO blood flow rate affect oxygenation versus CO2 removal?',
    answer: 'Blood flow rate is the primary determinant of oxygenation during ECMO. Higher flow rates allow more blood to pass through the oxygenator, increasing total oxygen delivery. CO2 removal is primarily controlled by sweep gas flow and is relatively independent of blood flow rate at flows above 1-2 L/min, because CO2 diffuses approximately 20 times faster than oxygen across the membrane. This allows effective CO2 removal even at lower blood flow rates.',
    difficulty: 2,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 216,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is acquired von Willebrand syndrome in ECMO patients?',
    answer: 'Acquired von Willebrand syndrome (AVWS) occurs in nearly all ECMO patients due to shear stress from the centrifugal pump degrading high-molecular-weight von Willebrand factor (VWF) multimers. These large multimers are essential for platelet adhesion and primary hemostasis. The loss results in a qualitative platelet dysfunction and increased bleeding risk, particularly mucosal and surgical bleeding, even when platelet counts are adequate. It is diagnosed by measuring VWF activity-to-antigen ratio and multimer analysis.',
    difficulty: 3,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 217,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the key considerations for patient mobilization during ECMO?',
    answer: 'Awake ECMO with early mobilization is increasingly practiced, particularly with VV-ECMO. Key considerations include: securing cannulation sites to prevent dislodgement, adequate staffing (typically 3-4 trained personnel), ensuring circuit length allows movement, monitoring for position-related flow changes (chattering), avoiding excessive tension on cannulas, maintaining anticoagulation parameters, continuous SpO2 and circuit monitoring, and having emergency equipment available. Femoral cannulation limits ambulation compared to upper body cannulation strategies.',
    difficulty: 2,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 218,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is "chattering" or "chugging" in the ECMO circuit, and what causes it?',
    answer: 'Chattering is a rhythmic vibration of the ECMO circuit tubing caused by intermittent obstruction of venous drainage. It occurs when the drainage cannula intermittently contacts or is sucked against the vessel wall or right atrial wall, creating a cycle of obstruction and release. Causes include hypovolemia (most common), cannula malposition, high pump speeds relative to venous return, pneumothorax, tamponade, or patient position changes. Management includes volume resuscitation, reducing pump speed, repositioning the patient, and evaluating cannula position.',
    difficulty: 1,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 219,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are absolute and relative contraindications to VV-ECMO?',
    answer: 'Absolute contraindications include: irreversible underlying disease with no plan for transplant, severe irreversible neurological injury, uncontrolled bleeding, and conditions incompatible with anticoagulation. Relative contraindications include: prolonged high-pressure ventilation (greater than 7-10 days), advanced age (varies by center, typically over 65-70), severe multi-organ failure, morbid obesity (BMI over 40-45), and immunosuppression. Each center establishes its own specific criteria, and decisions are individualized based on the likelihood of recovery.',
    difficulty: 1,
    topic: 'ECMO Deep Dive',
    isFree: false,
    orderIndex: 220,
  },

  // ============================================================
  // ADVANCED ABG & ACID-BASE (cards 221-235)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the Stewart (physicochemical) approach to acid-base analysis, and how does it differ from the traditional Henderson-Hasselbalch approach?',
    answer: 'The Stewart approach identifies three independent variables that determine blood pH: (1) strong ion difference (SID), (2) total weak acid concentration (ATOT, primarily albumin and phosphate), and (3) PaCO2. Unlike the traditional approach that treats bicarbonate as an independent variable, Stewart recognizes that bicarbonate is a dependent variable determined by these three independent factors. This approach better explains complex acid-base derangements, particularly non-anion-gap metabolic acidoses and the effect of albumin on acid-base status.',
    difficulty: 3,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 221,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the strong ion difference (SID), and what is its normal value?',
    answer: 'The strong ion difference (SID) is the net charge difference between strong cations (mainly Na+, K+, Ca2+, Mg2+) and strong anions (mainly Cl-, lactate, and other unmeasured strong anions) in plasma. The apparent SID is approximately 40-42 mEq/L (calculated as [Na+ + K+ + Ca2+ + Mg2+] minus [Cl- + lactate]). A decrease in SID causes acidosis (e.g., hyperchloremia lowers SID), while an increase causes alkalosis (e.g., hypoalbuminemia effectively raises SID).',
    difficulty: 3,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 222,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does the anion gap help classify metabolic acidosis?',
    answer: 'The anion gap (AG = Na+ minus Cl- minus HCO3-) classifies metabolic acidosis into two categories. A high anion gap (greater than 12 mEq/L) indicates accumulation of unmeasured anions such as lactate, ketoacids, uremic toxins, or toxic alcohols (remembered by the mnemonic MUDPILES). A normal anion gap (hyperchloremic) metabolic acidosis results from bicarbonate loss (diarrhea, renal tubular acidosis) or chloride gain (normal saline resuscitation). The anion gap must be corrected for albumin: for every 1 g/dL decrease in albumin below 4, add 2.5 mEq/L to the calculated AG.',
    difficulty: 1,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 223,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the delta-delta ratio and how is it interpreted?',
    answer: 'The delta-delta ratio compares the change in anion gap (delta AG = measured AG minus 12) to the change in bicarbonate (delta HCO3 = 24 minus measured HCO3). A ratio of 1-1.6 suggests a pure high-AG metabolic acidosis. A ratio greater than 2 indicates a concurrent metabolic alkalosis (the AG has risen more than HCO3 has fallen, suggesting HCO3 was higher than expected). A ratio less than 1 indicates a concurrent non-AG metabolic acidosis (HCO3 has fallen more than the AG has risen, suggesting an additional source of HCO3 loss).',
    difficulty: 2,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 224,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the osmolar gap, and when is it clinically significant?',
    answer: 'The osmolar gap is the difference between measured serum osmolality and calculated osmolality. Calculated osmolality = 2(Na+) + glucose/18 + BUN/2.8. A normal osmolar gap is less than 10 mOsm/kg. An elevated osmolar gap in the setting of a high anion gap metabolic acidosis strongly suggests toxic alcohol ingestion (methanol, ethylene glycol, or isopropanol). It is also elevated with propylene glycol infusion (used as a solvent in lorazepam and phenytoin IV formulations), mannitol administration, and severe alcoholic ketoacidosis.',
    difficulty: 2,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 225,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How do you identify a triple acid-base disorder?',
    answer: 'A triple acid-base disorder is identified through systematic analysis: (1) determine the primary disorder from pH and PaCO2, (2) calculate expected compensation and note any discrepancy (indicating a second disorder), (3) calculate the anion gap (if elevated, a high-AG metabolic acidosis is present regardless of pH or HCO3), and (4) calculate the delta-delta ratio. A classic example is a patient with diabetic ketoacidosis (high-AG acidosis), concurrent vomiting (metabolic alkalosis), and respiratory compensation. The delta-delta ratio greater than 2 in a high-AG acidosis unmasks the hidden metabolic alkalosis.',
    difficulty: 3,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 226,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the expected respiratory compensation for a metabolic acidosis, and how is it calculated?',
    answer: 'The expected PaCO2 in acute metabolic acidosis is predicted by Winter\'s formula: expected PaCO2 = (1.5 x HCO3-) + 8 (plus or minus 2). If the measured PaCO2 is higher than expected, a concurrent respiratory acidosis is present. If the measured PaCO2 is lower than expected, a concurrent respiratory alkalosis is present. As a quick check, PaCO2 should approximate the last two digits of pH (e.g., pH 7.28 should have PaCO2 near 28 mmHg).',
    difficulty: 1,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 227,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does hypoalbuminemia affect acid-base interpretation in the ICU?',
    answer: 'Albumin is a weak acid (part of ATOT in the Stewart model). Hypoalbuminemia, common in critically ill patients, causes a metabolic alkalosis by reducing the total weak acid buffer concentration. It also falsely lowers the calculated anion gap, potentially masking a high-AG acidosis. The corrected anion gap is calculated by adding 2.5 mEq/L for each 1 g/dL that albumin is below 4 g/dL. Without this correction, significant lactic acidosis or other anion-gap acidoses can be missed in hypoalbuminemic patients.',
    difficulty: 2,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 228,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the strong ion gap (SIG) and what does it indicate?',
    answer: 'The strong ion gap (SIG) represents unmeasured strong anions in the plasma. It is calculated as the apparent SID minus the effective SID (which equals HCO3- plus albumin charge + phosphate charge). Normal SIG is approximately 0-2 mEq/L. An elevated SIG indicates the presence of unmeasured anions such as lactate, ketoacids, sulfate, or other organic acids. Unlike the traditional anion gap, SIG is not affected by changes in albumin or other weak acids, making it a more precise measure of unmeasured anions in critically ill patients.',
    difficulty: 3,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 229,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does normal saline resuscitation cause a hyperchloremic metabolic acidosis?',
    answer: 'Normal saline (0.9% NaCl) contains Na+ and Cl- in equal concentrations (154 mEq/L each), whereas plasma has a higher Na+ (140) than Cl- (100) concentration. Large-volume saline infusion disproportionately increases Cl- relative to Na+, narrowing the strong ion difference (SID). According to Stewart principles, a decreased SID drives water dissociation toward higher H+ concentration, producing acidosis. This is also understood as chloride displacing bicarbonate. Balanced crystalloids (Ringer lactate, PlasmaLyte) have a lower chloride concentration and an SID closer to plasma, reducing this effect.',
    difficulty: 2,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 230,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the expected compensatory responses for a primary respiratory alkalosis in acute versus chronic settings?',
    answer: 'In acute respiratory alkalosis (first 6-24 hours), HCO3- decreases by 2 mEq/L for every 10 mmHg decrease in PaCO2 (through buffering mechanisms). In chronic respiratory alkalosis (3-5 days), HCO3- decreases by 5 mEq/L for every 10 mmHg decrease in PaCO2 (through renal compensation with decreased bicarbonate reabsorption). If the actual HCO3- is higher or lower than expected for the duration, a concurrent metabolic disorder is present.',
    difficulty: 2,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 231,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is the urinary anion gap used to evaluate a normal-anion-gap metabolic acidosis?',
    answer: 'The urinary anion gap (UAG) is calculated as urinary (Na+ + K+) minus Cl-. It serves as an indirect estimate of urinary ammonium (NH4+) excretion. A negative UAG (typically -20 to -50) indicates appropriate renal NH4+ excretion, suggesting an extrarenal cause of bicarbonate loss (e.g., diarrhea). A positive UAG indicates impaired renal acidification (renal tubular acidosis), as the kidneys are failing to excrete adequate ammonium. This distinction guides further workup and management of non-AG metabolic acidosis.',
    difficulty: 3,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 232,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is permissive hypercapnia, and what are its physiological effects and contraindications?',
    answer: 'Permissive hypercapnia is the deliberate acceptance of elevated PaCO2 (typically up to 60-80 mmHg) to enable lung-protective ventilation with lower tidal volumes and pressures. Physiological effects include sympathetic stimulation (increased heart rate, cardiac output), cerebral vasodilation (increased ICP), rightward shift of the oxyhemoglobin dissociation curve, pulmonary vasoconstriction, and intracellular acidosis. Contraindications include elevated intracranial pressure, severe pulmonary hypertension, significant cardiac arrhythmias, and severe metabolic acidosis (pH less than 7.15). The pH is typically maintained above 7.20 with or without bicarbonate buffering.',
    difficulty: 1,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 233,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does lactic acidosis differ between Type A and Type B classifications?',
    answer: 'Type A lactic acidosis results from tissue hypoperfusion or hypoxia leading to anaerobic metabolism. Causes include shock (cardiogenic, septic, hemorrhagic), severe hypoxemia, cardiac arrest, mesenteric ischemia, and severe anemia. Type B lactic acidosis occurs without evidence of tissue hypoperfusion. Causes include medications (metformin, linezolid, epinephrine, nucleoside reverse transcriptase inhibitors), liver failure (impaired lactate clearance), malignancy, thiamine deficiency, seizures, and mitochondrial disorders. Treatment targets differ: Type A requires restoring perfusion; Type B requires identifying and treating the underlying cause.',
    difficulty: 2,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 234,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the base excess (BE) and how is it interpreted in the ICU?',
    answer: 'Base excess represents the amount of strong acid or base (in mEq/L) needed to return blood pH to 7.40 at PaCO2 of 40 mmHg and 37 degrees Celsius. Normal BE is -2 to +2 mEq/L. A negative base excess (base deficit) indicates metabolic acidosis, while a positive base excess indicates metabolic alkalosis. In trauma and critical care, base deficit serves as a marker of tissue hypoperfusion and resuscitation adequacy. A base deficit greater than -6 mEq/L correlates with increased mortality and transfusion requirements. Serial measurements track the response to resuscitation.',
    difficulty: 1,
    topic: 'Advanced ABG & Acid-Base',
    isFree: false,
    orderIndex: 235,
  },

  // ============================================================
  // PULMONARY VASCULAR DISEASE IN ICU (cards 236-250)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is acute pulmonary embolism classified by severity, and how does this guide management?',
    answer: 'PE is classified as: (1) Massive (high-risk): sustained hypotension (SBP less than 90 for over 15 minutes), requiring vasopressors, or cardiac arrest - treated with systemic thrombolysis, surgical embolectomy, or catheter-directed therapy. (2) Submassive (intermediate-risk): normotensive but with RV dysfunction (echo or CT) and/or elevated troponin/BNP - considered for escalated therapy if deterioration occurs. (3) Low-risk: normotensive without RV dysfunction or biomarker elevation - treated with anticoagulation alone, with possible early discharge.',
    difficulty: 1,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 236,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the role of systemic thrombolysis in massive PE, and what agent is most commonly used?',
    answer: 'Systemic thrombolysis is first-line treatment for massive PE with hemodynamic instability. Alteplase (tPA) is the most commonly used agent, given as 100 mg IV over 2 hours (or 0.6 mg/kg over 15 minutes as an accelerated regimen in cardiac arrest). It lyses the obstructing thrombus, rapidly reducing pulmonary artery pressure and improving RV function. Contraindications include active internal bleeding, recent hemorrhagic stroke (within 3 months), intracranial neoplasm, and recent major surgery (within 3 weeks). The risk of major bleeding is approximately 10-15%, with intracranial hemorrhage occurring in 1-3% of cases.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 237,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is catheter-directed therapy (CDT) for pulmonary embolism?',
    answer: 'Catheter-directed therapy encompasses several percutaneous interventional approaches: catheter-directed thrombolysis (low-dose tPA delivered directly into the pulmonary artery thrombus, typically 1 mg/hr per catheter for 12-24 hours), ultrasound-facilitated thrombolysis (EKOS system, using ultrasound to enhance tPA penetration into clot), aspiration thrombectomy, and rheolytic thrombectomy. CDT is considered for massive PE when systemic thrombolysis is contraindicated or has failed, and for submassive PE with clinical deterioration. It offers the advantage of lower total tPA doses, potentially reducing bleeding risk.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 238,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the echocardiographic findings of acute right ventricular failure due to PE?',
    answer: 'Echocardiographic findings include: RV dilation (RV/LV ratio greater than 1.0 in apical 4-chamber view), RV hypokinesis with apical sparing (McConnell sign, which is relatively specific for acute PE), paradoxical septal motion (interventricular septum bowing toward the LV during systole), tricuspid regurgitation with elevated RVSP, dilated IVC without respiratory collapse (indicating elevated RA pressure), and the "60-60" sign (pulmonary acceleration time less than 60 ms with RVSP less than 60 mmHg, suggesting acute rather than chronic RV pressure overload).',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 239,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does a pulmonary hypertensive crisis present, and what is the initial management?',
    answer: 'A pulmonary hypertensive crisis presents with acute elevation in pulmonary artery pressure leading to RV failure, with systemic hypotension, tachycardia, elevated JVP, RV heave, and potential cardiovascular collapse. Triggers include hypoxia, hypercarbia, acidosis, pain/agitation, fluid overload, and interruption of pulmonary vasodilator therapy. Initial management includes: correcting hypoxia (100% FiO2), hyperventilation to reduce PaCO2 (alkalosis reduces PVR), inhaled nitric oxide (20-40 ppm) or inhaled epoprostenol, IV vasopressors (norepinephrine preferred to maintain coronary perfusion), avoiding volume overload, and treating the underlying trigger.',
    difficulty: 3,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 240,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does inhaled nitric oxide (iNO) work, and what are its indications in adult critical care?',
    answer: 'Inhaled nitric oxide selectively vasodilates pulmonary vessels in ventilated lung regions, reducing pulmonary vascular resistance and improving V/Q matching without systemic hypotension (it is rapidly inactivated by hemoglobin). Adult indications include: acute pulmonary hypertensive crisis, RV failure after cardiac surgery, severe ARDS with refractory hypoxemia (as a rescue therapy), post-lung transplant reperfusion injury, and pulmonary hypertension in the perioperative setting. Typical doses are 5-40 ppm. Monitoring includes methemoglobin levels (keep below 5%) and nitrogen dioxide levels. It must be weaned gradually to prevent rebound pulmonary hypertension.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 241,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the mechanisms of acute right heart failure in the ICU setting?',
    answer: 'Acute right heart failure results from: (1) Pressure overload - acute PE, ARDS, pulmonary hypertensive crisis, mechanical ventilation with high intrathoracic pressures. (2) Volume overload - excessive fluid resuscitation, tricuspid or pulmonic regurgitation, left-to-right shunts. (3) Impaired contractility - RV myocardial infarction, septic cardiomyopathy, post-cardiotomy dysfunction. (4) Reduced coronary perfusion - systemic hypotension reduces RV coronary perfusion (which occurs in both systole and diastole, unlike the LV), creating a downward spiral of hypotension causing RV ischemia causing further hypotension.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 242,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the role of epoprostenol (prostacyclin) in pulmonary hypertension management?',
    answer: 'Epoprostenol is a potent pulmonary and systemic vasodilator and platelet aggregation inhibitor. In ICU settings, it is used as a continuous IV infusion for pulmonary hypertensive crisis and severe pulmonary arterial hypertension (PAH). It has a very short half-life (3-5 minutes), requiring continuous infusion via a central line. Starting dose is typically 1-2 ng/kg/min, titrated up by 1-2 ng/kg/min every 15 minutes. Key considerations include systemic hypotension as a dose-limiting side effect, the need for dedicated central line access, and the danger of abrupt discontinuation causing rebound pulmonary hypertension that can be fatal.',
    difficulty: 3,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 243,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How do positive-pressure ventilation and PEEP affect right ventricular function?',
    answer: 'Positive-pressure ventilation increases intrathoracic pressure, which compresses pulmonary capillaries and increases RV afterload (especially at high tidal volumes and PEEP). This can precipitate RV failure in patients with borderline RV function or existing pulmonary hypertension. Additionally, elevated intrathoracic pressure reduces venous return (RV preload) and can shift the interventricular septum leftward, impairing LV filling. Strategies to minimize RV impact include limiting tidal volumes and plateau pressures, using moderate PEEP, avoiding hypoxia and hypercarbia (which worsen pulmonary vasoconstriction), and maintaining adequate systemic blood pressure for RV coronary perfusion.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 244,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is treprostinil and how does its administration differ from epoprostenol?',
    answer: 'Treprostinil is a prostacyclin analogue with a longer half-life (4.5 hours compared to 3-5 minutes for epoprostenol), providing greater dose stability and reduced risk of rebound pulmonary hypertension with brief interruptions. It can be given via continuous subcutaneous infusion, IV infusion, inhalation (Tyvaso), or oral formulation. In the ICU, the IV route is preferred for acute management. The subcutaneous route causes significant infusion-site pain. Treprostinil is often used as a transition from IV epoprostenol in patients stabilizing from pulmonary hypertensive crisis.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 245,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is inhaled epoprostenol used as an alternative to inhaled nitric oxide?',
    answer: 'Inhaled epoprostenol is delivered as a continuous nebulization through the ventilator circuit, typically at 10,000-50,000 ng/mL concentration with flow rates adjusted to achieve 20-50 ng/kg/min. Like iNO, it selectively vasodilates ventilated lung units, improving V/Q matching and reducing pulmonary artery pressure without systemic effects. Advantages over iNO include significantly lower cost, no specialized delivery system required, no risk of methemoglobinemia, and no nitrogen dioxide production. Disadvantages include potential stickiness on circuit components, less precise dosing, and the need for alkaline diluent (glycine buffer at pH 10.5) which may affect the ventilator circuit.',
    difficulty: 3,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 246,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the Pulmonary Embolism Severity Index (PESI) and how is it used?',
    answer: 'The PESI is a clinical prediction tool that stratifies 30-day mortality risk in patients with confirmed PE. It assigns points based on: age (age in years), male sex (+10), cancer (+30), heart failure (+10), chronic lung disease (+10), heart rate 110 or greater (+20), SBP less than 100 (+30), respiratory rate 30 or greater (+20), temperature less than 36 C (+20), altered mental status (+60), and SpO2 less than 90% (+20). Classes I-II (low risk, less than 85 points) may be candidates for outpatient treatment. The simplified PESI (sPESI) uses the same variables dichotomously and is validated for identifying low-risk patients when the score is 0.',
    difficulty: 1,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 247,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What fluid management strategy is recommended for acute right heart failure?',
    answer: 'Fluid management in acute RV failure requires careful assessment, as the relationship between preload and RV output follows a flat Frank-Starling curve. While the failing RV may be preload-dependent, excessive volume worsens RV dilation, increases tricuspid regurgitation, shifts the septum leftward (impairing LV filling), and increases wall tension (worsening RV ischemia). A cautious 250-500 mL fluid challenge with reassessment is recommended for patients without volume overload. If CVP is already elevated (above 12-15 mmHg) or echocardiography shows RV dilation, diuresis rather than volume loading is typically indicated. Vasopressors (norepinephrine) are preferred over fluids for hypotension in most cases.',
    difficulty: 3,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 248,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is chronic thromboembolic pulmonary hypertension (CTEPH) and when should it be suspected in the ICU?',
    answer: 'CTEPH is persistent organized thromboembolic obstruction of the pulmonary arteries causing pulmonary hypertension and progressive RV failure. It develops in approximately 2-4% of acute PE survivors. It should be suspected in ICU patients with unexplained pulmonary hypertension, persistent dyspnea and exercise intolerance after PE treatment, echocardiographic findings of chronic RV pressure overload (RV hypertrophy, not just dilation), and ventilation-perfusion scan showing persistent mismatched defects. Diagnosis requires right heart catheterization showing mPAP of 25 mmHg or greater with PAWP of 15 mmHg or less, and pulmonary angiography. Definitive treatment is pulmonary endarterectomy at an experienced center.',
    difficulty: 2,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 249,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does milrinone affect the right ventricle, and what are the concerns with its use in RV failure?',
    answer: 'Milrinone is a phosphodiesterase-3 inhibitor that provides both inotropic support (increasing RV contractility via increased cAMP) and pulmonary vasodilation (reducing RV afterload), making it theoretically attractive for RV failure. However, its potent systemic vasodilatory effect frequently causes hypotension, which can reduce RV coronary perfusion and worsen RV ischemia. Therefore, milrinone is often combined with a vasopressor (norepinephrine or vasopressin) when used for RV failure. Inhaled milrinone has been studied as an alternative to deliver pulmonary vasodilation with less systemic hypotension, particularly in the cardiac surgical setting.',
    difficulty: 3,
    topic: 'Pulmonary Vascular Disease in ICU',
    isFree: false,
    orderIndex: 250,
  },

  // ============================================================
  // TRANSPLANT CRITICAL CARE (cards 251-265)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is primary graft dysfunction (PGD) after lung transplantation, and how is it graded?',
    answer: 'PGD is a form of acute lung injury occurring within the first 72 hours after lung transplant, caused by ischemia-reperfusion injury. It is graded by the ISHLT system using the PaO2/FiO2 ratio: Grade 0 (PF ratio greater than 300 with clear CXR), Grade 1 (PF ratio greater than 300 with diffuse infiltrates), Grade 2 (PF ratio 200-300), Grade 3 (PF ratio less than 200). Grade 3 PGD at 72 hours carries significant mortality risk (up to 40%) and predicts development of chronic lung allograft dysfunction. Management includes lung-protective ventilation, judicious fluid management, inhaled nitric oxide, and in severe cases, ECMO support.',
    difficulty: 2,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 251,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the typical ventilator management goals in the immediate post-lung transplant period?',
    answer: 'Post-lung transplant ventilator goals include: tidal volumes of 6-8 mL/kg (donor predicted body weight), plateau pressures less than 30 cmH2O, moderate PEEP (5-10 cmH2O, sufficient to prevent atelectasis but not excessive to avoid anastomotic stress), FiO2 titrated to SpO2 92-96%, and avoidance of hyperinflation. Unique considerations include: avoiding high airway pressures that could stress the bronchial anastomosis, recognizing that the transplanted lung is denervated (absent cough reflex below the anastomosis), and understanding that single-lung recipients may have different compliance between native and transplanted lungs, requiring careful PEEP optimization.',
    difficulty: 2,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 252,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the key respiratory complications of immunosuppressive therapy in transplant patients?',
    answer: 'Immunosuppressive therapy predisposes transplant patients to: (1) Opportunistic infections - CMV pneumonitis, Pneumocystis jirovecii pneumonia (PJP), invasive aspergillosis, Nocardia, atypical mycobacteria. (2) Drug-specific pulmonary toxicity - sirolimus/everolimus can cause drug-induced pneumonitis and impaired wound healing (bronchial anastomotic dehiscence). (3) Post-transplant lymphoproliferative disorder (PTLD) - EBV-associated lymphoma that can present as pulmonary nodules or masses. (4) Increased susceptibility to community-acquired respiratory infections with atypical and severe presentations. Prophylaxis protocols typically include trimethoprim-sulfamethoxazole for PJP and valganciclovir for CMV.',
    difficulty: 2,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 253,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is acute cellular rejection diagnosed and managed in lung transplant recipients?',
    answer: 'Acute cellular rejection presents with dyspnea, cough, low-grade fever, declining FEV1 (greater than 10% decrease from baseline), new infiltrates on chest imaging, and hypoxemia. Diagnosis requires transbronchial biopsy showing perivascular and interstitial lymphocytic infiltrates, graded A0 (none) through A4 (severe). Grade A2 or higher typically requires treatment. Management consists of pulse-dose IV methylprednisolone (500-1000 mg daily for 3 days), followed by an oral prednisone taper and optimization of maintenance immunosuppression. Refractory or recurrent rejection may require anti-thymocyte globulin, alemtuzumab, or photopheresis.',
    difficulty: 3,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 254,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is chronic lung allograft dysfunction (CLAD), and what are its phenotypes?',
    answer: 'CLAD is a persistent decline in lung function (FEV1 less than 80% of baseline for at least 3 weeks) after lung transplant, occurring in approximately 50% of recipients by 5 years. Two main phenotypes exist: (1) Bronchiolitis obliterans syndrome (BOS) - the most common form, characterized by obstructive physiology (declining FEV1 without restriction) with air trapping on CT, caused by fibrotic obliteration of small airways. (2) Restrictive allograft syndrome (RAS) - a restrictive pattern with persistent parenchymal infiltrates or pleural thickening, carrying a worse prognosis than BOS. Management is largely supportive with optimization of immunosuppression, azithromycin (for BOS), and consideration for re-transplantation.',
    difficulty: 3,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 255,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the unique hemodynamic considerations in the denervated heart after heart transplant?',
    answer: 'The transplanted heart is denervated, resulting in: (1) Loss of vagal tone, producing a resting heart rate of 90-110 bpm. (2) Absence of reflex tachycardia or bradycardia in response to hypotension or hypertension. (3) Dependence on circulating catecholamines for heart rate response, causing a delayed and blunted response to exercise or stress. (4) Lack of response to atropine, digoxin, and carotid sinus massage (which act via vagal pathways). (5) Preserved response to isoproterenol, epinephrine, and direct-acting beta-agonists. (6) Preload dependence - the transplanted heart relies heavily on adequate filling pressures. These factors significantly affect acute management in the ICU.',
    difficulty: 1,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 256,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the main immunosuppressive agents used in solid organ transplant, and how are their levels monitored?',
    answer: 'The triple-drug immunosuppression regimen typically includes: (1) Calcineurin inhibitors (tacrolimus or cyclosporine) - monitored by trough levels; tacrolimus targets 8-15 ng/mL acutely, 5-10 ng/mL maintenance; nephrotoxicity and neurotoxicity are dose-limiting. (2) Antimetabolites (mycophenolate mofetil or azathioprine) - mycophenolate monitored by AUC or trough; azathioprine by WBC count; bone marrow suppression is the main toxicity. (3) Corticosteroids - tapered to lowest effective dose. Some centers use mTOR inhibitors (sirolimus, everolimus) as alternatives, monitored by trough levels with targets of 5-15 ng/mL. Drug interactions are extensive, particularly with CYP3A4 inhibitors and inducers.',
    difficulty: 1,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 257,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is antibody-mediated rejection (AMR) in lung transplantation?',
    answer: 'AMR is caused by donor-specific antibodies (DSAs) targeting donor HLA antigens on the pulmonary vascular endothelium. It presents with acute graft dysfunction (hypoxemia, declining PF ratio, diffuse infiltrates), often more abruptly than cellular rejection. Diagnosis requires the triad of: (1) clinical allograft dysfunction, (2) presence of circulating DSAs, and (3) histopathological evidence of complement deposition (C4d staining) in pulmonary capillaries on biopsy. Treatment includes plasmapheresis to remove circulating antibodies, IV immunoglobulin, rituximab (anti-CD20), bortezomib (proteasome inhibitor), and eculizumab (complement inhibitor) in refractory cases.',
    difficulty: 3,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 258,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What pulmonary complications occur after hematopoietic stem cell transplantation (HSCT)?',
    answer: 'Pulmonary complications occur in 40-60% of HSCT recipients and include: Early (pre-engraftment, days 0-30): pulmonary edema, diffuse alveolar hemorrhage (DAH), idiopathic pneumonia syndrome (IPS), engraftment syndrome. Mid-phase (days 30-100): CMV pneumonitis, PJP, invasive aspergillosis, other opportunistic infections. Late phase (after day 100): bronchiolitis obliterans (a manifestation of chronic graft-versus-host disease), cryptogenic organizing pneumonia, late-onset noninfectious pulmonary syndrome. These represent the most common causes of non-relapse mortality in HSCT recipients.',
    difficulty: 2,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 259,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is diffuse alveolar hemorrhage (DAH) after stem cell transplant, and how is it managed?',
    answer: 'DAH occurs in 5-12% of HSCT recipients, typically within the first 30 days during the engraftment period. It presents with progressive dyspnea, hypoxemia, diffuse bilateral infiltrates, and often without overt hemoptysis (only 30% of patients have hemoptysis). Diagnosis is confirmed by BAL showing progressively bloodier returns across sequential aliquots and hemosiderin-laden macrophages. Mortality exceeds 60-80% despite treatment. Management includes high-dose methylprednisolone (500-1000 mg daily for 3-5 days), supportive ventilatory care with lung-protective strategies, platelet transfusion to maintain counts above 50,000, correction of coagulopathy, and consideration of recombinant factor VIIa or aminocaproic acid in refractory cases.',
    difficulty: 3,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 260,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is idiopathic pneumonia syndrome (IPS) after HSCT?',
    answer: 'IPS is a noninfectious diffuse lung injury occurring after HSCT, defined as widespread alveolar damage with multilobar infiltrates on imaging in the absence of active lower respiratory tract infection, cardiac dysfunction, renal failure, or iatrogenic fluid overload. It results from conditioning regimen toxicity (particularly total body irradiation and alkylating agents), occult infection, and inflammatory cascades. It occurs in approximately 5-10% of allogeneic HSCT recipients. Treatment is primarily supportive plus high-dose corticosteroids. Etanercept (TNF-alpha antagonist) has shown some benefit. Mortality remains high at 50-80%.',
    difficulty: 2,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 261,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does the denervation of the transplanted lung affect airway management and secretion clearance?',
    answer: 'Lung denervation after transplant results in: (1) Absent cough reflex below the bronchial anastomosis, increasing aspiration and secretion retention risk. (2) Impaired mucociliary clearance due to disrupted neural coordination, requiring aggressive airway clearance techniques. (3) Loss of bronchoconstriction reflexes, potentially allowing deeper penetration of irritants. (4) Altered ventilatory responses (diminished response to CO2 changes from transplanted lung). (5) Impaired lymphatic drainage, contributing to edema. Respiratory therapists must emphasize aggressive bronchial hygiene including bronchoscopic clearance, chest physiotherapy, and patient education on forced cough techniques.',
    difficulty: 1,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 262,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is ex-vivo lung perfusion (EVLP), and how has it expanded the donor lung pool?',
    answer: 'EVLP is a technique for assessing and reconditioning marginal donor lungs outside the body before transplantation. Donor lungs are placed in a chamber and perfused with a specialized acellular perfusate at normothermia while being ventilated. Over 4-6 hours, lung function is assessed (PaO2/FiO2 ratio, compliance, airway pressures, pulmonary vascular resistance), and the lungs may improve as pulmonary edema resolves and atelectasis is recruited. EVLP has expanded the usable donor pool by 15-30% by enabling utilization of donation-after-circulatory-death (DCD) donors, older donors, and donors with initially poor gas exchange, without increasing primary graft dysfunction rates.',
    difficulty: 2,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 263,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is tacrolimus nephrotoxicity, and how should the respiratory therapist recognize its systemic effects?',
    answer: 'Tacrolimus nephrotoxicity is a common and dose-dependent complication affecting 25-40% of transplant recipients. It manifests as rising creatinine, decreased urine output, hyperkalemia, hypomagnesemia, and metabolic acidosis (type 4 RTA). Systemic effects relevant to respiratory care include: fluid overload from declining renal function (causing pulmonary edema), electrolyte disturbances (hypomagnesemia can cause cardiac arrhythmias and neuromuscular weakness), neurotoxicity (tremor, seizures, posterior reversible encephalopathy syndrome), and hyperglycemia (new-onset diabetes after transplant). Recognition of these patterns should prompt trough level checking and communication with the transplant team for dose adjustment.',
    difficulty: 1,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 264,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the key differences in managing respiratory failure in immunocompromised transplant patients versus immunocompetent patients?',
    answer: 'Key differences include: (1) Broader differential diagnosis - opportunistic organisms (PJP, CMV, Aspergillus, Nocardia) must be considered alongside typical pathogens. (2) Earlier and more aggressive diagnostic workup - early bronchoscopy with BAL, broad multiplex PCR panels, galactomannan and beta-D-glucan testing, and consideration of lung biopsy. (3) Empiric antimicrobial coverage must be broader, often including anti-PJP, antifungal, and antiviral coverage pending cultures. (4) Immunosuppression adjustment - balancing the risk of infection (reducing immunosuppression) against rejection (maintaining immunosuppression). (5) Atypical presentations - absence of classic inflammatory signs due to immunosuppression. (6) Higher index of suspicion for non-infectious causes (drug toxicity, PTLD, pulmonary GVHD).',
    difficulty: 2,
    topic: 'Transplant Critical Care',
    isFree: false,
    orderIndex: 265,
  },

  // ============================================================
  // ADVANCED INFECTION MANAGEMENT (cards 266-280)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the key multi-drug resistant (MDR) organisms encountered in the ICU, and what defines their resistance patterns?',
    answer: 'Major MDR organisms include: (1) MRSA (methicillin-resistant Staphylococcus aureus) - resistant to all beta-lactams; treated with vancomycin, linezolid, daptomycin. (2) VRE (vancomycin-resistant Enterococcus) - treated with linezolid or daptomycin. (3) ESBL-producing Enterobacteriaceae - resistant to most cephalosporins and penicillins; treated with carbapenems. (4) CRE (carbapenem-resistant Enterobacteriaceae) - resistant to carbapenems; treated with ceftazidime-avibactam, meropenem-vaborbactam, or colistin. (5) MDR Pseudomonas aeruginosa - requires susceptibility-guided therapy. (6) MDR Acinetobacter baumannii - often susceptible only to colistin, tigecycline, or ampicillin-sulbactam. Infection control measures include contact precautions and antimicrobial stewardship.',
    difficulty: 1,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 266,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What antifungal agents are used in the ICU, and what are the key differences between their spectrums?',
    answer: 'Major antifungal classes in the ICU: (1) Echinocandins (micafungin, caspofungin, anidulafungin) - first-line for invasive candidiasis; active against Candida (including fluconazole-resistant species) but NOT Cryptococcus or mucormycosis; well tolerated. (2) Azoles - fluconazole for susceptible Candida; voriconazole for invasive aspergillosis (first-line); posaconazole and isavuconazole for broader mold coverage including mucormycosis (isavuconazole). (3) Amphotericin B (liposomal formulation) - broadest spectrum; covers Candida, Aspergillus, mucormycosis, and endemic fungi; nephrotoxicity limits use. Choice depends on suspected organism, site of infection, organ function, and drug interactions (azoles interact with CYP3A4).',
    difficulty: 2,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 267,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is invasive pulmonary aspergillosis diagnosed and managed in the ICU?',
    answer: 'Invasive pulmonary aspergillosis (IPA) occurs primarily in immunocompromised patients (neutropenia, high-dose steroids, transplant recipients) but also in critically ill patients with COPD or severe influenza. Diagnosis relies on: CT findings (halo sign or air-crescent sign), BAL galactomannan assay (index greater than 0.5-1.0), serum galactomannan, BAL culture and cytology, and serum beta-D-glucan (nonspecific). First-line treatment is voriconazole (6 mg/kg IV twice on day 1, then 4 mg/kg IV twice daily), with therapeutic drug monitoring targeting trough levels of 1-5 mcg/mL. Alternatives include isavuconazole and liposomal amphotericin B. Duration is typically 6-12 weeks minimum. Mortality remains 30-50% despite treatment.',
    difficulty: 2,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 268,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the pathophysiology and management of Clostridioides difficile infection in the ICU?',
    answer: 'C. difficile infection (CDI) is caused by toxin-producing anaerobic bacteria that proliferate when normal gut flora is disrupted by antibiotics. The toxins (A and B) cause intestinal inflammation, secretory diarrhea, and pseudomembranous colitis. Diagnosis is via PCR or toxin immunoassay from stool. ICU-specific concerns include fulminant colitis with toxic megacolon, ileus masking diarrhea, and septic shock. Treatment stratification: non-severe - oral vancomycin 125 mg four times daily or fidaxomicin 200 mg twice daily; severe - oral vancomycin 500 mg four times daily; fulminant - oral vancomycin 500 mg four times daily plus IV metronidazole 500 mg every 8 hours, with rectal vancomycin if ileus is present. Surgical consultation for colectomy in refractory cases.',
    difficulty: 1,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 269,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is procalcitonin used to guide antibiotic therapy in the ICU?',
    answer: 'Procalcitonin (PCT) is a biomarker that rises specifically in bacterial infections and remains low in viral infections and non-infectious inflammation. In the ICU, PCT-guided antibiotic stewardship has been validated for: (1) Initiating antibiotics - PCT less than 0.25 ng/mL suggests antibiotics may be withheld (low probability of bacterial infection); PCT greater than 0.5 ng/mL supports bacterial infection. (2) Discontinuing antibiotics - a decrease of 80% or more from peak value, or an absolute value less than 0.5 ng/mL, supports safe discontinuation, reducing antibiotic duration by 2-3 days on average. Limitations include false elevations in renal failure, post-cardiac surgery, trauma, cardiogenic shock, and some fungal infections. PCT should complement, not replace, clinical judgment.',
    difficulty: 1,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 270,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is antibiotic de-escalation, and how is it implemented in the ICU?',
    answer: 'Antibiotic de-escalation is the practice of narrowing empiric broad-spectrum antibiotic therapy to targeted therapy once culture and sensitivity data are available, typically within 48-72 hours. Implementation involves: (1) Obtaining appropriate cultures before starting antibiotics (blood cultures, respiratory cultures, urine). (2) Starting broad empiric coverage based on suspected source, local antibiogram, and risk factors for MDR organisms. (3) Reviewing culture results at 48-72 hours and narrowing to the most targeted effective agent. (4) Discontinuing antibiotics if infection is excluded. Benefits include reduced antimicrobial resistance, decreased CDI risk, fewer drug adverse effects, and lower costs, without increasing mortality when appropriately implemented.',
    difficulty: 1,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 271,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What respiratory management lessons were learned from COVID-19 ICU experience?',
    answer: 'Key COVID-19 ICU lessons include: (1) Recognition of different ARDS phenotypes (L-type with preserved compliance vs H-type with classic ARDS features), influencing PEEP strategies. (2) Awake prone positioning in non-intubated patients with high-flow nasal cannula can improve oxygenation and may reduce intubation rates. (3) High-flow nasal cannula and non-invasive ventilation with appropriate precautions are viable strategies to avoid intubation. (4) Prolonged prone positioning sessions (16+ hours) improve outcomes. (5) Dexamethasone reduces mortality in patients requiring supplemental oxygen. (6) Patient self-inflicted lung injury (P-SILI) from vigorous spontaneous breathing may worsen outcomes, supporting earlier intubation in some patients. (7) Importance of aerosolization precautions during airway procedures.',
    difficulty: 2,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 272,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is ventilator-associated pneumonia (VAP) prevention bundle, and what are its components?',
    answer: 'The VAP prevention bundle is a group of evidence-based interventions implemented together to reduce VAP incidence. Core components include: (1) Elevation of the head of bed to 30-45 degrees to reduce aspiration risk. (2) Daily sedation interruption and assessment of readiness to extubate. (3) Peptic ulcer disease prophylaxis (though this may paradoxically increase pneumonia risk). (4) DVT prophylaxis. (5) Daily oral care with chlorhexidine (0.12%). (6) Subglottic secretion drainage using specialized endotracheal tubes. (7) Maintaining endotracheal cuff pressure at 20-30 cmH2O. (8) Minimizing ventilator circuit changes. Compliance with all bundle elements simultaneously achieves greater VAP reduction than individual components alone.',
    difficulty: 1,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 273,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does Pneumocystis jirovecii pneumonia (PJP) present in non-HIV immunocompromised patients, and how does management differ from HIV-associated PJP?',
    answer: 'In non-HIV immunocompromised patients, PJP has a more acute and fulminant presentation with rapid respiratory failure, higher organism burden, and greater mortality (30-60% vs 10-20% in HIV). The inflammatory response is more intense, and CT findings may show more consolidation and less of the classic ground-glass pattern. BAL sensitivity is lower than in HIV-associated PJP because organism burden is lower, making beta-D-glucan (elevated, greater than 80 pg/mL) a useful adjunctive test. Treatment is the same: trimethoprim-sulfamethoxazole 15-20 mg/kg/day of TMP component for 21 days. Adjunctive corticosteroids are proven beneficial in HIV-associated PJP (when PaO2 less than 70 mmHg) but have less evidence in non-HIV PJP, though they are often used empirically.',
    difficulty: 3,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 274,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the role of beta-D-glucan and galactomannan testing in the diagnosis of invasive fungal infections?',
    answer: 'Beta-D-glucan (BDG) is a cell wall component of most fungi (except mucormycosis and Cryptococcus). A serum level greater than 80 pg/mL suggests invasive fungal infection with good sensitivity but limited specificity. False positives occur with certain antibiotics (piperacillin-tazobactam, amoxicillin-clavulanate), albumin infusions, hemodialysis membranes, gauze surgical packing, and bacteremia. Galactomannan (GM) is an Aspergillus-specific cell wall antigen. Serum GM index greater than 0.5 or BAL GM index greater than 1.0 supports invasive aspergillosis diagnosis. False positives occur with piperacillin-tazobactam and some foods. Used together, these biomarkers help guide empiric antifungal therapy and reduce unnecessary treatment.',
    difficulty: 2,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 275,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the significance of MRSA nasal screening in ICU pneumonia management?',
    answer: 'MRSA nasal PCR or culture screening has high negative predictive value (95-99%) for MRSA pneumonia. A negative MRSA nasal screen in a patient with suspected HAP or VAP makes MRSA pneumonia very unlikely, allowing clinicians to safely withhold or discontinue empiric anti-MRSA therapy (vancomycin or linezolid). This application is a key antimicrobial stewardship tool that reduces unnecessary vancomycin use, limiting nephrotoxicity, vancomycin-resistant organism selection, and drug costs. However, the positive predictive value is low (approximately 40-50%), as nasal colonization does not confirm MRSA as the pneumonia pathogen, so a positive screen does not confirm MRSA pneumonia.',
    difficulty: 2,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 276,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the optimal approach to obtaining respiratory cultures for suspected VAP?',
    answer: 'Two approaches are validated: (1) Quantitative cultures via bronchoscopic BAL (threshold greater than 10,000 CFU/mL) or protected specimen brush (threshold greater than 1,000 CFU/mL), which offer greater specificity and guide de-escalation. (2) Semi-quantitative endotracheal aspirate cultures (reporting light, moderate, heavy growth), which are simpler to obtain and have equivalent impact on clinical outcomes in comparative trials. Regardless of method, cultures should be obtained before initiating or changing antibiotics. Gram stain provides rapid preliminary guidance. The presence of less than 1% squamous epithelial cells confirms a lower respiratory tract sample. Neither approach has demonstrated mortality superiority over the other, but quantitative cultures more effectively guide antibiotic de-escalation.',
    difficulty: 2,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 277,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the risk factors for developing MDR organism infections in the ICU?',
    answer: 'Risk factors for MDR infections include: (1) Prior antibiotic exposure within 90 days (strongest risk factor). (2) Hospitalization for 5 or more days (especially in ICU). (3) Prior MDR organism colonization or infection. (4) Residence in long-term care facility. (5) Chronic dialysis. (6) Home infusion therapy. (7) Immunosuppression. (8) Structural lung disease (bronchiectasis, cystic fibrosis). (9) Local epidemiology (high MDR prevalence in the facility). (10) Presence of invasive devices (central lines, urinary catheters, endotracheal tubes). These risk factors guide empiric antibiotic selection: patients with MDR risk factors receive broader empiric coverage, while those without can receive narrower-spectrum agents.',
    difficulty: 1,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 278,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is mucormycosis (zygomycosis) recognized and managed in the ICU?',
    answer: 'Mucormycosis is an aggressive angioinvasive fungal infection caused by Mucorales fungi (Rhizopus, Mucor, Lichtheimia). Risk factors include diabetic ketoacidosis, neutropenia, corticosteroid use, iron overload, and deferoxamine therapy. Pulmonary mucormycosis presents with fever, cough, hemoptysis, and rapidly progressive infiltrates or cavitation on CT (reverse halo sign is suggestive). Key diagnostic features: tissue biopsy showing broad, ribbon-like, non-septate hyphae with right-angle branching; importantly, galactomannan and beta-D-glucan are NEGATIVE (unlike aspergillosis). Treatment requires liposomal amphotericin B (5-10 mg/kg/day) as first-line, surgical debridement when feasible, isavuconazole or posaconazole as alternatives, and correction of the underlying predisposing condition. Mortality exceeds 50%.',
    difficulty: 3,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 279,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the concept of aerosolized antibiotic therapy in the ICU, and when is it indicated?',
    answer: 'Aerosolized antibiotics deliver high concentrations directly to the lung while minimizing systemic toxicity. Agents include inhaled tobramycin, amikacin, colistin, and aztreonam. Indications include adjunctive therapy for MDR gram-negative VAP (particularly when caused by organisms susceptible only to nephrotoxic agents like colistin or aminoglycosides), treatment of MDR tracheobronchitis, and cystic fibrosis exacerbations. Administration requires a vibrating mesh nebulizer (more efficient than jet nebulizers for viscous antibiotics), synchronization with inspiration, in-line placement in the ventilator circuit, and consideration of ventilator filter changes. They should be used as adjuncts to, not replacements for, systemic antibiotics in pneumonia.',
    difficulty: 2,
    topic: 'Advanced Infection Management',
    isFree: false,
    orderIndex: 280,
  },

  // ============================================================
  // ICU TECHNOLOGY & INNOVATION (cards 281-300)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the BLUE protocol for lung ultrasound, and how does it guide management of acute respiratory failure?',
    answer: 'The BLUE (Bedside Lung Ultrasound in Emergency) protocol is a rapid, systematic approach using lung ultrasound to diagnose the cause of acute respiratory failure within minutes. Key patterns: (1) A-profile (A-lines with lung sliding and no DVT) suggests asthma or COPD. (2) A-profile with DVT suggests pulmonary embolism. (3) B-profile (bilateral B-lines with lung sliding) suggests pulmonary edema. (4) A/B profile (asymmetric B-lines) suggests pneumonia. (5) Absent lung sliding with lung point or barcode sign suggests pneumothorax. (6) Absent lung sliding with B-lines suggests pneumonia. (7) PLAPS (posterolateral alveolar and/or pleural syndrome) with consolidation suggests pneumonia. The protocol achieves over 90% diagnostic accuracy.',
    difficulty: 1,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 281,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are B-lines on lung ultrasound, and what do they indicate?',
    answer: 'B-lines are hyperechoic, vertical, comet-tail artifacts that arise from the pleural line, extend to the bottom of the screen without fading, move synchronously with lung sliding, and erase A-lines. They represent thickened interlobular septa from fluid in the lung interstitium. Fewer than 3 B-lines per intercostal space are considered normal. Three or more B-lines per zone constitute a positive B-pattern. Bilateral diffuse B-lines indicate cardiogenic pulmonary edema, ARDS, or diffuse interstitial disease. Focal or asymmetric B-lines suggest pneumonia, contusion, or atelectasis. The number and distribution of B-lines correlate with extravascular lung water and can be used to monitor fluid status and diuretic response.',
    difficulty: 1,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 282,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is lung ultrasound used to identify consolidation and differentiate it from pleural effusion?',
    answer: 'Consolidation on lung ultrasound appears as a tissue-like (hepatized) pattern at the lung periphery, often with air bronchograms (hyperechoic punctate or linear structures within the consolidated tissue). Dynamic air bronchograms (bronchograms that move with respiration) suggest pneumonia rather than atelectasis (which shows static air bronchograms). Pleural effusion appears as an anechoic (black) space between the visceral and parietal pleura, with the lung visible within it (often compressive atelectasis). Distinguishing features: effusion is gravity-dependent and anechoic, while consolidation is tissue-density with air bronchograms. Complex effusions may show septations, debris, or echogenic material suggesting empyema or hemothorax.',
    difficulty: 2,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 283,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is diaphragm ultrasound, and how is it used to assess diaphragmatic function in the ICU?',
    answer: 'Diaphragm ultrasound assesses diaphragmatic function through two measurements: (1) Diaphragm excursion - measured in M-mode via the subcostal approach, with the probe in the right or left anterior axillary line. Normal excursion during quiet breathing is 1.5-2.5 cm; less than 1 cm suggests diaphragm dysfunction. (2) Diaphragm thickening fraction (DTF) - measured at the zone of apposition (8th-10th intercostal space, anterior axillary line) using a high-frequency linear probe. DTF = (thickness at end-inspiration minus thickness at end-expiration) divided by thickness at end-expiration, times 100. A DTF greater than 30-36% suggests adequate diaphragmatic effort, while less than 20% predicts weaning failure. Serial measurements detect ventilator-induced diaphragm dysfunction.',
    difficulty: 2,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 284,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does point-of-care ultrasound (POCUS) assess volume status and fluid responsiveness in the ICU?',
    answer: 'POCUS assesses volume status through multiple windows: (1) IVC assessment - IVC diameter greater than 2.1 cm with less than 50% collapse suggests elevated CVP; IVC less than 1.5 cm with greater than 50% collapse suggests low CVP. (2) Cardiac views - LV cavity size (small hyperdynamic LV suggests hypovolemia), RV size and function, and estimation of cardiac output. (3) Lung ultrasound - presence of B-lines suggests pulmonary congestion, arguing against further fluid administration. (4) Venous congestion protocol (VExUS) - assessing hepatic vein, portal vein, and renal vein Doppler patterns for venous congestion. Integration of these findings provides a more complete hemodynamic picture than any single measurement and helps guide fluid and vasopressor therapy.',
    difficulty: 2,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 285,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is electrical impedance tomography (EIT), and how is it used in mechanical ventilation?',
    answer: 'EIT is a non-invasive, radiation-free, real-time imaging technique that uses a belt of electrodes placed around the chest to measure regional lung ventilation by detecting changes in electrical impedance during breathing. Clinical applications include: (1) PEEP titration - identifying optimal PEEP by visualizing regional overdistension and collapse simultaneously. (2) Assessing ventilation distribution - detecting dependent atelectasis or ventral overdistension. (3) Monitoring prone positioning effects on ventilation distribution. (4) Detecting pneumothorax in real-time (sudden loss of impedance change in an area). (5) Evaluating the effects of recruitment maneuvers. (6) Assessing pendelluft (intratidal gas redistribution). It provides breath-by-breath bedside imaging without the radiation exposure of CT.',
    difficulty: 3,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 286,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are closed-loop ventilation systems, and what are the main commercially available modes?',
    answer: 'Closed-loop ventilation systems use algorithms to automatically adjust ventilator settings based on continuous patient data feedback. Major systems include: (1) Adaptive Support Ventilation (ASV, Hamilton) - adjusts pressure, rate, and I:E ratio to achieve target minute ventilation using the Otis least work-of-breathing equation. (2) INTELLiVENT-ASV - adds automated FiO2 and PEEP adjustment based on SpO2 and EtCO2 targets. (3) SmartCare/PS (Drager) - automates weaning from pressure support by adjusting PS based on respiratory rate, tidal volume, and EtCO2. (4) Neurally Adjusted Ventilatory Assist (NAVA) - uses diaphragm electrical activity (Edi) to trigger and proportion ventilator support to neural respiratory drive. These systems aim to reduce clinician workload and may improve ventilator synchrony and weaning times.',
    difficulty: 2,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 287,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does Neurally Adjusted Ventilatory Assist (NAVA) work, and what are its advantages?',
    answer: 'NAVA uses an esophageal catheter with electrodes positioned at the level of the diaphragm to detect the electrical activity of the diaphragm (Edi signal). The ventilator delivers pressure proportional to the Edi signal, with the proportionality determined by the NAVA level (cmH2O per microvolt). Advantages include: (1) Improved patient-ventilator synchrony (eliminates trigger delays and cycling mismatches since triggering is neural). (2) Proportional support that adjusts breath-by-breath to patient demand. (3) Maintained neural feedback loop for breathing pattern regulation. (4) Can function even with significant air leaks (useful in non-invasive ventilation). (5) Edi monitoring provides real-time assessment of respiratory drive. Limitations include the need for catheter placement and limited familiarity among clinicians.',
    difficulty: 3,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 288,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the lung ultrasound aeration score, and how is it used clinically?',
    answer: 'The lung ultrasound aeration score quantifies lung aeration across 12 zones (6 per hemithorax: anterior superior, anterior inferior, lateral superior, lateral inferior, posterior superior, posterior inferior). Each zone is scored: 0 = normal aeration (A-lines or fewer than 3 B-lines), 1 = moderate loss (3 or more well-spaced B-lines), 2 = severe loss (coalescent B-lines), 3 = complete loss (consolidation). Total score ranges from 0-36. Clinical applications include: tracking ARDS progression or resolution, assessing recruitment maneuver effectiveness (re-scoring before and after), guiding fluid management (changes in B-line scores with diuresis), predicting weaning outcomes, and monitoring response to prone positioning. A decrease in score indicates improving aeration.',
    difficulty: 2,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 289,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is telemedicine ICU (tele-ICU), and what are its demonstrated benefits?',
    answer: 'Tele-ICU uses audiovisual technology and electronic monitoring to provide remote intensivist and critical care nurse oversight of ICU patients, typically from a centralized command center. Components include: continuous remote monitoring of vital signs, ventilator data, lab trends, and medication administration; bidirectional audio-video communication with bedside staff; computerized clinical decision support alerts; and remote order entry capability. Demonstrated benefits include: reduced ICU mortality (15-30% relative risk reduction in some studies), reduced ICU length of stay, faster implementation of best-practice protocols, increased adherence to evidence-based guidelines, improved nighttime and weekend coverage for ICUs without 24/7 intensivist presence, and earlier recognition of clinical deterioration.',
    difficulty: 1,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 290,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is focused cardiac ultrasound (FoCUS) used in the ICU for acute hemodynamic assessment?',
    answer: 'FoCUS uses standardized cardiac views (parasternal long-axis, parasternal short-axis, apical 4-chamber, subcostal) to rapidly answer clinical questions at the bedside. Key assessments include: (1) LV function - visual estimation of ejection fraction (hyperdynamic, normal, reduced, severely reduced). (2) RV size and function - RV/LV ratio, RV free wall motion. (3) Pericardial effusion and tamponade physiology (diastolic RV or RA collapse). (4) Gross valvular abnormalities. (5) IVC size and collapsibility for volume status assessment. (6) Wall motion abnormalities suggesting ischemia. FoCUS is not a comprehensive echocardiogram but provides immediately actionable information in shock states, cardiac arrest, and unexplained hemodynamic instability. Training programs require 25-50 supervised studies for competency.',
    difficulty: 1,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 291,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the VExUS (Venous Excess Ultrasound) protocol, and how does it assess venous congestion?',
    answer: 'The VExUS protocol uses ultrasound to grade the severity of systemic venous congestion by evaluating four components: (1) IVC diameter (greater than 2 cm indicates elevated CVP and is required for VExUS to be applicable). (2) Hepatic vein Doppler (normal is S greater than D; severe congestion shows reversed S-wave). (3) Portal vein Doppler (normal is continuous flow; severe congestion shows greater than 50% pulsatility). (4) Intrarenal vein Doppler (normal is continuous; severe congestion shows discontinuous or reversed diastolic flow). VExUS grades: Grade 0 = IVC less than 2 cm; Grade 1 = IVC greater than 2 cm with mild organ Doppler abnormalities; Grade 2 = IVC greater than 2 cm with at least one severe organ Doppler abnormality; Grade 3 = IVC greater than 2 cm with multiple severe organ abnormalities. Higher grades correlate with acute kidney injury risk and guide diuresis.',
    difficulty: 3,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 292,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is ultrasound used to guide pleural procedures in the ICU?',
    answer: 'Ultrasound-guided pleural procedures significantly reduce complications compared to landmark-based techniques. For thoracentesis: ultrasound identifies the optimal puncture site (largest pocket of fluid), measures effusion depth, visualizes the diaphragm to avoid subdiaphragmatic puncture, identifies underlying lung to avoid parenchymal injury, and confirms fluid (anechoic) versus consolidated tissue. Real-time guidance during needle insertion is recommended for small or complex effusions. For chest tube placement: ultrasound confirms effusion location, identifies safe insertion point above the diaphragm and below the fluid level, and avoids intercostal vessels. Post-procedure ultrasound confirms drainage and detects complications (pneumothorax). Ultrasound guidance reduces the pneumothorax rate from 10-18% (landmark) to 1-4%.',
    difficulty: 1,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 293,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the lung sliding sign on ultrasound, and how is it used to diagnose pneumothorax?',
    answer: 'Lung sliding is the normal shimmering, back-and-forth movement of the visceral pleura against the parietal pleura during respiration, visible on B-mode ultrasound at the pleural interface. On M-mode, normal lung sliding produces the "seashore sign" (granular pattern below the pleural line). In pneumothorax, air between the pleural layers prevents visualization of sliding, producing the "barcode" or "stratosphere sign" on M-mode (horizontal lines only). The lung point, where sliding lung meets non-sliding lung, is pathognomonic for pneumothorax and identifies its boundary. The absence of lung sliding combined with absent B-lines and the presence of a lung point has near 100% specificity for pneumothorax. Ultrasound is more sensitive than supine anteroposterior chest radiograph for detecting pneumothorax.',
    difficulty: 2,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 294,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is transpulmonary thermodilution monitoring, and how does it differ from pulmonary artery catheterization?',
    answer: 'Transpulmonary thermodilution (PiCCO, EV1000) uses a central venous catheter and a thermistor-tipped arterial catheter (typically femoral) to measure cardiac output. Cold saline is injected centrally, and the temperature change is detected at the arterial catheter after traversing the cardiopulmonary circuit. It additionally calculates: extravascular lung water (EVLW, useful in ARDS and fluid management), global end-diastolic volume (cardiac preload), and pulse pressure variation (fluid responsiveness). Advantages over PA catheterization include: less invasive (no catheter through the right heart), longer indwelling time, continuous cardiac output via pulse contour analysis, and EVLW measurement. Limitations include unreliability with severe aortic regurgitation, IABP, severe arrhythmias, and the need for femoral arterial access.',
    difficulty: 3,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 295,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is Adaptive Support Ventilation (ASV), and how does its algorithm determine ventilator settings?',
    answer: 'ASV is a closed-loop ventilation mode that automatically adjusts inspiratory pressure, respiratory rate, and inspiratory time to deliver a target minute ventilation set by the clinician (based on patient weight). The algorithm uses the Otis equation to calculate the optimal breathing pattern (tidal volume and respiratory rate combination) that minimizes the elastic and resistive work of breathing for the individual patient. It continuously measures respiratory mechanics (compliance, resistance, auto-PEEP) and adjusts settings breath-by-breath. ASV can function as a controlled, assist-control, or support mode depending on patient effort. It prevents tachypnea, excessive tidal volumes, and air trapping through built-in safety rules. INTELLiVENT-ASV extends this by adding automated FiO2/PEEP titration.',
    difficulty: 2,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 296,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the role of artificial intelligence and machine learning in ICU respiratory care?',
    answer: 'AI and machine learning applications in ICU respiratory care include: (1) Predictive analytics for early detection of patient deterioration (early warning scores augmented by ML algorithms analyzing vital sign trends). (2) Automated ventilator weaning protocols using real-time physiological data to predict extubation readiness with greater accuracy than traditional indices. (3) Image recognition for chest radiograph and CT interpretation, detecting pneumothorax, consolidation, and line placement. (4) Sepsis prediction algorithms that identify sepsis hours before clinical recognition. (5) Personalized PEEP optimization using integration of multiple parameters. (6) Smart alarm management that reduces alarm fatigue by filtering false alarms using pattern recognition. These technologies are emerging as clinical decision support tools, with the clinician retaining final decision authority.',
    difficulty: 2,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 297,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is esophageal pressure monitoring used to optimize mechanical ventilation?',
    answer: 'Esophageal pressure (Pes) monitoring uses a balloon-tipped catheter placed in the mid-esophagus to estimate pleural pressure, enabling calculation of transpulmonary pressure (Ptp = airway pressure minus Pes). Clinical applications include: (1) PEEP titration targeting a positive end-expiratory transpulmonary pressure (typically 0-5 cmH2O) to ensure lung is open at end-expiration without overdistension. (2) Identifying the true distending pressure of the lung in obese patients where high chest wall elastance contributes to elevated plateau pressure. (3) Quantifying patient inspiratory effort during assisted breathing (esophageal pressure swing). (4) Detecting pendelluft and occult patient effort during controlled ventilation. (5) Guiding lung-protective ventilation by keeping inspiratory Ptp below 20-25 cmH2O. The EPVent-2 trial showed improved oxygenation but not mortality with Pes-guided PEEP.',
    difficulty: 3,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 298,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the components and clinical utility of integrated bedside clinical information systems in the ICU?',
    answer: 'Integrated ICU clinical information systems combine multiple data streams into a unified display: (1) Continuous physiological monitoring (vital signs, waveforms, SpO2, EtCO2). (2) Ventilator data integration (real-time display of ventilator parameters, waveforms, and trends). (3) Electronic medication administration record (infusion rates, dosing, timing). (4) Laboratory result integration (ABG trends, coagulation, metabolic panels). (5) Clinical decision support (drug interaction alerts, evidence-based protocol prompts, early warning scores). (6) Documentation automation (auto-charting of physiological parameters). Clinical utility includes: reduced documentation burden, improved data accuracy, trend visualization for earlier detection of deterioration, standardized care protocol adherence, and data availability for quality improvement and research.',
    difficulty: 1,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 299,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is stress index derived from the ventilator pressure-time curve, and how does it guide PEEP adjustment?',
    answer: 'The stress index is calculated from the shape of the airway pressure-time curve during constant-flow volume-controlled ventilation. A perfectly straight (linear) pressure rise during inspiration yields a stress index of 1 (optimal). A stress index less than 1 (concave downward curve) indicates tidal recruitment, suggesting PEEP should be increased to keep recruited units open throughout the breath. A stress index greater than 1 (concave upward curve) indicates overdistension, suggesting PEEP or tidal volume should be reduced. The target range is 0.9-1.1. This method provides a noninvasive, breath-by-breath assessment of whether the current ventilator settings are causing recruitment or overdistension, complementing other tools like driving pressure and transpulmonary pressure monitoring.',
    difficulty: 3,
    topic: 'ICU Technology & Innovation',
    isFree: false,
    orderIndex: 300,
  },
]

async function main() {
  console.log('Seeding ACCS flashcards batch 3 (cards 201-300)...')

  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })

  console.log(`Successfully seeded ${result.count} ACCS flashcards (batch 3).`)
}

main()
  .catch((e) => {
    console.error('Error seeding ACCS batch 3:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
