import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const cards = [
  // ============================================================
  // ADVANCED VENTILATOR CONCEPTS (301-320)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the primary mechanism of gas exchange during high-frequency oscillatory ventilation (HFOV)?',
    answer: 'HFOV relies on enhanced molecular diffusion and convective dispersion rather than bulk flow ventilation. A piston or diaphragm oscillates at rates of 3-15 Hz, delivering tidal volumes smaller than anatomical dead space while maintaining a constant mean airway pressure.',
    difficulty: 3,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 301,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Describe the two pressure levels used in airway pressure release ventilation (APRV).',
    answer: 'APRV alternates between a high pressure (P-high) sustained for a long duration (T-high) and a brief release to a low pressure (P-low) for a short duration (T-low). The prolonged high-pressure phase promotes alveolar recruitment while the brief release allows CO2 elimination.',
    difficulty: 3,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 302,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the recommended T-low setting in APRV and why?',
    answer: 'T-low is typically set so that expiratory flow terminates at approximately 75% of peak expiratory flow. This brief release time (often 0.4-0.8 seconds) prevents complete alveolar emptying and maintains end-expiratory lung volume, functioning as intrinsic PEEP.',
    difficulty: 3,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 303,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the primary physiological benefits of prone positioning in mechanically ventilated patients with severe ARDS?',
    answer: 'Prone positioning improves ventilation-perfusion matching by redistributing ventilation to dorsal lung regions that remain well-perfused. It also reduces compression of dependent lung tissue by the heart and abdomen, improves secretion drainage, and promotes more homogeneous alveolar inflation.',
    difficulty: 2,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 304,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'For how many hours per day is prone positioning typically recommended in moderate-to-severe ARDS?',
    answer: 'Current evidence supports prone positioning sessions of at least 12-16 hours per day in patients with moderate-to-severe ARDS (PaO2/FiO2 less than 150). Sessions should be initiated early in the disease course for maximum survival benefit.',
    difficulty: 2,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 305,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is auto-PEEP (intrinsic PEEP) and how is it detected on ventilator waveforms?',
    answer: 'Auto-PEEP occurs when expiratory flow does not reach zero before the next breath begins, trapping gas in the lungs. On the flow-time waveform, it is identified when the expiratory flow tracing does not return to the zero baseline before the next inspiration starts.',
    difficulty: 2,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 306,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Name three ventilator adjustments that can reduce auto-PEEP.',
    answer: 'Auto-PEEP can be reduced by decreasing the respiratory rate (allowing more expiratory time), increasing inspiratory flow rate (shortening inspiratory time), and reducing tidal volume. Bronchodilator therapy may also help by decreasing airway resistance and facilitating complete exhalation.',
    difficulty: 2,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 307,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of a lung recruitment maneuver and what is a common technique?',
    answer: 'Recruitment maneuvers aim to open collapsed alveoli by transiently applying sustained high airway pressures. A common technique is the sustained inflation method, where continuous positive pressure of 30-40 cmH2O is held for 30-40 seconds, followed by returning to the previous ventilator settings with adequate PEEP to keep recruited units open.',
    difficulty: 2,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 308,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is permissive hypercapnia and when is it used?',
    answer: 'Permissive hypercapnia is a ventilation strategy that tolerates elevated PaCO2 levels (typically up to 60-80 mmHg) to allow use of lung-protective tidal volumes (6 mL/kg IBW). It is used in ARDS and severe obstructive disease to minimize ventilator-induced lung injury while accepting a compensated respiratory acidosis.',
    difficulty: 2,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 309,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a contraindication to permissive hypercapnia?',
    answer: 'Permissive hypercapnia is contraindicated in patients with elevated intracranial pressure because hypercapnia causes cerebral vasodilation and can worsen cerebral edema. It should also be used cautiously in patients with significant cardiac arrhythmias, pulmonary hypertension, or severe metabolic acidosis.',
    difficulty: 2,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 310,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is optimal PEEP determined using a decremental PEEP trial?',
    answer: 'In a decremental PEEP trial, a recruitment maneuver is performed first, then PEEP is gradually reduced in 1-2 cmH2O increments while monitoring compliance or oxygenation. The optimal PEEP is set 2 cmH2O above the level at which compliance begins to decline or oxygenation drops, indicating the onset of derecruitment.',
    difficulty: 3,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 311,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does a "beaking" or "penguin beak" pattern on a pressure-volume curve indicate?',
    answer: 'A beaking pattern at the end of inspiration on the pressure-volume curve indicates overdistension of alveoli. The pressure rises sharply with minimal volume gain, suggesting that tidal volume or PEEP should be reduced to prevent ventilator-induced lung injury.',
    difficulty: 3,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 312,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is flow asynchrony (flow starvation) and how does it appear on ventilator graphics?',
    answer: 'Flow asynchrony occurs when the ventilator-delivered flow rate is insufficient to meet the patient\'s inspiratory demand. On the pressure-time waveform, it appears as a concave scooping or dipping of the inspiratory pressure tracing below the expected trajectory, indicating the patient is pulling harder than the ventilator is delivering.',
    difficulty: 3,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 313,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is double-triggering and what typically causes it?',
    answer: 'Double-triggering occurs when a single patient effort triggers two consecutive ventilator breaths, effectively delivering twice the set tidal volume. It is commonly caused by a set tidal volume that is too low relative to patient demand or an inspiratory time that is shorter than the patient\'s neural inspiratory time.',
    difficulty: 3,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 314,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the primary indication for neuromuscular blockade in mechanically ventilated patients?',
    answer: 'Neuromuscular blockade is primarily indicated in early severe ARDS (PaO2/FiO2 less than 150) when deep sedation alone fails to achieve adequate ventilator synchrony or lung-protective ventilation. It eliminates patient-ventilator asynchrony, reduces oxygen consumption, and may reduce biotrauma by preventing injurious spontaneous efforts.',
    difficulty: 3,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 315,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What monitoring is essential during continuous neuromuscular blockade?',
    answer: 'Train-of-four (TOF) peripheral nerve stimulation monitoring is essential to assess the depth of neuromuscular blockade and prevent overdosing. A target of 1-2 twitches out of 4 is typical. Adequate sedation must be verified because paralyzed patients cannot communicate distress, and daily interruption should be considered.',
    difficulty: 2,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 316,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does reverse triggering differ from other forms of patient-ventilator asynchrony?',
    answer: 'Reverse triggering is a unique form of asynchrony where a mandatory ventilator breath triggers a reflexive diaphragmatic contraction via entrainment of the respiratory center. Unlike typical trigger asynchrony where the patient initiates, here the ventilator breath causes the patient effort, which can lead to breath-stacking and elevated transpulmonary pressures.',
    difficulty: 3,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 317,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the stress index and how is it used to guide ventilator management?',
    answer: 'The stress index is derived from the shape of the pressure-time curve during constant-flow volume ventilation. A value of 1 (straight line) indicates appropriate settings, less than 1 (concave up) suggests tidal recruitment and potential for increasing PEEP, and greater than 1 (concave down) indicates overdistension requiring reduced PEEP or tidal volume.',
    difficulty: 3,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 318,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between driving pressure and plateau pressure?',
    answer: 'Plateau pressure reflects the total static pressure in the respiratory system at end-inspiration. Driving pressure is calculated as plateau pressure minus PEEP, representing the pressure change that actually distends the lungs during each breath. Driving pressure above 15 cmH2O is associated with increased mortality in ARDS.',
    difficulty: 2,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 319,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What ventilator graphic finding suggests missed triggering efforts?',
    answer: 'Missed triggers appear as small negative deflections on the airway pressure tracing or small positive deflections on the flow tracing that do not result in a delivered breath. They indicate the patient is making inspiratory efforts that fail to meet the trigger threshold, often requiring increased trigger sensitivity.',
    difficulty: 2,
    topic: 'Advanced Ventilator Concepts',
    isFree: false,
    orderIndex: 320,
  },

  // ============================================================
  // PULMONARY REHABILITATION (321-335)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the primary goals of a pulmonary rehabilitation program?',
    answer: 'Pulmonary rehabilitation aims to reduce dyspnea, improve exercise tolerance, enhance quality of life, and reduce healthcare utilization. It combines exercise training, education, nutritional counseling, and psychosocial support tailored to the individual patient\'s needs and disease severity.',
    difficulty: 1,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 321,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the 6-minute walk test (6MWT) and what does it measure?',
    answer: 'The 6MWT is a submaximal exercise test in which patients walk as far as possible on a flat, hard surface in 6 minutes. It measures functional exercise capacity and is used to assess treatment response, prognosis, and candidacy for pulmonary rehabilitation. Normal distance is approximately 400-700 meters depending on age and gender.',
    difficulty: 1,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 322,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What parameters should be monitored during a 6-minute walk test?',
    answer: 'During the 6MWT, clinicians should monitor SpO2, heart rate, blood pressure, dyspnea level (Borg scale), distance walked, and any symptoms such as chest pain or severe desaturation. The test should be stopped if SpO2 falls below 80%, the patient develops chest pain, or severe symptoms occur.',
    difficulty: 1,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 323,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is the modified Borg scale used in pulmonary rehabilitation?',
    answer: 'The modified Borg scale is a 0-10 rating scale used to assess perceived dyspnea and exertion during exercise. A rating of 0 means no breathlessness and 10 means maximal breathlessness. During exercise training, patients are typically instructed to maintain a dyspnea level of 3-5 (moderate to somewhat severe).',
    difficulty: 1,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 324,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is exercise intensity prescribed in pulmonary rehabilitation for COPD patients?',
    answer: 'Exercise intensity is typically prescribed at 60-80% of the peak work rate achieved during a baseline cardiopulmonary exercise test. Alternatively, a target heart rate of 60-80% of heart rate reserve or a Borg dyspnea score of 4-6 can guide intensity. Sessions usually involve 20-60 minutes of combined upper and lower extremity endurance training.',
    difficulty: 2,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 325,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Why is upper extremity training important in pulmonary rehabilitation?',
    answer: 'Upper extremity training is essential because many activities of daily living (bathing, dressing, grooming) involve the arms. In COPD patients, arm activities recruit accessory muscles that are also used for breathing, creating ventilatory competition. Arm training improves endurance for daily tasks and reduces dyspnea during upper body activities.',
    difficulty: 2,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 326,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What nutritional considerations are important for patients with advanced COPD?',
    answer: 'Patients with advanced COPD often experience weight loss and muscle wasting due to increased work of breathing and systemic inflammation. Dietary recommendations include high-calorie, high-protein meals in small frequent portions, limiting simple carbohydrates (which increase CO2 production), and adequate hydration to thin secretions.',
    difficulty: 2,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 327,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Why should excessive carbohydrate intake be avoided in patients with CO2 retention?',
    answer: 'Carbohydrate metabolism produces the highest respiratory quotient (RQ = 1.0), meaning it generates more CO2 per unit of oxygen consumed compared to fats (RQ = 0.7) or proteins (RQ = 0.8). In patients with limited ventilatory reserve, excess carbohydrates can increase CO2 production beyond their ability to eliminate it, worsening hypercapnia.',
    difficulty: 2,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 328,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the four components of the GOLD classification system for COPD?',
    answer: 'The GOLD system classifies COPD using spirometric grades (1-4 based on FEV1 percent predicted), symptom burden (assessed by mMRC dyspnea scale or CAT score), exacerbation history (frequency and severity of prior exacerbations), and group assignment (A, B, or E) to guide pharmacotherapy decisions.',
    difficulty: 2,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 329,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does the BODE index predict and what variables does it include?',
    answer: 'The BODE index predicts mortality in COPD patients using four variables: Body mass index, degree of airflow Obstruction (FEV1), Dyspnea severity (mMRC scale), and Exercise capacity (6-minute walk distance). Scores range from 0-10, with higher scores indicating greater mortality risk. It is a better predictor of outcomes than FEV1 alone.',
    difficulty: 3,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 330,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the established criteria for prescribing long-term continuous oxygen therapy?',
    answer: 'Long-term oxygen therapy is indicated when resting PaO2 is 55 mmHg or less, or SpO2 is 88% or less on room air. It is also indicated at PaO2 of 56-59 mmHg with evidence of cor pulmonale, polycythemia (hematocrit above 55%), or right heart failure. Usage of at least 15 hours per day has demonstrated a mortality benefit.',
    difficulty: 2,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 331,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What psychosocial issues commonly affect patients with chronic respiratory disease?',
    answer: 'Patients with chronic respiratory disease frequently experience anxiety, depression, social isolation, loss of independence, and fear of dyspnea. These psychosocial factors can worsen symptom perception and reduce adherence to treatment. Pulmonary rehabilitation programs address these through support groups, counseling, relaxation techniques, and peer interaction.',
    difficulty: 1,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 332,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What breathing techniques are taught in pulmonary rehabilitation to manage dyspnea?',
    answer: 'Key techniques include pursed-lip breathing (which creates back-pressure to prevent airway collapse and improve gas exchange), diaphragmatic breathing (to reduce accessory muscle use), and pacing with activity (coordinating breathing with movement). These techniques help patients manage dyspnea during exertion and reduce panic-related hyperventilation.',
    difficulty: 1,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 333,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the minimum recommended duration for a pulmonary rehabilitation program?',
    answer: 'Evidence-based guidelines recommend a minimum of 6-8 weeks of supervised pulmonary rehabilitation, with sessions typically 2-3 times per week. Longer programs (12+ weeks) generally produce greater and more sustained benefits in exercise capacity and quality of life compared to shorter programs.',
    difficulty: 1,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 334,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the minimum clinically important difference for the 6-minute walk test?',
    answer: 'The minimum clinically important difference (MCID) for the 6MWT in COPD patients is approximately 25-33 meters. An improvement of at least this distance after pulmonary rehabilitation indicates a meaningful clinical change that the patient is likely to perceive as beneficial in daily function.',
    difficulty: 3,
    topic: 'Pulmonary Rehabilitation',
    isFree: false,
    orderIndex: 335,
  },

  // ============================================================
  // HOME CARE & DISCHARGE PLANNING (336-350)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does an oxygen concentrator work?',
    answer: 'An oxygen concentrator draws in room air and passes it through a molecular sieve containing zeolite, which adsorbs nitrogen and allows oxygen to pass through. This produces oxygen at concentrations of 87-95% at flow rates typically up to 5-10 L/min. It requires an electrical power source and does not store oxygen.',
    difficulty: 1,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 336,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the advantages of a liquid oxygen system for home use compared to compressed gas cylinders?',
    answer: 'Liquid oxygen systems store a large volume of oxygen in a compact reservoir (1 liter of liquid equals approximately 860 liters of gas). They allow easy filling of lightweight portable units for ambulation, do not require electricity, and provide higher flow rates than concentrators. However, oxygen continuously evaporates and is wasted even when not in use.',
    difficulty: 2,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 337,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a portable oxygen concentrator (POC) and what are its limitations?',
    answer: 'A POC is a battery-powered, lightweight device that concentrates oxygen from ambient air for mobile patients. Limitations include relatively low maximum continuous flow rates (typically 2-3 L/min), limited battery life (2-8 hours), and many models only deliver pulse-dose (demand) oxygen rather than continuous flow, which may be inadequate during sleep.',
    difficulty: 2,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 338,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What oxygen safety precautions should be taught to patients receiving home oxygen therapy?',
    answer: 'Patients should keep oxygen equipment at least 5-10 feet from open flames, heat sources, and electrical appliances that may spark. No smoking in the presence of oxygen, post "Oxygen in Use" signs, avoid petroleum-based products near the face, and ensure adequate ventilation. A fire extinguisher should be readily accessible in the home.',
    difficulty: 1,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 339,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What factors determine the choice between an oxygen concentrator and compressed gas for home oxygen therapy?',
    answer: 'Key factors include the prescribed flow rate (concentrators are limited to 5-10 L/min), need for portability, electrical reliability of the home, continuous versus nocturnal-only use, and patient activity level. Concentrators are most cost-effective for continuous, low-flow use at home, while compressed gas cylinders serve as backup or portable supplementation.',
    difficulty: 2,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 340,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What education topics should be covered when discharging a patient on home oxygen therapy?',
    answer: 'Education should include equipment operation and troubleshooting, prescribed flow rate and usage schedule, safety precautions around open flames, signs and symptoms requiring medical attention, cleaning and maintenance of equipment, backup oxygen supply plan during power outages, and proper use of portable systems during ambulation.',
    difficulty: 1,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 341,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the key components of a home ventilator setup for a patient with a tracheostomy?',
    answer: 'The setup includes a portable volume or pressure ventilator with internal battery, appropriate circuit with heated humidifier, tracheostomy supplies (spare tubes, ties, suction equipment), pulse oximeter, manual resuscitation bag for emergencies, and a backup ventilator or power source. Caregiver training and a 24-hour emergency contact plan are essential.',
    difficulty: 2,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 342,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is durable medical equipment (DME) in the context of respiratory home care?',
    answer: 'DME refers to reusable medical devices prescribed for home use, including oxygen delivery systems, CPAP/BiPAP machines, nebulizers, suction equipment, home ventilators, and pulse oximeters. DME must be ordered by a physician, is typically covered by insurance with documentation of medical necessity, and is supplied by licensed DME providers.',
    difficulty: 1,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 343,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What should a home suction setup include for a tracheostomy patient?',
    answer: 'A home suction setup should include a portable suction machine (electric with battery backup), sterile and clean suction catheters of appropriate size, a collection canister, connecting tubing, clean gloves, sterile saline for rinsing, and a manual backup (bulb syringe or DeLee trap). Caregivers must be trained in proper technique and catheter sizing.',
    difficulty: 2,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 344,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How should a respiratory therapist assess a home environment before discharging a ventilator-dependent patient?',
    answer: 'The assessment should evaluate adequate electrical capacity and grounding, backup power availability, telephone access for emergencies, room size and ventilation, cleanliness, temperature control, and accessibility for equipment. The local utility company and emergency services should be notified of a life-support-dependent resident in the home.',
    difficulty: 2,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 345,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the role of an oxygen-conserving device and how does it work?',
    answer: 'An oxygen-conserving device (demand or pulse-dose system) delivers oxygen only during the initial portion of inspiration rather than continuously. A sensor detects the onset of inspiration and triggers a bolus of oxygen. This reduces oxygen waste during exhalation, extending the duration of portable oxygen supplies by 2-7 times compared to continuous flow.',
    difficulty: 2,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 346,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of a reservoir cannula and how does it conserve oxygen?',
    answer: 'A reservoir cannula (such as a Oxymizer) contains a built-in reservoir that stores approximately 20 mL of oxygen during exhalation. This stored oxygen is available as a bolus at the start of the next inspiration, effectively increasing the FiO2 delivered. It can reduce oxygen consumption by approximately 50%, extending portable supply duration.',
    difficulty: 2,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 347,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What documentation is required for Medicare coverage of home oxygen therapy?',
    answer: 'Medicare requires a Certificate of Medical Necessity (CMN) documenting qualifying arterial blood gas or oximetry results obtained on room air at rest, during exercise, or during sleep. The prescribing physician must specify the flow rate, frequency of use, and estimated duration of need. Recertification testing may be required within 90 days.',
    difficulty: 2,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 348,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What should be included in a caregiver training program for home mechanical ventilation?',
    answer: 'Training must cover ventilator operation and alarm response, manual ventilation with a resuscitation bag, tracheostomy care and emergency tube changes, suctioning technique, signs of respiratory distress, when to call emergency services, equipment troubleshooting, power failure contingency plans, and basic cardiopulmonary resuscitation.',
    difficulty: 1,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 349,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How often should home oxygen concentrators be checked for proper function?',
    answer: 'Home oxygen concentrators should be checked at least monthly by the DME provider for proper oxygen concentration output (should maintain above 85% at prescribed flow), filter cleanliness, alarm function, and general operation. Patients should be taught to clean or replace intake filters weekly and to contact their provider if the low-oxygen alarm sounds.',
    difficulty: 1,
    topic: 'Home Care & Discharge Planning',
    isFree: false,
    orderIndex: 350,
  },

  // ============================================================
  // TRAUMA & SURGICAL RESPIRATORY CARE (351-365)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are common post-operative pulmonary complications and their risk factors?',
    answer: 'Common complications include atelectasis, pneumonia, respiratory failure, bronchospasm, and pleural effusion. Risk factors include upper abdominal or thoracic surgery, general anesthesia duration greater than 3 hours, pre-existing lung disease, smoking history, obesity, advanced age, and poor nutritional status.',
    difficulty: 1,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 351,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What strategies are used to prevent post-operative atelectasis?',
    answer: 'Prevention strategies include incentive spirometry (10 sustained breaths per hour while awake), early ambulation, adequate pain control to allow deep breathing, use of CPAP or positive expiratory pressure devices, coughing and deep breathing exercises, and positioning the patient upright. These are most critical in the first 48-72 hours after surgery.',
    difficulty: 1,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 352,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of a chest tube and what are the common indications for placement?',
    answer: 'A chest tube (thoracostomy tube) is inserted into the pleural space to drain air, blood, or fluid. Common indications include pneumothorax, hemothorax, pleural effusion, empyema, and after thoracic surgery. The tube is connected to a drainage system that typically uses a water seal to prevent air from re-entering the pleural space.',
    difficulty: 1,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 353,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does continuous bubbling in the water seal chamber of a chest drainage system indicate?',
    answer: 'Continuous bubbling in the water seal chamber indicates an air leak. This may be from the lung itself (bronchopleural fistula), from around the chest tube insertion site, or from a connection leak in the system. The therapist should systematically check all connections and clamp the tube briefly near the insertion site to localize the source.',
    difficulty: 2,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 354,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is tidaling in a chest drainage system and what does its absence suggest?',
    answer: 'Tidaling refers to the normal fluctuation of the water level in the water seal chamber that corresponds with respiration. During spontaneous breathing, the water rises on inspiration and falls on exhalation. Absence of tidaling may indicate the tube is kinked, clamped, occluded by a clot, or that the lung has fully re-expanded.',
    difficulty: 2,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 355,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is thoracentesis and how does a respiratory therapist assist?',
    answer: 'Thoracentesis is a procedure in which a needle is inserted through the chest wall into the pleural space to aspirate fluid for diagnostic or therapeutic purposes. The respiratory therapist assists by positioning the patient (usually upright leaning forward), monitoring SpO2 and vital signs, coaching breathing, providing supplemental oxygen, and obtaining post-procedure imaging.',
    difficulty: 2,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 356,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is flail chest and how does it affect ventilation?',
    answer: 'Flail chest occurs when three or more consecutive ribs are fractured in two or more places, creating a free-floating segment. This segment moves paradoxically during breathing (inward during inspiration, outward during expiration), impairing the normal bellows mechanism. The underlying pulmonary contusion rather than the paradoxical motion is the primary cause of hypoxemia.',
    difficulty: 2,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 357,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How is flail chest managed from a respiratory standpoint?',
    answer: 'Management focuses on pain control (epidural analgesia is preferred) to allow adequate ventilation, supplemental oxygen, pulmonary hygiene, and careful fluid management. Mechanical ventilation with positive pressure serves as internal pneumatic stabilization if the patient develops respiratory failure. Non-invasive ventilation may be used in selected patients to avoid intubation.',
    difficulty: 2,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 358,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What respiratory complications are associated with smoke inhalation injury?',
    answer: 'Smoke inhalation can cause upper airway edema and obstruction from thermal injury, chemical tracheobronchitis and mucosal sloughing from toxic gases, carbon monoxide poisoning reducing oxygen-carrying capacity, and cyanide toxicity from combustion of synthetic materials. Delayed complications include ARDS and bacterial pneumonia developing 48-72 hours after exposure.',
    difficulty: 2,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 359,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the initial respiratory management priority in a near-drowning victim?',
    answer: 'The initial priority is establishing a patent airway and providing ventilation with 100% oxygen. Positive pressure ventilation with PEEP is often needed because aspirated water washes out surfactant and causes alveolar collapse. Both fresh and saltwater aspiration produce similar clinical pictures of pulmonary edema, V/Q mismatch, and intrapulmonary shunting.',
    difficulty: 2,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 360,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does high altitude affect oxygenation and what compensatory mechanisms occur?',
    answer: 'At high altitude, the reduced barometric pressure lowers the partial pressure of inspired oxygen (PiO2), causing hypoxemia. Compensatory mechanisms include hyperventilation (increasing alveolar PO2 and reducing PaCO2), increased heart rate and cardiac output, polycythemia from erythropoietin release, and rightward shift of the oxyhemoglobin dissociation curve via increased 2,3-DPG.',
    difficulty: 2,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 361,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the proper response if a chest tube becomes accidentally dislodged?',
    answer: 'If a chest tube is dislodged, immediately cover the insertion site with petroleum gauze (occlusive dressing) taped on three sides to create a flutter-valve effect. This allows air to escape during exhalation but prevents air entry during inspiration. Monitor for signs of tension pneumothorax, administer supplemental oxygen, and notify the physician immediately for tube reinsertion.',
    difficulty: 2,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 362,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What respiratory assessments are critical in a patient with multiple rib fractures?',
    answer: 'Critical assessments include respiratory rate and pattern, tidal volume and minute ventilation, pain level with breathing and coughing, SpO2 monitoring, serial chest radiographs for developing pneumothorax or hemothorax, breath sounds (diminished suggests effusion or atelectasis), and ability to cough and clear secretions. Serial ABGs may be needed if oxygenation worsens.',
    difficulty: 1,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 363,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Why is carbon monoxide poisoning treated with 100% oxygen and what is the role of hyperbaric oxygen?',
    answer: 'The half-life of carboxyhemoglobin (COHb) on room air is approximately 4-6 hours but decreases to 60-90 minutes on 100% oxygen. High-flow 100% oxygen accelerates CO displacement from hemoglobin. Hyperbaric oxygen further reduces the half-life to 15-30 minutes and is considered for severe poisoning (COHb above 25%), neurological symptoms, or pregnant patients.',
    difficulty: 3,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 364,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a pulmonary contusion and how does it progress?',
    answer: 'A pulmonary contusion is bruising of the lung parenchyma caused by blunt chest trauma, resulting in hemorrhage and edema within the alveoli. Symptoms may be minimal initially but typically worsen over 24-72 hours as inflammation and edema progress. Management includes supplemental oxygen, careful fluid resuscitation, pulmonary hygiene, and mechanical ventilation if respiratory failure develops.',
    difficulty: 2,
    topic: 'Trauma & Surgical Respiratory Care',
    isFree: false,
    orderIndex: 365,
  },

  // ============================================================
  // SLEEP-DISORDERED BREATHING BASICS (366-375)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is obstructive sleep apnea (OSA) and what causes it?',
    answer: 'OSA is characterized by repeated episodes of partial or complete upper airway obstruction during sleep, leading to apneas and hypopneas. It is caused by relaxation of the pharyngeal muscles during sleep combined with anatomical factors such as obesity, enlarged tonsils, a large tongue, or a narrow airway. This results in intermittent hypoxemia and sleep fragmentation.',
    difficulty: 1,
    topic: 'Sleep-Disordered Breathing',
    isFree: false,
    orderIndex: 366,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the STOP-BANG questionnaire and what score suggests high risk for OSA?',
    answer: 'STOP-BANG is a screening tool for OSA risk. It evaluates: Snoring, Tiredness, Observed apneas, blood Pressure (hypertension), BMI over 35, Age over 50, Neck circumference over 40 cm, and Gender (male). Each item scores one point. A score of 5 or higher indicates high risk for moderate-to-severe OSA and warrants polysomnography referral.',
    difficulty: 1,
    topic: 'Sleep-Disordered Breathing',
    isFree: false,
    orderIndex: 367,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is polysomnography and what parameters does it measure?',
    answer: 'Polysomnography (PSG) is the gold standard sleep study performed in a sleep laboratory. It simultaneously records EEG (brain waves), EOG (eye movements), EMG (muscle activity), ECG, airflow (nasal and oral), respiratory effort (thoracic and abdominal), SpO2, body position, snoring, and leg movements to diagnose sleep-disordered breathing and other sleep disorders.',
    difficulty: 2,
    topic: 'Sleep-Disordered Breathing',
    isFree: false,
    orderIndex: 368,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the apnea-hypopnea index (AHI) and how is OSA severity classified?',
    answer: 'The AHI represents the average number of apnea and hypopnea events per hour of sleep. OSA severity is classified as mild (AHI 5-14), moderate (AHI 15-29), and severe (AHI 30 or greater). An apnea is cessation of airflow for at least 10 seconds, while a hypopnea is a reduction in airflow of at least 30% with an associated desaturation or arousal.',
    difficulty: 1,
    topic: 'Sleep-Disordered Breathing',
    isFree: false,
    orderIndex: 369,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does auto-CPAP (APAP) differ from fixed CPAP therapy?',
    answer: 'Auto-CPAP automatically adjusts the delivered pressure within a set range based on detected airflow limitation, snoring, or apnea events throughout the night. Fixed CPAP delivers a single constant pressure determined during a titration study. APAP is advantageous for patients whose pressure needs vary with sleep stage, body position, or alcohol and sedative use.',
    difficulty: 2,
    topic: 'Sleep-Disordered Breathing',
    isFree: false,
    orderIndex: 370,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a split-night polysomnography study?',
    answer: 'A split-night study combines the diagnostic portion and CPAP titration in a single night. The first part of the night confirms OSA (typically requiring an AHI of 40 or greater in the first 2 hours, or 20-40 with clinical symptoms), and the remaining time is used to titrate CPAP pressure to eliminate respiratory events. This approach reduces the need for two separate nights of testing.',
    difficulty: 2,
    topic: 'Sleep-Disordered Breathing',
    isFree: false,
    orderIndex: 371,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a mandibular advancement device and when is it indicated for OSA?',
    answer: 'A mandibular advancement device (MAD) is an oral appliance that repositions the lower jaw and tongue forward during sleep to enlarge the upper airway. It is indicated for patients with mild-to-moderate OSA who cannot tolerate CPAP, or as an adjunct therapy. It is less effective than CPAP for severe OSA but has higher adherence rates in appropriate candidates.',
    difficulty: 2,
    topic: 'Sleep-Disordered Breathing',
    isFree: false,
    orderIndex: 372,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the cardiovascular consequences of untreated obstructive sleep apnea?',
    answer: 'Untreated OSA is associated with systemic hypertension, pulmonary hypertension, cardiac arrhythmias (particularly atrial fibrillation), coronary artery disease, heart failure, and increased risk of stroke. The mechanisms include intermittent hypoxemia, sympathetic nervous system activation, oxidative stress, systemic inflammation, and intrathoracic pressure swings.',
    difficulty: 2,
    topic: 'Sleep-Disordered Breathing',
    isFree: false,
    orderIndex: 373,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between obstructive, central, and mixed apneas on a polysomnogram?',
    answer: 'Obstructive apneas show absent airflow with continued respiratory effort (chest and abdominal movement). Central apneas show absent airflow with absent respiratory effort. Mixed apneas begin as central (no effort or flow) and transition to obstructive (effort resumes but airflow remains absent). The distinction is important for selecting appropriate treatment.',
    difficulty: 2,
    topic: 'Sleep-Disordered Breathing',
    isFree: false,
    orderIndex: 374,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What CPAP compliance metrics are typically required by insurance for continued coverage?',
    answer: 'Most insurance policies define CPAP compliance as use of the device for at least 4 hours per night on at least 70% of nights (approximately 21 out of 30 nights) during the initial compliance period (usually the first 90 days). Modern CPAP devices electronically track usage data that can be downloaded to verify adherence.',
    difficulty: 1,
    topic: 'Sleep-Disordered Breathing',
    isFree: false,
    orderIndex: 375,
  },

  // ============================================================
  // SPECIAL POPULATIONS (376-390)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What age-related changes in the respiratory system affect elderly patients?',
    answer: 'Aging causes decreased chest wall compliance (calcification of costal cartilage), reduced elastic recoil of the lungs, decreased respiratory muscle strength, diminished cough reflex, reduced mucociliary clearance, and decreased ventilatory response to hypoxia and hypercapnia. These changes reduce functional reserve and increase susceptibility to respiratory infections and failure.',
    difficulty: 1,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 376,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does obesity affect respiratory mechanics in bariatric patients?',
    answer: 'Obesity reduces functional residual capacity and expiratory reserve volume due to increased abdominal pressure compressing the diaphragm. It increases work of breathing, reduces chest wall compliance, and promotes ventilation-perfusion mismatch in dependent lung zones. Obese patients desaturate more rapidly during apnea due to lower oxygen reserves and increased metabolic demand.',
    difficulty: 2,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 377,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is obesity hypoventilation syndrome (OHS) and how does it differ from OSA?',
    answer: 'OHS is defined by the triad of obesity (BMI 30 or greater), daytime hypercapnia (PaCO2 above 45 mmHg), and sleep-disordered breathing in the absence of other causes of hypoventilation. While most OHS patients also have OSA, OHS specifically involves chronic daytime CO2 retention that OSA alone does not. Treatment often requires BiPAP rather than CPAP alone.',
    difficulty: 3,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 378,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What respiratory complications are common in patients with neuromuscular diseases such as ALS or muscular dystrophy?',
    answer: 'Neuromuscular diseases cause progressive respiratory muscle weakness leading to ineffective cough (increasing aspiration and pneumonia risk), nocturnal hypoventilation progressing to daytime hypercapnia, reduced vital capacity, and eventual respiratory failure. Monitoring with serial vital capacity and maximal inspiratory pressure measurements helps guide intervention timing.',
    difficulty: 2,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 379,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a mechanical insufflation-exsufflation (MI-E) device and when is it used?',
    answer: 'An MI-E device (commonly known by the brand name CoughAssist) delivers a deep inspiration via positive pressure followed by an abrupt switch to negative pressure to simulate a cough. It is used in patients with neuromuscular weakness who have an inadequate peak cough flow (less than 270 L/min) to help clear secretions and prevent atelectasis and pneumonia.',
    difficulty: 2,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 380,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does spinal cord injury level affect respiratory function?',
    answer: 'Injuries at C1-C2 eliminate all respiratory muscle function requiring full ventilatory support. C3-C5 injuries impair diaphragm function (phrenic nerve origins) with variable ventilator dependence. Injuries below C5 spare the diaphragm but impair intercostal and abdominal muscles, reducing cough effectiveness and vital capacity. Higher injury levels cause greater respiratory compromise.',
    difficulty: 2,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 381,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a diaphragm pacing system and who is it appropriate for?',
    answer: 'A diaphragm pacing system electrically stimulates the phrenic nerve to cause diaphragmatic contraction, providing ventilation without a mechanical ventilator. It is appropriate for patients with high cervical spinal cord injuries (C1-C2) who have intact phrenic nerves and diaphragm muscles. It allows greater mobility and speech compared to positive pressure ventilation.',
    difficulty: 3,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 382,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What unique respiratory challenges do burn patients face?',
    answer: 'Burn patients face inhalation injury (upper airway edema, chemical tracheobronchitis, CO and cyanide poisoning), circumferential chest burns restricting chest wall expansion (may require escharotomy), massive fluid resuscitation causing pulmonary edema, hypermetabolism increasing CO2 production and oxygen demand, and high risk for nosocomial pneumonia due to immune suppression.',
    difficulty: 2,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 383,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is an escharotomy and why might it be necessary for respiratory care?',
    answer: 'An escharotomy is a surgical incision through burned, inelastic eschar tissue. When circumferential full-thickness burns of the chest restrict chest wall expansion, escharotomy is necessary to restore thoracic compliance and allow adequate ventilation. Without it, the rigid eschar acts like a constrictive band, severely limiting tidal volume and increasing peak airway pressures.',
    difficulty: 3,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 384,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What respiratory precautions are important when caring for immunocompromised patients?',
    answer: 'Immunocompromised patients require strict infection control including hand hygiene, protective isolation (positive-pressure rooms for transplant patients), use of sterile technique for all respiratory procedures, avoiding nebulizers that may aerosolize pathogens, and monitoring for opportunistic infections such as Pneumocystis jirovecii pneumonia and invasive aspergillosis.',
    difficulty: 1,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 385,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What ventilator considerations apply to morbidly obese patients?',
    answer: 'Morbidly obese patients require higher PEEP levels (10-15 cmH2O) to prevent dependent atelectasis, tidal volumes based on ideal body weight (not actual weight), semi-upright or reverse Trendelenburg positioning to offload the abdomen, and potentially higher FiO2 initially. Recruitment maneuvers may be needed more frequently due to rapid derecruitment.',
    difficulty: 2,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 386,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'When should non-invasive ventilation be initiated in a patient with progressive neuromuscular disease?',
    answer: 'NIV should be initiated when symptoms of nocturnal hypoventilation appear (morning headache, daytime somnolence, fatigue) or when objective criteria are met: FVC below 50% predicted, MIP weaker than negative 60 cmH2O, nocturnal SpO2 below 88% for more than 5 consecutive minutes, or PaCO2 above 45 mmHg. Early initiation improves survival and quality of life.',
    difficulty: 3,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 387,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is autonomic dysreflexia and why should respiratory therapists be aware of it?',
    answer: 'Autonomic dysreflexia is a potentially life-threatening condition in patients with spinal cord injuries at T6 or above, triggered by noxious stimuli below the injury level (including suctioning or bladder distension). It causes severe hypertension, bradycardia, headache, and flushing. Respiratory therapists must recognize it because tracheal suctioning is a common trigger and the hypertensive crisis requires immediate attention.',
    difficulty: 3,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 388,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does aging affect the response to bronchodilator therapy?',
    answer: 'Elderly patients may show a reduced bronchodilator response due to decreased beta-2 receptor density and sensitivity. They are also more susceptible to adverse effects including tachycardia, tremor, and hypokalemia from beta-agonists, and urinary retention, dry mouth, and glaucoma exacerbation from anticholinergics. Dosing adjustments and careful monitoring are warranted.',
    difficulty: 2,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 389,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is glossopharyngeal breathing and which patient population benefits from it?',
    answer: 'Glossopharyngeal breathing (frog breathing) is a technique in which the patient uses the tongue and pharyngeal muscles to gulp small volumes of air into the lungs, stacking them to achieve a larger breath. It benefits patients with high spinal cord injuries or neuromuscular diseases to augment tidal volume for cough and brief periods of ventilator-free breathing.',
    difficulty: 3,
    topic: 'Special Populations',
    isFree: false,
    orderIndex: 390,
  },

  // ============================================================
  // PROFESSIONAL PRACTICE & PROTOCOLS (391-400)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a therapist-driven protocol (TDP) in respiratory care?',
    answer: 'A TDP is a pre-approved set of clinical guidelines that allows respiratory therapists to independently initiate, adjust, or discontinue respiratory care services based on patient assessment without requiring individual physician orders for each change. TDPs are developed collaboratively with physicians and approved by medical staff, enabling more timely and efficient patient care.',
    difficulty: 1,
    topic: 'Professional Practice & Protocols',
    isFree: false,
    orderIndex: 391,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the key benefits of therapist-driven protocols?',
    answer: 'TDPs improve resource allocation by directing therapy to patients who need it, reduce unnecessary treatments, improve timeliness of care adjustments, enhance therapist job satisfaction and professional autonomy, standardize evidence-based care delivery, and have been shown to reduce hospital length of stay and respiratory care costs without compromising outcomes.',
    difficulty: 1,
    topic: 'Professional Practice & Protocols',
    isFree: false,
    orderIndex: 392,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What components should be included in a respiratory care plan documented in the medical record?',
    answer: 'A respiratory care plan should include the patient assessment findings, identified problems, specific therapy goals with measurable outcomes, prescribed interventions and their rationale, frequency and duration of treatments, criteria for modifying or discontinuing therapy, patient education provided, and planned reassessment schedule.',
    difficulty: 1,
    topic: 'Professional Practice & Protocols',
    isFree: false,
    orderIndex: 393,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the legal and professional significance of proper documentation in respiratory care?',
    answer: 'Documentation serves as a legal record of care provided, supports communication among the healthcare team, justifies medical necessity for reimbursement, provides data for quality improvement, and protects the practitioner in liability situations. The standard principle is "if it was not documented, it was not done." Entries must be timely, accurate, objective, and legible.',
    difficulty: 1,
    topic: 'Professional Practice & Protocols',
    isFree: false,
    orderIndex: 394,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between the CRT and RRT credentials?',
    answer: 'The CRT (Certified Respiratory Therapist) is the entry-level credential earned by passing the TMC exam at the low-cut score. The RRT (Registered Respiratory Therapist) is the advanced credential requiring passage of the TMC at the high-cut score plus the Clinical Simulation Exam (CSE). The RRT demonstrates advanced clinical competency and is increasingly required by employers.',
    difficulty: 1,
    topic: 'Professional Practice & Protocols',
    isFree: false,
    orderIndex: 395,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the scope of practice for a respiratory therapist?',
    answer: 'The respiratory therapy scope of practice, defined by state licensure laws and practice acts, includes diagnostic testing (ABGs, PFTs, sleep studies), therapeutic interventions (oxygen therapy, aerosol medication delivery, airway management, mechanical ventilation), patient assessment, care plan development, patient education, and cardiopulmonary rehabilitation. Scope varies by state.',
    difficulty: 1,
    topic: 'Professional Practice & Protocols',
    isFree: false,
    orderIndex: 396,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What continuing education requirements must respiratory therapists meet to maintain their credentials?',
    answer: 'The NBRC requires respiratory therapists to renew their credentials every 5 years. This can be accomplished through completion of continuing education credits, retaking the credentialing exam, or obtaining a specialty credential. State licensure boards may have additional CE requirements. CE ensures practitioners remain current with evolving evidence-based practices.',
    difficulty: 1,
    topic: 'Professional Practice & Protocols',
    isFree: false,
    orderIndex: 397,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the NBRC and what role does it play in respiratory therapy?',
    answer: 'The National Board for Respiratory Care (NBRC) is the credentialing organization for respiratory therapists in the United States. It develops and administers the TMC and CSE examinations, awards the CRT and RRT credentials, and manages credential renewal. The NBRC does not regulate licensure, which is managed by individual state boards.',
    difficulty: 1,
    topic: 'Professional Practice & Protocols',
    isFree: false,
    orderIndex: 398,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What quality improvement metrics are commonly tracked in a respiratory care department?',
    answer: 'Common metrics include ventilator-associated event rates, unplanned extubation rates, reintubation rates within 48 hours, protocol compliance rates, medication error rates, patient satisfaction scores, oxygen therapy misallocation rates, and length of time on mechanical ventilation. These metrics drive evidence-based practice improvement and are often reported to hospital quality committees.',
    difficulty: 2,
    topic: 'Professional Practice & Protocols',
    isFree: false,
    orderIndex: 399,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the role of the respiratory therapist in a rapid response team?',
    answer: 'The respiratory therapist is a core member of the rapid response team, responsible for airway assessment and management, initiating oxygen therapy or non-invasive ventilation, performing bag-mask ventilation, assisting with emergency intubation, obtaining and interpreting ABGs, setting up mechanical ventilation, and providing continuous cardiopulmonary monitoring during patient stabilization.',
    difficulty: 1,
    topic: 'Professional Practice & Protocols',
    isFree: false,
    orderIndex: 400,
  },
];

async function main() {
  console.log('Seeding TMC Batch 4 (cards 301-400)...');
  console.log(`Total cards to insert: ${cards.length}`);

  const result = await prisma.flashcard.createMany({
    data: cards,
    skipDuplicates: true,
  });

  console.log(`Successfully inserted ${result.count} flashcards.`);
  console.log('TMC Batch 4 seeding complete.');
}

main()
  .catch((e) => {
    console.error('Error seeding TMC Batch 4:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
