import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding RPFT flashcards batch 4 (cards 301-400)...')

  await prisma.flashcard.createMany({
    data: [
      // --- Advanced Interpretation Algorithms and Decision Trees (cards 301-310) ---
      {
        question: 'In a stepwise PFT interpretation algorithm, what is the recommended first branch point after determining that FEV1/FVC is reduced?',
        answer: 'The next step is to assess TLC to distinguish true obstruction (normal or elevated TLC) from a mixed obstructive-restrictive pattern (reduced TLC). This prevents misclassifying restriction with airflow limitation as pure obstruction.',
        difficulty: 2,
        topic: 'Advanced Interpretation Algorithms',
        isFree: false,
        orderIndex: 301,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'When applying the ATS/ERS interpretive algorithm, how should you classify a patient with a normal FEV1/FVC ratio but FVC and TLC both below the lower limit of normal (LLN)?',
        answer: 'This pattern is classified as restriction. A normal FEV1/FVC with reduced FVC suggests restriction, and a reduced TLC confirms it. The algorithm requires TLC measurement to definitively diagnose restriction rather than relying on FVC alone.',
        difficulty: 1,
        topic: 'Advanced Interpretation Algorithms',
        isFree: false,
        orderIndex: 302,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A patient shows FEV1/FVC below LLN, TLC above ULN, and RV/TLC ratio markedly elevated. DLCO is reduced. What interpretive conclusion does this decision-tree pathway support?',
        answer: 'This pathway indicates obstructive lung disease with hyperinflation and gas trapping (elevated TLC and RV/TLC), combined with impaired gas exchange (reduced DLCO), most consistent with emphysema. The decision tree distinguishes this from asthma, where DLCO is typically preserved or elevated.',
        difficulty: 2,
        topic: 'Advanced Interpretation Algorithms',
        isFree: false,
        orderIndex: 303,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'In the GLI-2012 reference framework, what statistical method replaced percent predicted for defining the lower limit of normal?',
        answer: 'The GLI-2012 uses z-scores derived from lambda-mu-sigma (LMS) equations. A z-score of -1.645 defines the 5th percentile (LLN). This approach accounts for age-dependent variability and skewness of the distribution, providing more accurate classification than fixed percent-predicted cutoffs.',
        difficulty: 2,
        topic: 'Advanced Interpretation Algorithms',
        isFree: false,
        orderIndex: 304,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'Why is using a fixed FEV1/FVC ratio of 0.70 problematic in elderly patients according to current interpretive guidelines?',
        answer: 'A fixed 0.70 cutoff leads to overdiagnosis of obstruction in older adults because FEV1/FVC naturally declines with age. The LLN for FEV1/FVC falls below 0.70 in many individuals over age 60-65. Using age-adjusted LLN (z-score approach) avoids this false-positive classification.',
        difficulty: 1,
        topic: 'Advanced Interpretation Algorithms',
        isFree: false,
        orderIndex: 305,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does a decision-tree algorithm differentiate neuromuscular weakness from parenchymal restriction when both show reduced TLC?',
        answer: 'Key differentiators include: (1) MIP/MEP are reduced in neuromuscular disease but preserved in parenchymal restriction, (2) DLCO corrected for alveolar volume (KCO) is preserved or elevated in neuromuscular disease but reduced in parenchymal disease like ILD, (3) supine FVC drops >20% in diaphragmatic weakness, and (4) MVV is disproportionately reduced relative to FEV1 in neuromuscular disease.',
        difficulty: 3,
        topic: 'Advanced Interpretation Algorithms',
        isFree: false,
        orderIndex: 306,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the significance of a bronchodilator response showing improvement in FVC but not FEV1 in a patient with apparent obstruction?',
        answer: 'An isolated FVC response without FEV1 improvement suggests reduction in air trapping and hyperinflation rather than reversal of airway smooth muscle contraction. This pattern is common in emphysema where bronchodilators reduce dynamic hyperinflation, improving exertional capacity even without classic spirometric reversibility.',
        difficulty: 2,
        topic: 'Advanced Interpretation Algorithms',
        isFree: false,
        orderIndex: 307,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'In a systematic interpretation framework, what three conditions must be evaluated when FEV1/FVC is normal but FEV1 and FVC are both reduced proportionally?',
        answer: 'The three conditions are: (1) restriction confirmed by reduced TLC, (2) submaximal effort or poor technique causing proportional reduction without true disease, and (3) the nonspecific ventilatory pattern where TLC is normal despite reduced FEV1 and FVC, which may occur in obesity, early disease, or air trapping not captured by plethysmography.',
        difficulty: 3,
        topic: 'Advanced Interpretation Algorithms',
        isFree: false,
        orderIndex: 308,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What severity grading system does the ATS/ERS recommend once an obstructive or restrictive pattern is identified?',
        answer: 'Severity is graded using FEV1 percent predicted (regardless of the type of abnormality): mild (>70%), moderate (60-69%), moderately severe (50-59%), severe (35-49%), and very severe (<35%). This single-parameter grading applies after the pattern is established by FEV1/FVC and TLC.',
        difficulty: 1,
        topic: 'Advanced Interpretation Algorithms',
        isFree: false,
        orderIndex: 309,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How should an interpretive algorithm handle discordance between plethysmographic TLC and dilution TLC?',
        answer: 'Plethysmographic TLC exceeding dilution TLC by more than 1 liter or >10% suggests significant gas trapping, as dilution methods underestimate lung volume in regions with poor ventilation. The algorithm should use plethysmographic TLC as the definitive value for classifying restriction, while noting the discordance as evidence of inhomogeneous ventilation distribution.',
        difficulty: 3,
        topic: 'Advanced Interpretation Algorithms',
        isFree: false,
        orderIndex: 310,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Longitudinal PFT Monitoring and Rate of Decline (cards 311-320) ---
      {
        question: 'What is the expected annual rate of FEV1 decline in healthy nonsmoking adults after age 25-30?',
        answer: 'Healthy nonsmoking adults lose approximately 20-30 mL/year of FEV1. This accelerates with aging, reaching 30-40 mL/year after age 65. Rates exceeding 40-50 mL/year suggest accelerated decline and should prompt investigation for occupational exposures, undiagnosed disease, or other risk factors.',
        difficulty: 1,
        topic: 'Longitudinal PFT Monitoring',
        isFree: false,
        orderIndex: 311,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'When monitoring FEV1 decline longitudinally, what minimum number of data points and time span are recommended to establish a reliable rate of decline?',
        answer: 'At least 3-5 data points over a minimum of 2-3 years are recommended to establish a reliable decline rate. Individual measurement variability (approximately 150-200 mL for FEV1) can produce misleading trends with fewer observations or shorter intervals. Linear regression analysis is preferred over simple two-point comparisons.',
        difficulty: 2,
        topic: 'Longitudinal PFT Monitoring',
        isFree: false,
        orderIndex: 312,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How do you differentiate a significant year-over-year FEV1 change from normal measurement variability in a longitudinal monitoring program?',
        answer: 'A clinically significant change exceeds the coefficient of repeatability, which is approximately 330 mL or 12% for FEV1 in within-session measurements. For between-session (week-to-week) variability, the threshold is higher, approximately 15% or 380 mL. Changes below these thresholds may represent normal biological and technical variability rather than true disease progression.',
        difficulty: 2,
        topic: 'Longitudinal PFT Monitoring',
        isFree: false,
        orderIndex: 313,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the annual limit of decline (ALD) method used in occupational spirometry surveillance programs?',
        answer: 'The ALD is a statistically derived threshold that accounts for normal age-related decline plus expected measurement variability. If a workers FEV1 or FVC decline exceeds the ALD compared to their personal baseline, it triggers a referral for medical evaluation. OSHA and NIOSH recommend using the ALD to detect accelerated decline before clinical impairment occurs.',
        difficulty: 2,
        topic: 'Longitudinal PFT Monitoring',
        isFree: false,
        orderIndex: 314,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'In monitoring FVC decline for idiopathic pulmonary fibrosis (IPF), what threshold of absolute decline over 6-12 months is considered a predictor of increased mortality?',
        answer: 'A decline in FVC of 5-10% absolute (or approximately 200 mL) over 6-12 months in IPF is associated with increased mortality risk. A decline of 10% or more is strongly predictive of worse outcomes and may prompt escalation of therapy or transplant referral. Marginal declines of 5-10% are considered possibly significant and warrant close follow-up.',
        difficulty: 3,
        topic: 'Longitudinal PFT Monitoring',
        isFree: false,
        orderIndex: 315,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'Why is it important to use the same spirometer, technologist, and testing conditions when performing longitudinal PFT monitoring?',
        answer: 'Between-device variability can be 100-150 mL for FEV1 even among calibrated spirometers. Different technologists may elicit different effort quality. Time of day, bronchodilator timing, and patient positioning also affect results. Standardizing these variables reduces non-disease-related variability, improving the signal-to-noise ratio for detecting true physiologic changes.',
        difficulty: 1,
        topic: 'Longitudinal PFT Monitoring',
        isFree: false,
        orderIndex: 316,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is a personal best baseline established for longitudinal spirometry monitoring in workplace surveillance programs?',
        answer: 'The personal best baseline is typically the highest FEV1 and FVC from at least two acceptable quality tests performed within the first year of employment or monitoring. Some programs require three sessions within the first 6-12 months. The baseline should be obtained when the worker is in stable health and should be updated if values improve significantly, suggesting the initial baseline did not reflect true maximal performance.',
        difficulty: 2,
        topic: 'Longitudinal PFT Monitoring',
        isFree: false,
        orderIndex: 317,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What statistical method is most appropriate for analyzing longitudinal FEV1 decline in research studies with unequal observation intervals and missing data?',
        answer: 'Mixed-effects linear models (also called linear mixed models or random coefficient models) are preferred. They handle unequal time intervals between measurements, accommodate missing data under the missing-at-random assumption, account for within-subject correlation, and allow both fixed effects (group-level trends) and random effects (individual variation in baseline and decline rate).',
        difficulty: 3,
        topic: 'Longitudinal PFT Monitoring',
        isFree: false,
        orderIndex: 318,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'In COPD monitoring, what is the "horse-racing effect" in longitudinal FEV1 studies?',
        answer: 'The horse-racing effect refers to selection bias in longitudinal studies where participants with the most rapid FEV1 decline drop out (due to death, disability, or inability to perform testing), leaving a healthier survivor cohort. This artificially flattens the observed mean decline rate over time and can lead to underestimation of true disease progression in the population.',
        difficulty: 3,
        topic: 'Longitudinal PFT Monitoring',
        isFree: false,
        orderIndex: 319,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What role does DLCO trending play in monitoring patients with systemic sclerosis (scleroderma)?',
        answer: 'Serial DLCO is critical for detecting pulmonary vascular disease and interstitial lung disease in scleroderma. A declining DLCO with preserved lung volumes suggests developing pulmonary arterial hypertension. A declining DLCO with declining FVC suggests progressive ILD. A disproportionate DLCO drop (DLCO declining faster than FVC) should prompt echocardiographic screening for pulmonary hypertension.',
        difficulty: 3,
        topic: 'Longitudinal PFT Monitoring',
        isFree: false,
        orderIndex: 320,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- PFT Laboratory Management and Accreditation (cards 321-330) ---
      {
        question: 'What organization provides accreditation specifically for pulmonary function laboratories in the United States?',
        answer: 'The American Association for Respiratory Care (AARC) offers the PFT laboratory accreditation program. Additionally, the College of American Pathologists (CAP) accredits laboratories performing arterial blood gas analysis. ATS/ERS provide technical standards but do not directly accredit individual laboratories.',
        difficulty: 1,
        topic: 'PFT Lab Management and Accreditation',
        isFree: false,
        orderIndex: 321,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the key components of a PFT laboratory quality management system as outlined by ATS/ERS?',
        answer: 'Key components include: (1) written standard operating procedures for all tests, (2) daily calibration verification and documentation, (3) biological control (bio-QC) programs using healthy subjects, (4) equipment maintenance logs, (5) technologist competency assessment and continuing education, (6) proficiency testing participation, (7) medical director oversight, (8) infection control protocols, and (9) periodic review of over-read accuracy and inter-technologist variability.',
        difficulty: 2,
        topic: 'PFT Lab Management and Accreditation',
        isFree: false,
        orderIndex: 322,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is a biological quality control (bio-QC) program implemented in a PFT laboratory?',
        answer: 'A bio-QC program uses one or more healthy, nonsmoking staff members who perform spirometry at regular intervals (typically weekly or biweekly). Results are plotted on control charts with established mean and standard deviation. Values exceeding 2 SD from the personal mean trigger investigation for equipment malfunction. Bio-QC detects drift or systematic errors that calibration checks alone may miss, particularly for effort-dependent maneuvers.',
        difficulty: 2,
        topic: 'PFT Lab Management and Accreditation',
        isFree: false,
        orderIndex: 323,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What daily quality control procedure must be performed on a volume-displacement spirometer before patient testing?',
        answer: 'A calibration verification (not full calibration) must be performed using a validated 3-liter syringe at three different flow rates (low, medium, high). The measured volume must be within 3.5% of the syringe volume (3.0 L plus or minus 105 mL). If the check fails, the spirometer must be recalibrated or serviced before patient testing begins. Results must be documented.',
        difficulty: 1,
        topic: 'PFT Lab Management and Accreditation',
        isFree: false,
        orderIndex: 324,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What infection control measures are required between patients in a PFT laboratory?',
        answer: 'Required measures include: (1) use of disposable inline bacterial/viral filters for spirometry and DLCO, (2) hand hygiene between patients, (3) surface disinfection of mouthpieces, nose clips, and shared equipment, (4) proper handling and disposal of contaminated filters and tubing, (5) isolation protocols for patients with known or suspected transmissible respiratory infections, and (6) adherence to institutional infection prevention policies including PPE requirements.',
        difficulty: 1,
        topic: 'PFT Lab Management and Accreditation',
        isFree: false,
        orderIndex: 325,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the responsibilities of the medical director of a PFT laboratory?',
        answer: 'The medical director is responsible for: (1) overseeing quality assurance and quality improvement programs, (2) reviewing and approving SOPs, (3) interpreting and signing PFT reports, (4) ensuring technologist competency and credentialing, (5) addressing quality concerns and corrective actions, (6) selecting reference equations, (7) establishing interpretive guidelines, (8) evaluating new equipment and tests, and (9) ensuring compliance with accreditation standards and regulatory requirements.',
        difficulty: 2,
        topic: 'PFT Lab Management and Accreditation',
        isFree: false,
        orderIndex: 326,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What documentation must a PFT laboratory maintain for CAP accreditation of blood gas analysis?',
        answer: 'Required documentation includes: (1) daily two-level quality control with Levey-Jennings charts, (2) calibration records, (3) proficiency testing results (minimum twice annually), (4) corrective action logs for out-of-range QC, (5) reagent/electrode lot change records, (6) instrument maintenance logs, (7) personnel competency assessments, (8) procedure manual reviewed annually, and (9) correlation studies when multiple analyzers are in use.',
        difficulty: 3,
        topic: 'PFT Lab Management and Accreditation',
        isFree: false,
        orderIndex: 327,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How should a PFT laboratory handle Westgard rule violations in blood gas analyzer quality control?',
        answer: 'Common Westgard rules include: 1-2s (warning), 1-3s (reject run, random error), 2-2s (reject if same direction, systematic error), R-4s (reject, random error), 4-1s (reject if trending, systematic error), and 10x (reject if 10 consecutive on same side of mean). When a rejection rule triggers, patient testing stops, the cause is investigated, corrective action is documented, and QC is repeated before resuming testing.',
        difficulty: 3,
        topic: 'PFT Lab Management and Accreditation',
        isFree: false,
        orderIndex: 328,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What elements should be included in a PFT report according to ATS/ERS recommendations?',
        answer: 'A complete report should include: patient demographics and anthropometrics, test indication, medication status, reference equations used, numerical results with predicted values and LLN/z-scores, bronchodilator response data if applicable, quality grades for each maneuver, graphical displays (flow-volume loops, volume-time curves), technologist comments on cooperation and effort, and an interpretive summary signed by the medical director.',
        difficulty: 1,
        topic: 'PFT Lab Management and Accreditation',
        isFree: false,
        orderIndex: 329,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the recommended frequency and method for verifying DLCO analyzer gas concentrations?',
        answer: 'Gas analyzer accuracy should be verified daily using a certified reference gas mixture with known concentrations of CO, tracer gas (helium, methane, or neon), and balance air. The measured concentrations should agree within 1% absolute of the certified values. Linearity should be checked periodically across the measurement range. Gas cylinder certificates of analysis must be retained for documentation.',
        difficulty: 2,
        topic: 'PFT Lab Management and Accreditation',
        isFree: false,
        orderIndex: 330,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Telemedicine and Remote Spirometry (cards 331-337) ---
      {
        question: 'What are the key technical requirements for valid home spirometry used in telemedicine monitoring programs?',
        answer: 'Requirements include: (1) devices meeting ATS/ERS accuracy and precision standards, (2) built-in quality checks for acceptability (back-extrapolated volume, plateau detection, effort duration), (3) automated data transmission to a central platform, (4) technologist or automated review of flow-volume curves for quality grading, (5) patient training with return demonstration, and (6) standardized testing protocols including time of day, bronchodilator withholding, and body position.',
        difficulty: 2,
        topic: 'Telemedicine and Remote Spirometry',
        isFree: false,
        orderIndex: 331,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What quality challenges are unique to unsupervised home spirometry compared to laboratory-based testing?',
        answer: 'Challenges include: (1) inability to directly coach maximal effort, (2) higher rates of submaximal or unacceptable maneuvers, (3) variable environmental conditions (temperature, humidity), (4) inconsistent body positioning, (5) difficulty verifying filter use and hygiene, (6) potential for effort-related artifacts without real-time technologist feedback, and (7) reliance on automated quality algorithms that may not catch all technical errors visible to an experienced technologist.',
        difficulty: 2,
        topic: 'Telemedicine and Remote Spirometry',
        isFree: false,
        orderIndex: 332,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'In lung transplant monitoring, how is home spirometry used to detect early allograft dysfunction?',
        answer: 'Transplant recipients perform daily or thrice-weekly home spirometry. A sustained decline in FEV1 of 10-15% from the personal best baseline triggers clinical evaluation for acute rejection, infection, or bronchiolitis obliterans syndrome (BOS). Early detection through frequent home monitoring can lead to earlier intervention and potentially better outcomes compared to clinic-only spirometry performed at less frequent intervals.',
        difficulty: 2,
        topic: 'Telemedicine and Remote Spirometry',
        isFree: false,
        orderIndex: 333,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What role does the RPFT play in overseeing a telemedicine spirometry program?',
        answer: 'The RPFT is responsible for: (1) validating device accuracy and establishing QC protocols for remote devices, (2) training patients on proper technique via video instruction, (3) remotely reviewing transmitted spirometry data for technical quality, (4) flagging suboptimal maneuvers and coaching patients to improve technique, (5) establishing alert thresholds for clinician notification, (6) maintaining compliance with regulatory and accreditation standards, and (7) ensuring data security and HIPAA compliance in transmission and storage.',
        difficulty: 1,
        topic: 'Telemedicine and Remote Spirometry',
        isFree: false,
        orderIndex: 334,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the ATS 2019 recommendations regarding office-based spirometry performed by non-PFT-specialist personnel?',
        answer: 'ATS recommends that office spirometry should use devices meeting ATS/ERS technical standards, operators should receive formal training including competency assessment, built-in quality feedback and automated grading should be available, over-reading by qualified personnel should be implemented, and results should be interpreted using LLN rather than fixed ratio cutoffs. Without these safeguards, office spirometry has unacceptably high rates of poor-quality tests.',
        difficulty: 1,
        topic: 'Telemedicine and Remote Spirometry',
        isFree: false,
        orderIndex: 335,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does ambient temperature and humidity correction apply to portable spirometry devices used in field or home settings?',
        answer: 'Spirometers measure gas at ambient temperature and pressure saturated (ATPS) and must convert to body temperature and pressure saturated (BTPS). Portable devices should have built-in temperature sensors for automatic BTPS correction. Extreme temperatures (below 17C or above 40C) may exceed the devices correction range and produce inaccurate results. Humidity affects gas density and viscosity, particularly for turbine and ultrasonic flow sensors.',
        difficulty: 3,
        topic: 'Telemedicine and Remote Spirometry',
        isFree: false,
        orderIndex: 336,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What data security considerations must be addressed when transmitting PFT results in a telemedicine program?',
        answer: 'Considerations include: (1) HIPAA-compliant encrypted data transmission (TLS/SSL), (2) secure cloud storage with access controls, (3) patient authentication before data upload, (4) audit trails for data access, (5) Business Associate Agreements with device manufacturers and cloud providers, (6) data integrity verification to prevent corruption during transmission, and (7) compliance with state-specific telehealth regulations and licensure requirements.',
        difficulty: 1,
        topic: 'Telemedicine and Remote Spirometry',
        isFree: false,
        orderIndex: 337,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Emerging Technologies (cards 338-347) ---
      {
        question: 'How does forced oscillation technique (FOT) using broadband frequency signals differ from impulse oscillometry (IOS) in clinical application?',
        answer: 'FOT applies continuous multifrequency pressure oscillations during tidal breathing, while IOS uses discrete impulse signals. Both measure respiratory impedance (resistance and reactance), but broadband FOT can provide more detailed frequency-dependent information. FOT/IOS advantages over spirometry include effort independence, tidal breathing measurement, and ability to test young children and patients unable to perform forced maneuvers.',
        difficulty: 2,
        topic: 'Emerging Technologies',
        isFree: false,
        orderIndex: 338,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the principle behind nitrogen multiple-breath washout (N2 MBW) testing and what does it measure?',
        answer: 'N2 MBW measures ventilation inhomogeneity by having the patient breathe 100% O2 while monitoring the washout of resident nitrogen from the lungs. The lung clearance index (LCI) is the number of lung turnovers needed to clear N2 to 1/40th of the starting concentration. Elevated LCI indicates uneven ventilation distribution and is sensitive to early small airway disease, particularly in cystic fibrosis, often detecting abnormalities before spirometry.',
        difficulty: 2,
        topic: 'Emerging Technologies',
        isFree: false,
        orderIndex: 339,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the clinical utility of exhaled nitric oxide (FeNO) measurement and what cutoff values guide interpretation?',
        answer: 'FeNO reflects eosinophilic airway inflammation. ATS guidelines suggest: <25 ppb in adults indicates low eosinophilic inflammation (less likely to respond to corticosteroids), 25-50 ppb is intermediate, and >50 ppb indicates high eosinophilic inflammation (likely steroid responsive). Values are affected by atopy, smoking (lowers FeNO), age, height, and recent respiratory infections. FeNO is useful for asthma diagnosis, phenotyping, and monitoring adherence to inhaled corticosteroids.',
        difficulty: 1,
        topic: 'Emerging Technologies',
        isFree: false,
        orderIndex: 340,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the potential clinical role of computational fluid dynamics (CFD) modeling based on CT imaging in pulmonary diagnostics?',
        answer: 'CFD uses CT-derived airway geometry to simulate airflow patterns, pressure drops, and particle deposition throughout the tracheobronchial tree. Clinical applications include: predicting response to bronchodilators, optimizing inhaler device selection, planning surgical interventions for tracheal stenosis, assessing regional ventilation heterogeneity, and personalizing aerosol drug delivery. It remains largely a research tool but is moving toward clinical translation.',
        difficulty: 3,
        topic: 'Emerging Technologies',
        isFree: false,
        orderIndex: 341,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does electrical impedance tomography (EIT) provide real-time assessment of regional lung ventilation?',
        answer: 'EIT uses a belt of electrodes placed around the thorax that inject small alternating currents and measure resulting voltage patterns. Changes in thoracic impedance during breathing are reconstructed into cross-sectional images showing regional ventilation distribution. EIT is radiation-free, portable, and provides continuous monitoring. Clinical applications include optimizing mechanical ventilation settings, detecting pneumothorax, and assessing regional response to bronchodilators.',
        difficulty: 3,
        topic: 'Emerging Technologies',
        isFree: false,
        orderIndex: 342,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are structured light plethysmography (SLP) and optoelectronic plethysmography (OEP) and what advantages do they offer?',
        answer: 'Both are contactless methods for measuring chest wall motion and deriving ventilatory parameters. SLP projects a light grid onto the torso and uses cameras to track surface movement. OEP uses reflective markers and infrared cameras. Advantages include: no mouthpiece or noseclip needed, applicable to uncooperative patients and infants, measurement of chest wall compartmental motion (rib cage vs. abdomen), and ability to detect asynchronous breathing patterns.',
        difficulty: 3,
        topic: 'Emerging Technologies',
        isFree: false,
        orderIndex: 343,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the principle behind xenon-enhanced CT ventilation imaging and how does it complement PFTs?',
        answer: 'Xenon-enhanced CT uses inhaled stable xenon gas (non-radioactive) as a CT contrast agent. Because xenon is radiodense, regions receiving ventilation show increased CT attenuation. This provides high-resolution spatial mapping of ventilation distribution that complements global PFT measurements. Applications include identifying ventilation defects not apparent on spirometry, guiding bronchoscopic interventions, and assessing regional treatment response.',
        difficulty: 3,
        topic: 'Emerging Technologies',
        isFree: false,
        orderIndex: 344,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How might artificial intelligence and machine learning improve PFT interpretation in the future?',
        answer: 'AI applications include: (1) automated quality grading of spirometry maneuvers with accuracy approaching expert technologists, (2) pattern recognition for complex mixed disorders that challenge algorithmic approaches, (3) predictive modeling for disease progression using longitudinal data, (4) integration of PFTs with imaging, biomarkers, and clinical data for more precise phenotyping, and (5) real-time coaching of patients during testing to optimize effort quality.',
        difficulty: 1,
        topic: 'Emerging Technologies',
        isFree: false,
        orderIndex: 345,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the role of volatile organic compound (VOC) analysis in exhaled breath (breathomics) as an emerging pulmonary diagnostic tool?',
        answer: 'Exhaled breath contains hundreds of VOCs produced by metabolic processes, inflammation, and oxidative stress. Electronic nose devices and mass spectrometry can identify VOC patterns (breathprints) associated with specific diseases including lung cancer, asthma, COPD, and infections. While promising for noninvasive disease screening and phenotyping, standardization of collection methods, analytical platforms, and validation in large cohorts remain ongoing challenges.',
        difficulty: 2,
        topic: 'Emerging Technologies',
        isFree: false,
        orderIndex: 346,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is hyperpolarized gas MRI and how does it provide functional lung imaging?',
        answer: 'Hyperpolarized gas MRI uses noble gases (helium-3 or xenon-129) whose nuclear spin polarization has been massively enhanced through optical pumping. When inhaled, these gases produce strong MRI signals that map ventilation distribution with high spatial resolution and no ionizing radiation. Xenon-129 is also soluble in tissue and blood, allowing measurement of gas exchange at the alveolar-capillary membrane. This technology can detect ventilation defects invisible to conventional PFTs.',
        difficulty: 3,
        topic: 'Emerging Technologies',
        isFree: false,
        orderIndex: 347,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Complex Mixed Patterns and Atypical Presentations (cards 348-355) ---
      {
        question: 'How do you identify a mixed obstructive-restrictive pattern and what are the diagnostic criteria?',
        answer: 'A mixed pattern requires: (1) FEV1/FVC below LLN confirming obstruction, AND (2) TLC below LLN confirming coexisting restriction. FVC alone is insufficient to diagnose restriction in the presence of obstruction because air trapping can reduce FVC without true volume loss. Common clinical scenarios include COPD with obesity, asthma with concurrent ILD, and sarcoidosis with airway involvement.',
        difficulty: 1,
        topic: 'Complex Mixed Patterns',
        isFree: false,
        orderIndex: 348,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the nonspecific ventilatory pattern and what is its clinical significance?',
        answer: 'The nonspecific pattern shows reduced FEV1 and FVC with a normal FEV1/FVC ratio and normal TLC. It does not fit classic obstruction or restriction. Causes include obesity, submaximal effort, early airway disease with air trapping (where RV may be elevated but TLC is preserved), chest wall abnormalities, and neuromuscular weakness. It is found in approximately 10-15% of PFT referrals and warrants clinical correlation rather than automatic reclassification.',
        difficulty: 2,
        topic: 'Complex Mixed Patterns',
        isFree: false,
        orderIndex: 349,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A patient has a normal FEV1/FVC ratio, normal TLC, but DLCO is severely reduced (40% predicted). What conditions should be considered?',
        answer: 'Isolated severe DLCO reduction with normal spirometry and lung volumes suggests: (1) pulmonary vascular disease (pulmonary hypertension, chronic thromboembolic disease), (2) early emphysema not yet affecting spirometry, (3) anemia (which should be corrected by hemoglobin adjustment), (4) pulmonary hemorrhage recovery phase, or (5) early ILD. Pulmonary vascular disease is the most concerning diagnosis in this pattern and warrants echocardiography and possibly right heart catheterization.',
        difficulty: 2,
        topic: 'Complex Mixed Patterns',
        isFree: false,
        orderIndex: 350,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How can combined pulmonary fibrosis and emphysema (CPFE) syndrome produce deceptively normal spirometry?',
        answer: 'In CPFE, upper-lobe emphysema causes hyperinflation and increased compliance while lower-lobe fibrosis causes volume loss and decreased compliance. These opposing effects on lung volumes can cancel out, producing near-normal FVC and TLC. FEV1/FVC may also be preserved. However, DLCO is severely reduced because both diseases impair gas exchange. The key diagnostic clue is a marked DLCO reduction disproportionate to the mild spirometric abnormalities, combined with characteristic CT findings.',
        difficulty: 3,
        topic: 'Complex Mixed Patterns',
        isFree: false,
        orderIndex: 351,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT pattern is characteristic of obesity hypoventilation syndrome and how does it differ from simple obesity?',
        answer: 'Both show reduced ERV, but obesity hypoventilation syndrome (OHS) additionally shows: (1) elevated PaCO2 (>45 mmHg by definition), (2) more significantly reduced ERV, (3) possible mild restriction with reduced TLC in severe cases, (4) reduced MIP/MEP from respiratory muscle loading, and (5) blunted ventilatory response to CO2. Simple obesity typically preserves PaCO2 and has less severe ERV reduction. DLCO may be normal or slightly reduced in both.',
        difficulty: 2,
        topic: 'Complex Mixed Patterns',
        isFree: false,
        orderIndex: 352,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A patient shows a plateau on the inspiratory limb of the flow-volume loop with a normal expiratory limb. What does this indicate?',
        answer: 'An isolated inspiratory plateau (flattening) with a normal expiratory limb indicates variable extrathoracic upper airway obstruction. During inspiration, negative intraluminal pressure causes a compliant extrathoracic lesion (such as vocal cord paralysis, tracheomalacia above the thoracic inlet, or a goiter) to narrow. During expiration, positive intraluminal pressure splints the lesion open, preserving normal expiratory flow.',
        difficulty: 1,
        topic: 'Complex Mixed Patterns',
        isFree: false,
        orderIndex: 353,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What atypical spirometric findings may be seen in left heart failure and how do they relate to the pathophysiology?',
        answer: 'Left heart failure can produce: (1) mild obstruction from bronchial wall edema and peribronchial cuffing, (2) restriction from pulmonary edema and pleural effusions, (3) reduced DLCO from interstitial edema (or paradoxically increased DLCO from capillary engorgement in early stages), (4) reduced ERV from increased pulmonary blood volume, and (5) bronchial hyperresponsiveness ("cardiac asthma"). These findings may improve with diuresis, and serial PFTs can show volume-status-dependent variability.',
        difficulty: 3,
        topic: 'Complex Mixed Patterns',
        isFree: false,
        orderIndex: 354,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does the PFT pattern in lymphangioleiomyomatosis (LAM) differ from typical ILD patterns?',
        answer: 'Unlike most ILDs that show restriction, LAM typically shows obstruction (reduced FEV1/FVC) with air trapping (elevated RV/TLC), hyperinflation, and severely reduced DLCO. This is because LAM causes cystic destruction and airway smooth muscle proliferation leading to expiratory airflow limitation. The pattern resembles emphysema rather than typical ILD. FVC may be reduced from air trapping rather than true restriction. This atypical obstructive-ILD pattern is shared with pulmonary Langerhans cell histiocytosis.',
        difficulty: 3,
        topic: 'Complex Mixed Patterns',
        isFree: false,
        orderIndex: 355,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Pharmacologic Challenge Testing Beyond Methacholine (cards 356-363) ---
      {
        question: 'What are the indications for mannitol bronchial provocation testing and how does it differ from methacholine challenge?',
        answer: 'Mannitol is an indirect bronchial provocation agent that causes airway narrowing by drawing water from the airway surface, triggering mast cell mediator release. Unlike methacholine (a direct smooth muscle agonist), mannitol is more specific for active airway inflammation and better predicts response to inhaled corticosteroids. It is delivered as a dry powder inhaler in escalating doses. A positive test is a 15% fall in FEV1, with a PD15 calculated. It has fewer false positives than methacholine in non-asthmatic conditions.',
        difficulty: 2,
        topic: 'Pharmacologic Challenge Testing',
        isFree: false,
        orderIndex: 356,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is eucapnic voluntary hyperpnea (EVH) testing performed and what condition is it primarily used to diagnose?',
        answer: 'EVH is the gold standard for diagnosing exercise-induced bronchoconstriction (EIB), particularly in elite athletes. The patient hyperventilates dry air containing 5% CO2 (to prevent hypocapnic bronchoconstriction) at 85% of MVV for 6 minutes. FEV1 is measured serially for 20 minutes post-challenge. A fall in FEV1 of 10% or more is considered positive. EVH has higher sensitivity and specificity for EIB than exercise testing because it provides a more potent osmotic stimulus to the airways.',
        difficulty: 3,
        topic: 'Pharmacologic Challenge Testing',
        isFree: false,
        orderIndex: 357,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the role of adenosine monophosphate (AMP) challenge testing in asthma evaluation?',
        answer: 'AMP is an indirect bronchial provocation agent that activates mast cells through adenosine receptors, causing release of histamine and leukotrienes. AMP responsiveness is more closely linked to airway inflammation than methacholine and decreases more rapidly with inhaled corticosteroid treatment. It can be used to monitor anti-inflammatory treatment response and to differentiate inflammatory from structural airway hyperresponsiveness. It is less commonly available than methacholine or mannitol.',
        difficulty: 3,
        topic: 'Pharmacologic Challenge Testing',
        isFree: false,
        orderIndex: 358,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What medications must be withheld before bronchial provocation testing and for how long?',
        answer: 'Key withholding times: short-acting beta-agonists (8 hours), long-acting beta-agonists (48 hours), ultra-long-acting beta-agonists like indacaterol (72 hours), short-acting anticholinergics (24 hours), long-acting anticholinergics (7 days), theophylline (24-48 hours), leukotriene modifiers (24 hours), antihistamines (72 hours for most, 7 days for hydroxyzine/cetirizine), and caffeine (day of test). Inhaled corticosteroids are generally continued but noted in the report.',
        difficulty: 1,
        topic: 'Pharmacologic Challenge Testing',
        isFree: false,
        orderIndex: 359,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What safety equipment and protocols must be in place before performing any bronchial provocation test?',
        answer: 'Required elements include: (1) emergency medications readily available (short-acting bronchodilator, epinephrine, injectable corticosteroids), (2) supplemental oxygen and delivery devices, (3) pulse oximetry monitoring throughout, (4) trained personnel capable of managing severe bronchospasm, (5) physician available on-site or by immediate contact, (6) established stopping criteria (typically FEV1 fall >20% for methacholine), (7) minimum baseline FEV1 requirements (usually >60-70% predicted or >1.0-1.5 L), and (8) informed consent documenting risks.',
        difficulty: 1,
        topic: 'Pharmacologic Challenge Testing',
        isFree: false,
        orderIndex: 360,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does hypertonic saline (4.5%) bronchial provocation differ from other indirect challenge agents?',
        answer: 'Hypertonic saline challenge uses nebulized 4.5% saline in escalating exposure durations. Like mannitol and EVH, it is an indirect stimulus that acts through osmotic water loss from the airway surface, triggering mediator release from mast cells. It has the additional advantage of inducing sputum that can be collected for inflammatory cell analysis (combined provocation and sputum induction). A 15% fall in FEV1 defines a positive response.',
        difficulty: 2,
        topic: 'Pharmacologic Challenge Testing',
        isFree: false,
        orderIndex: 361,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is a specific inhalation challenge (SIC) and when is it performed?',
        answer: 'SIC is the gold standard for confirming occupational asthma. The patient is exposed to the suspected workplace agent under controlled conditions in a challenge chamber. FEV1 is monitored for early (within 1 hour), late (4-8 hours), and dual (both) responses. SIC requires specialized facilities, expert supervision, and prolonged monitoring (typically 24 hours). It is indicated when noninvasive testing is inconclusive and the diagnosis has significant employment and medicolegal implications.',
        difficulty: 2,
        topic: 'Pharmacologic Challenge Testing',
        isFree: false,
        orderIndex: 362,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How do you interpret a methacholine dose-response curve that shows a plateau in FEV1 decline?',
        answer: 'A plateau (maximal response plateau) indicates that FEV1 stops declining despite increasing methacholine doses, suggesting a ceiling to airway narrowing. This plateau is protective and is typically present in non-asthmatic hyperresponsive individuals and those with mild asthma. Absence of a plateau (continued progressive decline) is associated with more severe asthma and greater risk of serious bronchospasm. The maximal response plateau adds clinical information beyond the PC20 alone.',
        difficulty: 3,
        topic: 'Pharmacologic Challenge Testing',
        isFree: false,
        orderIndex: 363,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Advanced Gas Exchange Physiology / MIGET (cards 364-372) ---
      {
        question: 'What is the multiple inert gas elimination technique (MIGET) and what physiologic information does it provide?',
        answer: 'MIGET quantifies the distribution of ventilation-perfusion (V/Q) ratios throughout the lung. Six inert gases with different solubilities are infused intravenously, and their concentrations are measured in expired gas and arterial blood. Mathematical analysis yields a continuous distribution of V/Q ratios, quantifying the contributions of shunt (V/Q=0), low V/Q regions, normal V/Q matching, high V/Q regions (dead space), and diffusion limitation to gas exchange impairment.',
        difficulty: 3,
        topic: 'Advanced Gas Exchange / MIGET',
        isFree: false,
        orderIndex: 364,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'Why are six inert gases with different solubilities used in MIGET rather than a single gas?',
        answer: 'Each gas acts as a probe for a specific range of V/Q ratios based on its blood-gas partition coefficient. Low-solubility gases (SF6) are retained only in very low V/Q units, while high-solubility gases (acetone) are excreted even from high V/Q units. Using six gases spanning a wide solubility range (SF6, ethane, cyclopropane, halothane, diethyl ether, acetone) provides resolution across the entire V/Q spectrum from shunt through dead space.',
        difficulty: 3,
        topic: 'Advanced Gas Exchange / MIGET',
        isFree: false,
        orderIndex: 365,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does MIGET differentiate between shunt and low V/Q mismatch as causes of hypoxemia?',
        answer: 'In true shunt (V/Q=0), even high-solubility gases are fully retained in the blood because there is no ventilation to eliminate them. In low V/Q regions (V/Q between 0 and 0.1), high-solubility gases can still be partially eliminated. MIGET exploits this difference: the retention pattern of low-solubility gases identifies true shunt, while the retention-excretion pattern of moderate-solubility gases maps low V/Q regions. Standard clinical tools like the shunt equation cannot make this distinction.',
        difficulty: 3,
        topic: 'Advanced Gas Exchange / MIGET',
        isFree: false,
        orderIndex: 366,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the three main mechanisms of hypoxemia and how does the alveolar-arterial oxygen difference (A-a gradient) help distinguish them?',
        answer: 'The three main mechanisms are: (1) V/Q mismatch (most common) - elevated A-a gradient, responsive to supplemental O2; (2) shunt - elevated A-a gradient, poorly responsive to supplemental O2; (3) hypoventilation - normal A-a gradient, PaCO2 is elevated, responds to supplemental O2. Diffusion impairment is a fourth mechanism but clinically relevant only during exercise or at altitude. A normal A-a gradient points to hypoventilation or low FiO2 as the sole cause.',
        difficulty: 1,
        topic: 'Advanced Gas Exchange / MIGET',
        isFree: false,
        orderIndex: 367,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is the physiologic dead space to tidal volume ratio (VD/VT) calculated using the Bohr-Enghoff equation?',
        answer: 'VD/VT = (PaCO2 - PeCO2) / PaCO2, where PaCO2 is arterial CO2 tension and PeCO2 is mixed expired CO2 tension. Normal resting VD/VT is 0.20-0.35. Values above 0.40 at rest suggest increased dead space ventilation. During exercise, VD/VT normally decreases to <0.28; failure to decrease suggests pulmonary vascular disease. Note that this modified Bohr equation uses PaCO2 (not ideal alveolar PCO2) and therefore includes both anatomic and alveolar dead space.',
        difficulty: 2,
        topic: 'Advanced Gas Exchange / MIGET',
        isFree: false,
        orderIndex: 368,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the clinical significance of an elevated alveolar-arterial oxygen difference (A-a gradient) during exercise in a patient with normal resting gas exchange?',
        answer: 'An A-a gradient that widens abnormally during exercise suggests: (1) exercise-induced V/Q mismatch (most common), (2) diffusion limitation due to shortened red cell pulmonary capillary transit time, (3) opening of intracardiac or intrapulmonary shunts under increased cardiac output, or (4) early pulmonary vascular disease. This exercise-induced gas exchange impairment often precedes resting abnormalities and is a sensitive early marker of pulmonary vascular disease or ILD.',
        difficulty: 2,
        topic: 'Advanced Gas Exchange / MIGET',
        isFree: false,
        orderIndex: 369,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does oxygen supplementation help differentiate shunt from V/Q mismatch as the predominant cause of hypoxemia?',
        answer: 'With 100% FiO2, V/Q mismatch is largely corrected because even poorly ventilated alveoli receive enough oxygen to fully saturate pulmonary capillary blood. Shunt, however, persists because shunted blood bypasses ventilated alveoli entirely. Clinically, if PaO2 fails to rise above 400-500 mmHg on 100% O2, significant shunt (typically >20%) is present. Each 5% shunt fraction reduces PaO2 on 100% O2 by approximately 20-25 mmHg from the expected value.',
        difficulty: 2,
        topic: 'Advanced Gas Exchange / MIGET',
        isFree: false,
        orderIndex: 370,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the concept of diffusion limitation during exercise and under what conditions does it become clinically significant?',
        answer: 'Diffusion limitation occurs when red blood cells transit the pulmonary capillary too quickly (due to high cardiac output) to achieve complete equilibration of oxygen across the alveolar-capillary membrane. At rest, equilibration is normally complete within one-third of capillary transit time, providing a large reserve. During maximal exercise, transit time shortens to the point where equilibration may be incomplete, especially if: (1) the diffusing surface is reduced (emphysema, ILD), (2) the membrane is thickened, or (3) the patient is at altitude where the driving pressure gradient is reduced.',
        difficulty: 2,
        topic: 'Advanced Gas Exchange / MIGET',
        isFree: false,
        orderIndex: 371,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does MIGET demonstrate that the gas exchange impairment in COPD is primarily due to V/Q mismatch rather than diffusion limitation?',
        answer: 'MIGET studies in COPD consistently show bimodal V/Q distributions with both low V/Q (poorly ventilated, well-perfused) and high V/Q (well-ventilated, poorly perfused) modes, indicating V/Q heterogeneity as the primary mechanism. True shunt fraction is typically small (<5%). Importantly, inert gas exchange does not depend on diffusion properties (unlike O2), so MIGET can separate V/Q effects from diffusion effects. In COPD, V/Q mismatch alone accounts for nearly all observed hypoxemia.',
        difficulty: 3,
        topic: 'Advanced Gas Exchange / MIGET',
        isFree: false,
        orderIndex: 372,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Board-Style Multi-System Integration Scenarios (cards 373-392, 20 cards) ---
      {
        question: 'A 58-year-old with rheumatoid arthritis presents with progressive dyspnea. PFTs show FEV1/FVC 0.68, TLC 78% predicted, DLCO 52% predicted. How do you integrate these findings?',
        answer: 'This mixed obstructive-restrictive pattern with severely reduced DLCO suggests multiple pulmonary complications of rheumatoid arthritis: (1) RA-associated ILD causing restriction and reduced DLCO, (2) obliterative bronchiolitis causing obstruction (a known RA complication), and (3) possible drug-related toxicity (methotrexate pneumonitis). The reduced DLCO out of proportion to restriction raises concern for concurrent pulmonary vascular involvement. HRCT, medication review, and rheumatology consultation are warranted.',
        difficulty: 3,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 373,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 45-year-old presents for preoperative evaluation before bariatric surgery. BMI is 52. PFTs show FVC 68%, FEV1 72%, FEV1/FVC 0.84, TLC 82%, ERV 25% predicted, DLCO 95%. What is your interpretation?',
        answer: 'This pattern is consistent with obesity-related lung function changes: (1) reduced FVC and mild restriction from diaphragm elevation and chest wall loading, (2) preserved FEV1/FVC ratio (actually supranormal, as obesity compresses airways improving the ratio), (3) dramatically reduced ERV (characteristic of obesity), (4) mildly reduced TLC, and (5) preserved DLCO (increased pulmonary blood volume in obesity can even elevate DLCO). No intrinsic lung disease is suggested. Perioperative risks relate to atelectasis and hypoventilation rather than gas exchange impairment.',
        difficulty: 2,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 374,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 30-year-old competitive cyclist has exertional dyspnea at peak effort. Resting PFTs are normal. CPET shows VO2max 58 mL/kg/min with arterial desaturation to 88% at peak exercise. What is the most likely explanation?',
        answer: 'This represents exercise-induced arterial hypoxemia (EIAH), which occurs in highly fit athletes who achieve very high cardiac outputs. The mechanism involves: (1) shortened pulmonary capillary transit time causing diffusion limitation, (2) relative mechanical ventilatory constraint limiting the hyperpneic response, and (3) possible widening of V/Q mismatch at extreme workloads. EIAH occurs in approximately 50% of elite endurance athletes at VO2max >60 mL/kg/min. It is a physiologic phenomenon in the context of exceptional fitness, not a disease state. Intracardiac shunt (PFO) should be excluded if desaturation is severe.',
        difficulty: 3,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 375,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 65-year-old former shipyard worker has FEV1/FVC 0.62, TLC 115%, RV 185%, DLCO 45%, and bilateral pleural plaques on chest radiograph. What is the most likely diagnosis and what additional findings support it?',
        answer: 'Asbestosis with concurrent COPD (likely from smoking, common in this occupational cohort). The obstructive pattern with hyperinflation suggests COPD, while the severely reduced DLCO suggests parenchymal involvement beyond emphysema alone. Pleural plaques confirm asbestos exposure. Asbestosis (interstitial fibrosis) would cause restriction, but concurrent COPD can mask the restrictive component. The severely reduced DLCO out of proportion to the obstruction severity suggests dual pathology. HRCT would help identify basal interstitial fibrosis characteristic of asbestosis.',
        difficulty: 2,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 376,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 22-year-old with sickle cell disease has FVC 75%, FEV1 72%, FEV1/FVC 0.78, TLC 80%, DLCO 55%. ABG shows pH 7.44, PaCO2 32, PaO2 74. How do you interpret this constellation?',
        answer: 'Sickle cell chronic lung disease is suggested. The restriction with reduced DLCO reflects: (1) recurrent pulmonary infarctions causing parenchymal loss, (2) chronic pulmonary vascular occlusion reducing capillary surface area, and (3) possible pulmonary hypertension (common in sickle cell). The DLCO is low but must be interpreted cautiously because chronic anemia also reduces DLCO; correcting for hemoglobin may show a less severe reduction. The mild hypoxemia with hypocapnia suggests compensatory hyperventilation. Echocardiography to assess pulmonary pressures is essential.',
        difficulty: 3,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 377,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 50-year-old woman with progressive dyspnea has FVC 82%, FEV1 80%, FEV1/FVC 0.79, TLC 88%, DLCO 38%, MIP -85 cmH2O, MEP +90 cmH2O. What diagnosis should be strongly considered?',
        answer: 'The severely and disproportionately reduced DLCO with near-normal spirometry and lung volumes, combined with normal respiratory muscle strength, strongly suggests pulmonary vascular disease. Primary pulmonary arterial hypertension or chronic thromboembolic pulmonary hypertension should be evaluated. The DLCO reduction reflects loss of pulmonary capillary blood volume. Normal MIP/MEP exclude neuromuscular disease. Urgent echocardiography and possible right heart catheterization are indicated. CT pulmonary angiography should be considered to evaluate for chronic thromboembolic disease.',
        difficulty: 2,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 378,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 70-year-old with COPD (FEV1 35% predicted) is being evaluated for lung volume reduction surgery. What PFT criteria must be met and what findings would exclude candidacy?',
        answer: 'NETT trial criteria for LVRS candidacy include: FEV1 20-45% predicted, TLC >100% predicted (hyperinflation), RV >150% predicted (air trapping), and predominantly upper-lobe emphysema on CT with low exercise capacity. Exclusion criteria include: FEV1 <20% predicted combined with either DLCO <20% predicted or homogeneous emphysema (these patients had excessive surgical mortality in NETT). Adequate rehabilitation participation and absence of significant comorbidities are also required.',
        difficulty: 2,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 379,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A patient undergoing chemotherapy with bleomycin has DLCO declining from 95% to 65% predicted over 3 months with stable spirometry. What is the significance and what action is required?',
        answer: 'This represents bleomycin pulmonary toxicity until proven otherwise. DLCO is the most sensitive early marker of bleomycin-induced lung injury, often declining before symptoms or radiographic changes. A decline of >15-20% from baseline, or DLCO falling below 60% predicted, typically triggers drug discontinuation or dose modification. Serial DLCO monitoring (every 1-2 cycles) is standard practice during bleomycin therapy. CT may show ground-glass opacities. Continued bleomycin exposure risks irreversible pulmonary fibrosis.',
        difficulty: 1,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 380,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 35-year-old with myasthenia gravis has FVC 2.8L sitting and 1.9L supine, MIP -35 cmH2O, MVV 45 L/min (predicted 120 L/min). FEV1 is 2.5L and FEV1 x 35 = 87.5 L/min. What do these findings indicate?',
        answer: 'These findings indicate significant respiratory muscle weakness with diaphragmatic involvement: (1) >30% supine FVC drop confirms bilateral diaphragmatic weakness (normal drop is <10%), (2) MIP of -35 indicates severe inspiratory muscle weakness (normal >-80 cmH2O), (3) MVV is disproportionately reduced relative to FEV1 (measured MVV is only 51% of estimated MVV from FEV1 x 35), indicating neuromuscular limitation rather than airway obstruction. This pattern warrants ICU awareness for potential myasthenic crisis and consideration of plasma exchange or IVIg.',
        difficulty: 2,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 381,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 55-year-old post-pneumonectomy patient has FEV1 1.8L (55% predicted for two lungs). How do you assess whether this represents normal post-surgical function or additional disease?',
        answer: 'After pneumonectomy, the expected residual lung function depends on the preoperative contribution of each lung (assessed by quantitative perfusion scan). Typically, the remaining lung provides 55-60% of preoperative function, with some compensatory growth. To assess adequacy: (1) compare to predicted postoperative values calculated from preoperative PFTs and perfusion data, (2) account for compensatory hyperinflation (expected and beneficial), (3) monitor DLCO which should be proportionally reduced. If measured values are significantly below predicted postoperative values, investigate for infection, recurrence, radiation fibrosis, or contralateral disease.',
        difficulty: 2,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 382,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 40-year-old with HIV and CD4 count of 180 has FVC 90%, FEV1 65%, FEV1/FVC 0.58, TLC 110%, RV 165%, DLCO 50%. What diagnoses should be considered?',
        answer: 'This obstructive pattern with air trapping and reduced DLCO in an HIV-positive patient with low CD4 suggests: (1) HIV-associated emphysema (accelerated emphysema in HIV, even without smoking, possibly from chronic inflammation and protease imbalance), (2) lymphocytic interstitial pneumonitis causing airways disease, (3) prior opportunistic infections (PCP causes residual cystic disease), and (4) COPD from smoking if applicable. HIV-associated pulmonary arterial hypertension could contribute to the reduced DLCO. HRCT would help differentiate emphysema from cystic disease. Antiretroviral therapy may stabilize but rarely reverses lung damage.',
        difficulty: 3,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 383,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 28-year-old presents with unexplained dyspnea. Spirometry is normal. DLCO is 125% predicted. What conditions can cause an elevated DLCO?',
        answer: 'Elevated DLCO occurs with: (1) polycythemia (increased hemoglobin binds more CO), (2) pulmonary hemorrhage (free hemoglobin in alveoli absorbs CO - seen in Goodpasture syndrome and other alveolar hemorrhage syndromes), (3) left-to-right intracardiac shunt increasing pulmonary blood volume, (4) obesity (increased cardiac output and pulmonary blood volume), (5) asthma (increased pulmonary capillary blood volume from negative intrathoracic pressure), and (6) exercise immediately before testing. In a young patient with unexplained dyspnea and elevated DLCO, pulmonary hemorrhage and intracardiac shunt are important to exclude.',
        difficulty: 1,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 384,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A patient with amyotrophic lateral sclerosis (ALS) has FVC 52% predicted. Sniff nasal inspiratory pressure (SNIP) is 28 cmH2O. What is the prognostic significance and clinical implication?',
        answer: 'Both values indicate advanced respiratory muscle weakness and predict poor prognosis. FVC <50% predicted in ALS is an indication for noninvasive ventilation (NIV) initiation. SNIP <40 cmH2O independently predicts 6-month mortality. SNIP may be more sensitive than FVC for detecting diaphragmatic weakness in ALS because it is less affected by bulbar weakness that can impair mouthpiece seal. Together, these values support urgent initiation of NIV, discussion of advanced directives, and consideration of diaphragm pacing or tracheostomy if consistent with patient goals.',
        difficulty: 2,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 385,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'An 8-year-old with cystic fibrosis has LCI of 12.5 (upper limit of normal 7.0) but FEV1 of 98% predicted. What does this discordance indicate?',
        answer: 'This demonstrates the superior sensitivity of LCI (lung clearance index from multiple-breath washout) over FEV1 for detecting early CF lung disease. The elevated LCI indicates significant ventilation inhomogeneity from mucus plugging and early structural airway disease that has not yet progressed enough to affect FEV1. LCI can detect CF lung disease 2-3 years before FEV1 declines. This finding may support earlier treatment intensification and is increasingly used as an outcome measure in CF clinical trials to detect treatment effects at earlier disease stages.',
        difficulty: 2,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 386,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 62-year-old with known COPD (FEV1 45%) develops new bilateral upper lobe fibrotic changes on CT. DLCO drops from 60% to 30% while FVC increases from 65% to 78%. How do you reconcile these changes?',
        answer: 'This is consistent with combined pulmonary fibrosis and emphysema (CPFE). The paradoxical FVC improvement occurs because new upper lobe fibrosis (traction) may recruit previously trapped gas, and the opposing elastic recoil effects of fibrosis and emphysema partially normalize volumes. The dramatic DLCO decline reflects additive gas exchange impairment from both diseases. The improving spirometry could mislead clinicians into thinking the patient is improving when gas exchange is actually worsening severely. This highlights why DLCO monitoring is essential and should not be omitted when following patients with COPD or suspected CPFE.',
        difficulty: 3,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 387,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 48-year-old liver transplant candidate has massive ascites. PFTs show FVC 55%, TLC 68%, with hepatopulmonary syndrome confirmed. What PFT considerations are important for transplant evaluation?',
        answer: 'Key considerations: (1) restriction from ascites is partially reversible with paracentesis - repeat PFTs post-drainage to assess intrinsic lung function, (2) hepatopulmonary syndrome causes intrapulmonary vascular dilatation and right-to-left shunting, reducing PaO2 and DLCO, (3) DLCO reduction in hepatopulmonary syndrome reflects shunt physiology rather than membrane disease, (4) portopulmonary hypertension should be excluded as it independently affects transplant candidacy and requires specific hemodynamic criteria, and (5) severe hypoxemia (PaO2 <60 mmHg) or mean pulmonary artery pressure >35 mmHg may contraindicate transplantation.',
        difficulty: 3,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 388,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 55-year-old with progressive systemic sclerosis has FVC 65%, DLCO 35%, and estimated right ventricular systolic pressure of 55 mmHg on echocardiography. How do you assess the relative contributions of ILD and pulmonary hypertension?',
        answer: 'The FVC/DLCO ratio is a useful tool: (1) if DLCO reduction is proportional to FVC reduction (similar percent predicted), ILD alone likely explains both, (2) if DLCO is disproportionately reduced relative to FVC (as here: FVC 65% but DLCO 35%), concurrent pulmonary vascular disease is likely contributing. A FVC%/DLCO% ratio >1.6-2.0 strongly suggests pulmonary hypertension beyond what ILD alone would cause. Right heart catheterization is needed to confirm pulmonary arterial hypertension and guide specific vasodilator therapy. The echocardiographic findings support this clinical concern.',
        difficulty: 3,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 389,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 60-year-old presents with dyspnea. Spirometry shows FEV1/FVC 0.72 (LLN 0.70), FEV1 82% predicted. Bronchodilator response: FEV1 increases 250 mL and 14%. How should this borderline case be interpreted?',
        answer: 'This is a borderline obstructive pattern requiring careful interpretation: (1) FEV1/FVC is just above LLN, making obstruction uncertain by z-score criteria, (2) however, the significant bronchodilator response (meeting the ATS/ERS 2021 criterion of >10% predicted, which 14% exceeds) suggests reversible airway disease, (3) a positive bronchodilator response in the setting of borderline obstruction increases diagnostic confidence for asthma or early COPD, (4) clinical context (smoking history, symptoms, atopy) must guide the final interpretation. This case illustrates why bronchodilator testing adds value at borderline ratios.',
        difficulty: 1,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 390,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A patient with kyphoscoliosis has FVC 45%, FEV1 42%, FEV1/FVC 0.80, TLC 55%, DLCO 48%, KCO (DLCO/VA) 115%. ABG: pH 7.36, PaCO2 52, PaO2 62. What is the integrated interpretation?',
        answer: 'This demonstrates extrapulmonary restriction from chest wall deformity: (1) restriction confirmed by reduced TLC, (2) the elevated KCO (DLCO/VA) is characteristic of extrapulmonary restriction where the alveolar-capillary membrane is intrinsically normal but DLCO is low simply because lung volume is reduced, (3) the ABG shows chronic hypercapnic respiratory failure (compensated respiratory acidosis) from the combination of reduced lung volume and chest wall mechanical disadvantage, (4) hypoxemia results from both hypoventilation and V/Q mismatch from atelectasis. Treatment focuses on nocturnal noninvasive ventilation rather than lung-directed therapy.',
        difficulty: 2,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 391,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A 38-year-old woman with lymphangioleiomyomatosis has FEV1/FVC 0.60, TLC 115%, RV 190%, DLCO 40%, and recent pneumothorax. She is being evaluated for lung transplant. What PFT trajectory and thresholds guide transplant listing?',
        answer: 'LAM transplant referral indicators include: (1) FEV1 <40% predicted or rapidly declining (>200 mL/year), (2) severe gas exchange impairment (DLCO <40%, resting hypoxemia), (3) exercise intolerance with VO2max <50% predicted, (4) recurrent pneumothorax requiring pleurodesis (complicates future transplant surgery), and (5) NYHA class III-IV symptoms despite medical therapy (including sirolimus). This patients already-reduced DLCO of 40%, severe air trapping, and pneumothorax history suggest transplant evaluation is appropriate. Rate of FEV1 decline helps determine urgency of listing.',
        difficulty: 3,
        topic: 'Board-Style Integration Scenarios',
        isFree: false,
        orderIndex: 392,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Error Analysis and Artifact Recognition (cards 393-400) ---
      {
        question: 'What are the most common artifacts in flow-volume loop recordings and how does each affect the measured values?',
        answer: 'Common artifacts include: (1) cough (sharp spikes on expiratory curve - can falsely elevate PEF or reduce FEV1), (2) glottic closure (abrupt termination of flow - reduces FVC and FEV6), (3) hesitant start (large back-extrapolated volume - invalidates FEV1 timing), (4) submaximal effort (reduced peak flow with scooped contour mimicking obstruction), (5) air leak around mouthpiece (variable flow interruptions), (6) tongue obstruction (irregular flow pattern), and (7) early termination (failure to reach plateau - underestimates FVC).',
        difficulty: 1,
        topic: 'Error Analysis and Artifact Recognition',
        isFree: false,
        orderIndex: 393,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How do you recognize and troubleshoot a leak in a body plethysmograph during FRC measurement?',
        answer: 'Signs of a plethysmograph leak include: (1) inability to achieve a stable baseline box pressure, (2) drift in the pressure-volume loops during panting, (3) erroneously large FRC/TGV values because box pressure changes are attenuated, (4) open loops on the Boyle law plot instead of closed loops. Troubleshooting steps: verify door seal integrity, check all tubing connections, ensure shutter valve is sealing completely, inspect the pneumotachograph gaskets, and test with the box sealed and empty to confirm leak-free operation before patient testing.',
        difficulty: 2,
        topic: 'Error Analysis and Artifact Recognition',
        isFree: false,
        orderIndex: 394,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'During DLCO testing, what errors can occur with the Valsalva or Mueller maneuver and how do they affect results?',
        answer: 'Valsalva maneuver (straining against closed glottis) during breath-hold reduces pulmonary capillary blood volume by increasing intrathoracic pressure, leading to falsely low DLCO. Mueller maneuver (inspiratory effort against closed glottis) increases pulmonary capillary blood volume, leading to falsely high DLCO. The technologist should monitor mouth pressure during breath-hold; pressure should remain near atmospheric. Deviations exceeding 10 cmH2O sustained for more than a brief period can significantly affect DLCO accuracy.',
        difficulty: 2,
        topic: 'Error Analysis and Artifact Recognition',
        isFree: false,
        orderIndex: 395,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What effect does an inadequate inspired volume have on single-breath DLCO measurement and how is this quality issue identified?',
        answer: 'An inspired volume (VI) less than 85% of the largest known VC results in: (1) incomplete gas distribution to all lung regions, biasing the measurement toward better-ventilated areas, (2) potentially falsely elevated KCO because well-ventilated regions have higher gas transfer per unit volume, (3) reduced alveolar volume (VA) underestimating lung size, and (4) variable effects on DLCO depending on disease pattern. ATS/ERS 2017 standards require VI >85% of largest VC for an acceptable maneuver. Repeated submaximal inspirations should prompt technique coaching.',
        difficulty: 2,
        topic: 'Error Analysis and Artifact Recognition',
        isFree: false,
        orderIndex: 396,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does carboxyhemoglobin (COHb) affect DLCO measurement and what correction is applied?',
        answer: 'Elevated COHb reduces measured DLCO through two mechanisms: (1) CO back-pressure effect - CO already bound to hemoglobin reduces the driving pressure gradient for additional CO uptake, and (2) reduced available hemoglobin for CO binding. Each 1% increase in COHb reduces DLCO by approximately 1%. Corrections are applied: adjusted DLCO = measured DLCO x [1 + (COHb% / 100)]. Smokers should abstain for at least 4 hours before testing. COHb can be estimated from the washout volume CO concentration in some DLCO systems.',
        difficulty: 1,
        topic: 'Error Analysis and Artifact Recognition',
        isFree: false,
        orderIndex: 397,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What errors can occur during plethysmographic airway resistance (Raw) measurement and how are they detected?',
        answer: 'Common errors include: (1) panting too fast (>1-2 Hz) causing frequency-dependent effects and upper airway artifact, (2) panting too slowly allowing thermal drift, (3) cheek vibration causing artifactual flow oscillations (patients should support cheeks with hands), (4) glottic closure during panting creating spikes in the flow-pressure loops, (5) leaks around the mouthpiece, and (6) thermal equilibration artifact if the patient has not been in the box long enough. These are detected by examining the shape and reproducibility of the flow-box pressure loops, which should be linear and repeatable.',
        difficulty: 2,
        topic: 'Error Analysis and Artifact Recognition',
        isFree: false,
        orderIndex: 398,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the "learning effect" in serial PFT testing and how should it be accounted for in longitudinal monitoring?',
        answer: 'The learning effect refers to improved performance on initial serial tests as patients become familiar with the maneuvers. FEV1 and FVC may improve 50-100 mL or more between the first and second testing sessions in previously naive subjects. This can be mistaken for true improvement or can mask decline. To minimize this artifact: (1) establish baseline only after the patient has demonstrated consistent technique across at least two sessions, (2) use the personal best from initial sessions as the reference, (3) ensure standardized coaching protocols, and (4) interpret early trends cautiously until stable technique is confirmed.',
        difficulty: 1,
        topic: 'Error Analysis and Artifact Recognition',
        isFree: false,
        orderIndex: 399,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'During methacholine challenge testing, what technical errors can produce false-negative or false-positive results?',
        answer: 'False-negative errors: (1) inadequate nebulizer output (low dose delivery), (2) patient using a noseclip but mouth-breathing too shallowly, (3) failure to withhold bronchodilators or caffeine, (4) expired methacholine solution with reduced potency, (5) excessive time between doses allowing recovery. False-positive errors: (1) deep inspiration-induced bronchodilation masking hyperresponsiveness (perform spirometry without preceding deep breaths if suspected), (2) submaximal inspiratory effort on post-challenge spirometry falsely lowering FEV1, (3) cough-induced artifact mimicking FEV1 decline, and (4) upper airway obstruction (vocal cord dysfunction) mimicking a positive response. Reviewing flow-volume loop morphology at each dose helps distinguish true from artifactual responses.',
        difficulty: 3,
        topic: 'Error Analysis and Artifact Recognition',
        isFree: false,
        orderIndex: 400,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
    ],
    skipDuplicates: true,
  })

  console.log('Successfully seeded 100 RPFT flashcards (batch 4).')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
