import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding CPFT flashcards batch 3 (cards 201-300)...')

  await prisma.flashcard.createMany({
    data: [
      // --- Advanced Spirometry Interpretation and Quality Grading (10 cards) ---
      {
        question: 'According to ATS/ERS 2019 standards, what is the maximum acceptable back-extrapolated volume (BEV) for a valid FVC maneuver?',
        answer: 'The BEV must be less than 5% of the FVC or 100 mL, whichever is greater. Excessive BEV indicates a hesitant or slow start to the forced expiratory maneuver.',
        difficulty: 2,
        topic: 'Advanced Spirometry Interpretation',
        isFree: false,
        orderIndex: 201,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What are the ATS/ERS criteria for an acceptable end-of-test (EOT) for spirometry?',
        answer: 'The patient must either reach a plateau in the volume-time curve (no change in volume of less than 25 mL for at least 1 second), or achieve an expiratory time of at least 15 seconds, or the patient cannot or should not continue further exhalation.',
        difficulty: 2,
        topic: 'Advanced Spirometry Interpretation',
        isFree: false,
        orderIndex: 202,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How is the ATS/ERS repeatability criterion for FEV1 and FVC defined in the 2019 standards?',
        answer: 'The two largest values of FEV1 and FVC from acceptable maneuvers must be within 150 mL of each other. In patients with FVC less than 1.0 L, the repeatability threshold is 100 mL.',
        difficulty: 2,
        topic: 'Advanced Spirometry Interpretation',
        isFree: false,
        orderIndex: 203,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What does a quality grade of "A" indicate on a spirometry report using the ATS/ERS grading system?',
        answer: 'Grade A indicates that three or more acceptable maneuvers were obtained and the repeatability criteria were met (the two best FEV1 and FVC values are within 150 mL). This is the highest quality grade.',
        difficulty: 1,
        topic: 'Advanced Spirometry Interpretation',
        isFree: false,
        orderIndex: 204,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient performs spirometry and has only two acceptable blows with FEV1 values of 2.45 L and 2.38 L. What quality grade should be assigned?',
        answer: 'Grade B. The two acceptable maneuvers meet repeatability (difference of 70 mL, which is within 150 mL), but only two acceptable blows were obtained instead of the three required for grade A.',
        difficulty: 3,
        topic: 'Advanced Spirometry Interpretation',
        isFree: false,
        orderIndex: 205,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What artifact on a spirometry volume-time curve indicates a cough during the first second of exhalation?',
        answer: 'A sudden spike or notch in the volume-time tracing during the first second, often accompanied by an abrupt change in the slope. This makes the FEV1 unreliable, and the maneuver should not be used for FEV1 determination.',
        difficulty: 2,
        topic: 'Advanced Spirometry Interpretation',
        isFree: false,
        orderIndex: 206,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'In the ATS/ERS quality grading system, what distinguishes a grade D from a grade F?',
        answer: 'Grade D indicates that usable results were obtained but they did not meet repeatability criteria. Grade F means no usable results were obtained — the maneuvers were unacceptable due to poor effort, leaks, obstruction of the mouthpiece, or other technical failures.',
        difficulty: 3,
        topic: 'Advanced Spirometry Interpretation',
        isFree: false,
        orderIndex: 207,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'When selecting the best FEV1 and FVC values from multiple acceptable spirometry maneuvers, should they come from the same maneuver?',
        answer: 'No. The best FEV1 and the best FVC are selected independently from all acceptable maneuvers, even if they come from different blows. This is because the largest values are the most representative of the patient\'s true capacity.',
        difficulty: 1,
        topic: 'Advanced Spirometry Interpretation',
        isFree: false,
        orderIndex: 208,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What does a "scalloped" or concave shape in the expiratory limb of the flow-volume loop suggest?',
        answer: 'A concave or scalloped expiratory curve suggests small airway obstruction. This pattern is characteristic of obstructive diseases such as COPD and asthma, where there is progressive airflow limitation as lung volume decreases during exhalation.',
        difficulty: 1,
        topic: 'Advanced Spirometry Interpretation',
        isFree: false,
        orderIndex: 209,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How is the FEV1/FVC ratio used to differentiate between obstructive and restrictive patterns on spirometry?',
        answer: 'A reduced FEV1/FVC ratio (below the lower limit of normal) indicates an obstructive pattern. A normal or elevated FEV1/FVC ratio with reduced FVC suggests a possible restrictive pattern, though lung volume measurements are needed for confirmation.',
        difficulty: 1,
        topic: 'Advanced Spirometry Interpretation',
        isFree: false,
        orderIndex: 210,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // --- Bronchial Challenge Testing (10 cards) ---
      {
        question: 'What is the primary indication for performing a methacholine bronchial challenge test?',
        answer: 'To evaluate suspected asthma when baseline spirometry is normal. Methacholine challenge tests for airway hyperresponsiveness, which is a hallmark of asthma. A positive result supports an asthma diagnosis in patients with compatible symptoms.',
        difficulty: 1,
        topic: 'Bronchial Challenge Testing',
        isFree: false,
        orderIndex: 211,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What defines a positive methacholine challenge test result?',
        answer: 'A 20% or greater decline in FEV1 from the post-diluent baseline value (the PC20). The provocative concentration causing this decline is reported. A PC20 of less than or equal to 4 mg/mL is considered a positive test indicating airway hyperresponsiveness.',
        difficulty: 2,
        topic: 'Bronchial Challenge Testing',
        isFree: false,
        orderIndex: 212,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the minimum baseline FEV1 (as percent predicted) generally required before proceeding with a methacholine challenge?',
        answer: 'The baseline FEV1 should be at least 60-70% of predicted (commonly 60% per ATS guidelines). Testing patients with significantly reduced baseline FEV1 increases the risk of severe bronchoconstriction and is generally contraindicated.',
        difficulty: 2,
        topic: 'Bronchial Challenge Testing',
        isFree: false,
        orderIndex: 213,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'List three absolute contraindications to methacholine bronchial challenge testing.',
        answer: 'Absolute contraindications include: (1) severe airflow obstruction with FEV1 less than 50% predicted or less than 1.0 L, (2) recent myocardial infarction or stroke within the past 3 months, and (3) known aortic or cerebral aneurysm. Uncontrolled hypertension is also an absolute contraindication.',
        difficulty: 2,
        topic: 'Bronchial Challenge Testing',
        isFree: false,
        orderIndex: 214,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does a mannitol bronchial challenge test differ from methacholine in its mechanism of bronchoconstriction?',
        answer: 'Mannitol is an indirect challenge agent that acts by changing airway surface osmolarity, causing mast cells and other inflammatory cells to release mediators (histamine, leukotrienes) that then cause bronchoconstriction. Methacholine acts directly on smooth muscle muscarinic receptors.',
        difficulty: 3,
        topic: 'Bronchial Challenge Testing',
        isFree: false,
        orderIndex: 215,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What defines a positive result for a mannitol (Aridol) bronchial challenge test?',
        answer: 'A positive mannitol challenge is defined as a 15% or greater decline in FEV1 from baseline (0 mg dose), or a 10% decline in FEV1 between consecutive doses. The provocative dose (PD15) is the cumulative dose that produces the 15% fall.',
        difficulty: 3,
        topic: 'Bronchial Challenge Testing',
        isFree: false,
        orderIndex: 216,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What withholding times should be observed for short-acting bronchodilators and inhaled corticosteroids before a methacholine challenge?',
        answer: 'Short-acting beta-agonists (e.g., albuterol) should be withheld for at least 8 hours. Short-acting anticholinergics should be withheld for 24 hours. Inhaled corticosteroids should ideally be withheld, but this decision is made by the ordering physician.',
        difficulty: 2,
        topic: 'Bronchial Challenge Testing',
        isFree: false,
        orderIndex: 217,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'During an exercise challenge test, what target heart rate should the patient achieve, and for how long?',
        answer: 'The patient should reach 80-90% of their predicted maximum heart rate (220 minus age) and maintain that level of exercise for 6-8 minutes. Achieving this workload is necessary for the test to be considered adequate for detecting exercise-induced bronchoconstriction.',
        difficulty: 2,
        topic: 'Bronchial Challenge Testing',
        isFree: false,
        orderIndex: 218,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the criterion for a positive exercise challenge test?',
        answer: 'A decline in FEV1 of 10% or greater from the pre-exercise baseline is considered a positive test for exercise-induced bronchoconstriction (EIB). FEV1 is typically measured at 5, 10, 15, 20, and 30 minutes post-exercise.',
        difficulty: 2,
        topic: 'Bronchial Challenge Testing',
        isFree: false,
        orderIndex: 219,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What reversal agent must be immediately available during any bronchial challenge test, and when is it administered?',
        answer: 'A short-acting bronchodilator (typically albuterol via nebulizer or MDI) must be immediately available. It is administered when the test endpoint is reached (positive result), when the patient experiences significant symptoms, or when FEV1 drops by 20% or more from baseline.',
        difficulty: 1,
        topic: 'Bronchial Challenge Testing',
        isFree: false,
        orderIndex: 220,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // --- Equipment Troubleshooting and Calibration (10 cards) ---
      {
        question: 'What is the acceptable range for a 3-liter calibration syringe check on a spirometer?',
        answer: 'The measured volume must be within plus or minus 3% of the known 3-liter syringe volume, meaning the acceptable range is 2.91 to 3.09 liters. This calibration check should be performed daily before patient testing.',
        difficulty: 1,
        topic: 'Equipment Troubleshooting',
        isFree: false,
        orderIndex: 221,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A flow-type spirometer consistently reads volumes lower than the 3-liter syringe. What are the most likely causes?',
        answer: 'Common causes include: a leak in the system (loose connections, cracked tubing, worn gaskets), a dirty or contaminated flow sensor (screen-type pneumotachograph), incorrect BTPS correction factor due to wrong temperature input, or an obstructed flow path.',
        difficulty: 2,
        topic: 'Equipment Troubleshooting',
        isFree: false,
        orderIndex: 222,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How is a linearity check performed on a spirometer, and how often is it required?',
        answer: 'A linearity check involves injecting the calibration syringe at three different flow rates (low, medium, and high) to verify accuracy across the range of flows. It should be performed quarterly. All volumes at each flow rate must be within plus or minus 3% of the syringe volume.',
        difficulty: 3,
        topic: 'Equipment Troubleshooting',
        isFree: false,
        orderIndex: 223,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the purpose of a biological control (bio-QC) program in a pulmonary function laboratory?',
        answer: 'A bio-QC program uses a healthy, non-smoking laboratory staff member who performs spirometry regularly (weekly or monthly) to monitor equipment performance over time. Consistent results from the biological control confirm that the equipment is functioning properly and that BTPS corrections are accurate.',
        difficulty: 2,
        topic: 'Equipment Troubleshooting',
        isFree: false,
        orderIndex: 224,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the acceptable leak rate for a body plethysmograph, and how is it tested?',
        answer: 'The leak rate should not exceed 30 mL over 10 seconds (or the manufacturer\'s specification). It is tested by pressurizing the sealed, empty box to a specified level and monitoring the pressure decay over time. Excessive leaks will cause errors in lung volume measurements.',
        difficulty: 3,
        topic: 'Equipment Troubleshooting',
        isFree: false,
        orderIndex: 225,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'When calibrating a DLCO system, what gases are used and what are the acceptable tolerances?',
        answer: 'A known test gas containing approximately 0.3% carbon monoxide (CO), a tracer gas (such as 0.3% methane, helium, or neon), 21% oxygen, and balance nitrogen is used. Gas analyzer accuracy must be within plus or minus 1% of the certified concentration for CO and the tracer gas.',
        difficulty: 3,
        topic: 'Equipment Troubleshooting',
        isFree: false,
        orderIndex: 226,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A pneumotachograph-based spirometer shows erratic flow readings. What maintenance step should be performed first?',
        answer: 'Clean the flow sensor (screen or mesh) of the pneumotachograph. Mucus, moisture, or debris on the screen changes its resistance characteristics and causes inaccurate or erratic flow measurements. Regular cleaning according to manufacturer guidelines is essential.',
        difficulty: 1,
        topic: 'Equipment Troubleshooting',
        isFree: false,
        orderIndex: 227,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What does BTPS stand for, and why is this correction applied to spirometry measurements?',
        answer: 'BTPS stands for Body Temperature (37 degrees C), ambient Pressure, Saturated with water vapor. Spirometry volumes are corrected to BTPS conditions because gas expands when warmed from room temperature to body temperature and becomes fully saturated, so BTPS values represent actual in-vivo lung volumes.',
        difficulty: 1,
        topic: 'Equipment Troubleshooting',
        isFree: false,
        orderIndex: 228,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the recommended frequency and method for verifying gas analyzer accuracy in a DLCO system?',
        answer: 'Gas analyzers should be calibrated daily using two known concentrations: a zero gas (room air or nitrogen) and a span gas of known certified concentration. The analyzer response should be linear across the measurement range, and a two-point calibration establishes this linearity.',
        difficulty: 2,
        topic: 'Equipment Troubleshooting',
        isFree: false,
        orderIndex: 229,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why must the temperature inside the spirometer or flow sensor be measured accurately?',
        answer: 'Temperature is critical for accurate BTPS correction. An incorrect temperature reading will cause systematic volume errors. For every 1 degree C error in temperature measurement, there can be approximately a 0.35% error in the BTPS-corrected volume.',
        difficulty: 3,
        topic: 'Equipment Troubleshooting',
        isFree: false,
        orderIndex: 230,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // --- Special Populations (10 cards) ---
      {
        question: 'What modifications should be made when performing spirometry on a pediatric patient aged 3 to 6 years?',
        answer: 'Use incentive software or animations to encourage maximal effort, accept shorter expiratory times (at least 1 second may be acceptable in very young children), use a smaller mouthpiece if available, allow the child to remain seated on a parent\'s lap, and use pediatric-specific reference equations.',
        difficulty: 2,
        topic: 'Special Populations',
        isFree: false,
        orderIndex: 231,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the minimum acceptable expiratory time for a valid spirometry maneuver in children under 10 years of age?',
        answer: 'Children under 10 may have acceptable maneuvers with expiratory times as short as 1 to 3 seconds, provided they demonstrate an end-of-test plateau (volume change less than 25 mL in the final second). Young children typically empty their lungs faster than adults.',
        difficulty: 2,
        topic: 'Special Populations',
        isFree: false,
        orderIndex: 232,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What special consideration must be given to geriatric patients during DLCO testing?',
        answer: 'Elderly patients may have difficulty maintaining a 10-second breath hold, may have reduced inspiratory capacity making it hard to inhale 85% of VC, and may have false teeth that can cause leaks around the mouthpiece. Additionally, their predicted values decline with age, so age-appropriate reference equations must be used.',
        difficulty: 2,
        topic: 'Special Populations',
        isFree: false,
        orderIndex: 233,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does obesity affect pulmonary function test results?',
        answer: 'Obesity primarily causes a restrictive pattern with reduced ERV and FRC due to the weight of adipose tissue on the chest wall and diaphragm. FVC and TLC may be mildly reduced. The FEV1/FVC ratio is usually normal or elevated. DLCO may be normal or slightly reduced.',
        difficulty: 2,
        topic: 'Special Populations',
        isFree: false,
        orderIndex: 234,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What unique spirometry pattern is often seen in patients with neuromuscular disease such as ALS or muscular dystrophy?',
        answer: 'A restrictive pattern with reduced FVC and preserved FEV1/FVC ratio. The flow-volume loop may show reduced peak expiratory flow with a rapid decline and oscillations. Supine and upright FVC should be compared, as a greater than 20% decline in supine FVC suggests diaphragmatic weakness.',
        difficulty: 3,
        topic: 'Special Populations',
        isFree: false,
        orderIndex: 235,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why is it important to measure both upright and supine vital capacity in patients with suspected diaphragmatic weakness?',
        answer: 'The diaphragm relies partly on gravity in the upright position to descend during inspiration. In the supine position, abdominal contents push against a weak diaphragm, reducing vital capacity. A drop of more than 20% from upright to supine VC is considered significant for diaphragmatic dysfunction.',
        difficulty: 3,
        topic: 'Special Populations',
        isFree: false,
        orderIndex: 236,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What are the key considerations when measuring height for pulmonary function testing in patients who cannot stand?',
        answer: 'Use arm span as a surrogate for height. Arm span can be measured fingertip to fingertip with arms fully extended. For patients with kyphosis, scoliosis, or limb amputations, arm span or ulna length with conversion formulas should be used to estimate standing height.',
        difficulty: 1,
        topic: 'Special Populations',
        isFree: false,
        orderIndex: 237,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'A patient with a tracheostomy needs pulmonary function testing. What adaptations are required?',
        answer: 'A tracheostomy adapter or connector must be used to create a seal between the tracheostomy tube and the spirometer circuit. The cuff on the tracheostomy tube (if present) should be inflated to prevent air leak. Nose clips are not needed since the upper airway is bypassed.',
        difficulty: 3,
        topic: 'Special Populations',
        isFree: false,
        orderIndex: 238,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What reference equations are recommended for use in multi-ethnic populations?',
        answer: 'The Global Lung Initiative (GLI) 2012 reference equations are recommended. They provide race/ethnicity-specific equations for Caucasians, African Americans, Northeast Asians, and Southeast Asians, as well as a "mixed/other" category, using a single set of continuous equations across ages 3-95.',
        difficulty: 2,
        topic: 'Special Populations',
        isFree: false,
        orderIndex: 239,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why might a spinal cord injury patient at level C3-C5 have particularly poor pulmonary function results?',
        answer: 'The phrenic nerve originates from C3-C5 spinal segments. Injuries at these levels can partially or fully paralyze the diaphragm, which is the primary muscle of inspiration. These patients have severely reduced VC and may be ventilator-dependent. Intercostal and abdominal muscle function is also lost.',
        difficulty: 3,
        topic: 'Special Populations',
        isFree: false,
        orderIndex: 240,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // --- Infection Control and Biosafety (10 cards) ---
      {
        question: 'What type of filter should be used on the spirometer mouthpiece to prevent cross-contamination between patients?',
        answer: 'A disposable inline bacterial/viral filter with a minimum filtration efficiency of 99.9% should be used. The filter must have minimal resistance (less than 1.5 cmH2O at 14 L/s) and minimal dead space to avoid affecting test results.',
        difficulty: 1,
        topic: 'Infection Control',
        isFree: false,
        orderIndex: 241,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How should a spirometer be disinfected between patients when inline filters are not used?',
        answer: 'All components that contact the patient\'s breath (tubing, valves, mouthpiece) should be disassembled and cleaned with enzymatic detergent, then subjected to high-level disinfection (such as glutaraldehyde, ortho-phthalaldehyde, or hydrogen peroxide). Components should be thoroughly rinsed and dried before reuse.',
        difficulty: 2,
        topic: 'Infection Control',
        isFree: false,
        orderIndex: 242,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What personal protective equipment (PPE) should a PFT technologist wear during testing of a patient with suspected active tuberculosis?',
        answer: 'At minimum, an N95 or higher-level respirator (not a surgical mask), gloves, and eye protection. Testing should be performed in a negative-pressure isolation room if possible. If the test is not urgent, it should be postponed until the patient is no longer infectious.',
        difficulty: 2,
        topic: 'Infection Control',
        isFree: false,
        orderIndex: 243,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What precautions should be taken when testing a patient known to be infected with HIV?',
        answer: 'Standard precautions should be followed, which include gloves, hand hygiene, and use of inline bacterial/viral filters on the spirometer. HIV is not transmitted by respiratory droplets, so an N95 respirator is not specifically required for HIV alone. The same infection control procedures used for all patients should be applied.',
        difficulty: 1,
        topic: 'Infection Control',
        isFree: false,
        orderIndex: 244,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How often should reusable breathing circuits and valves in a PFT laboratory be cleaned and disinfected?',
        answer: 'Reusable circuits should be cleaned and disinfected between every patient if inline filters are not used. If inline filters are used, circuits should be disinfected at least daily and whenever visible contamination occurs. Manufacturer guidelines for specific equipment should always be followed.',
        difficulty: 1,
        topic: 'Infection Control',
        isFree: false,
        orderIndex: 245,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the difference between cleaning, disinfection, and sterilization in the context of PFT equipment?',
        answer: 'Cleaning removes visible soil and organic material. Disinfection eliminates most pathogenic microorganisms but not necessarily all bacterial spores (high-level disinfection kills most spores). Sterilization destroys all forms of microbial life including spores. Most PFT equipment requires cleaning followed by high-level disinfection.',
        difficulty: 1,
        topic: 'Infection Control',
        isFree: false,
        orderIndex: 246,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Should the interior of a body plethysmograph box be decontaminated between patients? If so, how?',
        answer: 'Yes. The interior surfaces should be wiped down with an appropriate disinfectant between patients. Adequate time should be allowed for the disinfectant fumes to dissipate before the next patient enters, as chemical vapors in the sealed box could irritate airways and affect test results.',
        difficulty: 2,
        topic: 'Infection Control',
        isFree: false,
        orderIndex: 247,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the proper hand hygiene protocol for a PFT technologist between patients?',
        answer: 'Hands should be washed with soap and water or an alcohol-based hand sanitizer before and after each patient contact, after removing gloves, and after contact with any potentially contaminated surfaces or equipment. Soap and water is preferred when hands are visibly soiled.',
        difficulty: 1,
        topic: 'Infection Control',
        isFree: false,
        orderIndex: 248,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Can an inline filter affect spirometry results? If so, how?',
        answer: 'Yes. Filters add dead space volume and flow resistance to the circuit. Filters with excessive resistance (greater than 1.5 cmH2O at 14 L/s) can cause patients to fatigue early, reducing FVC. Excessive dead space can cause rebreathing. Calibration should be performed with the filter in place.',
        difficulty: 2,
        topic: 'Infection Control',
        isFree: false,
        orderIndex: 249,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What environmental controls are recommended for a PFT laboratory to minimize airborne infection transmission?',
        answer: 'Adequate room ventilation with a minimum of 6-12 air changes per hour is recommended. Air should not recirculate to other areas without HEPA filtration. Negative pressure relative to hallways is ideal for testing potentially infectious patients. UV germicidal irradiation may be used as a supplemental measure.',
        difficulty: 3,
        topic: 'Infection Control',
        isFree: false,
        orderIndex: 250,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // --- Advanced DLCO Concepts (10 cards) ---
      {
        question: 'How is DLCO adjusted for hemoglobin concentration, and why is this adjustment necessary?',
        answer: 'DLCO is corrected using formulas that account for the patient\'s measured hemoglobin relative to a standard value (14.6 g/dL for males, 13.4 g/dL for females). Anemia reduces the amount of hemoglobin available to bind CO in the alveolar capillaries, artificially lowering DLCO. The corrected value is called DLCOc or DLCO adjusted.',
        difficulty: 3,
        topic: 'Advanced DLCO',
        isFree: false,
        orderIndex: 251,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What effect does elevated carboxyhemoglobin (COHb) have on DLCO measurement, and how is it addressed?',
        answer: 'Elevated COHb reduces the pressure gradient for CO transfer by occupying hemoglobin binding sites and increasing alveolar CO back-pressure. DLCO should be corrected for COHb levels. Smokers should abstain from smoking for at least 12 hours before testing. Each 1% increase in COHb reduces DLCO by approximately 1%.',
        difficulty: 3,
        topic: 'Advanced DLCO',
        isFree: false,
        orderIndex: 252,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does altitude affect DLCO measurements, and what correction is applied?',
        answer: 'At higher altitudes, lower barometric pressure increases the alveolar PO2 relative to the reduced atmospheric pressure, affecting the CO transfer. DLCO increases at altitude due to lower PO2 enhancing CO-hemoglobin binding affinity. A correction factor based on barometric pressure or altitude is applied to normalize results to sea level conditions.',
        difficulty: 3,
        topic: 'Advanced DLCO',
        isFree: false,
        orderIndex: 253,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the difference between DLCO and DLCO/VA (KCO), and when is KCO particularly useful?',
        answer: 'DLCO is the total diffusing capacity of the lung. KCO (DLCO/VA) is the transfer coefficient, representing diffusing capacity per unit of alveolar volume. KCO is useful in distinguishing between reduced DLCO due to loss of lung units (e.g., pneumonectomy, where KCO is normal) versus reduced DLCO due to parenchymal disease (e.g., emphysema, where KCO is also reduced).',
        difficulty: 3,
        topic: 'Advanced DLCO',
        isFree: false,
        orderIndex: 254,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What are the ATS/ERS acceptability criteria for inspired volume during a DLCO test?',
        answer: 'The inspired volume (VI) should be at least 85% of the largest measured vital capacity (VC or FVC). If VI is less than 85% of VC, the test may not adequately inflate the lungs, leading to underestimation of DLCO. The maneuver should be repeated with better coaching.',
        difficulty: 2,
        topic: 'Advanced DLCO',
        isFree: false,
        orderIndex: 255,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the acceptable breath-hold time for a single-breath DLCO test, and how is it measured?',
        answer: 'The breath-hold time should be 10 plus or minus 2 seconds (8 to 12 seconds). It is measured using the Jones-Meade method, starting from approximately one-third of the way through inspiration to the beginning of sample gas collection. Breath-hold times outside this range can affect DLCO results.',
        difficulty: 2,
        topic: 'Advanced DLCO',
        isFree: false,
        orderIndex: 256,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the minimum time interval required between repeated DLCO maneuvers, and why?',
        answer: 'At least 4 minutes should elapse between DLCO maneuvers to allow washout of test gas (CO and tracer gas) from the lungs. In patients with airflow obstruction, a longer interval (up to 10 minutes) may be necessary. Residual CO from a prior breath would decrease the CO gradient and falsely lower the measured DLCO.',
        difficulty: 2,
        topic: 'Advanced DLCO',
        isFree: false,
        orderIndex: 257,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What conditions can cause an abnormally elevated DLCO?',
        answer: 'Conditions that increase pulmonary capillary blood volume can elevate DLCO, including: pulmonary hemorrhage (blood in alveoli absorbs CO), left-to-right intracardiac shunts, polycythemia (elevated hemoglobin), asthma (increased pulmonary blood volume), exercise, and the supine position.',
        difficulty: 2,
        topic: 'Advanced DLCO',
        isFree: false,
        orderIndex: 258,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How many acceptable DLCO maneuvers are needed for a valid test, and what is the repeatability criterion?',
        answer: 'At least two acceptable maneuvers are required. The two values must be within 2 mL CO/min/mmHg (or 0.67 mmol/min/kPa) of each other. If this criterion is not met, additional maneuvers should be performed up to a maximum of five attempts. The mean of acceptable, repeatable maneuvers is reported.',
        difficulty: 2,
        topic: 'Advanced DLCO',
        isFree: false,
        orderIndex: 259,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What effect does supplemental oxygen use have on DLCO measurement?',
        answer: 'Supplemental oxygen should be discontinued before DLCO testing (for at least 10-15 minutes if clinically safe). High alveolar PO2 from supplemental oxygen competes with CO for hemoglobin binding sites, reducing CO uptake and falsely lowering the measured DLCO value.',
        difficulty: 3,
        topic: 'Advanced DLCO',
        isFree: false,
        orderIndex: 260,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // --- Flow-Volume Loop Pattern Recognition (10 cards) ---
      {
        question: 'What flow-volume loop pattern is characteristic of a fixed upper airway obstruction?',
        answer: 'A fixed upper airway obstruction produces flattening (plateau) of both the inspiratory and expiratory limbs of the flow-volume loop. The peak inspiratory and peak expiratory flows are equally reduced, creating a box-like or rectangular appearance. This occurs because the obstruction limits flow equally in both directions.',
        difficulty: 2,
        topic: 'Flow-Volume Loop Patterns',
        isFree: false,
        orderIndex: 261,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does the flow-volume loop of a variable extrathoracic obstruction differ from a variable intrathoracic obstruction?',
        answer: 'Variable extrathoracic obstruction shows flattening of the inspiratory limb only (during inspiration, negative intraluminal pressure causes the extrathoracic lesion to narrow). Variable intrathoracic obstruction shows flattening of the expiratory limb only (during expiration, positive intrathoracic pressure compresses the intrathoracic airway at the lesion site).',
        difficulty: 3,
        topic: 'Flow-Volume Loop Patterns',
        isFree: false,
        orderIndex: 262,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What flow-volume loop pattern suggests vocal cord dysfunction (VCD)?',
        answer: 'Vocal cord dysfunction typically produces flattening or truncation of the inspiratory limb of the flow-volume loop, similar to a variable extrathoracic obstruction. The expiratory limb is usually normal. The pattern may be intermittent and may normalize between episodes.',
        difficulty: 2,
        topic: 'Flow-Volume Loop Patterns',
        isFree: false,
        orderIndex: 263,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Describe the flow-volume loop pattern seen in a patient with a restrictive lung disease such as pulmonary fibrosis.',
        answer: 'The loop appears as a miniature version of a normal loop — it retains a normal shape but is compressed with reduced volumes. Peak expiratory flow may be normal or slightly reduced, FVC is reduced, and the FEV1/FVC ratio is normal or elevated. The expiratory limb descends steeply due to increased elastic recoil.',
        difficulty: 2,
        topic: 'Flow-Volume Loop Patterns',
        isFree: false,
        orderIndex: 264,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What does an abrupt termination of the expiratory limb on a flow-volume loop indicate?',
        answer: 'Abrupt termination suggests the patient stopped exhaling prematurely, either due to glottic closure, poor effort, or air trapping. This is an unacceptable maneuver and does not meet end-of-test criteria. The technologist should coach the patient to blow longer and more completely.',
        difficulty: 1,
        topic: 'Flow-Volume Loop Patterns',
        isFree: false,
        orderIndex: 265,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How can you identify a submaximal effort on a flow-volume loop?',
        answer: 'A submaximal effort typically shows a rounded or blunted peak expiratory flow (rather than a sharp peak), poor reproducibility between maneuvers, and the overall envelope may appear smaller than expected. The rise to peak flow is slow and the peak flow may vary significantly between attempts.',
        difficulty: 1,
        topic: 'Flow-Volume Loop Patterns',
        isFree: false,
        orderIndex: 266,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What flow-volume loop abnormality might be seen in a patient with tracheomalacia?',
        answer: 'Tracheomalacia causes a variable intrathoracic obstruction pattern with flattening or a saw-tooth pattern on the expiratory limb. During forced expiration, the weakened tracheal wall collapses due to increased intrathoracic pressure, limiting expiratory airflow. The inspiratory limb is typically normal.',
        difficulty: 3,
        topic: 'Flow-Volume Loop Patterns',
        isFree: false,
        orderIndex: 267,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What does a "saw-tooth" or oscillating pattern on the flow-volume loop suggest?',
        answer: 'A saw-tooth or oscillation pattern with regular fluctuations in flow can indicate upper airway instability, such as obstructive sleep apnea, Parkinson\'s disease, or other neuromuscular conditions affecting the upper airway. It may also be an artifact from loose dentures or the patient partially obstructing the mouthpiece.',
        difficulty: 2,
        topic: 'Flow-Volume Loop Patterns',
        isFree: false,
        orderIndex: 268,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does the flow-volume loop in a patient with combined obstructive and restrictive disease (mixed pattern) appear?',
        answer: 'The loop shows features of both patterns: reduced total volume (shifted left, indicating restriction) combined with a concave expiratory limb (indicating obstruction). The FVC is reduced, FEV1 is disproportionately reduced, and the FEV1/FVC ratio is low. Full lung volume measurements are needed to confirm the mixed pattern.',
        difficulty: 3,
        topic: 'Flow-Volume Loop Patterns',
        isFree: false,
        orderIndex: 269,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the significance of a reduced peak inspiratory flow (PIF) on the flow-volume loop when the expiratory limb is normal?',
        answer: 'Reduced PIF with a normal expiratory limb suggests a variable extrathoracic airway obstruction, such as vocal cord paralysis, subglottic stenosis, or vocal cord dysfunction. PIF should be at least 80-100% of peak expiratory flow in normal individuals. The PIF/PEF ratio is a useful screening metric.',
        difficulty: 3,
        topic: 'Flow-Volume Loop Patterns',
        isFree: false,
        orderIndex: 270,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // --- Quality Assurance Programs (10 cards) ---
      {
        question: 'What are the key components of a pulmonary function laboratory quality assurance (QA) program?',
        answer: 'Key components include: daily equipment calibration and verification, regular bio-QC testing, documentation of equipment maintenance, technologist competency assessment, review of test quality grades, proficiency testing, infection control protocols, recording of environmental conditions, and periodic review by a medical director.',
        difficulty: 2,
        topic: 'Quality Assurance',
        isFree: false,
        orderIndex: 271,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What environmental conditions must be monitored and recorded in a PFT laboratory?',
        answer: 'Room temperature, barometric pressure, and relative humidity should be recorded daily. Temperature should be between 17 and 40 degrees Celsius for accurate BTPS correction. These conditions affect gas volumes and the accuracy of BTPS corrections applied to spirometric measurements.',
        difficulty: 1,
        topic: 'Quality Assurance',
        isFree: false,
        orderIndex: 272,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the role of the medical director in a pulmonary function laboratory QA program?',
        answer: 'The medical director is responsible for overseeing the QA program, reviewing and interpreting test results, establishing laboratory policies and procedures, ensuring technologist competency, addressing quality issues identified by QC data, and maintaining accreditation standards.',
        difficulty: 1,
        topic: 'Quality Assurance',
        isFree: false,
        orderIndex: 273,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How should a PFT laboratory document and respond to an out-of-control calibration check?',
        answer: 'The out-of-control result should be logged with the date, equipment identification, the observed error, and the corrective action taken. The equipment should not be used for patient testing until the problem is resolved. Previous patient results obtained since the last successful calibration should be reviewed for potential errors.',
        difficulty: 2,
        topic: 'Quality Assurance',
        isFree: false,
        orderIndex: 274,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What statistical measure is commonly used to evaluate bio-QC results over time?',
        answer: 'The coefficient of variation (CV) is used, calculated as the standard deviation divided by the mean, expressed as a percentage. For a well-functioning laboratory, the within-subject CV for FEV1 and FVC should be less than or equal to 5%. Results are plotted on control charts (Levey-Jennings) to detect trends.',
        difficulty: 3,
        topic: 'Quality Assurance',
        isFree: false,
        orderIndex: 275,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the purpose of proficiency testing in a pulmonary function laboratory?',
        answer: 'Proficiency testing involves analyzing unknown samples or performing standardized test simulations to compare a laboratory\'s results against other laboratories and established standards. It is an external quality assessment that helps identify systematic errors and verify accuracy of measurements.',
        difficulty: 2,
        topic: 'Quality Assurance',
        isFree: false,
        orderIndex: 276,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How frequently should PFT technologist competency be assessed, and what should the assessment include?',
        answer: 'Competency should be assessed at hire, at 6 months, and at least annually thereafter. Assessments should include observed performance of test procedures, evaluation of test quality (proportion of grade A results), knowledge of acceptability and repeatability criteria, infection control practices, and appropriate patient coaching techniques.',
        difficulty: 2,
        topic: 'Quality Assurance',
        isFree: false,
        orderIndex: 277,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is a Levey-Jennings chart, and how is it used in PFT quality control?',
        answer: 'A Levey-Jennings chart plots individual QC data points over time against the mean and standard deviation lines (typically at plus or minus 1, 2, and 3 SD). It is used to monitor calibration checks and bio-QC results for trends, shifts, and outliers that indicate equipment malfunction or changes in testing conditions.',
        difficulty: 3,
        topic: 'Quality Assurance',
        isFree: false,
        orderIndex: 278,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What corrective action should be taken if a bio-QC trend shows a gradual upward drift in FVC values?',
        answer: 'Investigate possible causes including: a slow leak developing in the calibration syringe, inaccurate temperature sensor reading lower than actual temperature (over-correcting BTPS), or changes in the bio-QC subject\'s health. Verify calibration syringe accuracy against a reference standard and check the temperature sensor calibration.',
        difficulty: 3,
        topic: 'Quality Assurance',
        isFree: false,
        orderIndex: 279,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What percentage of spirometry tests in a PFT lab should meet ATS/ERS grade A quality?',
        answer: 'A well-run laboratory should aim for at least 80-90% of all spirometry tests to achieve grade A quality (three or more acceptable maneuvers meeting repeatability criteria). This metric should be tracked by technologist and used as a competency indicator.',
        difficulty: 2,
        topic: 'Quality Assurance',
        isFree: false,
        orderIndex: 280,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // --- Pre/Post Bronchodilator Assessment (10 cards) ---
      {
        question: 'What is the standard dose and administration method for bronchodilator used in pre/post spirometry?',
        answer: 'The standard is 4 puffs (400 mcg) of albuterol (salbutamol) administered via metered-dose inhaler (MDI) with a spacer/valved holding chamber. Each puff is given 30 seconds apart. Some protocols use 2.5 mg albuterol via nebulizer as an alternative.',
        difficulty: 1,
        topic: 'Pre/Post Bronchodilator',
        isFree: false,
        orderIndex: 281,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How long after bronchodilator administration should post-bronchodilator spirometry be performed?',
        answer: 'Post-bronchodilator spirometry should be performed 10 to 15 minutes after administration of a short-acting beta-agonist (albuterol). If an anticholinergic (ipratropium) is used, the wait time is 30 to 45 minutes due to its slower onset of action.',
        difficulty: 1,
        topic: 'Pre/Post Bronchodilator',
        isFree: false,
        orderIndex: 282,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the ATS/ERS criterion for a significant (positive) bronchodilator response in adults?',
        answer: 'A significant bronchodilator response is defined as an increase of 10% or more in either FEV1 or FVC relative to the predicted value (using the 2021 ATS/ERS update). Previously, the criterion was a 12% increase AND 200 mL absolute increase from the pre-bronchodilator value.',
        difficulty: 2,
        topic: 'Pre/Post Bronchodilator',
        isFree: false,
        orderIndex: 283,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What medications should be withheld before pre/post bronchodilator testing, and for how long?',
        answer: 'Short-acting beta-agonists: 4-6 hours. Short-acting anticholinergics: 12 hours. Long-acting beta-agonists (LABA): 24 hours. Ultra-long-acting beta-agonists (e.g., indacaterol): 36-48 hours. Long-acting anticholinergics (e.g., tiotropium): 48 hours. However, the ordering physician determines which medications should be withheld.',
        difficulty: 2,
        topic: 'Pre/Post Bronchodilator',
        isFree: false,
        orderIndex: 284,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Can a patient with a significant bronchodilator response still have COPD rather than asthma?',
        answer: 'Yes. Significant bronchodilator response can occur in COPD. Bronchodilator reversibility does not reliably distinguish between asthma and COPD. In COPD, the post-bronchodilator FEV1/FVC ratio remains below the lower limit of normal. The degree of reversibility may vary between visits in both conditions.',
        difficulty: 2,
        topic: 'Pre/Post Bronchodilator',
        isFree: false,
        orderIndex: 285,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why might FVC improve significantly after bronchodilator while FEV1 shows minimal change?',
        answer: 'An improvement in FVC without proportional FEV1 change suggests reduction in air trapping. The bronchodilator reduces airway resistance in peripheral airways, allowing more complete exhalation and reducing the residual volume. This pattern is commonly seen in COPD with significant hyperinflation.',
        difficulty: 3,
        topic: 'Pre/Post Bronchodilator',
        isFree: false,
        orderIndex: 286,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What are the contraindications to administering a bronchodilator during PFT testing?',
        answer: 'Relative contraindications include known hypersensitivity to the bronchodilator medication, severe tachycardia or tachyarrhythmia, and poorly controlled hypertension. The technologist should check for medication allergies and cardiac history before administering the bronchodilator.',
        difficulty: 1,
        topic: 'Pre/Post Bronchodilator',
        isFree: false,
        orderIndex: 287,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How should bronchodilator response be calculated and reported?',
        answer: 'Report both absolute change (post minus pre in mL) and percent change. The 2021 ATS/ERS recommendation calculates the change as a percentage of the predicted value: ((post - pre) / predicted) x 100. Report pre-BD values, post-BD values, absolute change, and percent change for both FEV1 and FVC.',
        difficulty: 2,
        topic: 'Pre/Post Bronchodilator',
        isFree: false,
        orderIndex: 288,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What side effects should the technologist monitor for after administering albuterol for bronchodilator response testing?',
        answer: 'Common side effects include tremor, tachycardia, palpitations, nervousness, and headache. The technologist should monitor the patient\'s heart rate and ask about symptoms before performing post-bronchodilator spirometry. Significant tachycardia or arrhythmia should be reported to the ordering physician.',
        difficulty: 1,
        topic: 'Pre/Post Bronchodilator',
        isFree: false,
        orderIndex: 289,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'If a patient cannot coordinate use of an MDI with spacer for bronchodilator administration, what alternative method is preferred?',
        answer: 'A small-volume nebulizer (SVN) should be used to administer the bronchodilator (typically 2.5 mg albuterol in 3 mL normal saline). The patient breathes tidally through a mouthpiece or mask for approximately 10-15 minutes. This method does not require coordination of inhalation with actuation.',
        difficulty: 1,
        topic: 'Pre/Post Bronchodilator',
        isFree: false,
        orderIndex: 290,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },

      // --- Reference Equations and Interpretation Strategies (10 cards) ---
      {
        question: 'What are the GLI-2012 reference equations, and why are they preferred over older reference sets?',
        answer: 'The Global Lung Initiative 2012 equations are multi-ethnic reference equations derived from a large international dataset of over 97,000 healthy individuals ages 3-95. They are preferred because they use continuous equations across all ages (eliminating age-break artifacts), provide lower limit of normal (LLN) values using z-scores, and include equations for multiple ethnic groups.',
        difficulty: 2,
        topic: 'Reference Equations',
        isFree: false,
        orderIndex: 291,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why is the lower limit of normal (LLN) preferred over fixed cutoff ratios (e.g., FEV1/FVC less than 0.70) for defining obstruction?',
        answer: 'The LLN, defined as the 5th percentile of the healthy population (z-score of -1.645), accounts for age, sex, height, and ethnicity. Using a fixed ratio of 0.70 overdiagnoses obstruction in elderly patients (whose ratio normally declines with age) and may underdiagnose it in younger adults.',
        difficulty: 2,
        topic: 'Reference Equations',
        isFree: false,
        orderIndex: 292,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is a z-score in the context of pulmonary function interpretation, and what z-score corresponds to the lower limit of normal?',
        answer: 'A z-score indicates how many standard deviations a measured value is from the predicted mean for a person of the same age, sex, height, and ethnicity. A z-score of -1.645 corresponds to the lower limit of normal (5th percentile). Values below this are considered abnormally low.',
        difficulty: 2,
        topic: 'Reference Equations',
        isFree: false,
        orderIndex: 293,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'According to the ATS/ERS interpretation strategy, how should severity of spirometric abnormalities be graded?',
        answer: 'Severity is graded based on FEV1 percent predicted (or z-score): Mild if FEV1 is greater than 70% predicted (z-score above -2.5), Moderate if FEV1 is 60-69% predicted (z-score -2.5 to -4.0), Moderately Severe if 50-59%, Severe if 35-49%, and Very Severe if less than 35% predicted.',
        difficulty: 2,
        topic: 'Reference Equations',
        isFree: false,
        orderIndex: 294,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'When should a PFT technologist recommend additional testing beyond spirometry to the interpreting physician?',
        answer: 'Additional testing should be suggested when: spirometry shows a possible restrictive pattern (low FVC with normal ratio) requiring lung volumes for confirmation, gas exchange assessment is needed (DLCO), pre-operative evaluation requires complete PFTs, or when the clinical question cannot be answered by spirometry alone.',
        difficulty: 1,
        topic: 'Reference Equations',
        isFree: false,
        orderIndex: 295,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the "nonspecific pattern" in spirometry interpretation?',
        answer: 'The nonspecific pattern occurs when both FEV1 and FVC are reduced but the FEV1/FVC ratio is normal or above the LLN. This pattern could represent early obstruction with air trapping, a restrictive process, or submaximal effort. Lung volume measurements are needed to differentiate between these possibilities.',
        difficulty: 3,
        topic: 'Reference Equations',
        isFree: false,
        orderIndex: 296,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'How does the technologist determine which set of reference equations to use for a patient of mixed racial/ethnic background?',
        answer: 'For patients of mixed racial/ethnic background, the GLI-2012 "other/mixed" reference equations should be used. If GLI equations are not available, some laboratories allow the patient to self-identify their primary ethnic group. The reference equation set used must be documented in the report.',
        difficulty: 2,
        topic: 'Reference Equations',
        isFree: false,
        orderIndex: 297,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What patient demographic information is required to calculate predicted values from reference equations?',
        answer: 'Age, sex, standing height, and race/ethnicity are required. Age should be recorded to the nearest year, height should be measured without shoes at the time of testing (not self-reported), and biological sex is used rather than gender identity for reference equation selection.',
        difficulty: 1,
        topic: 'Reference Equations',
        isFree: false,
        orderIndex: 298,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'Why is it important to measure height at the time of PFT testing rather than using a self-reported or historical value?',
        answer: 'Self-reported height is often inaccurate (typically overestimated by 1-2 cm). Height loss occurs with aging due to vertebral compression and postural changes. Since predicted values are highly dependent on height, even small errors can significantly affect percent predicted values and lead to misinterpretation.',
        difficulty: 1,
        topic: 'Reference Equations',
        isFree: false,
        orderIndex: 299,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
      {
        question: 'What is the clinical significance of tracking pulmonary function trends over time in an individual patient?',
        answer: 'Longitudinal tracking allows detection of clinically significant changes beyond normal variability. An annual decline in FEV1 greater than 40-50 mL/year suggests accelerated lung function loss (normal age-related decline is 20-30 mL/year after age 35). Trends help assess disease progression, treatment response, and occupational exposure effects.',
        difficulty: 2,
        topic: 'Reference Equations',
        isFree: false,
        orderIndex: 300,
        divisionId: 'cmsm41fxw0004zf54sy6um2ui',
      },
    ],
    skipDuplicates: true,
  })

  console.log('Successfully seeded 100 CPFT flashcards (batch 3).')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
