import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const TMC_DIVISION_ID = 'cmsm41fq00000zf54wqjaayvz'

const flashcards = [
  // ============================================================
  // PATIENT ASSESSMENT (cards 1-15)
  // ============================================================
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the normal range for adult respiratory rate?',
    answer: '12-20 breaths per minute. A rate above 20 is termed tachypnea, while a rate below 12 is bradypnea. Respiratory rate is one of the most sensitive indicators of patient deterioration.',
    difficulty: 1,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 1,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What does a barrel chest appearance suggest in a patient?',
    answer: 'A barrel chest (increased anteroposterior diameter) is characteristic of chronic air trapping, most commonly seen in COPD/emphysema. The AP diameter approaches the lateral diameter, giving the chest a rounded shape.',
    difficulty: 1,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 2,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What breath sounds are expected over the trachea during auscultation?',
    answer: 'Bronchial (tubular) breath sounds are normally heard over the trachea. They are loud, high-pitched, and have a longer expiratory phase than inspiratory phase. Hearing bronchial sounds over the lung periphery is abnormal and may indicate consolidation.',
    difficulty: 1,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 3,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the significance of jugular venous distention (JVD) in a respiratory patient?',
    answer: 'JVD indicates elevated central venous pressure, commonly associated with right-sided heart failure, cor pulmonale, tension pneumothorax, or cardiac tamponade. The external jugular veins appear engorged when the patient is positioned at 45 degrees.',
    difficulty: 2,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 4,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'On a chest radiograph, how can you distinguish between a pleural effusion and consolidation?',
    answer: 'A pleural effusion produces a meniscus sign (concave upward curve) at the costophrenic angle and layers dependently on a lateral decubitus film. Consolidation shows air bronchograms (air-filled bronchi visible within opacified lung tissue) and does not shift with position changes.',
    difficulty: 3,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 5,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What does the presence of subcutaneous emphysema indicate?',
    answer: 'Subcutaneous emphysema (crepitus felt under the skin) indicates air has escaped into the subcutaneous tissue. Common causes include pneumothorax, pneumomediastinum, chest tube malposition, or tracheostomy-related complications.',
    difficulty: 2,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 6,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the normal adult heart rate range, and what values define tachycardia and bradycardia?',
    answer: 'Normal adult heart rate is 60-100 beats per minute. Tachycardia is a rate above 100 bpm, and bradycardia is below 60 bpm. Sinus tachycardia in respiratory patients may indicate hypoxemia, fever, pain, or anxiety.',
    difficulty: 1,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 7,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How do you assess for pulsus paradoxus, and what does it indicate?',
    answer: 'Pulsus paradoxus is a systolic blood pressure drop greater than 10 mmHg during inspiration. It is measured by noting the pressure at which Korotkoff sounds are first heard only during expiration versus when heard throughout. It suggests severe asthma, cardiac tamponade, or pericardial effusion.',
    difficulty: 3,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 8,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What does digital clubbing of the fingers suggest?',
    answer: 'Digital clubbing (increased angle between the nail and nail bed beyond 180 degrees) is associated with chronic hypoxemia. Common causes include bronchiectasis, cystic fibrosis, interstitial pulmonary fibrosis, and lung cancer.',
    difficulty: 2,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 9,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the clinical significance of a tracheal shift on physical exam?',
    answer: 'The trachea shifts toward the affected side with atelectasis and pneumonectomy (due to volume loss). It shifts away from the affected side with tension pneumothorax and large pleural effusion (due to pressure or fluid pushing mediastinal structures).',
    difficulty: 2,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 10,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What radiographic finding is most consistent with left ventricular failure?',
    answer: 'Bilateral perihilar haziness (butterfly or bat-wing pattern) with cephalization of pulmonary vasculature is most consistent with pulmonary edema from left ventricular failure. Kerley B lines (short horizontal lines near the lung bases) and bilateral pleural effusions may also be present.',
    difficulty: 3,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 11,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the normal values for systolic and diastolic blood pressure in an adult?',
    answer: 'Normal blood pressure is less than 120/80 mmHg. Hypertension is defined as sustained readings at or above 130/80 mmHg. Hypotension is generally defined as systolic pressure below 90 mmHg.',
    difficulty: 1,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 12,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What does diminished or absent breath sounds over one lung field suggest?',
    answer: 'Diminished or absent unilateral breath sounds suggest pneumothorax, large pleural effusion, mainstem intubation on the opposite side, or complete obstruction of a mainstem bronchus (mucus plug or foreign body). Immediate evaluation and intervention may be required.',
    difficulty: 2,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 13,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'Describe the difference between fine and coarse crackles on auscultation.',
    answer: 'Fine crackles are soft, high-pitched, and heard at end-inspiration, typically associated with pulmonary fibrosis, early heart failure, or atelectasis. Coarse crackles are louder, lower-pitched, heard during both inspiration and expiration, and suggest secretions in larger airways as seen in bronchitis or pneumonia.',
    difficulty: 2,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 14,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What chest X-ray finding confirms proper endotracheal tube placement?',
    answer: 'The tip of the endotracheal tube should be positioned 3-5 cm above the carina on a chest radiograph (approximately at the level of the aortic knob or T3-T4). If the tip is too low, right mainstem intubation is likely; if too high, accidental extubation risk increases.',
    difficulty: 2,
    topic: 'Patient Assessment',
    isFree: true,
    orderIndex: 15,
  },

  // ============================================================
  // ABG INTERPRETATION (cards 16-30)
  // ============================================================
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the normal arterial blood gas values for pH, PaCO2, PaO2, and HCO3?',
    answer: 'Normal ABG values: pH 7.35-7.45, PaCO2 35-45 mmHg, PaO2 80-100 mmHg, and HCO3 22-26 mEq/L. These reference ranges are essential for classifying acid-base disturbances.',
    difficulty: 1,
    topic: 'ABG Interpretation',
    isFree: true,
    orderIndex: 16,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How do you identify respiratory acidosis on an ABG?',
    answer: 'Respiratory acidosis is identified by pH below 7.35 with PaCO2 above 45 mmHg. The primary problem is inadequate alveolar ventilation (hypoventilation). If HCO3 is elevated above 26 mEq/L, renal compensation is occurring.',
    difficulty: 1,
    topic: 'ABG Interpretation',
    isFree: true,
    orderIndex: 17,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'A patient has pH 7.28, PaCO2 60 mmHg, HCO3 28 mEq/L. Interpret this ABG.',
    answer: 'This is partially compensated respiratory acidosis. The pH is acidotic, the elevated PaCO2 is the primary cause, and the HCO3 is elevated as the kidneys retain bicarbonate to compensate. Full compensation has not occurred because the pH is still outside normal range.',
    difficulty: 2,
    topic: 'ABG Interpretation',
    isFree: true,
    orderIndex: 18,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the expected PaO2 for a patient breathing room air based on the alveolar air equation?',
    answer: 'Using a simplified alveolar air equation: PAO2 = FiO2(Pb - PH2O) - (PaCO2/0.8). On room air at sea level: PAO2 = 0.21(760-47) - (40/0.8) = approximately 100 mmHg. The normal A-a gradient is 5-15 mmHg, giving an expected PaO2 of 80-100 mmHg.',
    difficulty: 3,
    topic: 'ABG Interpretation',
    isFree: true,
    orderIndex: 19,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What ABG pattern indicates metabolic alkalosis?',
    answer: 'Metabolic alkalosis shows pH above 7.45 with HCO3 above 26 mEq/L. Common causes include prolonged nasogastric suctioning, excessive vomiting, diuretic use, and overcorrection with sodium bicarbonate. Respiratory compensation involves hypoventilation (rising PaCO2).',
    difficulty: 1,
    topic: 'ABG Interpretation',
    isFree: true,
    orderIndex: 20,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How do you calculate the P/F ratio, and what does a value below 300 indicate?',
    answer: 'The P/F ratio is calculated by dividing PaO2 by FiO2 (as a decimal). A P/F ratio below 300 indicates acute lung injury (ALI), and below 200 meets the oxygenation criterion for ARDS. For example, PaO2 of 80 on FiO2 0.40 gives a P/F ratio of 200.',
    difficulty: 3,
    topic: 'ABG Interpretation',
    isFree: false,
    orderIndex: 21,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'A patient has pH 7.50, PaCO2 30 mmHg, HCO3 24 mEq/L. Interpret this ABG.',
    answer: 'This is uncompensated respiratory alkalosis. The elevated pH with low PaCO2 indicates the patient is hyperventilating. The normal HCO3 shows the kidneys have not yet compensated. Common causes include anxiety, hypoxemia, pain, or excessive mechanical ventilation.',
    difficulty: 2,
    topic: 'ABG Interpretation',
    isFree: false,
    orderIndex: 22,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the Henderson-Hasselbalch equation and how does it relate pH to the bicarbonate buffer system?',
    answer: 'The Henderson-Hasselbalch equation is pH = 6.1 + log(HCO3 / 0.03 x PaCO2). It demonstrates that pH is determined by the ratio of bicarbonate (metabolic component) to dissolved CO2 (respiratory component). A 20:1 ratio of HCO3 to dissolved CO2 yields a normal pH of 7.40.',
    difficulty: 3,
    topic: 'ABG Interpretation',
    isFree: false,
    orderIndex: 23,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the significance of the anion gap in metabolic acidosis?',
    answer: 'The anion gap (Na - [Cl + HCO3]) is normally 8-12 mEq/L. An elevated anion gap indicates accumulation of unmeasured acids such as lactic acid, ketoacids, or toxins (methanol, ethylene glycol, salicylates). A normal anion gap metabolic acidosis (hyperchloremic) results from bicarbonate loss (diarrhea) or renal tubular acidosis.',
    difficulty: 3,
    topic: 'ABG Interpretation',
    isFree: false,
    orderIndex: 24,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How does the body compensate for metabolic acidosis?',
    answer: 'The respiratory system compensates for metabolic acidosis by increasing ventilation (Kussmaul breathing), which lowers PaCO2. This occurs rapidly within minutes to hours. The expected PaCO2 can be estimated using Winter\'s formula: PaCO2 = (1.5 x HCO3) + 8, plus or minus 2.',
    difficulty: 3,
    topic: 'ABG Interpretation',
    isFree: false,
    orderIndex: 25,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What does an elevated A-a gradient indicate?',
    answer: 'An elevated A-a gradient (above 15 mmHg on room air) indicates an intrapulmonary cause of hypoxemia such as V/Q mismatch, diffusion impairment, or intrapulmonary shunt. A normal A-a gradient with hypoxemia points to hypoventilation or low FiO2 as the cause.',
    difficulty: 3,
    topic: 'ABG Interpretation',
    isFree: false,
    orderIndex: 26,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the difference between acute and chronic respiratory acidosis on ABG?',
    answer: 'In acute respiratory acidosis, pH drops significantly with elevated PaCO2 and near-normal HCO3 (increases ~1 mEq/L per 10 mmHg rise in PaCO2). In chronic respiratory acidosis, renal compensation raises HCO3 (~3.5 mEq/L per 10 mmHg rise in PaCO2), bringing pH closer to normal.',
    difficulty: 3,
    topic: 'ABG Interpretation',
    isFree: false,
    orderIndex: 27,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'A patient has pH 7.33, PaCO2 38 mmHg, HCO3 18 mEq/L. What is the acid-base disturbance?',
    answer: 'This is partially compensated metabolic acidosis. The low pH and low HCO3 indicate a metabolic origin. The PaCO2 is lower than 40, showing the lungs are attempting to compensate by blowing off CO2, but pH remains below normal so compensation is incomplete.',
    difficulty: 2,
    topic: 'ABG Interpretation',
    isFree: false,
    orderIndex: 28,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What ABG findings would you expect in a patient with a COPD exacerbation who has a chronic baseline PaCO2 of 55 mmHg?',
    answer: 'A COPD patient with chronic CO2 retention typically has a compensated respiratory acidosis at baseline (near-normal pH with elevated HCO3). During an acute exacerbation, PaCO2 rises further above baseline, pH drops below 7.35, and PaO2 falls. This pattern is called acute-on-chronic respiratory acidosis.',
    difficulty: 3,
    topic: 'ABG Interpretation',
    isFree: false,
    orderIndex: 29,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the normal base excess range, and what does a negative value signify?',
    answer: 'Normal base excess is -2 to +2 mEq/L. A negative base excess (base deficit) indicates metabolic acidosis, meaning there is a deficit of buffer base in the blood. A positive base excess indicates metabolic alkalosis with excess buffer base.',
    difficulty: 2,
    topic: 'ABG Interpretation',
    isFree: false,
    orderIndex: 30,
  },

  // ============================================================
  // OXYGEN THERAPY (cards 31-45)
  // ============================================================
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What FiO2 does a nasal cannula deliver at 1-6 L/min?',
    answer: 'A nasal cannula delivers approximately 24% FiO2 at 1 L/min, increasing about 4% per liter up to 6 L/min (44% FiO2). Flow rates above 6 L/min do not significantly increase FiO2 and cause nasal mucosal drying and discomfort.',
    difficulty: 1,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 31,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the key advantage of a high-flow nasal cannula (HFNC) system over a standard nasal cannula?',
    answer: 'HFNC delivers heated and humidified gas at flows up to 60 L/min, which meets or exceeds the patient\'s inspiratory demand. This provides a more precise and consistent FiO2, generates a small amount of PEEP, and reduces anatomic dead space through nasopharyngeal washout.',
    difficulty: 2,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 32,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What type of oxygen delivery device provides the most precise FiO2?',
    answer: 'An air-entrainment (Venturi) mask provides the most precise FiO2 among standard devices because it uses jet mixing to entrain a fixed ratio of room air. It is classified as a high-flow system when total flow meets the patient\'s inspiratory demand. Available FiO2 settings typically range from 24% to 50%.',
    difficulty: 1,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 33,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'When should a non-rebreather mask be used, and what FiO2 does it deliver?',
    answer: 'A non-rebreather mask is indicated for acute hypoxemia requiring high FiO2. It delivers 60-80% FiO2 at 10-15 L/min with a reservoir bag and one-way valves. The flow must be sufficient to keep the reservoir bag from deflating completely during inspiration.',
    difficulty: 1,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 34,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is oxygen toxicity, and at what FiO2 level does the risk become significant?',
    answer: 'Oxygen toxicity occurs from prolonged exposure to high FiO2, causing free radical damage to alveolar membranes. The risk becomes significant at FiO2 above 0.60 for more than 24-48 hours. Manifestations include substernal chest pain, progressive hypoxemia, and eventually ARDS-like changes.',
    difficulty: 3,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 35,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'Why is high-flow oxygen potentially dangerous for a patient with chronic CO2 retention?',
    answer: 'Chronic CO2 retainers (e.g., COPD patients) may rely partly on hypoxic drive to stimulate ventilation. Administering high FiO2 can diminish this drive, leading to further hypoventilation and worsening hypercapnia. Additionally, high FiO2 can worsen V/Q mismatch by releasing hypoxic vasoconstriction. The target SpO2 is typically 88-92%.',
    difficulty: 3,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 36,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How do you calculate the total flow output of an air-entrainment device set to deliver 40% FiO2?',
    answer: 'Use the air-to-oxygen entrainment ratio. For 40% FiO2, the ratio is 3:1 (3 parts air to 1 part oxygen). If the oxygen flow is set at 8 L/min, total flow = 8 x (3+1) = 32 L/min. Total flow must meet or exceed the patient\'s peak inspiratory flow to ensure accurate FiO2 delivery.',
    difficulty: 3,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 37,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is retinopathy of prematurity (ROP), and how is it related to oxygen therapy?',
    answer: 'ROP is abnormal blood vessel growth in the retina of premature infants exposed to excessive oxygen levels. High PaO2 causes vasoconstriction followed by disorganized neovascularization. PaO2 should be maintained between 50-80 mmHg (SpO2 88-95%) in premature neonates to reduce risk.',
    difficulty: 2,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 38,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the indications for initiating long-term home oxygen therapy?',
    answer: 'Home oxygen is indicated for patients with a resting PaO2 of 55 mmHg or less, or SpO2 of 88% or less. It is also indicated at PaO2 56-59 mmHg if there is evidence of cor pulmonale, polycythemia (hematocrit above 55%), or pulmonary hypertension.',
    difficulty: 1,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 39,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'A patient on a simple mask at 8 L/min has SpO2 of 85%. What is the appropriate next step?',
    answer: 'Switch to a non-rebreather mask at 10-15 L/min to maximize FiO2. If SpO2 remains below 90%, consider high-flow nasal cannula or non-invasive positive pressure ventilation. If the patient shows signs of respiratory failure despite escalation, intubation and mechanical ventilation should be considered.',
    difficulty: 2,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 40,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is absorption atelectasis, and how does oxygen therapy contribute to it?',
    answer: 'Absorption atelectasis occurs when high concentrations of oxygen replace nitrogen in poorly ventilated alveoli. Since oxygen is rapidly absorbed into the blood, the alveoli collapse without nitrogen to maintain their volume. This is most likely with FiO2 above 0.50 in regions with low V/Q ratios.',
    difficulty: 3,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 41,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the maximum recommended flow rate for a standard nasal cannula, and why?',
    answer: 'The maximum recommended flow for a standard nasal cannula is 6 L/min. Higher flows cause significant nasal mucosal drying, epistaxis, headaches, and patient discomfort without meaningful improvement in FiO2. If higher FiO2 is needed, switch to a mask-based device or HFNC.',
    difficulty: 1,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 42,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How does a partial rebreather mask differ from a non-rebreather mask?',
    answer: 'A partial rebreather has a reservoir bag but no one-way valves between the bag and the mask, so the first third of exhaled gas (from dead space, rich in O2) refills the bag. A non-rebreather has one-way valves preventing exhaled gas from entering the bag, delivering higher FiO2 (60-80% vs. 40-70%).',
    difficulty: 2,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 43,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the appropriate oxygen delivery device for a patient who needs precise low-flow FiO2 of 28%?',
    answer: 'An air-entrainment (Venturi) mask set to 28% is the best choice for precise low-concentration oxygen delivery. This is particularly important for COPD patients at risk of oxygen-induced hypercapnia. The total output flow at 28% typically provides approximately 72 L/min, exceeding most patients\' inspiratory demands.',
    difficulty: 2,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 44,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the magic box method for calculating air-entrainment ratios?',
    answer: 'The magic box places 100 (oxygen) and 21 (air) on the left side and the desired FiO2 in the center. Cross-subtract: desired FiO2 minus 21 gives the oxygen part, and 100 minus desired FiO2 gives the air part. For example, for 40% FiO2: air = 100-40 = 60, oxygen = 40-21 = 19, giving a ratio of approximately 3:1.',
    difficulty: 3,
    topic: 'Oxygen Therapy',
    isFree: false,
    orderIndex: 45,
  },

  // ============================================================
  // AIRWAY MANAGEMENT (cards 46-60)
  // ============================================================
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the standard endotracheal tube size for an average adult male and female?',
    answer: 'For an adult male, the typical ET tube size is 8.0-8.5 mm internal diameter. For an adult female, 7.0-7.5 mm ID is standard. Tube size selection should also consider the clinical situation; a smaller tube may be chosen when airway edema is suspected.',
    difficulty: 1,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 46,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the recommended cuff pressure range for an endotracheal tube?',
    answer: 'ET tube cuff pressure should be maintained between 20-30 cmH2O (or 25 cmH2O as a target). Pressures below 20 cmH2O risk aspiration of secretions, while pressures above 30 cmH2O can impair tracheal capillary perfusion, leading to ischemia, necrosis, and tracheal stenosis.',
    difficulty: 1,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 47,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the proper technique for suctioning through an endotracheal tube?',
    answer: 'Use a suction catheter no larger than half the ET tube\'s internal diameter. Insert without suction applied until resistance is met or the patient coughs, then apply intermittent suction while withdrawing with a rotating motion. Limit each pass to 10-15 seconds and pre-oxygenate with 100% O2 before and after.',
    difficulty: 1,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 48,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the signs of accidental right mainstem bronchus intubation?',
    answer: 'Signs include absent or diminished breath sounds over the left lung, decreased chest rise on the left side, and potentially increased peak airway pressures. SpO2 may decrease due to left lung atelectasis. The fix is to deflate the cuff, withdraw the tube 2-3 cm, re-inflate, and confirm position with auscultation and chest X-ray.',
    difficulty: 2,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 49,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'When is a tracheostomy generally recommended over continued endotracheal intubation?',
    answer: 'Tracheostomy is typically considered after 7-10 days of endotracheal intubation or when prolonged mechanical ventilation is anticipated. Benefits include reduced laryngeal injury, improved patient comfort, easier oral care, facilitated weaning, and the ability to eat and speak (with appropriate valves).',
    difficulty: 2,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 50,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the purpose of a Passy-Muir speaking valve?',
    answer: 'A Passy-Muir valve is a one-way valve placed on a tracheostomy tube that allows air in during inspiration but closes during expiration, redirecting airflow up through the vocal cords. This enables speech, improves swallowing, and restores physiologic PEEP. The cuff must be fully deflated before use.',
    difficulty: 2,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 51,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the immediate action if a tracheostomy tube becomes dislodged within the first 72 hours post-placement?',
    answer: 'In the first 72 hours, the stoma tract is not mature and reinsertion may create a false passage. Immediately attempt oral or nasal intubation while covering the stoma. Bag-mask ventilate through the mouth/nose with the stoma covered. Call for surgical assistance for controlled reinsertion.',
    difficulty: 3,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 52,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How do you determine the correct suction catheter size for a given endotracheal tube?',
    answer: 'Multiply the ET tube internal diameter by 2 and select the next smallest French catheter size. For example, an 8.0 mm ET tube: 8 x 2 = 16, so use a 14 French catheter. The catheter should not exceed half the internal diameter to prevent excessive negative pressure and atelectasis.',
    difficulty: 2,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 53,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the Mallampati classification used for?',
    answer: 'The Mallampati classification assesses the visibility of oropharyngeal structures with the mouth fully open and tongue protruding to predict intubation difficulty. Class I (full visibility of soft palate, uvula, and pillars) predicts easy intubation. Class IV (only hard palate visible) predicts difficult intubation.',
    difficulty: 3,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 54,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the indications for using a laryngeal mask airway (LMA)?',
    answer: 'An LMA is used when endotracheal intubation fails or is not feasible, as a bridge device during difficult airway management, and for short surgical procedures. It does not provide definitive airway protection against aspiration. It is placed supraglottically without laryngoscopy.',
    difficulty: 2,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 55,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the complications of endotracheal suctioning?',
    answer: 'Complications include hypoxemia, cardiac arrhythmias (bradycardia from vagal stimulation), mucosal trauma and bleeding, bronchospasm, increased intracranial pressure, and atelectasis. These are minimized by limiting suction duration to 10-15 seconds, pre-oxygenation, and using appropriate catheter size and suction pressure.',
    difficulty: 3,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 56,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is a cuff leak test, and when is it performed?',
    answer: 'A cuff leak test assesses for upper airway edema before extubation. The cuff is deflated and the difference between inspiratory and expiratory tidal volumes is measured. A cuff leak less than 110 mL (or less than 10-25% of delivered tidal volume) suggests significant laryngeal edema and increased risk of post-extubation stridor.',
    difficulty: 3,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 57,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the steps for confirming endotracheal tube placement after intubation?',
    answer: 'Confirm placement by: (1) direct visualization of the tube passing through the cords, (2) auscultation of bilateral breath sounds and absence of epigastric sounds, (3) end-tidal CO2 detection (gold standard for confirming tracheal placement), (4) chest X-ray to confirm depth, and (5) observing bilateral chest rise.',
    difficulty: 1,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 58,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the recommended suction pressure range for adults during endotracheal suctioning?',
    answer: 'Recommended suction pressure for adults is 100-150 mmHg (some sources say up to 120 mmHg). For children, 80-100 mmHg is used, and for neonates, 60-80 mmHg. Excessive suction pressure increases the risk of mucosal trauma, bleeding, and atelectasis.',
    difficulty: 1,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 59,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is a cricothyrotomy, and when is it performed?',
    answer: 'A cricothyrotomy is an emergency surgical airway created by incising the cricothyroid membrane between the thyroid and cricoid cartilages. It is performed as a last resort when the airway cannot be secured by intubation or supraglottic devices (cannot intubate, cannot oxygenate scenario). It provides rapid temporary access.',
    difficulty: 3,
    topic: 'Airway Management',
    isFree: false,
    orderIndex: 60,
  },

  // ============================================================
  // MECHANICAL VENTILATION (cards 61-80)
  // ============================================================
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the difference between volume-controlled and pressure-controlled ventilation?',
    answer: 'In volume-controlled ventilation, a set tidal volume is delivered and airway pressure varies depending on compliance and resistance. In pressure-controlled ventilation, a set inspiratory pressure is delivered and tidal volume varies. Volume control guarantees minute ventilation; pressure control limits peak pressure.',
    difficulty: 1,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 61,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is PEEP, and what is its primary purpose?',
    answer: 'PEEP (Positive End-Expiratory Pressure) maintains a positive pressure in the airways at the end of expiration to prevent alveolar collapse. It improves oxygenation by increasing functional residual capacity (FRC) and recruiting collapsed alveoli. Typical starting PEEP is 5 cmH2O.',
    difficulty: 1,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 62,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What initial ventilator settings would you recommend for a 70 kg patient with normal lungs?',
    answer: 'Typical initial settings: mode AC/VC, tidal volume 6-8 mL/kg IBW (420-560 mL), rate 12-16 breaths/min, FiO2 1.0 (wean based on SpO2), PEEP 5 cmH2O, and flow rate 40-60 L/min. Adjust based on ABG results within 30 minutes.',
    difficulty: 1,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 63,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How does SIMV mode differ from Assist-Control (AC) mode?',
    answer: 'In AC mode, every patient-triggered breath receives the full set tidal volume or pressure. In SIMV, the ventilator delivers a set number of mandatory breaths, and any additional patient breaths above that rate are spontaneous (unsupported unless pressure support is added). SIMV was historically used for weaning but has fallen out of favor.',
    difficulty: 2,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 64,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is auto-PEEP, and how is it detected?',
    answer: 'Auto-PEEP (intrinsic PEEP) is trapped gas pressure that occurs when expiration is incomplete before the next breath. It is detected by performing an expiratory hold maneuver and noting pressure above set PEEP. Common causes include high respiratory rates, prolonged inspiration, bronchospasm, and air trapping in COPD.',
    difficulty: 3,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 65,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What ventilator changes would you make to correct respiratory acidosis (high PaCO2)?',
    answer: 'To reduce PaCO2, increase minute ventilation by either increasing the respiratory rate or tidal volume. Increasing the rate is preferred if tidal volume is already at 6-8 mL/kg IBW. Avoid excessive tidal volumes, which cause ventilator-induced lung injury. Ensure adequate expiratory time to prevent auto-PEEP.',
    difficulty: 2,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 66,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the ARDSNet lung-protective ventilation strategy?',
    answer: 'ARDSNet recommends tidal volumes of 4-6 mL/kg ideal body weight, plateau pressures no higher than 30 cmH2O, and adequate PEEP guided by a PEEP/FiO2 table. The goal is to minimize volutrauma and barotrauma. Permissive hypercapnia is acceptable (pH above 7.20) to maintain protective volumes.',
    difficulty: 2,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 67,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What does a high peak inspiratory pressure (PIP) with normal plateau pressure indicate?',
    answer: 'High PIP with normal plateau pressure (difference greater than 10 cmH2O) indicates increased airway resistance. Causes include bronchospasm, secretions, kinked ET tube, biting on the tube, or a small-diameter ET tube. The gradient between PIP and plateau reflects resistive pressure.',
    difficulty: 2,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 68,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What does a high peak inspiratory pressure (PIP) with equally high plateau pressure indicate?',
    answer: 'When both PIP and plateau pressure are elevated, the problem is decreased lung compliance. Causes include pneumothorax, atelectasis, pulmonary edema, ARDS, abdominal distension, or pleural effusion. Plateau pressure above 30 cmH2O significantly increases the risk of barotrauma.',
    difficulty: 2,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 69,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is pressure support ventilation (PSV), and when is it used?',
    answer: 'PSV provides a set level of inspiratory pressure augmentation during spontaneous breaths. The patient controls rate, tidal volume, and inspiratory time. It is primarily used to overcome the work of breathing through the ET tube and circuit during weaning, or as the sole mode in patients with reliable respiratory drive.',
    difficulty: 2,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 70,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What criteria indicate a patient is ready for a spontaneous breathing trial (SBT)?',
    answer: 'SBT readiness criteria: underlying cause of respiratory failure is improving, FiO2 0.40 or less, PEEP 5-8 cmH2O or less, adequate oxygenation (P/F greater than 150-200), hemodynamically stable without vasopressors, able to initiate spontaneous breaths, and no significant sedation.',
    difficulty: 3,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 71,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the rapid shallow breathing index (RSBI), and what value predicts successful extubation?',
    answer: 'RSBI is calculated as respiratory rate divided by tidal volume in liters (f/VT). An RSBI less than 105 breaths/min/L predicts successful extubation, while a value above 105 suggests likely extubation failure. It is measured during a brief period of unassisted spontaneous breathing.',
    difficulty: 2,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 72,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How do you calculate static compliance, and what is the normal value?',
    answer: 'Static compliance = tidal volume / (plateau pressure - PEEP). Normal static compliance is 60-100 mL/cmH2O. Values below 30 mL/cmH2O indicate significantly reduced lung compliance. It reflects the elastic properties of the lung and chest wall without the influence of airway resistance.',
    difficulty: 3,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 73,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the cause and treatment of ventilator-associated patient-ventilator asynchrony (double triggering)?',
    answer: 'Double triggering occurs when the ventilator delivers two consecutive breaths for one patient effort, often because the set tidal volume is too low or inspiratory time is too short relative to patient demand. Treatment includes increasing tidal volume, adjusting inspiratory time, or changing to pressure-targeted mode to better match flow demand.',
    difficulty: 3,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 74,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the difference between a high-pressure alarm and a low-pressure alarm on a ventilator?',
    answer: 'A high-pressure alarm triggers when PIP exceeds the set limit, caused by coughing, secretions, bronchospasm, kinked tubing, biting, or decreased compliance. A low-pressure alarm indicates a circuit leak or disconnect, such as a loose connection, cuff leak, or chest tube with a large bronchopleural fistula.',
    difficulty: 1,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 75,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is CPAP, and how does it differ from BiPAP?',
    answer: 'CPAP delivers continuous positive airway pressure at a single set pressure throughout both inspiration and expiration. BiPAP (bilevel positive airway pressure) provides two pressure levels: a higher IPAP during inspiration and a lower EPAP during expiration. BiPAP additionally supports ventilation by augmenting tidal volume.',
    difficulty: 1,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 76,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the I:E ratio, and what is the normal setting?',
    answer: 'The I:E ratio is the ratio of inspiratory time to expiratory time in a respiratory cycle. Normal setting is 1:2 to 1:3. An inverse ratio (e.g., 2:1) may be used in severe ARDS to improve oxygenation but increases mean airway pressure and risk of auto-PEEP.',
    difficulty: 2,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 77,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the purpose of a plateau pressure measurement, and how is it obtained?',
    answer: 'Plateau pressure reflects alveolar pressure and lung compliance without the influence of airway resistance. It is measured by performing a brief inspiratory hold (0.5-2 seconds) at end-inspiration during volume-controlled ventilation. It should be maintained below 30 cmH2O to prevent ventilator-induced lung injury.',
    difficulty: 2,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 78,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What ventilator waveform abnormality suggests the presence of auto-PEEP?',
    answer: 'On the flow-time waveform, expiratory flow that does not return to zero baseline before the next inspiration indicates auto-PEEP (air trapping). The expiratory flow curve appears truncated. Interventions include decreasing the respiratory rate, decreasing inspiratory time, or treating the underlying cause of air trapping.',
    difficulty: 3,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 79,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the contraindications for non-invasive positive pressure ventilation (NIPPV)?',
    answer: 'Contraindications include cardiac or respiratory arrest, inability to protect the airway, excessive secretions, uncooperative or obtunded patient, recent facial or upper airway surgery, hemodynamic instability, and high aspiration risk. These patients generally require immediate intubation and invasive ventilation.',
    difficulty: 2,
    topic: 'Mechanical Ventilation',
    isFree: false,
    orderIndex: 80,
  },

  // ============================================================
  // PHARMACOLOGY (cards 81-90)
  // ============================================================
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the mechanism of action of albuterol?',
    answer: 'Albuterol is a short-acting beta-2 adrenergic agonist (SABA) that relaxes bronchial smooth muscle by stimulating beta-2 receptors, increasing intracellular cAMP. Onset is 5-15 minutes with duration of 4-6 hours. Side effects include tachycardia, tremor, and hypokalemia.',
    difficulty: 2,
    topic: 'Pharmacology',
    isFree: false,
    orderIndex: 81,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the role of ipratropium bromide in respiratory care?',
    answer: 'Ipratropium is an anticholinergic (parasympatholytic) bronchodilator that blocks muscarinic receptors, reducing bronchospasm and secretions. It has a slower onset (15-30 minutes) than albuterol but fewer cardiac side effects. It is often combined with albuterol (DuoNeb) for synergistic bronchodilation in COPD and severe asthma.',
    difficulty: 1,
    topic: 'Pharmacology',
    isFree: false,
    orderIndex: 82,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'When should inhaled corticosteroids be used in respiratory disease?',
    answer: 'Inhaled corticosteroids (e.g., budesonide, fluticasone) are used as maintenance therapy for persistent asthma and sometimes COPD to reduce airway inflammation. They are not rescue medications. Patients should rinse their mouth after use to prevent oral candidiasis (thrush) and dysphonia.',
    difficulty: 1,
    topic: 'Pharmacology',
    isFree: false,
    orderIndex: 83,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the standard adult dose of racemic epinephrine, and what is its primary indication?',
    answer: 'Racemic epinephrine is given as 0.5 mL of 2.25% solution diluted in 3 mL normal saline via nebulizer. Its primary indication is post-extubation stridor and upper airway edema (croup in pediatrics). It works by stimulating alpha-adrenergic receptors causing mucosal vasoconstriction, reducing edema.',
    difficulty: 2,
    topic: 'Pharmacology',
    isFree: false,
    orderIndex: 84,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the mechanism and use of acetylcysteine (Mucomyst)?',
    answer: 'Acetylcysteine is a mucolytic that breaks disulfide bonds in mucus glycoproteins, reducing mucus viscosity. It is used for patients with thick, tenacious secretions. It can cause bronchospasm and should be administered with a bronchodilator. It is also the antidote for acetaminophen overdose when given orally or IV.',
    difficulty: 2,
    topic: 'Pharmacology',
    isFree: false,
    orderIndex: 85,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the indications for exogenous surfactant therapy?',
    answer: 'Exogenous surfactant is indicated for neonatal respiratory distress syndrome (RDS) caused by surfactant deficiency in premature infants. It is administered endotracheally and reduces surface tension, improving compliance and preventing alveolar collapse. It can be given as prophylaxis or rescue therapy.',
    difficulty: 2,
    topic: 'Pharmacology',
    isFree: false,
    orderIndex: 86,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the difference between a metered-dose inhaler (MDI) and a dry powder inhaler (DPI) in terms of technique?',
    answer: 'An MDI requires slow, deep inhalation coordinated with actuation and a 10-second breath hold; a spacer improves delivery. A DPI requires fast, forceful inhalation to disperse the powder and does not need coordination with actuation. DPIs should never be used with a spacer, and patients should not exhale into the device.',
    difficulty: 2,
    topic: 'Pharmacology',
    isFree: false,
    orderIndex: 87,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the side effects of systemic corticosteroids used in acute asthma exacerbations?',
    answer: 'Short-term systemic corticosteroid side effects include hyperglycemia, fluid retention, mood changes, and increased infection risk. Long-term use can cause adrenal suppression, osteoporosis, cataracts, and immunosuppression. Oral prednisone or IV methylprednisolone courses are typically limited to 5-10 days to minimize these effects.',
    difficulty: 3,
    topic: 'Pharmacology',
    isFree: false,
    orderIndex: 88,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the role of dornase alfa (Pulmozyme) in respiratory therapy?',
    answer: 'Dornase alfa is a recombinant DNase enzyme that cleaves extracellular DNA in purulent secretions, reducing sputum viscosity. It is specifically indicated for cystic fibrosis patients to improve pulmonary function and reduce respiratory infections. Standard dose is 2.5 mg via nebulizer once daily.',
    difficulty: 3,
    topic: 'Pharmacology',
    isFree: false,
    orderIndex: 89,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the indications for inhaled nitric oxide (iNO)?',
    answer: 'Inhaled nitric oxide is a selective pulmonary vasodilator indicated for persistent pulmonary hypertension of the newborn (PPHN). It relaxes pulmonary vascular smooth muscle, reducing right-to-left shunting and improving oxygenation. Typical starting dose is 20 ppm. Methemoglobin and NO2 levels must be monitored.',
    difficulty: 3,
    topic: 'Pharmacology',
    isFree: false,
    orderIndex: 90,
  },

  // ============================================================
  // INFECTION CONTROL & EQUIPMENT (cards 91-100)
  // ============================================================
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the difference between sterilization and high-level disinfection?',
    answer: 'Sterilization destroys all microorganisms including bacterial spores (achieved by autoclaving, ethylene oxide gas, or plasma sterilization). High-level disinfection destroys all microorganisms except some bacterial spores (achieved by glutaraldehyde soaking or pasteurization). Semi-critical items require at least high-level disinfection.',
    difficulty: 1,
    topic: 'Infection Control & Equipment',
    isFree: false,
    orderIndex: 91,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How often should ventilator circuits be changed?',
    answer: 'Ventilator circuits should not be changed routinely on a schedule but only when visibly soiled or malfunctioning. Evidence shows that routine circuit changes (e.g., every 24-48 hours) do not reduce VAP rates and may actually increase infection risk by disrupting the circuit.',
    difficulty: 2,
    topic: 'Infection Control & Equipment',
    isFree: false,
    orderIndex: 92,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the components of a ventilator-associated pneumonia (VAP) prevention bundle?',
    answer: 'A VAP bundle includes: elevating the head of bed 30-45 degrees, daily sedation vacations with spontaneous breathing trials, peptic ulcer prophylaxis, DVT prophylaxis, daily oral care with chlorhexidine, and subglottic secretion drainage. These evidence-based interventions collectively reduce VAP incidence.',
    difficulty: 1,
    topic: 'Infection Control & Equipment',
    isFree: false,
    orderIndex: 93,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What type of isolation precautions are required for a patient with active pulmonary tuberculosis?',
    answer: 'Airborne precautions are required: the patient must be in a negative-pressure room with at least 6-12 air changes per hour. Healthcare workers must wear N95 respirators (or PAPRs) that have been fit-tested. Standard surgical masks are not sufficient for TB protection.',
    difficulty: 1,
    topic: 'Infection Control & Equipment',
    isFree: false,
    orderIndex: 94,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What is the Spaulding classification system for medical equipment?',
    answer: 'The Spaulding system classifies devices by infection risk: critical items (enter sterile tissue, require sterilization), semi-critical items (contact mucous membranes, require high-level disinfection), and noncritical items (contact intact skin, require low-level disinfection). Bronchoscopes are semi-critical; surgical instruments are critical.',
    difficulty: 2,
    topic: 'Infection Control & Equipment',
    isFree: false,
    orderIndex: 95,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How should heated humidifiers be managed to prevent infection?',
    answer: 'Heated humidifier water chambers should be filled with sterile distilled water, and condensate in the circuit tubing should be drained away from the patient (treated as contaminated waste). The water level should be maintained without breaking the circuit. Water traps should be emptied regularly.',
    difficulty: 2,
    topic: 'Infection Control & Equipment',
    isFree: false,
    orderIndex: 96,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'When should a healthcare worker perform hand hygiene according to the WHO "Five Moments"?',
    answer: 'The WHO Five Moments for Hand Hygiene are: (1) before touching a patient, (2) before a clean/aseptic procedure, (3) after body fluid exposure risk, (4) after touching a patient, and (5) after touching patient surroundings. Alcohol-based hand rub is preferred unless hands are visibly soiled.',
    difficulty: 1,
    topic: 'Infection Control & Equipment',
    isFree: false,
    orderIndex: 97,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What are the advantages of a heat-moisture exchanger (HME) over a heated humidifier for mechanically ventilated patients?',
    answer: 'HMEs are passive devices that capture exhaled heat and moisture and return it during inspiration. Advantages include lower cost, no external water source (reducing aspiration/infection risk), portability, and simplicity. Disadvantages include increased dead space, increased resistive work, and they are contraindicated with thick secretions or large air leaks.',
    difficulty: 3,
    topic: 'Infection Control & Equipment',
    isFree: false,
    orderIndex: 98,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'What personal protective equipment (PPE) is required for droplet precautions?',
    answer: 'Droplet precautions require a standard surgical mask worn within 3-6 feet of the patient, along with gloves and gown if contact with the patient or contaminated surfaces is anticipated. Eye protection is added if splashes are likely. Droplet precautions are used for influenza, pertussis, and meningococcal infections.',
    difficulty: 1,
    topic: 'Infection Control & Equipment',
    isFree: false,
    orderIndex: 99,
  },
  {
    divisionId: TMC_DIVISION_ID,
    question: 'How should reusable resuscitation bags (manual resuscitators) be processed between patients?',
    answer: 'Reusable manual resuscitators must be disassembled and undergo high-level disinfection or sterilization between patients, as they contact mucous membranes (semi-critical classification). Alternatively, single-use disposable bags can be used to eliminate reprocessing concerns. Bag valves and masks must be included in the processing.',
    difficulty: 2,
    topic: 'Infection Control & Equipment',
    isFree: false,
    orderIndex: 100,
  },
]

async function main() {
  console.log('Seeding TMC flashcards (batch 1)...')
  console.log(`Total cards: ${flashcards.length}`)

  // Verify the division exists
  const division = await prisma.division.findUnique({
    where: { id: TMC_DIVISION_ID },
  })

  if (!division) {
    console.error(
      `Division ${TMC_DIVISION_ID} not found. Run seed-divisions.ts first.`
    )
    process.exit(1)
  }

  console.log(`Found division: ${division.name}`)

  // Delete existing flashcards for this division to avoid duplicates on re-run
  const deleted = await prisma.flashcard.deleteMany({
    where: { divisionId: TMC_DIVISION_ID },
  })
  console.log(`Cleared ${deleted.count} existing flashcards for TMC division.`)

  // Insert all flashcards
  const result = await prisma.flashcard.createMany({
    data: flashcards,
  })

  console.log(`Successfully inserted ${result.count} TMC flashcards.`)

  // Log summary by topic
  const topicCounts: Record<string, number> = {}
  const difficultyCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0 }
  let freeCount = 0

  for (const card of flashcards) {
    topicCounts[card.topic] = (topicCounts[card.topic] || 0) + 1
    difficultyCounts[card.difficulty]++
    if (card.isFree) freeCount++
  }

  console.log('\n--- Summary ---')
  console.log('By topic:')
  for (const [topic, count] of Object.entries(topicCounts)) {
    console.log(`  ${topic}: ${count} cards`)
  }
  console.log('By difficulty:')
  console.log(`  Easy (1): ${difficultyCounts[1]}`)
  console.log(`  Medium (2): ${difficultyCounts[2]}`)
  console.log(`  Hard (3): ${difficultyCounts[3]}`)
  console.log(`Free cards: ${freeCount}`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
