import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding RPFT flashcards batch 2 (cards 101-200)...')

  await prisma.flashcard.createMany({
    data: [
      // --- Advanced Cardiopulmonary Exercise Testing (CPET) ---
      {
        question: 'What is the gold-standard method for determining anaerobic threshold (AT) during CPET?',
        answer: 'The V-slope method, which identifies the inflection point where VCO2 begins to increase disproportionately relative to VO2 due to buffering of lactic acid by bicarbonate.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 101,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What does the VE/VCO2 slope represent during CPET, and what value suggests an abnormal ventilatory response?',
        answer: 'The VE/VCO2 slope represents ventilatory efficiency — how much ventilation is required to eliminate a given amount of CO2. A slope greater than 34 is generally considered abnormal, and values above 45 indicate severe ventilatory inefficiency, often seen in heart failure or pulmonary vascular disease.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 102,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is O2 pulse calculated during CPET, and what does it physiologically represent?',
        answer: 'O2 pulse = VO2 / heart rate. It represents the volume of oxygen extracted per heartbeat and serves as a noninvasive surrogate for stroke volume. A plateau or decline in O2 pulse during progressive exercise may indicate cardiac limitation.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 103,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the four major categories of exercise limitation identified by CPET?',
        answer: 'Cardiovascular limitation, ventilatory (pulmonary) limitation, deconditioning/peripheral muscle limitation, and poor effort or symptom limitation. Each has distinct patterns on the nine-panel plot of CPET data.',
        difficulty: 1,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 104,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'During CPET, what breathing reserve value suggests ventilatory limitation as the cause of exercise intolerance?',
        answer: 'A breathing reserve (BR) less than 15-20% suggests ventilatory limitation. BR is calculated as (MVV - peak VE) / MVV x 100. Normal subjects typically have a BR of 20-40% at peak exercise, meaning they do not approach their ventilatory ceiling.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 105,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the respiratory exchange ratio (RER), and what RER value at peak exercise indicates maximal effort?',
        answer: 'RER = VCO2 / VO2 measured at the mouth. A peak RER greater than or equal to 1.10 is widely accepted as an indicator of maximal effort. Values above 1.0 reflect CO2 production exceeding O2 consumption due to bicarbonate buffering of lactic acid.',
        difficulty: 1,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 106,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the respiratory compensation point (RCP) during CPET, and how is it identified?',
        answer: 'The RCP is the point during exercise above the anaerobic threshold where ventilation increases disproportionately relative to VCO2 due to respiratory compensation for metabolic acidosis. It is identified when VE/VCO2 begins to rise after a period of relative stability (nadir), or from a second breakpoint on the VE vs. VCO2 plot.',
        difficulty: 3,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 107,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does a cardiovascular limitation pattern present on CPET?',
        answer: 'Low peak VO2, low anaerobic threshold (typically less than 40% predicted VO2max), abnormal O2 pulse plateau or decline, adequate breathing reserve (greater than 20%), abnormal heart rate response or early achievement of predicted max HR, and potentially exercise-induced ECG changes or arrhythmias.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 108,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the normal range for the VE/VCO2 nadir, and in what conditions is it characteristically elevated?',
        answer: 'The normal VE/VCO2 nadir is typically 25-30. It is characteristically elevated in pulmonary hypertension, heart failure with reduced ejection fraction, interstitial lung disease, and chronic thromboembolic pulmonary hypertension (CTEPH). The elevation reflects increased dead space ventilation or ventilation-perfusion mismatch.',
        difficulty: 3,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 109,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is exercise oscillatory ventilation (EOV), and what is its clinical significance?',
        answer: 'EOV is a cyclical fluctuation in minute ventilation during exercise with an amplitude greater than 15% of the mean and a cycle length of 40-100 seconds. It is associated with heart failure and indicates poor prognosis. It reflects circulatory delay and instability in the chemoreflex feedback loop controlling ventilation.',
        difficulty: 3,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 110,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is dead space ventilation (VD/VT) estimated during CPET, and what does failure to decrease normally during exercise indicate?',
        answer: 'VD/VT can be estimated using the modified Bohr equation: VD/VT = (PaCO2 - PETCO2) / PaCO2. Normally VD/VT decreases from approximately 0.30-0.35 at rest to 0.15-0.20 at peak exercise. Failure to decrease or an increase during exercise suggests pulmonary vascular disease or significant ventilation-perfusion mismatch.',
        difficulty: 3,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 111,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What work rate protocol is most commonly used for diagnostic CPET on a cycle ergometer?',
        answer: 'An individualized ramp protocol targeting 8-12 minutes of incremental exercise. The work rate increment per minute is estimated using: increment = (predicted peak VO2 - unloaded VO2) / 10, where unloaded VO2 is approximately 500 mL/min. This typically yields 10-30 watt/min ramp rates depending on the patient.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 112,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the expected VO2-work rate relationship during a ramp CPET protocol, and what does a plateau or flattening suggest?',
        answer: 'VO2 normally increases linearly with work rate at approximately 10 mL/min/watt during cycle ergometry. A plateau or flattening of the VO2-work rate relationship near peak exercise may indicate true VO2max achievement. A lower-than-expected slope throughout exercise suggests cardiovascular limitation or peripheral O2 extraction impairment.',
        difficulty: 3,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 113,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- High-Altitude and Environmental Physiology ---
      {
        question: 'What is the alveolar gas equation, and how is it used to calculate PAO2 at altitude?',
        answer: 'PAO2 = FIO2 x (PB - PH2O) - (PaCO2 / R). At altitude, barometric pressure (PB) decreases, reducing FIO2 x (PB - 47), which directly lowers PAO2. For example, at 10,000 feet (PB ~523 mmHg), PAO2 = 0.21 x (523 - 47) - (40/0.8) = approximately 50 mmHg.',
        difficulty: 2,
        topic: 'High-Altitude and Environmental Physiology',
        isFree: false,
        orderIndex: 114,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What physiological adaptations occur during acclimatization to high altitude?',
        answer: 'Hyperventilation (lowering PaCO2 to raise PAO2), increased 2,3-DPG shifting the oxyhemoglobin dissociation curve rightward, polycythemia (increased erythropoietin production), increased cardiac output initially, pulmonary vasoconstriction, and renal bicarbonate excretion to compensate for respiratory alkalosis.',
        difficulty: 1,
        topic: 'High-Altitude and Environmental Physiology',
        isFree: false,
        orderIndex: 115,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does the hypoxic ventilatory response (HVR) test assess a patient\'s suitability for high-altitude travel?',
        answer: 'HVR measures the increase in minute ventilation in response to progressive isocapnic hypoxia. A brisk HVR (large increase in VE per decrease in SpO2 or PaO2) suggests better tolerance to altitude. A blunted HVR is associated with increased risk of altitude illness. The test involves breathing progressive hypoxic gas mixtures while maintaining PETCO2 constant.',
        difficulty: 3,
        topic: 'High-Altitude and Environmental Physiology',
        isFree: false,
        orderIndex: 116,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the hypoxia altitude simulation test (HAST), and when is it indicated?',
        answer: 'The HAST involves breathing 15.1% FIO2 (simulating 8,000 ft cabin altitude) for 20 minutes while monitoring SpO2 and symptoms. It is indicated for patients with baseline pulmonary disease planning air travel. Supplemental O2 is recommended if PaO2 falls below 50 mmHg or SpO2 below 85% during the test.',
        difficulty: 2,
        topic: 'High-Altitude and Environmental Physiology',
        isFree: false,
        orderIndex: 117,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What effect does cold air have on airway responsiveness during pulmonary function testing?',
        answer: 'Cold air can provoke bronchospasm, particularly in patients with exercise-induced bronchoconstriction (EIB) or asthma. Eucapnic voluntary hyperventilation (EVH) with cold dry air is used as a bronchoprovocation test. Breathing cold air increases airway heat and water loss, triggering osmotic changes in the airway surface liquid that activate mast cells and cause bronchoconstriction.',
        difficulty: 2,
        topic: 'High-Altitude and Environmental Physiology',
        isFree: false,
        orderIndex: 118,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- Metabolic Measurements ---
      {
        question: 'What is indirect calorimetry, and what two gas measurements does it require?',
        answer: 'Indirect calorimetry estimates energy expenditure by measuring oxygen consumption (VO2) and carbon dioxide production (VCO2). Using the Weir equation, REE (kcal/day) = [3.941 x VO2 (L/min) + 1.106 x VCO2 (L/min)] x 1440. It assumes negligible protein oxidation contribution.',
        difficulty: 1,
        topic: 'Metabolic Measurements',
        isFree: false,
        orderIndex: 119,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is a steady-state condition during indirect calorimetry, and why is it important?',
        answer: 'Steady state is achieved when VO2 and VCO2 vary by less than 10% (some protocols use 5%) over a 5-minute period. It ensures that measured gas exchange accurately reflects metabolic substrate utilization. Without steady state, CO2 storage or release from body buffering pools may invalidate RQ and caloric calculations.',
        difficulty: 2,
        topic: 'Metabolic Measurements',
        isFree: false,
        orderIndex: 120,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What respiratory quotient (RQ) values correspond to the oxidation of carbohydrates, fats, and proteins?',
        answer: 'Carbohydrates: RQ = 1.0. Fats: RQ = 0.70. Proteins: RQ = 0.80. A mixed diet typically yields an RQ of 0.80-0.85. An RQ greater than 1.0 indicates lipogenesis (overfeeding), and an RQ below 0.70 suggests a measurement error or ketogenesis.',
        difficulty: 1,
        topic: 'Metabolic Measurements',
        isFree: false,
        orderIndex: 121,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What factors can cause measurement errors during indirect calorimetry?',
        answer: 'Air leaks in the circuit or around the canopy/mask, supplemental oxygen use (invalidates standard calculations), hyperventilation (CO2 washout falsely elevates RQ), patient agitation or non-steady state, recent physical activity, FIO2 greater than 0.60 causing analyzer inaccuracy, and temperature drift of gas analyzers.',
        difficulty: 2,
        topic: 'Metabolic Measurements',
        isFree: false,
        orderIndex: 122,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How should a patient be prepared for a resting energy expenditure (REE) measurement?',
        answer: 'The patient should fast for at least 4-5 hours (12 hours preferred), rest supine in a thermoneutral environment for 30 minutes before testing, avoid caffeine and nicotine for at least 4 hours, and be free from acute illness or fever. The room should be quiet and dimly lit to minimize stimulation. Sedatives should be avoided if possible.',
        difficulty: 1,
        topic: 'Metabolic Measurements',
        isFree: false,
        orderIndex: 123,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- Advanced Bronchial Challenge Interpretation ---
      {
        question: 'How is PC20 calculated from a methacholine challenge dose-response curve?',
        answer: 'PC20 is the provocative concentration causing a 20% fall in FEV1. It is calculated by log-linear interpolation between the last two concentrations (C1 and C2) using: log PC20 = log C1 + [(log C2 - log C1) x (20 - %fall after C1) / (%fall after C2 - %fall after C1)]. C1 is the second-to-last dose and C2 is the dose causing greater than 20% fall.',
        difficulty: 3,
        topic: 'Advanced Bronchial Challenge',
        isFree: false,
        orderIndex: 124,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the severity classifications for methacholine PC20 values?',
        answer: 'Borderline bronchial hyperresponsiveness (BHR): PC20 4-16 mg/mL. Mild BHR: PC20 1-4 mg/mL. Moderate BHR: PC20 0.25-1 mg/mL. Severe BHR: PC20 less than 0.25 mg/mL. A PC20 greater than 16 mg/mL is considered a negative test. These thresholds apply to the standardized five-breath dosimeter protocol.',
        difficulty: 2,
        topic: 'Advanced Bronchial Challenge',
        isFree: false,
        orderIndex: 125,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the difference between sensitivity and reactivity on a dose-response curve for bronchial provocation?',
        answer: 'Sensitivity refers to the position of the curve on the dose axis (how little stimulus is needed to initiate a response), reflected by the threshold dose or PC20. Reactivity refers to the slope of the dose-response curve (how rapidly FEV1 falls once the response begins). A plateau in the dose-response curve indicates a maximal response, which is typically present in normal subjects but absent in severe asthma.',
        difficulty: 3,
        topic: 'Advanced Bronchial Challenge',
        isFree: false,
        orderIndex: 126,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What medications must be withheld before methacholine challenge testing, and for how long?',
        answer: 'Short-acting bronchodilators: 8 hours. Long-acting beta-agonists (LABA): 48 hours. Ultra-long-acting beta-agonists (e.g., indacaterol): 72 hours. Long-acting muscarinic antagonists: 1 week. Leukotriene modifiers: 24 hours. Antihistamines: 72 hours. Inhaled corticosteroids may blunt the response but do not need to be withheld unless clinically appropriate.',
        difficulty: 2,
        topic: 'Advanced Bronchial Challenge',
        isFree: false,
        orderIndex: 127,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is eucapnic voluntary hyperventilation (EVH), and for what condition is it considered the gold standard provocation test?',
        answer: 'EVH involves the patient hyperventilating dry air containing 5% CO2 (to maintain eucapnia) at 85% of MVV for 6 minutes. It is considered the gold standard for diagnosing exercise-induced bronchoconstriction (EIB). A positive test is a fall in FEV1 of 10% or greater from baseline measured at intervals post-challenge.',
        difficulty: 2,
        topic: 'Advanced Bronchial Challenge',
        isFree: false,
        orderIndex: 128,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the difference between a direct and indirect bronchial provocation test?',
        answer: 'Direct tests (methacholine, histamine) act directly on airway smooth muscle receptors causing bronchoconstriction. Indirect tests (mannitol, EVH, exercise, hypertonic saline) trigger bronchoconstriction through release of mediators from inflammatory cells in the airway. Indirect tests are more specific for active airway inflammation and better predict response to anti-inflammatory therapy.',
        difficulty: 1,
        topic: 'Advanced Bronchial Challenge',
        isFree: false,
        orderIndex: 129,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is a mannitol challenge test, and what defines a positive result?',
        answer: 'The mannitol challenge uses inhaled dry powder mannitol in escalating doses (0, 5, 10, 20, 40, 80, 160, 160, 160 mg). The test is positive if FEV1 falls by 15% or more from baseline, or if there is a cumulative 10% fall in FEV1 between consecutive doses. It is an indirect challenge that identifies active airway inflammation and exercise-induced bronchoconstriction.',
        difficulty: 2,
        topic: 'Advanced Bronchial Challenge',
        isFree: false,
        orderIndex: 130,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- Respiratory Mechanics ---
      {
        question: 'How is static lung compliance (Cst) measured, and what are normal values?',
        answer: 'Static compliance is measured using an esophageal balloon to estimate pleural pressure. Cst = change in volume / change in transpulmonary pressure at points of zero flow (during step deflation from TLC). Normal Cst is approximately 200 mL/cmH2O. It is increased in emphysema (loss of elastic recoil) and decreased in pulmonary fibrosis.',
        difficulty: 3,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 131,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the difference between static and dynamic lung compliance?',
        answer: 'Static compliance (Cst) is measured at points of zero airflow and reflects only elastic properties of the lung. Dynamic compliance (Cdyn) is measured during tidal breathing and includes both elastic and resistive components. Frequency dependence of compliance — where Cdyn decreases at higher breathing rates — indicates small airway disease because affected regions fill and empty with longer time constants.',
        difficulty: 2,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 132,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is airway resistance measured by the interrupter technique (Rint)?',
        answer: 'The interrupter technique briefly occludes airflow (for approximately 100 ms) during tidal breathing using a shutter valve. Mouth pressure measured during the interruption equilibrates with alveolar pressure. Rint is calculated from the ratio of this pressure to the flow measured immediately before interruption. It is effort-independent and useful in children and uncooperative patients.',
        difficulty: 2,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 133,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the work of breathing, and what are the two main components?',
        answer: 'Work of breathing (WOB) is the energy expended to move air in and out of the lungs. It has two components: elastic work (overcoming lung and chest wall elastic recoil, dominant at low frequencies) and resistive work (overcoming airway and tissue resistance, dominant at high frequencies). Total WOB is measured from pressure-volume loops using esophageal manometry. Normal resting WOB is 0.3-0.6 joules per liter.',
        difficulty: 2,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 134,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the time constant of the respiratory system, and how is it calculated?',
        answer: 'The time constant (tau) = Resistance x Compliance. It represents the time required for 63% of the volume change to occur during passive inflation or deflation. Three time constants allow approximately 95% of the volume change. A prolonged time constant (as in COPD with high resistance and compliance) leads to air trapping and dynamic hyperinflation.',
        difficulty: 3,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 135,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the forced oscillation technique (FOT), and what does it measure?',
        answer: 'FOT applies small-amplitude pressure oscillations at the airway opening during tidal breathing and measures the resulting flow to determine respiratory impedance (Zrs). Impedance has two components: resistance (Rrs, in-phase with flow) and reactance (Xrs, out-of-phase). It is effort-independent, requires only tidal breathing, and can detect peripheral airway obstruction through frequency dependence of resistance and decreased reactance at lower frequencies.',
        difficulty: 3,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 136,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is intrinsic PEEP (PEEPi or auto-PEEP), and how can it be detected in the PFT lab?',
        answer: 'Intrinsic PEEP is positive end-expiratory alveolar pressure caused by incomplete exhalation before the next breath begins. In the PFT lab, it can be detected by examining the flow-volume loop for failure to return to zero flow before the next inspiration, by measuring end-expiratory esophageal pressure, or by noting that inspiratory effort must first overcome PEEPi before generating inspiratory flow. It is common in severe COPD.',
        difficulty: 3,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 137,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What does the maximal inspiratory pressure (MIP) measure, and what are normal values for adults?',
        answer: 'MIP (also called PImax) measures the maximum pressure generated during a forceful inspiratory effort against an occluded airway at RV or FRC. It reflects inspiratory muscle strength, primarily the diaphragm. Normal values: males greater than -80 cmH2O, females greater than -60 cmH2O (more negative values indicate stronger muscles). A sustained 1-second plateau pressure is preferred for reproducibility.',
        difficulty: 1,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 138,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the sniff nasal inspiratory pressure (SNIP), and when is it preferred over MIP?',
        answer: 'SNIP measures peak nasal pressure during a maximal sniff from FRC through one occluded nostril while the other remains patent. It is preferred when patients cannot form a tight seal on a mouthpiece (e.g., neuromuscular disease with facial weakness), as the sniff maneuver is more natural. Normal SNIP is greater than 70 cmH2O in males and greater than 60 cmH2O in females.',
        difficulty: 2,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 139,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the clinical significance of the maximal expiratory pressure (MEP)?',
        answer: 'MEP (PEmax) measures maximal expiratory muscle strength (primarily abdominals and intercostals) against an occluded airway at TLC. Normal values: males greater than 100 cmH2O, females greater than 80 cmH2O. Reduced MEP indicates expiratory muscle weakness, which impairs cough effectiveness and secretion clearance. It is important in neuromuscular disease assessment and preoperative evaluation.',
        difficulty: 1,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 140,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- Preoperative Pulmonary Assessment ---
      {
        question: 'What is the predicted postoperative FEV1 (ppo-FEV1), and how is it calculated for pneumonectomy?',
        answer: 'ppo-FEV1 estimates the FEV1 remaining after surgical resection. For pneumonectomy: ppo-FEV1 = preoperative FEV1 x (1 - fraction of total perfusion to the resected lung, determined by quantitative perfusion lung scan). A ppo-FEV1 less than 40% predicted (or less than 0.8 L) indicates high surgical risk.',
        difficulty: 2,
        topic: 'Preoperative Pulmonary Assessment',
        isFree: false,
        orderIndex: 141,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT values suggest a patient can undergo lung resection surgery without further cardiopulmonary testing?',
        answer: 'If both preoperative FEV1 and DLCO are greater than 80% predicted, the patient is generally considered low risk and can proceed to surgery without additional testing. If either FEV1 or DLCO is less than 80% predicted, predicted postoperative values should be calculated, and CPET may be indicated if ppo values are borderline.',
        difficulty: 1,
        topic: 'Preoperative Pulmonary Assessment',
        isFree: false,
        orderIndex: 142,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the role of CPET in preoperative assessment for lung resection, and what VO2max threshold indicates prohibitive risk?',
        answer: 'CPET is indicated when predicted postoperative FEV1 or DLCO falls below 40-60% predicted. A peak VO2 greater than 20 mL/kg/min indicates low risk. A peak VO2 of 10-20 mL/kg/min indicates moderate risk requiring shared decision-making. A peak VO2 less than 10 mL/kg/min (or less than 35% predicted) indicates very high risk and is often considered prohibitive for major resection.',
        difficulty: 2,
        topic: 'Preoperative Pulmonary Assessment',
        isFree: false,
        orderIndex: 143,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is predicted postoperative DLCO (ppo-DLCO) calculated for lobectomy?',
        answer: 'For lobectomy, ppo-DLCO = preoperative DLCO x (1 - number of functional segments removed / total number of functional segments). The number of functional segments is determined by CT or perfusion scanning. For example, if 3 segments are removed from a total of 19 functional segments: ppo-DLCO = preop DLCO x (1 - 3/19).',
        difficulty: 3,
        topic: 'Preoperative Pulmonary Assessment',
        isFree: false,
        orderIndex: 144,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the stair-climbing test in preoperative assessment, and what distance correlates with acceptable surgical risk?',
        answer: 'The stair-climbing test is a simple functional assessment where the patient climbs stairs at their own pace. Climbing more than 22 meters (approximately 5 flights) correlates with a peak VO2 greater than 20 mL/kg/min and low surgical risk. Inability to climb 1-2 flights suggests high risk. It serves as a screening tool when formal CPET is not available.',
        difficulty: 1,
        topic: 'Preoperative Pulmonary Assessment',
        isFree: false,
        orderIndex: 145,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- Advanced Blood Gas Analysis ---
      {
        question: 'How is the A-a gradient (P(A-a)O2) calculated, and what is the normal expected value adjusted for age?',
        answer: 'P(A-a)O2 = PAO2 - PaO2, where PAO2 is calculated from the alveolar gas equation. The normal A-a gradient on room air increases with age and is estimated by: (Age/4) + 4 mmHg. A widened A-a gradient indicates V/Q mismatch, shunt, or diffusion impairment. A normal A-a gradient with hypoxemia suggests hypoventilation or low FIO2.',
        difficulty: 1,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 146,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is the intrapulmonary shunt fraction (Qs/Qt) calculated?',
        answer: 'Qs/Qt = (CcO2 - CaO2) / (CcO2 - CvO2), where CcO2 is end-capillary oxygen content (calculated assuming full equilibration with PAO2), CaO2 is arterial oxygen content, and CvO2 is mixed venous oxygen content (from pulmonary artery catheter). A shunt fraction greater than 10% is abnormal. True shunt (Qs/Qt) does not improve with supplemental oxygen, unlike V/Q mismatch.',
        difficulty: 3,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 147,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the a/A ratio, and why is it preferred over the A-a gradient at high FIO2?',
        answer: 'The a/A ratio = PaO2 / PAO2. Unlike the A-a gradient, the a/A ratio remains relatively stable across different FIO2 levels, making it more useful for tracking gas exchange efficiency when FIO2 changes. Normal a/A ratio is greater than 0.77. A low a/A ratio indicates impaired gas exchange. The A-a gradient increases nonlinearly with FIO2, making serial comparisons unreliable.',
        difficulty: 2,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 148,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the PaO2/FIO2 (P/F) ratio, and what values define ARDS severity?',
        answer: 'The P/F ratio = PaO2 / FIO2. It is used to categorize the severity of ARDS: Mild ARDS: P/F 200-300 mmHg. Moderate ARDS: P/F 100-200 mmHg. Severe ARDS: P/F less than 100 mmHg. Normal P/F ratio on room air is approximately 400-500 mmHg. The ratio must be measured with a PEEP of at least 5 cmH2O for ARDS classification.',
        difficulty: 1,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 149,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How do you calculate oxygen content (CaO2) from arterial blood gas data?',
        answer: 'CaO2 = (1.34 x Hb x SaO2) + (0.003 x PaO2). The first term represents oxygen bound to hemoglobin (the major component), and the second term represents dissolved oxygen. For example, with Hb 15 g/dL, SaO2 98%, PaO2 95 mmHg: CaO2 = (1.34 x 15 x 0.98) + (0.003 x 95) = 19.70 + 0.29 = 19.99 mL O2/dL.',
        difficulty: 1,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 150,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the clinical significance of a P(a-ET)CO2 gradient, and what does a negative value indicate?',
        answer: 'The P(a-ET)CO2 gradient is PaCO2 minus PETCO2. Normally it is 2-5 mmHg (PaCO2 slightly exceeds PETCO2 due to dead space dilution). An increased gradient suggests increased dead space ventilation (e.g., pulmonary embolism). A negative gradient (PETCO2 exceeds PaCO2) can occur during exercise in normal subjects, during rebreathing, or when there are large intrapulmonary shunts causing mixed venous CO2 to reach the exhaled gas.',
        difficulty: 3,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 151,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the Henderson-Hasselbalch equation components, and how is expected PaCO2 compensation calculated in metabolic acidosis?',
        answer: 'pH = 6.1 + log([HCO3-] / (0.03 x PaCO2)). In metabolic acidosis, the expected respiratory compensation (Winter formula) is: expected PaCO2 = (1.5 x HCO3-) + 8 (plus or minus 2). If measured PaCO2 is lower than expected, a concurrent respiratory alkalosis is present. If PaCO2 is higher than expected, a concurrent respiratory acidosis is present.',
        difficulty: 2,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 152,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the oxygen extraction ratio (O2ER), and what does an elevated value indicate?',
        answer: 'O2ER = (CaO2 - CvO2) / CaO2, or approximately (SaO2 - SvO2) / SaO2. Normal O2ER is 22-30%. An elevated O2ER (greater than 30%) indicates that tissues are extracting a greater-than-normal fraction of delivered oxygen, suggesting inadequate oxygen delivery relative to metabolic demand — as seen in low cardiac output states, severe anemia, or shock.',
        difficulty: 2,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 153,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- Research Methodology and Statistics ---
      {
        question: 'What is the coefficient of variation (CV), and how is it used in PFT quality assurance?',
        answer: 'CV = (standard deviation / mean) x 100%. In PFT labs, CV is used to assess the reproducibility of measurements and analyzer performance. For example, a biologic control performing daily spirometry should have a CV of less than 5% for FEV1 and FVC to confirm instrument stability. A rising CV triggers equipment review and recalibration.',
        difficulty: 1,
        topic: 'Research Methodology and Statistics',
        isFree: false,
        orderIndex: 154,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the difference between accuracy and precision in PFT measurement?',
        answer: 'Accuracy refers to how close a measurement is to the true value (e.g., a 3-L syringe reading as 3.0 L). Precision (reproducibility) refers to how close repeated measurements are to each other, regardless of the true value. A spirometer can be precise but inaccurate (consistently reads 2.9 L for a 3.0 L syringe), or accurate but imprecise (readings scatter around 3.0 L). Quality PFT requires both.',
        difficulty: 1,
        topic: 'Research Methodology and Statistics',
        isFree: false,
        orderIndex: 155,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What statistical test is most appropriate for comparing FEV1 values before and after an intervention in the same group of patients?',
        answer: 'A paired t-test (if data are normally distributed) or a Wilcoxon signed-rank test (if data are not normally distributed). These are used because the measurements are paired — each subject serves as their own control, and the analysis examines within-subject differences. An unpaired t-test would be incorrect because it ignores the paired structure.',
        difficulty: 2,
        topic: 'Research Methodology and Statistics',
        isFree: false,
        orderIndex: 156,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is a Bland-Altman plot, and how is it used in PFT research?',
        answer: 'A Bland-Altman plot graphs the difference between two measurements (or two methods) against their mean. It is used to assess agreement between methods — for example, comparing DLCO values from two different devices. The plot shows systematic bias (mean difference), limits of agreement (mean difference plus or minus 1.96 SD), and whether discrepancies vary with the magnitude of measurement. It is preferred over correlation for method comparison.',
        difficulty: 3,
        topic: 'Research Methodology and Statistics',
        isFree: false,
        orderIndex: 157,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the lower limit of normal (LLN), and why is it preferred over a fixed percentage of predicted for defining abnormality?',
        answer: 'The LLN is typically defined as the 5th percentile of the distribution in a healthy reference population (1.645 standard deviations below the predicted mean). It accounts for age, sex, height, and race-specific variability. A fixed percentage (e.g., FEV1/FVC less than 70%) misclassifies healthy elderly (false positives) and young adults with early disease (false negatives) because it ignores the natural decline with aging.',
        difficulty: 1,
        topic: 'Research Methodology and Statistics',
        isFree: false,
        orderIndex: 158,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the GLI-2012 reference equations, and what advantage do they offer over prior reference sets?',
        answer: 'The Global Lung Initiative 2012 (GLI-2012) equations are multi-ethnic spirometry reference equations covering ages 3-95 using Lambda-Mu-Sigma (LMS) methodology. They model the distribution of lung function as it varies with age, height, sex, and ethnicity. Advantages include continuous equations across all ages (no breakpoints at age transitions), z-score-based interpretation, and a single consistent reference set replacing multiple population-specific equations.',
        difficulty: 2,
        topic: 'Research Methodology and Statistics',
        isFree: false,
        orderIndex: 159,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What does a z-score of -2.5 for FEV1 mean in clinical interpretation?',
        answer: 'A z-score of -2.5 means the patient FEV1 is 2.5 standard deviations below the predicted mean for their reference group. This falls well below the LLN (z-score of -1.645, representing the 5th percentile) and indicates moderately severe reduction. Z-scores allow standardized comparison across different parameters, ages, and ethnic groups regardless of the absolute units.',
        difficulty: 2,
        topic: 'Research Methodology and Statistics',
        isFree: false,
        orderIndex: 160,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the purpose of a biologic control program in a PFT laboratory?',
        answer: 'A biologic control program uses healthy, nonsmoking laboratory staff who perform PFT measurements (typically spirometry and DLCO) at regular intervals to monitor instrument performance over time. It detects gradual drift or sudden shifts that mechanical quality control (syringe checks) may miss. Measurements are plotted on control charts, and deviations beyond 2 SD or trends trigger investigation of equipment or technique.',
        difficulty: 1,
        topic: 'Research Methodology and Statistics',
        isFree: false,
        orderIndex: 161,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the minimal clinically important difference (MCID) for FEV1 in COPD?',
        answer: 'The MCID for FEV1 in COPD is generally accepted as 100-140 mL (absolute change). This represents the smallest change that is perceived as meaningful by patients and clinicians, beyond statistical significance. The MCID helps interpret treatment effects in clinical trials — a statistically significant change smaller than the MCID may not be clinically relevant.',
        difficulty: 2,
        topic: 'Research Methodology and Statistics',
        isFree: false,
        orderIndex: 162,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- Occupational and Disability Testing ---
      {
        question: 'What PFT parameters are required for AMA impairment rating of respiratory disability?',
        answer: 'The AMA Guides require: FVC, FEV1, FEV1/FVC ratio, DLCO, and in some cases, VO2max from CPET. Impairment is classified into four severity classes based on the most abnormal parameter. Class 1 (mild): FVC 65-79%, FEV1 65-79%, DLCO 61-79%. Class 4 (severe): FVC less than 50%, FEV1 less than 40%, DLCO less than 40%. Exercise testing with peak VO2 measurement may be needed for borderline cases.',
        difficulty: 2,
        topic: 'Occupational and Disability Testing',
        isFree: false,
        orderIndex: 163,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is a serial PFT monitoring program for occupational exposure, and what rate of FEV1 decline is considered excessive?',
        answer: 'Serial monitoring involves performing spirometry at baseline and at regular intervals (annually or more frequently) to detect accelerated decline in workers exposed to respiratory hazards. Normal age-related FEV1 decline is 20-30 mL/year. Excessive decline is defined as greater than 60 mL/year (longitudinal limit of decline). The ATS recommends using within-person year-to-year variability (about 15%) as the threshold for significant change.',
        difficulty: 2,
        topic: 'Occupational and Disability Testing',
        isFree: false,
        orderIndex: 164,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What specific PFT findings are characteristic of occupational asthma, and how is the diagnosis confirmed?',
        answer: 'Characteristic findings include: variable airflow obstruction with work-related patterns (declines in FEV1 or peak flow during work shifts and improvement away from work), bronchial hyperresponsiveness (positive methacholine challenge), and cross-shift FEV1 decline of 10% or more. Diagnosis is confirmed by specific inhalation challenge (SIC) in a controlled laboratory exposing the patient to the suspected workplace agent while monitoring FEV1.',
        difficulty: 3,
        topic: 'Occupational and Disability Testing',
        isFree: false,
        orderIndex: 165,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the role of serial peak expiratory flow (PEF) monitoring in diagnosing occupational asthma?',
        answer: 'Serial PEF monitoring involves the worker recording PEF at least 4 times daily for at least 2 weeks at work and 2 weeks away from work. A work-related pattern shows decreased PEF during work periods with recovery during time off. A diurnal PEF variability greater than 20% supports asthma diagnosis. Computer programs (like OASYS) can objectively analyze the records for work-relatedness patterns.',
        difficulty: 2,
        topic: 'Occupational and Disability Testing',
        isFree: false,
        orderIndex: 166,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT pattern is typically seen in asbestosis?',
        answer: 'Asbestosis typically presents as a restrictive pattern: reduced FVC and TLC with preserved or elevated FEV1/FVC ratio, and reduced DLCO. The DLCO is often reduced out of proportion to the volume loss, reflecting diffuse interstitial fibrosis affecting gas exchange. Exercise desaturation may occur before resting values become abnormal. Pleural disease alone (plaques, thickening) may cause mild restriction without reduced DLCO.',
        difficulty: 1,
        topic: 'Occupational and Disability Testing',
        isFree: false,
        orderIndex: 167,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What spirometry quality standards must be met for tests used in occupational surveillance programs?',
        answer: 'The test must meet ATS/ERS acceptability and repeatability criteria: at least 3 acceptable maneuvers with good start of test (back-extrapolated volume less than 5% of FVC or 150 mL), adequate duration (EOFE plateau or 15 seconds), no artifacts (cough, glottic closure, early termination), and repeatability of the two largest FVC and FEV1 values within 150 mL. The technician must document maneuver quality, and equipment must pass daily calibration verification.',
        difficulty: 1,
        topic: 'Occupational and Disability Testing',
        isFree: false,
        orderIndex: 168,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- Complex Case Interpretation ---
      {
        question: 'A patient has reduced FVC, reduced TLC, normal FEV1/FVC, and severely reduced DLCO. Lung volumes by plethysmography show normal TLC. What is the most likely explanation?',
        answer: 'This pattern suggests a nonspecific or mixed pattern with gas trapping. The discrepancy between reduced TLC by gas dilution (suggested by reduced FVC) and normal plethysmographic TLC indicates trapped gas that is not communicating with the airways during helium dilution. Combined with severely reduced DLCO, this pattern can be seen in emphysema with air trapping, or combined obstructive-restrictive disease where obstruction leads to underestimation of lung volumes by dilution methods.',
        difficulty: 3,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 169,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How do you differentiate between pulmonary vascular disease and interstitial lung disease when both show reduced DLCO and exercise desaturation?',
        answer: 'In pulmonary vascular disease: lung volumes (TLC, FVC) are often normal or only mildly reduced, FEV1/FVC is normal, DLCO is reduced out of proportion to any volume loss, and CPET shows high VE/VCO2 slope with widened VD/VT. In ILD: lung volumes are proportionally reduced (restrictive pattern), DLCO is reduced in proportion to volume loss, and CPET shows ventilatory limitation with reduced breathing reserve. CT imaging and echocardiography further distinguish them.',
        difficulty: 3,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 170,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A patient shows normal spirometry, normal lung volumes, normal DLCO at rest, but desaturates to SpO2 86% during a 6-minute walk test. What conditions should be considered?',
        answer: 'Consider early interstitial lung disease (before resting PFT abnormalities develop), pulmonary arteriovenous malformations (right-to-left shunt increasing with exercise), early pulmonary hypertension, hepatopulmonary syndrome (platypnea-orthodeoxia), patent foramen ovale with right-to-left shunting during exercise (increased right atrial pressure), or occult cardiac shunt. Exercise DLCO, contrast echocardiography, and right heart catheterization may help differentiate.',
        difficulty: 3,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 171,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the significance of a reduced DLCO with increased KCO (DLCO/VA)?',
        answer: 'A reduced DLCO with elevated KCO occurs when lung volume is reduced but the remaining lung parenchyma is normal or hyperperfused — classically seen in pneumonectomy, lobectomy, neuromuscular disease with low TLC, chest wall restriction, or suboptimal inspiration during testing. The high KCO indicates that the available alveolar-capillary membrane functions normally or has increased capillary blood volume per unit of ventilated lung.',
        difficulty: 3,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 172,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does the pattern of DLCO change in pulmonary hemorrhage compared to other causes of reduced DLCO?',
        answer: 'In acute pulmonary hemorrhage (e.g., Goodpasture syndrome, DAH), DLCO is paradoxically increased because free hemoglobin in the alveolar space avidly binds carbon monoxide, increasing CO uptake. This is the opposite of most parenchymal diseases that reduce DLCO. Serial DLCO measurements can track hemorrhage activity — rising DLCO suggests active bleeding, falling DLCO suggests resolution.',
        difficulty: 2,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 173,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A patient has severe obstruction (FEV1 35% predicted) with a TLC of 130% predicted and RV of 250% predicted. Post-bronchodilator FEV1 improves by 400 mL (18%). What is the interpretation?',
        answer: 'This pattern shows severe obstructive disease with significant hyperinflation and air trapping (elevated TLC and markedly elevated RV). The significant bronchodilator response (both greater than 200 mL and greater than 12% change) indicates a reversible component, which may represent asthma-COPD overlap or asthma with incomplete reversibility. The high RV/TLC ratio (approximately 65%) confirms severe air trapping. Complete post-bronchodilator lung volumes would help assess whether hyperinflation deflates with bronchodilator.',
        difficulty: 2,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 174,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT pattern suggests upper airway obstruction, and how does fixed differ from variable obstruction on flow-volume loops?',
        answer: 'Fixed upper airway obstruction shows flattening of both inspiratory and expiratory limbs of the flow-volume loop. Variable extrathoracic obstruction shows predominantly inspiratory flow limitation (plateau on the inspiratory limb) because negative intraluminal pressure during inspiration collapses the lesion. Variable intrathoracic obstruction shows predominantly expiratory flow limitation because positive pleural pressure during forced expiration compresses the airway at the lesion site.',
        difficulty: 1,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 175,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A patient has FEV1 50% predicted, FVC 55% predicted, FEV1/FVC 72%, TLC 60% predicted, and DLCO 45% predicted. How do you classify this pattern?',
        answer: 'This is a mixed obstructive-restrictive pattern. The FEV1/FVC ratio is reduced for age (below LLN in most adults), confirming obstruction. The TLC is reduced to 60% predicted, confirming coexistent restriction (which cannot be inferred from spirometry alone when obstruction is present). The disproportionately reduced DLCO suggests significant parenchymal involvement. This pattern may be seen in combined COPD and pulmonary fibrosis, or sarcoidosis with both fibrotic and obstructive features.',
        difficulty: 2,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 176,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- More CPET Topics ---
      {
        question: 'What is the OUES (oxygen uptake efficiency slope), and what is its advantage in CPET?',
        answer: 'OUES is derived from the relationship: VO2 = a x log10(VE) + b, where "a" is the OUES. It reflects the efficiency of oxygen uptake relative to ventilation. Its main advantage is that it can be determined from submaximal exercise data and does not require maximal effort, making it useful in patients who cannot achieve peak exercise. Lower OUES values indicate less efficient ventilation.',
        difficulty: 3,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 177,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does dynamic hyperinflation during exercise affect CPET results in COPD patients?',
        answer: 'During exercise in COPD, expiratory flow limitation prevents complete exhalation, causing progressive air trapping (increased EELV). This reduces inspiratory capacity (IC), limits tidal volume expansion, increases the work of breathing, and contributes to dyspnea and exercise limitation. Serial IC measurements during exercise quantify dynamic hyperinflation — a decrease in IC greater than 150 mL or 10% from baseline is considered significant.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 178,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the heart rate reserve (HRR) at peak exercise, and what does an abnormally high HRR indicate?',
        answer: 'HRR = (predicted max HR - peak exercise HR) / predicted max HR x 100, where predicted max HR = 220 - age. Normal subjects achieve greater than 80% of predicted max HR, yielding HRR less than 20%. An abnormally high HRR (greater than 20%) at peak exercise with low peak VO2 suggests non-cardiovascular limitation — either ventilatory limitation, deconditioning, musculoskeletal limitation, or poor effort. A very low HRR with low peak VO2 supports chronotropic incompetence if beta-blockers have been excluded.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 179,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- More Advanced Blood Gas ---
      {
        question: 'What is the oxygenation index (OI), and how does it differ from the P/F ratio?',
        answer: 'OI = (MAP x FIO2 x 100) / PaO2, where MAP is mean airway pressure. Unlike the P/F ratio, the OI incorporates the level of ventilatory support (mean airway pressure) needed to achieve a given PaO2. A higher OI indicates worse oxygenation failure. OI greater than 40 sustained for several hours is one criterion for ECMO consideration in severe ARDS. It is more informative than P/F ratio in ventilated patients because two patients with the same P/F may have very different ventilatory support requirements.',
        difficulty: 3,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 180,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How do you interpret a blood gas showing pH 7.28, PaCO2 22 mmHg, HCO3- 10 mEq/L, and an anion gap of 24?',
        answer: 'Primary disorder: high anion gap metabolic acidosis (low pH, low HCO3-, elevated anion gap). Expected respiratory compensation: PaCO2 = (1.5 x 10) + 8 = 23 (+/- 2). The measured PaCO2 of 22 is within the expected range, so respiratory compensation is appropriate — no additional respiratory disorder. The delta-delta calculation: delta AG = 24-12 = 12, delta HCO3- = 24-10 = 14. Delta ratio = 12/14 = 0.86, suggesting a concurrent non-anion-gap metabolic acidosis.',
        difficulty: 3,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 181,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the significance of mixed venous oxygen saturation (SvO2), and what is the normal value?',
        answer: 'SvO2 is measured from the pulmonary artery (mixed venous blood) and reflects the balance between oxygen delivery and consumption. Normal SvO2 is 65-75%. Low SvO2 (less than 60%) indicates increased oxygen extraction due to inadequate delivery (low cardiac output, anemia, hypoxemia) or increased consumption (fever, sepsis, exercise). High SvO2 may indicate sepsis with impaired extraction, left-to-right shunt, or cyanide poisoning.',
        difficulty: 1,
        topic: 'Advanced Blood Gas Analysis',
        isFree: false,
        orderIndex: 182,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- More Respiratory Mechanics ---
      {
        question: 'What is the pressure-time product (PTP) of the respiratory muscles, and what does it indicate?',
        answer: 'PTP is the integral of esophageal pressure over time during inspiration (area under the pressure-time curve, cmH2O x sec). It reflects the metabolic cost of breathing more accurately than work of breathing because it includes isometric components (pressure generation without volume change, as when overcoming auto-PEEP). Elevated PTP predicts respiratory muscle fatigue and weaning failure in ICU patients. Normal PTP is approximately 100-150 cmH2O x sec/min.',
        difficulty: 3,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 183,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the maximum voluntary ventilation (MVV), and how is it used to estimate breathing reserve during CPET?',
        answer: 'MVV is the maximum volume of air a patient can breathe in one minute during rapid deep breathing (typically measured over 12-15 seconds and extrapolated). Normal MVV is approximately 35-40 x FEV1. During CPET, breathing reserve = (MVV - peak VE) / MVV x 100. If measured MVV is not available, estimated MVV (FEV1 x 40) is commonly used. Low breathing reserve (less than 15-20%) at peak exercise indicates ventilatory limitation.',
        difficulty: 1,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 184,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does the negative expiratory pressure (NEP) technique assess expiratory flow limitation?',
        answer: 'NEP applies a brief negative pressure (typically -5 cmH2O) at the mouth during expiration. If the resulting flow increases above the preceding tidal expiratory flow, the patient is not flow-limited. If flow does not increase despite the added driving pressure, expiratory flow limitation is present. NEP does not require patient cooperation beyond tidal breathing and does not alter lung volume history, making it useful in mechanically ventilated patients and those unable to perform forced maneuvers.',
        difficulty: 3,
        topic: 'Respiratory Mechanics',
        isFree: false,
        orderIndex: 185,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- More Metabolic / Environmental ---
      {
        question: 'What is the Haldane transformation, and why is it important in metabolic gas exchange calculations?',
        answer: 'The Haldane transformation uses the principle that nitrogen is metabolically inert (not consumed or produced) to calculate either inspired or expired volume from the other when only one is measured directly. Since inspired N2 volume equals expired N2 volume: VI x FIN2 = VE x FEN2. This allows accurate VO2 and VCO2 calculations because inspired and expired volumes differ due to the respiratory exchange ratio not equaling 1.0. Without this correction, VO2 calculations would be significantly in error.',
        difficulty: 3,
        topic: 'Metabolic Measurements',
        isFree: false,
        orderIndex: 186,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What BTPS correction is applied to lung volumes, and why?',
        answer: 'BTPS (Body Temperature and Pressure, Saturated) corrects measured gas volumes to body conditions: 37 degrees C, ambient barometric pressure, and fully saturated with water vapor. Spirometers measure gas at ambient temperature (ATPS), which is cooler than body temperature. The BTPS correction factor = [(PB - PH2O at ambient temp) / (PB - 47)] x [310 / (273 + ambient temp)]. This correction typically increases measured volumes by 5-10% depending on ambient conditions.',
        difficulty: 1,
        topic: 'Metabolic Measurements',
        isFree: false,
        orderIndex: 187,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'Why must metabolic gas exchange measurements (VO2, VCO2) be reported at STPD conditions?',
        answer: 'STPD (Standard Temperature and Pressure, Dry: 0 degrees C, 760 mmHg, dry) is used for metabolic measurements because it allows comparison of gas volumes independent of ambient conditions. Since VO2 and VCO2 represent quantities of gas molecules consumed or produced, standardizing to STPD ensures that values measured in different labs at different altitudes, temperatures, and humidities are directly comparable. Lung volumes, in contrast, are reported at BTPS to reflect actual physiologic volumes.',
        difficulty: 1,
        topic: 'Metabolic Measurements',
        isFree: false,
        orderIndex: 188,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- More Occupational / Disability ---
      {
        question: 'What is the specific inhalation challenge (SIC), and what defines a positive response?',
        answer: 'SIC is the gold standard for confirming occupational asthma. The patient is exposed in a controlled laboratory chamber to the suspected workplace agent in incremental doses while FEV1 is monitored for up to 24 hours. A positive response is a sustained fall in FEV1 of 20% or more from baseline. Responses can be immediate (within 30 minutes), late (3-8 hours after exposure), or dual (both). Late responses are particularly important as they may be missed without prolonged monitoring.',
        difficulty: 3,
        topic: 'Occupational and Disability Testing',
        isFree: false,
        orderIndex: 189,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT findings are characteristic of silicosis?',
        answer: 'Early simple silicosis may show normal PFTs or a mixed obstructive-restrictive pattern. Progressive massive fibrosis (PMF/complicated silicosis) typically causes: progressive restrictive defect (reduced FVC and TLC), reduced DLCO, and in some cases concurrent obstruction (reduced FEV1/FVC) particularly in smokers. The mixed pattern reflects both fibrosis (restriction) and dust-related bronchitis (obstruction). DLCO may be reduced before lung volume changes become apparent.',
        difficulty: 2,
        topic: 'Occupational and Disability Testing',
        isFree: false,
        orderIndex: 190,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- More Complex Interpretation ---
      {
        question: 'What is the bronchodilator response significance when FVC improves but FEV1 does not?',
        answer: 'An isolated FVC improvement (greater than 200 mL and greater than 12%) without significant FEV1 change suggests reduction in air trapping and hyperinflation rather than bronchodilation of large airways. The bronchodilator allows more complete emptying during forced expiration. This pattern is commonly seen in COPD where the primary benefit is lung volume reduction rather than airway caliber increase. Measuring IC or RV pre- and post-bronchodilator can confirm this mechanism.',
        difficulty: 2,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 191,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How do you interpret DLCO results when the hemoglobin is significantly abnormal?',
        answer: 'DLCO must be corrected for hemoglobin because CO transfer depends on available hemoglobin binding sites. The correction formula: DLCOcorrected = DLCOmeasured x (1.7 x Hb) / ((10.22 + Hb) for males or (9.38 + Hb) for females). In anemia, uncorrected DLCO underestimates true membrane diffusing capacity. In polycythemia, uncorrected DLCO overestimates it. A DLCO that is low uncorrected but normal after hemoglobin correction localizes the problem to anemia rather than parenchymal disease.',
        difficulty: 2,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 192,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the significance of the inspiratory capacity to total lung capacity (IC/TLC) ratio in COPD?',
        answer: 'The IC/TLC ratio reflects the degree of static hyperinflation. A ratio less than 0.25 (IC less than 25% of TLC) is associated with increased mortality, greater dyspnea, reduced exercise tolerance, and higher risk of acute exacerbation in COPD. It is a stronger predictor of mortality than FEV1 alone in some studies. Dynamic IC changes during exercise further predict exercise intolerance and the benefit of bronchodilator therapy.',
        difficulty: 3,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 193,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'A patient has a DLCO of 40% predicted but a KCO of 110% predicted. TLC is 55% predicted. What does this suggest?',
        answer: 'This pattern — low DLCO, high KCO, low TLC — is characteristic of extraparenchymal restriction. The lung tissue itself is healthy (high KCO indicates normal gas transfer per unit of ventilated alveolar volume), but accessible lung volume is reduced. Causes include neuromuscular disease (e.g., ALS, myasthenia gravis), chest wall deformity (kyphoscoliosis), pleural disease, or obesity. This contrasts with parenchymal restriction (ILD) where both DLCO and KCO are reduced.',
        difficulty: 2,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 194,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the nonspecific pattern in PFTs, and what conditions can produce it?',
        answer: 'The nonspecific pattern shows reduced FVC and/or FEV1 with normal FEV1/FVC ratio and normal TLC. It does not fit classic obstruction or restriction. It may represent early airway disease (air trapping reducing FVC without reducing FEV1/FVC), obesity (limiting chest wall excursion without reducing TLC), respiratory muscle weakness, suboptimal effort, or a normal variant at the lower end of the distribution. Further testing (lung volumes, respiratory muscle pressures, bronchodilator response) helps clarify.',
        difficulty: 1,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 195,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      // --- Additional Advanced Topics ---
      {
        question: 'What is the diffusing capacity for nitric oxide (DLNO), and how does combining DLNO with DLCO separate membrane and vascular components?',
        answer: 'DLNO uses nitric oxide instead of CO. Because NO has approximately 280 times greater affinity for hemoglobin than CO, the capillary blood resistance to NO uptake is negligible — DLNO reflects primarily the alveolar membrane diffusing capacity (Dm). By measuring both DLCO and DLNO simultaneously, one can partition diffusing capacity into membrane (Dm) and capillary blood volume (Vc) components without needing two different FIO2 levels as in the classic Roughton-Forster method.',
        difficulty: 3,
        topic: 'Advanced Diffusing Capacity',
        isFree: false,
        orderIndex: 196,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the Roughton-Forster equation, and how does it separate membrane and blood components of diffusing capacity?',
        answer: '1/DLCO = 1/Dm + 1/(theta x Vc), where Dm is membrane diffusing capacity, Vc is pulmonary capillary blood volume, and theta is the rate of CO uptake by red blood cells. By measuring DLCO at two different PAO2 levels (varying theta by altering hemoglobin O2 saturation), a system of two equations yields Dm and Vc. This helps distinguish membrane disease (reduced Dm in ILD) from capillary disease (reduced Vc in pulmonary vascular disorders).',
        difficulty: 3,
        topic: 'Advanced Diffusing Capacity',
        isFree: false,
        orderIndex: 197,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the six-minute walk test (6MWT) distance that corresponds to a peak VO2 of approximately 14 mL/kg/min?',
        answer: 'A 6MWT distance of approximately 300-350 meters roughly corresponds to a peak VO2 of 14 mL/kg/min, which is a commonly used threshold for heart transplant listing decisions. However, the 6MWT-to-VO2 correlation is imperfect and depends on the underlying disease, patient motivation, and walking efficiency. The 6MWT provides complementary but not interchangeable information to formal CPET.',
        difficulty: 2,
        topic: 'Cardiopulmonary Exercise Testing',
        isFree: false,
        orderIndex: 198,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the quality control requirements for gas analyzers used in DLCO measurement?',
        answer: 'Gas analyzers must be calibrated daily with known reference gases traceable to NIST standards. The CO analyzer must have accuracy within 0.0005% (5 ppm) and linearity across the measurement range. The tracer gas analyzer (helium or methane) must be accurate within 0.5% absolute. Leak testing of the system must demonstrate less than 25 mL/min leak. A biologic control subject should be tested monthly, and the DLCO coefficient of variation should be less than the within-session repeatability threshold.',
        difficulty: 1,
        topic: 'Research Methodology and Statistics',
        isFree: false,
        orderIndex: 199,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the clinical utility of measuring exhaled nitric oxide (FeNO) alongside traditional PFTs?',
        answer: 'FeNO is a noninvasive biomarker of eosinophilic airway inflammation. Values above 50 ppb in adults strongly suggest eosinophilic inflammation responsive to corticosteroids. Combined with PFTs, FeNO helps differentiate asthma from COPD (typically low FeNO in COPD unless eosinophilic), predict steroid responsiveness, monitor adherence to inhaled corticosteroids (FeNO rises with non-adherence), and identify asthma-COPD overlap. It complements but does not replace bronchial challenge testing for asthma diagnosis.',
        difficulty: 1,
        topic: 'Complex Case Interpretation',
        isFree: false,
        orderIndex: 200,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
    ],
    skipDuplicates: true,
  })

  console.log('Successfully seeded 100 RPFT flashcards (batch 2).')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
