import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const ACCS_DIVISION_ID = 'cmsm41fw40002zf5463d399ps'

const flashcards = [
  // ============================================================
  // ADVANCED HEMODYNAMIC ASSESSMENT (cards 1-15)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the four chambers or vessels traversed by a pulmonary artery catheter during insertion?',
    answer: 'The catheter passes through the right atrium, right ventricle, pulmonary artery, and into a pulmonary artery wedge position. Each chamber produces a characteristic pressure waveform that confirms proper catheter progression during flotation.',
    difficulty: 1,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 1,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the normal range for pulmonary artery wedge pressure (PAWP)?',
    answer: 'Normal PAWP is 8-12 mmHg. This pressure reflects left atrial filling pressure and serves as an indirect estimate of left ventricular end-diastolic pressure when mitral valve function is normal.',
    difficulty: 1,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 2,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is cardiac output measured using the thermodilution technique?',
    answer: 'A known volume of cold or room-temperature saline is injected into the right atrium via the proximal port. A thermistor at the catheter tip detects the temperature change in the pulmonary artery, and cardiac output is calculated from the area under the resulting temperature-time curve using the Stewart-Hamilton equation.',
    difficulty: 2,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 3,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the Fick equation for calculating cardiac output?',
    answer: 'Cardiac output equals oxygen consumption (VO2) divided by the arteriovenous oxygen content difference (CaO2 minus CvO2). This method is considered the gold standard for cardiac output determination but requires accurate measurement of oxygen consumption, which can be technically difficult.',
    difficulty: 2,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 4,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is systemic vascular resistance (SVR) calculated?',
    answer: 'SVR is calculated as (MAP minus CVP) divided by cardiac output, then multiplied by 80 to convert to dynes·sec·cm⁻⁵. Normal SVR is 800-1200 dynes·sec·cm⁻⁵. Elevated SVR indicates vasoconstriction while decreased SVR suggests vasodilation.',
    difficulty: 2,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 5,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is pulmonary vascular resistance (PVR) calculated?',
    answer: 'PVR is calculated as (mean PAP minus PAWP) divided by cardiac output, then multiplied by 80. Normal PVR is 100-250 dynes·sec·cm⁻⁵. Elevated PVR is seen in pulmonary hypertension, hypoxic vasoconstriction, and pulmonary embolism.',
    difficulty: 2,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 6,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What hemodynamic profile characterizes cardiogenic shock?',
    answer: 'Cardiogenic shock presents with low cardiac output, elevated PAWP (often greater than 18 mmHg), elevated CVP, and elevated SVR. The heart fails as a pump, causing blood to back up into the pulmonary vasculature while compensatory vasoconstriction attempts to maintain perfusion pressure.',
    difficulty: 1,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 7,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What hemodynamic profile is seen in septic (distributive) shock?',
    answer: 'Septic shock shows high cardiac output (hyperdynamic state), low SVR due to systemic vasodilation, and low to normal PAWP. This profile results from inflammatory mediators causing widespread vasodilation and capillary leak, with compensatory increased cardiac output.',
    difficulty: 1,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 8,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does hypovolemic shock differ hemodynamically from cardiogenic shock?',
    answer: 'Hypovolemic shock shows low cardiac output, low PAWP, low CVP, and elevated SVR. In contrast, cardiogenic shock has low cardiac output but elevated PAWP and CVP. The key differentiator is filling pressures, which are low in hypovolemia and high in cardiogenic failure.',
    difficulty: 1,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 9,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What does a large V wave on the PAWP tracing indicate?',
    answer: 'A prominent V wave on the PAWP tracing suggests mitral regurgitation. During ventricular systole, blood regurgitates through the incompetent mitral valve into the left atrium, producing an elevated V wave that can falsely elevate the mean PAWP reading.',
    difficulty: 3,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 10,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the normal central venous pressure (CVP) range and what does it reflect?',
    answer: 'Normal CVP is 2-6 mmHg. CVP reflects right atrial pressure and right ventricular preload. Elevated CVP may indicate right heart failure, fluid overload, or cardiac tamponade, while low CVP suggests hypovolemia.',
    difficulty: 1,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 11,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'Why must the PAWP be read at end-expiration?',
    answer: 'At end-expiration, intrathoracic pressure is closest to atmospheric pressure, minimizing the effect of pleural pressure on the vascular pressure measurement. During mechanical ventilation, end-expiration is the highest point on the waveform, while during spontaneous breathing it is the lowest point.',
    difficulty: 3,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 12,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the normal cardiac index and why is it preferred over cardiac output?',
    answer: 'Normal cardiac index is 2.5-4.0 L/min/m². Cardiac index is cardiac output divided by body surface area and is preferred because it normalizes cardiac performance to body size, allowing meaningful comparison between patients of different sizes.',
    difficulty: 1,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 13,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What hemodynamic findings characterize obstructive shock from cardiac tamponade?',
    answer: 'Cardiac tamponade shows equalization of diastolic pressures across all chambers (CVP, RVDP, diastolic PAP, and PAWP are nearly equal). Cardiac output is decreased, SVR is elevated, and pulsus paradoxus is present with a drop in systolic BP greater than 10 mmHg during inspiration.',
    difficulty: 3,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 14,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What complication is indicated when the PA catheter shows a persistent wedge waveform without balloon inflation?',
    answer: 'A spontaneous wedge pattern without balloon inflation indicates catheter migration into a distal pulmonary artery branch. This poses a risk of pulmonary infarction and vessel rupture. The catheter should be pulled back until a proper PA waveform is restored.',
    difficulty: 3,
    topic: 'Advanced Hemodynamic Assessment',
    isFree: true,
    orderIndex: 15,
  },

  // ============================================================
  // ADVANCED MECHANICAL VENTILATION (cards 16-35)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What tidal volume does the ARDSNet protocol recommend for patients with ARDS?',
    answer: 'The ARDSNet protocol recommends 6 mL/kg of predicted (ideal) body weight. Predicted body weight is calculated from height and sex, not actual weight, to prevent overdistension of the remaining functional lung units.',
    difficulty: 1,
    topic: 'Advanced Mechanical Ventilation',
    isFree: true,
    orderIndex: 16,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the plateau pressure goal in the ARDSNet protocol?',
    answer: 'The ARDSNet protocol targets a plateau pressure of 30 cmH2O or less. If plateau pressure exceeds 30 cmH2O, the tidal volume should be reduced in 1 mL/kg increments down to a minimum of 4 mL/kg predicted body weight to limit alveolar overdistension.',
    difficulty: 1,
    topic: 'Advanced Mechanical Ventilation',
    isFree: true,
    orderIndex: 17,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the PEEP/FiO2 table used for in the ARDSNet protocol?',
    answer: 'The PEEP/FiO2 table provides paired combinations of PEEP and FiO2 to achieve a target PaO2 of 55-80 mmHg or SpO2 of 88-95%. As FiO2 requirements increase, PEEP is titrated upward in a stepwise fashion to improve oxygenation while maintaining lung protection.',
    difficulty: 1,
    topic: 'Advanced Mechanical Ventilation',
    isFree: true,
    orderIndex: 18,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is driving pressure and why is it clinically significant in ARDS?',
    answer: 'Driving pressure equals plateau pressure minus PEEP, representing the pressure distending the lung above the set PEEP. Research suggests that driving pressure above 15 cmH2O is associated with increased mortality in ARDS, as it reflects the strain applied to the functional lung tissue.',
    difficulty: 2,
    topic: 'Advanced Mechanical Ventilation',
    isFree: true,
    orderIndex: 19,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the primary physiologic benefit of prone positioning in severe ARDS?',
    answer: 'Prone positioning improves ventilation-perfusion matching by redistributing ventilation toward dorsal lung regions where perfusion is greatest. It also promotes more homogeneous lung inflation, reduces compression of dorsal lung units by the heart and abdomen, and improves secretion drainage.',
    difficulty: 2,
    topic: 'Advanced Mechanical Ventilation',
    isFree: true,
    orderIndex: 20,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'According to the PROSEVA trial, how long per day should prone positioning sessions last for survival benefit in severe ARDS?',
    answer: 'The PROSEVA trial demonstrated a mortality benefit with prone sessions of at least 16 consecutive hours per day. This study showed a significant reduction in 28-day and 90-day mortality in patients with severe ARDS (PaO2/FiO2 less than 150) who were proned early.',
    difficulty: 2,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 21,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What does ECMO stand for and what are the two main configurations?',
    answer: 'ECMO stands for extracorporeal membrane oxygenation. Veno-venous (VV) ECMO is used for isolated respiratory failure, draining and returning blood to the venous system. Veno-arterial (VA) ECMO provides both cardiac and respiratory support by returning oxygenated blood to the arterial system.',
    difficulty: 1,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 22,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is APRV and how does it differ from conventional ventilation?',
    answer: 'Airway pressure release ventilation (APRV) maintains a sustained high pressure (P-high) for most of the breath cycle while allowing brief releases to a low pressure (P-low) for CO2 elimination. Unlike conventional modes, the patient breathes spontaneously at the high pressure level throughout the cycle.',
    difficulty: 2,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 23,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'In APRV, what is the typical release time (T-low) setting and why?',
    answer: 'T-low is typically set to terminate at 75% of the peak expiratory flow rate, usually resulting in a release time of 0.4-0.8 seconds. This brief release creates auto-PEEP that prevents alveolar derecruitment while still allowing adequate CO2 elimination through the rapid pressure release.',
    difficulty: 3,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 24,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'Why has high-frequency oscillatory ventilation (HFOV) fallen out of favor for adult ARDS?',
    answer: 'The OSCILLATE and OSCAR trials showed that HFOV provided no benefit and potentially increased mortality in adult ARDS compared to conventional lung-protective ventilation. HFOV is now generally not recommended as a routine strategy for adult ARDS management.',
    difficulty: 3,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 25,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is transpulmonary pressure and how is it measured?',
    answer: 'Transpulmonary pressure is the difference between airway pressure and pleural pressure. It is estimated clinically by subtracting esophageal pressure (as a surrogate for pleural pressure) from airway pressure using an esophageal balloon catheter. This measurement reflects the true distending pressure of the lung.',
    difficulty: 3,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 26,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does esophageal manometry help guide PEEP titration?',
    answer: 'Esophageal manometry allows calculation of transpulmonary pressure at end-expiration. If end-expiratory transpulmonary pressure is negative, alveoli are collapsing at end-expiration and PEEP should be increased. The goal is to maintain a slightly positive end-expiratory transpulmonary pressure to keep alveoli open without overdistension.',
    difficulty: 3,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 27,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the concept of the "baby lung" in ARDS?',
    answer: 'The baby lung concept describes how ARDS reduces the aerated lung volume to a fraction of normal, sometimes to the size of a small child\'s lung. Because tidal volume is delivered only to these aerated regions, standard tidal volumes create excessive strain, which is why low tidal volume ventilation is essential.',
    difficulty: 2,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 28,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the best PEEP trial (decremental PEEP titration) approach?',
    answer: 'The decremental PEEP trial involves first performing a recruitment maneuver to fully open the lung, then reducing PEEP in small steps while monitoring compliance or oxygenation. The PEEP level just above the point where compliance begins to decrease represents the optimal PEEP that keeps recruited alveoli open.',
    difficulty: 3,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 29,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the stress index and how is it used to assess lung mechanics during ventilation?',
    answer: 'The stress index analyzes the shape of the pressure-time curve during constant-flow volume-controlled ventilation. A concave upward curve (stress index greater than 1) suggests overdistension, a concave downward curve (less than 1) suggests ongoing recruitment, and a straight line (equal to 1) indicates appropriate ventilation settings.',
    difficulty: 3,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 30,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is predicted body weight (PBW) calculated for setting tidal volume in ARDS?',
    answer: 'For males, PBW equals 50 plus 2.3 times the number of inches over 5 feet in height. For females, PBW equals 45.5 plus 2.3 times the number of inches over 5 feet. Using PBW rather than actual weight is critical because lung size correlates with height, not body mass.',
    difficulty: 1,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 31,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is permissive hypercapnia and when is it acceptable?',
    answer: 'Permissive hypercapnia is the deliberate tolerance of elevated PaCO2 (and resultant respiratory acidosis) to maintain lung-protective tidal volumes. It is generally acceptable if pH remains above 7.20, though it is contraindicated in patients with elevated intracranial pressure or severe pulmonary hypertension.',
    difficulty: 2,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 32,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the contraindications to prone positioning in mechanically ventilated patients?',
    answer: 'Contraindications include spinal instability, open abdominal wounds, unstable fractures of the face or pelvis, elevated intracranial pressure, and hemodynamic instability requiring active resuscitation. Pregnancy in advanced stages is also a relative contraindication due to abdominal compression concerns.',
    difficulty: 2,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 33,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What ventilator settings are recommended during VV-ECMO to provide lung rest?',
    answer: 'During VV-ECMO, ventilator settings should be reduced to allow lung rest: low tidal volumes (around 4 mL/kg PBW or less), low FiO2 (typically 0.3-0.4), moderate PEEP (10-15 cmH2O), and low respiratory rate. The goal is to minimize ventilator-induced lung injury while the ECMO circuit handles gas exchange.',
    difficulty: 3,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 34,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the mechanical power concept in ventilation and why does it matter?',
    answer: 'Mechanical power is the total energy delivered to the lungs per unit time, incorporating tidal volume, respiratory rate, PEEP, driving pressure, and flow. Higher mechanical power is associated with increased risk of ventilator-induced lung injury, and the concept highlights that no single parameter alone determines lung injury risk.',
    difficulty: 3,
    topic: 'Advanced Mechanical Ventilation',
    isFree: false,
    orderIndex: 35,
  },

  // ============================================================
  // CRITICAL CARE PHARMACOLOGY (cards 36-50)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the first-line vasopressor recommended for septic shock?',
    answer: 'Norepinephrine is the first-line vasopressor for septic shock. It acts primarily on alpha-1 receptors to cause vasoconstriction, with some beta-1 activity providing modest inotropic support. It effectively raises mean arterial pressure with less tachycardia than dopamine.',
    difficulty: 1,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 36,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the mechanism of action of vasopressin when used in shock?',
    answer: 'Vasopressin acts on V1 receptors in vascular smooth muscle to cause vasoconstriction independent of adrenergic pathways. It is used as an adjunct to norepinephrine in refractory septic shock, typically at a fixed dose of 0.03-0.04 units/min, and can help reduce the norepinephrine requirement.',
    difficulty: 2,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 37,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does dobutamine differ from dopamine in its cardiovascular effects?',
    answer: 'Dobutamine is primarily a beta-1 agonist that increases cardiac contractility and output with relatively less effect on heart rate and vascular resistance. Dopamine has dose-dependent effects on dopaminergic, beta-1, and alpha-1 receptors, causing more tachycardia and arrhythmias at higher doses.',
    difficulty: 2,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 38,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What does the RASS scale measure and what is the target range for most ICU patients?',
    answer: 'The Richmond Agitation-Sedation Scale (RASS) measures the level of sedation and agitation on a scale from -5 (unarousable) to +4 (combative). For most mechanically ventilated ICU patients, a target of 0 to -2 (alert and calm to light sedation) is recommended to minimize complications of oversedation.',
    difficulty: 1,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 39,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the CAM-ICU tool used to assess?',
    answer: 'The Confusion Assessment Method for the ICU (CAM-ICU) screens for delirium in critically ill patients. It evaluates four features: acute onset or fluctuating mental status, inattention, altered level of consciousness, and disorganized thinking. Delirium is present if features 1 and 2 are positive plus either 3 or 4.',
    difficulty: 1,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 40,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the mechanism of inhaled nitric oxide (iNO) and its primary clinical indication in adults?',
    answer: 'Inhaled nitric oxide causes selective pulmonary vasodilation by activating guanylate cyclase in pulmonary vascular smooth muscle, increasing cyclic GMP. In adults, it is primarily used for refractory hypoxemia in ARDS and acute pulmonary hypertension to improve ventilation-perfusion matching without systemic hypotension.',
    difficulty: 2,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 41,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What toxic byproduct must be monitored during inhaled nitric oxide therapy?',
    answer: 'Methemoglobin levels must be monitored during iNO therapy, as nitric oxide binds to hemoglobin and oxidizes iron from the ferrous to the ferric state. Methemoglobin levels should be kept below 5%. Nitrogen dioxide (NO2) levels in the circuit should also be monitored as it is a toxic oxidation product.',
    difficulty: 2,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 42,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is inhaled epoprostenol and how does it compare to iNO?',
    answer: 'Inhaled epoprostenol (Flolan) is a prostacyclin analog that causes selective pulmonary vasodilation similar to iNO. It is significantly less expensive than iNO and does not require specialized delivery systems. However, it can be sticky in the ventilator circuit and may affect expiratory valve function if not monitored.',
    difficulty: 2,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 43,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What neuromuscular blocking agent is preferred for use in ARDS and why?',
    answer: 'Cisatracurium is preferred because it undergoes Hofmann degradation, a spontaneous non-enzymatic breakdown independent of hepatic or renal function. This is advantageous in critically ill patients who may have organ dysfunction. The ACURASYS trial suggested a mortality benefit with early cisatracurium use in severe ARDS.',
    difficulty: 3,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 44,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'Why must adequate sedation be ensured before administering neuromuscular blocking agents?',
    answer: 'Neuromuscular blockers paralyze skeletal muscles but have no analgesic or sedative properties. A paralyzed patient who is aware experiences extreme distress and psychological trauma. Adequate sedation and analgesia must be confirmed using clinical assessment and processed EEG monitoring (such as BIS) before and during paralysis.',
    difficulty: 1,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 45,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the train-of-four (TOF) test used for in the ICU?',
    answer: 'The train-of-four test monitors the depth of neuromuscular blockade by delivering four successive electrical stimuli to a peripheral nerve. The number of visible twitches indicates the degree of paralysis. A target of 1-2 out of 4 twitches indicates adequate blockade while avoiding excessive paralysis.',
    difficulty: 2,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 46,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the advantages of dexmedetomidine over benzodiazepines for ICU sedation?',
    answer: 'Dexmedetomidine provides sedation and analgesia without significant respiratory depression, allowing patients to be arousable and cooperative. It is associated with less delirium, shorter duration of mechanical ventilation, and better cognitive outcomes compared to benzodiazepines like midazolam or lorazepam.',
    difficulty: 2,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 47,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'Why should inhaled nitric oxide be weaned gradually rather than discontinued abruptly?',
    answer: 'Abrupt discontinuation of iNO can cause rebound pulmonary hypertension and severe hypoxemia. During iNO therapy, endogenous NO production is downregulated, so sudden withdrawal removes vasodilatory support before the body can restore its own production. Gradual weaning over hours allows endogenous mechanisms to recover.',
    difficulty: 3,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 48,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the ABCDEF bundle in ICU care?',
    answer: 'The ABCDEF bundle includes: Assess/prevent/manage pain, Both spontaneous awakening and breathing trials, Choice of appropriate sedation, Delirium assessment and management, Early mobility and exercise, and Family engagement. This evidence-based bundle reduces ICU delirium, shortens ventilator days, and improves patient outcomes.',
    difficulty: 1,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 49,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the role of milrinone in critical care?',
    answer: 'Milrinone is a phosphodiesterase-3 inhibitor that increases cardiac contractility and causes vasodilation (inodilator). It works independently of beta receptors, making it useful in patients with beta-receptor downregulation from chronic heart failure or prolonged catecholamine exposure. It can cause hypotension and requires careful hemodynamic monitoring.',
    difficulty: 3,
    topic: 'Critical Care Pharmacology',
    isFree: false,
    orderIndex: 50,
  },

  // ============================================================
  // ACUTE RESPIRATORY FAILURE (cards 51-65)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What defines Type I (hypoxemic) respiratory failure?',
    answer: 'Type I respiratory failure is characterized by a PaO2 less than 60 mmHg with a normal or low PaCO2. It results from ventilation-perfusion mismatch, shunt, or diffusion impairment. Common causes include pneumonia, ARDS, pulmonary embolism, and pulmonary edema.',
    difficulty: 1,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 51,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What defines Type II (hypercapnic) respiratory failure?',
    answer: 'Type II respiratory failure is characterized by a PaCO2 greater than 50 mmHg, often accompanied by hypoxemia. It results from alveolar hypoventilation due to inadequate minute ventilation. Common causes include COPD exacerbation, neuromuscular disease, drug overdose, and chest wall deformities.',
    difficulty: 1,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 52,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the three categories of ARDS severity according to the Berlin definition?',
    answer: 'The Berlin definition classifies ARDS as mild (PaO2/FiO2 200-300 mmHg), moderate (PaO2/FiO2 100-200 mmHg), or severe (PaO2/FiO2 less than 100 mmHg), all measured with PEEP of at least 5 cmH2O. Mortality increases with severity category, ranging from approximately 27% in mild to 45% in severe ARDS.',
    difficulty: 1,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 53,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the four criteria required for the Berlin definition of ARDS?',
    answer: 'The Berlin definition requires: onset within one week of a known clinical insult or new/worsening respiratory symptoms; bilateral opacities on chest imaging not fully explained by effusions, collapse, or nodules; respiratory failure not fully explained by cardiac failure or fluid overload; and a PaO2/FiO2 ratio meeting severity thresholds with PEEP of at least 5 cmH2O.',
    difficulty: 2,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 54,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does sepsis cause acute respiratory failure?',
    answer: 'Sepsis triggers a systemic inflammatory response releasing cytokines, complement, and neutrophil-mediated injury that damages the pulmonary capillary endothelium. This causes increased capillary permeability, protein-rich pulmonary edema, surfactant inactivation, and alveolar collapse, resulting in intrapulmonary shunting and refractory hypoxemia characteristic of ARDS.',
    difficulty: 2,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 55,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is ventilator-induced lung injury (VILI)?',
    answer: 'VILI is lung damage caused by mechanical ventilation through mechanisms including volutrauma (overdistension), barotrauma (excessive pressure), atelectrauma (repeated opening and closing of alveoli), and biotrauma (release of inflammatory mediators). Lung-protective ventilation strategies aim to minimize all these injury mechanisms.',
    difficulty: 1,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 56,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is volutrauma and how is it prevented?',
    answer: 'Volutrauma is lung injury caused by overdistension of alveoli from excessive tidal volume delivery. It is the primary mechanism of VILI and is prevented by using low tidal volumes (6 mL/kg PBW) and monitoring plateau pressure. Regional overdistension can still occur even with low tidal volumes in heterogeneous lung disease.',
    difficulty: 2,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 57,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is atelectrauma?',
    answer: 'Atelectrauma is lung injury caused by the cyclic opening and closing of unstable alveoli during tidal ventilation. The repetitive shear forces generated at the interface between collapsed and aerated alveoli cause epithelial damage and inflammation. Adequate PEEP helps prevent atelectrauma by maintaining alveolar recruitment throughout the respiratory cycle.',
    difficulty: 2,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 58,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is biotrauma and why is it clinically significant?',
    answer: 'Biotrauma is the release of inflammatory mediators (cytokines, chemokines) from mechanically stressed lung tissue into the systemic circulation. This inflammatory cascade can lead to multiorgan dysfunction syndrome (MODS), which is the leading cause of death in ARDS patients rather than hypoxemia alone.',
    difficulty: 2,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 59,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the three pathological phases of ARDS?',
    answer: 'The exudative phase (days 1-7) features diffuse alveolar damage, hyaline membrane formation, and pulmonary edema. The proliferative phase (days 7-21) involves type II pneumocyte proliferation and fibroblast migration. The fibrotic phase (after day 21) shows collagen deposition and irreversible fibrosis in some patients.',
    difficulty: 3,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 60,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does intrapulmonary shunting differ from V/Q mismatch in terms of oxygen responsiveness?',
    answer: 'Intrapulmonary shunt (perfusion without ventilation) is refractory to supplemental oxygen because blood passes through non-ventilated alveoli and cannot participate in gas exchange regardless of FiO2. V/Q mismatch (low V/Q regions) responds to supplemental oxygen because the poorly ventilated units can still receive additional oxygen.',
    difficulty: 3,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 61,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What clinical signs suggest impending respiratory muscle fatigue and ventilatory failure?',
    answer: 'Signs include respiratory alternans (alternating abdominal and thoracic breathing), paradoxical abdominal motion (inward movement during inspiration), accessory muscle use, tachypnea progressing to bradypnea, diaphoresis, and rising PaCO2 with falling pH. These indicate the patient cannot maintain adequate minute ventilation and may require intubation.',
    difficulty: 2,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 62,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the shunt equation and how is it used clinically?',
    answer: 'The shunt equation is Qs/Qt = (CcO2 - CaO2) / (CcO2 - CvO2), where CcO2 is pulmonary capillary oxygen content, CaO2 is arterial oxygen content, and CvO2 is mixed venous oxygen content. A shunt fraction greater than 30% typically indicates severe intrapulmonary shunting requiring mechanical ventilation and PEEP.',
    difficulty: 3,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 63,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the difference between barotrauma as a VILI mechanism and its clinical manifestations?',
    answer: 'As a VILI mechanism, barotrauma refers to lung injury from excessive transpulmonary pressure causing alveolar rupture. Clinically, it manifests as pneumothorax, pneumomediastinum, subcutaneous emphysema, or pneumoperitoneum. Monitoring plateau pressure and keeping it below 30 cmH2O reduces barotrauma risk.',
    difficulty: 2,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 64,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does obesity affect the risk and management of acute respiratory failure?',
    answer: 'Obesity increases atelectasis due to elevated abdominal pressure compressing the diaphragm, reduces functional residual capacity, and increases oxygen consumption. PEEP requirements are typically higher, plateau pressure limits may need adjustment for elevated chest wall elastance, and PBW (not actual weight) must be used for tidal volume calculation.',
    difficulty: 3,
    topic: 'Acute Respiratory Failure',
    isFree: false,
    orderIndex: 65,
  },

  // ============================================================
  // CRITICAL CARE MONITORING (cards 66-80)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the Allen test and why is it performed before arterial line placement?',
    answer: 'The Allen test assesses collateral circulation to the hand by occluding both the radial and ulnar arteries, then releasing the ulnar artery to see if color returns to the hand. A positive test (adequate collateral flow) confirms the ulnar artery can perfuse the hand if the radial artery becomes compromised by catheter placement.',
    difficulty: 1,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 66,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the normal mixed venous oxygen saturation (SvO2) and what does it indicate?',
    answer: 'Normal SvO2 is 60-80%, measured from blood in the pulmonary artery. It reflects the balance between oxygen delivery and oxygen consumption. A low SvO2 indicates that tissue oxygen extraction is increased, suggesting inadequate oxygen delivery relative to metabolic demand.',
    difficulty: 1,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 67,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What conditions cause a decreased SvO2?',
    answer: 'SvO2 decreases when oxygen delivery is inadequate or oxygen consumption is excessive. Causes include low cardiac output, anemia, hypoxemia, and increased metabolic demand from fever, seizures, or shivering. SvO2 below 60% indicates significant oxygen supply-demand imbalance requiring intervention.',
    difficulty: 1,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 68,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What does an elevated SvO2 (above 80%) suggest?',
    answer: 'An elevated SvO2 can indicate that tissues are not extracting oxygen normally, as seen in sepsis (cytopathic hypoxia), cyanide poisoning, high-output states, left-to-right intracardiac shunts, or wedged PA catheter artifact. In sepsis, despite adequate delivery, mitochondrial dysfunction prevents normal cellular oxygen utilization.',
    difficulty: 3,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 69,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the clinical significance of serum lactate levels in critical care?',
    answer: 'Lactate is produced during anaerobic metabolism and serves as a marker of tissue hypoperfusion. Normal lactate is less than 2 mmol/L. Levels above 4 mmol/L are associated with significant mortality. Serial lactate measurements and lactate clearance (decrease of at least 10% over 2 hours) are used to guide resuscitation adequacy.',
    difficulty: 1,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 70,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the difference between ScvO2 and SvO2?',
    answer: 'ScvO2 (central venous oxygen saturation) is measured from a central venous catheter in the superior vena cava, while SvO2 (mixed venous oxygen saturation) is measured from the pulmonary artery. ScvO2 is typically 2-5% higher than SvO2 because it does not include desaturated coronary sinus blood. ScvO2 is more readily available clinically.',
    difficulty: 3,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 71,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does capnography help detect pulmonary embolism in ventilated patients?',
    answer: 'A sudden decrease in end-tidal CO2 (ETCO2) in a mechanically ventilated patient with stable minute ventilation can suggest pulmonary embolism. The embolism creates dead space by occluding pulmonary blood flow, so ventilated alveoli cannot eliminate CO2. This increases the PaCO2-ETCO2 gradient significantly.',
    difficulty: 2,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 72,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the normal PaCO2-to-ETCO2 gradient and what causes it to widen?',
    answer: 'The normal PaCO2-ETCO2 gradient is 2-5 mmHg, with PaCO2 being higher. The gradient widens with increased dead space ventilation from pulmonary embolism, low cardiac output, hyperinflation, or any condition reducing pulmonary perfusion. A widening gradient indicates that ETCO2 alone cannot reliably estimate PaCO2.',
    difficulty: 2,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 73,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What does an arterial line waveform with a dampened tracing indicate?',
    answer: 'A dampened arterial waveform (blunted systolic peak, absent dicrotic notch, artificially low systolic and high diastolic readings) may indicate catheter kinking, air bubbles in the tubing, clot formation at the catheter tip, or excessively compliant tubing. A fast-flush test showing fewer than 1.5 oscillations confirms overdampening.',
    difficulty: 2,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 74,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the proper leveling and zeroing procedure for invasive hemodynamic monitoring?',
    answer: 'The transducer is leveled to the phlebostatic axis (intersection of the fourth intercostal space and mid-axillary line) and opened to atmospheric pressure to establish a zero reference. This must be repeated whenever the patient or transducer position changes to ensure accurate pressure readings.',
    difficulty: 1,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 75,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does intracranial pressure (ICP) monitoring influence ventilator management?',
    answer: 'Elevated ICP requires careful ventilator management to avoid hypercarbia, which causes cerebral vasodilation and further increases ICP. PaCO2 is typically maintained at 35-40 mmHg. Brief hyperventilation to a PaCO2 of 30-35 mmHg can be used acutely for ICP crises, but prolonged hyperventilation is avoided due to cerebral ischemia risk.',
    difficulty: 3,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 76,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the normal intracranial pressure and at what value is treatment indicated?',
    answer: 'Normal ICP is 5-15 mmHg. Treatment is generally initiated when ICP exceeds 20-22 mmHg. Sustained ICP elevation reduces cerebral perfusion pressure (CPP equals MAP minus ICP), risking cerebral ischemia. Treatment includes head elevation, osmotic therapy, sedation, and CSF drainage.',
    difficulty: 2,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 77,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What point-of-care tests are commonly used in respiratory critical care?',
    answer: 'Common point-of-care tests include arterial blood gas analysis, lactate, hemoglobin/hematocrit, electrolytes, glucose, and coagulation studies (ACT). These rapid bedside tests allow immediate clinical decision-making for ventilator adjustments, fluid resuscitation, transfusion, and medication dosing without waiting for central laboratory results.',
    difficulty: 1,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 78,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the significance of the dicrotic notch on an arterial pressure waveform?',
    answer: 'The dicrotic notch represents aortic valve closure at the end of ventricular systole. Its presence confirms a properly functioning monitoring system. The position and shape of the dicrotic notch can provide information about aortic valve competence and systemic vascular resistance.',
    difficulty: 2,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 79,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does PEEP affect CVP and PAWP measurements?',
    answer: 'PEEP increases intrathoracic pressure, which can be transmitted to the vascular structures and artificially elevate CVP and PAWP readings. The effect is greater with high lung compliance. Transmural pressure (measured minus pleural pressure) gives the true filling pressure, but clinically, trending changes in readings at consistent PEEP levels is practical.',
    difficulty: 3,
    topic: 'Critical Care Monitoring',
    isFree: false,
    orderIndex: 80,
  },

  // ============================================================
  // MULTISYSTEM CRITICAL CARE (cards 81-95)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is hepatopulmonary syndrome?',
    answer: 'Hepatopulmonary syndrome occurs in patients with liver disease and involves intrapulmonary vascular dilation that creates right-to-left shunting. Patients develop hypoxemia that characteristically worsens when sitting upright (platypnea) and improves when lying down. It is diagnosed by contrast echocardiography showing intrapulmonary shunting.',
    difficulty: 3,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 81,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does acute kidney injury affect mechanical ventilation management?',
    answer: 'Acute kidney injury causes fluid overload that worsens pulmonary edema and reduces lung compliance, metabolic acidosis that increases ventilatory demand, and electrolyte derangements (hyperkalemia) that can cause cardiac arrhythmias. Fluid removal through dialysis or ultrafiltration can significantly improve respiratory mechanics and facilitate weaning.',
    difficulty: 2,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 82,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is disseminated intravascular coagulation (DIC) and how does it affect the lungs?',
    answer: 'DIC is a systemic activation of the coagulation cascade causing widespread microvascular thrombosis followed by consumption of clotting factors and bleeding. Pulmonary microthrombi increase dead space, damage the alveolar-capillary membrane, and can precipitate ARDS. Treatment focuses on the underlying cause and supportive care.',
    difficulty: 2,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 83,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is a massive transfusion protocol and when is it activated?',
    answer: 'A massive transfusion protocol provides rapid delivery of balanced blood products (typically a 1:1:1 ratio of packed red blood cells, fresh frozen plasma, and platelets) for life-threatening hemorrhage. It is activated when a patient requires more than 10 units of PRBCs in 24 hours or more than 4 units in one hour.',
    difficulty: 2,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 84,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is transfusion-related acute lung injury (TRALI)?',
    answer: 'TRALI is a form of non-cardiogenic pulmonary edema occurring within 6 hours of transfusion. It presents with acute hypoxemia, bilateral infiltrates, and no evidence of volume overload. It is thought to be caused by donor antibodies activating recipient neutrophils in the pulmonary vasculature, causing capillary leak.',
    difficulty: 3,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 85,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the ventilator management goals for a potential organ donor?',
    answer: 'Organ donation ventilation aims to preserve lung function: tidal volume 6-8 mL/kg PBW, PEEP 8-10 cmH2O, lowest FiO2 for SpO2 above 92%, plateau pressure below 30 cmH2O. Recruitment maneuvers, aggressive pulmonary toileting, and frequent repositioning maximize the number of transplantable organs, especially lungs.',
    difficulty: 2,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 86,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What clinical tests are required for the determination of brain death?',
    answer: 'Brain death testing requires two clinical examinations demonstrating absent brainstem reflexes (pupillary, corneal, oculocephalic, oculovestibular, cough, and gag reflexes) and an apnea test. Prerequisites include normothermia, hemodynamic stability, absence of CNS depressant drugs, and correction of metabolic derangements.',
    difficulty: 2,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 87,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is the apnea test performed during brain death evaluation?',
    answer: 'The patient is preoxygenated with 100% FiO2, then disconnected from the ventilator while oxygen is insufflated through the endotracheal tube. The patient is observed for spontaneous respirations for 8-10 minutes while PaCO2 is allowed to rise. The test is positive for brain death if no respirations occur and PaCO2 rises above 60 mmHg (or 20 mmHg above baseline).',
    difficulty: 3,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 88,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is targeted temperature management (therapeutic hypothermia) and when is it used?',
    answer: 'Targeted temperature management involves cooling patients to 32-36 degrees Celsius after cardiac arrest to reduce neurological injury. It decreases cerebral metabolic demand, reduces reperfusion injury, and limits inflammatory cascades. Shivering must be controlled, and rewarming should be performed slowly (0.25-0.5 degrees C per hour) to avoid rebound injury.',
    difficulty: 2,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 89,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does therapeutic hypothermia affect ventilator management?',
    answer: 'Hypothermia decreases CO2 production and metabolic rate, which may require reducing minute ventilation to prevent respiratory alkalosis. Oxygen consumption decreases, and the oxyhemoglobin dissociation curve shifts leftward, potentially impairing oxygen unloading at the tissue level. ABG values should be interpreted at the measured temperature.',
    difficulty: 3,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 90,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What respiratory complications are associated with massive blood transfusion?',
    answer: 'Massive transfusion can cause TRALI, transfusion-associated circulatory overload (TACO), citrate toxicity causing hypocalcemia and metabolic alkalosis, hypothermia-related coagulopathy, and hyperkalemia. Both TRALI and TACO present with respiratory distress and bilateral infiltrates but differ in volume status and response to diuretics.',
    difficulty: 3,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 91,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is hepatorenal syndrome and how does it affect respiratory care?',
    answer: 'Hepatorenal syndrome is progressive renal failure in patients with advanced liver disease, caused by severe renal vasoconstriction. It leads to fluid retention, ascites, and pleural effusions that compromise respiratory function. These patients often develop hepatic hydrothorax, typically right-sided, requiring thoracentesis and careful fluid management.',
    difficulty: 3,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 92,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is abdominal compartment syndrome and how does it affect ventilation?',
    answer: 'Abdominal compartment syndrome occurs when intra-abdominal pressure exceeds 20 mmHg with new organ dysfunction. Elevated abdominal pressure pushes the diaphragm cephalad, reducing FRC, lung compliance, and tidal volume. Peak and plateau pressures rise while oxygenation deteriorates. Decompressive laparotomy may be required.',
    difficulty: 3,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 93,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the lethal triad in trauma patients?',
    answer: 'The lethal triad consists of hypothermia, acidosis, and coagulopathy, which form a self-perpetuating cycle in severely injured patients. Hypothermia impairs coagulation enzymes, ongoing hemorrhage causes acidosis, and acidosis further impairs coagulation. Breaking this cycle with damage control resuscitation and rapid rewarming is critical to survival.',
    difficulty: 1,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 94,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How should PEEP be managed in a patient with elevated intracranial pressure?',
    answer: 'PEEP should be used judiciously in patients with elevated ICP. PEEP can impede cerebral venous drainage and increase ICP, particularly when lung compliance is preserved. However, PEEP needed for oxygenation should not be withheld, as hypoxemia itself worsens ICP. The head of bed should be elevated to 30 degrees to mitigate venous effects.',
    difficulty: 2,
    topic: 'Multisystem Critical Care',
    isFree: false,
    orderIndex: 95,
  },

  // ============================================================
  // WEANING & LIBERATION (cards 96-100)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the rapid shallow breathing index (RSBI) and what value predicts weaning success?',
    answer: 'The RSBI is the ratio of respiratory rate to tidal volume (f/Vt) measured in breaths/min/L during a brief period of unassisted breathing. An RSBI less than 105 predicts successful extubation, while values above 105 suggest the patient may not tolerate weaning. It is the most widely used single predictor of weaning outcome.',
    difficulty: 1,
    topic: 'Weaning & Liberation',
    isFree: false,
    orderIndex: 96,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the prerequisites for conducting a spontaneous breathing trial (SBT)?',
    answer: 'Prerequisites include adequate oxygenation (FiO2 of 0.40 or less and PEEP of 5-8 cmH2O or less), hemodynamic stability without vasopressors or minimal doses, patient able to initiate spontaneous breaths, adequate level of consciousness, and resolution or improvement of the underlying condition that necessitated mechanical ventilation.',
    difficulty: 1,
    topic: 'Weaning & Liberation',
    isFree: false,
    orderIndex: 97,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What criteria indicate failure of a spontaneous breathing trial?',
    answer: 'SBT failure criteria include tachypnea (rate above 35), tachycardia or bradycardia (change greater than 20%), hypertension or hypotension, SpO2 below 88-90%, increased anxiety or diaphoresis, accessory muscle use, and paradoxical breathing. The trial should be terminated and mechanical ventilation resumed if failure criteria are met.',
    difficulty: 2,
    topic: 'Weaning & Liberation',
    isFree: false,
    orderIndex: 98,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'When is tracheostomy typically considered for mechanically ventilated patients?',
    answer: 'Tracheostomy is generally considered after 10-14 days of mechanical ventilation when prolonged ventilation is anticipated. Benefits include improved patient comfort, easier oral care, reduced sedation requirements, facilitation of weaning, and potential for speech and oral feeding. Early tracheostomy (within 7 days) remains controversial.',
    difficulty: 2,
    topic: 'Weaning & Liberation',
    isFree: false,
    orderIndex: 99,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What defines prolonged mechanical ventilation and what are key management strategies?',
    answer: 'Prolonged mechanical ventilation is generally defined as ventilator dependence for 21 days or more for at least 6 hours per day. Management focuses on gradual conditioning of respiratory muscles through progressive reduction of ventilator support, optimizing nutrition, treating infections, addressing psychological barriers, and early mobilization to prevent further deconditioning.',
    difficulty: 2,
    topic: 'Weaning & Liberation',
    isFree: false,
    orderIndex: 100,
  },
]

async function main() {
  console.log('Seeding ACCS flashcards (Batch 1: cards 1-100)...')
  console.log(`Total cards to insert: ${flashcards.length}`)

  // Verify the division exists
  const division = await prisma.division.findUnique({
    where: { id: ACCS_DIVISION_ID },
  })

  if (!division) {
    console.error(
      `Division ${ACCS_DIVISION_ID} not found. Run seed-divisions.ts first.`
    )
    process.exit(1)
  }

  console.log(`Found division: ${division.name}`)

  // Delete existing flashcards for this division to avoid duplicates on re-run
  const deleted = await prisma.flashcard.deleteMany({
    where: { divisionId: ACCS_DIVISION_ID },
  })
  console.log(`Cleared ${deleted.count} existing flashcards for ACCS division.`)

  // Insert all flashcards
  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })

  console.log(`Successfully inserted ${result.count} ACCS flashcards.`)

  // Log summary by topic
  const topicCounts: Record<string, number> = {}
  const difficultyCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0 }
  let freeCount = 0

  for (const card of flashcards) {
    topicCounts[card.topic] = (topicCounts[card.topic] || 0) + 1
    difficultyCounts[card.difficulty]++
    if (card.isFree) freeCount++
  }

  console.log('\n--- Summary ---')
  console.log('By topic:')
  for (const [topic, count] of Object.entries(topicCounts)) {
    console.log(`  ${topic}: ${count} cards`)
  }
  console.log('By difficulty:')
  console.log(`  Easy (1): ${difficultyCounts[1]}`)
  console.log(`  Medium (2): ${difficultyCounts[2]}`)
  console.log(`  Hard (3): ${difficultyCounts[3]}`)
  console.log(`Free cards: ${freeCount}`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
