import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const SDS_DIVISION_ID = 'cmsm41fwz0003zf54l0h5llrr'

const flashcards = [
  // ============================================================
  // COMPLEX CASE INTERPRETATION (cards 201-220)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient with heart failure and obesity has an AHI of 35 with a mix of obstructive and central events. How do you determine the predominant apnea type, and why does it matter for treatment selection?',
    answer: 'Classify each event individually using AASM criteria based on respiratory effort signals. If more than 50% of events are central, the patient has predominantly central sleep apnea. This distinction is critical because CPAP treats obstructive events but may be insufficient or even worsen central events. Predominantly central apnea in heart failure may require adaptive servo-ventilation (if EF is above 45%) or optimization of cardiac medications. A split pattern may respond to CPAP initially, with reassessment after cardiac optimization.',
    difficulty: 3,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 201,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'During a PSG, you notice rhythmic 1-Hz artifact obscuring the EEG channels. What is the likely source, and how do you differentiate it from true cerebral activity?',
    answer: 'Rhythmic 1-Hz artifact is most commonly caused by respiratory or ballistocardiographic artifact. Differentiate it from true cerebral activity by checking whether the rhythm correlates with the respiratory effort channels or heart rate. True EEG activity will be present across appropriate derivations with typical morphology, while artifact will appear simultaneously in non-cerebral channels (EOG, EMG) and lack the spatial distribution expected of genuine brain waves. Electrode impedance checks and repositioning can confirm the source.',
    difficulty: 2,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 202,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient on chronic opioid therapy has an AHI of 22 with an ataxic (Biot) breathing pattern during NREM sleep. What is the clinical significance, and what treatment approach is recommended?',
    answer: 'Ataxic or Biot breathing is an irregular, unpredictable respiratory pattern commonly seen with chronic opioid use, reflecting brainstem respiratory center depression. Unlike Cheyne-Stokes respiration, it lacks the crescendo-decrescendo pattern. Standard CPAP is often insufficient because the underlying drive is impaired. Treatment options include bilevel PAP with a backup rate (bilevel ST) or adaptive servo-ventilation (though evidence is mixed in opioid-induced CSA). Opioid dose reduction, when clinically possible, is the most effective intervention.',
    difficulty: 3,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 203,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do you distinguish true REM sleep from an epoch contaminated by eye blink artifact overlying a low-amplitude mixed-frequency EEG?',
    answer: 'True REM sleep shows conjugate, irregular, sharply-peaked rapid eye movements in EOG channels with low chin EMG tone and a low-amplitude mixed-frequency EEG. Eye blinks produce synchronous vertical deflections that are identical in polarity in both EOG channels, typically occur during wakefulness, and are accompanied by higher muscle tone. Additionally, sawtooth waves (2-6 Hz theta notched waves) in central EEG leads support a REM designation, while alpha activity with eye blinks supports wake.',
    difficulty: 2,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 204,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient with COPD and OSA (overlap syndrome) shows sustained SpO2 of 82% during REM sleep despite an AHI of only 8. How should this finding be interpreted and managed?',
    answer: 'In overlap syndrome, desaturation severity is disproportionate to the AHI because COPD-related hypoventilation and V/Q mismatch compound the intermittent obstruction. REM-related hypoventilation worsens the baseline hypoxemia from COPD. Management requires CPAP for the obstructive component plus supplemental oxygen for sustained hypoxemia. If hypercapnia is present, bilevel PAP may be needed. Nocturnal oxygen saturation monitoring should continue on treatment to confirm resolution of sustained desaturation, not just normalization of AHI.',
    difficulty: 3,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 205,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is treatment-emergent central sleep apnea (complex sleep apnea), and how should it be managed when identified during a CPAP titration?',
    answer: 'Treatment-emergent CSA occurs when central apneas develop or persist after obstructive events are eliminated by CPAP. It occurs in approximately 5-15% of OSA patients starting CPAP. During titration, continue CPAP at the pressure that eliminates obstructive events and document the central events. In most cases (approximately 50-80%), treatment-emergent CSA resolves spontaneously within weeks to months of continued CPAP use. If it persists beyond 2-3 months, consider switching to adaptive servo-ventilation or bilevel ST.',
    difficulty: 2,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 206,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient with a BMI of 52 and OHS is on bilevel PAP but continues to have morning headaches and an elevated serum bicarbonate. What does this suggest, and what is the next step?',
    answer: 'Persistent morning headaches and elevated serum bicarbonate suggest inadequate ventilation with ongoing nocturnal hypercapnia despite bilevel PAP. The next step is to obtain nocturnal transcutaneous or end-tidal CO2 monitoring while the patient uses the device. If CO2 remains elevated, increase the pressure support (difference between IPAP and EPAP), adjust the backup rate if using bilevel ST mode, or consider switching to volume-assured pressure support (VAPS/AVAPS) which automatically adjusts IPAP to maintain a target tidal volume.',
    difficulty: 3,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 207,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does 60-Hz electrical interference present on a PSG tracing, and what steps should the technologist take to eliminate it?',
    answer: '60-Hz interference appears as a uniform, sinusoidal waveform superimposed on the EEG, EOG, or EMG channels. It creates a thick, fuzzy baseline when the sweep speed is too slow to resolve individual cycles. To eliminate it: check and reduce all electrode impedances to below 5 kohms, ensure electrode wires are not crossing AC power cables, verify proper grounding of the patient and equipment, move electronic devices away from electrode wires, use twisted-pair electrode cables, and as a last resort apply a 60-Hz notch filter (understanding it may attenuate some biological signals).',
    difficulty: 1,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 208,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient with atrial fibrillation undergoes PSG. How does the irregular cardiac rhythm affect scoring of respiratory events and identification of cardiac arrhythmias during sleep?',
    answer: 'Atrial fibrillation creates an irregularly irregular heart rate that can make pulse oximetry readings unreliable due to signal averaging difficulties, potentially causing false desaturations or missed true desaturations. ECG artifact from atrial fibrillation can contaminate EEG channels. For scoring, the technologist should note the arrhythmia and rely more heavily on nasal pressure and thermal airflow signals than SpO2 for respiratory event identification. New-onset or worsening atrial fibrillation during sleep may indicate severe OSA and should be reported to the ordering physician.',
    difficulty: 2,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 209,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient with well-treated OSA on CPAP at 12 cmH2O reports return of daytime sleepiness. The CPAP download shows good adherence (7 hours/night, 95th percentile) with a residual AHI of 1.2. What differential diagnoses should be considered?',
    answer: 'With good CPAP adherence and a low residual AHI, alternative causes of persistent sleepiness include: insufficient sleep syndrome (assess total sleep time and sleep hygiene), comorbid narcolepsy (consider MSLT), periodic limb movement disorder (review CPAP data or repeat PSG), comorbid insomnia, depression or other psychiatric conditions, hypothyroidism, medication side effects (sedating medications), and idiopathic hypersomnia. Evaluate with detailed sleep history, sleep diary, actigraphy, and targeted laboratory tests before considering an MSLT.',
    difficulty: 2,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 210,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do you interpret a PSG showing repetitive short-duration central apneas with a crescendo-decrescendo ventilatory pattern and a cycle length of 60-90 seconds?',
    answer: 'This pattern is Cheyne-Stokes respiration (CSR), characterized by a waxing-waning tidal volume with interposed central apneas. The 60-90 second cycle length is typical and reflects prolonged circulatory time. CSR is most commonly associated with heart failure (reduced ejection fraction), stroke, or renal failure. It differs from other forms of CSA by its predictable, regular crescendo-decrescendo morphology. At least 3 consecutive cycles with a cycle length of at least 40 seconds and at least 5 central apneas/hypopneas per hour are required for the AASM diagnosis.',
    difficulty: 2,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 211,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient with epilepsy has nocturnal seizures captured during PSG. How are ictal events distinguished from normal sleep phenomena such as hypnagogic hypersynchrony or vertex sharp waves?',
    answer: 'Ictal EEG activity typically shows rhythmic, evolving patterns that increase in frequency, amplitude, or distribution over seconds to minutes, often followed by post-ictal slowing. Hypnagogic hypersynchrony is a brief burst of high-amplitude theta/delta in children during drowsiness that does not evolve. Vertex sharp waves are centrally maximal, surface-negative transients occurring in N1 sleep. Seizures are often accompanied by motor manifestations (captured on EMG and video), autonomic changes (heart rate, desaturation), and disrupt the normal sleep EEG architecture.',
    difficulty: 3,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 212,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient on CPAP at 15 cmH2O develops aerophagia with bloating and abdominal discomfort. What strategies can address this while maintaining airway patency?',
    answer: 'Aerophagia management strategies include: reducing the CPAP pressure if the current setting exceeds what is needed (repeat titration may be warranted), switching to APAP to allow lower average pressures, adding expiratory pressure relief (EPR/C-Flex), trying bilevel PAP with a lower EPAP, changing sleep position (elevating the head of bed may reduce swallowing of air), treating any concurrent GERD, or using a chinstrap if mouth leak is contributing to air swallowing. If aerophagia persists at therapeutic pressures, consider alternative therapies such as an oral appliance.',
    difficulty: 1,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 213,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the significance of REM-predominant OSA, and how does it affect clinical decision-making?',
    answer: 'REM-predominant OSA is defined as an overall AHI below 5 or mild range, but with a REM AHI at least double the NREM AHI (some definitions require REM AHI above 10). It is more common in women, younger patients, and those with lower BMI. It is clinically significant because REM-associated events tend to produce more severe desaturation and may contribute to cardiometabolic risk. Standard split-night studies may miss it if insufficient REM sleep is recorded. Positional therapy is less effective since REM events are less position-dependent. CPAP or APAP remains effective treatment.',
    difficulty: 2,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 214,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient with neuromuscular disease (ALS) presents with orthopnea and morning headaches. The PSG shows an AHI of 6 with prolonged episodes of hypoxemia during REM sleep without discrete apneas or hypopneas. What is the diagnosis, and what is the treatment?',
    answer: 'This presentation indicates sleep-related hypoventilation due to diaphragmatic weakness. In neuromuscular disease, the diaphragm becomes the primary ventilatory muscle during REM sleep when intercostal and accessory muscles are atonic. Failure of the weakened diaphragm leads to sustained hypoxemia without discrete obstructive events. The diagnosis requires confirmation with CO2 monitoring showing elevated PtcCO2 or PetCO2. Treatment is noninvasive ventilation with bilevel PAP in spontaneous-timed (ST) mode with a backup rate, not CPAP, as the issue is ventilatory failure rather than airway obstruction.',
    difficulty: 3,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 215,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the clinical significance of a saw-tooth desaturation pattern versus a sustained low-baseline desaturation pattern on overnight oximetry?',
    answer: 'A saw-tooth desaturation pattern (repetitive cyclical dips and recoveries of 3-4% or more) is characteristic of obstructive sleep apnea, where each desaturation corresponds to an apnea or hypopnea followed by reoxygenation with arousal. A sustained low-baseline pattern (continuous SpO2 below 90% without cyclical variation) suggests hypoventilation, COPD, or obesity hypoventilation syndrome. Overlap syndrome may show both patterns. This distinction guides treatment: the saw-tooth pattern responds to CPAP, while sustained hypoxemia may require bilevel PAP and/or supplemental oxygen.',
    difficulty: 1,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 216,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A PSG shows high-amplitude slow eye movements in a patient with an EEG showing alpha rhythm. How should this epoch be scored, and what does this combination suggest?',
    answer: 'Slow eye movements (SEMs) with a persistent alpha rhythm should be scored as stage W (wake), not N1. SEMs typically begin during drowsiness as the alpha rhythm attenuates, marking the transition from wake to N1. However, if the alpha rhythm occupies more than 50% of the epoch, the epoch remains wake regardless of SEMs. This combination can be seen in patients who are drowsy but not yet asleep, or in patients with alpha-intrusion patterns. The key rule is that alpha rhythm predominance always takes scoring precedence over SEMs.',
    difficulty: 1,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 217,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient with treated OSA on CPAP has a residual AHI of 3 but a persistent oxygen desaturation index (ODI) of 18. What could explain the discrepancy between AHI and ODI?',
    answer: 'A low AHI with a persistently elevated ODI suggests desaturations unrelated to scored apneas and hypopneas. Causes include: mask leak causing intermittent pressure loss and transient desaturation not meeting hypopnea duration criteria, concurrent lung disease causing V/Q mismatch, hypoventilation from obesity or neuromuscular disease, cardiac shunting, periodic breathing not meeting central apnea scoring criteria, or pulse oximeter artifact. Evaluation should include review of mask fit and leak data, assessment for comorbid pulmonary disease (PFTs, ABG), and nocturnal CO2 monitoring.',
    difficulty: 3,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 218,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does body position affect the interpretation of PSG results, and when is positional OSA diagnosed?',
    answer: 'Positional OSA is diagnosed when the supine AHI is at least twice the non-supine AHI (some definitions require the non-supine AHI to be below 5). Body position data must be documented and analyzed separately because many patients have significantly worse OSA when supine due to gravitational effects on the tongue and soft palate. Positional OSA is more common with lower BMI, lower overall AHI severity, and younger age. Recognizing positional dependence is important because these patients may benefit from positional therapy (devices that prevent supine sleep) as an alternative or adjunct to CPAP.',
    difficulty: 1,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 219,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'A patient referred for PAP titration reports that CPAP "makes my breathing worse." The titration shows central apneas emerging at 10 cmH2O that were not present on the diagnostic study. What is the mechanism, and what are the options?',
    answer: 'CPAP can induce central apneas through several mechanisms: increased lung volume raises PaCO2 clearance efficiency, pushing CO2 below the apneic threshold; elimination of upper airway resistance reflexes that stimulate ventilatory drive; and activation of pulmonary stretch receptors (Hering-Breuer reflex) that inhibit inspiration. Options include continuing CPAP at the lowest effective pressure for obstructive events while monitoring for spontaneous resolution over 4-8 weeks, switching to bilevel ST with a backup rate, or transitioning to adaptive servo-ventilation if events persist.',
    difficulty: 3,
    topic: 'Complex Case Interpretation',
    isFree: false,
    orderIndex: 220,
  },

  // ============================================================
  // ADVANCED RESPIRATORY MONITORING IN SLEEP (cards 221-235)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is end-tidal CO2 (PetCO2) monitoring, and what are its advantages and limitations in the sleep laboratory?',
    answer: 'PetCO2 monitoring uses a nasal cannula with an infrared CO2 analyzer to measure the peak CO2 concentration at the end of exhalation, which approximates alveolar CO2. Advantages include breath-by-breath trending, noninvasive application, and real-time assessment of ventilatory adequacy. Limitations include inaccuracy with mouth breathing, high supplemental oxygen flow diluting the sample, nasal obstruction, and poor correlation with PaCO2 in patients with significant V/Q mismatch or COPD. In pediatric sleep studies, PetCO2 monitoring is considered standard practice for detecting hypoventilation.',
    difficulty: 1,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 221,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does transcutaneous CO2 (PtcCO2) monitoring work, and when is it preferred over end-tidal CO2 monitoring?',
    answer: 'PtcCO2 monitoring uses a heated sensor (typically 42-44 degrees Celsius) placed on the skin to measure CO2 diffusing through tissue. Heating arterializes the capillary bed, allowing the sensor to approximate arterial PaCO2 (though PtcCO2 typically reads slightly higher due to tissue metabolism). It is preferred over PetCO2 when patients are on PAP therapy (where exhaled gas sampling is difficult), have significant mouth breathing, require supplemental oxygen (which dilutes PetCO2), or have COPD where PetCO2 underestimates PaCO2. It requires calibration and has a slower response time than PetCO2.',
    difficulty: 1,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 222,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What AASM criteria define sleep-related hypoventilation using CO2 monitoring?',
    answer: 'The AASM defines sleep-related hypoventilation as an increase in PaCO2 (or surrogate such as PtcCO2 or PetCO2) to a value greater than 55 mmHg for at least 10 minutes, OR an increase of 10 mmHg or more above the awake supine value to a level exceeding 50 mmHg for at least 10 minutes. In pediatric patients, hypoventilation is defined as PetCO2 or PtcCO2 greater than 50 mmHg for more than 25% of total sleep time. These criteria emphasize that a single elevated value is insufficient; sustained elevation is required.',
    difficulty: 2,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 223,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do you distinguish true oxygen desaturation from pulse oximetry artifact on a PSG?',
    answer: 'True desaturation correlates with respiratory events (apneas or hypopneas on airflow channels), occurs with a physiologic time delay of 10-30 seconds after the respiratory event, and shows a smooth descent-recovery pattern. Artifact features include abrupt square-wave drops without corresponding respiratory events, loss of pulse waveform quality on the plethysmograph, correlation with patient movement (signal loss during position changes), absence of heart rate changes expected with true desaturation, and isolated probe disconnection events. Checking the plethysmographic waveform quality and perfusion index is the most reliable way to verify signal validity.',
    difficulty: 1,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 224,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is respiratory inductance plethysmography (RIP), and how are the thoracic and abdominal bands used to characterize respiratory events?',
    answer: 'RIP uses sinusoidal coils embedded in elastic bands around the thorax and abdomen that generate signals proportional to changes in cross-sectional area during breathing. When calibrated, the sum of the two signals approximates tidal volume. In-phase (synchronous) movement of both bands indicates normal unobstructed breathing. Paradoxical (out-of-phase) movement indicates obstructive events, as the diaphragm descends (abdomen expands) while the chest wall is pulled inward against a closed airway. Absent excursion in both bands indicates central apnea. RIP is the recommended effort sensor per AASM guidelines.',
    difficulty: 1,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 225,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is esophageal pressure (Pes) monitoring, and why is it considered the gold standard for measuring respiratory effort during sleep?',
    answer: 'Pes monitoring uses a thin catheter with a pressure transducer placed in the lower esophagus to directly measure intrathoracic pressure changes. It is the gold standard because it quantifies actual inspiratory effort in cmH2O, detecting even subtle increases in effort that surface sensors may miss. Normal Pes swings are -5 to -8 cmH2O; values more negative than -10 cmH2O during inspiration suggest increased upper airway resistance. It is essential for diagnosing upper airway resistance syndrome (UARS), where flow limitation and effort-related arousals occur without meeting apnea or hypopnea criteria.',
    difficulty: 2,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 226,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What respiratory pattern on RIP bands is characteristic of upper airway resistance syndrome, and how does it differ from frank obstructive hypopneas?',
    answer: 'In upper airway resistance syndrome, the RIP bands show increasing paradoxical or out-of-phase movement (progressive flattening of the nasal pressure flow signal) culminating in an arousal, but without a 30% or greater reduction in airflow amplitude lasting 10 seconds. This pattern is called a respiratory effort-related arousal (RERA). In contrast, obstructive hypopneas meet the 30% or greater airflow reduction for at least 10 seconds with either a 3% desaturation or an arousal. Both conditions show flow limitation, but RERAs reflect a subclinical degree of obstruction that is clinically significant in terms of sleep fragmentation.',
    difficulty: 3,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 227,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does supplemental oxygen affect the reliability of SpO2 as an indicator of respiratory events during a PSG?',
    answer: 'Supplemental oxygen shifts the oxyhemoglobin dissociation curve to the left, meaning that the patient maintains higher SpO2 levels despite the same degree of airflow reduction. This can mask the 3% desaturation criterion for scoring hypopneas, potentially lowering the AHI even though the mechanical obstruction and arousals are unchanged. The nasal pressure and RIP channels remain unaffected and should be used as the primary indicators of respiratory events. When oxygen is administered during a PSG or titration, it is essential to note that the AHI may underestimate true disease severity if relying on desaturation-based scoring.',
    difficulty: 2,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 228,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the forced oscillation technique (FOT) in the context of sleep-disordered breathing, and what information does it provide?',
    answer: 'FOT applies small-amplitude pressure oscillations at the airway opening during spontaneous breathing and measures the resulting impedance (resistance and reactance) of the respiratory system. During sleep, increasing upper airway resistance or narrowing is detected as rising resistance values before frank apnea or hypopnea occurs. FOT can detect flow limitation and airway narrowing in real time without requiring patient effort, making it useful for research into upper airway mechanics. It is not yet standard in clinical PSG but is used in some advanced PAP devices to detect and respond to airway impedance changes.',
    difficulty: 3,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 229,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What factors cause falsely low SpO2 readings on pulse oximetry during a sleep study?',
    answer: 'Factors causing falsely low SpO2 include poor peripheral perfusion (cold extremities, Raynaud phenomenon), motion artifact from patient movement, venous pulsation (right heart failure causing venous congestion), dark nail polish (particularly blue, green, or black), deeply pigmented skin in some clinical scenarios, methemoglobinemia (reads approximately 85% regardless of true saturation), sensor malposition, and ambient light interference. Signal quality should be verified using the plethysmographic waveform; a poor-quality waveform suggests the SpO2 value is unreliable.',
    difficulty: 1,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 230,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the significance of the nasal pressure transducer signal flattening index in detecting subtle sleep-disordered breathing?',
    answer: 'The flattening index quantifies the degree of inspiratory flow limitation by comparing the shape of the nasal pressure transducer waveform to a reference sinusoidal waveform. A normal breath has a rounded inspiratory peak, while a flow-limited breath shows progressive flattening (plateau). The flattening index ranges from 0 (completely flat, maximal flow limitation) to 1 (normal rounded contour). This metric is used in auto-titrating PAP algorithms to detect and respond to flow limitation before frank apneas or hypopneas occur, enabling proactive pressure adjustments.',
    difficulty: 3,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 231,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'Why is a thermal airflow sensor (oronasal thermistor) still required in PSG when a nasal pressure transducer is also used?',
    answer: 'The thermal airflow sensor (thermistor or thermocouple) detects airflow by sensing temperature changes between inspired and expired air at the nose and mouth. It is required because it is the recommended sensor for scoring apneas (complete cessation of airflow), as the nasal pressure signal can be lost entirely during mouth breathing or with sensor displacement. Conversely, the nasal pressure transducer is recommended for scoring hypopneas because it provides a semi-quantitative flow signal with better sensitivity to subtle airflow reductions. Using both sensors together ensures accurate event detection.',
    difficulty: 1,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 232,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does high-altitude affect respiratory monitoring during sleep, and what sleep-disordered breathing patterns are commonly seen?',
    answer: 'At altitudes above 2,500 meters, reduced barometric pressure lowers inspired PO2, triggering hyperventilation through peripheral chemoreceptor stimulation. This drives PaCO2 below the apneic threshold, producing periodic breathing with central apneas (high-altitude periodic breathing). SpO2 baseline is lower, and cyclical desaturations accompany the periodic breathing. The central apnea index increases with altitude. This pattern is distinct from OSA and typically resolves with acclimatization or descent. Acetazolamide, which induces metabolic acidosis and stabilizes ventilatory control, is an effective treatment.',
    difficulty: 1,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 233,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the clinical utility of diaphragm EMG monitoring during sleep studies, and in what patient populations is it most valuable?',
    answer: 'Diaphragm EMG (recorded via surface electrodes over the lower intercostal spaces or via an esophageal electrode) directly measures phrenic nerve-driven diaphragmatic muscle activity during inspiration. It is most valuable in patients with neuromuscular disease (ALS, muscular dystrophy, phrenic nerve palsy) where standard RIP belts may not accurately reflect central respiratory drive. Diaphragm EMG can detect reduced or absent diaphragmatic recruitment during REM sleep, confirm central versus obstructive events when RIP signals are ambiguous, and quantify the degree of respiratory muscle weakness during sleep.',
    difficulty: 3,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 234,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the oxygen desaturation index (ODI), and how does it complement the AHI in characterizing sleep-disordered breathing severity?',
    answer: 'The ODI is the number of oxygen desaturation events (typically defined as a 3% or 4% drop from baseline SpO2) per hour of sleep. It complements the AHI because the two measures can diverge: a patient may have a moderate AHI but a high ODI if events cause profound desaturations, indicating greater hypoxic burden and cardiovascular risk. Conversely, a patient with many RERAs may have a high respiratory disturbance index but a low ODI. Recent research suggests that the hypoxic burden (area under the desaturation curve) may better predict cardiovascular outcomes than either AHI or ODI alone.',
    difficulty: 2,
    topic: 'Advanced Respiratory Monitoring',
    isFree: false,
    orderIndex: 235,
  },

  // ============================================================
  // SURGICAL & PROCEDURAL SLEEP INTERVENTIONS (cards 236-250)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is uvulopalatopharyngoplasty (UPPP), and what is its reported success rate for treating OSA?',
    answer: 'UPPP involves surgical excision of the uvula, posterior soft palate margin, redundant pharyngeal tissue, and often the tonsils to enlarge the retropalatal airway. Its reported success rate (defined as a 50% or greater reduction in AHI to below 20) is approximately 40-50% as a standalone procedure. Success rates are higher in patients with isolated retropalatal obstruction, lower BMI, and mild-to-moderate OSA. UPPP does not address tongue base collapse or lateral wall collapse. It may compromise future PAP therapy by increasing oral air leak if the velopharyngeal seal is altered.',
    difficulty: 1,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 236,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is maxillomandibular advancement (MMA) surgery, and for which OSA patients is it most appropriate?',
    answer: 'MMA involves bilateral sagittal split osteotomy of the mandible and Le Fort I osteotomy of the maxilla to advance both jaws forward by 10-12 mm, thereby expanding the entire posterior airway space at both the retropalatal and retroglossal levels. It is most appropriate for patients with moderate-to-severe OSA who have craniofacial abnormality (retrognathia, micrognathia), those who have failed CPAP and other surgical interventions, or as a primary surgical option in selected cases. MMA has the highest success rate of all upper airway surgeries (85-90%), with significant and durable AHI reduction.',
    difficulty: 2,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 237,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does hypoglossal nerve stimulation (Inspire therapy) work, and what are the selection criteria for candidates?',
    answer: 'Hypoglossal nerve stimulation uses an implanted pulse generator that delivers electrical stimulation to the medial branches of the hypoglossal nerve during inspiration, protruding the tongue forward to open the retroglossal airway. Selection criteria include: moderate-to-severe OSA (AHI 15-65), failure of or inability to tolerate CPAP, BMI at or below 40 (recently expanded from 32), no concentric collapse at the velopharyngeal level on drug-induced sleep endoscopy (DISE), and absence of significant central sleep apnea (central apnea index below 25% of total AHI). The device senses respiratory effort to synchronize stimulation with inspiration.',
    difficulty: 2,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 238,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'Why is drug-induced sleep endoscopy (DISE) performed before hypoglossal nerve stimulation implantation, and what finding is a contraindication?',
    answer: 'DISE is performed to visualize the pattern and level of upper airway collapse during simulated sleep (using propofol or midazolam sedation). Before hypoglossal nerve stimulation, DISE identifies the site(s) of obstruction. Complete concentric collapse (CCC) at the velopharyngeal (soft palate) level is a contraindication because hypoglossal nerve stimulation only addresses tongue base obstruction and cannot overcome circumferential palatal collapse. Patients with anteroposterior palatal collapse or lateral wall collapse without CCC may still benefit. DISE also helps identify multi-level obstruction for surgical planning.',
    difficulty: 2,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 239,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What effect does bariatric surgery have on obstructive sleep apnea, and does it eliminate the need for PAP therapy?',
    answer: 'Bariatric surgery typically produces significant weight loss (50-70% of excess body weight) and reduces AHI by 50-75% on average. Studies show that approximately 75-80% of bariatric surgery patients have improvement in OSA severity. However, complete resolution (AHI below 5) occurs in only about 25-40% of patients. Therefore, bariatric surgery should not be assumed to eliminate the need for PAP therapy. Post-surgical sleep testing is recommended to reassess OSA severity and adjust PAP pressure. Residual OSA is common, particularly in patients with craniofacial risk factors independent of weight.',
    difficulty: 2,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 240,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'When is tracheostomy indicated for the treatment of obstructive sleep apnea, and why is it considered the most effective surgical intervention?',
    answer: 'Tracheostomy is indicated for life-threatening OSA refractory to all other treatments, morbid obesity with severe OSA and inability to tolerate PAP, craniofacial abnormalities preventing effective PAP use, and as a temporizing measure before definitive surgery. It is the most effective surgical intervention because it completely bypasses the upper airway obstruction by creating an airway below the level of collapse. The tracheostomy tube is plugged during the day for normal phonation and uncapped during sleep. Its use has decreased substantially with improved PAP technology and alternative surgical options.',
    difficulty: 1,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 241,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the role of tonsillectomy and adenoidectomy in pediatric versus adult OSA?',
    answer: 'In pediatric OSA, adenotonsillectomy is the first-line treatment because adenotonsillar hypertrophy is the most common cause of upper airway obstruction in children. It resolves OSA in approximately 70-80% of otherwise healthy children, though residual OSA is more common in obese children. In adults, tonsillectomy alone (for grade 3-4 tonsils) can reduce AHI but is rarely curative as a standalone procedure because adult OSA is typically multifactorial (retropalatal, retroglossal, and lateral wall collapse). It is often performed as part of multi-level surgery or concurrent with UPPP.',
    difficulty: 1,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 242,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the key differences between a custom-fitted mandibular advancement device (MAD) and an over-the-counter boil-and-bite oral appliance for OSA treatment?',
    answer: 'Custom-fitted MADs are fabricated by a dentist trained in dental sleep medicine using dental impressions or digital scans. They offer precise, incremental mandibular advancement (titratability), better retention and comfort, and are supported by clinical evidence for efficacy. Over-the-counter devices lack titratability, have poor retention leading to lower adherence, are not recommended by the AASM for OSA treatment, and may cause temporomandibular joint problems due to poor fit. AASM guidelines recommend only custom, titratable devices prescribed by a qualified dentist, with follow-up sleep testing to confirm efficacy.',
    difficulty: 1,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 243,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What follow-up is required after initiating oral appliance therapy for OSA, and what side effects should be monitored?',
    answer: 'Follow-up requires an objective sleep test (PSG or HSAT) with the appliance in place at the final titrated position to confirm therapeutic efficacy. Ongoing monitoring includes regular dental examinations every 6-12 months for occlusal changes (development of an anterior open bite or changes in overjet), temporomandibular joint symptoms (pain, clicking, limited opening), excessive salivation or dry mouth, tooth soreness, and appliance integrity. Long-term dental changes occur in a significant proportion of patients and may be irreversible, necessitating informed consent and periodic cephalometric radiographs in some protocols.',
    difficulty: 2,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 244,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the Friedman tongue position staging system, and how does it predict surgical outcomes for UPPP?',
    answer: 'The Friedman staging system classifies patients based on tongue position (modified Mallampati I-IV), tonsil size (1-4), and BMI. Stage I patients (Mallampati I-II, tonsil size 3-4, BMI below 40) have the best predicted UPPP success rate (approximately 80%). Stage II (intermediate features) has approximately 37% success. Stage III (Mallampati III-IV, small tonsils, BMI above 40) has the lowest success rate (approximately 8%). This staging system helps select appropriate surgical candidates and set realistic expectations, directing Stage III patients toward alternative therapies such as PAP, oral appliances, or multi-level surgery.',
    difficulty: 3,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 245,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is transoral robotic surgery (TORS) for OSA, and what is its role in multi-level surgical approaches?',
    answer: 'TORS uses a surgical robot to access and resect tissue at the tongue base and epiglottis through the mouth without external incisions. It addresses retroglossal and supraglottic obstruction that UPPP alone cannot treat. In multi-level surgery, TORS is combined with palatal procedures (UPPP or expansion sphincter pharyngoplasty) to address both retropalatal and retroglossal collapse. Studies report success rates of 60-80% when combined with palatal surgery. Advantages include improved visualization, precision, and shorter recovery compared to traditional open tongue base procedures.',
    difficulty: 3,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 246,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What perioperative risks are heightened in OSA patients undergoing any surgery, and what precautions are recommended?',
    answer: 'OSA patients face increased perioperative risks including difficult intubation (due to anatomical airway narrowing), heightened sensitivity to opioids and sedatives (risk of respiratory depression), postoperative airway obstruction, hypoxemia, atelectasis, cardiac arrhythmias, and prolonged ICU stays. Precautions include preoperative OSA screening (STOP-Bang), using regional anesthesia when possible, minimizing opioid use, continuous postoperative SpO2 monitoring, semi-upright positioning, having the patient bring their own CPAP device for postoperative use, and avoiding premature discharge. The ASA guidelines recommend PAP therapy be continued throughout the perioperative period.',
    difficulty: 1,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 247,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is expansion sphincter pharyngoplasty (ESP), and how does it differ from traditional UPPP?',
    answer: 'ESP is a modification of palatopharyngoplasty that rotates the palatopharyngeus muscle superolaterally and sutures it to the pterygoid hamulus, creating lateral tension to expand the velopharyngeal airway in an anteroposterior and lateral dimension. Unlike traditional UPPP, which primarily addresses anteroposterior narrowing by removing tissue, ESP addresses lateral pharyngeal wall collapse, which is a major contributor to OSA in many patients. ESP preserves more mucosal tissue, has a lower rate of velopharyngeal insufficiency, and some studies report higher success rates (60-80%) compared to traditional UPPP.',
    difficulty: 3,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 248,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the role of nasal surgery in the treatment of OSA?',
    answer: 'Nasal surgery (septoplasty, turbinate reduction, nasal valve repair) alone rarely cures OSA, as the nasal airway is not the primary site of obstruction in most patients. However, nasal surgery plays an important adjunctive role: it reduces nasal resistance, which can lower effective CPAP pressure requirements, improve PAP tolerance and adherence, reduce mouth breathing and oral leak, and improve subjective sleep quality. Nasal obstruction also contributes to snoring, which may improve significantly after surgery. Nasal surgery is often performed as part of multi-level surgical management or to optimize PAP therapy.',
    difficulty: 1,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 249,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the outcomes and considerations for weight loss interventions (medical and surgical) as treatment for OSA in obese patients?',
    answer: 'A 10% weight loss typically produces a 26-32% reduction in AHI. Medical weight loss programs achieve meaningful results but have high recidivism rates. Bariatric surgery produces greater and more sustained weight loss but requires lifelong nutritional monitoring. GLP-1 receptor agonists (semaglutide, tirzepatide) represent a newer pharmacological approach with significant weight loss and emerging evidence of OSA improvement. Key considerations include: weight loss alone may not resolve OSA completely, particularly in patients with craniofacial risk factors; PAP therapy should continue during the weight loss period; and repeat sleep testing is needed after stable weight loss to reassess treatment needs.',
    difficulty: 2,
    topic: 'Surgical & Procedural Interventions',
    isFree: false,
    orderIndex: 250,
  },

  // ============================================================
  // OCCUPATIONAL & LEGAL ASPECTS (cards 251-265)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the FMCSA screening recommendations for obstructive sleep apnea in commercial motor vehicle (CMV) drivers?',
    answer: 'The FMCSA recommends that medical examiners screen CMV drivers for OSA risk during the DOT physical examination. Drivers with a BMI of 35 or greater, or those with a BMI of 33 or greater plus additional risk factors (hypertension, diabetes, neck circumference greater than 17 inches in men or 15.5 inches in women, witnessed apneas, or excessive daytime sleepiness), should be referred for sleep testing. Diagnosed OSA drivers must demonstrate treatment compliance (minimum 4 hours per night on 70% of nights) to maintain medical certification. Noncompliance may result in loss of commercial driving privileges.',
    difficulty: 2,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 251,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the FAA regulations regarding obstructive sleep apnea for commercial pilots?',
    answer: 'The FAA requires airmen with a BMI of 40 or greater to be evaluated for OSA before medical certification. Pilots diagnosed with OSA must demonstrate treatment compliance and clinical improvement to maintain their medical certificate. They must provide documentation of CPAP compliance data showing adequate nightly usage, resolution of sleepiness symptoms, and annual recertification with updated compliance data. The Aviation Medical Examiner (AME) may defer certification to the FAA Aerospace Medical Certification Division for review. Untreated OSA is disqualifying for all classes of medical certificates.',
    difficulty: 2,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 252,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What medicolegal liability does a sleep medicine provider face when a patient with diagnosed OSA causes a drowsy driving accident?',
    answer: 'Providers may face liability if they fail to adequately warn the patient about drowsy driving risks, fail to document the counseling, fail to diagnose OSA when the clinical presentation was clear, or clear a patient for commercial driving without adequate assessment. The standard of care requires documenting that the patient was counseled about accident risk, advised not to drive while excessively sleepy, and informed about treatment options. In jurisdictions with mandatory reporting (few in the US but more common internationally), failure to report may create additional liability. Thorough documentation of risk discussion and treatment recommendations is the best protection.',
    difficulty: 3,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 253,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What statistics regarding drowsy driving highlight the public health significance of untreated sleep disorders?',
    answer: 'Drowsy driving accounts for an estimated 100,000 police-reported crashes, 71,000 injuries, and 1,550 fatalities annually in the United States according to NHTSA estimates (actual numbers are likely higher due to underreporting). Untreated OSA increases motor vehicle accident risk 2-3 fold compared to the general population. Drivers who sleep less than 4 hours have an 11.5-fold increased crash risk. Commercial drivers with untreated OSA have a 5-fold increase in preventable crashes. Effective CPAP treatment reduces accident risk to near-normal levels within weeks of initiating therapy.',
    difficulty: 1,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 254,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does the Americans with Disabilities Act (ADA) apply to employees with sleep disorders in the workplace?',
    answer: 'Under the ADA, sleep disorders such as narcolepsy and severe OSA may qualify as disabilities if they substantially limit major life activities (sleeping, concentrating, working). Employers with 15 or more employees must provide reasonable accommodations, which may include modified work schedules, shift reassignment (avoiding night shifts for circadian disorders), additional break periods, a private area for napping (narcolepsy), workspace modifications, and modified job duties that avoid safety-sensitive tasks during periods of uncontrolled sleepiness. The employee must disclose the condition and request accommodation. The employer is not required to eliminate essential job functions.',
    difficulty: 2,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 255,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What fitness-for-duty considerations apply to shift workers in safety-sensitive positions who have been diagnosed with shift work sleep disorder?',
    answer: 'Fitness-for-duty evaluations must assess whether the worker can safely perform essential job functions without excessive sleepiness. Considerations include: objective measurement of sleepiness (MSLT or psychomotor vigilance testing), adequacy of treatment (strategic napping, circadian adaptation strategies, wake-promoting agents), compliance with sleep hygiene recommendations for shift workers, the specific job hazards and risk tolerance, and documentation of improvement with treatment. Workers in safety-critical roles (pilots, heavy equipment operators, healthcare providers) may require formal clearance. Employers may need to consider shift modifications as a reasonable accommodation.',
    difficulty: 3,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 256,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What workplace accommodations might be recommended for a patient with narcolepsy?',
    answer: 'Recommended accommodations include scheduled daytime naps (15-20 minutes, typically 1-2 times per day), flexible scheduling to align with optimal alertness periods, avoidance of monotonous tasks during periods of peak sleepiness, modified job duties to avoid safety-sensitive operations during uncontrolled symptoms, a private rest area, permission to stand or move during meetings, reduced driving requirements, and ergonomic workstation modifications. The accommodations should be individualized based on symptom severity, medication response, and job requirements. Documentation from the treating sleep medicine provider supports the accommodation request.',
    difficulty: 1,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 257,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the key elements a sleep medicine provider should document to minimize medicolegal risk when managing a patient with OSA?',
    answer: 'Essential documentation includes: initial assessment findings and diagnostic results, explanation of the diagnosis and its health risks (cardiovascular, metabolic, accident risk), treatment options discussed with risks and benefits, specific counseling about drowsy driving (with the patient acknowledging understanding), treatment plan and rationale, compliance monitoring data, follow-up assessment of treatment response, documentation of patient refusal of treatment if applicable (with risks re-explained), and any referrals made. All discussions about driving restrictions or occupational safety should be explicitly documented in the medical record.',
    difficulty: 2,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 258,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do railroad industry regulations address sleep apnea screening and treatment for engineers and conductors?',
    answer: 'The Federal Railroad Administration (FRA) requires railroads to have medical fitness-for-duty programs. While there is no specific OSA screening mandate comparable to FMCSA guidelines, railroads have implemented their own screening programs, often using BMI thresholds and symptom questionnaires. Engineers and conductors diagnosed with OSA must demonstrate adequate treatment compliance. Hours-of-service regulations limit consecutive work hours and mandate minimum rest periods. The National Transportation Safety Board (NTSB) has cited untreated sleep apnea as a contributing factor in multiple rail accidents and has recommended mandatory screening for safety-sensitive railroad personnel.',
    difficulty: 2,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 259,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What role does the Maintenance of Wakefulness Test (MWT) play in occupational fitness-for-duty determinations?',
    answer: 'The MWT measures the ability to stay awake in a quiet, dark environment across four 40-minute trials. A mean sleep latency of less than 8 minutes is considered abnormal and indicates inability to maintain wakefulness. The MWT is used in occupational settings to objectively document whether a treated patient can sustain wakefulness, which is particularly relevant for commercial drivers, pilots, and safety-sensitive workers. Unlike the MSLT (which measures sleep propensity), the MWT directly assesses the functional ability to remain alert, making it more applicable to fitness-for-duty decisions. Some regulatory bodies accept MWT results as evidence of treatment adequacy.',
    difficulty: 2,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 260,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What informed consent elements are specific to polysomnography that distinguish it from general medical informed consent?',
    answer: 'PSG-specific informed consent should address: the nature and purpose of the study (diagnostic, titration, or split-night), the electrode and sensor application process, video and audio monitoring throughout the night, the possibility of skin irritation from electrode adhesives, the possibility of a technically inadequate study requiring repeat testing, potential discomfort from sleeping in an unfamiliar environment (first-night effect), the role of the sleep technologist during the study, conditions under which the technologist will intervene (severe desaturation, arrhythmia), and how results will be communicated. For PAP titrations, additional consent covers PAP mask application and pressure adjustments.',
    difficulty: 1,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 261,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the impact of untreated obstructive sleep apnea on workers\' compensation claims and occupational injury rates?',
    answer: 'Workers with untreated OSA have a 2-3 times higher rate of occupational injuries compared to workers without OSA. They have increased rates of workplace accidents, particularly those involving inattention, impaired judgment, and slowed reaction time. Untreated OSA has been associated with higher workers compensation costs, increased absenteeism, and reduced productivity (presenteeism). Some employers in high-risk industries have implemented OSA screening programs as part of occupational health because the cost of screening and treatment is offset by reduced injury claims and improved productivity.',
    difficulty: 1,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 262,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do state-level driving regulations for patients with sleep disorders differ across the United States?',
    answer: 'State regulations vary considerably. Most states do not have mandatory reporting requirements for physicians regarding patients with sleep disorders. A few states (such as California, Oregon, and Pennsylvania) have voluntary or mandatory physician reporting of conditions that impair driving ability. Some states require patients with narcolepsy or excessive daytime sleepiness to demonstrate treatment compliance before driver license renewal. The lack of uniform federal standards for non-commercial drivers creates a patchwork of regulations. Sleep medicine providers should be familiar with their state-specific reporting obligations and document drowsy driving counseling regardless of state requirements.',
    difficulty: 2,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 263,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What ethical considerations arise when an OSA patient refuses treatment but works in a safety-sensitive occupation?',
    answer: 'This situation creates tension between patient autonomy (the right to refuse treatment) and public safety (duty to warn or report). The provider should thoroughly document the risks explained to the patient, including accident risk to self and others. The provider should clearly communicate that the patient may not be fit for safety-sensitive duties while untreated. In most jurisdictions, there is no legal obligation for non-mandatory reporting, but the provider should consider whether a duty to warn exists. If the patient holds a commercial driver license, the DOT medical examiner may be unable to certify the patient. Documenting the refusal and counseling is essential.',
    difficulty: 3,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 264,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the economic burden of untreated sleep disorders in the workplace, and how does treatment affect productivity?',
    answer: 'Untreated sleep disorders cost the US economy an estimated 411 billion dollars annually in lost productivity (including presenteeism, absenteeism, and accidents). Workers with untreated insomnia lose approximately 11.3 days of productivity per year, while untreated OSA results in approximately 7-12 days of lost productivity annually. Treatment of OSA with CPAP has been shown to reduce healthcare costs by 50% over 2 years, reduce motor vehicle accident rates to near baseline, and improve workplace performance and cognitive function within weeks of adherence. Employer-sponsored sleep health programs show positive return on investment through reduced claims and improved output.',
    difficulty: 1,
    topic: 'Occupational & Legal Aspects',
    isFree: false,
    orderIndex: 265,
  },

  // ============================================================
  // ADVANCED PAP MODALITIES (cards 266-280)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is volume-assured pressure support (VAPS), and how do AVAPS and iVAPS differ in their algorithms?',
    answer: 'VAPS modes automatically adjust inspiratory pressure (IPAP) to maintain a target tidal volume or alveolar ventilation. AVAPS (Philips/Respironics) targets a set tidal volume and adjusts IPAP slowly (over minutes) between set IPAP min and max. iVAPS (ResMed) targets alveolar minute ventilation (calculated by subtracting estimated dead space ventilation) and adjusts more dynamically. Both modes provide a guaranteed minimum ventilation while allowing patient-triggered breaths. VAPS is indicated for patients with obesity hypoventilation, neuromuscular disease, or chronic hypoventilation where fixed bilevel may not maintain adequate ventilation across sleep stages.',
    difficulty: 3,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 266,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does auto-bilevel PAP differ from standard bilevel PAP and auto-CPAP?',
    answer: 'Auto-bilevel PAP automatically adjusts both IPAP and EPAP within preset ranges based on detected respiratory events. Standard bilevel PAP uses fixed IPAP and EPAP settings. Auto-CPAP adjusts a single continuous pressure. Auto-bilevel provides the benefits of bilevel therapy (pressure support for comfort and ventilation) while adapting to changing conditions across body positions and sleep stages. It is particularly useful for patients who require high pressures (where fixed high bilevel may cause aerophagia) or those with variable obstruction. Auto-bilevel maintains a set pressure support (IPAP minus EPAP difference) while auto-adjusting the overall pressure range.',
    difficulty: 2,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 267,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is adaptive servo-ventilation (ASV), and how does its algorithm respond to central apneas and Cheyne-Stokes respiration?',
    answer: 'ASV continuously analyzes the patient\'s breathing pattern and provides variable pressure support that is inversely proportional to the patient\'s own ventilatory effort. During hyperventilation phases of CSR, the device reduces or eliminates pressure support, allowing the natural drive to decrease. During hypoventilation or central apnea phases, it increases pressure support and delivers mandatory breaths at a calculated rate. The EPAP auto-adjusts to maintain upper airway patency. This "anti-cycling" algorithm stabilizes ventilation around a target minute ventilation. ASV is contraindicated in heart failure patients with LVEF of 45% or below due to increased mortality risk shown in the SERVE-HF trial.',
    difficulty: 3,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 268,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'Why is adaptive servo-ventilation contraindicated in patients with heart failure and reduced ejection fraction, and what is the evidence?',
    answer: 'The SERVE-HF trial (2015) demonstrated that ASV was associated with increased all-cause and cardiovascular mortality in patients with heart failure and LVEF of 45% or below who had predominantly central sleep apnea. The mechanism is hypothesized to involve suppression of compensatory hyperventilation in heart failure (CSR may serve a protective role by maintaining cardiac output through respiratory-driven venous return and sympathetic activation), or the positive pressure itself may worsen cardiac output in already compromised hearts. As a result, ASV is absolutely contraindicated when LVEF is 45% or below, and an echocardiogram should be obtained before initiating ASV in any patient with known or suspected heart failure.',
    difficulty: 2,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 269,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How is a backup respiratory rate determined during bilevel ST titration for central sleep apnea?',
    answer: 'The backup rate should be set just below the patient\'s spontaneous sleeping respiratory rate to provide support during central apneas without overriding spontaneous breathing. A typical starting point is 10-12 breaths per minute for adults. The rate should be high enough to prevent prolonged central apneas and maintain oxygen saturation but low enough to allow spontaneous breaths to dominate when present. During titration, increase the backup rate if central apneas persist with significant desaturation. In patients with obesity hypoventilation or neuromuscular disease, a higher backup rate (14-18) may be needed to ensure adequate minute ventilation during REM sleep.',
    difficulty: 2,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 270,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What strategies are used to manage patients who require very high CPAP pressures (above 15 cmH2O)?',
    answer: 'High-pressure strategies include: switching to bilevel PAP to provide a lower EPAP for comfort while maintaining adequate IPAP for airway patency; using auto-bilevel to minimize average pressure; adding chinstrap or full-face mask to reduce mouth leak at high pressures; optimizing nasal patency (nasal corticosteroids, nasal surgery) to reduce pressure requirements; addressing positional OSA with positional therapy to reduce supine time; encouraging weight loss; considering oral appliance therapy as an adjunct; and ensuring the mask seal can handle high pressures without excessive leak. High-pressure intolerance is one of the most common reasons for CPAP failure.',
    difficulty: 1,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 271,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the difference between spontaneous (S), timed (T), and spontaneous-timed (ST) modes on a bilevel PAP device?',
    answer: 'In Spontaneous (S) mode, the device cycles between IPAP and EPAP based on the patient\'s own inspiratory and expiratory efforts; no mandatory breaths are delivered. In Timed (T) mode, the device delivers breaths at a preset rate and inspiratory time regardless of patient effort, functioning like a pressure-controlled ventilator. In Spontaneous-Timed (ST) mode, the device follows the patient\'s spontaneous breaths but delivers a mandatory breath at the set backup rate if the patient fails to initiate a breath within the set time interval. ST mode is used for central sleep apnea and hypoventilation syndromes where respiratory drive may be impaired intermittently.',
    difficulty: 1,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 272,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does expiratory pressure relief (EPR, C-Flex, A-Flex) work, and what is its clinical benefit?',
    answer: 'Expiratory pressure relief transiently reduces the delivered pressure during early exhalation, making it easier for the patient to breathe out against the positive pressure. EPR (ResMed) offers settings of 1-3 cmH2O of pressure reduction. C-Flex (Philips) provides proportional pressure relief scaled to expiratory flow, while A-Flex adds pressure relief during both late inspiration and expiration. These features improve comfort and may enhance adherence, especially in patients who report difficulty exhaling against CPAP. They do not change the therapeutic pressure during inspiration, so efficacy for airway patency is maintained. They should not be confused with bilevel PAP, which provides separate IPAP and EPAP settings.',
    difficulty: 1,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 273,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the role of the ramp feature on PAP devices, and when might it be counterproductive?',
    answer: 'The ramp feature starts the device at a low comfortable pressure and gradually increases to the therapeutic pressure over a set period (typically 5-45 minutes), allowing the patient to fall asleep at a lower, more tolerable pressure. It can be counterproductive in patients who fall asleep quickly and may have obstructive events during the ramp period before therapeutic pressure is reached, in patients with severe OSA at low pressures who need full pressure immediately, or in patients with insomnia who may still be awake when the pressure ramps up and find the increasing pressure disturbing. Auto-ramp features that detect sleep onset and then increase pressure may address some of these limitations.',
    difficulty: 1,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 274,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What parameters should be reviewed when interpreting a PAP device download for a patient with persistent symptoms?',
    answer: 'Key parameters include: usage hours per night and percentage of nights used (adherence), residual AHI (broken down by obstructive, central, and unclassified events if available), 95th percentile pressure (for APAP devices, to assess if max pressure is being reached), mask leak rate (median and 95th percentile; high leak reduces effective pressure), pressure data trends (to identify positional or REM-related pressure needs), and large leak events (timing and duration). A high residual AHI with good adherence may indicate inadequate pressure, persistent central events, or mask leak artifact. Persistent high leak despite mask adjustment may require mask type change.',
    difficulty: 2,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 275,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does PAP therapy with supplemental oxygen entrainment work, and when is it indicated?',
    answer: 'Supplemental oxygen is entrained into the PAP circuit by connecting oxygen tubing to a port on the mask or the device outlet. The FiO2 delivered depends on the oxygen flow rate, PAP pressure, and mask leak. Higher PAP pressures dilute the supplemental oxygen more, reducing the effective FiO2. It is indicated when PAP alone does not resolve sustained hypoxemia, such as in overlap syndrome (COPD plus OSA), obesity hypoventilation with persistent desaturation despite adequate ventilatory support, or interstitial lung disease with concurrent OSA. The oxygen flow rate should be titrated during attended PSG to achieve target SpO2 above 88-90%.',
    difficulty: 2,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 276,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the inspiratory time (Ti) setting on bilevel PAP, and how does it affect ventilation and patient comfort?',
    answer: 'Inspiratory time (Ti) determines how long the device delivers IPAP before cycling to EPAP. A typical adult Ti is 0.8-1.2 seconds. A longer Ti increases the volume of pressure support delivered per breath and can improve tidal volume, but if too long, the patient may fight the device by trying to exhale during the IPAP phase (patient-ventilator asynchrony). A shorter Ti may not allow adequate tidal volume delivery. In ST mode, Ti sets the mandatory breath duration. Ti minimum and maximum settings on some devices constrain the spontaneous cycling to prevent auto-triggering or prolonged inspiration from leak.',
    difficulty: 3,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 277,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the rise time setting on bilevel PAP, and how should it be adjusted for patient comfort?',
    answer: 'Rise time controls how quickly the device transitions from EPAP to IPAP at the onset of inspiration. A shorter rise time (faster transition) delivers pressure support more quickly, which may benefit patients who feel air-hungry or have high ventilatory demands. A longer rise time (slower transition) provides a more gradual pressure increase that some patients find more comfortable and natural. Patients with COPD who are accustomed to breathing against resistance may prefer a longer rise time, while patients with restrictive disease or neuromuscular weakness may prefer a shorter rise time for more immediate ventilatory support. Typical settings range from 1 to 6 on a manufacturer-specific scale.',
    difficulty: 2,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 278,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does the auto-titrating algorithm in an APAP device detect and respond to obstructive respiratory events?',
    answer: 'APAP algorithms use a combination of inputs: vibration or snoring detection (early upper airway narrowing), inspiratory flow limitation (flattening of the flow waveform indicating increased resistance), apneas (cessation of flow), and hypopneas (reduction in flow amplitude). When flow limitation or snoring is detected, the device incrementally increases pressure to prevent progression to apnea. When events resolve, the device gradually decreases pressure to find the minimum effective level. Different manufacturers use proprietary algorithms with varying emphasis on these signals and different rates of pressure change. The device responds to apneas with larger, more rapid pressure increases than to flow limitation.',
    difficulty: 2,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 279,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is patient-ventilator asynchrony on bilevel PAP, what are the common types, and how are they corrected?',
    answer: 'Patient-ventilator asynchrony occurs when the device\'s cycling does not match the patient\'s spontaneous breathing pattern. Common types include: auto-triggering (device delivers breaths without patient effort, caused by leak or cardiac oscillation; correct by adjusting trigger sensitivity or fixing leak), ineffective triggering (patient efforts do not trigger IPAP; lower trigger threshold or increase EPAP to reduce intrinsic PEEP), premature cycling (Ti too short; increase Ti minimum), and delayed cycling (Ti too long; decrease Ti maximum). Asynchrony causes discomfort, dyspnea, and may reduce treatment efficacy. Identifying and correcting it requires careful observation during attended titration.',
    difficulty: 3,
    topic: 'Advanced PAP Modalities',
    isFree: false,
    orderIndex: 280,
  },

  // ============================================================
  // RESEARCH & EMERGING TOPICS (cards 281-300)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How are consumer wearable sleep trackers validated against polysomnography, and what are their known limitations?',
    answer: 'Consumer wearables (smartwatches, rings, headbands) are validated by simultaneous comparison with PSG. Most devices use accelerometry and photoplethysmography to estimate sleep stages. Current devices show reasonable accuracy for total sleep time (within 10-30 minutes) and sleep efficiency but tend to overestimate sleep (misclassify wake as light sleep) and have poor accuracy for individual sleep stage classification, particularly N3 and REM detection. They cannot detect respiratory events, limb movements, or arousals. They are useful for longitudinal sleep pattern tracking but are not diagnostic tools and should not replace PSG or HSAT for diagnosing sleep disorders.',
    difficulty: 1,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 281,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the PALM model for phenotyping obstructive sleep apnea, and how does it guide personalized treatment?',
    answer: 'The PALM model identifies four key physiological traits contributing to OSA: P (Pcrit, pharyngeal collapsibility: the critical closing pressure of the upper airway), A (arousal threshold: the ease with which respiratory events trigger cortical arousal), L (loop gain: the sensitivity of the ventilatory control system), and M (muscle responsiveness: the ability of upper airway dilator muscles to activate in response to negative pharyngeal pressure). Patients with high collapsibility primarily benefit from CPAP or surgery. Those with low arousal threshold may benefit from sedatives that raise the threshold. High loop gain responds to oxygen or acetazolamide. This framework moves toward precision medicine in OSA beyond one-size-fits-all CPAP.',
    difficulty: 3,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 282,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is hypoxic burden, and why is it proposed as a better predictor of cardiovascular outcomes than AHI?',
    answer: 'Hypoxic burden quantifies the total area under the oxygen desaturation curve associated with respiratory events, integrating both the depth and duration of each desaturation event over the total sleep time. Unlike AHI, which counts events equally regardless of their physiological impact, hypoxic burden captures the cumulative hypoxemic stress. A patient with few but very deep desaturations may have a low AHI but high hypoxic burden. Studies have shown that hypoxic burden independently predicts cardiovascular mortality, heart failure, and atrial fibrillation better than AHI alone. It represents a shift toward outcome-relevant metrics in sleep medicine.',
    difficulty: 2,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 283,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is loop gain in the context of sleep-disordered breathing, and how does high loop gain contribute to central sleep apnea?',
    answer: 'Loop gain is an engineering concept describing the sensitivity of a feedback control system. In ventilatory control, it is the ratio of the ventilatory response to a ventilatory disturbance. High loop gain means the system overresponds to small changes in blood gases: a brief apnea causes CO2 to rise, triggering an exaggerated hyperventilatory response that drives CO2 below the apneic threshold, causing another central apnea, perpetuating a cycle. High loop gain contributes to Cheyne-Stokes respiration and treatment-emergent CSA. It can be estimated from PSG data. Interventions to lower loop gain include supplemental oxygen, acetazolamide, and adaptive servo-ventilation.',
    difficulty: 3,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 284,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the arousal threshold in OSA pathophysiology, and how can it be estimated without esophageal manometry?',
    answer: 'The arousal threshold is the level of negative intrathoracic pressure (respiratory effort) at which a cortical arousal is triggered during an obstructive event. A low arousal threshold means the patient wakes up easily from minimal obstruction before upper airway muscles can respond protectively, perpetuating a cycle of obstruction-arousal-sleep onset-obstruction. It can be estimated from clinical PSG data: a low arousal threshold is suggested by an AHI below 30, nadir SpO2 above 82.5%, and hypopnea fraction greater than 58% of all events. Patients with a low arousal threshold may benefit from agents that raise it (such as trazodone or eszopiclone), potentially allowing PAP to work more effectively.',
    difficulty: 3,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 285,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is drug-induced sleep endoscopy (DISE), and what classification system is commonly used to document findings?',
    answer: 'DISE is a diagnostic procedure in which a flexible nasopharyngoscope is used to visualize upper airway collapse during sedation-simulated sleep (typically using propofol or midazolam). The VOTE classification system grades obstruction at four levels: Velum (soft palate), Oropharynx (lateral walls and tonsils), Tongue base, and Epiglottis. At each level, the degree of obstruction is graded as none, partial, or complete, and the configuration is described as anteroposterior, lateral, or concentric. DISE guides surgical planning by identifying the specific sites and patterns of collapse, enabling targeted interventions rather than empirical surgery.',
    difficulty: 2,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 286,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are emerging biomarkers being studied for obstructive sleep apnea diagnosis and risk stratification?',
    answer: 'Emerging biomarkers include: high-sensitivity C-reactive protein and interleukin-6 (systemic inflammation), oxidized LDL and malondialdehyde (oxidative stress), urinary catecholamines (sympathetic activation), plasma endothelin-1 and VEGF (endothelial dysfunction and intermittent hypoxia response), HbA1c and adipokines like leptin and adiponectin (metabolic dysfunction), and circulating microRNAs associated with intermittent hypoxia. These biomarkers are being investigated to identify patients at highest cardiovascular risk, predict treatment response, and potentially serve as screening tools. None have yet achieved clinical validation sufficient to replace standard diagnostic testing.',
    difficulty: 3,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 287,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the role of peripheral arterial tonometry (PAT) in sleep apnea diagnosis, and how does the WatchPAT device work?',
    answer: 'PAT measures peripheral arterial pulsatile volume at the fingertip, which decreases with sympathetic activation following respiratory events. The WatchPAT device uses a finger-mounted probe to detect PAT signal attenuation, combined with actigraphy and pulse oximetry, to estimate AHI, sleep stages, and body position without EEG, airflow sensors, or chest belts. It is FDA-cleared for home diagnosis of OSA. Studies show good correlation with PSG-derived AHI for moderate-to-severe OSA. Limitations include inability to differentiate central from obstructive events and reduced accuracy in patients on sympatholytic medications (beta-blockers, alpha-blockers).',
    difficulty: 2,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 288,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the concept of OSA endotypes, and how does endotyping differ from traditional severity classification?',
    answer: 'OSA endotyping classifies patients by the underlying pathophysiological mechanisms driving their disease rather than by a single severity metric (AHI). The major endotypes include: anatomical (high Pcrit from structural narrowing), low arousal threshold (frequent awakenings from minimal obstruction), high loop gain (ventilatory control instability), and poor muscle responsiveness (inadequate compensatory upper airway dilator activation). A single patient may have one or multiple contributing endotypes. This approach enables precision medicine: anatomical endotypes respond to CPAP/surgery, low arousal threshold to sedatives, high loop gain to oxygen/acetazolamide, and poor muscle responsiveness to hypoglossal nerve stimulation or myofunctional therapy.',
    difficulty: 2,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 289,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is myofunctional therapy for OSA, and what evidence supports its use?',
    answer: 'Myofunctional therapy consists of exercises targeting the oropharyngeal muscles (tongue, soft palate, lateral pharyngeal wall, and facial muscles) to improve upper airway tone and reduce collapsibility. Exercises include tongue strengthening, soft palate elevation, and circular breathing techniques performed daily for several months. A meta-analysis showed approximately 50% reduction in AHI in adults and 62% in children, with improvements in snoring, oxygen desaturation index, and sleepiness. It is most effective for mild-to-moderate OSA and as adjunctive therapy. The mechanism involves increasing the tonic and phasic activity of upper airway dilator muscles. Adherence to the exercise regimen is the primary challenge.',
    difficulty: 2,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 290,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What pharmacological agents are being investigated as targeted therapies for OSA based on endotype-specific mechanisms?',
    answer: 'Atomoxetine plus oxybutynin (a noradrenergic agent combined with an antimuscarinic) has shown promise in reducing AHI by increasing upper airway muscle tone during sleep. Trazodone and eszopiclone are being studied to raise the arousal threshold in patients with a low arousal threshold endotype. Acetazolamide and supplemental oxygen target high loop gain by stabilizing ventilatory control. Dronabinol (synthetic THC) has been studied for its potential to reduce AHI through modulation of vagal afferents. Sulthiame, a carbonic anhydrase inhibitor, has shown AHI reduction in clinical trials. These represent the emerging field of pharmacotherapy for OSA beyond CPAP.',
    difficulty: 3,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 291,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How is artificial intelligence being applied in sleep medicine for automated scoring and diagnosis?',
    answer: 'AI algorithms, particularly deep learning neural networks, are being developed and validated for automated sleep stage scoring (achieving inter-rater reliability comparable to human scorers), automated detection and classification of respiratory events, prediction of CPAP titration pressures from diagnostic data, identification of atrial fibrillation and other arrhythmias from single-lead ECG, and prediction of OSA from demographic and clinical data without PSG. Current FDA-cleared AI tools include automated scoring assistance software that reduces technologist scoring time. Limitations include the need for large validated training datasets, potential bias in training data, and the requirement for human oversight and final interpretation.',
    difficulty: 2,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 292,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the significance of the T90 metric (percentage of sleep time with SpO2 below 90%), and how does it relate to clinical outcomes?',
    answer: 'T90 quantifies the cumulative duration of clinically significant hypoxemia during sleep, expressed as a percentage of total sleep time. T90 greater than 10% is associated with increased risk of pulmonary hypertension, cardiac arrhythmias, cognitive impairment, and mortality. T90 captures sustained hypoxemia (as seen in hypoventilation syndromes and overlap syndrome) that the AHI may not reflect, since AHI counts discrete events regardless of desaturation severity. T90 is particularly important in COPD-OSA overlap syndrome, obesity hypoventilation, and neuromuscular disease, where sustained (not just intermittent) hypoxemia drives pulmonary vascular remodeling and right heart failure.',
    difficulty: 3,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 293,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the potential role of mandibular advancement during drug-induced sleep endoscopy in predicting oral appliance therapy success?',
    answer: 'During DISE, the examiner can manually advance the mandible (jaw thrust maneuver) or use a simulation bite to observe whether tongue base and retroglossal airway collapse resolves with mandibular protrusion. If the airway opens substantially with jaw advancement during DISE, the patient is more likely to respond to a mandibular advancement device. This technique helps predict treatment success before committing to the time and expense of a custom oral appliance. Studies show that DISE with mandibular advancement has a positive predictive value of approximately 80-90% for oral appliance success, improving patient selection compared to clinical characteristics alone.',
    difficulty: 2,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 294,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the limitations of using AHI as the primary metric for OSA severity, and what alternative metrics are being proposed?',
    answer: 'AHI limitations include: it treats all events equally regardless of duration, desaturation depth, or arousal intensity; it does not account for sleep stage distribution of events; it uses arbitrary severity thresholds (5/15/30); it poorly predicts individual cardiovascular risk, daytime sleepiness, or neurocognitive impairment; and it does not distinguish endotypes. Proposed alternatives include hypoxic burden (area under the desaturation curve), arousal intensity index, sleep fragmentation metrics, oxygen desaturation index, T90, event duration analysis, and composite scores combining multiple physiological signals. Research suggests that multi-dimensional characterization better predicts clinical outcomes than any single metric.',
    difficulty: 2,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 295,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the role of contactless radar-based sleep monitoring technology, and what are its current capabilities?',
    answer: 'Contactless radar sensors (using ultra-wideband or frequency-modulated continuous wave technology) placed on the nightstand can detect chest wall movement for respiratory rate and effort, body movement for sleep-wake discrimination, and heart rate through ballistic cardiac motion. They can identify respiratory events suggestive of sleep apnea without any sensors attached to the patient. Current capabilities include reasonable accuracy for respiratory rate and total sleep time estimation. Limitations include inability to detect blood oxygen levels, limited sleep staging accuracy, and susceptibility to interference from bed partners. They are being explored for longitudinal home monitoring and screening.',
    difficulty: 2,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 296,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is positional therapy using newer wearable devices, and how effective is it compared to traditional methods?',
    answer: 'Newer positional therapy devices are small, wearable sensors worn on the chest or neck that detect supine position and deliver gentle vibrotactile feedback (vibration) to prompt the patient to change position without causing full arousal. They are more effective and better tolerated than traditional methods (tennis ball technique, positional pillows) because they apply graded stimulation, track compliance objectively via companion apps, and provide data on positional sleep distribution. Studies show 70-80% reduction in supine sleep time and significant AHI reduction in patients with confirmed positional OSA. They are indicated for patients with positional OSA (supine AHI at least twice non-supine AHI) who prefer an alternative to CPAP.',
    difficulty: 1,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 297,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the concept of Pcrit (critical closing pressure), and how does it relate to upper airway collapsibility and treatment selection?',
    answer: 'Pcrit is the nasal pressure at which the upper airway collapses and flow ceases. A more positive (less negative) Pcrit indicates a more collapsible airway. Normal individuals have Pcrit values of approximately -13 cmH2O. Simple snorers have values around -5 cmH2O, and OSA patients typically have values above -2 cmH2O (often positive). Pcrit is measured during sleep by progressively lowering nasal pressure and plotting the flow-pressure relationship. Patients with highly positive Pcrit (greater than +2 cmH2O) have severe anatomical collapse and are most likely to require CPAP or surgery. Those with Pcrit near zero may respond to non-anatomical interventions (positional therapy, oral appliances, weight loss).',
    difficulty: 3,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 298,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the significance of the respiratory arousal intensity concept, and how does it complement the traditional arousal index?',
    answer: 'Respiratory arousal intensity quantifies the magnitude of cortical activation following respiratory events, ranging from brief, mild arousals (minimal EEG frequency shift) to prolonged, intense arousals (high-amplitude, widespread cortical activation with behavioral awakening). The traditional arousal index counts all arousals equally regardless of their intensity. Research shows that higher arousal intensity is associated with greater sympathetic activation, blood pressure surges, and cardiovascular risk. Conversely, some respiratory arousals may be protective by restoring airway patency. Arousal intensity metrics may help identify patients at highest cardiovascular risk and explain why some patients with similar AHI have vastly different clinical outcomes.',
    difficulty: 3,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 299,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How is home-based multi-night sleep testing being explored as an alternative to single-night PSG, and what advantages does it offer?',
    answer: 'Multi-night home testing uses simplified sensor arrays (nasal pressure, SpO2, actigraphy, or advanced wearables) over 3-14 consecutive nights to characterize a patient\'s sleep-disordered breathing across multiple nights. Advantages include capturing night-to-night AHI variability (which can be substantial, with standard deviation of 10-15 events/hour), reducing the probability of a false-negative or false-positive single-night result, accounting for the first-night effect, providing data across different body positions and sleep stages encountered naturally, and being more representative of the patient\'s typical sleep. This approach may improve diagnostic accuracy and treatment decisions, particularly for patients near severity thresholds where a single-night study might misclassify them.',
    difficulty: 1,
    topic: 'Research & Emerging Topics',
    isFree: false,
    orderIndex: 300,
  },
]

async function main() {
  console.log('Seeding SDS Batch 3 flashcards (201-300)...')
  console.log(`Total cards: ${flashcards.length}`)

  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })

  console.log(`Successfully created ${result.count} flashcards`)

  // Summary stats
  const topicCounts: Record<string, number> = {}
  const difficultyCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0 }
  let freeCount = 0

  for (const card of flashcards) {
    topicCounts[card.topic] = (topicCounts[card.topic] || 0) + 1
    difficultyCounts[card.difficulty]++
    if (card.isFree) freeCount++
  }

  console.log('\n--- Summary ---')
  console.log('By topic:')
  for (const [topic, count] of Object.entries(topicCounts)) {
    console.log(`  ${topic}: ${count} cards`)
  }
  console.log('By difficulty:')
  console.log(`  Easy (1): ${difficultyCounts[1]}`)
  console.log(`  Medium (2): ${difficultyCounts[2]}`)
  console.log(`  Hard (3): ${difficultyCounts[3]}`)
  console.log(`Free cards: ${freeCount}`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
