import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const flashcards = [
  // ============================================================
  // PULMONARY FUNCTION TESTING (cards 101-115)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What FEV1/FVC ratio indicates obstructive lung disease?',
    answer: 'An FEV1/FVC ratio below 0.70 (70%) indicates obstructive lung disease. The lower the ratio, the more severe the obstruction, reflecting air trapping and reduced expiratory airflow.',
    difficulty: 2,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 101,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does FVC (Forced Vital Capacity) measure?',
    answer: 'FVC measures the total volume of air a patient can forcefully exhale after a maximal inspiration. A reduced FVC with a normal or elevated FEV1/FVC ratio suggests a restrictive pattern.',
    difficulty: 1,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 102,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does a flow-volume loop appear in a patient with a fixed upper airway obstruction?',
    answer: 'A fixed upper airway obstruction produces flattening of both the inspiratory and expiratory limbs of the flow-volume loop, creating a characteristic box-shaped pattern. This occurs because the obstruction limits flow equally in both directions.',
    difficulty: 3,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 103,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the DLCO test and what does a decreased result indicate?',
    answer: 'DLCO (Diffusing Capacity of the Lung for Carbon Monoxide) measures the ability of gas to transfer from alveoli into pulmonary capillary blood. A decreased DLCO suggests damage to the alveolar-capillary membrane, as seen in emphysema, pulmonary fibrosis, or pulmonary embolism.',
    difficulty: 2,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 104,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'Which lung volume cannot be measured by simple spirometry?',
    answer: 'Residual volume (RV) cannot be measured by spirometry because it is the air remaining in the lungs after maximal exhalation. Measuring RV requires helium dilution, nitrogen washout, or body plethysmography.',
    difficulty: 2,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 105,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is Total Lung Capacity (TLC) and how is it calculated?',
    answer: 'TLC is the total volume of air in the lungs after a maximal inspiration, normally about 6 liters in adults. It equals the sum of all four lung volumes: tidal volume + inspiratory reserve volume + expiratory reserve volume + residual volume.',
    difficulty: 1,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 106,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What pattern on spirometry suggests a restrictive lung disease?',
    answer: 'Restrictive disease shows proportionally reduced FEV1 and FVC with a normal or elevated FEV1/FVC ratio (often above 0.70). TLC is also reduced, confirming that lung expansion is limited rather than airflow being obstructed.',
    difficulty: 2,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 107,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does an increased Residual Volume (RV) indicate?',
    answer: 'An increased RV indicates air trapping, commonly seen in obstructive diseases such as COPD and asthma. The patient is unable to fully exhale, leaving excess air trapped in the lungs at end-expiration.',
    difficulty: 2,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 108,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the significance of the FEF25-75% measurement?',
    answer: 'FEF25-75% (Forced Expiratory Flow at 25-75% of FVC) reflects airflow in the small and medium airways. It is considered a sensitive early indicator of small airway disease and may be reduced before FEV1 shows significant decline.',
    difficulty: 3,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 109,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does a variable extrathoracic obstruction appear on a flow-volume loop?',
    answer: 'A variable extrathoracic obstruction flattens only the inspiratory limb of the flow-volume loop while the expiratory limb remains normal. During forced inspiration, negative intrathoracic pressure causes the extrathoracic obstruction to worsen.',
    difficulty: 3,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 110,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is Functional Residual Capacity (FRC)?',
    answer: 'FRC is the volume of air remaining in the lungs at the end of a normal passive exhalation. It equals the expiratory reserve volume plus the residual volume and represents the resting equilibrium point of the respiratory system.',
    difficulty: 1,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 111,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does a positive bronchodilator response on spirometry look like?',
    answer: 'A positive bronchodilator response is defined as an improvement in FEV1 or FVC of at least 12% and 200 mL from baseline after inhaling a short-acting bronchodilator. This suggests reversible airway obstruction, characteristic of asthma.',
    difficulty: 2,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 112,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does body plethysmography differ from helium dilution for measuring lung volumes?',
    answer: 'Body plethysmography measures all intrathoracic gas including trapped air, while helium dilution only measures gas in communicating airways. In patients with significant air trapping, plethysmography yields higher and more accurate lung volume measurements.',
    difficulty: 3,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 113,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is Peak Expiratory Flow (PEF) and when is it most useful?',
    answer: 'PEF is the maximum flow rate achieved during a forced exhalation from full inspiration. It is most useful for monitoring asthma severity and treatment response, though it is effort-dependent and primarily reflects large airway function.',
    difficulty: 1,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 114,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What conditions can cause an increased DLCO?',
    answer: 'DLCO can be increased in conditions that raise pulmonary capillary blood volume, such as polycythemia, left-to-right intracardiac shunts, pulmonary hemorrhage, and asthma. Exercise and the supine position can also transiently increase DLCO.',
    difficulty: 3,
    topic: 'Pulmonary Function Testing',
    isFree: false,
    orderIndex: 115,
  },

  // ============================================================
  // NEONATAL & PEDIATRIC BASICS (cards 116-130)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the five components of the Apgar score?',
    answer: 'The five Apgar components are: Appearance (skin color), Pulse (heart rate), Grimace (reflex irritability), Activity (muscle tone), and Respiration (breathing effort). Each is scored 0-2, with a maximum total of 10, assessed at 1 and 5 minutes after birth.',
    difficulty: 1,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 116,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What Apgar score range indicates the need for immediate resuscitation?',
    answer: 'An Apgar score of 0-3 indicates severe distress requiring immediate resuscitative intervention. Scores of 4-6 suggest moderate distress needing some assistance, while 7-10 are considered normal.',
    difficulty: 1,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 117,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the initial FiO2 recommended for term newborn resuscitation?',
    answer: 'Current NRP guidelines recommend starting resuscitation of term newborns with 21% oxygen (room air). FiO2 should be titrated based on pulse oximetry readings to meet target pre-ductal SpO2 values for each minute of life.',
    difficulty: 2,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 118,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does the pediatric airway differ anatomically from the adult airway?',
    answer: 'The pediatric airway has a proportionally larger tongue and occiput, a more anterior and cephalad larynx, a funnel-shaped (versus cylindrical) airway with the narrowest point at the cricoid ring, and shorter tracheal length. These differences make intubation more challenging.',
    difficulty: 2,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 119,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of exogenous surfactant therapy in neonates?',
    answer: 'Exogenous surfactant replaces deficient pulmonary surfactant in premature infants with Respiratory Distress Syndrome (RDS). It reduces alveolar surface tension, prevents alveolar collapse at end-expiration, and improves lung compliance and oxygenation.',
    difficulty: 2,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 120,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'At what gestational age do type II pneumocytes begin producing adequate surfactant?',
    answer: 'Type II pneumocytes begin producing adequate surfactant around 35-36 weeks gestation. Surfactant production begins around 24-28 weeks but does not reach sufficient levels until near term, which is why premature infants are at high risk for RDS.',
    difficulty: 2,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 121,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is nasal CPAP used for in neonates?',
    answer: 'Nasal CPAP is used to maintain functional residual capacity and prevent alveolar collapse in neonates with RDS or apnea of prematurity. It provides continuous distending pressure through nasal prongs, stabilizing the airway and improving oxygenation without intubation.',
    difficulty: 1,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 122,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the Silverman-Andersen score used to assess?',
    answer: 'The Silverman-Andersen score assesses the severity of respiratory distress in neonates by grading five signs: chest lag, intercostal retractions, xiphoid retractions, nasal flaring, and expiratory grunting. Each is scored 0-2, with a higher total indicating greater distress.',
    difficulty: 3,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 123,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What ventilation rate is recommended during neonatal CPR?',
    answer: 'During neonatal CPR, the recommended rate is 30 breaths and 90 compressions per minute, using a 3:1 compression-to-ventilation ratio. This delivers approximately 120 events per minute total, prioritizing ventilation since neonatal arrests are usually respiratory in origin.',
    difficulty: 2,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 124,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is Transient Tachypnea of the Newborn (TTN)?',
    answer: 'TTN is a self-limiting condition caused by delayed clearance of fetal lung fluid, commonly seen after cesarean deliveries. It presents with tachypnea, mild retractions, and sometimes cyanosis within hours of birth and typically resolves within 24-72 hours with supportive care.',
    difficulty: 2,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 125,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the appropriate ET tube size formula for pediatric patients older than 1 year?',
    answer: 'For uncuffed tubes: (age in years / 4) + 4 gives the internal diameter in mm. For cuffed tubes: (age in years / 4) + 3.5. These formulas provide starting estimates, and the clinician should have tubes one half-size above and below available.',
    difficulty: 2,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 126,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is bronchopulmonary dysplasia (BPD)?',
    answer: 'BPD is a chronic lung disease of premature infants resulting from prolonged mechanical ventilation and oxygen exposure. It is defined as continued oxygen requirement at 36 weeks postmenstrual age and is characterized by impaired alveolar and vascular development.',
    difficulty: 3,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 127,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the lecithin-sphingomyelin (L/S) ratio and its clinical significance?',
    answer: 'The L/S ratio is measured from amniotic fluid to assess fetal lung maturity. A ratio of 2:1 or greater indicates mature lungs with adequate surfactant production. Values below 2:1 suggest a high risk for RDS if delivered prematurely.',
    difficulty: 3,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 128,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the signs of respiratory distress in a neonate?',
    answer: 'Signs include nasal flaring, grunting, intercostal and subcostal retractions, tachypnea (rate above 60/min), cyanosis, and head bobbing. Grunting is particularly significant as it represents the infant attempting to maintain FRC by exhaling against a partially closed glottis.',
    difficulty: 1,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 129,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is retinopathy of prematurity (ROP) and how is it related to oxygen therapy?',
    answer: 'ROP is abnormal blood vessel development in the retina of premature infants, potentially leading to vision loss. It is associated with excessive or fluctuating oxygen levels, which is why SpO2 targets for premature neonates are typically kept between 88-95% to minimize risk.',
    difficulty: 3,
    topic: 'Neonatal & Pediatric',
    isFree: false,
    orderIndex: 130,
  },

  // ============================================================
  // CARDIOPULMONARY ANATOMY & PHYSIOLOGY (cards 131-145)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the normal ventilation-perfusion (V/Q) ratio?',
    answer: 'The normal overall V/Q ratio is approximately 0.8. This means alveolar ventilation (about 4 L/min) is slightly less than pulmonary blood flow (about 5 L/min). Regional V/Q varies, being highest at the lung apices and lowest at the bases in upright individuals.',
    difficulty: 2,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 131,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a pulmonary shunt?',
    answer: 'A pulmonary shunt occurs when blood passes through the pulmonary vasculature without participating in gas exchange (V/Q = 0). This happens when alveoli are perfused but not ventilated, as in atelectasis, pneumonia, or ARDS. Shunt-related hypoxemia responds poorly to supplemental oxygen.',
    difficulty: 2,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 132,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is dead space ventilation?',
    answer: 'Dead space ventilation occurs when alveoli are ventilated but not perfused (V/Q = infinity). Anatomic dead space includes the conducting airways, while alveolar dead space refers to ventilated but unperfused alveoli. Pulmonary embolism is a classic cause of increased alveolar dead space.',
    difficulty: 2,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 133,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is hypoxic pulmonary vasoconstriction (HPV)?',
    answer: 'HPV is a protective reflex where pulmonary arterioles constrict in response to local alveolar hypoxia. This diverts blood away from poorly ventilated lung regions toward better-ventilated areas, optimizing V/Q matching. It is unique to the pulmonary circulation.',
    difficulty: 3,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 134,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the normal PaO2 for a patient breathing room air at sea level?',
    answer: 'The normal PaO2 on room air at sea level is 80-100 mmHg. PaO2 naturally declines with age and can be estimated by the formula: expected PaO2 = 100 - (age/3). Values below 60 mmHg indicate significant hypoxemia requiring intervention.',
    difficulty: 1,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 135,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does the oxyhemoglobin dissociation curve shift to the right?',
    answer: 'A rightward shift occurs with increased temperature, increased PaCO2, decreased pH (acidosis), and increased 2,3-DPG. This shift decreases hemoglobin oxygen affinity, meaning hemoglobin releases oxygen more readily to the tissues. It is beneficial when tissues have increased oxygen demand.',
    difficulty: 2,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 136,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What causes a leftward shift of the oxyhemoglobin dissociation curve?',
    answer: 'A leftward shift occurs with decreased temperature, decreased PaCO2, increased pH (alkalosis), decreased 2,3-DPG, carbon monoxide poisoning, and fetal hemoglobin. This increases hemoglobin oxygen affinity, making hemoglobin hold onto oxygen more tightly and release less to tissues.',
    difficulty: 2,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 137,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the three forms in which CO2 is transported in the blood?',
    answer: 'CO2 is transported as dissolved CO2 in plasma (about 7%), bound to hemoglobin as carbaminohemoglobin (about 23%), and as bicarbonate ions (about 70%). The chloride shift facilitates bicarbonate transport by exchanging bicarbonate for chloride ions across the red blood cell membrane.',
    difficulty: 2,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 138,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the normal pulmonary artery pressure?',
    answer: 'Normal pulmonary artery pressure is approximately 25/10 mmHg with a mean of about 15 mmHg. The pulmonary circulation is a low-pressure, low-resistance system compared to the systemic circulation. Mean pulmonary artery pressure above 20 mmHg at rest defines pulmonary hypertension.',
    difficulty: 2,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 139,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the Bohr effect?',
    answer: 'The Bohr effect describes how increased CO2 and decreased pH reduce hemoglobin oxygen affinity, promoting oxygen release at the tissue level. In the lungs, the reverse occurs: as CO2 is exhaled and pH rises, hemoglobin picks up oxygen more readily.',
    difficulty: 3,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 140,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the alveolar gas equation used for?',
    answer: 'The alveolar gas equation (PAO2 = FiO2(Pb - PH2O) - PaCO2/0.8) calculates the ideal partial pressure of oxygen in the alveoli. It is used to determine the A-a gradient, which helps differentiate causes of hypoxemia such as shunt, V/Q mismatch, and diffusion impairment.',
    difficulty: 3,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 141,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the normal A-a gradient and what does an elevated value indicate?',
    answer: 'The normal A-a gradient is 5-15 mmHg on room air and increases with age and higher FiO2. An elevated A-a gradient indicates a problem with gas exchange within the lungs, such as V/Q mismatch, shunt, or diffusion impairment, rather than hypoventilation.',
    difficulty: 3,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 142,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is oxygen content (CaO2) and how is it calculated?',
    answer: 'CaO2 is the total amount of oxygen carried in arterial blood, calculated as (Hb x 1.34 x SaO2) + (PaO2 x 0.003). Normal CaO2 is approximately 18-20 mL O2/dL. The hemoglobin-bound component contributes over 98% of total oxygen content.',
    difficulty: 3,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 143,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the Haldane effect?',
    answer: 'The Haldane effect describes how oxygenation of hemoglobin in the lungs promotes CO2 release, while deoxygenation at the tissues enhances CO2 pickup. This complements the Bohr effect and helps optimize both oxygen delivery and carbon dioxide removal.',
    difficulty: 3,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 144,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the function of the bronchial circulation?',
    answer: 'The bronchial circulation, arising from the aorta, supplies oxygenated blood to the conducting airways, pulmonary vessels, and pleura. It represents a normal anatomic shunt because some bronchial venous blood drains into pulmonary veins, mixing deoxygenated blood with oxygenated blood.',
    difficulty: 2,
    topic: 'Cardiopulmonary Anatomy & Physiology',
    isFree: false,
    orderIndex: 145,
  },

  // ============================================================
  // HUMIDITY & AEROSOL THERAPY (cards 146-160)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the Isothermic Saturation Boundary (ISB)?',
    answer: 'The ISB is the point in the airway (normally about 5 cm below the carina) where inspired gas reaches body temperature (37C) and 100% relative humidity (44 mg/L absolute humidity). Bypassing the upper airway with an artificial airway shifts the ISB deeper into the lungs.',
    difficulty: 2,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 146,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is an HME (Heat and Moisture Exchanger) and when is it used?',
    answer: 'An HME is a passive humidifier placed at the airway connection that captures exhaled heat and moisture and returns it during the next inspiration. It is used for intubated patients as an alternative to heated humidifiers, but is contraindicated with thick secretions or large air leaks.',
    difficulty: 1,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 147,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between a heated humidifier and a bland aerosol device?',
    answer: 'A heated humidifier adds molecular water vapor to inspired gas without producing particulate water, while a bland aerosol device generates suspended water droplets (aerosol particles). Heated humidifiers are preferred for mechanical ventilation; bland aerosols are used to mobilize secretions or deliver cool mist.',
    difficulty: 2,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 148,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the proper technique for using an MDI (Metered-Dose Inhaler)?',
    answer: 'Shake the MDI, exhale to FRC, place the mouthpiece between the lips, actuate while beginning a slow deep inhalation over 3-5 seconds, then hold the breath for up to 10 seconds. Using a spacer or valved holding chamber improves drug delivery and reduces oropharyngeal deposition.',
    difficulty: 1,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 149,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does a DPI (Dry Powder Inhaler) differ from an MDI?',
    answer: 'A DPI delivers medication as a dry powder that requires the patient to generate a fast, deep inspiratory flow (typically 60 L/min or greater) to disperse the drug. Unlike MDIs, DPIs are breath-actuated and do not use propellants, eliminating the need for hand-breath coordination.',
    difficulty: 2,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 150,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of a spacer or valved holding chamber (VHC) with an MDI?',
    answer: 'A spacer or VHC reduces the velocity of aerosol particles, decreases oropharyngeal drug deposition, and eliminates the need for precise hand-breath coordination. It increases the percentage of drug reaching the lower airways from about 10% to 20% or more.',
    difficulty: 1,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 151,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the optimal particle size range for aerosol deposition in the lower airways?',
    answer: 'The optimal particle size for lower airway deposition is 1-5 micrometers (MMAD). Particles larger than 5 micrometers tend to deposit in the upper airways and oropharynx by inertial impaction, while particles smaller than 0.5 micrometers may be exhaled without depositing.',
    difficulty: 2,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 152,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the hazards of heated humidification?',
    answer: 'Hazards include thermal burns from overheated gas, over-humidification leading to bronchospasm or water intoxication, condensation (rain-out) in the circuit that can obstruct flow or be aspirated, and electrical shock. Water traps should be placed at low points in the circuit to collect condensate.',
    difficulty: 2,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 153,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a small volume nebulizer (SVN) and what gas flow powers it?',
    answer: 'An SVN is a jet nebulizer that aerosolizes liquid medication for inhalation using a compressed gas source, typically set at 6-8 L/min. Treatment usually takes 10-15 minutes with a fill volume of 3-5 mL. Patients should breathe normally with occasional deep breaths.',
    difficulty: 1,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 154,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'When should an HME not be used?',
    answer: 'HMEs are contraindicated in patients with thick, copious, or bloody secretions (which can occlude the filter), significant air leaks exceeding 20% of tidal volume, body temperatures below 32C, and when aerosolized medications are being delivered through the ventilator circuit.',
    difficulty: 2,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 155,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the difference between absolute humidity and relative humidity?',
    answer: 'Absolute humidity is the actual water content in gas, measured in mg/L. Relative humidity is the ratio of actual water content to the maximum capacity at a given temperature, expressed as a percentage. Gas at 37C and 100% relative humidity holds 44 mg/L of water vapor.',
    difficulty: 1,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 156,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How should an MDI be used with a mechanically ventilated patient?',
    answer: 'Place a spacer or adapter in the inspiratory limb of the circuit, actuate the MDI synchronized with the beginning of inspiration, and allow adequate inspiratory time. Remove the HME if present, as it can filter out the aerosol. Dose may need to be increased compared to spontaneous breathing.',
    difficulty: 3,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 157,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a vibrating mesh nebulizer and what are its advantages?',
    answer: 'A vibrating mesh nebulizer uses a vibrating aperture plate with thousands of laser-drilled holes to generate aerosol. It is quieter, faster, and more efficient than jet nebulizers, produces a more uniform particle size, and does not add extra flow to the ventilator circuit.',
    difficulty: 3,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 158,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of hypertonic saline (3% or 7%) aerosol therapy?',
    answer: 'Hypertonic saline draws water into the airways via osmotic gradient, hydrating secretions and improving mucociliary clearance. It is commonly used in cystic fibrosis and for sputum induction for diagnostic purposes. Pre-treatment with a bronchodilator is recommended to prevent bronchospasm.',
    difficulty: 2,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 159,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What factors affect aerosol drug delivery during mechanical ventilation?',
    answer: 'Key factors include ventilator mode and settings (tidal volume, inspiratory flow, duty cycle), humidification (heated humidifiers reduce delivery compared to HMEs), circuit tubing diameter, device placement in the circuit, patient-ventilator synchrony, and endotracheal tube size.',
    difficulty: 3,
    topic: 'Humidity & Aerosol Therapy',
    isFree: false,
    orderIndex: 160,
  },

  // ============================================================
  // CHEST PHYSIOTHERAPY & LUNG EXPANSION (cards 161-175)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is incentive spirometry and what is it used for?',
    answer: 'Incentive spirometry is a lung expansion technique where the patient takes slow, deep breaths using a visual feedback device that encourages sustained maximal inspiration. It is used to prevent and treat atelectasis in postoperative patients and those at risk for pulmonary complications.',
    difficulty: 1,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 161,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the proper technique for incentive spirometry?',
    answer: 'The patient should sit upright, exhale normally, seal lips around the mouthpiece, and inhale slowly and deeply to raise the indicator to the target volume. They should hold the breath for at least 5 seconds at peak inspiration. Goal is 10 repetitions every 1-2 hours while awake.',
    difficulty: 1,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 162,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is IPPB (Intermittent Positive Pressure Breathing) therapy?',
    answer: 'IPPB delivers a positive-pressure breath triggered by the patient to achieve lung expansion. It is indicated for patients unable to take adequate deep breaths independently, such as those with neuromuscular weakness. Delivered tidal volumes should exceed spontaneous volumes to be effective.',
    difficulty: 2,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 163,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the contraindications for IPPB therapy?',
    answer: 'IPPB is contraindicated in untreated tension pneumothorax, intracranial pressure above 15 mmHg, hemodynamic instability, active hemoptysis, tracheoesophageal fistula, and recent esophageal or facial surgery. It should be used cautiously in patients with air trapping or bullous emphysema.',
    difficulty: 2,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 164,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is PEP (Positive Expiratory Pressure) therapy?',
    answer: 'PEP therapy involves exhaling against a fixed resistance (typically 10-20 cmH2O) through a mask or mouthpiece device. It helps prevent airway collapse during exhalation, promotes collateral ventilation behind mucus plugs, and facilitates secretion mobilization. It is commonly used in cystic fibrosis.',
    difficulty: 2,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 165,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How do oscillatory PEP devices (such as the Acapella or Flutter valve) work?',
    answer: 'Oscillatory PEP devices combine positive expiratory pressure with high-frequency oscillations of the airway. These oscillations loosen secretions from airway walls while the PEP component splints airways open, preventing collapse. The patient exhales through the device at a slightly active rate for 10-20 breaths.',
    difficulty: 2,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 166,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the indications for chest percussion and postural drainage?',
    answer: 'Chest percussion and postural drainage are indicated for patients producing more than 25-30 mL of sputum per day, those with atelectasis caused by mucus plugging, and patients with conditions like cystic fibrosis or bronchiectasis. The goal is to mobilize retained secretions using gravity and mechanical energy.',
    difficulty: 1,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 167,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What positions are used for postural drainage of the posterior basal segments of the lower lobes?',
    answer: 'The patient is placed prone with the bed tilted 30 degrees in Trendelenburg position (head down) with a pillow under the hips. Percussion is applied over the lower posterior ribs bilaterally. This position uses gravity to drain secretions from the posterior bases toward the central airways.',
    difficulty: 2,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 168,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the contraindications for Trendelenburg positioning during postural drainage?',
    answer: 'Trendelenburg is contraindicated in patients with increased intracranial pressure, uncontrolled hypertension, distended abdomen, recent esophageal or head surgery, hemodynamic instability, and uncontrolled airway with aspiration risk. Modified positions should be used for these patients.',
    difficulty: 2,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 169,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a high-frequency chest wall oscillation (HFCWO) vest?',
    answer: 'HFCWO uses an inflatable vest connected to an air pulse generator that rapidly compresses and releases the chest wall at frequencies of 5-25 Hz. This creates small bursts of expiratory airflow that mobilize secretions without requiring specific body positioning, making it popular for cystic fibrosis care.',
    difficulty: 2,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 170,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the active cycle of breathing technique (ACBT)?',
    answer: 'ACBT is a secretion clearance technique consisting of three phases: breathing control (relaxed tidal breathing), thoracic expansion exercises (deep breaths with inspiratory holds), and the forced expiratory technique (huffing from mid to low lung volume). It can be performed independently without equipment.',
    difficulty: 3,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 171,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is autogenic drainage?',
    answer: 'Autogenic drainage is a self-performed airway clearance technique using controlled breathing at three different lung volume levels: low volume breathing to unstick secretions, mid-volume breathing to collect them, and high-volume breathing to evacuate them. It requires significant patient training and cooperation.',
    difficulty: 3,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 172,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is intrapulmonary percussive ventilation (IPV)?',
    answer: 'IPV delivers rapid, short bursts of pressurized gas (100-300 cycles/min) directly to the airways via a mouthpiece. It simultaneously provides internal percussion to mobilize secretions, aerosol delivery of medication, and lung expansion. It is useful for patients unable to perform standard airway clearance techniques.',
    difficulty: 3,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 173,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'When should IPPB be considered over incentive spirometry?',
    answer: 'IPPB should be considered when a patient cannot generate adequate inspiratory volumes with incentive spirometry despite coaching, such as with neuromuscular weakness or severe pain. The key indicator is that IPPB-delivered volumes must exceed the patient spontaneous volumes to justify its use.',
    difficulty: 2,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 174,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How should chest physiotherapy be timed in relation to meals and bronchodilator treatments?',
    answer: 'CPT should be performed at least 1-2 hours after meals to reduce the risk of nausea and aspiration. If a bronchodilator is prescribed, it should be administered 15-20 minutes before CPT to open airways and enhance secretion mobilization during the therapy session.',
    difficulty: 1,
    topic: 'Chest Physiotherapy & Lung Expansion',
    isFree: false,
    orderIndex: 175,
  },

  // ============================================================
  // HEMODYNAMIC MONITORING (cards 176-190)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is a pulmonary artery catheter (Swan-Ganz catheter) used for?',
    answer: 'A Swan-Ganz catheter is inserted through a central vein and advanced into the pulmonary artery to measure right atrial pressure (CVP), pulmonary artery pressure, pulmonary capillary wedge pressure (PCWP), cardiac output, and mixed venous oxygen saturation. It guides fluid management and vasoactive therapy.',
    difficulty: 2,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 176,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does CVP (Central Venous Pressure) reflect?',
    answer: 'CVP reflects right atrial pressure and right ventricular preload. Normal CVP is 2-6 mmHg. Low CVP suggests hypovolemia or vasodilation, while elevated CVP may indicate right heart failure, fluid overload, cardiac tamponade, or tension pneumothorax.',
    difficulty: 2,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 177,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does the Pulmonary Capillary Wedge Pressure (PCWP) reflect?',
    answer: 'PCWP is an indirect measurement of left atrial pressure and left ventricular preload, obtained by inflating the balloon tip of the PA catheter. Normal PCWP is 6-12 mmHg. Elevated PCWP (above 18 mmHg) suggests left heart failure and cardiogenic pulmonary edema.',
    difficulty: 2,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 178,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How do you differentiate cardiogenic from non-cardiogenic pulmonary edema using hemodynamics?',
    answer: 'Cardiogenic pulmonary edema presents with an elevated PCWP (above 18 mmHg) reflecting left heart failure, while non-cardiogenic pulmonary edema (ARDS) has a normal or low PCWP (below 18 mmHg) because the edema is caused by increased capillary permeability rather than hydrostatic pressure.',
    difficulty: 3,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 179,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is normal cardiac output and how is it measured?',
    answer: 'Normal cardiac output is 4-8 L/min. It is measured with a PA catheter using thermodilution: cold saline is injected into the right atrium, and temperature change is detected at the PA catheter tip. The resulting curve is used to calculate output via the Stewart-Hamilton equation.',
    difficulty: 2,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 180,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is cardiac index and why is it used instead of cardiac output?',
    answer: 'Cardiac index is cardiac output divided by body surface area (CO/BSA), with a normal value of 2.5-4.0 L/min/m2. It is preferred over raw cardiac output because it normalizes for body size, allowing meaningful comparison between patients of different sizes.',
    difficulty: 2,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 181,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is Systemic Vascular Resistance (SVR) and what do abnormal values indicate?',
    answer: 'SVR measures the resistance the left ventricle must overcome to eject blood, with a normal range of 800-1500 dynes/sec/cm5. Elevated SVR is seen in cardiogenic shock and hypovolemia (compensatory vasoconstriction), while decreased SVR occurs in septic shock and anaphylaxis (vasodilation).',
    difficulty: 3,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 182,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the normal mixed venous oxygen saturation (SvO2) and what does a low value mean?',
    answer: 'Normal SvO2 is 60-80%, measured from the distal port of the PA catheter. A low SvO2 (below 60%) indicates that tissues are extracting more oxygen than normal, suggesting inadequate oxygen delivery from low cardiac output, anemia, hypoxemia, or increased metabolic demand.',
    difficulty: 2,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 183,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What hemodynamic profile is characteristic of cardiogenic shock?',
    answer: 'Cardiogenic shock presents with decreased cardiac output, elevated PCWP (above 18 mmHg) reflecting left heart congestion, elevated CVP, increased SVR (compensatory vasoconstriction), and decreased SvO2 (increased oxygen extraction). Treatment focuses on improving cardiac contractility and reducing afterload.',
    difficulty: 3,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 184,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What hemodynamic profile is characteristic of septic shock?',
    answer: 'Septic shock typically shows increased cardiac output (hyperdynamic state), decreased SVR due to vasodilation, low to normal PCWP, and a normal to elevated SvO2 despite tissue hypoperfusion (due to impaired oxygen extraction at the cellular level). Initial treatment includes fluid resuscitation and vasopressors.',
    difficulty: 3,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 185,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is Pulmonary Vascular Resistance (PVR) and when is it elevated?',
    answer: 'PVR measures resistance in the pulmonary vascular bed, with a normal range of 20-120 dynes/sec/cm5. It is elevated in pulmonary hypertension, hypoxic vasoconstriction, pulmonary embolism, and ARDS. Elevated PVR increases right ventricular afterload and can lead to right heart failure.',
    difficulty: 3,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 186,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is stroke volume and how is it calculated?',
    answer: 'Stroke volume is the amount of blood ejected by the left ventricle per beat, calculated as cardiac output divided by heart rate (SV = CO/HR). Normal stroke volume is 60-100 mL/beat. It is determined by preload, afterload, and contractility.',
    difficulty: 1,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 187,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'How does PEEP affect hemodynamic measurements from a PA catheter?',
    answer: 'High levels of PEEP can increase intrathoracic pressure, which may falsely elevate CVP, PAP, and PCWP readings. PEEP can also reduce venous return and cardiac output by compressing the vena cava. Readings should be taken at end-expiration and interpreted in the clinical context.',
    difficulty: 3,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 188,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What hemodynamic findings indicate hypovolemic shock?',
    answer: 'Hypovolemic shock shows decreased CVP, decreased PCWP, decreased cardiac output, increased heart rate (compensatory tachycardia), and increased SVR (compensatory vasoconstriction). SvO2 is decreased due to increased tissue oxygen extraction. Treatment is aggressive fluid resuscitation.',
    difficulty: 2,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 189,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What does the waveform look like when the PA catheter balloon overwedges?',
    answer: 'An overwedged waveform appears as a rising, non-pulsatile tracing that continuously increases in pressure. It occurs when the balloon is overinflated or the catheter has migrated too far distally. The balloon should be deflated immediately to prevent pulmonary artery rupture.',
    difficulty: 3,
    topic: 'Hemodynamic Monitoring',
    isFree: false,
    orderIndex: 190,
  },

  // ============================================================
  // EMERGENCY & RESUSCITATION (cards 191-200)
  // ============================================================
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the correct compression-to-ventilation ratio for adult CPR with two rescuers?',
    answer: 'The compression-to-ventilation ratio for adult CPR is 30:2 regardless of one or two rescuers. Compressions should be at a rate of 100-120 per minute, at least 2 inches deep, with full chest recoil between compressions. Once an advanced airway is placed, continuous compressions are given with a breath every 6 seconds.',
    difficulty: 1,
    topic: 'Emergency & Resuscitation',
    isFree: false,
    orderIndex: 191,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the first-line drug and dose for pulseless ventricular tachycardia or ventricular fibrillation?',
    answer: 'Epinephrine 1 mg IV/IO every 3-5 minutes is the first-line vasopressor. The first dose should be given after the second defibrillation attempt. Amiodarone 300 mg IV bolus is the first-line antiarrhythmic, with a second dose of 150 mg if needed.',
    difficulty: 2,
    topic: 'Emergency & Resuscitation',
    isFree: false,
    orderIndex: 192,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the shockable cardiac arrest rhythms?',
    answer: 'The two shockable rhythms are ventricular fibrillation (V-fib) and pulseless ventricular tachycardia (pulseless V-tach). These rhythms respond to defibrillation. Asystole and pulseless electrical activity (PEA) are non-shockable rhythms treated with CPR and medications only.',
    difficulty: 1,
    topic: 'Emergency & Resuscitation',
    isFree: false,
    orderIndex: 193,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the recommended initial energy level for biphasic defibrillation in adults?',
    answer: 'For biphasic defibrillators, the initial energy is typically 120-200 joules depending on the manufacturer recommendation. If the specific recommendation is unknown, the maximum available dose is used. Subsequent shocks should be at the same or higher energy level.',
    difficulty: 2,
    topic: 'Emergency & Resuscitation',
    isFree: false,
    orderIndex: 194,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What are the reversible causes of cardiac arrest (the Hs and Ts)?',
    answer: 'The Hs are: Hypovolemia, Hypoxia, Hydrogen ion (acidosis), Hypo/Hyperkalemia, and Hypothermia. The Ts are: Tension pneumothorax, Tamponade (cardiac), Toxins, and Thrombosis (pulmonary or coronary). Identifying and treating these underlying causes is essential for successful resuscitation.',
    difficulty: 2,
    topic: 'Emergency & Resuscitation',
    isFree: false,
    orderIndex: 195,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the role of atropine in emergency cardiac care?',
    answer: 'Atropine is a parasympatholytic (vagolytic) drug used to treat symptomatic bradycardia at a dose of 0.5 mg IV every 3-5 minutes up to a maximum of 3 mg. It increases heart rate by blocking vagal tone on the SA node. It is no longer recommended for asystole or PEA.',
    difficulty: 2,
    topic: 'Emergency & Resuscitation',
    isFree: false,
    orderIndex: 196,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the purpose of capnography (ETCO2 monitoring) during CPR?',
    answer: 'ETCO2 monitoring during CPR provides real-time feedback on compression quality, as effective compressions generate adequate cardiac output and CO2 delivery to the lungs. An ETCO2 below 10 mmHg suggests ineffective compressions. A sudden sustained rise may indicate return of spontaneous circulation (ROSC).',
    difficulty: 2,
    topic: 'Emergency & Resuscitation',
    isFree: false,
    orderIndex: 197,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What medication and dose is given for symptomatic bradycardia unresponsive to atropine?',
    answer: 'If atropine is ineffective for symptomatic bradycardia, options include dopamine infusion at 5-20 mcg/kg/min or epinephrine infusion at 2-10 mcg/min. Transcutaneous pacing should also be initiated. If the patient is hemodynamically unstable, pacing should not be delayed for medication trials.',
    difficulty: 3,
    topic: 'Emergency & Resuscitation',
    isFree: false,
    orderIndex: 198,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'When should synchronized cardioversion be used instead of defibrillation?',
    answer: 'Synchronized cardioversion is used for unstable tachyarrhythmias with a pulse, such as unstable supraventricular tachycardia, atrial fibrillation, atrial flutter, or monomorphic ventricular tachycardia with a pulse. The sync mode delivers the shock timed to the R-wave to avoid triggering V-fib.',
    difficulty: 3,
    topic: 'Emergency & Resuscitation',
    isFree: false,
    orderIndex: 199,
  },
  {
    divisionId: 'cmsm41fq00000zf54wqjaayvz',
    question: 'What is the rapid response team (RRT) and what are common activation criteria?',
    answer: 'An RRT is a multidisciplinary team activated for acute patient deterioration before cardiac arrest occurs. Common triggers include acute respiratory distress, SpO2 below 90% despite oxygen, heart rate above 140 or below 40, systolic BP below 90 mmHg, acute mental status change, or staff concern about the patient.',
    difficulty: 1,
    topic: 'Emergency & Resuscitation',
    isFree: false,
    orderIndex: 200,
  },
];

async function main() {
  console.log('Starting TMC Batch 2 seed (cards 101-200)...');
  console.log(`Total flashcards to insert: ${flashcards.length}`);

  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  });

  console.log(`Successfully inserted ${result.count} flashcards.`);
  console.log('TMC Batch 2 seeding complete.');
}

main()
  .catch((e) => {
    console.error('Error seeding TMC Batch 2:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
