import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const SDS_DIVISION_ID = 'cmsm41fwz0003zf54l0h5llrr'

const flashcards = [
  // ============================================================
  // ADVANCED PSG INTERPRETATION (cards 101-120)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does the AASM distinguish between an obstructive apnea and a central apnea based on respiratory effort signals?',
    answer: 'An obstructive apnea shows continued or increasing respiratory effort (thoracic and abdominal excursions present) despite cessation of airflow for at least 10 seconds. A central apnea shows absence of both airflow and respiratory effort for at least 10 seconds. The key differentiator is the presence or absence of effort, best detected by esophageal manometry or calibrated RIP belts.',
    difficulty: 1,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 101,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is paradoxical breathing, and what does it indicate on a polysomnogram?',
    answer: 'Paradoxical breathing occurs when the thoracic and abdominal respiratory effort bands move in opposite directions rather than in synchrony. On PSG, this appears as out-of-phase deflections on the RIP channels. It indicates upper airway obstruction, as the patient generates inspiratory effort against a closed or narrowed airway, causing the chest wall to retract while the abdomen expands.',
    difficulty: 1,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 102,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is flow limitation, and how is it identified on a nasal pressure transducer tracing?',
    answer: 'Flow limitation refers to a reduction in airflow that does not meet criteria for an apnea or hypopnea but reflects increased upper airway resistance. On the nasal pressure transducer signal, it appears as flattening of the inspiratory portion of the flow waveform, changing from a rounded sinusoidal shape to a plateau or "squared-off" contour, indicating partial airway collapse.',
    difficulty: 1,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 103,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is an autonomic arousal, and why is it clinically significant even without a cortical EEG arousal?',
    answer: 'An autonomic arousal is a transient activation of the sympathetic nervous system evidenced by changes such as heart rate acceleration, blood pressure surge, or peripheral vasoconstriction without meeting EEG criteria for a cortical arousal (a 3-second frequency shift). These events can fragment sleep and contribute to daytime sleepiness and cardiovascular morbidity even when the standard arousal index appears normal.',
    difficulty: 3,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 104,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is cyclic alternating pattern (CAP), and what does a high CAP rate suggest?',
    answer: 'CAP is a periodic EEG pattern during NREM sleep consisting of alternating sequences of transient activations (phase A) and background quiescence (phase B), each lasting 2-60 seconds. A high CAP rate indicates NREM sleep instability and is associated with conditions causing sleep fragmentation such as obstructive sleep apnea, periodic limb movements, and chronic insomnia.',
    difficulty: 3,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 105,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the sleep fragmentation index, and how is it calculated?',
    answer: 'The sleep fragmentation index quantifies the degree of sleep disruption by combining the arousal index (number of arousals per hour of sleep) with the sleep stage transition index (number of transitions to lighter sleep or wakefulness per hour). A higher fragmentation index correlates with greater daytime sleepiness and impaired neurocognitive function.',
    difficulty: 1,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 106,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do you differentiate a mixed apnea from an obstructive or central apnea on PSG?',
    answer: 'A mixed apnea begins with a central component (absent airflow and absent respiratory effort) followed by an obstructive component (continued absent airflow with resumption of respiratory effort). The total event must last at least 10 seconds. The initial effort-free portion transitions to visible thoracoabdominal excursions against a closed airway.',
    difficulty: 2,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 107,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the respiratory effort-related arousal (RERA), and how is it scored?',
    answer: 'A RERA is a sequence of breaths lasting at least 10 seconds characterized by increasing respiratory effort or flattening of the nasal pressure waveform that does not meet criteria for an apnea or hypopnea but leads to an arousal from sleep. It is counted in the respiratory disturbance index (RDI) but not in the apnea-hypopnea index (AHI).',
    difficulty: 2,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 108,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What does a "sawtooth" pattern on the oximetry tracing during a PSG typically indicate?',
    answer: 'A sawtooth or cyclical pattern of repetitive oxygen desaturations and resaturations on the SpO2 channel typically indicates recurrent obstructive respiratory events. The periodic dips correspond to apneas or hypopneas, with resaturation occurring during the intervening recovery breaths. The depth and frequency of the desaturations reflect the severity of obstructive sleep apnea.',
    difficulty: 1,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 109,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What PSG findings suggest REM-related obstructive sleep apnea versus NREM-predominant disease?',
    answer: 'REM-related OSA shows respiratory events predominantly or exclusively during REM sleep, with a REM AHI at least twice the NREM AHI. It is more common in women, younger patients, and those with milder overall AHI. NREM-predominant disease tends to occur in more severe OSA and is often associated with greater oxygen desaturation across all sleep stages.',
    difficulty: 2,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 110,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does body position affect respiratory event scoring, and what is positional OSA?',
    answer: 'Positional OSA is defined when the supine AHI is at least twice the non-supine AHI, with the supine AHI meeting diagnostic thresholds. Body position is recorded during PSG using a position sensor. Positional therapy (avoiding the supine position) may be a treatment option for these patients. Scoring should account for time spent in each position to avoid misrepresenting severity.',
    difficulty: 3,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 111,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is alpha-delta sleep, and with which clinical conditions is it associated?',
    answer: 'Alpha-delta sleep is an atypical PSG pattern in which alpha frequency activity (8-13 Hz) intrudes into delta wave sleep during N3. This alpha intrusion is thought to represent a state of incomplete deep sleep. It is most commonly associated with fibromyalgia, chronic pain syndromes, and rheumatoid arthritis, and may explain the non-restorative sleep these patients report.',
    difficulty: 3,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 112,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is sleep onset REM period (SOREMP), and what is its significance when found on diagnostic PSG?',
    answer: 'A SOREMP is defined as the occurrence of REM sleep within 15 minutes of sleep onset. On a diagnostic nocturnal PSG, a SOREMP can occur due to REM rebound from prior sleep deprivation, medication withdrawal (especially REM-suppressing drugs), or underlying narcolepsy. In the context of a positive MSLT, a nocturnal SOREMP can substitute for one of the two required SOREMPs in diagnosing narcolepsy.',
    difficulty: 3,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 113,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is Cheyne-Stokes breathing pattern on PSG, and how does it differ from standard central apneas?',
    answer: 'Cheyne-Stokes respiration appears on PSG as a crescendo-decrescendo pattern of airflow and effort alternating with central apneas or hypopneas in a regular cyclical fashion. The cycle length is typically 45-90 seconds. Unlike isolated central apneas, CSR shows a smooth waxing and waning ventilatory pattern and is most commonly associated with heart failure or stroke.',
    difficulty: 2,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 114,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the PSG characteristics of sleep-related hypoventilation, and how is it diagnosed?',
    answer: 'Sleep-related hypoventilation is diagnosed when arterial PCO2 (or surrogate such as transcutaneous CO2 or end-tidal CO2) rises to greater than 55 mmHg for at least 10 minutes, or increases by 10 mmHg or more above an awake supine value to exceed 50 mmHg for at least 10 minutes during sleep. SpO2 monitoring alone may miss hypoventilation if supplemental oxygen is in use.',
    difficulty: 3,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 115,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How is the respiratory disturbance index (RDI) different from the apnea-hypopnea index (AHI)?',
    answer: 'The AHI includes only apneas and hypopneas per hour of sleep. The RDI includes apneas, hypopneas, and respiratory effort-related arousals (RERAs) per hour of sleep. Therefore, the RDI is always equal to or greater than the AHI. The distinction matters clinically because some patients with a normal AHI may have a significantly elevated RDI due to frequent RERAs.',
    difficulty: 1,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 116,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What artifact can ECG signal produce on EEG channels, and how can it be identified?',
    answer: 'ECG artifact appears on EEG channels as regularly spaced sharp deflections that correspond precisely to the QRS complexes on the ECG channel. It is identified by its fixed periodicity matching the heart rate and its presence across multiple EEG derivations simultaneously. It can mimic epileptiform discharges or sleep spindles and must not be confused with true cerebral activity.',
    difficulty: 2,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 117,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the significance of prolonged sleep latency on a diagnostic PSG?',
    answer: 'Prolonged sleep latency (greater than 30 minutes) on diagnostic PSG may indicate heightened arousal or hyperarousal states such as psychophysiological insomnia, first-night effect, anxiety, pain, or environmental discomfort. It can also result from circadian misalignment or stimulant use. The technologist should document potential contributing factors including room conditions and patient complaints.',
    difficulty: 1,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 118,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What does the absence of REM sleep on a full-night diagnostic PSG suggest?',
    answer: 'Absent REM sleep may result from REM-suppressing medications (SSRIs, SNRIs, tricyclics, MAOIs), alcohol consumption, severe untreated OSA (which can preferentially disrupt REM), first-night effect, or acute sleep deprivation causing excessive N3 rebound. It may also occur with significant circadian disruption. The finding should prompt review of the medication list and consideration for a repeat study.',
    difficulty: 2,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 119,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How is the oxygen desaturation index (ODI) calculated, and what clinical information does it provide beyond the AHI?',
    answer: 'The ODI is the number of times per hour of sleep that the SpO2 drops by a specified threshold (commonly 3% or 4%) from baseline. It provides information about the hypoxemic burden of sleep-disordered breathing independent of event classification. A high ODI relative to the AHI may suggest prolonged hypopneas, overlap with COPD, or hypoventilation contributing to desaturation beyond discrete apnea events.',
    difficulty: 3,
    topic: 'Advanced PSG Interpretation',
    isFree: false,
    orderIndex: 120,
  },

  // ============================================================
  // PEDIATRIC SLEEP MEDICINE (cards 121-135)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do the criteria for scoring a pediatric obstructive apnea differ from adult criteria?',
    answer: 'In children, an obstructive apnea is scored when there is a drop in the peak thermal sensor signal by 90% or more of baseline for a duration of at least two missed breaths (rather than the 10-second rule used in adults). Respiratory effort must be present throughout the event. This shorter duration threshold reflects the faster respiratory rate in children.',
    difficulty: 2,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 121,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What AHI threshold is considered abnormal in pediatric patients, and how does this compare to adults?',
    answer: 'In children, an AHI of 1 event per hour or greater is considered abnormal, in contrast to the adult threshold of 5 or more events per hour. Pediatric OSA is classified as mild (AHI 1-5), moderate (AHI 5-10), and severe (AHI greater than 10). Even a low AHI in children can be clinically significant due to the impact on growth, behavior, and neurocognitive development.',
    difficulty: 1,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 122,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the most common cause of obstructive sleep apnea in children, and what is the first-line treatment?',
    answer: 'Adenotonsillar hypertrophy is the most common cause of OSA in otherwise healthy children. The first-line treatment is adenotonsillectomy, which resolves OSA in approximately 75-80% of non-obese children. Post-surgical PSG is recommended in children with severe OSA, obesity, craniofacial anomalies, or neuromuscular disorders to confirm resolution.',
    difficulty: 1,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 123,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does pediatric PSG electrode montage differ from the standard adult setup?',
    answer: 'Pediatric PSG uses the same basic electrode positions but with age-appropriate modifications. Neonates and infants may require additional monitoring such as transcutaneous CO2. The EEG derivations are the same (frontal, central, occipital referenced to contralateral mastoid), but electrode impedances may be harder to maintain on smaller heads. End-tidal CO2 monitoring is recommended for all pediatric studies to detect hypoventilation.',
    difficulty: 1,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 124,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the unique characteristics of sleep architecture in infants compared to adults?',
    answer: 'Infants spend approximately 50% of total sleep time in active sleep (the precursor to REM), compared to 20-25% in adults. Sleep onset in newborns typically begins with active sleep rather than NREM. Total sleep time is 14-17 hours per day in newborns. Sleep cycles are shorter, approximately 50-60 minutes, and the distinction between quiet and active sleep becomes more defined over the first several months of life.',
    difficulty: 2,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 125,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is behavioral insomnia of childhood, and what are its two subtypes?',
    answer: 'Behavioral insomnia of childhood is a condition in which a child has difficulty falling or staying asleep due to behavioral factors. The sleep-onset association type occurs when a child requires specific conditions to fall asleep (such as being rocked or fed) and cannot self-soothe after normal nighttime awakenings. The limit-setting type occurs when a caregiver fails to enforce appropriate bedtime boundaries, leading to bedtime resistance and delayed sleep onset.',
    difficulty: 1,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 126,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What modifiable risk factors for sudden infant death syndrome (SIDS) should sleep professionals be aware of?',
    answer: 'Modifiable SIDS risk factors include prone or side sleeping position (supine is recommended), soft bedding or loose objects in the crib, bed sharing with adults, overheating, prenatal and postnatal tobacco smoke exposure, and maternal alcohol or drug use. Protective factors include pacifier use during sleep, breastfeeding, room sharing without bed sharing, and immunizations. The "Back to Sleep" campaign significantly reduced SIDS rates.',
    difficulty: 1,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 127,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does obesity affect the presentation and management of pediatric OSA?',
    answer: 'Obese children have a higher prevalence of OSA that is less likely to resolve with adenotonsillectomy alone (approximately 50% residual OSA post-surgery versus 20% in non-obese children). The pathophysiology shifts from primarily lymphoid hypertrophy to include pharyngeal fat deposition and reduced lung volumes. CPAP therapy and weight management may be necessary as adjunctive or primary treatments in obese pediatric patients.',
    difficulty: 3,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 128,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the clinical signs and symptoms of obstructive sleep apnea specific to children that differ from adult presentations?',
    answer: 'Unlike adults who primarily present with excessive daytime sleepiness, children with OSA more commonly exhibit hyperactivity, inattention, behavioral problems, and poor school performance. Other pediatric-specific signs include mouth breathing, enuresis, failure to thrive, and paradoxical inward chest wall movement during sleep. Morning headaches and tonsillar hypertrophy on examination are also important indicators.',
    difficulty: 2,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 129,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the recommended approach for CPAP titration in pediatric patients?',
    answer: 'Pediatric CPAP titration follows the same general principles as adult titration but starts at lower pressures (typically 4 cmH2O) with smaller increments (1 cmH2O). Pressure increases are made to eliminate obstructive apneas, hypopneas, RERAs, and snoring. Interface selection is critical as pediatric masks must fit smaller facial structures, and mid-face growth concerns require monitoring. Bilevel PAP is considered when pressures exceed 12-15 cmH2O or for comfort intolerance.',
    difficulty: 3,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 130,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What EEG differences exist when scoring sleep stages in children compared to adults?',
    answer: 'Children generate higher-amplitude slow-wave activity than adults, making N3 scoring more straightforward. Hypnagogic hypersynchrony (bursts of high-amplitude rhythmic theta or delta) is a normal finding during drowsiness in children and should not be mistaken for pathology. Sleep spindle frequency may be slightly slower in young children, and posterior dominant rhythm develops gradually, reaching adult alpha frequency by approximately age 8.',
    difficulty: 3,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 131,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is apparent life-threatening event (ALTE) or brief resolved unexplained event (BRUE), and how does it relate to sleep evaluation?',
    answer: 'BRUE (formerly ALTE) is an episode in an infant younger than one year involving a brief and now-resolved combination of cyanosis or pallor, absent or irregular breathing, altered tone, or altered responsiveness. While most BRUEs are benign, evaluation may include PSG if obstructive sleep apnea, central apnea of infancy, or gastroesophageal reflux during sleep is suspected as a contributing cause.',
    difficulty: 2,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 132,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is congenital central hypoventilation syndrome (CCHS), and how is it managed during sleep?',
    answer: 'CCHS is a rare genetic disorder caused by PHOX2B gene mutations resulting in absent or diminished ventilatory response to hypercapnia and hypoxemia, particularly during sleep. Affected children require lifelong ventilatory support during sleep, typically via tracheostomy with mechanical ventilation in infancy, with potential transition to noninvasive ventilation or diaphragm pacing as they grow. PSG with CO2 monitoring is essential for management.',
    difficulty: 3,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 133,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does Down syndrome increase the risk of obstructive sleep apnea in children?',
    answer: 'Children with Down syndrome have multiple anatomical and physiological factors predisposing them to OSA, including midface hypoplasia, relative macroglossia, a narrow nasopharynx, adenotonsillar hypertrophy, hypotonia of upper airway muscles, and increased prevalence of obesity. The prevalence of OSA in Down syndrome exceeds 50%, and the American Academy of Pediatrics recommends PSG screening by age 4.',
    difficulty: 2,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 134,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the normal sleep duration recommendations for different pediatric age groups?',
    answer: 'According to consensus guidelines, recommended sleep durations are: infants 4-12 months need 12-16 hours (including naps); toddlers 1-2 years need 11-14 hours; preschoolers 3-5 years need 10-13 hours; school-age children 6-12 years need 9-12 hours; and teenagers 13-18 years need 8-10 hours. Insufficient sleep in children is associated with behavioral problems, impaired learning, and increased obesity risk.',
    difficulty: 1,
    topic: 'Pediatric Sleep Medicine',
    isFree: false,
    orderIndex: 135,
  },

  // ============================================================
  // MEDICAL CONDITIONS & SLEEP (cards 136-155)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is overlap syndrome, and why does it carry a worse prognosis than either condition alone?',
    answer: 'Overlap syndrome is the coexistence of obstructive sleep apnea and chronic obstructive pulmonary disease (COPD) in the same patient. It carries a worse prognosis because the combined effects produce more severe nocturnal hypoxemia and hypercapnia than either condition alone. Patients are at increased risk for pulmonary hypertension, right heart failure, and daytime respiratory failure. Treatment typically requires CPAP or bilevel PAP, often with supplemental oxygen.',
    difficulty: 2,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 136,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'Why does oxygen desaturation during sleep tend to be more pronounced in patients with COPD compared to those with OSA alone?',
    answer: 'COPD patients already have a lower baseline awake PaO2 and operate on the steep portion of the oxyhemoglobin dissociation curve, so even small reductions in ventilation during sleep cause disproportionately large drops in SpO2. Additionally, COPD patients lose the accessory muscle contribution to breathing during REM atonia, have blunted ventilatory responses to hypoxia and hypercapnia, and have increased ventilation-perfusion mismatch.',
    difficulty: 3,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 137,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the relationship between congestive heart failure and central sleep apnea?',
    answer: 'Congestive heart failure predisposes to central sleep apnea, particularly Cheyne-Stokes respiration, through several mechanisms: increased circulation time delays chemoreceptor feedback, pulmonary congestion stimulates vagal irritant receptors increasing ventilatory drive, and low cardiac output elevates plant gain. The prevalence of CSA-CSR in systolic heart failure is 30-50%. Optimizing heart failure treatment (diuretics, afterload reduction, cardiac resynchronization) may reduce the severity of CSA.',
    difficulty: 2,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 138,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does neuromuscular disease affect breathing during sleep, and what monitoring is recommended?',
    answer: 'Neuromuscular diseases (such as ALS, muscular dystrophies, and myasthenia gravis) weaken the respiratory muscles, particularly the diaphragm. During REM sleep, when accessory muscle tone is lost, these patients rely entirely on a weakened diaphragm, leading to hypoventilation with hypoxemia and hypercapnia. PSG with transcutaneous or end-tidal CO2 monitoring is recommended. Noninvasive ventilation (typically bilevel PAP) is initiated when nocturnal hypoventilation develops.',
    difficulty: 2,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 139,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the relationship between epilepsy and sleep, and how can seizures be differentiated from parasomnias on PSG?',
    answer: 'Sleep and epilepsy are bidirectionally related: sleep deprivation lowers the seizure threshold, and seizures disrupt sleep architecture. Nocturnal frontal lobe epilepsy can mimic parasomnias with brief stereotyped motor events. Differentiation relies on expanded EEG montage showing ictal discharges, the stereotyped nature and brief duration of epileptic events, and their tendency to occur multiple times per night with similar semiology, unlike the variable presentations of parasomnias.',
    difficulty: 3,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 140,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does gastroesophageal reflux disease (GERD) interact with obstructive sleep apnea?',
    answer: 'GERD and OSA have a bidirectional relationship. The negative intrathoracic pressure swings during obstructive events increase the transdiaphragmatic pressure gradient, promoting gastric acid reflux. Conversely, reflux-induced arousals and microaspiration can worsen upper airway inflammation and edema, potentially aggravating OSA. CPAP treatment can reduce reflux events by stabilizing intrathoracic pressure, and treating GERD may modestly improve OSA symptoms.',
    difficulty: 3,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 141,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does chronic pain affect sleep architecture and sleep quality?',
    answer: 'Chronic pain disrupts sleep through multiple mechanisms: increased sleep onset latency, frequent arousals, reduced total sleep time, and altered sleep architecture with decreased N3 and REM sleep. Alpha intrusions into NREM sleep (alpha-delta pattern) are commonly observed. The relationship is bidirectional, as fragmented sleep lowers the pain threshold and increases pain sensitivity the following day, creating a vicious cycle that requires addressing both sleep and pain management simultaneously.',
    difficulty: 2,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 142,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the effects of opioid medications on sleep and breathing during sleep?',
    answer: 'Opioids suppress respiratory drive and can cause central apneas, ataxic (irregular) breathing patterns, and sustained hypoxemia during sleep. They reduce N3 and REM sleep, increase N1 and N2 sleep, and may cause sleep fragmentation. Chronic opioid use is associated with central sleep apnea in 25-50% of patients. ASV was previously used but is now cautiously considered. Bilevel ST mode or servo-ventilation with appropriate monitoring may be needed for opioid-related sleep-disordered breathing.',
    difficulty: 3,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 143,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What changes in sleep architecture are associated with major depression?',
    answer: 'Major depression is associated with characteristic sleep architecture changes including shortened REM latency (early onset of the first REM period), increased REM density (more rapid eye movements per REM period), increased total REM sleep percentage, reduced N3 slow-wave sleep, increased sleep fragmentation, and either insomnia or hypersomnia. These changes are used as biological markers and often improve with successful treatment.',
    difficulty: 2,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 144,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does pregnancy affect sleep and sleep-disordered breathing?',
    answer: 'During pregnancy, sleep-disordered breathing may develop or worsen due to weight gain, upper airway edema from fluid retention, elevated diaphragm from uterine enlargement, and progesterone-driven increases in ventilatory demand. Snoring prevalence increases significantly. Gestational OSA is associated with preeclampsia, gestational diabetes, and fetal growth restriction. Sleep quality deteriorates progressively through the trimesters, with increased insomnia, restless legs symptoms, and nocturia.',
    difficulty: 3,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 145,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What effect do beta-blockers have on sleep?',
    answer: 'Lipophilic beta-blockers (such as propranolol and metoprolol) cross the blood-brain barrier and can cause insomnia, nightmares, and sleep disturbance by suppressing nocturnal melatonin secretion. They may also increase the frequency of periodic limb movements during sleep. Hydrophilic beta-blockers (such as atenolol) have fewer central nervous system effects and are less likely to disrupt sleep. Supplemental melatonin may help counteract the sleep disturbance.',
    difficulty: 2,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 146,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the impact of hypothyroidism on sleep-disordered breathing?',
    answer: 'Hypothyroidism can contribute to obstructive sleep apnea through multiple mechanisms including macroglossia, mucosal edema of the upper airway, weight gain, decreased respiratory muscle function, and blunted ventilatory drive. Central sleep apnea may also occur due to impaired chemosensitivity. Treatment with thyroid hormone replacement can improve or resolve sleep-disordered breathing, making thyroid function testing appropriate in newly diagnosed OSA patients.',
    difficulty: 2,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 147,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does acromegaly predispose to sleep apnea?',
    answer: 'Acromegaly, caused by excess growth hormone, leads to OSA through soft tissue hypertrophy of the tongue and pharyngeal structures, mandibular prognathism (which paradoxically does not protect against OSA due to the soft tissue changes), and thickening of pharyngeal mucosa. Central sleep apnea also occurs in acromegaly, possibly due to altered ventilatory chemosensitivity. Sleep apnea prevalence in acromegaly exceeds 60%, and severity may improve with treatment of the underlying growth hormone excess.',
    difficulty: 3,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 148,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the effect of alcohol consumption on sleep architecture and sleep-disordered breathing?',
    answer: 'Alcohol initially acts as a sedative, reducing sleep onset latency and increasing N3 sleep in the first half of the night. As it is metabolized, a rebound effect causes sleep fragmentation, increased REM sleep, and frequent awakenings in the second half. Alcohol also relaxes upper airway muscles, increases upper airway resistance, and can convert primary snoring into obstructive apnea or worsen existing OSA severity by 2-3 fold.',
    difficulty: 1,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 149,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does stroke affect sleep architecture, and what sleep disorders commonly develop after stroke?',
    answer: 'Stroke disrupts sleep architecture by damaging brainstem and cortical centers involved in sleep-wake regulation. Common post-stroke sleep disorders include central sleep apnea (especially with brainstem infarcts), obstructive sleep apnea (present in over 50% of stroke patients), insomnia, hypersomnia, and circadian rhythm disruption. Sleep-disordered breathing after stroke is associated with worse neurological recovery and higher mortality. Screening and treatment are recommended during rehabilitation.',
    difficulty: 3,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 150,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the effects of selective serotonin reuptake inhibitors (SSRIs) on sleep architecture?',
    answer: 'SSRIs suppress REM sleep by increasing serotonergic tone, leading to prolonged REM latency, reduced total REM percentage, and sometimes increased eye movements during the remaining REM periods. They may increase periodic limb movements during sleep and can trigger or worsen REM sleep behavior disorder. SSRIs often cause insomnia or daytime sedation depending on the specific agent, and may increase the frequency of nocturnal bruxism.',
    difficulty: 2,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 151,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the relationship between atrial fibrillation and obstructive sleep apnea?',
    answer: 'OSA and atrial fibrillation are strongly associated, with OSA present in approximately 50% of AF patients. The mechanisms linking them include intermittent hypoxemia, intrathoracic pressure swings, sympathetic surges, and atrial remodeling from chronic stretch. Untreated OSA increases the risk of AF recurrence after cardioversion or ablation. CPAP therapy has been shown to reduce AF recurrence rates, making OSA screening an important component of AF management.',
    difficulty: 3,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 152,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do corticosteroids affect sleep when administered to patients?',
    answer: 'Corticosteroids cause insomnia by increasing alertness and suppressing melatonin secretion. They reduce total sleep time, decrease N3 and REM sleep, increase N1 and wakefulness after sleep onset, and can cause vivid dreams or nightmares. These effects are dose-dependent and more pronounced with evening administration. When possible, dosing earlier in the day can minimize sleep disruption. Even short courses of corticosteroids can significantly fragment sleep architecture.',
    difficulty: 1,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 153,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What sleep problems are commonly seen in patients with Parkinson disease?',
    answer: 'Parkinson disease is associated with multiple sleep disorders including REM sleep behavior disorder (which may precede motor symptoms by years), insomnia, excessive daytime sleepiness, restless legs syndrome, periodic limb movements, sleep fragmentation due to motor symptoms (rigidity, tremor), and nocturia. Sleep architecture shows reduced N3 and REM sleep. The dopaminergic medications used to treat Parkinson can both improve and worsen different aspects of sleep.',
    difficulty: 2,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 154,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the impact of end-stage renal disease on sleep, and how does dialysis timing affect sleep quality?',
    answer: 'End-stage renal disease causes sleep disruption through uremic toxin accumulation, metabolic derangements, restless legs syndrome (affecting 20-60% of dialysis patients), periodic limb movements, and sleep apnea (both central and obstructive). Sleep quality is generally poor with increased fragmentation and reduced total sleep time. Dialysis timing matters because nocturnal dialysis and more frequent dialysis sessions have been shown to improve sleep quality compared to conventional thrice-weekly schedules.',
    difficulty: 3,
    topic: 'Medical Conditions & Sleep',
    isFree: false,
    orderIndex: 155,
  },

  // ============================================================
  // PAP TROUBLESHOOTING ADVANCED (cards 156-170)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is treatment-emergent central sleep apnea (complex sleep apnea), and how should it be managed?',
    answer: 'Treatment-emergent CSA occurs when central apneas develop or persist after obstructive events have been adequately treated with CPAP, despite the absence of significant central apneas on the diagnostic study. It occurs in approximately 5-15% of OSA patients starting CPAP. Management includes continued CPAP for several weeks (as it often resolves spontaneously), pressure optimization, and if persistent, consideration of adaptive servo-ventilation (ASV) or bilevel ST mode.',
    difficulty: 2,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 156,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'When is supplemental oxygen added to PAP therapy, and how is it administered?',
    answer: 'Supplemental oxygen is added when adequate PAP eliminates obstructive events but sustained SpO2 remains below 88-90%, indicating coexisting hypoventilation, parenchymal lung disease, or other causes of hypoxemia. Oxygen is bled into the PAP circuit, typically at 1-4 LPM, connected at the mask or machine outlet. The flow rate is titrated to maintain SpO2 at or above 90%. End-tidal or transcutaneous CO2 monitoring is recommended to ensure oxygen does not mask worsening hypoventilation.',
    difficulty: 2,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 157,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How should PAP therapy be adjusted for patients with obesity hypoventilation syndrome?',
    answer: 'OHS patients often require bilevel PAP (BPAP) in spontaneous/timed (ST) mode rather than CPAP, because they need both upper airway splinting and augmented ventilation to correct hypercapnia. The IPAP-EPAP pressure differential drives tidal volume. A backup rate ensures minimum ventilation during sleep. An average volume-assured pressure support (AVAPS) mode can automatically adjust pressures to maintain target tidal volume. CO2 monitoring during titration is essential to confirm adequate ventilation.',
    difficulty: 3,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 158,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What special PAP considerations exist for bariatric surgery patients?',
    answer: 'Bariatric patients require careful perioperative PAP management. Preoperative PSG is recommended to identify and treat OSA before surgery. CPAP should be used perioperatively to reduce respiratory complications. Pressure requirements often change post-surgery as weight loss progresses, necessitating repeat titration studies. Patients should continue PAP until repeat testing confirms resolution of OSA, which occurs in approximately 60-70% of patients after significant weight loss.',
    difficulty: 2,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 159,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do you interpret a PAP compliance download showing a high residual AHI despite adequate usage hours?',
    answer: 'A high residual AHI on PAP data suggests inadequate treatment and may indicate mask leak undermining effective pressure delivery, mouth breathing on nasal mask therapy, insufficient pressure settings, positional or REM-related events not controlled at the current pressure, treatment-emergent central apneas, or weight change since the titration study. Troubleshooting requires reviewing the detailed data including leak graphs, event type breakdown, and pressure response, followed by targeted intervention.',
    difficulty: 3,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 160,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the clinical significance of large mask leak on a PAP download, and what threshold defines excessive leak?',
    answer: 'Large mask leak reduces effective therapeutic pressure delivery and can trigger auto-titrating algorithms to inappropriately increase pressure, worsening the leak. Most device manufacturers define large leak as exceeding 24-36 LPM (varies by manufacturer) above intentional vent flow. Clinically significant leak causes dry mouth, eye irritation, aerophagia, and sleep fragmentation. Solutions include mask refitting, chin straps for mouth leak on nasal masks, or switching to full-face masks.',
    difficulty: 1,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 161,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is adaptive servo-ventilation (ASV), and when is it contraindicated?',
    answer: 'ASV is a mode of noninvasive ventilation that continuously adjusts inspiratory pressure support on a breath-by-breath basis to stabilize breathing patterns. It targets central apneas and periodic breathing by providing more support during hypopneas and less during periods of hyperventilation. ASV is contraindicated in patients with symptomatic heart failure with reduced ejection fraction (LVEF less than or equal to 45%) based on the SERVE-HF trial, which showed increased cardiovascular mortality in this population.',
    difficulty: 3,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 162,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What strategies can improve PAP adherence in patients who report claustrophobia with the mask?',
    answer: 'Strategies include systematic desensitization (gradually wearing the mask while awake, then with pressure, then during naps before full-night use), trying different mask styles (nasal pillows often feel less confining than full-face masks), using ramp features to start at low pressure and gradually increase, applying relaxation techniques, and considering short-term anxiolytic medication in severe cases. Behavioral support and positive reinforcement of incremental progress are important components.',
    difficulty: 1,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 163,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does auto-titrating CPAP (APAP) adjust pressures, and what are its limitations?',
    answer: 'APAP devices use proprietary algorithms to detect flow limitation, snoring, apneas, and hypopneas and respond by increasing pressure. When the airway is stable, pressure is gradually reduced to the minimum effective level. Limitations include inability to differentiate obstructive from central events (potentially overtreating centrals with pressure), poor performance in patients with significant heart failure, COPD, or obesity hypoventilation, and inaccuracy with large mask leaks that corrupt the flow signal.',
    difficulty: 2,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 164,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is expiratory pressure relief (EPR/C-Flex/A-Flex), and when is it useful?',
    answer: 'Expiratory pressure relief is a comfort feature that reduces pressure during early exhalation by 1-3 cmH2O (EPR setting 1-3) before restoring the full therapeutic pressure for the next inspiration. This reduces the sense of breathing against pressure and can improve comfort and adherence, particularly for patients who complain of difficulty exhaling against CPAP pressure. It should be reduced or eliminated if residual events are not adequately controlled.',
    difficulty: 1,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 165,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What factors should guide the choice between bilevel PAP spontaneous mode and bilevel PAP ST mode?',
    answer: 'Bilevel spontaneous mode provides two pressure levels triggered by the patient\'s own respiratory effort and is appropriate when the patient has adequate respiratory drive but needs pressure differential for comfort or ventilatory support. Bilevel ST (spontaneous/timed) mode adds a mandatory backup rate and is indicated when the patient has unreliable respiratory drive, such as in central sleep apnea, neuromuscular disease, or obesity hypoventilation, to ensure minimum ventilation during apneic periods.',
    difficulty: 3,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 166,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How should PAP therapy be managed during an acute upper respiratory infection?',
    answer: 'During an acute URI, patients may experience nasal congestion making nasal mask use difficult, increased mouth breathing, and mask discomfort. Recommendations include using heated humidification to manage mucosal dryness, temporarily switching from nasal to full-face mask if congestion is severe, using nasal saline irrigation or short-term topical decongestants, and continuing PAP therapy whenever possible. Discontinuation during illness increases the risk of cardiovascular events and worsened daytime symptoms.',
    difficulty: 1,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 167,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is aerophagia in PAP therapy, and how should it be managed?',
    answer: 'Aerophagia is the swallowing of air during PAP use, causing gastric distension, bloating, belching, and abdominal discomfort. It is more common at higher pressures and with mouth breathing. Management strategies include reducing maximum pressure if the auto-titrating range allows, switching to bilevel PAP to lower expiratory pressure, addressing mouth leak with chin straps or full-face masks, elevating the head of bed, using EPR features, and avoiding eating close to bedtime.',
    difficulty: 2,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 168,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'When reviewing APAP data, what does the 90th or 95th percentile pressure indicate, and how is it used clinically?',
    answer: 'The 90th or 95th percentile pressure represents the pressure at or below which the device operated for 90% or 95% of the usage time. It reflects the effective therapeutic pressure needed to control the majority of respiratory events. Clinically, it is used to set a fixed CPAP pressure (if converting from APAP) or to evaluate whether the current pressure range is appropriate. An excessively high percentile pressure may indicate mask leak, mouth breathing, or weight gain.',
    difficulty: 3,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 169,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the role of heated humidification in PAP therapy, and what problems can arise from inadequate or excessive humidification?',
    answer: 'Heated humidification warms and moistens the delivered air to prevent mucosal drying, nasal congestion, epistaxis, and mouth dryness that are common with PAP use, especially at higher pressures. Inadequate humidification causes these drying symptoms and may reduce adherence. Excessive humidification or a cool room can cause condensation in the tubing (rainout), which may trigger awakenings or mask sputtering. Heated tubing can minimize rainout by maintaining temperature throughout the circuit.',
    difficulty: 1,
    topic: 'PAP Troubleshooting Advanced',
    isFree: false,
    orderIndex: 170,
  },

  // ============================================================
  // SLEEP PHARMACOLOGY (cards 171-185)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do benzodiazepine receptor agonists (Z-drugs) like zolpidem and zaleplon promote sleep, and what risks are associated with their use?',
    answer: 'Z-drugs selectively bind to the alpha-1 subunit of the GABA-A receptor, enhancing inhibitory neurotransmission to promote sleep onset. Unlike traditional benzodiazepines, they have less effect on sleep architecture, causing minimal N3 or REM suppression at therapeutic doses. Risks include complex sleep behaviors (sleepwalking, sleep-eating, sleep-driving), next-day impairment, tolerance, dependence, rebound insomnia, and increased fall risk in the elderly.',
    difficulty: 2,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 171,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are dual orexin receptor antagonists (DORAs), and how do they differ mechanistically from older sedative-hypnotics?',
    answer: 'DORAs (suvorexant, lemborexant) block both orexin-1 and orexin-2 receptors, inhibiting the wake-promoting orexin (hypocretin) signaling system. Unlike benzodiazepines and Z-drugs that broadly enhance GABA-mediated inhibition, DORAs specifically reduce wakefulness drive without globally suppressing CNS activity. This mechanism results in more physiological sleep architecture preservation, lower abuse potential, and less respiratory depression, making them potentially safer in patients with mild-moderate OSA.',
    difficulty: 2,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 172,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the mechanism of action of ramelteon, and for which type of insomnia is it most effective?',
    answer: 'Ramelteon is a selective melatonin receptor agonist with high affinity for MT1 and MT2 receptors in the suprachiasmatic nucleus. It promotes sleep by mimicking melatonin\'s effect on circadian timing and reducing the alerting signal. It is most effective for sleep-onset insomnia and has no significant effect on sleep maintenance. It has no abuse potential, no DEA scheduling, and does not suppress respiratory drive, making it safe for patients with OSA.',
    difficulty: 2,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 173,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is sodium oxybate, and what is its role in treating narcolepsy?',
    answer: 'Sodium oxybate (gamma-hydroxybutyrate) is a CNS depressant that acts on GABA-B receptors. It is FDA-approved for cataplexy and excessive daytime sleepiness in narcolepsy. It consolidates nocturnal sleep, increases N3 slow-wave sleep, and reduces the frequency of cataplexy attacks. It is taken in two divided doses at bedtime and 2.5-4 hours later. Due to its abuse potential and risk of respiratory depression, it is available only through a restricted Risk Evaluation and Mitigation Strategy (REMS) program.',
    difficulty: 2,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 174,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is pitolisant, and how does it treat excessive daytime sleepiness in narcolepsy?',
    answer: 'Pitolisant is a selective histamine H3 receptor inverse agonist/antagonist that increases histamine release in the brain by blocking presynaptic H3 autoreceptors. Enhanced histaminergic neurotransmission promotes wakefulness. It is FDA-approved for excessive daytime sleepiness in narcolepsy. Unlike traditional stimulants, it is not a scheduled controlled substance, does not have significant abuse potential, and does not disrupt nocturnal sleep architecture when dosed in the morning.',
    difficulty: 3,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 175,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is solriamfetol, and how does it differ from traditional stimulants used for hypersomnia?',
    answer: 'Solriamfetol is a selective dopamine and norepinephrine reuptake inhibitor FDA-approved for excessive daytime sleepiness in narcolepsy and obstructive sleep apnea. Unlike amphetamines, it does not promote catecholamine release, which gives it a lower abuse potential (Schedule IV vs Schedule II). It is taken once daily in the morning and does not significantly disrupt nocturnal sleep. It should not be used as a substitute for PAP therapy in OSA but as an adjunct for residual sleepiness.',
    difficulty: 2,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 176,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do traditional benzodiazepines affect sleep architecture differently from Z-drugs?',
    answer: 'Traditional benzodiazepines bind nonselectively to multiple GABA-A receptor subunits (alpha-1, 2, 3, and 5), producing broader effects including anxiolysis, muscle relaxation, and anticonvulsant activity. They significantly reduce N3 slow-wave sleep, may slightly reduce REM sleep, increase N2 sleep with increased spindle activity, and prolong total sleep time. Compared to Z-drugs, benzodiazepines have a higher risk of next-day sedation, tolerance, physical dependence, and respiratory depression.',
    difficulty: 2,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 177,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'Which commonly prescribed medications are known to worsen restless legs syndrome symptoms?',
    answer: 'Medications that can worsen or trigger RLS include dopamine-blocking agents (antipsychotics, metoclopramide, prochlorperazine), antihistamines (diphenhydramine, hydroxyzine), SSRIs and SNRIs (except possibly bupropion), tricyclic antidepressants, lithium, and caffeine. When managing a patient with RLS, reviewing the medication list for these potential exacerbating agents is an important initial step before adding pharmacotherapy for RLS itself.',
    difficulty: 1,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 178,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the role of modafinil in sleep medicine, and what is its mechanism of action?',
    answer: 'Modafinil is a wake-promoting agent FDA-approved for excessive daytime sleepiness in narcolepsy, shift work sleep disorder, and residual sleepiness in treated OSA. Its mechanism is not fully understood but involves inhibition of dopamine reuptake and possibly enhancement of histaminergic and orexinergic pathways. It has a lower abuse potential than amphetamines (Schedule IV) and causes less sympathetic activation, insomnia rebound, and appetite suppression than traditional stimulants.',
    difficulty: 1,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 179,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is augmentation in the context of dopaminergic treatment for restless legs syndrome?',
    answer: 'Augmentation is a paradoxical worsening of RLS symptoms that occurs with long-term dopaminergic therapy (levodopa or dopamine agonists). It manifests as earlier onset of symptoms in the day, spread to previously unaffected body parts (arms, trunk), increased intensity, and shorter latency to symptom onset when at rest. It is the most common complication of dopaminergic RLS treatment and is managed by reducing or discontinuing the dopaminergic agent and switching to alpha-2-delta ligands (gabapentin, pregabalin) or iron supplementation.',
    difficulty: 3,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 180,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does trazodone promote sleep, and why is it commonly prescribed off-label for insomnia?',
    answer: 'Trazodone is a serotonin antagonist and reuptake inhibitor (SARI) that promotes sleep primarily through antagonism of histamine H1 receptors and serotonin 5-HT2A receptors at low doses. It is commonly prescribed off-label for insomnia because it is non-addictive, inexpensive, and not a controlled substance. It may increase N3 sleep. Side effects include morning sedation, orthostatic hypotension, and rarely priapism. Its sedating effects occur at doses (25-100 mg) well below antidepressant doses.',
    difficulty: 1,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 181,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What effect does cannabis use have on sleep architecture and sleep disorders?',
    answer: 'Acute cannabis use may reduce sleep onset latency and increase N3 sleep while suppressing REM sleep. Chronic use is associated with tolerance to these effects and habituation. Cannabis withdrawal can cause significant rebound insomnia, vivid dreams (REM rebound), and poor sleep quality lasting days to weeks. Cannabis may worsen OSA by promoting upper airway muscle relaxation. While some patients report subjective sleep improvement, the evidence does not support cannabis as an effective or safe sleep aid.',
    difficulty: 2,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 182,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What medications must be discontinued before an MSLT, and why?',
    answer: 'REM-suppressing medications (SSRIs, SNRIs, tricyclics, MAOIs, stimulants) must be tapered and discontinued at least 2 weeks before the MSLT (5 weeks for fluoxetine due to its long half-life) because they can artificially prolong REM latency and eliminate SOREMPs, causing a false-negative result for narcolepsy. A urine drug screen should be performed to confirm clearance. The patient should also maintain a regular sleep schedule (documented by sleep diary or actigraphy) for at least 1-2 weeks before testing.',
    difficulty: 2,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 183,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the pharmacological treatment approach for REM sleep behavior disorder?',
    answer: 'The first-line pharmacological treatment for RBD is low-dose clonazepam (0.25-2 mg at bedtime), which reduces injurious dream-enactment behaviors in approximately 80-90% of patients, likely through muscle relaxation and suppression of phasic REM activity. Melatonin (3-12 mg) is considered an alternative or adjunctive therapy, particularly in elderly patients or those with OSA where clonazepam\'s respiratory depressant effects are a concern. Environmental safety measures should always accompany pharmacotherapy.',
    difficulty: 2,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 184,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How do alpha-2-delta calcium channel ligands (gabapentin, pregabalin) work in treating restless legs syndrome?',
    answer: 'Alpha-2-delta ligands bind to the alpha-2-delta subunit of voltage-gated calcium channels, reducing excitatory neurotransmitter release. In RLS, they decrease sensory excitability and improve both sensory symptoms and periodic limb movements. They are now considered first-line therapy over dopamine agonists due to lower risk of augmentation. Gabapentin enacarbil (a prodrug with improved bioavailability) is FDA-approved specifically for RLS. Common side effects include dizziness, somnolence, and peripheral edema.',
    difficulty: 3,
    topic: 'Sleep Pharmacology',
    isFree: false,
    orderIndex: 185,
  },

  // ============================================================
  // PROFESSIONAL PRACTICE & PATIENT MANAGEMENT (cards 186-200)
  // ============================================================
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the key accreditation requirements for a sleep disorders center according to the AASM?',
    answer: 'AASM accreditation requires a board-certified sleep medicine physician as medical director, qualified registered polysomnographic technologists (RPSGT) staffing studies, adherence to AASM scoring and practice standards, comprehensive policies and procedures manual, patient follow-up protocols, quality assurance program, appropriate facility standards (private patient rooms, monitoring capability), and documentation of continuing education for all staff. Accreditation must be renewed every 5 years with ongoing compliance.',
    difficulty: 2,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 186,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What infection control measures are required in the sleep laboratory?',
    answer: 'Sleep lab infection control includes high-level disinfection or disposable single-use respiratory equipment (masks, tubing, filters), cleaning and disinfection of reusable sensors between patients, use of bacterial filters on PAP devices during titrations, laundering linens between patients, hand hygiene protocols, surface disinfection of patient rooms and equipment, screening patients for communicable illnesses, and maintaining written infection control policies reviewed annually. Universal precautions apply to all patient contact.',
    difficulty: 1,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 187,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the core components of cognitive behavioral therapy for insomnia (CBT-I)?',
    answer: 'CBT-I consists of five core components: sleep restriction therapy (limiting time in bed to match actual sleep time to build sleep drive), stimulus control (reassociating the bed with sleep by eliminating non-sleep activities in bed), cognitive restructuring (addressing dysfunctional beliefs about sleep), sleep hygiene education (environmental and behavioral recommendations), and relaxation training (progressive muscle relaxation, guided imagery). CBT-I is recommended as first-line treatment for chronic insomnia before pharmacotherapy.',
    difficulty: 1,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 188,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is stimulus control therapy, and what specific instructions are given to the patient?',
    answer: 'Stimulus control therapy aims to re-establish the bed and bedroom as cues for sleep rather than wakefulness. Specific instructions include: go to bed only when sleepy, use the bed only for sleep and intimacy, if unable to fall asleep within approximately 20 minutes get out of bed and return only when sleepy, maintain a consistent wake time regardless of how much sleep was obtained, and avoid daytime napping. These rules break the association between the bed and wakefulness or anxiety that perpetuates insomnia.',
    difficulty: 1,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 189,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How does sleep restriction therapy work, and what is the typical protocol?',
    answer: 'Sleep restriction therapy works by creating mild sleep deprivation to consolidate sleep and increase sleep efficiency. The patient keeps a sleep diary for 1-2 weeks, and time in bed is restricted to match the average reported total sleep time (minimum 5 hours). As sleep efficiency (total sleep time divided by time in bed) improves to 85-90% or higher, time in bed is gradually increased by 15-30 minutes. This builds homeostatic sleep pressure and reduces time lying awake in bed.',
    difficulty: 2,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 190,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What elements should be included in patient education when initiating PAP therapy?',
    answer: 'Effective PAP education covers the rationale for treatment (health consequences of untreated OSA), realistic expectations for adjustment (adaptation takes days to weeks), proper mask fitting and seal techniques, device operation and care (cleaning humidifier chamber and tubing), using comfort features (ramp, heated humidification, EPR), importance of nightly use for full sleep period, how to access data downloads, when to contact the provider, and troubleshooting common problems (mask leak, dry mouth, nasal congestion). Hands-on demonstration improves outcomes.',
    difficulty: 1,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 191,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What constitutes adequate PAP adherence according to CMS (Medicare) criteria?',
    answer: 'CMS defines PAP adherence as use of the device for at least 4 hours per night on at least 70% of nights during a consecutive 30-day period within the first 90 days of therapy. This is the minimum standard for continued coverage of the PAP device and supplies. While this criterion is used for reimbursement purposes, optimal clinical benefit requires greater usage, with studies showing dose-dependent improvements in outcomes with more hours of nightly use.',
    difficulty: 1,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 192,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'How is telemedicine being applied in sleep medicine, and what are its advantages?',
    answer: 'Telemedicine in sleep medicine includes home sleep apnea testing with remote data interpretation, remote PAP setup and monitoring via cloud-based data management platforms, video consultations for follow-up and troubleshooting, and telemonitoring of PAP compliance and efficacy. Advantages include improved access for rural or mobility-limited patients, earlier intervention when compliance data shows problems, reduced travel burden, cost savings, and equivalent patient satisfaction to in-person visits for routine follow-up.',
    difficulty: 2,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 193,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What quality metrics should a sleep center track for its quality assurance program?',
    answer: 'Essential quality metrics include study failure or repeat rates, scoring reliability (inter-scorer agreement), patient satisfaction scores, PAP adherence rates at 30 days, 90 days, and 1 year, time from referral to diagnostic study, time from diagnosis to treatment initiation, percentage of patients with follow-up within 90 days of starting PAP, residual AHI on treatment, clinical outcome measures (Epworth Sleepiness Scale improvement), and accreditation compliance. Regular review of these metrics drives continuous quality improvement.',
    difficulty: 3,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 194,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the Epworth Sleepiness Scale, and how is it used in clinical practice?',
    answer: 'The Epworth Sleepiness Scale (ESS) is a validated 8-item self-administered questionnaire that measures the likelihood of dozing in eight everyday situations, scored 0-3 each for a total of 0-24. A score of 10 or greater suggests excessive daytime sleepiness. It is used to screen for sleep disorders, quantify sleepiness severity, track treatment response, and document clinical outcomes. Limitations include its subjective nature, poor correlation with objective measures like MSLT, and tendency for patients to underreport sleepiness.',
    difficulty: 1,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 195,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are the indications and limitations of home sleep apnea testing (HSAT) compared to in-laboratory PSG?',
    answer: 'HSAT is indicated for patients with a high pretest probability of moderate-to-severe OSA without significant comorbidities. Limitations include no EEG channels (cannot score sleep stages or arousals), inability to calculate true AHI (uses recording time rather than sleep time, potentially underestimating severity), no technician to troubleshoot data loss, and unsuitability for patients with heart failure, neuromuscular disease, chronic opioid use, or suspected non-OSA sleep disorders. A negative HSAT in a symptomatic patient requires in-lab PSG.',
    difficulty: 2,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 196,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the role of actigraphy in clinical sleep medicine?',
    answer: 'Actigraphy uses a wrist-worn accelerometer to estimate sleep-wake patterns over days to weeks in the patient\'s natural environment. It is clinically useful for evaluating circadian rhythm disorders, documenting sleep schedules before MSLT, assessing insomnia treatment outcomes, and estimating total sleep time in patients with suspected insufficient sleep. It is less accurate than PSG for detecting individual sleep events but provides valuable longitudinal data about habitual sleep patterns that a single-night PSG cannot capture.',
    difficulty: 2,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 197,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What legal and safety considerations apply to patients with untreated excessive daytime sleepiness who drive or operate heavy machinery?',
    answer: 'Sleep professionals have a responsibility to warn patients about the risks of drowsy driving and to document this counseling. While mandatory reporting laws vary by jurisdiction, clinicians should assess driving risk, recommend that severely sleepy patients refrain from driving until treated, and document these discussions. Commercial motor vehicle operators are subject to federal regulations requiring screening and treatment of OSA. Untreated OSA increases motor vehicle accident risk 2-3 fold, and effective treatment normalizes this risk.',
    difficulty: 3,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 198,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What are oral appliance therapy options for OSA, and when are they indicated?',
    answer: 'Mandibular advancement devices (MADs) are the primary oral appliances for OSA. They protrude the mandible forward, enlarging the retroglossal airway space. They are indicated for mild-to-moderate OSA as primary therapy, for patients who prefer them to CPAP, or for patients who cannot tolerate CPAP. Custom-fitted, titratable devices made by a qualified dentist are preferred over over-the-counter devices. Follow-up PSG or HSAT is needed to confirm efficacy, and side effects include temporomandibular joint discomfort and dental changes.',
    difficulty: 2,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 199,
  },
  {
    divisionId: SDS_DIVISION_ID,
    question: 'What is the STOP-Bang questionnaire, and how is it used for OSA screening?',
    answer: 'STOP-Bang is a validated 8-item screening tool for obstructive sleep apnea. It assesses Snoring, Tiredness, Observed apneas, blood Pressure (hypertension), BMI greater than 35, Age over 50, Neck circumference greater than 40 cm, and male Gender. Each item scores 0 or 1, with a total score of 0-8. A score of 0-2 indicates low risk, 3-4 intermediate risk, and 5-8 high risk for moderate-to-severe OSA. It is widely used in preoperative screening and primary care settings to identify patients who need diagnostic sleep testing.',
    difficulty: 1,
    topic: 'Professional Practice & Patient Management',
    isFree: false,
    orderIndex: 200,
  },
]

async function main() {
  console.log('Seeding SDS Batch 2 flashcards (101-200)...')
  console.log(`Total cards: ${flashcards.length}`)

  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })

  console.log(`Successfully created ${result.count} flashcards`)

  // Summary stats
  const topicCounts: Record<string, number> = {}
  const difficultyCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0 }
  let freeCount = 0

  for (const card of flashcards) {
    topicCounts[card.topic] = (topicCounts[card.topic] || 0) + 1
    difficultyCounts[card.difficulty]++
    if (card.isFree) freeCount++
  }

  console.log('\n--- Summary ---')
  console.log('By topic:')
  for (const [topic, count] of Object.entries(topicCounts)) {
    console.log(`  ${topic}: ${count} cards`)
  }
  console.log('By difficulty:')
  console.log(`  Easy (1): ${difficultyCounts[1]}`)
  console.log(`  Medium (2): ${difficultyCounts[2]}`)
  console.log(`  Hard (3): ${difficultyCounts[3]}`)
  console.log(`Free cards: ${freeCount}`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
