import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding RPFT flashcards batch 3 (cards 201-300)...')

  await prisma.flashcard.createMany({
    data: [
      // --- Infant Pulmonary Function Testing (10 cards) ---
      {
        question: 'What is the raised volume rapid thoracoabdominal compression (RVRTC) technique used to measure in infants?',
        answer: 'RVRTC measures forced expiratory flows and volumes in sedated infants by inflating the lungs to a defined pressure (typically 30 cmH2O) using a face mask, then rapidly compressing the chest and abdomen with an inflatable jacket to generate a forced expiration. It provides FVC, FEV0.5, and forced expiratory flow values analogous to adult spirometry.',
        difficulty: 2,
        topic: 'Infant Pulmonary Function Testing',
        isFree: false,
        orderIndex: 201,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'Why is FEV0.5 used instead of FEV1 in infant pulmonary function testing?',
        answer: 'Infants have much smaller lungs and higher respiratory rates than adults, so their forced vital capacity can be fully expired in less than one second. FEV0.5 (forced expiratory volume in 0.5 seconds) captures a more physiologically meaningful proportion of the forced expiration and provides better discrimination between normal and abnormal airflow in this age group.',
        difficulty: 1,
        topic: 'Infant Pulmonary Function Testing',
        isFree: false,
        orderIndex: 202,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What sedation agent is most commonly used for infant PFT, and what monitoring is required?',
        answer: 'Chloral hydrate (50-100 mg/kg orally) is the most commonly used sedation agent for infant PFT. Required monitoring includes continuous pulse oximetry, heart rate monitoring, and direct observation of respiratory pattern and skin color. Resuscitation equipment, supplemental oxygen, and personnel trained in pediatric airway management must be immediately available throughout the procedure.',
        difficulty: 2,
        topic: 'Infant Pulmonary Function Testing',
        isFree: false,
        orderIndex: 203,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does infant whole-body plethysmography differ from adult plethysmography in technique?',
        answer: 'In infant plethysmography, the infant is sedated and placed supine in a smaller, heated and humidified plethysmograph. Airway occlusion is performed at end-inspiration using a shutter in the face mask during quiet tidal breathing, relying on the Hering-Breuer reflex to induce respiratory efforts against the closed shutter. The compliance of the infant cheeks is a significant source of artifact, so cheek support or correction algorithms may be needed.',
        difficulty: 3,
        topic: 'Infant Pulmonary Function Testing',
        isFree: false,
        orderIndex: 204,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the tidal breathing rapid thoracoabdominal compression (RTC) technique, and what parameter does it primarily yield?',
        answer: 'The tidal RTC technique applies a rapid squeeze via an inflatable jacket around the infant\'s chest and abdomen at end-inspiration during tidal breathing (without prior lung inflation). The primary parameter is V\'maxFRC — the maximal flow at functional residual capacity. This reflects airway function at resting lung volumes but has a limited range due to flow limitation at low lung volumes.',
        difficulty: 3,
        topic: 'Infant Pulmonary Function Testing',
        isFree: false,
        orderIndex: 205,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the typical inflation pressure used during the raised volume maneuver in infant PFT, and why is this specific pressure chosen?',
        answer: 'The standard inflation pressure is 30 cmH2O. This pressure was chosen because it approximates total lung capacity in infants, producing near-maximal lung inflation without causing overdistension or barotrauma. It provides a standardized volume history that allows reproducible forced expiratory maneuvers and comparison to reference data.',
        difficulty: 2,
        topic: 'Infant Pulmonary Function Testing',
        isFree: false,
        orderIndex: 206,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the key acceptability criteria for a raised volume rapid thoracoabdominal compression (RVRTC) maneuver in infants?',
        answer: 'Key acceptability criteria include: (1) inflation to the target pressure (typically 30 cmH2O) with a visible plateau, (2) rapid jacket inflation producing a sharp peak expiratory flow, (3) smooth descending flow-volume curve without glottic closure artifacts, (4) expiration to residual volume with a clear end-of-test plateau, and (5) absence of leak around the face mask. At least three acceptable and reproducible maneuvers should be obtained.',
        difficulty: 3,
        topic: 'Infant Pulmonary Function Testing',
        isFree: false,
        orderIndex: 207,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Advanced Oscillometry and Impulse Oscillometry (12 cards) ---
      {
        question: 'What is the fundamental principle behind oscillometry (forced oscillation technique)?',
        answer: 'Oscillometry superimposes small-amplitude pressure oscillations on the airway opening during normal tidal breathing and measures the resulting flow response. The ratio of pressure to flow at each oscillation frequency yields respiratory impedance (Zrs), which is partitioned into resistance (the real component, Rrs) and reactance (the imaginary component, Xrs). It requires only passive cooperation, making it useful for young children and patients who cannot perform spirometry.',
        difficulty: 1,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 208,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the difference between resistance (Rrs) and reactance (Xrs) in oscillometry?',
        answer: 'Resistance (Rrs) is the real (in-phase) component of impedance, reflecting energy dissipation primarily due to airway friction. Reactance (Xrs) is the imaginary (out-of-phase) component, reflecting energy storage in the respiratory system — determined by the balance between the inertia of the air column (inertance) and the elastic recoil of the lung and chest wall (compliance). At low frequencies, compliance dominates and Xrs is negative; at higher frequencies, inertance dominates and Xrs becomes positive.',
        difficulty: 2,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 209,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What does the resonant frequency (Fres) represent in oscillometry, and what does an elevated Fres suggest?',
        answer: 'The resonant frequency (Fres) is the frequency at which reactance equals zero — where the elastic and inertive components of the respiratory system are equal and opposite. In healthy adults, Fres is typically between 7-12 Hz. An elevated Fres indicates increased peripheral airway obstruction or decreased lung compliance, as the compliance-dominated negative reactance extends to higher frequencies before being balanced by inertance.',
        difficulty: 2,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 210,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What does the area of reactance (AX) represent, and why is it considered a sensitive marker of peripheral airway dysfunction?',
        answer: 'AX (also called the Goldman triangle) is the integrated area of low-frequency reactance values between 5 Hz and the resonant frequency. It combines information about both the magnitude of reactance abnormality and the frequency range over which it occurs. AX is considered a sensitive composite marker because it captures changes in peripheral lung mechanics (compliance and small airway heterogeneity) that may not be reflected in resistance alone, and it shows larger changes with bronchial challenge or bronchodilator response than individual frequency-specific values.',
        difficulty: 3,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 211,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does impulse oscillometry (IOS) differ from the classical forced oscillation technique (FOT)?',
        answer: 'Classical FOT typically applies sinusoidal oscillations at individual frequencies sequentially, whereas IOS applies a periodic rectangular pulse signal that contains all frequencies simultaneously (a broadband impulse). This allows IOS to measure impedance across the full frequency spectrum from a single impulse, making data acquisition faster. Both methods yield the same impedance parameters (Rrs, Xrs, Fres, AX), and the terms are often used interchangeably in clinical practice.',
        difficulty: 2,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 212,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'In oscillometry, what does frequency dependence of resistance (R5-R20) indicate?',
        answer: 'R5-R20 (the difference between resistance at 5 Hz and 20 Hz) reflects frequency dependence of resistance. R5 reflects total airway resistance (central plus peripheral), while R20 predominantly reflects central airway resistance since high-frequency oscillations do not penetrate to the lung periphery. An elevated R5-R20 therefore suggests increased peripheral (small) airway resistance, as the excess resistance at 5 Hz is attributed to the peripheral airways that are not "seen" at 20 Hz.',
        difficulty: 2,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 213,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the key quality control checks during an oscillometry measurement?',
        answer: 'Key quality checks include: (1) proper cheek support by the patient or technologist to minimize upper airway shunting, (2) stable tidal breathing without swallowing, coughing, or vocalization, (3) coherence function values above 0.6 at 5 Hz and above 0.9 at frequencies above 10 Hz, (4) excluding breaths with leak or glottic closure artifacts, (5) a minimum of three acceptable replicate measurements with a coefficient of variation below 10-15% for R5 and X5, and (6) proper nose clip placement.',
        difficulty: 2,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 214,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How can oscillometry be used to assess bronchodilator response, and what thresholds suggest a significant response?',
        answer: 'Oscillometry measures are obtained before and 15-20 minutes after bronchodilator administration. A significant bronchodilator response is suggested by a decrease in R5 of 40% or more from baseline (or exceeding the within-session repeatability threshold), a decrease in AX of 50-80%, or a decrease in Fres. Unlike spirometry, oscillometry can detect bronchodilator-responsive small airway dysfunction even when FEV1 changes are minimal, making it a complementary assessment tool.',
        difficulty: 3,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 215,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What artifact does upper airway shunting produce in oscillometry, and how is it minimized?',
        answer: 'Upper airway shunting occurs when oscillatory flow is absorbed by the compliant cheeks, floor of the mouth, and pharyngeal walls rather than reaching the intrathoracic airways. This causes an artifactual increase in measured resistance and more negative reactance, particularly at higher frequencies. It is minimized by firm cheek support (the patient or technologist pressing both cheeks with their palms while supporting the chin) and using a rigid mouthpiece with a lip seal.',
        difficulty: 1,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 216,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What does within-breath analysis of oscillometry data reveal, and what is its clinical significance?',
        answer: 'Within-breath analysis separates impedance measurements into inspiratory and expiratory phases. In obstructive lung disease, expiratory flow limitation causes expiratory reactance (Xrs) to become markedly more negative than inspiratory Xrs, reflecting dynamic airway compression. The difference between inspiratory and expiratory X5 (delta X5) is an indicator of expiratory flow limitation that can be detected during tidal breathing, providing information analogous to negative expiratory pressure testing without requiring forced maneuvers.',
        difficulty: 3,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 217,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the coherence function in oscillometry, and what does a low coherence value indicate?',
        answer: 'The coherence function measures the linear relationship between the applied pressure signal and the resulting flow response at each frequency, on a scale from 0 to 1. A coherence of 1 indicates a perfect linear relationship. Low coherence (below 0.6 at 5 Hz or below 0.9 above 10 Hz) indicates contamination by nonlinear events such as swallowing, irregular breathing, glottic closure, or air leak, and those data points should be excluded from analysis.',
        difficulty: 1,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 218,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does oscillometry differentiate between a predominantly central versus peripheral airway obstruction pattern?',
        answer: 'Central airway obstruction elevates both R5 and R20 proportionally, with minimal frequency dependence of resistance (R5-R20 is small), and reactance may remain relatively normal. Peripheral airway obstruction elevates R5 more than R20 (large R5-R20 difference), produces more negative X5, increases Fres, and enlarges AX. This differential pattern arises because low-frequency oscillations penetrate the full airway tree while high frequencies are reflected proximally.',
        difficulty: 3,
        topic: 'Advanced Oscillometry and IOS',
        isFree: false,
        orderIndex: 219,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Exhaled Biomarkers (8 cards) ---
      {
        question: 'What is exhaled breath condensate (EBC), and what biomarkers can be measured from it?',
        answer: 'Exhaled breath condensate is collected by cooling exhaled air to condense the water vapor and aerosolized respiratory tract lining fluid. Biomarkers measurable in EBC include pH (reflecting airway acidification in inflammation), hydrogen peroxide (oxidative stress marker), 8-isoprostane (lipid peroxidation), leukotrienes (B4, C4, D4, E4), prostaglandins, cytokines (IL-6, TNF-alpha), and nitrogen oxides. Collection requires 10-15 minutes of tidal breathing into a cooled condenser system.',
        difficulty: 2,
        topic: 'Exhaled Biomarkers',
        isFree: false,
        orderIndex: 220,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are volatile organic compounds (VOCs) in exhaled breath, and how are they analyzed?',
        answer: 'Exhaled VOCs are gaseous organic molecules produced by metabolic processes, inflammation, and oxidative stress in the lungs and systemically. They are analyzed using gas chromatography-mass spectrometry (GC-MS) for individual compound identification, or electronic nose (e-nose) devices that use sensor arrays to detect VOC patterns without identifying specific molecules. Specific VOCs under investigation include pentane and ethane (lipid peroxidation markers), acetone, isoprene, and disease-specific VOC profiles for asthma, COPD, and lung cancer screening.',
        difficulty: 3,
        topic: 'Exhaled Biomarkers',
        isFree: false,
        orderIndex: 221,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What factors can affect exhaled breath condensate pH measurements, and what is the normal range?',
        answer: 'Normal EBC pH after deaeration (removal of dissolved CO2 by bubbling with argon or nitrogen) is approximately 7.5-8.1. Factors affecting EBC pH include: (1) incomplete deaeration leaving residual CO2, (2) oral contamination from saliva or gastric reflux, (3) ambient air contamination, (4) collection device material and temperature, (5) storage conditions and time, (6) dietary intake, and (7) concurrent medications like inhaled corticosteroids. Acidic EBC pH (below 7.4) is associated with acute asthma, COPD exacerbations, and bronchiectasis.',
        difficulty: 3,
        topic: 'Exhaled Biomarkers',
        isFree: false,
        orderIndex: 222,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does an electronic nose (e-nose) work in breath analysis, and what is its potential clinical application?',
        answer: 'An e-nose contains an array of cross-reactive chemical sensors (metal oxide, polymer, or quartz crystal microbalance) that each respond differently to the complex mixture of exhaled VOCs. The collective sensor response creates a "breathprint" pattern that is analyzed using pattern recognition algorithms (principal component analysis, neural networks). Clinical applications include phenotyping asthma and COPD, distinguishing eosinophilic from non-eosinophilic airway inflammation, screening for lung cancer, and monitoring treatment response without invasive sampling.',
        difficulty: 2,
        topic: 'Exhaled Biomarkers',
        isFree: false,
        orderIndex: 223,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the clinical significance of elevated 8-isoprostane in exhaled breath condensate?',
        answer: '8-Isoprostane is a prostaglandin F2-alpha isomer formed by free radical-catalyzed peroxidation of arachidonic acid, independent of cyclooxygenase enzymes. Elevated levels in EBC indicate increased oxidative stress in the airways. Concentrations are elevated in asthma (proportional to severity), COPD, cystic fibrosis, and interstitial lung disease. It is considered a more reliable oxidative stress marker than hydrogen peroxide because it is chemically stable and not affected by dietary antioxidant intake.',
        difficulty: 3,
        topic: 'Exhaled Biomarkers',
        isFree: false,
        orderIndex: 224,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the standardization challenges for exhaled breath condensate collection?',
        answer: 'Key standardization challenges include: (1) variable dilution factor — the ratio of respiratory lining fluid to condensed water vapor is unknown and variable, making absolute concentration comparisons difficult; (2) no validated normalization method — proposed approaches include urea, conductivity, and total protein but none is universally accepted; (3) device-dependent collection efficiency; (4) salivary contamination detection (amylase assay); (5) sample storage instability for some analytes; and (6) lack of consensus on deaeration protocols for pH measurement.',
        difficulty: 3,
        topic: 'Exhaled Biomarkers',
        isFree: false,
        orderIndex: 225,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the extended NO analysis model, and what parameters does it provide beyond standard FeNO?',
        answer: 'The extended NO analysis (also called the two-compartment model) measures FeNO at multiple expiratory flow rates to partition NO output into airway (bronchial) and alveolar sources. Parameters include: JawNO (maximum airway wall NO flux, reflecting bronchial inflammation), CANO (alveolar NO concentration, reflecting distal lung/alveolar inflammation), and DawNO (airway wall NO diffusing capacity). Elevated JawNO suggests eosinophilic large airway inflammation, while elevated CANO may indicate small airway or alveolar disease such as alveolitis.',
        difficulty: 3,
        topic: 'Exhaled Biomarkers',
        isFree: false,
        orderIndex: 226,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What breathing maneuver is required for exhaled breath condensate collection, and how is salivary contamination prevented?',
        answer: 'EBC collection requires 10-15 minutes of relaxed tidal breathing through a mouthpiece connected to a cooled condenser (typically at -10 to -20 degrees Celsius). A saliva trap or one-way valve in the mouthpiece prevents salivary contamination. Patients should rinse their mouth with water before collection. The amylase concentration in the condensate can be measured as a quality check — levels above a threshold indicate salivary contamination. A nose clip is worn to ensure exclusive oral breathing.',
        difficulty: 1,
        topic: 'Exhaled Biomarkers',
        isFree: false,
        orderIndex: 227,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Lung Clearance Index and Multiple Breath Washout (10 cards) ---
      {
        question: 'What does the lung clearance index (LCI) measure, and why is it clinically useful?',
        answer: 'LCI measures ventilation inhomogeneity — how unevenly air distributes throughout the lungs. It is calculated as the cumulative expired volume needed to clear an inert tracer gas to 1/40th of its starting concentration, divided by the functional residual capacity. A higher LCI indicates more uneven ventilation. LCI is clinically useful because it detects early small airway disease (particularly in cystic fibrosis) with greater sensitivity than spirometry, even when FEV1 is still normal.',
        difficulty: 1,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 228,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What tracer gases are used for multiple breath washout testing, and what are the advantages of each?',
        answer: 'The two main tracer gases are: (1) Sulfur hexafluoride (SF6) — an exogenous gas washed in and then washed out; advantage is a true wash-in/washout that avoids assumptions about resident gas, but requires specialized analyzers and has environmental concerns as a greenhouse gas. (2) Nitrogen (N2) — the resident gas washed out using 100% oxygen; advantage is simpler setup without needing exogenous gas supply, but requires correction for tissue nitrogen excretion and is affected by changes in oxygen-induced atelectasis. LCI values are not interchangeable between gases.',
        difficulty: 2,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 229,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is the lung clearance index (LCI) calculated from a multiple breath washout test?',
        answer: 'LCI = Cumulative expired volume (CEV) / Functional residual capacity (FRC). CEV is the total volume of gas expired from the start of washout until the tracer gas concentration falls below 1/40th (2.5%) of its starting concentration for three consecutive breaths. FRC is calculated from the total volume of tracer gas washed out divided by the difference between starting and ending tracer gas concentrations. Normal LCI in adults is approximately 7 or less (varies slightly with gas and equipment).',
        difficulty: 2,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 230,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are Scond and Sacin in multiple breath washout analysis, and what do they represent?',
        answer: 'Scond and Sacin are phase III slope indices derived from MBW analysis. Scond (conductive ventilation inhomogeneity) is the rate of increase in the normalized phase III slope between lung turnovers 1.5 and 6.0, reflecting ventilation inhomogeneity generated in the conducting airways due to differences in specific ventilation between lung units. Sacin is the normalized phase III slope of the first breath corrected for the Scond contribution, reflecting ventilation inhomogeneity in the acinar (gas-exchange) zone related to diffusion-convection interaction.',
        difficulty: 3,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 231,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the upper limit of normal for LCI in adults, and what conditions cause it to be elevated?',
        answer: 'The upper limit of normal for LCI in adults is approximately 7.0-8.0, depending on the tracer gas and equipment used (N2 washout tends to give slightly higher values than SF6). Elevated LCI is seen in cystic fibrosis (even with preserved FEV1), asthma, COPD, bronchiectasis, bronchiolitis obliterans, and post-lung transplant (indicating early onset of chronic rejection/BOS). LCI is particularly sensitive to early cystic fibrosis lung disease in children and young adults.',
        difficulty: 1,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 232,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the key quality control requirements for a valid multiple breath washout (MBW) test?',
        answer: 'Key quality requirements include: (1) stable end-expiratory level (FRC) during the pre-washout tidal breathing phase, (2) relaxed tidal breathing without sighs, swallows, or irregular breaths during washout, (3) no leaks at the mouthpiece or around the nose clip, (4) at least three valid washout trials with FRC values within 10% of each other, (5) adequate washout endpoint — tracer gas concentration below 1/40th of starting concentration for three consecutive breaths, and (6) tidal volume within the normal range without breath-holding.',
        difficulty: 2,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 233,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'Why does the nitrogen MBW test require correction for tissue nitrogen excretion?',
        answer: 'When breathing 100% oxygen during N2 washout, nitrogen dissolved in body tissues (blood, fat, muscle) diffuses into the alveoli and is expired, adding to the measured expired nitrogen. This tissue nitrogen contribution is not related to ventilation inhomogeneity and would falsely elevate both the calculated FRC and LCI if uncorrected. Correction algorithms estimate and subtract the tissue nitrogen contribution based on models of tissue nitrogen stores and blood-gas equilibration kinetics.',
        difficulty: 3,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 234,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What advantage does LCI have over FEV1 in monitoring cystic fibrosis lung disease?',
        answer: 'LCI detects ventilation inhomogeneity caused by mucus plugging and early structural airway changes before these produce measurable airflow obstruction on spirometry. Studies have shown LCI is abnormal in up to 70-80% of CF patients with normal FEV1, making it more sensitive for tracking early disease progression and treatment response. LCI also correlates better with structural lung changes seen on chest CT than FEV1 in early CF disease.',
        difficulty: 1,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 235,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How long does a typical MBW test take, and what factors affect test duration?',
        answer: 'A single MBW trial typically takes 3-5 minutes in a healthy subject but can take 15-20 minutes or more in patients with severe ventilation inhomogeneity (e.g., advanced CF or severe COPD). Since three valid trials are needed, total test time can exceed 60 minutes in severely affected patients. Factors affecting duration include severity of ventilation inhomogeneity, FRC size, breathing pattern (tidal volume and frequency), and the washout endpoint definition (1/40th concentration threshold).',
        difficulty: 1,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 236,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is moment ratio analysis in the context of MBW testing?',
        answer: 'Moment ratio analysis examines the shape of the washout curve by calculating the ratio of the first and second moments (weighted averages) of the tracer gas concentration over cumulative expired volume to the zeroth moment. The moment ratios M1/M0 and M2/M0 quantify different aspects of ventilation inhomogeneity — M1/M0 is analogous to LCI, while M2/M0 emphasizes the tail of the washout curve and is more sensitive to slowly ventilating units. These indices provide additional information about the distribution pattern and severity of ventilation inhomogeneity beyond what LCI alone provides.',
        difficulty: 3,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 237,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Advanced Exercise Testing Scenarios (12 cards) ---
      {
        question: 'What is the classic pattern of exercise limitation due to pulmonary vascular disease (pulmonary hypertension) on cardiopulmonary exercise testing?',
        answer: 'The classic CPET pattern includes: reduced peak VO2 and early anaerobic threshold (AT), elevated VE/VCO2 slope (often >40) reflecting increased dead space ventilation, low end-tidal CO2 (PETCO2) that falls further during exercise, reduced O2 pulse that plateaus early (reflecting limited stroke volume augmentation), preserved breathing reserve, and exercise-induced hypoxemia. The combination of high VE/VCO2 with adequate breathing reserve and low PETCO2 helps distinguish pulmonary vascular limitation from parenchymal lung disease.',
        difficulty: 2,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 238,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does the CPET pattern of deconditioning differ from cardiac limitation?',
        answer: 'In deconditioning, peak VO2 is reduced and AT occurs at a low percentage of predicted peak VO2, but the VO2-work rate relationship is normal (no plateau), O2 pulse rises normally during exercise (just reaches a lower absolute peak), heart rate reserve is low (high peak heart rate relative to work), VE/VCO2 slope is normal, and breathing reserve is preserved. In cardiac disease, O2 pulse typically plateaus early or decreases, the VO2-work rate relationship may flatten, and there may be an oscillatory breathing pattern. Both show low AT, but deconditioning shows a proportionally normal cardiovascular response to the reduced fitness level.',
        difficulty: 2,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 239,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is exercise oscillatory ventilation (EOV), and what is its prognostic significance?',
        answer: 'EOV is a periodic oscillation in minute ventilation during exercise with a cycle length of 40-100 seconds, amplitude exceeding 15% of the mean ventilation, and present for at least 60% of exercise duration. It is seen in approximately 20-30% of heart failure patients during CPET and reflects circulatory delay, elevated left-sided filling pressures, and heightened chemoreceptor sensitivity. EOV is a strong independent predictor of adverse outcomes in heart failure, associated with increased mortality risk even beyond peak VO2 and VE/VCO2 slope.',
        difficulty: 3,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 240,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What CPET findings characterize exercise limitation due to obesity?',
        answer: 'Obesity produces: increased VO2 at any given external work rate (due to the metabolic cost of moving excess body mass), normal or near-normal peak VO2 when expressed per kg of lean body mass but reduced when expressed per total body weight, elevated O2 cost of unloaded cycling or walking, increased ventilatory demand at submaximal exercise, reduced breathing reserve due to decreased expiratory reserve volume and FRC, and normal VE/VCO2 slope. AT expressed as percentage of predicted VO2max may be normal. Differentiating obesity alone from coexistent cardiac or pulmonary disease requires careful analysis of the VO2-work rate slope and gas exchange efficiency.',
        difficulty: 2,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 241,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How do you distinguish pulmonary mechanical limitation from pulmonary vascular limitation on CPET?',
        answer: 'Pulmonary mechanical limitation shows: reduced breathing reserve (high VE/MVV ratio, often >85%), development of dynamic hyperinflation (rising EELV with exercise), expiratory flow limitation on exercise flow-volume loops, modest elevation of VE/VCO2 slope, and PETCO2 that may rise or plateau. Pulmonary vascular limitation shows: preserved breathing reserve, markedly elevated VE/VCO2 slope (>40-45), PETCO2 that falls progressively with exercise, early O2 pulse plateau, and exercise-induced desaturation. Both may show reduced peak VO2, but the ventilatory pattern and gas exchange efficiency distinguish them.',
        difficulty: 3,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 242,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the O2 pulse, how is it calculated, and what does a plateau in O2 pulse during exercise suggest?',
        answer: 'O2 pulse is calculated as VO2 divided by heart rate (mL O2/beat) and serves as a noninvasive surrogate for stroke volume multiplied by arteriovenous oxygen difference (the Fick equation rearranged). A normal O2 pulse increases progressively during incremental exercise. An early plateau or decline in O2 pulse suggests failure to augment stroke volume (cardiac limitation from ischemia, cardiomyopathy, or valve disease) or a falling arteriovenous O2 difference (severe deconditioning or arterial desaturation). The pattern helps differentiate cardiac from non-cardiac exercise limitation.',
        difficulty: 1,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 243,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What CPET pattern suggests exercise-induced laryngeal obstruction (EILO), formerly called vocal cord dysfunction?',
        answer: 'EILO produces: inspiratory flow limitation visible on exercise flow-volume loops (flattened inspiratory limb), audible inspiratory stridor typically at high exercise intensities, abrupt onset and rapid resolution of symptoms with rest, normal expiratory flows, preserved gas exchange (normal SpO2, PETCO2, and VE/VCO2 slope), and often a supramaximal ventilatory response relative to metabolic demand. Peak VO2 may be normal or reduced depending on whether exercise was terminated due to symptoms. Definitive diagnosis requires continuous laryngoscopy during exercise (CLE) showing paradoxical vocal fold or supraglottic adduction.',
        difficulty: 2,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 244,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is dynamic hyperinflation assessed during cardiopulmonary exercise testing?',
        answer: 'Dynamic hyperinflation is assessed by performing serial inspiratory capacity (IC) maneuvers during exercise. A decrease in IC from rest to peak exercise indicates an increase in end-expiratory lung volume (EELV), confirming dynamic hyperinflation. The magnitude of IC reduction correlates with dyspnea intensity and exercise limitation. Exercise tidal flow-volume loops plotted within the maximal resting flow-volume envelope can also demonstrate expiratory flow limitation and progressive reduction in inspiratory reserve volume. A decrease in IC of more than 150 mL or 10% from baseline is considered significant.',
        difficulty: 2,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 245,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the VE/VCO2 slope, what is its normal range, and what conditions cause it to be elevated?',
        answer: 'The VE/VCO2 slope is the linear regression slope of minute ventilation plotted against CO2 output during incremental exercise, reflecting ventilatory efficiency. The normal range is approximately 25-30. Values above 34-36 are considered elevated and indicate increased dead space ventilation or heightened ventilatory drive. Conditions causing elevation include: heart failure (strong prognostic marker), pulmonary hypertension, pulmonary embolism, interstitial lung disease with vascular involvement, and hyperventilation syndrome. Values above 45 in heart failure indicate very high mortality risk.',
        difficulty: 1,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 246,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What CPET findings suggest a mixed cardiac and pulmonary limitation pattern?',
        answer: 'Mixed limitation shows overlapping features: reduced peak VO2 with both reduced breathing reserve (high VE/MVV ratio) AND abnormal cardiovascular response (early O2 pulse plateau, abnormal heart rate response). VE/VCO2 slope may be elevated from both dead space ventilation and low cardiac output. IC may decrease (dynamic hyperinflation) while O2 pulse plateaus (stroke volume limitation). Exercise desaturation may occur from both V/Q mismatch and low mixed venous PO2. Identifying the predominant limiting factor requires examining which abnormality appears first during progressive exercise and which is disproportionately more severe.',
        difficulty: 3,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 247,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the CPET criteria for identifying the anaerobic threshold using the V-slope method?',
        answer: 'The V-slope method plots VCO2 against VO2 during incremental exercise. Below AT, VCO2 increases linearly with VO2 with a slope less than 1. At AT, the onset of lactic acidosis stimulates additional CO2 production from bicarbonate buffering, causing VCO2 to increase more steeply relative to VO2 (slope exceeds 1). The AT is identified at the inflection point where the VCO2-VO2 slope transitions from below to above unity. This is confirmed by a simultaneous rise in VE/VO2 without a rise in VE/VCO2 (ventilatory equivalents method).',
        difficulty: 1,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 248,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does the CPET pattern of mitochondrial myopathy differ from deconditioning?',
        answer: 'Mitochondrial myopathy produces: markedly reduced peak VO2, very early AT (often below 40% predicted VO2max), exaggerated hyperventilatory response with elevated VE/VO2 and VE/VCO2 at low work rates, systemic lactic acidosis at minimal exercise, hyperkinetic cardiovascular response (excessive heart rate rise for the work rate), and low O2 extraction reflected in reduced arteriovenous O2 difference. Unlike deconditioning, the VO2-work rate relationship may plateau at very low workloads, heart rate rises disproportionately faster, and lactate levels are severely elevated at minimal exertion. The degree of physiological impairment is far out of proportion to the reported activity level.',
        difficulty: 3,
        topic: 'Advanced Exercise Testing Scenarios',
        isFree: false,
        orderIndex: 249,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Thoracic Gas Volume and Specific Airway Conductance (6 cards) ---
      {
        question: 'What is specific airway conductance (sGaw), and why is it preferred over raw airway resistance in some clinical situations?',
        answer: 'Specific airway conductance (sGaw) is airway conductance (Gaw = 1/Raw) divided by the thoracic gas volume (TGV) at which it is measured: sGaw = Gaw/TGV. It is preferred because airway resistance and conductance are volume-dependent — airways dilate at higher lung volumes, decreasing resistance. By normalizing to lung volume, sGaw accounts for this volume dependency, allowing valid comparisons between patients with different lung volumes and within the same patient at different time points (e.g., before and after bronchodilator). Normal sGaw is approximately 0.12-0.25 per second per cmH2O.',
        difficulty: 2,
        topic: 'Thoracic Gas Volume and sGaw',
        isFree: false,
        orderIndex: 250,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does thermal artifact affect thoracic gas volume measurements in body plethysmography?',
        answer: 'During panting against a closed shutter, gas in the airways is heated and humidified to body temperature, while box pressure changes reflect gas compression at ambient conditions (ATPS). If uncorrected, this thermal difference causes TGV to be overestimated because the mouth pressure-box pressure relationship includes temperature-related volume changes that are not due to gas compression alone. Modern plethysmographs use electronically heated pneumotachographs and correction algorithms to minimize this artifact. Panting at frequencies of 1-2 Hz (rather than higher frequencies) also reduces thermal effects.',
        difficulty: 3,
        topic: 'Thoracic Gas Volume and sGaw',
        isFree: false,
        orderIndex: 251,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'Why does body plethysmography overestimate thoracic gas volume in patients with severe airflow obstruction?',
        answer: 'In severe obstruction, trapped gas behind closed or nearly closed airways cannot equilibrate pressure with the mouth during the panting maneuver. The plethysmograph detects the full volume of gas being compressed within the thorax (including trapped gas), but mouth pressure underestimates the alveolar pressure of these non-communicating regions. Additionally, panting at higher frequencies worsens this effect as there is less time for pressure equilibration. This leads to an overestimation of TGV compared to gas dilution methods. Slow panting (less than 1 Hz) can reduce but not eliminate this overestimation.',
        difficulty: 2,
        topic: 'Thoracic Gas Volume and sGaw',
        isFree: false,
        orderIndex: 252,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the difference between TGV measured at FRC versus TGV measured at other lung volumes, and how does this affect clinical interpretation?',
        answer: 'TGV is ideally measured at FRC by occluding the shutter at end-tidal expiration. If the shutter closes at a volume above or below FRC, the measured TGV will differ from FRC accordingly. Since sGaw and sRaw are volume-dependent, measuring TGV at an incorrect lung volume alters these derived values. Technologists must ensure the shutter closes consistently at end-expiration during quiet breathing. Some systems allow TGV to be adjusted to FRC using the simultaneously measured ERV, but accurate practice requires proper shutter timing during the patient\'s natural breathing pattern.',
        difficulty: 2,
        topic: 'Thoracic Gas Volume and sGaw',
        isFree: false,
        orderIndex: 253,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is specific airway resistance (sRaw), and how does it relate to sGaw?',
        answer: 'Specific airway resistance (sRaw) is the product of airway resistance and thoracic gas volume: sRaw = Raw x TGV. It is the reciprocal of specific airway conductance: sRaw = 1/sGaw. sRaw can be measured directly from the plethysmograph as the slope of the box pressure-flow loop without requiring a shutter maneuver, making it technically simpler. An increase in sRaw (or decrease in sGaw) of more than 40-50% after bronchial challenge is generally considered a positive response. Normal sRaw is approximately 4-8 cmH2O per second.',
        difficulty: 1,
        topic: 'Thoracic Gas Volume and sGaw',
        isFree: false,
        orderIndex: 254,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How is panting frequency standardized during TGV measurement, and what artifacts arise from incorrect panting?',
        answer: 'Recommended panting frequency is 1-2 Hz (about 60-120 breaths per minute) with small tidal volumes, against the closed shutter while supporting the cheeks. Panting too fast (>2 Hz) causes thermal artifact overestimation and may not allow pressure equilibration across obstructed airways. Panting too slowly allows excessive gas exchange and temperature equilibration that alter mouth pressure readings. Irregular panting produces open or non-linear mouth pressure-box pressure loops that prevent accurate slope measurement. The patient should be coached to maintain a steady rhythm while keeping the glottis open.',
        difficulty: 1,
        topic: 'Thoracic Gas Volume and sGaw',
        isFree: false,
        orderIndex: 255,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- PFT in Specific Diseases (14 cards) ---
      {
        question: 'What is the typical PFT pattern in cystic fibrosis, and how does it evolve with disease progression?',
        answer: 'Early CF shows normal spirometry but elevated LCI reflecting small airway ventilation inhomogeneity and air trapping (elevated RV/TLC). As disease progresses, an obstructive pattern develops with reduced FEV1, reduced FEV1/FVC ratio, concavity on the expiratory flow-volume curve, and progressive hyperinflation (increased RV, normal to increased TLC). In advanced disease, FVC also declines. DLCO is typically preserved until late stages. Bronchodilator response is variable. Progressive decline in FEV1 (rate of decline) is the primary metric for monitoring disease progression and is a key determinant for lung transplant listing.',
        difficulty: 2,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 256,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does the PFT pattern in idiopathic pulmonary fibrosis (IPF) differ from that in combined pulmonary fibrosis and emphysema (CPFE)?',
        answer: 'IPF shows a classic restrictive pattern: reduced TLC, reduced FVC, normal or elevated FEV1/FVC ratio, and markedly reduced DLCO. In CPFE, the opposing effects on lung volumes (emphysema increases volumes, fibrosis decreases them) produce deceptively normal or near-normal spirometry and lung volumes despite severe disease. However, DLCO is disproportionately reduced because both processes independently impair gas exchange. CPFE patients often have severe exercise-induced hypoxemia and pulmonary hypertension despite "normal" lung volumes, making DLCO and exercise testing essential for accurate assessment.',
        difficulty: 3,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 257,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT findings suggest neuromuscular respiratory weakness, and which tests are most sensitive?',
        answer: 'Neuromuscular disease produces a restrictive pattern (reduced VC and TLC) with preserved DLCO when corrected for alveolar volume (KCO normal or elevated). Key findings include: reduced maximal inspiratory pressure (MIP) and maximal expiratory pressure (MEP), reduced sniff nasal inspiratory pressure (SNIP), postural drop in VC (>20% decrease from sitting to supine suggests diaphragmatic weakness), preserved FEV1/FVC ratio, elevated RV (expiratory muscle weakness), and reduced peak cough flow. MIP, SNIP, and supine VC are among the most sensitive early indicators, detecting respiratory muscle weakness before resting spirometry becomes abnormal.',
        difficulty: 2,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 258,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the significance of a supine drop in vital capacity, and what threshold suggests clinically important diaphragmatic weakness?',
        answer: 'A decrease in vital capacity from the seated to supine position greater than 20% strongly suggests significant diaphragmatic weakness. In the supine position, the weight of the abdominal contents pushes against the weakened diaphragm, reducing lung volume. Normal individuals show less than 10% decrease in VC when supine. A drop greater than 25% predicts nocturnal hypoventilation and the need for noninvasive ventilation. Bilateral diaphragm paralysis may produce drops of 40-50% or more. This simple test is more sensitive than upright spirometry alone for detecting diaphragmatic dysfunction.',
        difficulty: 1,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 259,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does obesity affect pulmonary function test results, and what distinguishes obesity-related changes from true restrictive lung disease?',
        answer: 'Obesity reduces ERV and FRC (due to mass loading on the chest wall) with relatively preserved TLC in mild-moderate obesity, though TLC may decrease in severe obesity (BMI >40). FEV1 and FVC may be mildly reduced with a preserved or elevated FEV1/FVC ratio. DLCO is typically normal or slightly increased (increased pulmonary blood volume). This differs from true restrictive disease, which shows proportionally reduced TLC, often reduced DLCO, and clinical/imaging evidence of parenchymal disease. A hallmark of obesity is dramatically reduced ERV with a disproportionately low FRC relative to TLC.',
        difficulty: 2,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 260,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT pattern is seen in pulmonary arterial hypertension (PAH) without coexisting parenchymal lung disease?',
        answer: 'Isolated PAH typically shows: normal spirometry and normal lung volumes, mildly to moderately reduced DLCO (reflecting reduced pulmonary capillary blood volume and impaired gas exchange), and a reduced KCO (DLCO/VA). The DLCO reduction may be the only PFT abnormality and its degree correlates with disease severity and prognosis. Exercise testing reveals markedly elevated VE/VCO2 slope, low PETCO2, exercise-induced hypoxemia, and early O2 pulse plateau. A severely reduced DLCO with otherwise normal PFTs should prompt evaluation for pulmonary vascular disease.',
        difficulty: 2,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 261,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the PFT criteria used for lung transplant listing in COPD according to major guidelines?',
        answer: 'Key PFT criteria for lung transplant referral in COPD include: FEV1 below 25% predicted (or rapidly declining FEV1 despite maximal medical therapy), DLCO below 20% predicted, and elevated BODE index (Body mass index, Obstruction, Dyspnea, Exercise capacity score of 7-10). Additional factors include hospitalization for acute exacerbation with hypercapnia (PaCO2 >50 mmHg), pulmonary hypertension despite oxygen therapy, and declining 6-minute walk distance below 150 meters. The combination of physiological impairment with clinical deterioration determines optimal listing timing.',
        difficulty: 2,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 262,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How do PFTs change following hematopoietic stem cell transplantation, and what patterns suggest bronchiolitis obliterans syndrome (BOS)?',
        answer: 'BOS after stem cell transplant is diagnosed by a new obstructive deficit: FEV1 decline to less than 75% of pre-transplant baseline with an FEV1/FVC ratio below 0.7 or the lower limit of normal, plus air trapping (RV >120% predicted or RV/TLC elevated) on PFTs. DLCO may decline. Early detection requires serial PFT monitoring starting before transplant and continuing at regular intervals. FEF25-75 decline may precede FEV1 changes. LCI and oscillometry are being investigated as more sensitive early markers. BOS is differentiated from restrictive patterns (suggesting organizing pneumonia or pulmonary fibrosis) by the obstructive physiology and air trapping.',
        difficulty: 3,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 263,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT changes are expected in sarcoidosis across its different stages?',
        answer: 'Stage I (bilateral hilar lymphadenopathy only): PFTs often normal, though subtle DLCO reduction or mild obstruction may occur. Stage II (lymphadenopathy plus parenchymal infiltrates): mixed or obstructive pattern with DLCO reduction. Stage III (parenchymal infiltrates without lymphadenopathy): restrictive or mixed pattern, reduced DLCO. Stage IV (pulmonary fibrosis): restrictive pattern with markedly reduced DLCO. Airflow obstruction from endobronchial granulomas or bronchial distortion occurs in 30-50% of cases. DLCO is the most sensitive PFT parameter across all stages and correlates with disease activity and exercise capacity.',
        difficulty: 2,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 264,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the role of PFTs in evaluating patients with systemic sclerosis (scleroderma)?',
        answer: 'PFT monitoring is essential in systemic sclerosis because interstitial lung disease (ILD) and pulmonary arterial hypertension (PAH) are leading causes of death. ILD produces restriction with reduced FVC and DLCO. Isolated PAH causes reduced DLCO with preserved FVC — an FVC/DLCO ratio greater than 1.6-1.8 suggests coexistent pulmonary vascular disease. Serial FVC and DLCO measurements every 3-6 months detect disease progression. An FVC decline greater than 10% or DLCO decline greater than 15% from baseline is clinically significant and may prompt treatment escalation. Baseline and serial PFTs guide decisions about immunosuppressive therapy initiation.',
        difficulty: 3,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 265,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT findings characterize lymphangioleiomyomatosis (LAM)?',
        answer: 'LAM produces an obstructive or mixed obstructive-restrictive pattern with progressive airflow limitation (reduced FEV1, reduced FEV1/FVC ratio), air trapping (elevated RV/TLC ratio), and reduced DLCO due to destruction of the pulmonary parenchyma and vasculature by cystic changes. Unlike typical COPD, LAM predominantly affects young women. DLCO is often reduced disproportionately to the degree of airflow obstruction. Serial PFTs showing FEV1 decline rate help monitor disease progression and assess treatment response to mTOR inhibitors (sirolimus). Positive bronchodilator response occurs in a subset of patients.',
        difficulty: 3,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 266,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT findings are expected in myasthenia gravis, and how do they help guide clinical management?',
        answer: 'Myasthenia gravis produces a restrictive pattern with reduced VC and preserved DLCO/KCO, similar to other neuromuscular diseases. MIP and MEP are reduced, often disproportionately to the VC decline. A key feature is variability — VC can fluctuate significantly with disease activity, medication timing, and fatigue. Serial VC measurements (including supine VC) help monitor respiratory muscle strength. A VC below 20 mL/kg, MIP weaker than -30 cmH2O, or MEP less than 40 cmH2O suggests impending respiratory failure (the "20/30/40 rule") and need for ICU admission during myasthenic crisis. Peak cough flow assessment guides cough augmentation needs.',
        difficulty: 1,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 267,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does the PFT pattern in hypersensitivity pneumonitis (HP) differ between acute/subacute and chronic forms?',
        answer: 'Acute and subacute HP typically show a restrictive pattern with reduced TLC, reduced FVC, preserved or elevated FEV1/FVC ratio, and reduced DLCO, reflecting diffuse alveolar and interstitial inflammation. Chronic HP (especially fibrotic) may show either restriction, obstruction, or a mixed pattern depending on the predominant pathology — fibrosis causes restriction while bronchiolar involvement and air trapping cause obstruction. DLCO is reduced in both forms. The presence of obstruction and air trapping in chronic HP helps differentiate it from IPF. Treatment response monitoring relies on serial FVC and DLCO changes after allergen avoidance.',
        difficulty: 2,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 268,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT parameters are most useful for monitoring disease progression in amyotrophic lateral sclerosis (ALS)?',
        answer: 'The most useful parameters are: seated and supine FVC (decline rate predicts survival), MIP (often first parameter to decline), SNIP (sniff nasal inspiratory pressure — correlates with diaphragm strength and predicts ventilatory failure), MEP (guides cough effectiveness assessment), and peak cough flow. FVC below 50% predicted is a threshold for noninvasive ventilation initiation. SNIP below 40 cmH2O predicts nocturnal hypoventilation. Peak cough flow below 270 L/min indicates the need for cough augmentation. Serial measurements every 2-3 months track progression rate and guide respiratory support decisions.',
        difficulty: 1,
        topic: 'PFT in Specific Diseases',
        isFree: false,
        orderIndex: 269,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Advanced Quality Management (10 cards) ---
      {
        question: 'What is proficiency testing (PT) in the context of a PFT laboratory, and why is it required?',
        answer: 'Proficiency testing is an external quality assessment program where a PFT laboratory tests standardized biological or mechanical samples sent by an accrediting organization and compares results against reference values or peer group means. It assesses the laboratory\'s ability to produce accurate results under routine conditions. PT is required by accreditation bodies (such as those following ISO 15189 standards) to identify systematic errors, verify measurement accuracy, demonstrate competency, and maintain laboratory accreditation. Failed PT results require root cause analysis and corrective action documentation.',
        difficulty: 1,
        topic: 'Advanced Quality Management',
        isFree: false,
        orderIndex: 270,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is method validation in pulmonary function testing, and what components does it include?',
        answer: 'Method validation is the process of confirming that a PFT measurement procedure is fit for its intended clinical use. Components include: accuracy assessment (comparison with reference standards or known values), precision evaluation (within-day and between-day repeatability), linearity verification across the clinically relevant measurement range, limit of detection and limit of quantification where applicable, comparison with an established reference method (e.g., new spirometer versus validated reference spirometer), and robustness testing (performance under varying but realistic conditions). Validation must be repeated when equipment is replaced, software is upgraded, or measurement procedures change.',
        difficulty: 2,
        topic: 'Advanced Quality Management',
        isFree: false,
        orderIndex: 271,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is measurement uncertainty in PFT, and how does it differ from measurement error?',
        answer: 'Measurement uncertainty is a quantitative estimate of the range of values within which the true value is expected to lie, expressed with a stated confidence level (e.g., 95% confidence interval). It accounts for all identified sources of variability including equipment precision, calibration uncertainty, biological variability, and environmental factors. Measurement error is the difference between a measured value and the true value for a single measurement. Unlike error, uncertainty is not a single number but a range, and it applies prospectively to future measurements. Understanding uncertainty helps clinicians determine whether a change between two tests represents true physiological change or falls within measurement variability.',
        difficulty: 3,
        topic: 'Advanced Quality Management',
        isFree: false,
        orderIndex: 272,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the purpose of biological quality control (bio-QC) in a PFT laboratory?',
        answer: 'Biological QC uses healthy, trained laboratory staff who perform PFT measurements at regular intervals (typically weekly or daily) to monitor the overall measurement system including equipment function, software algorithms, and testing technique. Unlike mechanical calibration checks that test only the transducer, bio-QC tests the entire measurement chain. Results are tracked on control charts (Levey-Jennings plots) with established mean and control limits (typically 2 SD). Trends, shifts, or out-of-range values trigger investigation. Bio-QC detects subtle systematic drift, software errors, or procedural changes that mechanical checks alone may miss.',
        difficulty: 1,
        topic: 'Advanced Quality Management',
        isFree: false,
        orderIndex: 273,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the Westgard rules, and how are they applied to PFT quality control?',
        answer: 'Westgard rules are a set of statistical decision criteria applied to quality control data on Levey-Jennings charts. Common rules include: 1-2s (warning: one QC value exceeds 2 SD), 1-3s (reject: one value exceeds 3 SD), 2-2s (reject: two consecutive values exceed 2 SD in the same direction), R-4s (reject: two consecutive values differ by more than 4 SD), 4-1s (reject: four consecutive values exceed 1 SD in the same direction — detects systematic shift), and 10x (reject: ten consecutive values on one side of the mean — detects systematic bias). In PFT, these rules are applied to bio-QC data and calibration verification results to detect random error, systematic bias, and trends.',
        difficulty: 2,
        topic: 'Advanced Quality Management',
        isFree: false,
        orderIndex: 274,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the difference between calibration and calibration verification in PFT equipment management?',
        answer: 'Calibration is the process of adjusting the measurement system to match known reference standards — for example, adjusting a spirometer\'s flow-volume algorithm using a 3-liter calibration syringe to ensure accurate volume and flow measurements. Calibration verification is the process of testing the equipment with a known standard to confirm it continues to measure accurately WITHOUT making adjustments — simply verifying that the existing calibration remains valid. Calibration verification is typically performed daily (pre-session) while full recalibration is performed when verification fails, after repairs, or at manufacturer-recommended intervals.',
        difficulty: 1,
        topic: 'Advanced Quality Management',
        isFree: false,
        orderIndex: 275,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the ISO 15189 requirements relevant to PFT laboratory accreditation?',
        answer: 'ISO 15189 (Medical laboratories — Requirements for quality and competence) requires: a quality management system with documented procedures, method validation, internal QC (including bio-QC), participation in external quality assessment (proficiency testing), staff competency assessment and continuing education, equipment maintenance and calibration programs, measurement uncertainty estimation, document control, corrective and preventive action processes, internal audits, management review, and patient sample (test result) quality assurance. For PFT specifically, this translates to calibration verification protocols, technologist competency assessment, interpretation oversight, and systematic quality metrics monitoring.',
        difficulty: 3,
        topic: 'Advanced Quality Management',
        isFree: false,
        orderIndex: 276,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How are Levey-Jennings control charts used to monitor PFT equipment performance?',
        answer: 'Levey-Jennings charts plot sequential QC measurements (y-axis) against time or sequence number (x-axis), with the established mean and 1, 2, and 3 standard deviation (SD) control limits. For PFT bio-QC, the healthy subject\'s FVC, FEV1, DLCO, and other parameters are plotted after each QC session. Data points within 2 SD indicate acceptable performance. Patterns suggesting systematic problems include: values exceeding 3 SD (immediate investigation), progressive trend across 5 or more consecutive points (calibration drift), shift of 7 or more consecutive points on one side of the mean (systematic bias), or increasing scatter (deteriorating precision). These charts provide visual and statistical evidence of measurement stability over time.',
        difficulty: 2,
        topic: 'Advanced Quality Management',
        isFree: false,
        orderIndex: 277,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is a competency assessment program for PFT technologists, and what elements should it include?',
        answer: 'A competency assessment program systematically evaluates each technologist\'s ability to perform PFTs correctly. It should include: direct observation of test performance (spirometry, DLCO, plethysmography, etc.), assessment of patient coaching technique, evaluation of test quality metrics (percentage of acceptable and repeatable tests per technologist), review of interpretive accuracy and quality grading decisions, written or practical examinations on theory and procedures, assessment of equipment maintenance skills, evaluation of infection control compliance, and documentation of continuing education. Assessments should occur at orientation, during the first six months, annually thereafter, and when new procedures are introduced.',
        difficulty: 2,
        topic: 'Advanced Quality Management',
        isFree: false,
        orderIndex: 278,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the concept of clinically significant change in serial PFT measurements, and how is it determined?',
        answer: 'Clinically significant change is the minimum difference between two serial measurements that exceeds the inherent variability (measurement uncertainty plus biological variability) and therefore likely represents true physiological change. It is determined by calculating the coefficient of variation (CV) from repeated measurements in stable patients, then applying a threshold such as the minimal clinically important difference (MCID). For FEV1, a change of approximately 100-200 mL or 10-12% is generally considered significant. For FVC, 150-200 mL or 10%. For DLCO, 3-4 mL/min/mmHg or 10-15%. Changes within these thresholds may be due to measurement variability alone and should not trigger clinical action without corroborating information.',
        difficulty: 1,
        topic: 'Advanced Quality Management',
        isFree: false,
        orderIndex: 279,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Surgical Lung Volume Reduction and Transplant Evaluation (8 cards) ---
      {
        question: 'What PFT criteria are used to select candidates for lung volume reduction surgery (LVRS)?',
        answer: 'Ideal LVRS candidates have: FEV1 20-45% predicted (below 20% only if heterogeneous disease with upper lobe predominance and low exercise capacity), TLC >100% predicted (confirming hyperinflation), RV >150-200% predicted (significant air trapping), DLCO >20% predicted (below 20% with FEV1 below 20% is a contraindication due to high mortality — the NETT trial findings), and upper lobe predominant emphysema on CT. Low post-rehabilitation exercise capacity combined with upper lobe disease identifies the subgroup with greatest survival and functional benefit from LVRS.',
        difficulty: 2,
        topic: 'Surgical Lung Reduction and Transplant',
        isFree: false,
        orderIndex: 280,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the role of quantitative CT analysis in conjunction with PFTs for LVRS planning?',
        answer: 'Quantitative CT analysis complements PFTs by mapping the regional distribution and severity of emphysema using densitometry (voxels below -950 HU at full inspiration represent emphysematous tissue). This identifies target zones for surgical resection and predicts post-operative lung function improvement. Patients with heterogeneous upper lobe predominant disease (confirmed by CT) plus low baseline exercise capacity benefit most from LVRS. PFTs provide the global functional assessment while CT provides the anatomical characterization — both are essential for patient selection, and the combination predicts outcomes better than either alone.',
        difficulty: 2,
        topic: 'Surgical Lung Reduction and Transplant',
        isFree: false,
        orderIndex: 281,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT changes are expected after successful lung volume reduction surgery?',
        answer: 'After successful LVRS: FEV1 improves by 50-100% from baseline (median approximately 200-400 mL), FVC increases, RV decreases significantly (often 1-2 liters reflecting reduced air trapping), TLC decreases modestly, RV/TLC ratio normalizes, IC increases (improving the IC/TLC ratio), DLCO may remain unchanged or modestly improve, MIP improves (diaphragm repositioned to a more efficient length-tension relationship), and 6-minute walk distance increases. These improvements reflect restored elastic recoil, reduced dynamic hyperinflation, improved diaphragm mechanics, and better ventilation-perfusion matching in the remaining lung tissue.',
        difficulty: 2,
        topic: 'Surgical Lung Reduction and Transplant',
        isFree: false,
        orderIndex: 282,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How are predicted postoperative (ppo) pulmonary function values calculated for lung resection surgery?',
        answer: 'Predicted postoperative values are calculated using either anatomical segment counting or quantitative perfusion scanning. The segment method: ppoFEV1 = preoperative FEV1 x (1 - number of functional segments to be resected / total number of functional segments). The perfusion method (more accurate, especially with heterogeneous disease): ppoFEV1 = preoperative FEV1 x (1 - fractional perfusion of the lung to be resected). A ppoDLCO is similarly calculated. Guidelines suggest ppoFEV1 >40% predicted and ppoDLCO >40% predicted indicate acceptable surgical risk. Values between 30-40% predicted require further evaluation with CPET, where a ppoVO2max >10 mL/kg/min suggests acceptable risk.',
        difficulty: 3,
        topic: 'Surgical Lung Reduction and Transplant',
        isFree: false,
        orderIndex: 283,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is bronchoscopic lung volume reduction (BLVR), and what PFT criteria guide patient selection?',
        answer: 'BLVR uses endobronchial valves, coils, or thermal vapor ablation to achieve volume reduction without surgery. Patient selection for endobronchial valve placement requires: FEV1 15-45% predicted, RV >175-200% predicted (severe hyperinflation), TLC >100% predicted, DLCO >20% predicted, heterogeneous emphysema with an intact interlobar fissure (no collateral ventilation to the target lobe — assessed by Chartis catheter measurement), and post-rehabilitation 6MWD >140 meters. Success is defined as an FEV1 improvement of at least 100 mL or 12% and a reduction in RV, and is dependent on achieving lobar atelectasis.',
        difficulty: 3,
        topic: 'Surgical Lung Reduction and Transplant',
        isFree: false,
        orderIndex: 284,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What PFT monitoring is recommended after lung transplantation, and what changes indicate chronic lung allograft dysfunction (CLAD)?',
        answer: 'Post-transplant PFT monitoring includes spirometry (FEV1 and FVC) at every clinic visit, typically weekly for the first month, then monthly for the first year, then every 2-3 months. DLCO and lung volumes are measured periodically. CLAD is defined as a sustained decline in FEV1 to less than 80% of the post-transplant baseline (best FEV1 from two measurements at least 3 weeks apart, at least 3 months post-transplant). CLAD phenotypes include BOS (obstructive — FEV1/FVC decline) and restrictive allograft syndrome (RAS — FVC decline with or without FEV1/FVC decline, plus restrictive imaging changes). RAS has a worse prognosis than BOS.',
        difficulty: 3,
        topic: 'Surgical Lung Reduction and Transplant',
        isFree: false,
        orderIndex: 285,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the split function assessment using quantitative perfusion scanning, and when is it indicated?',
        answer: 'Split function assessment uses quantitative ventilation-perfusion lung scanning (typically perfusion scintigraphy with Tc-99m macroaggregated albumin) to determine the fractional contribution of each lung and each lobe to overall lung function. It is indicated when calculating predicted postoperative lung function for patients undergoing pneumonectomy or lobectomy who have borderline PFTs (FEV1 or DLCO below 80% predicted). The fractional perfusion of the lung or lobe to be resected is used to calculate ppoFEV1 and ppoDLCO, providing a more accurate prediction than anatomical segment counting, especially when disease distribution is heterogeneous.',
        difficulty: 1,
        topic: 'Surgical Lung Reduction and Transplant',
        isFree: false,
        orderIndex: 286,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What are the absolute PFT contraindications to lung resection surgery according to current guidelines?',
        answer: 'While no single PFT value absolutely prohibits surgery, very high-risk thresholds include: ppoFEV1 <30% predicted, ppoDLCO <30% predicted, and ppoVO2max <10 mL/kg/min (or <35% predicted). These thresholds indicate prohibitively high perioperative mortality and long-term morbidity risk. Additionally, baseline FEV1 <30% predicted with homogeneous emphysema or ppoDLCO <20% predicted are considered near-absolute contraindications. Patients in this high-risk zone should be evaluated by a multidisciplinary team considering the risk-benefit ratio, and alternative treatments (stereotactic radiation, ablation) may be preferred for malignancy.',
        difficulty: 1,
        topic: 'Surgical Lung Reduction and Transplant',
        isFree: false,
        orderIndex: 287,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Integration of Imaging with PFT Findings (10 cards) ---
      {
        question: 'How can high-resolution CT (HRCT) findings help explain discordant PFT results?',
        answer: 'HRCT can explain discordance between PFT parameters by revealing the anatomical basis. Examples: (1) Normal spirometry but low DLCO — HRCT may show early emphysema or pulmonary vascular disease. (2) Obstruction on spirometry but normal FEV1/FVC — HRCT may show air trapping on expiratory images despite large airway patency. (3) Mixed obstructive-restrictive pattern — HRCT may reveal combined fibrosis and emphysema (CPFE). (4) Preserved volumes but severe gas exchange impairment — HRCT may show diffuse ground-glass opacity (alveolar process) or extensive cystic disease. Imaging provides the structural context that makes sense of physiological measurements.',
        difficulty: 2,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 288,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is quantitative CT (qCT) densitometry, and how does it complement traditional PFT assessment of emphysema?',
        answer: 'Quantitative CT densitometry measures the percentage of lung voxels below a specified Hounsfield unit threshold (typically -950 HU on inspiratory CT for emphysema, -856 HU on expiratory CT for air trapping) to quantify emphysema extent and distribution. It complements PFTs by: (1) detecting early emphysema when PFTs are still normal, (2) mapping regional disease distribution (upper vs. lower lobe predominance), (3) tracking disease progression with higher sensitivity than FEV1 decline, (4) differentiating phenotypes (emphysema-predominant vs. airway-predominant COPD), and (5) guiding surgical planning for LVRS and endobronchial valve placement.',
        difficulty: 2,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 289,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does parametric response mapping (PRM) from paired inspiratory/expiratory CT scans provide information beyond standard PFTs?',
        answer: 'PRM is a voxel-by-voxel analysis of co-registered inspiratory and expiratory CT images that classifies each voxel as normal, emphysema (low density on both inspiratory and expiratory scans), or functional small airway disease (fSAD — normal density on inspiration but abnormally low on expiration, indicating air trapping without parenchymal destruction). PRM quantifies the relative contributions of emphysema versus small airway disease to overall obstruction, which standard PFTs cannot separate. fSAD measured by PRM correlates with FEF25-75 decline and may represent a treatable component of COPD that is invisible to routine spirometry.',
        difficulty: 3,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 290,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What information does hyperpolarized gas MRI provide that conventional PFTs cannot?',
        answer: 'Hyperpolarized gas MRI (using helium-3 or xenon-129) provides direct visualization of ventilation distribution in the lungs, showing ventilation defects as signal voids. It provides: (1) regional ventilation maps showing the spatial pattern of ventilation inhomogeneity (versus LCI which gives a single global number), (2) apparent diffusion coefficient (ADC) maps quantifying acinar airspace enlargement regionally, (3) xenon-129 dissolved-phase imaging showing gas transfer from airspace to tissue and blood, enabling regional DLCO-like assessment, and (4) ventilation defect percentage — a quantitative measure of the fraction of lung that is poorly ventilated. These regional assessments complement global PFT measurements.',
        difficulty: 3,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 291,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How do expiratory CT scans help assess air trapping, and how does this correlate with PFT measures of air trapping?',
        answer: 'Expiratory CT scans reveal air trapping as regions of relatively preserved low attenuation (remaining dark) while normal lung increases in density on expiration. Air trapping is quantified as the percentage of voxels below -856 HU on expiratory CT or as the expiratory-to-inspiratory mean lung density ratio. This correlates with PFT measures of air trapping including: RV/TLC ratio (r = 0.5-0.7), FEF25-75, and LCI. Expiratory CT can detect regional air trapping in specific lobes or lung zones that contribute to global PFT abnormalities, and it may identify air trapping when RV/TLC is only borderline elevated.',
        difficulty: 2,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 292,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the role of chest ultrasound (lung ultrasound) in relation to PFT findings?',
        answer: 'Lung ultrasound provides bedside assessment that can correlate with PFT findings: (1) B-lines (vertical artifacts from thickened interlobular septa) correlate with reduced lung compliance and may explain restrictive PFT patterns, (2) reduced diaphragm excursion on M-mode correlates with reduced VC and may explain a supine VC drop, (3) diaphragm thickening fraction during inspiration assesses contractility (reduced in neuromuscular disease), (4) pleural effusion quantification explains restrictive findings, and (5) consolidation assessment. While not a substitute for PFTs, lung ultrasound provides point-of-care anatomical information that can explain or predict PFT abnormalities, especially in ICU patients unable to perform standard testing.',
        difficulty: 1,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 293,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How does the CT-derived total lung capacity compare to plethysmographic TLC, and when is CT lung volume measurement clinically useful?',
        answer: 'CT-derived TLC (measured from volumetric inspiratory CT using automated segmentation) correlates well with plethysmographic TLC (r = 0.90-0.95) but may differ by 5-10%. CT TLC is measured at a single static inflation level and depends on the patient\'s inspiratory effort during scanning. It is clinically useful when: (1) plethysmography is unavailable or the patient cannot perform it, (2) there is discrepancy between plethysmographic and dilution volumes suggesting gas trapping (CT confirms anatomical lung size), (3) preoperative assessment when PFTs are not feasible, and (4) longitudinal monitoring when a CT is obtained for other clinical indications. Limitations include lack of standardized inflation pressure and radiation exposure.',
        difficulty: 2,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 294,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the significance of mosaic attenuation on inspiratory HRCT, and how does it correlate with PFT findings?',
        answer: 'Mosaic attenuation is a pattern of alternating regions of different lung density on inspiratory CT. It has three causes with different PFT correlations: (1) Small airway disease (obliterative bronchiolitis) — low-density regions represent air trapping with reduced perfusion; PFTs show obstruction and air trapping (elevated RV/TLC). (2) Pulmonary vascular disease — low-density regions reflect oligemia; PFTs show reduced DLCO with preserved volumes. (3) Ground-glass opacity from infiltrative disease — high-density regions are abnormal; PFTs show restriction or mixed pattern with reduced DLCO. Expiratory CT helps differentiate: air trapping accentuates mosaic pattern in airway disease but not in vascular disease.',
        difficulty: 3,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 295,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'How can functional respiratory imaging (FRI) from computational fluid dynamics applied to CT scans augment PFT data?',
        answer: 'FRI uses computational fluid dynamics modeling applied to segmented airway trees from CT scans to simulate airflow patterns, calculate regional airway resistance, and quantify lobar ventilation distribution. It augments PFTs by: (1) localizing obstruction to specific airway generations and lobes (versus global measures from spirometry), (2) predicting bronchodilator response at regional level, (3) identifying optimal targets for bronchoscopic interventions, (4) calculating lobar volumes and ventilation that correlate with but spatially refine plethysmographic measurements, and (5) modeling the effect of proposed surgical interventions on postoperative function. FRI provides the anatomical specificity that complements the global physiological measurements of standard PFTs.',
        difficulty: 3,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 296,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is electrical impedance tomography (EIT), and how does it relate to pulmonary function assessment?',
        answer: 'EIT is a radiation-free, bedside imaging technique that measures regional ventilation distribution by detecting changes in thoracic electrical impedance during breathing via an electrode belt placed around the chest. It provides real-time regional ventilation maps showing tidal ventilation distribution, end-expiratory lung impedance changes (correlating with regional FRC changes), and ventilation inhomogeneity indices. EIT relates to PFT assessment by providing continuous, breath-by-breath regional information analogous to what MBW measures globally — ventilation distribution and inhomogeneity. It is particularly valuable in mechanically ventilated patients and for titrating ventilator settings where standard PFTs cannot be performed.',
        difficulty: 2,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 297,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },

      // --- Remaining cards to reach 100 (3 cards) ---
      {
        question: 'What is the Chartis assessment system, and how is it used in the context of endobronchial valve placement?',
        answer: 'The Chartis system is a catheter-based assessment tool inserted through a bronchoscope to measure collateral ventilation between lung lobes. A balloon is inflated in the target lobe\'s bronchus, and airflow and resistance are measured. If flow decreases toward zero and resistance increases over several minutes, there is no significant collateral ventilation (Chartis-positive), indicating the fissure is intact and the patient is a good candidate for endobronchial valve placement. If flow persists (Chartis-negative), collateral ventilation through incomplete fissures will prevent the target lobe from collapsing after valve placement, predicting treatment failure.',
        difficulty: 2,
        topic: 'Surgical Lung Reduction and Transplant',
        isFree: false,
        orderIndex: 298,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'What is the role of xenon-129 MRI dissolved-phase imaging in assessing gas transfer, and how does it compare to traditional DLCO?',
        answer: 'Xenon-129 dissolved-phase MRI exploits the chemical shift of xenon as it moves from the airspace into the alveolar membrane (tissue phase) and then into the red blood cells (RBC phase). The ratio of RBC signal to tissue signal reflects regional gas transfer efficiency. A low RBC/tissue ratio indicates impaired transfer from the alveolar-capillary membrane to the blood — analogous to a reduced DLCO but with regional specificity. Unlike DLCO (a single global value), xenon-129 dissolved-phase imaging maps gas transfer heterogeneity across the lungs, identifying regions of impaired transfer that may guide targeted therapy or explain disproportionate gas exchange impairment relative to lung volumes.',
        difficulty: 3,
        topic: 'Integration of Imaging with PFT',
        isFree: false,
        orderIndex: 299,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
      {
        question: 'In multiple breath washout testing, why are LCI values from nitrogen washout and SF6 washout not interchangeable?',
        answer: 'LCI values differ between N2 and SF6 washout because: (1) N2 is a resident gas already present in the lungs at variable concentrations affected by prior breathing patterns, while SF6 is washed in to a uniform starting concentration. (2) N2 washout uses 100% O2 which can cause absorption atelectasis in poorly ventilated units, altering ventilation distribution during the test. (3) Tissue nitrogen excretion adds to the expired N2, artificially prolonging washout. (4) SF6 has a higher molecular weight than N2, leading to different diffusion-convection interaction patterns in the acinar zone. (5) Equipment dead space and gas analyzer response times differ between systems. Published reference values are gas-specific, and longitudinal monitoring must use the same tracer gas consistently.',
        difficulty: 2,
        topic: 'Lung Clearance Index and MBW',
        isFree: false,
        orderIndex: 300,
        divisionId: 'cmsm41fyp0005zf54vrwow6p4',
      },
    ],
    skipDuplicates: true,
  })

  console.log('Successfully seeded 100 RPFT flashcards (batch 3).')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
