import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const NPS_DIVISION_ID = 'cmsm41fvb0001zf54yp8r6skl'

const flashcards = [
  // ============================================================
  // NEONATAL ASSESSMENT (cards 1-15)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the five components of the Apgar score?',
    answer: 'The five components are heart rate, respiratory effort, muscle tone, reflex irritability, and color. Each is scored 0, 1, or 2 for a maximum total of 10. The Apgar is assessed at 1 and 5 minutes after birth.',
    difficulty: 1,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 1,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What Apgar score at 1 minute indicates the need for immediate resuscitative intervention?',
    answer: 'An Apgar score of 0 to 3 at 1 minute indicates severe distress requiring immediate resuscitation, including positive-pressure ventilation and possibly chest compressions. A score of 4 to 6 suggests moderate depression requiring stimulation and possible respiratory support.',
    difficulty: 1,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 2,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What does the Silverman-Anderson scoring system evaluate?',
    answer: 'The Silverman-Anderson score evaluates the severity of respiratory distress in neonates by grading five signs: upper chest lag, lower chest retractions, xiphoid retractions, nasal flaring, and expiratory grunting. Each is scored 0, 1, or 2, with higher totals indicating greater respiratory distress.',
    difficulty: 2,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 3,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does the Silverman-Anderson score differ from the Apgar score in interpretation?',
    answer: 'The scoring interpretations are opposite. A high Silverman-Anderson score (maximum 10) indicates severe respiratory distress, while a high Apgar score (maximum 10) indicates a vigorous, healthy newborn. A Silverman-Anderson score of 0 means no distress.',
    difficulty: 2,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 4,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the normal heart rate range for a term newborn?',
    answer: 'The normal heart rate for a term newborn is 120 to 160 beats per minute. A rate below 100 bpm is considered bradycardia and often signals hypoxia requiring intervention. Transient rates up to 180 bpm can occur with crying or stress.',
    difficulty: 1,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 5,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the normal respiratory rate for a newborn infant?',
    answer: 'The normal neonatal respiratory rate is 30 to 60 breaths per minute. Tachypnea above 60 breaths per minute is one of the earliest signs of respiratory distress in neonates. Periodic breathing with brief pauses of less than 20 seconds is considered normal.',
    difficulty: 1,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 6,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the clinical significance of expiratory grunting in a neonate?',
    answer: 'Expiratory grunting occurs when the infant exhales against a partially closed glottis, generating auto-PEEP to maintain functional residual capacity and prevent alveolar collapse. It is a compensatory mechanism seen in conditions like RDS, pneumonia, and TTN and signals significant respiratory distress.',
    difficulty: 2,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 7,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is gestational age assessed using the New Ballard Score?',
    answer: 'The New Ballard Score evaluates six neuromuscular criteria (posture, square window, arm recoil, popliteal angle, scarf sign, heel-to-ear) and six physical maturity criteria (skin, lanugo, plantar surface, breast, eye/ear, genitalia). The combined score estimates gestational age from 20 to 44 weeks.',
    difficulty: 3,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 8,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What does a capillary refill time greater than 3 seconds suggest in a neonate?',
    answer: 'A capillary refill time exceeding 3 seconds in a neonate suggests poor peripheral perfusion, which may indicate hypovolemia, hypothermia, sepsis, or cardiovascular compromise. It is assessed by pressing on the sternum or nail bed and timing the return of color.',
    difficulty: 1,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 9,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is transillumination of the chest used to detect in neonates?',
    answer: 'Transillumination is a bedside procedure using a fiberoptic light source placed against the chest wall to detect pneumothorax. A large halo of light transmission around the light source on the affected side suggests air in the pleural space. It is a rapid screening tool but requires chest radiograph confirmation.',
    difficulty: 2,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 10,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What physical finding distinguishes acrocyanosis from central cyanosis in a newborn?',
    answer: 'Acrocyanosis involves bluish discoloration limited to the hands and feet and is a normal finding in the first 24 to 48 hours of life due to peripheral vasoconstriction. Central cyanosis involves the trunk, lips, and mucous membranes, indicating hypoxemia requiring immediate evaluation.',
    difficulty: 1,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 11,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the expected blood pressure values for a term neonate in the first day of life?',
    answer: 'A term newborn typically has a mean arterial pressure of approximately 40 to 60 mmHg, with systolic pressure around 60 to 80 mmHg and diastolic 30 to 45 mmHg. A general guideline is that the mean blood pressure should be at least equal to the gestational age in weeks.',
    difficulty: 2,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 12,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Why is pre-ductal and post-ductal oxygen saturation monitoring performed in neonates?',
    answer: 'Pre-ductal SpO2 (right hand) and post-ductal SpO2 (either foot) are compared to detect right-to-left shunting through a patent ductus arteriosus. A difference greater than 5 to 10 percent suggests persistent pulmonary hypertension of the newborn or a ductal-dependent cardiac lesion.',
    difficulty: 2,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 13,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the purpose of plotting an infant\'s weight on a Lubchenco growth curve?',
    answer: 'The Lubchenco growth curve classifies neonates as small for gestational age (SGA), appropriate for gestational age (AGA), or large for gestational age (LGA) based on birth weight plotted against gestational age. SGA infants have increased risks of hypoglycemia, polycythemia, and hypothermia.',
    difficulty: 3,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 14,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What does a positive hyperoxia test suggest about the cause of neonatal cyanosis?',
    answer: 'In the hyperoxia test, the infant breathes 100 percent oxygen for 10 to 15 minutes and PaO2 is measured. A PaO2 that rises above 150 mmHg suggests pulmonary disease. If PaO2 remains below 100 mmHg despite 100 percent oxygen, cyanotic congenital heart disease with fixed right-to-left shunting is likely.',
    difficulty: 3,
    topic: 'Neonatal Assessment',
    isFree: true,
    orderIndex: 15,
  },

  // ============================================================
  // NEONATAL PATHOPHYSIOLOGY (cards 16-35)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the primary pathophysiology of neonatal respiratory distress syndrome (RDS)?',
    answer: 'RDS results from surfactant deficiency in premature lungs, leading to increased alveolar surface tension, alveolar collapse (atelectasis), decreased compliance, and impaired gas exchange. Type II pneumocytes are insufficiently developed to produce adequate surfactant, typically before 34 to 36 weeks gestation.',
    difficulty: 1,
    topic: 'Neonatal Pathophysiology',
    isFree: true,
    orderIndex: 16,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the classic chest radiograph appearance of RDS in a premature infant?',
    answer: 'The classic RDS radiograph shows a diffuse reticulogranular (ground-glass) pattern with air bronchograms and low lung volumes. In severe cases, the lung fields become completely opacified (white-out). These findings are bilateral and symmetric, reflecting diffuse alveolar collapse.',
    difficulty: 2,
    topic: 'Neonatal Pathophysiology',
    isFree: true,
    orderIndex: 17,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What maternal factors reduce the risk of RDS in a premature infant?',
    answer: 'Antenatal corticosteroids (betamethasone or dexamethasone) given to the mother at least 24 to 48 hours before delivery accelerate fetal lung maturation and surfactant production, significantly reducing RDS incidence. Prolonged rupture of membranes and maternal stress may also accelerate lung maturity.',
    difficulty: 2,
    topic: 'Neonatal Pathophysiology',
    isFree: true,
    orderIndex: 18,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is meconium aspiration syndrome (MAS) and when does it typically occur?',
    answer: 'MAS occurs when a fetus or newborn aspirates meconium-stained amniotic fluid, causing airway obstruction, chemical pneumonitis, and surfactant inactivation. It is most common in term or post-term infants (greater than 42 weeks) who experience fetal distress or hypoxia, triggering in-utero gasping and meconium passage.',
    difficulty: 1,
    topic: 'Neonatal Pathophysiology',
    isFree: true,
    orderIndex: 19,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the current recommendation for suctioning a non-vigorous newborn born through meconium-stained amniotic fluid?',
    answer: 'Current NRP guidelines no longer recommend routine intubation and tracheal suctioning for non-vigorous infants born through meconium. Instead, initial steps of resuscitation should be performed, including stimulation and clearing the airway as needed. Intubation is reserved for infants who remain apneic or have persistent obstruction.',
    difficulty: 2,
    topic: 'Neonatal Pathophysiology',
    isFree: true,
    orderIndex: 20,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is transient tachypnea of the newborn (TTN) and what causes it?',
    answer: 'TTN results from delayed reabsorption of fetal lung fluid after birth, causing mild respiratory distress with tachypnea. It is most common in term or late preterm infants delivered by cesarean section without labor, since thoracic compression during vaginal delivery normally helps expel lung fluid. TTN is self-limiting, typically resolving within 24 to 72 hours.',
    difficulty: 1,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 21,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does the chest radiograph in TTN differ from that in RDS?',
    answer: 'TTN shows hyperinflated lung fields with prominent perihilar streaking, fluid in the fissures, and sometimes small pleural effusions from retained fetal lung fluid. In contrast, RDS shows low lung volumes with a diffuse ground-glass pattern and air bronchograms from alveolar collapse.',
    difficulty: 3,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 22,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is persistent pulmonary hypertension of the newborn (PPHN)?',
    answer: 'PPHN occurs when pulmonary vascular resistance fails to decrease after birth, maintaining fetal circulatory patterns with right-to-left shunting through the foramen ovale and ductus arteriosus. This causes severe hypoxemia disproportionate to the degree of lung disease. It can be primary or secondary to conditions like MAS, RDS, or sepsis.',
    difficulty: 1,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 23,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What clinical finding strongly suggests PPHN rather than cyanotic heart disease in a hypoxemic neonate?',
    answer: 'In PPHN, a significant difference (greater than 5 to 10 percent) between pre-ductal (right hand) and post-ductal (foot) SpO2 is typically present, reflecting right-to-left ductal shunting. Cyanotic heart disease with intracardiac shunting usually produces uniformly low saturations with no significant pre-ductal/post-ductal gradient.',
    difficulty: 3,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 24,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What defines bronchopulmonary dysplasia (BPD) in a premature infant?',
    answer: 'BPD is a chronic lung disease defined as an oxygen requirement persisting beyond 28 days of life or at 36 weeks postmenstrual age. It results from prolonged exposure to positive-pressure ventilation, supplemental oxygen, and inflammation in the immature lung, leading to disrupted alveolar and vascular development.',
    difficulty: 1,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 25,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What strategies help prevent the development of BPD in premature neonates?',
    answer: 'Prevention strategies include using gentle ventilation with low tidal volumes and permissive hypercapnia, early CPAP instead of immediate intubation, targeting lower SpO2 ranges (90 to 95 percent), early caffeine therapy, vitamin A supplementation, and minimizing ventilator days by weaning aggressively when possible.',
    difficulty: 3,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 26,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is congenital diaphragmatic hernia (CDH) and how does it present at birth?',
    answer: 'CDH is a developmental defect in the diaphragm (most commonly on the left side, called a Bochdalek hernia) that allows abdominal organs to herniate into the thoracic cavity. It presents with severe respiratory distress at birth, a scaphoid (flat or concave) abdomen, absent breath sounds on the affected side, and bowel sounds heard in the chest.',
    difficulty: 3,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 27,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Why should bag-mask ventilation be avoided in a neonate with suspected congenital diaphragmatic hernia?',
    answer: 'Bag-mask ventilation forces air into the stomach and intestines that have herniated into the chest, further compressing the lungs and mediastinum. This worsens respiratory compromise and can cause cardiovascular collapse. The infant should be intubated immediately and an orogastric tube placed to decompress the stomach.',
    difficulty: 2,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 28,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is tracheoesophageal fistula (TEF) and what is the most common type?',
    answer: 'TEF is a congenital abnormality involving an abnormal connection between the trachea and esophagus. The most common type (Type C, approximately 85 percent of cases) features proximal esophageal atresia with a distal tracheoesophageal fistula. It presents with excessive drooling, choking with feeds, and inability to pass a nasogastric tube.',
    difficulty: 2,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 29,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is choanal atresia and how is it diagnosed?',
    answer: 'Choanal atresia is a congenital obstruction of the posterior nasal passages by bony or membranous tissue. Because neonates are obligate nasal breathers, bilateral atresia causes severe respiratory distress at rest that improves with crying (when the mouth opens). It is diagnosed by inability to pass a suction catheter through the nares.',
    difficulty: 2,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 30,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is Pierre Robin sequence and what airway challenge does it pose?',
    answer: 'Pierre Robin sequence consists of micrognathia (small mandible), glossoptosis (tongue falling posteriorly), and often a U-shaped cleft palate. The posteriorly displaced tongue can obstruct the airway, especially in the supine position. Prone positioning often alleviates the obstruction, but severe cases may require a nasopharyngeal airway or intubation.',
    difficulty: 3,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 31,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What lecithin-to-sphingomyelin (L/S) ratio indicates fetal lung maturity?',
    answer: 'An L/S ratio of 2.0 or greater in amniotic fluid indicates adequate fetal lung maturity and a low risk of RDS. Lecithin production by type II pneumocytes surpasses sphingomyelin at approximately 35 weeks gestation. The presence of phosphatidylglycerol further confirms lung maturity.',
    difficulty: 3,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 32,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What complications can result from meconium aspiration syndrome?',
    answer: 'MAS can lead to a ball-valve mechanism causing air trapping and pneumothorax, chemical pneumonitis from bile salts and enzymes in meconium, surfactant inactivation, PPHN from hypoxia-induced pulmonary vasoconstriction, and bacterial superinfection. Severe cases may require ECMO if conventional therapies fail.',
    difficulty: 3,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 33,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What radiographic finding is characteristic of meconium aspiration syndrome?',
    answer: 'MAS typically shows coarse, irregular patchy infiltrates with areas of hyperinflation (air trapping) and areas of atelectasis on chest radiograph. The findings are often asymmetric and bilateral. Pneumothorax and pneumomediastinum may also be present due to the ball-valve obstruction mechanism.',
    difficulty: 2,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 34,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the pathophysiology of a patent ductus arteriosus (PDA) in a premature infant?',
    answer: 'In premature infants, the ductus arteriosus may fail to close after birth due to immature ductal tissue and responsiveness to prostaglandins. A PDA causes left-to-right shunting of blood from the aorta to the pulmonary artery, leading to pulmonary overcirculation, pulmonary edema, and increased work of breathing. Treatment includes indomethacin or ibuprofen to promote closure.',
    difficulty: 3,
    topic: 'Neonatal Pathophysiology',
    isFree: false,
    orderIndex: 35,
  },

  // ============================================================
  // NEONATAL RESPIRATORY SUPPORT (cards 36-55)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the two main categories of exogenous surfactant preparations?',
    answer: 'Exogenous surfactants are classified as natural (animal-derived) and synthetic. Natural surfactants (such as beractant from bovine lung and poractant alfa from porcine lung) contain surfactant proteins SP-B and SP-C and generally show faster onset of action. Synthetic surfactants (such as lucinactant) are protein-free or contain synthetic peptides.',
    difficulty: 2,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 36,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the standard dose and route of administration for beractant (Survanta)?',
    answer: 'Beractant is administered endotracheally at a dose of 4 mL/kg (100 mg phospholipids/kg) divided into aliquots. The infant is repositioned between aliquots to promote distribution. Up to four doses can be given at 6-hour intervals. Suctioning should be avoided for at least one hour after administration.',
    difficulty: 3,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 37,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the INSURE technique for surfactant administration?',
    answer: 'INSURE stands for Intubate, Surfactant, Extubate. The infant is briefly intubated for surfactant instillation and then promptly extubated to nasal CPAP, avoiding prolonged mechanical ventilation. This approach reduces ventilator-associated lung injury and may decrease the incidence of BPD in premature infants.',
    difficulty: 2,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 38,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are common adverse effects observed during surfactant administration?',
    answer: 'Transient adverse effects include oxygen desaturation, bradycardia, endotracheal tube obstruction from the viscous surfactant, and pulmonary hemorrhage. Rapid improvement in compliance after surfactant can lead to overventilation and pneumothorax if ventilator settings are not promptly reduced.',
    difficulty: 2,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 39,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the LISA technique for surfactant delivery?',
    answer: 'LISA (Less Invasive Surfactant Administration) involves placing a thin catheter into the trachea under direct laryngoscopy while the infant remains on CPAP and continues spontaneous breathing. Surfactant is slowly instilled through the catheter, avoiding intubation and mechanical ventilation entirely. This method is associated with reduced need for mechanical ventilation.',
    difficulty: 3,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 40,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What CPAP pressure is typically used as starting therapy for neonatal RDS?',
    answer: 'Nasal CPAP is typically initiated at 5 to 6 cmH2O for neonates with RDS. It maintains functional residual capacity, prevents alveolar collapse, improves oxygenation, and reduces the work of breathing. Pressure can be increased to 8 cmH2O if needed, though higher pressures increase the risk of air leak and abdominal distension.',
    difficulty: 1,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 41,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the delivery interfaces available for neonatal CPAP?',
    answer: 'Neonatal CPAP can be delivered via binasal prongs, nasopharyngeal prongs, or nasal masks. Binasal short prongs are the most commonly used interface and have been shown to be more effective than single-prong devices. Proper sizing is essential to minimize nasal trauma, septal injury, and air leak.',
    difficulty: 1,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 42,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'At what flow rate range is high-flow nasal cannula (HFNC) defined in neonates?',
    answer: 'In neonates, HFNC is generally defined as flow rates greater than 1 liter per minute, typically ranging from 2 to 8 liters per minute using heated, humidified gas. HFNC generates variable, unmeasured positive distending pressure and is used as an alternative to nasal CPAP for mild to moderate respiratory distress.',
    difficulty: 2,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 43,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the concept of permissive hypercapnia in neonatal ventilation?',
    answer: 'Permissive hypercapnia is a ventilation strategy that accepts higher-than-normal PaCO2 levels (typically 45 to 55 mmHg, pH above 7.20) to allow use of lower tidal volumes and peak pressures. This approach reduces ventilator-induced lung injury and may decrease the incidence of BPD in premature infants.',
    difficulty: 2,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 44,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What tidal volume range is recommended for ventilating premature neonates?',
    answer: 'A tidal volume of 4 to 6 mL/kg is recommended for premature neonates to minimize volutrauma. Volume-targeted ventilation modes help maintain consistent tidal volumes despite changes in compliance. Excessive tidal volumes contribute to ventilator-induced lung injury and increase the risk of developing BPD.',
    difficulty: 1,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 45,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does high-frequency oscillatory ventilation (HFOV) work in neonates?',
    answer: 'HFOV delivers very small tidal volumes at extremely high respiratory rates (typically 8 to 15 Hz, or 480 to 900 breaths per minute). Gas exchange occurs through enhanced diffusion mechanisms rather than bulk flow. A continuous distending pressure (mean airway pressure) maintains lung recruitment while the oscillatory amplitude drives CO2 elimination.',
    difficulty: 3,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 46,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'On HFOV, what parameter is adjusted to change oxygenation and what parameter controls ventilation?',
    answer: 'Mean airway pressure (Paw) and FiO2 control oxygenation on HFOV by affecting lung recruitment and the fraction of inspired oxygen. Amplitude (delta P or power) and frequency control ventilation (CO2 removal). Increasing amplitude or decreasing frequency increases tidal volume delivery and enhances CO2 clearance.',
    difficulty: 3,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 47,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the mechanism of action of inhaled nitric oxide (iNO) in neonates?',
    answer: 'Inhaled nitric oxide is a selective pulmonary vasodilator that diffuses into pulmonary vascular smooth muscle cells and activates guanylate cyclase, increasing cyclic GMP and causing vasodilation. It selectively dilates vessels adjacent to ventilated alveoli, improving ventilation-perfusion matching without causing systemic hypotension.',
    difficulty: 1,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 48,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the standard starting dose and maximum recommended dose for inhaled nitric oxide?',
    answer: 'The standard starting dose of iNO is 20 parts per million (ppm). Maximum recommended dose is 20 ppm, as higher doses increase the risk of methemoglobinemia and nitrogen dioxide formation without additional clinical benefit. Once the infant improves, iNO is weaned gradually to avoid rebound pulmonary hypertension.',
    difficulty: 2,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 49,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What must be monitored during inhaled nitric oxide therapy?',
    answer: 'Methemoglobin levels must be monitored (maintain below 5 percent), as iNO oxidizes hemoglobin to methemoglobin which cannot carry oxygen. Nitrogen dioxide (NO2) levels in the circuit should remain below 1 ppm to prevent pulmonary toxicity. Continuous monitoring of inspired NO concentration and oxygenation is also essential.',
    difficulty: 3,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 50,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Why should inhaled nitric oxide never be abruptly discontinued?',
    answer: 'Abrupt discontinuation of iNO can cause life-threatening rebound pulmonary hypertension. The endogenous NO pathway becomes down-regulated during therapy, so sudden removal leads to acute vasoconstriction and severe hypoxemia. iNO should be weaned in decrements (typically from 20 to 5 to 1 ppm) with close monitoring before discontinuation.',
    difficulty: 3,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 51,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the role of caffeine citrate in neonatal respiratory care?',
    answer: 'Caffeine citrate is a methylxanthine used to treat apnea of prematurity by stimulating the central respiratory drive and increasing diaphragmatic contractility. It has also been shown to reduce the incidence of BPD, facilitate earlier extubation, and improve long-term neurodevelopmental outcomes. Loading dose is typically 20 mg/kg followed by 5 to 10 mg/kg daily.',
    difficulty: 3,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 52,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the advantages of volume-targeted ventilation over pressure-limited ventilation in neonates?',
    answer: 'Volume-targeted modes deliver consistent tidal volumes despite changes in lung compliance and resistance, reducing the risk of volutrauma during lung recovery and hypoventilation during disease progression. Studies show reduced duration of ventilation, lower rates of pneumothorax, and decreased incidence of BPD compared to pure pressure-limited ventilation.',
    difficulty: 3,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 53,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What SpO2 target ranges are generally recommended for premature neonates receiving supplemental oxygen?',
    answer: 'Current evidence supports targeting SpO2 of 90 to 95 percent in premature neonates. Higher targets (above 95 percent) increase the risk of retinopathy of prematurity (ROP) and BPD, while very low targets (below 85 percent) are associated with increased mortality. Alarm limits should be set tightly around the target range.',
    difficulty: 1,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 54,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is bubble CPAP and why is it used in neonatal care?',
    answer: 'Bubble CPAP generates continuous distending pressure by submerging the expiratory limb of the circuit into a water column. The depth of submersion determines the CPAP level. The bubbling creates small pressure oscillations that may enhance gas exchange. It is simple, inexpensive, and effective, making it widely used in both resource-rich and resource-limited settings.',
    difficulty: 1,
    topic: 'Neonatal Respiratory Support',
    isFree: false,
    orderIndex: 55,
  },

  // ============================================================
  // PEDIATRIC RESPIRATORY DISEASES (cards 56-75)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is croup and what pathogen most commonly causes it?',
    answer: 'Croup (laryngotracheobronchitis) is an inflammation of the subglottic airway causing a characteristic barking or seal-like cough, inspiratory stridor, and hoarseness. Parainfluenza virus (types 1 and 2) is the most common cause. It typically affects children aged 6 months to 3 years, with peak incidence in fall and winter.',
    difficulty: 1,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 56,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the classic radiographic sign of croup?',
    answer: 'The steeple sign (or pencil-point sign) on an anteroposterior neck radiograph is the classic finding in croup. It shows subglottic narrowing of the tracheal air column that tapers to a point, reflecting edema below the vocal cords. The normal shouldered appearance of the subglottic airway is lost.',
    difficulty: 1,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 57,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the first-line treatments for moderate to severe croup?',
    answer: 'First-line treatments include nebulized racemic epinephrine (0.5 mL of 2.25 percent solution) for rapid but temporary relief of airway edema, and systemic corticosteroids (oral dexamethasone 0.6 mg/kg or nebulized budesonide) for sustained anti-inflammatory effect. Cool mist therapy has not demonstrated significant benefit in clinical studies.',
    difficulty: 2,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 58,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does epiglottitis differ from croup in clinical presentation?',
    answer: 'Epiglottitis presents with acute onset of high fever, severe sore throat, dysphagia, drooling, muffled voice, and a tripod or sniffing position. Unlike croup, there is no barking cough, and stridor occurs late. Epiglottitis is a life-threatening emergency that can rapidly progress to complete airway obstruction, while croup has a more gradual onset.',
    difficulty: 2,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 59,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What radiographic finding is associated with epiglottitis?',
    answer: 'The thumbprint sign on a lateral neck radiograph shows a swollen, enlarged epiglottis resembling the shape of a thumb, replacing the normally thin epiglottic shadow. However, obtaining radiographs should not delay securing the airway, and examination of the airway should only be done in a controlled setting prepared for emergency intubation.',
    difficulty: 2,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 60,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is bronchiolitis and which virus is the most common cause?',
    answer: 'Bronchiolitis is an acute lower respiratory tract infection primarily affecting infants and young children under 2 years. Respiratory syncytial virus (RSV) is responsible for the majority of cases. It causes inflammation, edema, and necrosis of bronchiolar epithelium with mucus plugging, leading to air trapping, wheezing, and respiratory distress.',
    difficulty: 1,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 61,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the primary treatment approach for bronchiolitis?',
    answer: 'Treatment for bronchiolitis is primarily supportive: supplemental oxygen for hypoxemia, nasal suctioning, hydration, and monitoring. Bronchodilators, corticosteroids, and antibiotics have not been shown to be effective and are not routinely recommended. Hypertonic saline nebulization may be considered for hospitalized patients to reduce mucus plugging.',
    difficulty: 2,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 62,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What prophylactic medication is available for RSV prevention in high-risk infants?',
    answer: 'Palivizumab (Synagis) is a monoclonal antibody given as monthly intramuscular injections during RSV season for prophylaxis in high-risk infants, including those born prematurely or with hemodynamically significant congenital heart disease or chronic lung disease. Nirsevimab is a newer long-acting monoclonal antibody requiring only a single dose per season.',
    difficulty: 3,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 63,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What classifies asthma severity in children as persistent versus intermittent?',
    answer: 'Intermittent asthma features symptoms 2 days or fewer per week, nighttime awakenings 2 or fewer times per month, and normal FEV1 between exacerbations. Persistent asthma (mild, moderate, or severe) involves symptoms more than 2 days per week, more frequent nighttime symptoms, or reduced FEV1. Persistent asthma requires daily controller therapy.',
    difficulty: 2,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 64,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the stepwise approach to managing a severe acute asthma exacerbation in a child?',
    answer: 'Initial management includes continuous nebulized albuterol, ipratropium bromide (first hour), supplemental oxygen, and systemic corticosteroids (oral or IV). If the child fails to improve, intravenous magnesium sulfate and subcutaneous terbutaline or epinephrine may be added. Endotracheal intubation is a last resort due to the high risk of complications.',
    difficulty: 3,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 65,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What clinical scenario should raise suspicion for foreign body aspiration in a child?',
    answer: 'Sudden onset of choking, coughing, or wheezing in a previously healthy toddler (typically 1 to 3 years old) should raise suspicion for foreign body aspiration. Unilateral wheezing or decreased breath sounds are classic findings. A witnessed choking episode is not always reported, and diagnosis may be delayed if the initial event is missed.',
    difficulty: 1,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 66,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What radiographic findings suggest foreign body aspiration in the airway?',
    answer: 'Radiopaque foreign bodies are directly visible on chest radiograph. For radiolucent objects, indirect signs include unilateral hyperinflation (air trapping due to ball-valve obstruction), mediastinal shift away from the affected side on expiration, and atelectasis if complete obstruction occurs. Bilateral decubitus or inspiratory/expiratory films can help demonstrate air trapping.',
    difficulty: 3,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 67,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is pertussis and what are the characteristic stages of illness?',
    answer: 'Pertussis (whooping cough) is caused by Bordetella pertussis and progresses through three stages: the catarrhal stage (1 to 2 weeks of mild cold symptoms), the paroxysmal stage (2 to 6 weeks of severe coughing fits followed by an inspiratory whoop), and the convalescent stage (gradual recovery over weeks to months). Infants may present with apnea rather than whooping.',
    difficulty: 2,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 68,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What pulmonary manifestations characterize cystic fibrosis in children?',
    answer: 'CF causes thick, tenacious secretions due to defective CFTR chloride channels, leading to chronic airway obstruction, recurrent infections (especially Pseudomonas aeruginosa and Staphylococcus aureus), progressive bronchiectasis, and eventual respiratory failure. Pulmonary function testing shows an obstructive pattern with declining FEV1 over time.',
    difficulty: 2,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 69,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What airway clearance techniques are used for children with cystic fibrosis?',
    answer: 'Airway clearance methods include chest physiotherapy with postural drainage and percussion, high-frequency chest wall oscillation (vest therapy), positive expiratory pressure (PEP) devices, oscillatory PEP (such as the Acapella or Flutter valve), autogenic drainage, and exercise. Dornase alfa (Pulmozyme) and hypertonic saline nebulization are used as mucolytic adjuncts.',
    difficulty: 2,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 70,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What organisms most commonly cause community-acquired pneumonia in different pediatric age groups?',
    answer: 'In neonates, Group B Streptococcus and gram-negative enterics predominate. In infants 1 to 3 months, Chlamydia trachomatis, RSV, and S. pneumoniae are common. In preschool children (3 months to 5 years), viruses and S. pneumoniae are most frequent. In school-age children, Mycoplasma pneumoniae becomes increasingly common alongside S. pneumoniae.',
    difficulty: 3,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 71,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does the presentation of bacterial pneumonia differ from viral pneumonia in children?',
    answer: 'Bacterial pneumonia typically presents with abrupt onset of high fever, toxic appearance, productive cough, and focal lung findings (lobar consolidation with crackles and bronchial breath sounds). Viral pneumonia more often shows gradual onset, lower-grade fever, diffuse wheezing or crackles, and bilateral interstitial or peribronchial infiltrates on radiograph.',
    difficulty: 2,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 72,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the staccato cough and what diagnosis does it suggest in an infant?',
    answer: 'The staccato cough is a distinctive, sharp, choppy cough pattern heard in infants with Chlamydia trachomatis pneumonia. This afebrile pneumonia typically presents at 4 to 12 weeks of age with tachypnea, the staccato cough, bilateral interstitial infiltrates, and often a history of chlamydial conjunctivitis. Eosinophilia may be present.',
    difficulty: 3,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 73,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What respiratory condition should be suspected in a child with recurrent right middle lobe pneumonia?',
    answer: 'Recurrent pneumonia in the same anatomic location suggests an anatomic abnormality or foreign body aspiration. The right middle lobe is the most common site because its bronchus branches at a sharp angle and is relatively long and narrow. Foreign bodies tend to lodge in the right mainstem bronchus due to its wider diameter and more vertical orientation.',
    difficulty: 3,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 74,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the significance of a unilateral wheeze in a pediatric patient?',
    answer: 'A unilateral (localized) wheeze in a child is a red flag for foreign body aspiration, endobronchial lesion, or extrinsic airway compression rather than generalized bronchoconstriction. Unlike the bilateral, diffuse wheezing of asthma, unilateral wheezing does not respond to bronchodilator therapy and warrants further investigation with imaging or bronchoscopy.',
    difficulty: 1,
    topic: 'Pediatric Respiratory Diseases',
    isFree: false,
    orderIndex: 75,
  },

  // ============================================================
  // PEDIATRIC CRITICAL CARE (cards 76-90)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How do the anatomical differences of the pediatric airway affect respiratory care?',
    answer: 'The pediatric airway has a proportionally larger tongue, a more cephalad and anterior larynx (C3-C4 versus C4-C5 in adults), an omega-shaped floppy epiglottis, and a narrower subglottic region. The narrowest point in children under 8 is at the cricoid ring (rather than the vocal cords in adults), making subglottic edema particularly dangerous.',
    difficulty: 1,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 76,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What formula is used to estimate uncuffed endotracheal tube size for children?',
    answer: 'The formula for uncuffed ETT size is (age in years / 4) + 4 for the internal diameter in millimeters. For cuffed tubes, the formula is (age in years / 4) + 3 or 3.5. A tube one-half size larger and smaller should always be available at the bedside. This formula applies to children aged 1 to 10 years.',
    difficulty: 1,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 77,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Are cuffed or uncuffed endotracheal tubes recommended for pediatric intubation?',
    answer: 'Current guidelines support the use of cuffed ETTs for children of all ages, including neonates, as long as cuff pressure is monitored and maintained below 20 to 25 cmH2O. Cuffed tubes reduce the need for reintubation due to air leak, decrease aspiration risk, and allow more accurate ventilation and end-tidal CO2 monitoring.',
    difficulty: 2,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 78,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the correct ETT depth of insertion for an infant or child?',
    answer: 'For oral intubation, a common estimation is ETT internal diameter multiplied by 3 (for example, a 4.0 mm tube would be inserted to 12 cm at the lip). For neonates, the tip-to-lip distance can be estimated as 6 cm plus the weight in kilograms. Tube position should always be confirmed by chest radiograph with the tip between T1 and T3.',
    difficulty: 2,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 79,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the recommended initial ventilator settings for a mechanically ventilated pediatric patient?',
    answer: 'Initial settings include a tidal volume of 6 to 8 mL/kg ideal body weight, respiratory rate appropriate for age (higher rates for younger children), PEEP of 5 cmH2O, FiO2 titrated to maintain SpO2 of 92 to 97 percent, and inspiratory time of 0.5 to 1.0 seconds depending on age. Settings are adjusted based on blood gas results.',
    difficulty: 2,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 80,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the PALS algorithm for pediatric cardiac arrest with a shockable rhythm?',
    answer: 'For a shockable rhythm (ventricular fibrillation or pulseless ventricular tachycardia), deliver an initial shock at 2 J/kg, then resume CPR for 2 minutes. If VF/pVT persists, shock at 4 J/kg, resume CPR, and give epinephrine 0.01 mg/kg IV/IO. Third and subsequent shocks are 4 J/kg or higher (max 10 J/kg), with amiodarone 5 mg/kg considered.',
    difficulty: 3,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 81,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the dose of epinephrine used in pediatric cardiac arrest?',
    answer: 'Epinephrine for pediatric cardiac arrest is 0.01 mg/kg (0.1 mL/kg of the 1:10,000 concentration) given intravenously or intraosseously every 3 to 5 minutes. The endotracheal dose, though no longer preferred, is 0.1 mg/kg (0.1 mL/kg of 1:1,000). Maximum single IV dose is 1 mg.',
    difficulty: 2,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 82,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the proper chest compression parameters for infant CPR?',
    answer: 'For infant CPR, compress the lower third of the sternum to a depth of at least one-third the anteroposterior chest diameter (approximately 1.5 inches or 4 cm). The two-thumb encircling technique is preferred for two-rescuer CPR. The compression-to-ventilation ratio is 15:2 for two rescuers and 30:2 for a single rescuer.',
    difficulty: 1,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 83,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is weight estimated for a pediatric patient when an actual weight is unavailable?',
    answer: 'Length-based tape (Broselow tape) is the preferred method for estimating weight in children during emergencies. Alternatively, formulas can be used: for children 1 to 10 years, weight in kg equals (age in years times 2) plus 10. These estimates guide initial medication dosing and equipment sizing until an actual weight is obtained.',
    difficulty: 1,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 84,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the normal blood pressure range for a 1-year-old child?',
    answer: 'A 1-year-old typically has a systolic blood pressure of 80 to 100 mmHg. The lower limit of normal systolic BP for children 1 to 10 years can be estimated as 70 plus (age in years times 2). Hypotension is a late and ominous sign in pediatric shock, as children compensate with tachycardia before blood pressure drops.',
    difficulty: 2,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 85,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the signs of compensated versus decompensated shock in a pediatric patient?',
    answer: 'Compensated shock presents with tachycardia, delayed capillary refill, cool extremities, and weak peripheral pulses while maintaining normal blood pressure. Decompensated shock occurs when compensatory mechanisms fail, resulting in hypotension, altered mental status, absent peripheral pulses, and mottled or gray skin color. Intervention must occur during the compensated phase.',
    difficulty: 2,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 86,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the initial fluid bolus for pediatric septic shock?',
    answer: 'The initial fluid bolus for pediatric septic shock is 20 mL/kg of isotonic crystalloid (normal saline or lactated Ringer solution) given as rapidly as possible (ideally within 5 to 10 minutes). Up to 60 mL/kg may be given in the first hour, with reassessment after each bolus. Vasopressors should be initiated if the child remains hypotensive after 40 to 60 mL/kg.',
    difficulty: 2,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 87,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What size laryngoscope blade is used for neonatal and infant intubation?',
    answer: 'A Miller 0 (straight blade) is used for premature neonates, and a Miller 1 is used for term neonates and infants up to approximately 2 years. Straight blades are preferred in young children because they better lift the proportionally larger, floppier epiglottis by directly elevating it. A Miller 2 is appropriate for children aged 2 to 6 years.',
    difficulty: 1,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 88,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the significance of the pediatric assessment triangle (PAT) in emergency care?',
    answer: 'The PAT is a rapid visual assessment performed in the first 30 seconds using three components: appearance (tone, interactiveness, consolability, look/gaze, speech/cry), work of breathing (retractions, nasal flaring, positioning, audible sounds), and circulation to skin (pallor, mottling, cyanosis). It identifies the severity and type of physiologic derangement without requiring hands-on evaluation.',
    difficulty: 3,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 89,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the correct dose and route for atropine in pediatric bradycardia?',
    answer: 'Atropine for symptomatic bradycardia in children is dosed at 0.02 mg/kg IV/IO with a minimum dose of 0.1 mg (to prevent paradoxical bradycardia) and a maximum single dose of 0.5 mg. It is used when bradycardia persists despite adequate oxygenation and ventilation. Epinephrine (0.01 mg/kg) is the first-line drug for bradycardia causing poor perfusion.',
    difficulty: 3,
    topic: 'Pediatric Critical Care',
    isFree: false,
    orderIndex: 90,
  },

  // ============================================================
  // MONITORING & DIAGNOSTICS (cards 91-100)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is transcutaneous monitoring and when is it used in neonates?',
    answer: 'Transcutaneous monitoring uses heated electrodes placed on the skin to measure PtcO2 and PtcCO2 by warming the underlying capillary bed to arterialize the blood. It provides continuous, noninvasive trending of oxygenation and ventilation in neonates, reducing the need for frequent arterial blood gas sampling. The sensor site must be changed every 2 to 4 hours to prevent thermal skin injury.',
    difficulty: 2,
    topic: 'Monitoring & Diagnostics',
    isFree: false,
    orderIndex: 91,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Why can pulse oximetry readings be unreliable in neonates with high levels of fetal hemoglobin?',
    answer: 'Conventional pulse oximeters measure the ratio of oxyhemoglobin to deoxyhemoglobin and cannot distinguish between adult hemoglobin (HbA) and fetal hemoglobin (HbF). While SpO2 readings are generally still accurate, HbF has a higher oxygen affinity and shifts the oxyhemoglobin dissociation curve to the left, meaning a normal SpO2 may correspond to a lower PaO2 than expected.',
    difficulty: 3,
    topic: 'Monitoring & Diagnostics',
    isFree: false,
    orderIndex: 92,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What factors can cause falsely low pulse oximetry readings in neonates?',
    answer: 'Falsely low SpO2 readings can be caused by poor perfusion (cold extremities, shock), excessive motion artifact, improper sensor placement, ambient light interference, methemoglobinemia, and dark nail polish or skin pigmentation. Jaundice and elevated bilirubin levels do not significantly affect pulse oximetry accuracy.',
    difficulty: 1,
    topic: 'Monitoring & Diagnostics',
    isFree: false,
    orderIndex: 93,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the normal range of end-tidal CO2 in a ventilated neonate, and what can affect its accuracy?',
    answer: 'Normal end-tidal CO2 (EtCO2) in a ventilated neonate is typically 35 to 45 mmHg, correlating with PaCO2. However, EtCO2 often underestimates PaCO2 in neonates due to their high respiratory rates, small tidal volumes, increased dead space, and ventilation-perfusion mismatch. The gradient between PaCO2 and EtCO2 may be 2 to 10 mmHg or more.',
    difficulty: 2,
    topic: 'Monitoring & Diagnostics',
    isFree: false,
    orderIndex: 94,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does a neonatal blood gas differ from an adult blood gas in terms of normal values?',
    answer: 'Neonatal normal values include a PaO2 of 50 to 80 mmHg (lower than the adult 80 to 100 mmHg), PaCO2 of 35 to 45 mmHg (similar), and pH of 7.30 to 7.40 (slightly lower). The lower PaO2 is acceptable due to fetal hemoglobin having a higher oxygen affinity. Premature infants may have even lower PaO2 targets to reduce oxygen toxicity.',
    difficulty: 1,
    topic: 'Monitoring & Diagnostics',
    isFree: false,
    orderIndex: 95,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What blood gas finding is typical in a premature infant with uncorrected RDS?',
    answer: 'An untreated premature infant with RDS typically shows a blood gas with low PaO2 (hypoxemia), elevated PaCO2 (hypercapnia), and low pH (mixed respiratory and metabolic acidosis). The combined respiratory acidosis from poor ventilation and metabolic acidosis from tissue hypoxia and lactic acid production is characteristic of severe surfactant deficiency.',
    difficulty: 2,
    topic: 'Monitoring & Diagnostics',
    isFree: false,
    orderIndex: 96,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What chest radiograph finding indicates proper endotracheal tube placement in a neonate?',
    answer: 'The ETT tip should be visible on chest radiograph at the level of T1 to T2, which is approximately 1 to 2 cm above the carina. In neonates, the carina is typically at the T3 to T4 level. Right mainstem intubation should be suspected if there is asymmetric lung aeration with left lung atelectasis or diminished inflation.',
    difficulty: 1,
    topic: 'Monitoring & Diagnostics',
    isFree: false,
    orderIndex: 97,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What does a chest radiograph showing bilateral white-out with air bronchograms in a premature neonate suggest?',
    answer: 'Bilateral white-out with air bronchograms in a premature infant is the hallmark radiographic appearance of severe respiratory distress syndrome. The ground-glass opacification results from diffuse alveolar atelectasis due to surfactant deficiency, and air bronchograms appear because air-filled airways are contrasted against the collapsed, opacified lung parenchyma.',
    difficulty: 2,
    topic: 'Monitoring & Diagnostics',
    isFree: false,
    orderIndex: 98,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the significance of a difference between arterial and capillary blood gas values in a neonate?',
    answer: 'Capillary blood gases provide reliable pH and PCO2 values that closely approximate arterial values when obtained from a well-warmed, well-perfused heel. However, capillary PO2 is significantly lower and less reliable than arterial PaO2, making capillary gases unsuitable for assessing oxygenation. Arterial sampling remains necessary when accurate PaO2 is clinically essential.',
    difficulty: 2,
    topic: 'Monitoring & Diagnostics',
    isFree: false,
    orderIndex: 99,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What radiographic findings help differentiate between pneumothorax and pneumomediastinum in a neonate?',
    answer: 'A pneumothorax shows a visible visceral pleural line with absent lung markings laterally and possible mediastinal shift away from the affected side. Pneumomediastinum shows air outlining the mediastinal structures, a continuous diaphragm sign (air beneath the heart), and the thymic sail sign (air elevating the thymus away from the cardiac silhouette). Pneumomediastinum rarely requires intervention.',
    difficulty: 3,
    topic: 'Monitoring & Diagnostics',
    isFree: false,
    orderIndex: 100,
  },
]

async function main() {
  console.log('Seeding NPS flashcards (batch 1)...')
  console.log(`Total cards: ${flashcards.length}`)

  // Verify the division exists
  const division = await prisma.division.findUnique({
    where: { id: NPS_DIVISION_ID },
  })

  if (!division) {
    console.error(
      `Division ${NPS_DIVISION_ID} not found. Run seed-divisions.ts first.`
    )
    process.exit(1)
  }

  console.log(`Found division: ${division.name}`)

  // Delete existing flashcards for this division to avoid duplicates on re-run
  const deleted = await prisma.flashcard.deleteMany({
    where: { divisionId: NPS_DIVISION_ID },
  })
  console.log(`Cleared ${deleted.count} existing flashcards for NPS division.`)

  // Insert all flashcards
  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })

  console.log(`Successfully inserted ${result.count} NPS flashcards.`)

  // Log summary by topic
  const topicCounts: Record<string, number> = {}
  const difficultyCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0 }
  let freeCount = 0

  for (const card of flashcards) {
    topicCounts[card.topic] = (topicCounts[card.topic] || 0) + 1
    difficultyCounts[card.difficulty]++
    if (card.isFree) freeCount++
  }

  console.log('\n--- Summary ---')
  console.log('By topic:')
  for (const [topic, count] of Object.entries(topicCounts)) {
    console.log(`  ${topic}: ${count} cards`)
  }
  console.log('By difficulty:')
  console.log(`  Easy (1): ${difficultyCounts[1]}`)
  console.log(`  Medium (2): ${difficultyCounts[2]}`)
  console.log(`  Hard (3): ${difficultyCounts[3]}`)
  console.log(`Free cards: ${freeCount}`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
