import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const NPS_DIVISION_ID = 'cmsm41fvb0001zf54yp8r6skl'

const flashcards = [
  // ============================================================
  // NEONATAL NUTRITION & THERMOREGULATION (cards 101-115)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is total parenteral nutrition (TPN) and when is it indicated in neonates?',
    answer: 'TPN is the intravenous delivery of all nutritional requirements including amino acids, dextrose, lipids, electrolytes, vitamins, and trace elements. It is indicated when enteral feeding is not possible or must be delayed, such as in extremely premature infants, those with necrotizing enterocolitis, gastrointestinal surgical conditions, or severe respiratory compromise that prevents safe oral or gavage feeding.',
    difficulty: 1,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 101,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the major complications associated with prolonged TPN use in neonates?',
    answer: 'Major complications include TPN-associated cholestasis (conjugated hyperbilirubinemia from hepatic injury), catheter-related bloodstream infections, metabolic derangements (hyperglycemia, hypertriglyceridemia, electrolyte imbalances), and catheter-related thrombosis. Lipid emulsions containing soybean oil are most associated with cholestasis, and newer fish-oil-based emulsions may reduce this risk.',
    difficulty: 2,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 102,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is trophic feeding and why is it used in preterm neonates?',
    answer: 'Trophic feeding (also called minimal enteral nutrition or gut priming) involves small-volume feedings of 10 to 20 mL/kg/day that are not intended to provide full caloric needs. The purpose is to stimulate gastrointestinal tract maturation, promote hormonal responses, maintain intestinal mucosal integrity, and reduce the risk of feeding intolerance when full enteral nutrition is eventually advanced.',
    difficulty: 2,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 103,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Why is human breast milk preferred over formula for preterm infants?',
    answer: 'Breast milk provides immunoglobulins (especially secretory IgA), lactoferrin, growth factors, and beneficial bacteria that protect the immature gut. It significantly reduces the incidence of necrotizing enterocolitis, late-onset sepsis, and feeding intolerance in preterm infants. Human milk also improves long-term neurodevelopmental outcomes and is better tolerated than formula due to its composition and digestibility.',
    difficulty: 1,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 104,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the clinical hallmarks of necrotizing enterocolitis (NEC)?',
    answer: 'NEC presents with the classic triad of abdominal distension, bloody stools, and feeding intolerance (increased gastric residuals or bilious aspirates). Systemic signs include temperature instability, lethargy, apnea, and hemodynamic instability. Radiographic hallmarks include pneumatosis intestinalis (intramural gas), portal venous gas, and in severe cases, pneumoperitoneum indicating perforation.',
    difficulty: 2,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 105,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is NEC staged using the modified Bell classification?',
    answer: 'Stage I (suspected) includes nonspecific signs such as temperature instability, mild abdominal distension, and guaiac-positive stools. Stage II (definite) adds pneumatosis intestinalis on radiograph, absent bowel sounds, and abdominal tenderness. Stage III (advanced) includes bowel perforation with pneumoperitoneum, severe systemic illness, disseminated intravascular coagulation, and hemodynamic collapse requiring surgical intervention.',
    difficulty: 3,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 106,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is a neutral thermal environment and why is it critical for neonates?',
    answer: 'A neutral thermal environment (NTE) is the ambient temperature range in which the neonate maintains a normal core body temperature (36.5 to 37.5 degrees Celsius) with minimal metabolic rate and oxygen consumption. Maintaining NTE is critical because neonates, especially preterm infants, have a high surface-area-to-body-weight ratio, limited subcutaneous fat, and immature thermoregulatory mechanisms.',
    difficulty: 1,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 107,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the four mechanisms of heat loss in neonates?',
    answer: 'The four mechanisms are evaporation (wet skin losing heat to air, especially significant at birth), conduction (direct contact with cold surfaces such as scales or beds), convection (heat loss to circulating air currents), and radiation (heat transfer to nearby cooler solid surfaces without direct contact). Evaporative loss is the greatest source of heat loss immediately after delivery.',
    difficulty: 1,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 108,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does cold stress affect oxygen consumption and metabolism in a neonate?',
    answer: 'Cold stress triggers nonshivering thermogenesis through metabolism of brown adipose tissue, which significantly increases oxygen consumption and caloric expenditure. This can lead to hypoxemia, metabolic acidosis from anaerobic metabolism, hypoglycemia from depleted glycogen stores, and increased respiratory distress. Chronic cold stress in preterm infants impairs growth and increases morbidity.',
    difficulty: 1,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 109,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is kangaroo care and what are its documented physiological benefits?',
    answer: 'Kangaroo care involves placing the diaper-clad infant in direct skin-to-skin contact against the parent chest in a prone upright position. Documented benefits include improved thermoregulation (the parent chest acts as a thermal regulator), stabilized heart rate and respiratory patterns, improved oxygen saturations, reduced episodes of apnea and bradycardia, enhanced breastfeeding success, and decreased length of hospital stay.',
    difficulty: 1,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 110,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the clinical signs of neonatal hypoglycemia and at what blood glucose level is intervention required?',
    answer: 'Clinical signs include jitteriness, tremors, irritability, poor feeding, lethargy, hypotonia, seizures, apnea, and cyanosis. Many hypoglycemic neonates are asymptomatic. Intervention is generally recommended when blood glucose falls below 45 mg/dL in the first 4 to 24 hours of life. Extremely low glucose values below 25 mg/dL require immediate intravenous dextrose administration.',
    difficulty: 2,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 111,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Which neonates are at highest risk for hypoglycemia in the first hours of life?',
    answer: 'Neonates at highest risk include infants of diabetic mothers (due to fetal hyperinsulinism from chronic maternal hyperglycemia), small-for-gestational-age and intrauterine growth restricted infants (depleted glycogen stores), large-for-gestational-age infants, preterm infants (immature glycogenolysis and gluconeogenesis pathways), and infants experiencing perinatal stress, hypothermia, or sepsis.',
    difficulty: 2,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 112,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What role does brown adipose tissue play in neonatal thermoregulation?',
    answer: 'Brown adipose tissue (BAT) is the primary source of nonshivering thermogenesis in neonates. Located between the scapulae, around the kidneys and adrenal glands, and in the axillae and mediastinum, BAT contains abundant mitochondria with uncoupling protein 1 (UCP1) that allows direct heat generation by dissipating the proton gradient without producing ATP. Preterm infants have significantly less BAT, making them more vulnerable to hypothermia.',
    difficulty: 3,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 113,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How are gavage feedings administered to a preterm neonate who cannot coordinate suck-swallow-breathe?',
    answer: 'Gavage feeding is administered through an orogastric or nasogastric tube inserted into the stomach. The tube placement is verified by aspirating gastric contents, checking pH (should be acidic), and measuring the insertion length from nose or mouth to earlobe to xiphoid process. Feedings may be given as intermittent boluses over 15 to 30 minutes or as continuous infusion, with the infant monitored for residuals, distension, and aspiration.',
    difficulty: 2,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 114,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the caloric goal for a growing preterm infant and how is adequate growth assessed?',
    answer: 'Growing preterm infants typically require 110 to 130 kcal/kg/day to achieve adequate growth, which is defined as a weight gain of approximately 15 to 20 g/kg/day (mimicking intrauterine growth rates). Protein intake of 3.5 to 4.5 g/kg/day is essential for lean mass accretion. Growth is tracked by plotting weight, length, and head circumference on gestational age-appropriate growth charts at regular intervals.',
    difficulty: 3,
    topic: 'Neonatal Nutrition & Thermoregulation',
    isFree: false,
    orderIndex: 115,
  },

  // ============================================================
  // CONGENITAL HEART DISEASE (cards 116-130)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How are congenital heart defects classified as cyanotic versus acyanotic?',
    answer: 'Cyanotic defects involve right-to-left shunting of deoxygenated blood into the systemic circulation, causing visible cyanosis unresponsive to supplemental oxygen. Examples include tetralogy of Fallot, transposition of the great arteries, and truncus arteriosus. Acyanotic defects involve left-to-right shunts or obstructive lesions that do not immediately produce cyanosis, such as ventricular septal defect, atrial septal defect, and patent ductus arteriosus.',
    difficulty: 1,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 116,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the hyperoxia test and how does it help differentiate cyanotic heart disease from pulmonary disease?',
    answer: 'The hyperoxia test involves placing the cyanotic neonate on 100 percent oxygen for 10 to 15 minutes and measuring arterial PaO2. In pulmonary disease, PaO2 typically rises above 150 mmHg because the supplemental oxygen can overcome ventilation-perfusion mismatch. In cyanotic congenital heart disease with fixed right-to-left shunting, PaO2 usually remains below 100 mmHg because the shunted blood bypasses the lungs entirely.',
    difficulty: 2,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 117,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is a patent ductus arteriosus and when does it become clinically significant in preterm infants?',
    answer: 'A patent ductus arteriosus (PDA) is failure of the ductus arteriosus to close after birth, allowing blood to shunt from the aorta to the pulmonary artery (left-to-right). It becomes clinically significant when the shunt is large enough to cause pulmonary overcirculation, leading to pulmonary edema, widened pulse pressure, bounding pulses, a continuous machinery murmur, tachycardia, and difficulty weaning from respiratory support.',
    difficulty: 1,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 118,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What pharmacologic agents are used to close a hemodynamically significant PDA?',
    answer: 'Indomethacin and ibuprofen are cyclooxygenase inhibitors that promote ductal closure by blocking prostaglandin E2 synthesis, which normally maintains ductal patency. Acetaminophen (paracetamol) is also effective through inhibition of the peroxidase component of prostaglandin synthase. Indomethacin may reduce cerebral and renal blood flow more than ibuprofen, making ibuprofen or acetaminophen preferred in some centers.',
    difficulty: 2,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 119,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the anatomy and pathophysiology of a ventricular septal defect?',
    answer: 'A VSD is an abnormal opening in the interventricular septum allowing communication between the left and right ventricles. Because left ventricular pressure exceeds right, blood shunts left-to-right, causing increased pulmonary blood flow. Small VSDs may be asymptomatic and close spontaneously. Large VSDs can lead to congestive heart failure, failure to thrive, recurrent respiratory infections, and if untreated, irreversible pulmonary hypertension (Eisenmenger syndrome).',
    difficulty: 1,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 120,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the clinical features of an atrial septal defect in childhood?',
    answer: 'An ASD allows left-to-right shunting at the atrial level. Many children are asymptomatic for years because the shunt is low-pressure. Findings may include a fixed split second heart sound (S2 does not vary with respiration), a soft systolic ejection murmur at the upper left sternal border from increased flow across the pulmonic valve, and possibly exertional dyspnea. Large unrepaired ASDs can eventually cause right heart failure and atrial arrhythmias in adulthood.',
    difficulty: 2,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 121,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the four anatomic defects that define tetralogy of Fallot?',
    answer: 'The four components are: (1) ventricular septal defect, (2) overriding aorta positioned over the VSD, (3) right ventricular outflow tract obstruction (infundibular or valvar pulmonic stenosis), and (4) right ventricular hypertrophy secondary to the outflow obstruction. The degree of right ventricular outflow obstruction determines the severity of cyanosis and the amount of right-to-left shunting.',
    difficulty: 1,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 122,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is a "tet spell" and how is it managed acutely?',
    answer: 'A tet spell (hypercyanotic episode) in tetralogy of Fallot occurs when infundibular spasm abruptly increases right ventricular outflow obstruction, dramatically increasing right-to-left shunting. Management includes placing the infant in a knee-chest position to increase systemic vascular resistance, administering morphine to reduce agitation and infundibular spasm, IV fluid bolus, phenylephrine for systemic vasoconstriction, and supplemental oxygen. Beta-blockers can be used for recurrent spells.',
    difficulty: 3,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 123,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is transposition of the great arteries and why is it a neonatal emergency?',
    answer: 'In transposition of the great arteries (TGA), the aorta arises from the right ventricle and the pulmonary artery from the left ventricle, creating two parallel circulations. Deoxygenated blood recirculates systemically while oxygenated blood recirculates through the lungs. Survival depends on mixing between the two circuits through a PDA, ASD, or VSD. Without intervention, severe cyanosis and metabolic acidosis progress rapidly after birth.',
    difficulty: 2,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 124,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is a balloon atrial septostomy and when is it performed?',
    answer: 'A balloon atrial septostomy (Rashkind procedure) is an emergent cardiac catheterization procedure in which a balloon-tipped catheter is passed through the foramen ovale and inflated to tear the atrial septum, creating a larger interatrial communication. It is performed in neonates with transposition of the great arteries who have inadequate mixing and severe cyanosis, providing a temporary bridge until definitive arterial switch surgery can be performed.',
    difficulty: 3,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 125,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is coarctation of the aorta and how does it present in neonates versus older children?',
    answer: 'Coarctation is a discrete narrowing of the aorta, typically near the insertion of the ductus arteriosus. In neonates with severe coarctation, presentation is acute when the ductus closes, causing poor lower extremity perfusion, absent femoral pulses, metabolic acidosis, and cardiogenic shock. In older children with milder coarctation, presentation includes upper extremity hypertension, a blood pressure gradient between arms and legs, and a systolic murmur.',
    difficulty: 2,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 126,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are ductal-dependent cardiac lesions and why is prostaglandin E1 essential?',
    answer: 'Ductal-dependent lesions are congenital heart defects that require a patent ductus arteriosus for adequate systemic or pulmonary blood flow. Ductal-dependent systemic flow lesions include hypoplastic left heart syndrome and critical coarctation. Ductal-dependent pulmonary flow lesions include critical pulmonic stenosis, pulmonary atresia, and tricuspid atresia. Prostaglandin E1 maintains ductal patency by preventing smooth muscle constriction until surgical intervention.',
    difficulty: 2,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 127,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the side effects and monitoring requirements for prostaglandin E1 infusion?',
    answer: 'Side effects include apnea (occurs in 10 to 12 percent of neonates, requiring intubation readiness), hypotension, fever, flushing, and jitteriness. Less common effects include cortical hyperostosis with prolonged use, diarrhea, and seizure-like activity. Continuous cardiorespiratory monitoring is required, and intubation equipment must be immediately available. The typical starting dose is 0.05 to 0.1 mcg/kg/min, reduced to the lowest effective dose once ductal patency is confirmed.',
    difficulty: 3,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 128,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does pulse oximetry screening detect critical congenital heart disease in newborns?',
    answer: 'Newborn pulse oximetry screening is performed after 24 hours of age or before discharge by measuring SpO2 on the right hand (preductal) and either foot (postductal). A positive screen is SpO2 below 90 percent in either extremity, SpO2 below 95 percent in both extremities on three measurements separated by one hour, or a difference of more than 3 percent between the right hand and foot. Positive screens require echocardiographic evaluation.',
    difficulty: 3,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 129,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What respiratory management considerations apply to a neonate with a large left-to-right intracardiac shunt?',
    answer: 'Neonates with large left-to-right shunts (VSD, AVSD, PDA) develop pulmonary overcirculation and may present with tachypnea, diaphoresis with feeding, and failure to thrive. Respiratory management should avoid excessive supplemental oxygen and hyperventilation, as lowering pulmonary vascular resistance further increases left-to-right shunting. Modest PEEP can support alveolar recruitment, and diuretics reduce pulmonary edema. Surgical or catheter-based repair is definitive.',
    difficulty: 3,
    topic: 'Congenital Heart Disease',
    isFree: false,
    orderIndex: 130,
  },

  // ============================================================
  // NEONATAL NEUROLOGY (cards 131-145)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is intraventricular hemorrhage and which neonatal population is most at risk?',
    answer: 'Intraventricular hemorrhage (IVH) is bleeding that originates in the fragile capillaries of the germinal matrix, a highly vascularized subependymal region in the developing brain. Preterm infants less than 32 weeks gestation and below 1500 grams birth weight are most at risk because the germinal matrix is still present and vulnerable to fluctuations in cerebral blood flow. Most IVH occurs within the first 72 hours of life.',
    difficulty: 1,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 131,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is intraventricular hemorrhage graded by severity?',
    answer: 'IVH is graded I through IV by cranial ultrasound. Grade I is hemorrhage confined to the germinal matrix. Grade II is hemorrhage extending into the lateral ventricle without ventricular dilation. Grade III is intraventricular hemorrhage with acute ventricular dilation. Grade IV (now termed periventricular hemorrhagic infarction) involves parenchymal hemorrhagic involvement adjacent to the ventricle due to venous congestion and infarction. Grades III and IV carry the worst neurodevelopmental prognosis.',
    difficulty: 2,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 132,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What respiratory care strategies help reduce the risk of intraventricular hemorrhage in preterm infants?',
    answer: 'Strategies include avoiding rapid changes in PaCO2 (both hypocarbia and hypercarbia alter cerebral blood flow), maintaining gentle ventilation with lower peak inspiratory pressures, preventing pneumothorax (which causes acute changes in venous pressure), minimizing handling and painful stimuli, and ensuring hemodynamic stability. Delayed cord clamping and midline head positioning to optimize cerebral venous drainage are also protective measures.',
    difficulty: 3,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 133,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is hypoxic-ischemic encephalopathy (HIE) and what causes it?',
    answer: 'HIE is brain injury resulting from a significant hypoxic-ischemic event during the perinatal period, typically caused by birth asphyxia from conditions such as placental abruption, uterine rupture, umbilical cord prolapse, or prolonged labor with impaired uteroplacental perfusion. The severity ranges from mild (hyperalertness, normal tone) to severe (coma, absent reflexes, seizures, multiorgan failure), classified by the Sarnat staging system.',
    difficulty: 2,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 134,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is therapeutic hypothermia for neonatal HIE and what are the eligibility criteria?',
    answer: 'Therapeutic hypothermia involves cooling the neonate to a core temperature of 33.5 degrees Celsius (whole-body cooling) or head cooling to 34 to 35 degrees for 72 hours, followed by slow rewarming at 0.5 degrees per hour. Eligible neonates are 36 weeks gestation or greater, less than 6 hours old, with evidence of moderate to severe encephalopathy and a qualifying perinatal event (pH less than 7.0, base deficit greater than 16, Apgar 5 or less at 10 minutes, or need for continued resuscitation at 10 minutes).',
    difficulty: 2,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 135,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What physiological effects does therapeutic hypothermia produce that protect the injured neonatal brain?',
    answer: 'Therapeutic hypothermia reduces cerebral metabolic rate and oxygen demand, suppresses excitatory neurotransmitter release (particularly glutamate), decreases free radical production, inhibits apoptotic cell death pathways, reduces inflammatory cytokine release, and stabilizes the blood-brain barrier. These effects work during the latent phase between primary and secondary energy failure, reducing the extent of permanent neuronal injury.',
    difficulty: 3,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 136,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What complications must be monitored during therapeutic hypothermia in neonates?',
    answer: 'Complications include sinus bradycardia (physiologic response to cooling), coagulopathy and thrombocytopenia, skin breakdown and subcutaneous fat necrosis, electrolyte disturbances (hypokalemia, hypomagnesemia), renal impairment, pulmonary hypertension, and increased oxygen requirement. During rewarming, rapid temperature increases can cause vasodilation and hypotension, seizures, and metabolic instability, so rewarming must be performed slowly and carefully monitored.',
    difficulty: 3,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 137,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How do neonatal seizures differ in presentation from seizures in older children?',
    answer: 'Neonatal seizures are often subtle and may manifest as repetitive oral automatisms (lip smacking, chewing), eye deviations, cycling or pedaling movements of the extremities, or autonomic changes (apnea, desaturation, blood pressure fluctuations) rather than the generalized tonic-clonic movements seen in older children. Electroencephalographic monitoring is often needed because many clinical events are not true electrographic seizures, and many electrographic seizures have no visible clinical correlate.',
    difficulty: 2,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 138,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the first-line treatment for neonatal seizures?',
    answer: 'Phenobarbital is the first-line anticonvulsant for neonatal seizures, administered as a loading dose of 20 mg/kg intravenously. If seizures persist, additional boluses of 5 to 10 mg/kg may be given up to a total of 40 mg/kg. Respiratory therapists must be prepared for respiratory depression and possible need for intubation and mechanical ventilation, as phenobarbital depresses the respiratory drive.',
    difficulty: 2,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 139,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What distinguishes apnea of prematurity from pathological apnea?',
    answer: 'Apnea of prematurity is a developmental condition in infants less than 37 weeks gestation caused by immature brainstem respiratory centers. It typically resolves by 36 to 37 weeks postmenstrual age and is a diagnosis of exclusion. Pathological apnea occurs at any age and is caused by an identifiable condition such as sepsis, seizures, metabolic disorder, airway obstruction, intracranial hemorrhage, or gastroesophageal reflux, requiring treatment of the underlying cause.',
    difficulty: 1,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 140,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the three types of apnea seen in preterm infants?',
    answer: 'Central apnea results from absent respiratory effort due to brainstem immaturity with no airflow and no chest wall movement. Obstructive apnea involves continued respiratory effort against a blocked airway (often pharyngeal collapse) with chest wall movement but no airflow. Mixed apnea, the most common type in preterm infants, combines both central and obstructive components, usually beginning with a central pause followed by an obstructive event.',
    difficulty: 2,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 141,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does caffeine citrate work in treating apnea of prematurity and what are the dosing guidelines?',
    answer: 'Caffeine is a methylxanthine that stimulates the central respiratory drive by blocking adenosine receptors in the brainstem, increasing chemoreceptor sensitivity to CO2, improving diaphragmatic contractility, and reducing periodic breathing. The loading dose is 20 mg/kg of caffeine citrate intravenously followed by a daily maintenance dose of 5 to 10 mg/kg. Caffeine has also been shown to reduce the incidence of bronchopulmonary dysplasia in very preterm infants.',
    difficulty: 1,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 142,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the Sarnat staging system for hypoxic-ischemic encephalopathy?',
    answer: 'Sarnat Stage I (mild) presents with hyperalertness, normal or slightly increased tone, and intact reflexes with a good prognosis. Stage II (moderate) includes lethargy, hypotonia, decreased reflexes, and seizures, with variable neurodevelopmental outcomes. Stage III (severe) is characterized by coma, flaccid tone, absent reflexes, suppressed brainstem function, and a high mortality rate or severe disability in survivors.',
    difficulty: 3,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 143,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'Why must PaCO2 be carefully managed during mechanical ventilation of neonates at risk for IVH?',
    answer: 'Both hypocarbia and hypercarbia affect cerebral blood flow through CO2-mediated vasoreactivity. Hypocarbia (PaCO2 below 25 to 30 mmHg) causes cerebral vasoconstriction, reducing blood flow and increasing the risk of ischemic injury to the periventricular white matter. Hypercarbia causes cerebral vasodilation, which in the premature brain with fragile germinal matrix vessels can lead to hemorrhage. Maintaining PaCO2 in a stable range of 40 to 55 mmHg is recommended.',
    difficulty: 3,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 144,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What respiratory support strategies are used when a preterm infant has frequent apnea of prematurity despite caffeine therapy?',
    answer: 'When caffeine alone is insufficient, nasal CPAP at 4 to 6 cm H2O is applied to provide a pneumatic splint for the upper airway and maintain functional residual capacity. If apnea continues, heated humidified high-flow nasal cannula or nasal intermittent positive pressure ventilation (NIPPV) may be used. For refractory apnea with repeated desaturations and bradycardia, intubation and mechanical ventilation may become necessary until the infant reaches sufficient postmenstrual age for maturation of respiratory control.',
    difficulty: 2,
    topic: 'Neonatal Neurology',
    isFree: false,
    orderIndex: 145,
  },

  // ============================================================
  // ADVANCED NEONATAL VENTILATION (cards 146-165)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is volume-targeted ventilation (VTV) and why is it preferred for premature neonates?',
    answer: 'Volume-targeted ventilation delivers a set tidal volume by automatically adjusting inspiratory pressure breath to breath based on measured exhaled tidal volume. It is preferred in premature neonates because it reduces the risk of volutrauma from excessively large tidal volumes and atelectotrauma from volumes that are too low. Studies show VTV reduces the combined outcome of death or bronchopulmonary dysplasia, severe IVH, pneumothorax, and duration of ventilation.',
    difficulty: 1,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 146,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What tidal volume targets are recommended for volume-targeted ventilation in preterm neonates?',
    answer: 'The recommended target tidal volume for preterm neonates on volume-targeted ventilation is 4 to 6 mL/kg. Tidal volumes below 4 mL/kg may lead to inadequate ventilation and atelectasis, while volumes above 6 to 8 mL/kg increase the risk of volutrauma and lung inflammation. The ventilator adjusts peak inspiratory pressure within a set maximum limit to deliver the target volume consistently despite changing lung compliance.',
    difficulty: 1,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 147,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does volume guarantee (VG) mode function on neonatal ventilators?',
    answer: 'Volume guarantee is a pressure-limited, volume-targeted mode that measures the exhaled tidal volume of the previous breath and adjusts the peak inspiratory pressure for the next breath to achieve the set target volume. If compliance improves (such as after surfactant), the ventilator automatically lowers the pressure. If compliance worsens, pressure increases up to a user-defined maximum pressure limit. This autoregulation provides consistent minute ventilation and facilitates weaning.',
    difficulty: 2,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 148,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is neurally adjusted ventilatory assist (NAVA) and how does it detect respiratory effort?',
    answer: 'NAVA uses a specialized feeding catheter with embedded electrodes positioned at the level of the diaphragm to measure the electrical activity of the diaphragm (Edi signal). The ventilator delivers pressure proportional to the Edi signal in real time, so the patient controls the timing, magnitude, and cycling of every breath. This neural triggering eliminates conventional trigger delay and synchrony problems that occur with flow or pressure triggering in neonates.',
    difficulty: 2,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 149,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the advantages of NAVA over conventional triggered ventilation in neonates?',
    answer: 'NAVA offers superior patient-ventilator synchrony by eliminating trigger delays, auto-triggering, and double-triggering common with conventional modes. It reduces peak airway pressures because support is proportional to respiratory effort and ceases when diaphragmatic activity stops. NAVA adapts to irregular neonatal breathing patterns, decreases work of breathing, and provides real-time diaphragmatic activity monitoring that can detect apneic events and guide weaning decisions.',
    difficulty: 3,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 150,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is the NAVA level set and adjusted during neonatal ventilation?',
    answer: 'The NAVA level (in cm H2O per microvolt) determines how much pressure the ventilator delivers per unit of diaphragmatic electrical activity. A typical starting NAVA level in neonates is 0.5 to 2.0 cm H2O/mcV. It is titrated by observing tidal volumes, respiratory rate, Edi peak values, and clinical comfort. An Edi titration trial can be performed by gradually increasing the NAVA level until the peak Edi stabilizes, indicating adequate unloading of the respiratory muscles.',
    difficulty: 3,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 151,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the concept of lung-protective ventilation in premature neonates?',
    answer: 'Lung-protective ventilation aims to minimize ventilator-induced lung injury by using low tidal volumes (4 to 6 mL/kg), adequate PEEP to maintain alveolar recruitment and prevent atelectotrauma, permissive hypercapnia to reduce minute ventilation demands, and the lowest FiO2 necessary to achieve target oxygen saturations. The goal is to reduce the incidence and severity of bronchopulmonary dysplasia while maintaining acceptable gas exchange.',
    difficulty: 1,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 152,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the target PaCO2 values for permissive hypercapnia in ventilated preterm infants?',
    answer: 'Permissive hypercapnia in preterm infants typically targets a PaCO2 of 45 to 55 mmHg as long as pH remains above 7.20 to 7.25. Some centers accept PaCO2 up to 60 mmHg in stable infants. This approach reduces the need for aggressive ventilation, lowering the risk of volutrauma and ventilator-associated lung injury. However, PaCO2 values above 60 to 65 mmHg may increase the risk of IVH and should be avoided in the first 72 hours of life.',
    difficulty: 2,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 153,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the minimal ventilation strategy and how does it differ from conventional management?',
    answer: 'Minimal ventilation aims to use the least invasive and least aggressive respiratory support possible at each stage of a preterm infant respiratory course. This includes early CPAP rather than routine intubation, INSURE (intubate-surfactant-extubate) or LISA (less invasive surfactant administration) techniques, early extubation to noninvasive support, and accepting wider ranges of blood gas values. It contrasts with the historical approach of aggressive ventilation targeting normal adult blood gas parameters.',
    difficulty: 2,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 154,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the INSURE technique and when is it used?',
    answer: 'INSURE stands for INtubate-SURfactant-Extubate. The infant is briefly intubated, surfactant is administered through the endotracheal tube, and the infant is promptly extubated to noninvasive respiratory support (typically nasal CPAP). This approach aims to deliver surfactant therapy while minimizing the duration of mechanical ventilation and its associated lung injury. It is used in preterm infants with RDS who require surfactant but may not need prolonged ventilation.',
    difficulty: 1,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 155,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is less invasive surfactant administration (LISA) and how is it performed?',
    answer: 'LISA involves administering surfactant through a thin flexible catheter placed into the trachea during laryngoscopy while the infant remains on CPAP and breathes spontaneously without intubation. The surfactant distributes through the lungs via the infant spontaneous breathing efforts. LISA avoids the hemodynamic and neurological effects of intubation and positive pressure ventilation, and studies suggest it reduces the composite outcome of death or BPD compared to INSURE or mechanical ventilation.',
    difficulty: 3,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 156,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the role of nasal intermittent positive pressure ventilation (NIPPV) in neonatal care?',
    answer: 'NIPPV provides intermittent positive pressure breaths superimposed on CPAP delivered noninvasively through nasal prongs or mask. It is used as primary support after surfactant administration, as post-extubation support to reduce reintubation rates, and to manage apnea of prematurity when CPAP alone is insufficient. Synchronized NIPPV may be more effective than unsynchronized, and it generates higher mean airway pressures than CPAP alone without requiring intubation.',
    difficulty: 3,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 157,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What PEEP levels are typically used in ventilated preterm infants and how is optimal PEEP determined?',
    answer: 'Initial PEEP in ventilated preterm infants is typically set at 4 to 6 cm H2O. Optimal PEEP maintains alveolar recruitment and functional residual capacity without causing overdistension. It can be assessed by evaluating oxygenation response, chest radiograph lung expansion (8 to 9 rib expansion), compliance trends on the ventilator, and the presence of hemodynamic compromise. PEEP that is too low promotes atelectotrauma, while excessive PEEP impairs venous return and overdistends compliant alveoli.',
    difficulty: 2,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 158,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the key differences between high-frequency oscillatory ventilation and high-frequency jet ventilation in neonates?',
    answer: 'HFOV uses a piston or diaphragm to create oscillations at frequencies of 8 to 15 Hz with active expiration, maintaining mean airway pressure while using tidal volumes smaller than dead space. HFJV delivers short pulses of gas at 240 to 660 breaths per minute through a specialized endotracheal tube adapter, with passive expiration, and is used in conjunction with a conventional ventilator that provides PEEP and sigh breaths. HFJV may be preferred in air leak syndromes due to lower mean airway pressure.',
    difficulty: 3,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 159,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is amplitude (delta-P) adjusted on high-frequency oscillatory ventilation and what does it primarily affect?',
    answer: 'Amplitude (delta-P) on HFOV is the primary determinant of CO2 removal. Increasing the amplitude increases the tidal volume oscillation, enhancing ventilation and reducing PaCO2. The adequacy of amplitude is initially assessed by observing visible chest wall vibration (chest wiggle) from the clavicles to the umbilicus. Fine adjustments are guided by blood gas analysis. Mean airway pressure controls oxygenation on HFOV, not amplitude.',
    difficulty: 1,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 160,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the open lung strategy when initiating HFOV in a neonate?',
    answer: 'The open lung strategy involves systematically increasing mean airway pressure on HFOV until oxygenation improves and FiO2 can be weaned (indicating optimal lung recruitment), then gradually reducing MAP to just above the closing pressure to maintain recruitment without overdistension. The optimal MAP is typically 1 to 2 cm H2O above the closing pressure. This approach maximizes the number of recruited alveoli participating in gas exchange while minimizing barotrauma.',
    difficulty: 3,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 161,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are common indications for transitioning a neonate from conventional ventilation to high-frequency ventilation?',
    answer: 'Common indications include failure of conventional ventilation (persistent hypoxemia or hypercarbia despite escalating settings), air leak syndromes (pneumothorax, pulmonary interstitial emphysema) where lower peak pressures may promote healing, and severe PPHN or CDH where maintaining higher mean airway pressures can improve oxygenation. Some centers also use HFOV as a primary mode for extremely premature infants or those requiring high conventional ventilator settings.',
    difficulty: 2,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 162,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is pressure support ventilation (PSV) and how is it used for neonatal weaning?',
    answer: 'PSV augments spontaneous breaths with a set level of inspiratory pressure support that is patient-triggered, pressure-limited, and flow-cycled. It reduces the work of breathing imposed by the endotracheal tube and ventilator circuit. During weaning, the pressure support level is gradually reduced as the infant demonstrates increasing respiratory strength and stability. PSV is often combined with volume targeting to ensure consistent tidal volumes during the transition from full support to extubation.',
    difficulty: 2,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 163,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What SpO2 targets are recommended for extremely preterm infants and why?',
    answer: 'Current evidence supports SpO2 targets of 91 to 95 percent for extremely preterm infants less than 28 weeks gestation. Lower targets (85 to 89 percent) increase the risk of mortality and necrotizing enterocolitis, while higher targets (greater than 95 percent) increase the risk of retinopathy of prematurity and potentially BPD. Alarm limits should be set tightly around the target range to prevent both sustained hypoxemia and hyperoxemia.',
    difficulty: 1,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 164,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is automated FiO2 control and what evidence supports its use in neonatal ventilation?',
    answer: 'Automated FiO2 control uses closed-loop algorithms (such as those in INTELLiVENT-ASV or CLiO2 systems) to continuously adjust inspired oxygen concentration based on real-time SpO2 feedback. Studies demonstrate that automated systems increase the time spent within target SpO2 ranges, reduce episodes of hyperoxemia and severe hypoxemia, decrease manual FiO2 adjustments by nursing staff, and potentially reduce oxygen-related morbidity including retinopathy of prematurity.',
    difficulty: 3,
    topic: 'Advanced Neonatal Ventilation',
    isFree: false,
    orderIndex: 165,
  },

  // ============================================================
  // PEDIATRIC EMERGENCY (cards 166-180)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the most common causes of upper airway obstruction in pediatric patients?',
    answer: 'The most common causes include croup (laryngotracheobronchitis), which produces a barking cough and inspiratory stridor; foreign body aspiration, most common in children aged 1 to 3 years; epiglottitis, now rare due to Hib vaccination; peritonsillar and retropharyngeal abscesses; angioedema from allergic reactions; and airway burns from inhalation injury. Congenital causes such as laryngomalacia and subglottic stenosis are common in infants.',
    difficulty: 1,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 166,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is severe croup managed when racemic epinephrine and corticosteroids fail to provide adequate relief?',
    answer: 'When standard therapy fails, the child should be placed in a monitored setting with preparations for advanced airway management. Heliox (helium-oxygen mixture of 70:30 or 80:20) may reduce airway resistance and work of breathing due to its lower density. If respiratory failure is imminent, intubation with an endotracheal tube 0.5 to 1.0 mm smaller than predicted is performed to account for subglottic edema. In extremely rare cases, surgical airway or rigid bronchoscopy may be necessary.',
    difficulty: 3,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 167,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the respiratory manifestations of anaphylaxis in children and how are they treated?',
    answer: 'Respiratory manifestations include upper airway edema causing stridor and hoarseness, laryngospasm, bronchospasm with wheezing and dyspnea, and lower airway obstruction. Treatment is intramuscular epinephrine 0.01 mg/kg (1:1000 concentration, maximum 0.3 mg in children) into the anterolateral thigh, which is the first-line therapy. Adjunctive respiratory treatments include inhaled albuterol for bronchospasm, supplemental oxygen, and preparation for emergency intubation if airway edema progresses.',
    difficulty: 2,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 168,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What defines status asthmaticus and what is the stepwise respiratory management approach?',
    answer: 'Status asthmaticus is a severe, life-threatening asthma exacerbation that does not respond to initial bronchodilator therapy. Stepwise management includes continuous nebulized albuterol, ipratropium bromide in the first hour, systemic corticosteroids (methylprednisolone or dexamethasone), IV magnesium sulfate (25 to 75 mg/kg, max 2 g) for smooth muscle relaxation, and IV terbutaline for refractory cases. Noninvasive ventilation (BiPAP) may prevent intubation, but mechanical ventilation is required for respiratory failure.',
    difficulty: 2,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 169,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the ventilation challenges specific to intubating and mechanically ventilating a child in status asthmaticus?',
    answer: 'Intubation carries the risk of worsening bronchospasm and cardiovascular collapse due to air trapping and auto-PEEP. Ketamine is the preferred induction agent because of its bronchodilating properties. Ventilator strategy focuses on prolonged expiratory times, low respiratory rates (8 to 12 breaths per minute), and moderate tidal volumes (6 to 8 mL/kg) to minimize air trapping. Permissive hypercapnia (pH above 7.20) is accepted to avoid barotrauma. Extrinsic PEEP should be kept lower than auto-PEEP.',
    difficulty: 3,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 170,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What respiratory management considerations apply during status epilepticus in a child?',
    answer: 'Seizure activity increases metabolic demand and oxygen consumption while impairing protective airway reflexes. Respiratory management includes positioning to maintain airway patency, suctioning secretions, providing supplemental oxygen, and preparing for intubation if the airway becomes compromised or benzodiazepine therapy causes respiratory depression. Bag-mask ventilation equipment must be immediately available. Capnography can detect hypoventilation from anticonvulsant sedation before SpO2 changes appear.',
    difficulty: 2,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 171,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the pathophysiology of submersion injury (drowning) and how does it affect the lungs?',
    answer: 'Submersion causes aspiration of water into the lungs, leading to surfactant washout and inactivation, alveolar collapse, ventilation-perfusion mismatch, and intrapulmonary shunting. Both fresh and salt water cause similar degrees of lung injury. Laryngospasm may initially limit aspiration but produces hypoxemia without significant aspiration. The resulting pulmonary edema, inflammation, and acute respiratory distress syndrome may evolve over 24 to 72 hours, requiring close monitoring even in initially stable patients.',
    difficulty: 2,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 172,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What respiratory support strategies are recommended after pediatric submersion injury?',
    answer: 'Management ranges from supplemental oxygen for mild cases to intubation and mechanical ventilation with lung-protective settings for severe injury. PEEP is essential to recruit collapsed alveoli and improve oxygenation after surfactant washout. ARDS-net protocols (6 mL/kg tidal volumes, adequate PEEP, plateau pressure below 30 cm H2O) are followed for submersion-related ARDS. Hypothermia should be addressed, and all submersion victims with any respiratory symptoms should be observed for at least 6 to 8 hours for delayed pulmonary edema.',
    difficulty: 2,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 173,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What initial airway and breathing assessments are performed in the primary survey of a pediatric trauma patient?',
    answer: 'The primary survey follows the ABCDE approach. Airway assessment includes inspecting for obstruction (blood, vomit, foreign bodies, facial fractures), maintaining cervical spine immobilization, and performing jaw thrust (not head-tilt) if the airway needs opening. Breathing assessment evaluates respiratory rate, effort, chest wall symmetry, breath sounds, tracheal position, and presence of open or tension pneumothorax. High-flow oxygen is applied, and rapid sequence intubation with inline stabilization is performed if the airway is not patent.',
    difficulty: 1,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 174,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How is tension pneumothorax recognized and emergently treated in a pediatric patient?',
    answer: 'Tension pneumothorax presents with severe respiratory distress, absent breath sounds on the affected side, tracheal deviation toward the contralateral side, jugular venous distension, hypotension, and tachycardia. Emergent needle decompression is performed at the second intercostal space, midclavicular line (or fourth to fifth intercostal space, anterior axillary line in children) using an appropriately sized angiocatheter. Definitive treatment is chest tube placement connected to a drainage system.',
    difficulty: 1,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 175,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the role of point-of-care ultrasound in pediatric respiratory emergencies?',
    answer: 'Point-of-care ultrasound rapidly identifies pneumothorax (absent lung sliding and absence of B-lines), pleural effusion (anechoic fluid above the diaphragm), consolidation (tissue-like pattern with air bronchograms), and pericardial effusion. In trauma, the eFAST exam detects free fluid and pneumothorax without radiation exposure. Lung ultrasound has been shown to be more sensitive than chest radiography for pneumothorax and effusion in children and can guide procedural interventions in real time.',
    difficulty: 3,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 176,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What medication is given via endotracheal tube during pediatric resuscitation if IV/IO access is unavailable?',
    answer: 'Epinephrine is the primary resuscitation medication that can be administered endotracheally when IV or IO access is unavailable. The endotracheal dose is 0.1 mg/kg (10 times the IV dose) using the 1:1000 concentration, diluted with normal saline to a volume of 3 to 5 mL and instilled directly into the tube followed by several positive pressure breaths. However, IV/IO access is strongly preferred due to unpredictable absorption from the endotracheal route.',
    difficulty: 1,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 177,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is rapid sequence intubation in pediatric patients and what medications are commonly used?',
    answer: 'RSI involves the near-simultaneous administration of a sedative and neuromuscular blocking agent to achieve rapid, safe intubation while minimizing aspiration risk. Common induction agents include etomidate (0.3 mg/kg), ketamine (1 to 2 mg/kg, preferred in asthma and hemodynamically unstable patients), and propofol (1 to 3 mg/kg, avoided in hypotension). Rocuronium (1 mg/kg) is the preferred paralytic due to its rapid onset. Preoxygenation, suctioning equipment, and backup airway devices should be prepared in advance.',
    difficulty: 2,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 178,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the appropriate management of a pediatric patient with suspected smoke inhalation injury?',
    answer: 'Management includes high-flow 100 percent oxygen via nonrebreather mask (to displace carbon monoxide), early assessment for upper airway edema (hoarseness, stridor, facial burns, singed nasal hairs, carbonaceous sputum), and early intubation if any signs of progressive airway edema are present, as delayed intubation may become impossible once edema worsens. Cyanide poisoning should be considered in structural fires; hydroxocobalamin (70 mg/kg IV) is the antidote. Serial chest radiographs and bronchoscopy may be needed to assess lower airway injury.',
    difficulty: 3,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 179,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does the physiological response to hemorrhagic shock differ in children compared to adults?',
    answer: 'Children compensate for blood loss more effectively than adults through robust sympathetic vasoconstriction and tachycardia, maintaining blood pressure until 25 to 30 percent of blood volume is lost (compared to approximately 15 to 20 percent in adults). This means hypotension in a child is a late and ominous sign of decompensated shock. Respiratory compensation includes tachypnea to correct metabolic acidosis. Initial fluid resuscitation is 20 mL/kg isotonic crystalloid boluses, with blood transfusion considered after 40 mL/kg without improvement.',
    difficulty: 2,
    topic: 'Pediatric Emergency',
    isFree: false,
    orderIndex: 180,
  },

  // ============================================================
  // DEVELOPMENTAL & CHRONIC CARE (cards 181-200)
  // ============================================================
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What defines bronchopulmonary dysplasia (BPD) in the current classification system?',
    answer: 'BPD is defined as the need for supplemental oxygen or respiratory support at 36 weeks postmenstrual age in infants born before 32 weeks gestation. Severity is graded as: Grade 1 (nasal cannula at flow 2 L/min or less), Grade 2 (nasal cannula above 2 L/min or noninvasive positive pressure), and Grade 3 (invasive mechanical ventilation). The newer definition recognizes that BPD reflects arrested alveolar and vascular lung development rather than the fibrotic scarring seen in the original description.',
    difficulty: 2,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 181,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What long-term respiratory complications are associated with BPD?',
    answer: 'Long-term complications include persistent airway hyperreactivity and wheezing, exercise intolerance, recurrent respiratory infections requiring hospitalization (especially RSV), pulmonary hypertension, airflow obstruction on pulmonary function testing, and need for supplemental oxygen beyond initial hospitalization. Some children require bronchodilators, inhaled corticosteroids, or diuretics for months to years. BPD survivors may have reduced lung function that persists into adolescence and adulthood.',
    difficulty: 2,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 182,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What pharmacologic therapies are used for long-term BPD management?',
    answer: 'Inhaled bronchodilators (albuterol) treat airway hyperreactivity and bronchospasm. Inhaled corticosteroids reduce airway inflammation. Diuretics (furosemide, chlorothiazide, spironolactone) manage chronic pulmonary edema and fluid retention. Systemic corticosteroids (dexamethasone or hydrocortisone) may be used in severe cases for short courses, though the risk of neurodevelopmental impairment limits their use. Palivizumab (RSV prophylaxis) prevents severe RSV bronchiolitis during the first two RSV seasons.',
    difficulty: 2,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 183,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the indications for home oxygen therapy in infants with BPD?',
    answer: 'Home oxygen is indicated when an infant requires supplemental oxygen to maintain SpO2 above 92 to 95 percent but is otherwise medically stable, feeding well, and gaining weight appropriately. The infant must have a stable or decreasing oxygen requirement, no acute episodes requiring escalation, and caregivers trained in equipment use and emergency response. Home monitoring includes pulse oximetry, and periodic evaluations determine readiness for oxygen weaning.',
    difficulty: 1,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 184,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is home apnea monitoring and when is it indicated for neonatal discharge?',
    answer: 'Home apnea monitoring uses a cardiorespiratory monitor that detects chest wall impedance (respiratory movement) and heart rate, alarming for apnea (typically pauses greater than 20 seconds) and bradycardia (usually set at below 80 bpm). Indications include preterm infants with persistent apnea of prematurity near discharge, siblings of SIDS victims (in some protocols), and infants with apparent life-threatening events. Monitors are typically discontinued after the infant has been event-free for a specified period, often 6 to 8 weeks.',
    difficulty: 1,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 185,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What elements of developmental care are implemented in the NICU to support preterm infant neurodevelopment?',
    answer: 'Developmental care includes clustering care activities to minimize handling and allow longer rest periods, reducing ambient noise below 45 decibels, dimming lights with cycled day-night lighting, positioning with nesting boundaries to promote flexion, providing nonnutritive sucking opportunities, implementing kangaroo care, minimizing painful procedures and providing pain management (sucrose, facilitated tucking), and involving parents as primary caregivers. These interventions aim to reduce stress and support brain maturation.',
    difficulty: 1,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 186,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What criteria must a preterm infant meet before NICU discharge?',
    answer: 'Discharge criteria include maintaining temperature in an open crib, demonstrating competent oral feeding (breast or bottle) with adequate weight gain of 20 to 30 g/day, stable cardiorespiratory status for a minimum of 5 to 7 days without significant apnea or bradycardia, completion of necessary immunizations and screenings (hearing, retinopathy of prematurity, metabolic), established follow-up appointments, and caregiver competency in infant care, CPR, and use of any home medical equipment.',
    difficulty: 1,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 187,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the car seat tolerance test and why is it required before NICU discharge?',
    answer: 'The car seat challenge (tolerance screening) monitors the infant for apnea, bradycardia, and oxygen desaturation while seated in their car seat for 90 to 120 minutes or the anticipated duration of the ride home. Preterm infants are at risk for airway obstruction and oxygen desaturation in the semi-upright position due to poor head control and low muscle tone. Infants who fail may need a car bed (flat-lying position) instead of a standard rear-facing car seat for safe transport.',
    difficulty: 3,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 188,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the role of palliative care in the NICU and when should it be introduced?',
    answer: 'Palliative care in the NICU provides comfort-focused care, family support, shared decision-making, and symptom management for infants with life-limiting conditions. It should be introduced alongside curative care at the time of diagnosis of conditions such as severe congenital anomalies, extreme prematurity at the threshold of viability, severe HIE, or progressive organ failure. Palliative care is not limited to end-of-life situations and can be provided concurrently with intensive care.',
    difficulty: 2,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 189,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the indications for tracheostomy in a pediatric patient?',
    answer: 'Pediatric tracheostomy is indicated for prolonged mechanical ventilation (typically after 2 to 4 weeks without anticipated extubation), upper airway obstruction that cannot be corrected surgically (severe subglottic stenosis, craniofacial anomalies), neurological impairment with chronic aspiration or inability to protect the airway, and severe BPD requiring extended ventilatory support. Tracheostomy improves patient comfort, facilitates oral care and feeding, allows for speech development with appropriate valves, and enables ventilator weaning.',
    difficulty: 1,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 190,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the essential components of tracheostomy care in a pediatric patient?',
    answer: 'Essential care includes suctioning with appropriate technique (premoistened catheter, insertion depth no deeper than the tracheostomy tube length plus 0.5 cm), daily site care with inspection for granulation tissue or skin breakdown, tracheostomy tie changes to maintain a one-finger gap, humidification of inspired gases, and emergency equipment at bedside (spare tracheostomy tubes in current and one size smaller, obturator, scissors, bag-mask device). Caregivers must demonstrate competency in routine care, tube changes, and emergency management before discharge.',
    difficulty: 2,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 191,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What speaking valve options are available for pediatric tracheostomy patients and how do they work?',
    answer: 'The Passy-Muir valve is the most commonly used one-way speaking valve. It is placed on the hub of the tracheostomy tube, opens during inspiration to allow air through the tracheostomy, then closes during expiration, redirecting airflow up through the vocal cords and out the mouth and nose. This enables phonation, improves swallowing safety by restoring subglottic pressure, and enhances secretion management. The patient must have an air leak around the tracheostomy tube (cuff must be fully deflated) for the valve to function safely.',
    difficulty: 3,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 192,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What are the key components of a home ventilator program for a chronically ventilated child?',
    answer: 'A home ventilator program requires a portable ventilator with internal battery, adequate caregivers trained in ventilator management and troubleshooting (usually two trained individuals available at all times), backup ventilator and manual resuscitation equipment, home pulse oximetry, suction machine with supplies, humidification system, reliable power supply with backup generator, home nursing support, emergency action plan, and coordination with local emergency services, power company, and durable medical equipment providers.',
    difficulty: 2,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 193,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What modes of chronic ventilation are used in pediatric home settings?',
    answer: 'Home ventilation modes include invasive ventilation via tracheostomy (pressure control, volume control, or pressure support depending on the child needs) and noninvasive ventilation via nasal or full-face mask (BiPAP or CPAP for obstructive sleep apnea, neuromuscular weakness, or chronic respiratory insufficiency). Some children require only nocturnal ventilation, while others need continuous support. Diaphragm pacing may be used in select patients with high spinal cord injuries or central hypoventilation syndrome.',
    difficulty: 3,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 194,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is congenital central hypoventilation syndrome and how is it managed?',
    answer: 'CCHS (also known as Ondine curse) is a rare genetic disorder caused by PHOX2B gene mutations that impair autonomic control of breathing, particularly during sleep. Affected children have absent or severely diminished ventilatory responses to hypercarbia and hypoxemia. Management requires lifelong ventilatory support, at minimum during sleep, via tracheostomy with mechanical ventilation, noninvasive positive pressure ventilation, or diaphragm pacing. CCHS patients also require monitoring for associated autonomic dysfunction including Hirschsprung disease and neural crest tumors.',
    difficulty: 3,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 195,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'How does retinopathy of prematurity (ROP) relate to respiratory therapy practices?',
    answer: 'ROP develops from abnormal retinal blood vessel growth triggered by fluctuating oxygen levels in premature infants. Respiratory therapists directly influence ROP risk through oxygen management. Maintaining stable SpO2 within target ranges (91 to 95 percent for extremely preterm infants), avoiding hyperoxemia, minimizing FiO2 swings, setting tight alarm limits, and using automated oxygen controllers all help reduce ROP incidence. Serial ophthalmologic examinations are required for at-risk infants.',
    difficulty: 1,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 196,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the NIDCAP model of developmental care and what does it assess?',
    answer: 'The Newborn Individualized Developmental Care and Assessment Program (NIDCAP) is a comprehensive approach that involves formal behavioral observation of the preterm infant to identify stress cues (finger splaying, gaze aversion, hiccoughing, color changes, vital sign fluctuations) and self-regulatory behaviors (hand-to-mouth, grasping, tucking). Caregiving is then individualized based on these observations to provide the environment, timing, and handling that best support each infant neurobehavioral development and reduce stress.',
    difficulty: 3,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 197,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What respiratory considerations apply when managing a technology-dependent child in the community?',
    answer: 'Community management requires coordination with schools, transportation services, and community agencies. The respiratory care plan must address equipment portability (battery life, weight, transport), environmental exposures (air quality, allergens, infection risk), emergency protocols for equipment failure or power outages, school nursing support for ventilator-dependent students, and psychosocial support for the family. Regular reassessment of respiratory status, growth, and developmental progress guides ongoing adjustments to the care plan.',
    difficulty: 2,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 198,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What is the respiratory management approach for a child with neuromuscular disease and progressive respiratory failure?',
    answer: 'Management progresses through stages: initially, lung volume recruitment with breath-stacking or insufflation-exsufflation (cough assist device) to maintain chest wall compliance and effective cough. Nocturnal noninvasive ventilation (BiPAP) is introduced when sleep-disordered breathing develops (morning headaches, elevated CO2, declining FVC below 50 percent predicted). As disease progresses, daytime ventilatory support and aggressive secretion management with mechanical insufflation-exsufflation become necessary. Tracheostomy is considered when noninvasive support is no longer adequate.',
    difficulty: 3,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 199,
  },
  {
    divisionId: NPS_DIVISION_ID,
    question: 'What immunoprophylaxis is recommended for preterm infants with BPD during RSV season?',
    answer: 'Palivizumab (Synagis) is a monoclonal antibody administered as monthly intramuscular injections (15 mg/kg) during RSV season (typically November through March) for up to five doses. It is recommended for infants and children under 2 years of age with BPD who required medical therapy (oxygen, bronchodilators, diuretics, corticosteroids) within 6 months of RSV season onset. Nirsevimab, a longer-acting monoclonal antibody requiring only a single dose, is now available as an alternative for RSV prevention in eligible infants.',
    difficulty: 1,
    topic: 'Developmental & Chronic Care',
    isFree: false,
    orderIndex: 200,
  },
]

async function main() {
  console.log('Seeding NPS flashcards (batch 2)...')
  console.log(`Total cards: ${flashcards.length}`)

  // Verify the division exists
  const division = await prisma.division.findUnique({
    where: { id: NPS_DIVISION_ID },
  })

  if (!division) {
    console.error(
      `Division ${NPS_DIVISION_ID} not found. Run seed-divisions.ts first.`
    )
    process.exit(1)
  }

  console.log(`Found division: ${division.name}`)

  // Insert all flashcards (do NOT clear existing cards — batch 1 data must remain)
  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })

  console.log(`Successfully inserted ${result.count} NPS flashcards (batch 2).`)

  // Log summary by topic
  const topicCounts: Record<string, number> = {}
  const difficultyCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0 }
  let freeCount = 0

  for (const card of flashcards) {
    topicCounts[card.topic] = (topicCounts[card.topic] || 0) + 1
    difficultyCounts[card.difficulty]++
    if (card.isFree) freeCount++
  }

  console.log('\n--- Summary ---')
  console.log('By topic:')
  for (const [topic, count] of Object.entries(topicCounts)) {
    console.log(`  ${topic}: ${count} cards`)
  }
  console.log('By difficulty:')
  console.log(`  Easy (1): ${difficultyCounts[1]}`)
  console.log(`  Medium (2): ${difficultyCounts[2]}`)
  console.log(`  Hard (3): ${difficultyCounts[3]}`)
  console.log(`Free cards: ${freeCount}`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
