import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const ACCS_DIVISION_ID = 'cmsm41fw40002zf5463d399ps'

const flashcards = [
  // ============================================================
  // SHOCK STATES (cards 101-120)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the four major classifications of shock?',
    answer: 'The four classifications are cardiogenic (pump failure), distributive (vasodilation and maldistribution of blood flow), hypovolemic (inadequate circulating volume), and obstructive (mechanical impediment to circulation). Each has a distinct hemodynamic profile that guides treatment.',
    difficulty: 1,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 101,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What hemodynamic profile is characteristic of cardiogenic shock?',
    answer: 'Cardiogenic shock presents with low cardiac output, elevated CVP, elevated PAWP, and high SVR. The heart fails as a pump, causing backup of pressure into the pulmonary and systemic venous circulation while the body compensates with vasoconstriction to maintain perfusion pressure.',
    difficulty: 2,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 102,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What hemodynamic profile is characteristic of distributive (septic) shock?',
    answer: 'Distributive shock typically shows low SVR, low-to-normal CVP, low-to-normal PAWP, and high cardiac output in the early hyperdynamic phase. The hallmark is inappropriate vasodilation leading to relative hypovolemia despite potentially normal or elevated cardiac output.',
    difficulty: 2,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 103,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What hemodynamic profile is characteristic of hypovolemic shock?',
    answer: 'Hypovolemic shock presents with low CVP, low PAWP, low cardiac output, and elevated SVR. The reduced circulating volume decreases venous return and preload, resulting in diminished stroke volume and cardiac output with compensatory vasoconstriction.',
    difficulty: 1,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 104,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What hemodynamic findings distinguish obstructive shock from cardiogenic shock?',
    answer: 'Both show low cardiac output and elevated SVR, but obstructive shock may present with elevated CVP and low or normal PAWP (as in tension pneumothorax or tamponade compressing the right heart). Cardiogenic shock typically shows elevated PAWP reflecting left heart failure. The key distinction is that obstructive shock resolves when the mechanical obstruction is relieved.',
    difficulty: 3,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 105,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the recommended initial fluid resuscitation volume for septic shock according to the Surviving Sepsis Campaign?',
    answer: 'The Surviving Sepsis Campaign recommends at least 30 mL/kg of crystalloid fluid within the first three hours for patients with sepsis-induced hypoperfusion. Reassessment of fluid responsiveness should guide further volume administration to avoid excessive fluid accumulation.',
    difficulty: 1,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 106,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the target mean arterial pressure (MAP) for patients in septic shock?',
    answer: 'The initial target MAP is 65 mmHg or greater. This threshold has been shown to maintain adequate organ perfusion in most patients. Higher targets may be considered for patients with chronic hypertension, though routine targeting of higher MAP values has not demonstrated improved outcomes.',
    difficulty: 1,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 107,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'Why is norepinephrine the first-line vasopressor for septic shock?',
    answer: 'Norepinephrine is preferred because it provides potent alpha-1 vasoconstriction to raise SVR while offering modest beta-1 stimulation to support cardiac output. Compared to dopamine, it carries a lower risk of tachyarrhythmias and has demonstrated improved survival outcomes in septic shock.',
    difficulty: 2,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 108,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'When should vasopressin be added in the management of septic shock?',
    answer: 'Vasopressin (up to 0.03 units/min) is recommended as an adjunct when norepinephrine alone is insufficient to achieve the target MAP of 65 mmHg. It acts on V1 receptors to cause vasoconstriction through a catecholamine-independent pathway, which is advantageous since sepsis depletes endogenous vasopressin stores.',
    difficulty: 2,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 109,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What role do corticosteroids play in septic shock management?',
    answer: 'Low-dose hydrocortisone (200 mg/day) is recommended for patients with septic shock that is refractory to adequate fluid resuscitation and vasopressor therapy. Corticosteroids help restore vascular responsiveness to catecholamines and may shorten the duration of shock, though they have not consistently improved overall mortality.',
    difficulty: 2,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 110,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does dobutamine differ from norepinephrine in the treatment of shock?',
    answer: 'Dobutamine is a beta-1 and beta-2 agonist that primarily increases cardiac contractility and heart rate while causing mild vasodilation. Unlike norepinephrine, it does not significantly raise SVR. Dobutamine is indicated when cardiac output remains inadequate despite adequate volume resuscitation and MAP support, particularly in cardiogenic shock.',
    difficulty: 2,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 111,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the clinical signs that differentiate warm (early) septic shock from cold (late) septic shock?',
    answer: 'Warm shock presents with flushed and warm skin, bounding pulses, wide pulse pressure, and tachycardia reflecting the hyperdynamic state with low SVR. Cold shock presents with cool and mottled extremities, weak pulses, narrow pulse pressure, and altered mental status, indicating progression to myocardial depression and vasoconstriction as compensatory mechanisms fail.',
    difficulty: 2,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 112,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the role of lactate measurement in the assessment of shock?',
    answer: 'An elevated serum lactate above 2 mmol/L indicates tissue hypoperfusion and anaerobic metabolism. Serial lactate measurements guide resuscitation adequacy; a decrease of at least 10-20% every two hours suggests improving tissue oxygen delivery. Persistent or rising lactate despite intervention indicates ongoing cellular hypoxia and carries a poor prognosis.',
    difficulty: 1,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 113,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the Surviving Sepsis Campaign hour-1 bundle?',
    answer: 'The hour-1 bundle mandates that within one hour of sepsis recognition, clinicians should: measure a lactate level, obtain blood cultures before antibiotics, administer broad-spectrum antibiotics, begin rapid crystalloid infusion for hypotension or lactate of 4 mmol/L or greater, and start vasopressors if hypotension persists during or after fluid resuscitation to maintain MAP of 65 mmHg or greater.',
    difficulty: 2,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 114,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does massive pulmonary embolism cause obstructive shock?',
    answer: 'A massive PE acutely obstructs pulmonary arterial blood flow, dramatically increasing right ventricular afterload. The right ventricle dilates and fails, reducing left ventricular preload and cardiac output. The interventricular septum bows leftward, further impairing left ventricular filling. Hemodynamics show elevated CVP, elevated PA pressures, low PAWP, and low cardiac output.',
    difficulty: 3,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 115,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the preferred crystalloid for initial fluid resuscitation in septic shock?',
    answer: 'Balanced crystalloids such as lactated Ringer solution are generally preferred over normal saline for large-volume resuscitation. Normal saline in large volumes can cause hyperchloremic metabolic acidosis and may be associated with acute kidney injury. Albumin may be considered when patients require substantial amounts of crystalloid.',
    difficulty: 2,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 116,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What dynamic measures help predict fluid responsiveness in shock?',
    answer: 'Dynamic measures include pulse pressure variation, stroke volume variation, passive leg raise testing, and response to a fluid challenge. These are superior to static measures such as CVP alone because they assess the position on the Frank-Starling curve. A pulse pressure variation greater than 12-13% in a mechanically ventilated patient suggests fluid responsiveness.',
    difficulty: 3,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 117,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'Why is phenylephrine generally avoided as a single vasopressor in septic shock?',
    answer: 'Phenylephrine is a pure alpha-1 agonist that raises SVR without any beta-adrenergic support for the heart. In septic shock, where myocardial depression is common, it may increase afterload without improving cardiac output, potentially worsening organ perfusion. It is typically reserved for situations where tachyarrhythmias preclude the use of agents with beta activity.',
    difficulty: 3,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 118,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is neurogenic shock and how does its hemodynamic profile differ from other types of distributive shock?',
    answer: 'Neurogenic shock results from loss of sympathetic tone after spinal cord injury, typically above T6. Unlike septic shock, it classically presents with hypotension and bradycardia (rather than tachycardia) because both the vasomotor and cardiac sympathetic pathways are disrupted. The skin is warm and dry below the level of injury.',
    difficulty: 3,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 119,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the indications for initiating mechanical circulatory support in cardiogenic shock?',
    answer: 'Mechanical circulatory support such as an intra-aortic balloon pump or percutaneous ventricular assist device is considered when cardiogenic shock persists despite optimal medical therapy including vasopressors and inotropes. Indicators include a cardiac index below 2.0 L/min/m², systolic blood pressure below 90 mmHg despite pharmacologic support, and evidence of end-organ hypoperfusion.',
    difficulty: 3,
    topic: 'Shock States',
    isFree: false,
    orderIndex: 120,
  },

  // ============================================================
  // ADVANCED AIRWAY MANAGEMENT (cards 121-135)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What clinical features suggest a potentially difficult airway?',
    answer: 'Features include a Mallampati score of III or IV, thyromental distance less than 6 cm, limited mouth opening (less than 3 cm), limited cervical spine mobility, short thick neck, facial trauma or edema, and history of difficult intubation. The mnemonic LEMON (Look, Evaluate, Mallampati, Obstruction, Neck mobility) provides a systematic assessment framework.',
    difficulty: 1,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 121,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the purpose of preoxygenation before intubation, and how is it best achieved?',
    answer: 'Preoxygenation replaces nitrogen in the functional residual capacity with oxygen, creating an oxygen reservoir that extends the safe apnea time. It is best achieved by having the patient breathe 100% oxygen via a tight-fitting mask for three to five minutes of tidal breathing or by performing eight vital capacity breaths. Critically ill patients may benefit from high-flow nasal cannula or noninvasive ventilation during preoxygenation.',
    difficulty: 1,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 122,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What medications are used in a standard rapid sequence intubation protocol?',
    answer: 'RSI typically involves an induction agent and a neuromuscular blocker given in rapid succession without intervening positive pressure ventilation. Common induction agents include etomidate, ketamine, and propofol. Succinylcholine provides rapid-onset paralysis lasting 6-10 minutes; rocuronium at high dose (1.2 mg/kg) is an alternative with slightly longer onset but can be reversed with sugammadex.',
    difficulty: 2,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 123,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'Why is etomidate commonly selected as an induction agent for RSI in hemodynamically unstable patients?',
    answer: 'Etomidate provides rapid onset of unconsciousness (within 30-60 seconds) with minimal cardiovascular depression, making it favorable in hypotensive patients. It does not significantly lower blood pressure or heart rate compared to propofol. The concern about transient adrenal suppression from a single dose is generally considered clinically insignificant in most situations.',
    difficulty: 2,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 124,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the contraindications to succinylcholine use?',
    answer: 'Absolute contraindications include known hyperkalemia, personal or family history of malignant hyperthermia, and certain myopathies. Relative contraindications include burns more than 24-48 hours old, crush injuries, denervation injuries, prolonged immobility, and renal failure with hyperkalemia. These conditions involve upregulation of extrajunctional acetylcholine receptors that can release massive amounts of potassium upon depolarization.',
    difficulty: 2,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 125,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What advantages does video laryngoscopy offer over direct laryngoscopy?',
    answer: 'Video laryngoscopy provides a wider field of view via a camera at the blade tip, enabling visualization of the glottis even when the oral, pharyngeal, and laryngeal axes are not aligned. It improves first-pass success rates in difficult airways, requires less cervical spine manipulation, and allows other team members to view the screen for teaching and assistance. It is particularly beneficial with anterior airways and limited mouth opening.',
    difficulty: 1,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 126,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'When is fiberoptic intubation the preferred technique?',
    answer: 'Fiberoptic intubation is preferred for anticipated difficult airways when the patient can be kept spontaneously breathing, particularly in cases of known difficult anatomy, cervical spine instability, limited mouth opening, upper airway tumors, or severe facial trauma. It allows real-time visualization of airway anatomy and can be performed nasally or orally with topical anesthesia and mild sedation.',
    difficulty: 2,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 127,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is a surgical cricothyrotomy, and when is it indicated?',
    answer: 'Surgical cricothyrotomy involves making an incision through the cricothyroid membrane to establish an emergency airway. It is indicated in a "cannot intubate, cannot oxygenate" scenario when all other airway techniques have failed and the patient cannot be ventilated. The cricothyroid membrane is identified between the thyroid and cricoid cartilages, and a cuffed tracheostomy tube or endotracheal tube is inserted through the incision.',
    difficulty: 2,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 128,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What steps should be performed immediately after endotracheal intubation to confirm proper tube placement?',
    answer: 'Confirmation includes continuous waveform capnography (most reliable), auscultation of bilateral breath sounds and absence of epigastric sounds, observation of bilateral chest rise, condensation in the tube, and a chest radiograph to verify depth. The tube tip should be positioned 3-5 cm above the carina, typically at the 21-cm mark at the teeth for an average adult.',
    difficulty: 1,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 129,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the recommended approach when a supraglottic airway device fails to provide adequate ventilation?',
    answer: 'If ventilation through a supraglottic device is inadequate, the clinician should reposition the device, attempt a different size, or try a second-generation device with a gastric drain. If rescue ventilation remains unsuccessful, the algorithm progresses to an intubation attempt (which may be performed through certain supraglottic devices) or, if all efforts fail, to a surgical airway.',
    difficulty: 3,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 130,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is apneic oxygenation and how is it applied during intubation?',
    answer: 'Apneic oxygenation delivers high-flow oxygen (typically 15 L/min or more via nasal cannula) during the apneic period of intubation. Because oxygen is passively drawn into the lungs by the difference between oxygen absorption and carbon dioxide excretion rates, this technique extends the safe apnea time by maintaining oxygen saturations. It is especially valuable in critically ill patients who desaturate rapidly.',
    difficulty: 2,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 131,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the management protocol for an unplanned extubation in the ICU?',
    answer: 'Immediate assessment determines whether the patient requires reintubation based on respiratory status, level of consciousness, and ability to protect the airway. Bag-mask ventilation is initiated if the patient is in distress. If reintubation is needed, it should follow standard preparation with full airway equipment available. Prevention strategies include adequate sedation, proper tube securement, wrist restraints when appropriate, and patient education.',
    difficulty: 2,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 132,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the bougie (tracheal tube introducer), and when is it used?',
    answer: 'A bougie is a semi-rigid, curved introducer that is advanced blindly or under direct vision through the glottic opening when visualization is limited. Tactile feedback of tracheal ring clicks and a hold-up sign at approximately 40 cm confirm tracheal placement. The endotracheal tube is then railroaded over the bougie into the trachea. It is a key adjunct for Cormack-Lehane grade III views.',
    difficulty: 2,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 133,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the significance of the Cormack-Lehane grading system?',
    answer: 'The Cormack-Lehane system grades the laryngeal view during direct laryngoscopy. Grade I reveals the full vocal cords, grade II shows partial cords, grade III exposes only the epiglottis, and grade IV reveals no identifiable laryngeal structures. Grades III and IV predict difficult intubation and should prompt use of adjuncts such as a bougie, video laryngoscopy, or alternative airway techniques.',
    difficulty: 1,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 134,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What post-intubation complications should be monitored for in the first 24 hours?',
    answer: 'Early complications include right mainstem intubation, esophageal intubation (if unrecognized), aspiration pneumonitis, laryngospasm, bronchospasm, dental or soft tissue injury, hemodynamic instability from positive pressure ventilation or sedation, and barotrauma. Endotracheal tube cuff pressure should be maintained at 20-30 cmH2O to prevent mucosal ischemia while ensuring an adequate seal.',
    difficulty: 1,
    topic: 'Advanced Airway Management',
    isFree: false,
    orderIndex: 135,
  },

  // ============================================================
  // THORACIC & CARDIAC SURGERY (cards 136-150)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the primary respiratory therapy concerns in post-CABG patients?',
    answer: 'Key concerns include atelectasis from cardiopulmonary bypass-induced surfactant dysfunction, pleural effusions, phrenic nerve injury causing diaphragm paralysis, pain-limited inspiratory effort from sternotomy, and potential for pneumothorax. Management includes early mobilization, incentive spirometry, adequate analgesia, and lung-protective ventilation until extubation, which is typically targeted within 6-8 hours postoperatively.',
    difficulty: 2,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 136,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What sternal precautions must be observed after median sternotomy?',
    answer: 'Patients should avoid pushing, pulling, or lifting objects greater than 5-10 pounds for 6-8 weeks. They should not use their arms to push up from a seated position and should splint the sternum when coughing. These restrictions prevent sternal dehiscence while the wired sternum heals. Upper extremity range of motion should be maintained but high-resistance activities are contraindicated.',
    difficulty: 1,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 137,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does cardiac tamponade present hemodynamically, and what is the treatment?',
    answer: 'Cardiac tamponade causes equalization of diastolic pressures across all chambers, with elevated CVP, elevated PAWP, low cardiac output, and elevated SVR. Beck triad includes hypotension, distended jugular veins, and muffled heart sounds. Pulsus paradoxus (greater than 10 mmHg drop in systolic BP during inspiration) is characteristic. Treatment is emergent pericardiocentesis or surgical drainage.',
    difficulty: 3,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 138,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the indications for chest tube placement following thoracic surgery?',
    answer: 'Chest tubes are placed to drain air, blood, and fluid from the pleural space after lung resection, to promote lung re-expansion, and to monitor for postoperative bleeding. After pneumonectomy, a chest tube is typically clamped (not connected to suction) to allow gradual filling of the empty hemithorax. After lobectomy or segmentectomy, tubes are connected to suction to facilitate expansion of remaining lung tissue.',
    difficulty: 2,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 139,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What does a persistent air leak in a chest tube drainage system indicate?',
    answer: 'A persistent air leak seen as continuous bubbling in the water seal chamber suggests an ongoing bronchopleural fistula, incomplete lung expansion, or a disrupted bronchial stump anastomosis. Small leaks may resolve with continued drainage, but large or persistent leaks may require surgical repair. The system should also be checked for external leaks at connections before assuming a parenchymal source.',
    difficulty: 2,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 140,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What respiratory complications are specific to pneumonectomy?',
    answer: 'Pneumonectomy complications include postpneumonectomy pulmonary edema (from increased flow through the remaining lung), bronchopleural fistula at the bronchial stump, cardiac herniation through the pericardial defect, and contralateral pneumonia. Fluid restriction is essential because the entire cardiac output now flows through a single pulmonary vascular bed, making the remaining lung susceptible to hydrostatic edema.',
    difficulty: 3,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 141,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is mediastinitis, and how does it present after cardiac surgery?',
    answer: 'Mediastinitis is a deep sternal wound infection involving the mediastinal space, occurring in 1-2% of sternotomy patients. It presents with fever, sternal instability or clicking, purulent wound drainage, and elevated white blood cell count, typically 7-14 days postoperatively. Risk factors include diabetes, obesity, bilateral internal mammary artery harvest, and prolonged operative time. Treatment requires surgical debridement and prolonged antibiotics.',
    difficulty: 3,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 142,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How should mechanical ventilation be managed in the immediate post-cardiac surgery period?',
    answer: 'Initial settings typically include volume-controlled ventilation with tidal volumes of 6-8 mL/kg ideal body weight, PEEP of 5 cmH2O, FiO2 titrated to maintain SpO2 above 92%, and a respiratory rate to maintain normocarbia. Fast-track cardiac anesthesia protocols target extubation within 4-8 hours. Criteria for extubation include hemodynamic stability, adequate gas exchange, normothermia, controlled bleeding, and patient responsiveness.',
    difficulty: 2,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 143,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the significance of mediastinal chest tube output after cardiac surgery?',
    answer: 'Normal output is less than 100 mL/hour, decreasing over the first several hours. Output exceeding 200 mL/hour for 2-3 consecutive hours, or greater than 400 mL in the first hour, suggests surgical bleeding requiring re-exploration. Sudden cessation of drainage may indicate tube occlusion with potential tamponade. Tube stripping should be avoided as it generates excessive negative pressure.',
    difficulty: 2,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 144,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is phrenic nerve injury, and how does it affect respiratory function after cardiac surgery?',
    answer: 'Phrenic nerve injury from cold cardioplegia or surgical retraction causes hemidiaphragm paralysis. The affected diaphragm rises paradoxically during inspiration, reducing tidal volume and functional residual capacity. It is more common on the left side and presents as unexplained dyspnea, orthopnea, or difficulty weaning from mechanical ventilation. Diagnosis is confirmed by fluoroscopic sniff test or ultrasound.',
    difficulty: 2,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 145,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the differences in post-operative care between mechanical and bioprosthetic valve replacement?',
    answer: 'Mechanical valves require lifelong anticoagulation with warfarin due to their thrombogenic surface, maintaining an INR of 2.5-3.5 for mitral valves and 2.0-3.0 for aortic valves. Bioprosthetic valves typically require only 3-6 months of anticoagulation before transitioning to antiplatelet therapy. Bioprosthetic valves have limited durability (10-20 years) but avoid the bleeding risks of long-term anticoagulation.',
    difficulty: 2,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 146,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is a tension pneumothorax, and what immediate intervention is required?',
    answer: 'Tension pneumothorax occurs when air enters the pleural space through a one-way valve mechanism, progressively accumulating and shifting the mediastinum to the contralateral side. It causes severe hypotension, distended neck veins, absent breath sounds on the affected side, and tracheal deviation. Immediate needle decompression at the second intercostal space midclavicular line is performed, followed by definitive chest tube insertion.',
    difficulty: 1,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 147,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What factors determine readiness for chest tube removal?',
    answer: 'Chest tube removal is considered when there is no air leak for at least 24 hours, drainage is less than 200 mL per 24 hours (or less than 150 mL for some protocols), the lung is fully expanded on chest radiograph, and the patient has stable respiratory status. The tube is removed during either end-expiration with Valsalva or end-inspiration, and a petroleum gauze dressing is applied over the site immediately.',
    difficulty: 1,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 148,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is postpericardiotomy syndrome?',
    answer: 'Postpericardiotomy syndrome is an inflammatory condition occurring days to weeks after cardiac surgery, characterized by fever, pleuritic chest pain, pericardial and pleural effusions, and elevated inflammatory markers. It is believed to be an autoimmune response to pericardial injury. Treatment includes NSAIDs and colchicine, with corticosteroids reserved for refractory cases. Large effusions causing tamponade require drainage.',
    difficulty: 3,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 149,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the respiratory implications of thoracoscopic (VATS) surgery compared to open thoracotomy?',
    answer: 'VATS involves smaller incisions and less chest wall disruption, resulting in reduced postoperative pain, preserved respiratory muscle function, fewer pulmonary complications, and faster recovery compared to open thoracotomy. However, one-lung ventilation is still required during the procedure. Patients typically have shorter chest tube duration and earlier mobilization, with lower incidence of chronic post-surgical pain.',
    difficulty: 1,
    topic: 'Thoracic & Cardiac Surgery',
    isFree: false,
    orderIndex: 150,
  },

  // ============================================================
  // BURNS & TRAUMA ICU (cards 151-165)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What clinical findings suggest inhalation injury in a burn patient?',
    answer: 'Findings include facial burns, singed nasal or facial hair, carbonaceous sputum, hoarseness or stridor, history of enclosed-space fire exposure, and soot deposits in the oropharynx. Direct visualization via bronchoscopy is the gold standard for diagnosis, revealing airway edema, erythema, and carbonaceous deposits. Upper airway edema can progress rapidly, so early intubation is often indicated.',
    difficulty: 1,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 151,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is carboxyhemoglobin (COHb) interpreted in carbon monoxide poisoning?',
    answer: 'Normal COHb levels are less than 3% in nonsmokers and up to 10% in smokers. Levels of 15-20% cause headache and confusion, 20-40% cause disorientation and nausea, 40-60% cause seizures and coma, and levels above 60% are often fatal. Pulse oximetry is unreliable because it cannot distinguish COHb from oxyhemoglobin. CO-oximetry is required for accurate measurement.',
    difficulty: 2,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 152,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the treatment for carbon monoxide poisoning?',
    answer: 'Treatment involves immediate administration of 100% oxygen, which reduces the half-life of carboxyhemoglobin from 4-6 hours on room air to approximately 60-90 minutes. Hyperbaric oxygen therapy at 2.5-3 atmospheres further reduces the half-life to 15-30 minutes and is considered for patients with loss of consciousness, neurologic deficits, cardiac ischemia, COHb greater than 25%, or pregnancy with COHb greater than 15%.',
    difficulty: 2,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 153,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How is cyanide toxicity recognized and treated in fire victims?',
    answer: 'Cyanide poisoning should be suspected in fire victims with persistent lactic acidosis despite adequate oxygenation and normal or low COHb. Cyanide inhibits cytochrome oxidase, blocking aerobic metabolism. The antidote hydroxocobalamin (Cyanokit) binds cyanide to form cyanocobalamin (vitamin B12) and is preferred in smoke inhalation because, unlike the older antidote sodium nitrite, it does not form methemoglobin, which would further impair oxygen carrying capacity.',
    difficulty: 3,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 154,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the Parkland formula for burn fluid resuscitation?',
    answer: 'The Parkland formula calculates the first 24-hour crystalloid requirement as 4 mL multiplied by body weight in kilograms multiplied by the percentage of total body surface area burned. Half is given in the first 8 hours from the time of burn injury, and the remaining half over the next 16 hours. Lactated Ringer solution is the preferred fluid. Urine output of 0.5-1.0 mL/kg/hour guides adequacy of resuscitation.',
    difficulty: 1,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 155,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'Why do burn patients develop unique ventilatory challenges?',
    answer: 'Circumferential chest wall burns create a restrictive physiology by forming tight eschar that limits chest wall compliance. Inhalation injury causes progressive airway edema, bronchospasm, and mucosal sloughing with cast formation. Massive fluid resuscitation leads to generalized edema worsening pulmonary compliance. High metabolic rates increase CO2 production, demanding higher minute ventilation. Escharotomy of the chest may be necessary to restore chest wall excursion.',
    difficulty: 3,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 156,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the Rule of Nines used for in burn assessment?',
    answer: 'The Rule of Nines estimates total body surface area burned in adults. The head and each upper extremity are 9% each, the anterior trunk, posterior trunk, and each lower extremity are 18% each, and the perineum is 1%. This rapid estimation guides initial fluid resuscitation calculations and triage decisions. It is less accurate in children, where the Lund-Browder chart provides age-adjusted estimates.',
    difficulty: 1,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 157,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is blast lung injury, and how does it present?',
    answer: 'Blast lung results from a primary blast wave causing rapid compression and re-expansion of gas-filled structures. It presents with dyspnea, cough, hemoptysis, and chest tightness, typically within hours of exposure. Chest imaging shows bilateral infiltrates resembling a butterfly pattern. Pneumothorax and air embolism are associated complications. Mechanical ventilation should use low tidal volumes and cautious PEEP, as the damaged alveoli are susceptible to barotrauma.',
    difficulty: 3,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 158,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is fat embolism syndrome, and when does it typically occur?',
    answer: 'Fat embolism syndrome develops 24-72 hours after long bone fractures or orthopedic surgery when fat globules enter the venous circulation and lodge in the pulmonary vasculature. The classic triad is respiratory distress, neurological changes (confusion, agitation), and a petechial rash on the chest, axillae, and conjunctivae. Treatment is supportive with oxygen therapy, mechanical ventilation if needed, and careful fluid management.',
    difficulty: 2,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 159,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does ARDS in trauma patients differ from medical ARDS in terms of management considerations?',
    answer: 'Trauma-related ARDS often involves hemorrhagic shock, massive transfusion, and chest wall injury as contributing factors. Management must balance lung-protective ventilation with the potential need for permissive hypercapnia, which may be contraindicated in traumatic brain injury. Damage control resuscitation with balanced blood product ratios helps prevent transfusion-related lung injury. Chest wall injuries may require surgical fixation to optimize ventilation mechanics.',
    difficulty: 3,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 160,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the appropriate airway management strategy for a patient with suspected cervical spine injury?',
    answer: 'Manual in-line stabilization should be maintained during airway management, and the cervical collar may be temporarily opened with an assistant stabilizing the head. Video laryngoscopy is preferred over direct laryngoscopy as it requires less cervical spine movement. Fiberoptic intubation is an option in cooperative patients. Bag-mask ventilation with jaw thrust (avoiding head tilt) provides temporary oxygenation. The priority remains preventing secondary spinal cord injury while securing the airway.',
    difficulty: 2,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 161,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is a flail chest, and how does it impair ventilation?',
    answer: 'Flail chest occurs when three or more consecutive ribs are fractured in two or more places, creating a free-floating segment. This segment moves paradoxically: inward during inspiration and outward during expiration, reducing tidal volume. The underlying pulmonary contusion, rather than the mechanical paradox, is the primary cause of respiratory failure. Treatment includes pain management, positive pressure ventilation when indicated, and surgical fixation for refractory cases.',
    difficulty: 2,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 162,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What ventilator settings are appropriate for patients with severe inhalation injury?',
    answer: 'Initial settings should follow lung-protective strategies with tidal volumes of 6-8 mL/kg ideal body weight. Higher PEEP may be needed to maintain alveolar recruitment, and frequent suctioning is required to clear mucosal debris and casts. Bronchoscopy may be necessary for cast removal. Nebulized heparin, N-acetylcysteine, and bronchodilators have been used to reduce cast formation. Peak pressures should be monitored closely due to decreased compliance.',
    difficulty: 2,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 163,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is rhabdomyolysis, and why is it a concern in trauma and burn patients?',
    answer: 'Rhabdomyolysis is the breakdown of skeletal muscle releasing myoglobin, creatine kinase, and potassium into the bloodstream. It occurs from crush injuries, electrical burns, prolonged immobilization, or compartment syndrome. Myoglobin precipitates in renal tubules causing acute kidney injury, especially in acidic urine. Treatment involves aggressive IV fluid resuscitation to maintain urine output above 200-300 mL/hour and alkalinization of urine. Hyperkalemia may cause fatal arrhythmias.',
    difficulty: 2,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 164,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the lethal triad of trauma, and why is it significant?',
    answer: 'The lethal triad consists of hypothermia, acidosis, and coagulopathy. These three conditions create a self-reinforcing cycle: hypothermia impairs clotting factor activity, ongoing hemorrhage causes acidosis and further coagulopathy, and acidosis worsens both coagulopathy and cardiac function. Damage control resuscitation and surgery prioritize correcting these factors before definitive surgical repair. Warming measures, balanced transfusion, and minimizing crystalloid help break the cycle.',
    difficulty: 1,
    topic: 'Burns & Trauma ICU',
    isFree: false,
    orderIndex: 165,
  },

  // ============================================================
  // NEUROCRITICAL CARE (cards 166-180)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the cerebral perfusion pressure (CPP) target in traumatic brain injury?',
    answer: 'The recommended CPP target is 60-70 mmHg. CPP is calculated as mean arterial pressure minus intracranial pressure. Values below 60 mmHg risk cerebral ischemia, while aggressive attempts to raise CPP above 70 mmHg with vasopressors and fluids may increase the risk of ARDS and other systemic complications without improving neurological outcomes.',
    difficulty: 1,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 166,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'Why is routine prophylactic hyperventilation no longer recommended in traumatic brain injury?',
    answer: 'Hyperventilation reduces PaCO2, causing cerebral vasoconstriction that lowers intracranial pressure but also reduces cerebral blood flow. In the injured brain, this can worsen secondary ischemic injury, particularly in the first 24-48 hours when cerebral blood flow is already compromised. Brief hyperventilation (PaCO2 30-35 mmHg) is reserved for acute herniation as a temporizing measure while definitive treatment is arranged.',
    difficulty: 2,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 167,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the recommended ventilation targets for patients with severe traumatic brain injury?',
    answer: 'The target PaCO2 is 35-40 mmHg (normocarbia) to avoid the cerebral vasodilation caused by hypercapnia or the vasoconstriction and ischemia risk from hypocapnia. PaO2 should be maintained above 60 mmHg, and hypoxemia must be aggressively avoided as it worsens secondary brain injury. Head of bed elevation to 30 degrees facilitates venous drainage and reduces ICP.',
    difficulty: 1,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 168,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the Monro-Kellie doctrine, and how does it relate to intracranial pressure management?',
    answer: 'The Monro-Kellie doctrine states that the skull is a fixed-volume container holding brain tissue, cerebrospinal fluid, and blood. An increase in any one component must be offset by a decrease in another, or ICP will rise. This explains why interventions such as CSF drainage, osmotic therapy to reduce brain water, and controlled hyperventilation to reduce cerebral blood volume can lower ICP.',
    difficulty: 2,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 169,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What osmotic agents are used to treat elevated ICP, and how do they differ?',
    answer: 'Mannitol (20%, 0.25-1 g/kg) is an osmotic diuretic that creates an osmotic gradient drawing water from brain tissue into the vasculature. Hypertonic saline (3%, 23.4%) raises serum osmolality without causing diuresis, making it preferable in hypovolemic patients. Mannitol can cause hypotension from diuresis and must be held if serum osmolality exceeds 320 mOsm/kg. Hypertonic saline may cause hypernatremia and central pontine myelinolysis if sodium rises too rapidly.',
    difficulty: 3,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 170,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the respiratory consequences of high cervical spinal cord injury?',
    answer: 'Injury at C3-C5 disrupts phrenic nerve innervation, causing diaphragm paralysis and ventilator dependence. Injuries at C5-C8 preserve diaphragm function but impair intercostal and abdominal muscles, reducing cough effectiveness and vital capacity by 50-70%. Patients develop a paradoxical breathing pattern, retain secretions, and are prone to atelectasis and pneumonia. Vital capacity typically improves over weeks as spinal shock resolves.',
    difficulty: 2,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 171,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is status epilepticus, and how does it affect respiratory management?',
    answer: 'Status epilepticus is defined as continuous seizure activity lasting more than 5 minutes or two or more seizures without return to baseline consciousness. Prolonged seizures cause respiratory failure from airway obstruction, aspiration, increased oxygen consumption, respiratory muscle fatigue, and central apnea. Airway protection and intubation are often required. First-line treatment is benzodiazepines, followed by second-line anticonvulsants such as levetiracetam, fosphenytoin, or valproate.',
    difficulty: 2,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 172,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What airway considerations are specific to acute ischemic stroke management?',
    answer: 'Patients with large hemispheric or posterior fossa strokes may lose airway protective reflexes and require intubation. Bulbar dysfunction in brainstem strokes causes impaired swallowing and aspiration risk. Intubation should maintain normoxia and normocarbia to avoid worsening cerebral injury. Blood pressure management during intubation is critical since induced hypotension can extend the ischemic penumbra, while hypertension may increase hemorrhagic transformation risk after thrombolysis.',
    difficulty: 3,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 173,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is autonomic dysreflexia, and how does it relate to respiratory care?',
    answer: 'Autonomic dysreflexia occurs in patients with spinal cord injury at T6 or above when a noxious stimulus below the lesion triggers a massive sympathetic response. It presents with severe hypertension, bradycardia, flushing above the lesion, and headache. Suctioning, bladder distension from a blocked catheter, or fecal impaction are common triggers. During respiratory care, suctioning should be performed gently and briefly, and the stimulus should be removed immediately if symptoms develop.',
    difficulty: 3,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 174,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does Guillain-Barre syndrome affect respiratory function, and what monitoring is essential?',
    answer: 'Guillain-Barre syndrome causes ascending demyelinating polyneuropathy that can involve respiratory muscles in 20-30% of cases. Serial measurement of forced vital capacity (FVC) and negative inspiratory force (NIF) is essential. Intubation is typically indicated when FVC falls below 20 mL/kg, NIF is weaker than -30 cmH2O, or there is a rapid decline of more than 30% in either parameter. The 20/30/40 rule guides intervention decisions.',
    difficulty: 2,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 175,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the significance of the cushing triad in neurocritical care?',
    answer: 'The Cushing triad consists of hypertension, bradycardia, and irregular respirations. It indicates critically elevated intracranial pressure with brainstem compression and impending herniation. The hypertension is a reflex response to maintain cerebral perfusion against rising ICP, and the bradycardia results from vagal activation. This is a late and ominous sign requiring emergent intervention to reduce ICP.',
    difficulty: 1,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 176,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is neurogenic pulmonary edema, and when does it occur?',
    answer: 'Neurogenic pulmonary edema is a non-cardiogenic pulmonary edema that develops rapidly after acute brain injury, particularly subarachnoid hemorrhage, severe TBI, or status epilepticus. It results from a massive sympathetic surge causing transient systemic and pulmonary hypertension, increased capillary permeability, and fluid extravasation into alveoli. It typically resolves within 48-72 hours with supportive care including mechanical ventilation and management of the underlying neurological condition.',
    difficulty: 3,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 177,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the role of EEG monitoring in neurocritical care patients on mechanical ventilation?',
    answer: 'Continuous EEG monitoring detects nonconvulsive seizures, which occur in up to 20% of critically ill neurological patients and are clinically occult in sedated or paralyzed patients. It also monitors burst suppression depth during therapeutic barbiturate coma for refractory intracranial hypertension. EEG helps titrate anticonvulsant therapy and can provide prognostic information after cardiac arrest or severe brain injury.',
    difficulty: 2,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 178,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'How does myasthenic crisis differ from cholinergic crisis, and why does the distinction matter for respiratory management?',
    answer: 'Myasthenic crisis is an exacerbation of myasthenia gravis with worsening weakness and respiratory failure from insufficient acetylcholine receptor stimulation. Cholinergic crisis results from excessive anticholinesterase medication, causing muscarinic symptoms (salivation, lacrimation, bradycardia) alongside weakness. Both cause respiratory failure, but treatment differs: myasthenic crisis requires plasmapheresis or IVIG, while cholinergic crisis requires withholding anticholinesterase drugs. Edrophonium testing can help distinguish them.',
    difficulty: 3,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 179,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What ventilator weaning challenges are specific to neurocritical care patients?',
    answer: 'Neurocritical patients may have impaired respiratory drive from brainstem injury, reduced cough strength from bulbar dysfunction, inability to protect the airway despite adequate ventilatory mechanics, and fluctuating neurological status. Tracheostomy is commonly needed for prolonged ventilation. Weaning assessments must consider both ventilatory capacity and airway protection. A cuff leak test and swallowing evaluation should precede extubation in patients with bulbar weakness.',
    difficulty: 2,
    topic: 'Neurocritical Care',
    isFree: false,
    orderIndex: 180,
  },

  // ============================================================
  // ICU PROCEDURES & PROTOCOLS (cards 181-200)
  // ============================================================
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the indications for bronchoscopy in the ICU?',
    answer: 'ICU bronchoscopy is indicated for therapeutic and diagnostic purposes including removal of mucus plugs or retained secretions causing lobar collapse, evaluation of hemoptysis, directed bronchoalveolar lavage for microbiological diagnosis of suspected pneumonia, assessment of airway injury after inhalation or trauma, airway inspection after difficult intubation, guidance of percutaneous tracheostomy, and evaluation of persistent air leaks.',
    difficulty: 1,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 181,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What precautions are necessary when performing bronchoscopy on a mechanically ventilated patient?',
    answer: 'FiO2 should be increased to 100% before the procedure due to partial airway occlusion by the bronchoscope. The endotracheal tube must be at least 8.0 mm to accommodate a standard adult bronchoscope (5.7 mm) while maintaining adequate ventilation. PEEP may be temporarily adjusted, and sedation and paralysis are often required. Potential complications include hypoxemia, bronchospasm, arrhythmias, bleeding, and pneumothorax from transbronchial biopsy.',
    difficulty: 2,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 182,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is thoracentesis, and what are its indications in the ICU?',
    answer: 'Thoracentesis is the insertion of a needle into the pleural space to drain fluid. It is indicated for diagnostic sampling of new or unexplained pleural effusions and therapeutic drainage of large effusions causing respiratory compromise. Ultrasound guidance reduces the risk of pneumothorax. No more than 1000-1500 mL should be drained at once to avoid re-expansion pulmonary edema.',
    difficulty: 1,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 183,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the ventilator-associated pneumonia (VAP) prevention bundle?',
    answer: 'The VAP prevention bundle includes head of bed elevation to 30-45 degrees, daily sedation interruption and spontaneous breathing trials, oral care with chlorhexidine, peptic ulcer prophylaxis, deep vein thrombosis prophylaxis, and early mobilization. Additional measures include maintaining endotracheal tube cuff pressure at 20-30 cmH2O, using subglottic secretion drainage when available, and minimizing the duration of mechanical ventilation.',
    difficulty: 1,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 184,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the components of the central line-associated bloodstream infection (CLABSI) prevention bundle?',
    answer: 'The CLABSI prevention bundle includes hand hygiene, full barrier precautions during insertion (cap, mask, sterile gown, sterile gloves, large sterile drape), chlorhexidine skin antisepsis, optimal catheter site selection (subclavian preferred over femoral), and daily review of line necessity with prompt removal of unnecessary catheters. Standardized insertion checklists and empowering any team member to halt the procedure for breaks in sterile technique are essential components.',
    difficulty: 1,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 185,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the complications of central venous catheter insertion?',
    answer: 'Immediate complications include pneumothorax, hemothorax, arterial puncture, air embolism, arrhythmias from guidewire stimulation, and thoracic duct injury (left-sided insertions). Delayed complications include catheter-related bloodstream infection, venous thrombosis, catheter migration, and myocardial perforation. Ultrasound-guided insertion reduces mechanical complications. Post-insertion chest radiograph confirms position and rules out pneumothorax for subclavian and internal jugular placements.',
    difficulty: 2,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 186,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the ABCDEF bundle for ICU liberation?',
    answer: 'The ABCDEF bundle stands for: Assess, prevent, and manage pain; Both spontaneous awakening and breathing trials; Choice of analgesia and sedation; Delirium assessment, prevention, and management; Early mobility and exercise; and Family engagement and empowerment. This evidence-based approach reduces time on mechanical ventilation, ICU length of stay, delirium incidence, and mortality by addressing the most modifiable risk factors for poor ICU outcomes.',
    difficulty: 2,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 187,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What pharmacologic strategies are recommended for ICU delirium prevention and management?',
    answer: 'Prevention focuses on nonpharmacologic measures: sleep promotion, early mobilization, reorientation, and minimizing deliriogenic medications such as benzodiazepines and anticholinergics. Dexmedetomidine is preferred over benzodiazepines for sedation as it is associated with less delirium. For hyperactive delirium with agitation posing safety concerns, low-dose haloperidol or atypical antipsychotics may be used, though routine antipsychotic use has not been shown to reduce delirium duration.',
    difficulty: 2,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 188,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the benefits of early mobility programs in the ICU?',
    answer: 'Early mobility reduces the incidence and duration of delirium, decreases ventilator days, shortens ICU and hospital length of stay, and improves functional outcomes at discharge. Activities range from passive range of motion to ambulation with ventilator support. Safety screening should assess hemodynamic stability, adequate oxygenation, and absence of acute cardiovascular events. Collaboration between respiratory therapists, physical therapists, and nursing is essential.',
    difficulty: 1,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 189,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the current recommendations for glycemic control in critically ill patients?',
    answer: 'Current guidelines recommend targeting a blood glucose of 140-180 mg/dL using insulin infusion protocols. Tight glycemic control targeting 80-110 mg/dL is no longer recommended because landmark trials demonstrated increased hypoglycemia and mortality without benefit. Hypoglycemia is an independent predictor of mortality in ICU patients. Blood glucose monitoring should occur at least every 1-2 hours during insulin infusion, using arterial blood samples when possible as capillary values are less reliable in shock.',
    difficulty: 2,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 190,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the recommended approach to nutrition in critically ill patients?',
    answer: 'Early enteral nutrition, initiated within 24-48 hours of ICU admission, is preferred over parenteral nutrition. It maintains gut mucosal integrity, reduces infectious complications, and supports immune function. Caloric targets are typically 25-30 kcal/kg/day with 1.2-2.0 g/kg/day of protein. Gastric residual volume monitoring is no longer routinely recommended. Parenteral nutrition is reserved for patients who cannot tolerate enteral feeding for 7 or more days.',
    difficulty: 2,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 191,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is paracentesis, and what respiratory improvement can it provide?',
    answer: 'Paracentesis is the percutaneous drainage of ascitic fluid from the peritoneal cavity. Large-volume ascites restricts diaphragm excursion and impairs respiratory mechanics. Therapeutic paracentesis can improve tidal volume, vital capacity, and oxygenation by reducing intra-abdominal pressure and allowing the diaphragm to descend normally. Large-volume removal (greater than 5 liters) typically requires albumin infusion (6-8 g per liter removed) to prevent circulatory dysfunction.',
    difficulty: 2,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 192,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the role of point-of-care ultrasound in ICU respiratory assessment?',
    answer: 'Point-of-care ultrasound enables rapid bedside assessment of pleural effusions, pneumothorax (absence of lung sliding), lung consolidation, interstitial syndrome (B-lines), diaphragm function, and cardiac filling status. It is superior to supine chest radiograph for detecting pleural fluid and pneumothorax. It guides procedural interventions such as thoracentesis and chest tube placement and can assess fluid responsiveness through cardiac and IVC evaluation.',
    difficulty: 1,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 193,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the difference between open and closed endotracheal suctioning systems?',
    answer: 'Open suctioning requires disconnecting the patient from the ventilator, inserting a sterile catheter, and applying suction during withdrawal. Closed (in-line) suctioning uses a catheter enclosed in a sterile sheath that remains connected to the ventilator circuit. Closed suctioning maintains PEEP, reduces desaturation and loss of lung volume, decreases environmental contamination, and is preferred for patients requiring high PEEP or FiO2, or those with airborne infections.',
    difficulty: 1,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 194,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the recommended approach to stress ulcer prophylaxis in ICU patients?',
    answer: 'Stress ulcer prophylaxis is indicated for patients at high risk, including those on mechanical ventilation for more than 48 hours and those with coagulopathy. Proton pump inhibitors and histamine-2 receptor antagonists are both effective. However, routine prophylaxis in low-risk patients is discouraged because acid suppression may increase the risk of Clostridioides difficile infection and ventilator-associated pneumonia by allowing bacterial overgrowth in the alkalinized stomach.',
    difficulty: 2,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 195,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is intra-abdominal hypertension, and how does it affect respiratory function?',
    answer: 'Intra-abdominal hypertension is defined as sustained intra-abdominal pressure above 12 mmHg. It impairs respiratory function by pushing the diaphragm cephalad, reducing lung volumes and compliance, and increasing airway pressures. Abdominal compartment syndrome (pressure above 20 mmHg with organ dysfunction) may require surgical decompression. Ventilator management should account for the elevated pleural pressure when interpreting plateau pressure and setting PEEP.',
    difficulty: 3,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 196,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the key elements of an ICU handoff communication tool such as I-PASS?',
    answer: 'I-PASS stands for: Illness severity (stable, watcher, or unstable), Patient summary (brief clinical synopsis), Action list (to-do items and timeline), Situation awareness and contingency planning (what to watch for and what to do if conditions change), and Synthesis by receiver (read-back to confirm understanding). Standardized handoff tools reduce communication failures, which are the leading cause of sentinel events in healthcare.',
    difficulty: 1,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 197,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What is the process and timing for percutaneous dilational tracheostomy in ICU patients?',
    answer: 'Percutaneous dilational tracheostomy is typically performed at the bedside between tracheal rings 1-3 using the Seldinger technique under bronchoscopic guidance. Current evidence suggests performing tracheostomy when prolonged mechanical ventilation beyond 10-14 days is anticipated. Benefits include improved patient comfort, reduced sedation requirements, facilitated oral care and communication, easier suctioning, and lower airway resistance. Complications include bleeding, false passage, posterior tracheal wall injury, and subcutaneous emphysema.',
    difficulty: 3,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 198,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What sleep promotion strategies should be implemented in the ICU?',
    answer: 'Strategies include clustering care activities to allow uninterrupted rest periods, reducing nighttime light and noise levels, maintaining a consistent day-night cycle, minimizing nighttime vital sign checks when clinically appropriate, using earplugs and eye masks, avoiding deliriogenic medications at bedtime, and optimizing ventilator settings for patient comfort. Sleep deprivation contributes to delirium, impairs immune function, and delays recovery.',
    difficulty: 1,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 199,
  },
  {
    divisionId: ACCS_DIVISION_ID,
    question: 'What are the indications and contraindications for prone positioning a non-ARDS patient in the ICU?',
    answer: 'Beyond ARDS, prone positioning may benefit patients with refractory hypoxemia from severe pneumonia, post-surgical atelectasis, or obesity-related respiratory failure by improving dorsal lung recruitment and ventilation-perfusion matching. Contraindications include spinal instability, open abdominal wounds, facial or pelvic fractures, hemodynamic instability requiring active resuscitation, and elevated intracranial pressure without ICP monitoring. Recent sternotomy is a relative contraindication requiring case-by-case evaluation.',
    difficulty: 3,
    topic: 'ICU Procedures & Protocols',
    isFree: false,
    orderIndex: 200,
  },
]

async function main() {
  console.log('Seeding ACCS Batch 2 flashcards (101-200)...')

  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })

  console.log(`Created ${result.count} flashcards.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
