import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const CPFT_DIVISION_ID = 'cmsm41fxw0004zf54sy6um2ui'

const flashcards = [
  // ============================================================
  // SPIROMETRY FUNDAMENTALS (cards 1-20)
  // ============================================================
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What does FVC stand for, and what does it measure?',
    answer: 'Forced Vital Capacity. It is the total volume of air that can be forcefully exhaled after a maximal inspiration. FVC reflects lung size and the ability to move air out of the lungs and is measured in liters.',
    difficulty: 1,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 1,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What does FEV1 represent, and why is it clinically important?',
    answer: 'Forced Expiratory Volume in one second is the volume of air exhaled during the first second of an FVC maneuver. It is the single most reproducible and clinically useful spirometric measurement, reflecting large and medium airway function.',
    difficulty: 1,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 2,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the normal range for the FEV1/FVC ratio in healthy adults?',
    answer: 'In healthy younger adults the FEV1/FVC ratio is typically 0.75 to 0.85 (75-85%). The ratio declines naturally with age due to loss of elastic recoil. A ratio below the lower limit of normal for the patient\'s age, sex, height, and ethnicity suggests airflow obstruction.',
    difficulty: 1,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 3,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What does FEF25-75% measure, and what is its clinical limitation?',
    answer: 'The Forced Expiratory Flow between 25% and 75% of FVC (also called mid-expiratory flow) reflects flow in the small to medium airways. Its main limitation is high variability between efforts and between individuals, which makes it less reliable as a standalone diagnostic parameter.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 4,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is Peak Expiratory Flow (PEF), and when during the FVC maneuver does it occur?',
    answer: 'PEF is the highest instantaneous flow rate achieved during a forced expiration. It typically occurs within the first 100-150 milliseconds of the maneuver and is largely effort-dependent, reflecting large airway caliber and expiratory muscle strength.',
    difficulty: 1,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 5,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'According to ATS/ERS standards, what are the acceptability criteria for the start of a forced expiratory maneuver?',
    answer: 'The back-extrapolated volume (BEV) must be less than 5% of the FVC or 100 mL, whichever is greater. This ensures the patient began the forced effort with a sharp, rapid start without hesitation. A large BEV indicates a slow or delayed onset of forced exhalation.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 6,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What are the ATS/ERS end-of-test criteria for an acceptable FVC maneuver?',
    answer: 'The patient must exhale for at least 6 seconds (3 seconds for children under 10), or reach a plateau in the volume-time curve (no change in volume greater than 25 mL for at least 1 second). The technologist should encourage exhalation up to a maximum of 15 seconds.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 7,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What are the ATS/ERS repeatability (reproducibility) criteria for FVC and FEV1?',
    answer: 'The two largest acceptable FVC values must be within 150 mL of each other, and the two largest acceptable FEV1 values must also be within 150 mL. If the FVC is 1.0 L or less, the threshold is 100 mL instead of 150 mL.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 8,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How many acceptable FVC maneuvers must a patient perform, and what is the maximum recommended number of attempts?',
    answer: 'A minimum of three acceptable maneuvers is required. Testing should continue until repeatability criteria are met, up to a maximum of eight attempts. Exceeding eight efforts increases fatigue and rarely improves data quality.',
    difficulty: 1,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 9,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is back-extrapolation in spirometry, and why is it used?',
    answer: 'Back-extrapolation is a method to determine the true time-zero of forced expiration by extending the steepest portion of the volume-time curve back to the x-axis. It corrects for hesitation at the start and defines the point from which FEV1 timing begins, ensuring accurate measurement.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 10,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What within-maneuver criteria must be met for an individual FVC effort to be considered acceptable?',
    answer: 'An acceptable effort must be free of artifacts such as coughing (especially in the first second), glottis closure, early termination, submaximal effort, air leak around the mouthpiece, and obstruction of the mouthpiece by the tongue or teeth.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 11,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How should the best FVC and FEV1 values be selected from multiple acceptable maneuvers?',
    answer: 'The largest FVC and the largest FEV1 are selected from any acceptable maneuvers, even if they come from different efforts. These values do not need to originate from the same maneuver since each parameter is independently at its physiologic maximum.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 12,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is a flow-volume loop, and what are its two axes?',
    answer: 'A flow-volume loop is a graphical representation of airflow plotted against lung volume during both forced expiration and inspiration. The x-axis shows volume (liters), and the y-axis shows flow rate (liters per second). Expiratory flow is plotted above the x-axis and inspiratory flow below.',
    difficulty: 1,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 13,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What does a scooped or concave expiratory limb on a flow-volume loop indicate?',
    answer: 'A concave (scooped) appearance of the descending expiratory limb suggests airflow obstruction. The characteristic scoop reflects disproportionate flow reduction at lower lung volumes due to dynamic airway compression and is commonly seen in COPD and asthma.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 14,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is Slow Vital Capacity (SVC), and when might it be larger than FVC?',
    answer: 'SVC is the maximum volume of air exhaled slowly from full inspiration to full expiration without forced effort. In patients with airflow obstruction, SVC may exceed FVC because the slow maneuver avoids dynamic airway compression and premature airway closure that occurs during forced exhalation.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 15,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What information does the volume-time curve provide that the flow-volume loop may not readily show?',
    answer: 'The volume-time curve clearly demonstrates exhalation duration, making it easier to assess whether end-of-test criteria (plateau or minimum exhalation time) have been met. It also helps identify early termination of effort, which is harder to detect on a flow-volume loop.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 16,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What patient instructions should a technologist provide before performing spirometry?',
    answer: 'The technologist should explain the test purpose, demonstrate the maneuver, instruct the patient to sit upright with feet flat, apply a nose clip, seal lips tightly around the mouthpiece, inhale maximally, and then blast the air out as hard and fast as possible and keep blowing until told to stop.',
    difficulty: 1,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 17,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Why should dentures generally be left in place during spirometry testing?',
    answer: 'Dentures help maintain the structural support of the cheeks and lips around the mouthpiece, providing a better seal. Removing dentures can lead to air leaks and difficulty maintaining mouth position. However, loose-fitting dentures that could dislodge should be removed for safety.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 18,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the purpose of the nose clip during spirometry?',
    answer: 'A nose clip prevents air from escaping through the nose during the forced maneuver, ensuring that all exhaled volume passes through the mouthpiece and is measured by the spirometer. Although some protocols allow testing without a nose clip for FVC maneuvers, it is recommended by ATS/ERS.',
    difficulty: 1,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 19,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does a cough during the first second of a forced expiratory maneuver affect the acceptability of the test?',
    answer: 'A cough in the first second makes the maneuver unacceptable because it artificially inflates the measured flow and volume during that critical period, resulting in an inaccurate FEV1. Coughs occurring later in the maneuver may not necessarily invalidate the effort but should be documented.',
    difficulty: 2,
    topic: 'Spirometry Fundamentals',
    isFree: true,
    orderIndex: 20,
  },

  // ============================================================
  // LUNG VOLUMES (cards 21-35)
  // ============================================================
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is Total Lung Capacity (TLC), and what lung volumes and capacities compose it?',
    answer: 'TLC is the total amount of air in the lungs after a maximal inspiration. It equals the sum of all four lung volumes: tidal volume (VT) + inspiratory reserve volume (IRV) + expiratory reserve volume (ERV) + residual volume (RV). Alternatively, TLC = VC + RV.',
    difficulty: 1,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 21,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is Residual Volume (RV), and why can it not be measured by spirometry?',
    answer: 'RV is the volume of air remaining in the lungs after a maximal exhalation. Spirometry can only measure air that moves in and out of the lungs, so RV (which stays trapped) requires indirect methods such as body plethysmography, helium dilution, or nitrogen washout.',
    difficulty: 1,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 22,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is Functional Residual Capacity (FRC), and what is its physiologic significance?',
    answer: 'FRC is the volume of air remaining in the lungs at the end of a normal tidal exhalation. It equals ERV + RV. Physiologically, FRC represents the equilibrium point where the inward elastic recoil of the lungs balances the outward recoil of the chest wall.',
    difficulty: 2,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 23,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is Expiratory Reserve Volume (ERV)?',
    answer: 'ERV is the maximum volume of air that can be exhaled from the end-expiratory level (the resting FRC position) down to the residual volume. It is typically about 1.0-1.2 liters in healthy adults. Obesity and pregnancy reduce ERV due to upward displacement of the diaphragm.',
    difficulty: 1,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 24,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is Inspiratory Capacity (IC), and what volumes does it include?',
    answer: 'IC is the maximum volume of air that can be inhaled from the end of a normal tidal exhalation to full inspiration. It equals the tidal volume plus the inspiratory reserve volume (IC = VT + IRV). IC can be measured with simple spirometry.',
    difficulty: 1,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 25,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does the helium dilution technique measure FRC?',
    answer: 'The patient breathes from a closed circuit containing a known concentration and volume of helium. Since helium is inert and not absorbed, it equilibrates between the spirometer and the lungs. FRC is calculated from the dilution equation: FRC = V1 x (C1 - C2) / C2, where V1 is the initial system volume, C1 is the initial helium concentration, and C2 is the final equilibrated concentration.',
    difficulty: 3,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 26,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does the nitrogen washout technique measure FRC?',
    answer: 'The patient breathes 100% oxygen while exhaled nitrogen concentration is monitored. As nitrogen is washed out of the lungs, the total volume of nitrogen collected is measured. FRC is calculated by dividing the total collected nitrogen volume by the initial alveolar nitrogen concentration (approximately 0.79). The test ends when exhaled nitrogen falls below 1.5%.',
    difficulty: 3,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 27,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does body plethysmography measure thoracic gas volume, and what principle does it rely on?',
    answer: 'The patient sits in a sealed chamber (body box) and pants against a closed shutter at FRC. Body plethysmography applies Boyle\'s law (P1V1 = P2V2): as the patient compresses and decompresses thoracic gas, changes in mouth pressure and box pressure are used to calculate the volume of gas in the thorax, including trapped gas.',
    difficulty: 3,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 28,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Why might body plethysmography yield a higher FRC than helium dilution or nitrogen washout?',
    answer: 'Body plethysmography measures all compressible gas in the thorax, including trapped gas in poorly ventilated or non-communicating regions. Gas dilution and washout methods only measure gas that communicates with the airways during the test period, underestimating FRC in patients with significant air trapping.',
    difficulty: 3,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 29,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is gas trapping, and how is it detected using lung volume measurements?',
    answer: 'Gas trapping occurs when air remains in the lungs due to premature airway closure during exhalation. It is detected by comparing plethysmographic lung volumes to gas dilution volumes: a significantly higher TLC by plethysmography than by dilution indicates trapped gas. An elevated RV/TLC ratio also suggests gas trapping.',
    difficulty: 3,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 30,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the normal RV/TLC ratio, and what does an elevated value indicate?',
    answer: 'The normal RV/TLC ratio is approximately 20-35% in young adults and increases with age. An elevated RV/TLC ratio indicates air trapping and hyperinflation, which is a hallmark of obstructive lung diseases like COPD and emphysema.',
    difficulty: 1,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 31,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How are lung volumes affected in a patient with restrictive lung disease?',
    answer: 'In restrictive disease, all lung volumes and capacities are proportionally reduced. The hallmark finding is a reduced TLC (below the lower limit of normal). FRC, RV, VC, and IC are also decreased. The RV/TLC ratio may be normal or mildly elevated.',
    difficulty: 1,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 32,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How are lung volumes typically altered in emphysema?',
    answer: 'Emphysema causes increased TLC, increased RV, increased FRC, and a markedly elevated RV/TLC ratio due to destruction of alveolar walls and loss of elastic recoil. The lungs become hyperinflated because they cannot adequately empty, trapping gas at all lung volume levels.',
    difficulty: 1,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 33,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is Vital Capacity (VC), and what is the relationship between VC, TLC, and RV?',
    answer: 'Vital Capacity is the maximum volume of air that can be exhaled after a maximum inhalation (VC = TLC - RV). It encompasses tidal volume, inspiratory reserve volume, and expiratory reserve volume. VC can be measured by spirometry as either a slow or forced maneuver.',
    difficulty: 1,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 34,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is Inspiratory Reserve Volume (IRV), and how is it affected by hyperinflation?',
    answer: 'IRV is the additional volume of air that can be inhaled beyond a normal tidal inspiration. In hyperinflated patients (such as those with COPD), FRC increases, shifting tidal breathing closer to TLC. This compresses IRV and IC, contributing to dyspnea because the patient has less room to increase tidal volume.',
    difficulty: 2,
    topic: 'Lung Volumes',
    isFree: false,
    orderIndex: 35,
  },

  // ============================================================
  // DIFFUSION CAPACITY (cards 36-50)
  // ============================================================
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What does the DLCO test measure?',
    answer: 'The Diffusing Capacity of the Lung for Carbon Monoxide (DLCO) measures the ability of the lungs to transfer gas from inhaled air to the red blood cells in pulmonary capillaries. It reflects the integrity of the alveolar-capillary membrane and the pulmonary capillary blood volume.',
    difficulty: 1,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 36,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Describe the single-breath DLCO technique step by step.',
    answer: 'The patient exhales to residual volume, then rapidly inhales a test gas mixture (containing 0.3% CO, a tracer gas such as helium or methane, 21% O2, and balance N2) to near TLC. The breath is held for approximately 10 seconds, then the patient exhales. The initial portion of exhaled gas is discarded (dead space washout), and an alveolar sample is collected and analyzed for CO and tracer gas concentrations.',
    difficulty: 2,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 37,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the required breath-hold time for a standard single-breath DLCO test?',
    answer: 'The standard breath-hold time is 10 seconds, measured using the Jones-Meade method (from the beginning of inspiration to the beginning of alveolar sample collection). Acceptable range is 8 to 12 seconds. Breath-hold times outside this range may require the maneuver to be repeated.',
    difficulty: 2,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 38,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What minimum inspired volume (VI) is required for an acceptable DLCO maneuver?',
    answer: 'The inspired volume must be at least 85% of the largest known vital capacity (VC or FVC). An inadequate inspired volume leads to undersampling of lung units and underestimation of DLCO because fewer alveoli participate in gas exchange during the test.',
    difficulty: 2,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 39,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Why must DLCO be adjusted for hemoglobin concentration?',
    answer: 'CO uptake depends on hemoglobin binding in the pulmonary capillaries. Anemia reduces the available hemoglobin for CO binding, causing a falsely low DLCO, while polycythemia increases available binding sites, elevating DLCO. Adjusting to a standard hemoglobin (14.6 g/dL for males, 13.4 g/dL for females) isolates the membrane diffusion component.',
    difficulty: 2,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 40,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does elevated carboxyhemoglobin (COHb) affect DLCO, and how is it corrected?',
    answer: 'Elevated COHb reduces the pressure gradient for CO diffusion because CO already bound to hemoglobin competes with test gas CO. Smokers or patients with recent CO exposure will have falsely low DLCO values. Correction formulas reduce the predicted DLCO proportionally to the measured COHb level. Patients should refrain from smoking for at least 4 hours before testing.',
    difficulty: 3,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 41,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does altitude affect DLCO measurements, and why?',
    answer: 'At higher altitudes, the reduced partial pressure of oxygen leads to increased CO uptake (higher uncorrected DLCO) due to less competition between O2 and CO for hemoglobin binding sites. A correction factor is applied based on the barometric pressure at the testing altitude to standardize results.',
    difficulty: 3,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 42,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Name three conditions that decrease DLCO and three that increase it.',
    answer: 'Decreased DLCO: emphysema (alveolar destruction reduces surface area), interstitial lung disease (thickened alveolar-capillary membrane), and pulmonary embolism (loss of perfused capillary bed). Increased DLCO: pulmonary hemorrhage (alveolar hemoglobin absorbs extra CO), polycythemia (more capillary hemoglobin binds CO), and left-to-right intracardiac shunts (increased pulmonary blood flow).',
    difficulty: 2,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 43,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does exercise affect DLCO?',
    answer: 'During exercise, cardiac output increases, recruiting and distending pulmonary capillaries. This increases the effective surface area for gas exchange and the pulmonary capillary blood volume, resulting in a higher measured DLCO. This is why patients should rest before DLCO testing.',
    difficulty: 3,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 44,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the role of the tracer gas (helium or methane) in the DLCO test?',
    answer: 'The tracer gas is inert and does not cross the alveolar-capillary membrane. By measuring the dilution of the tracer gas in the exhaled sample, the alveolar volume (VA) can be calculated. This also allows calculation of the initial alveolar CO concentration, which is essential for determining the rate of CO uptake.',
    difficulty: 3,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 45,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the KCO (DLCO/VA), and when is it useful?',
    answer: 'KCO is the transfer coefficient obtained by dividing DLCO by alveolar volume (VA). It represents diffusion efficiency per unit of lung volume. It is useful when DLCO is reduced due to decreased lung volume (such as after pneumonectomy) rather than intrinsic membrane disease. In pneumonectomy, KCO is typically normal despite a low DLCO.',
    difficulty: 3,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 46,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What time interval must elapse between successive DLCO maneuvers, and why?',
    answer: 'A minimum of 4 minutes must elapse between successive DLCO maneuvers to allow washout of the test gas from the lungs. Residual CO in the alveoli would reduce the driving pressure gradient for subsequent tests, leading to falsely lower DLCO measurements.',
    difficulty: 2,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 47,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What DLCO repeatability criteria should be met between acceptable maneuvers?',
    answer: 'Two acceptable DLCO measurements should agree within 2 mL CO/min/mmHg (or within 10% of each other, depending on the standard used). If they do not agree, additional maneuvers should be performed up to a maximum of five, with adequate washout time between each attempt.',
    difficulty: 3,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 48,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Why is the Valsalva maneuver during the breath-hold problematic for DLCO measurement?',
    answer: 'A Valsalva maneuver increases intrathoracic pressure, which compresses the pulmonary capillaries and reduces their blood volume. This decreases the surface area available for gas exchange and lowers the measured DLCO. Conversely, a Mueller maneuver (inspiratory effort against a closed glottis) increases capillary blood volume and raises DLCO.',
    difficulty: 3,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 49,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What supplemental oxygen consideration applies to DLCO testing?',
    answer: 'Patients on supplemental oxygen should have it discontinued prior to testing (typically at least 10 minutes) because elevated alveolar PO2 competes with CO for hemoglobin binding sites, reducing CO uptake and causing a falsely low DLCO. The patient\'s oxygen saturation should be monitored for safety during the discontinuation period.',
    difficulty: 3,
    topic: 'Diffusion Capacity',
    isFree: false,
    orderIndex: 50,
  },

  // ============================================================
  // EQUIPMENT & QUALITY CONTROL (cards 51-65)
  // ============================================================
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What are the two main categories of spirometers based on measurement principle?',
    answer: 'Volume-displacement spirometers (such as water-sealed, dry rolling-seal, and bellows types) directly measure volume changes. Flow-sensing spirometers (such as pneumotachometers, turbine sensors, and ultrasonic sensors) measure flow and derive volume by mathematical integration over time.',
    difficulty: 1,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 51,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does a Fleisch-type pneumotachometer measure airflow?',
    answer: 'A Fleisch pneumotachometer uses a bundle of small parallel capillary tubes that create a small resistance to airflow. The pressure drop across this resistance is proportional to flow (based on the Poiseuille equation). Differential pressure transducers measure this pressure drop and convert it to a flow signal.',
    difficulty: 2,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 52,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the standard calibration syringe volume used for spirometer verification, and how is it used?',
    answer: 'A 3-liter calibration syringe is used. The syringe is discharged into the spirometer at least three times at varied flow rates (low, medium, and high). The spirometer must read within plus or minus 3.5% of the known 3-liter volume (between 2.895 and 3.105 liters) to pass calibration verification.',
    difficulty: 1,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 53,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How often must spirometer calibration verification be performed according to ATS/ERS standards?',
    answer: 'Calibration verification with a 3-liter syringe must be performed daily, before patient testing begins. Volume accuracy must be within 3.5%. If the spirometer fails verification, it must not be used for patient testing until the issue is resolved and verification passes.',
    difficulty: 1,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 54,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is a biological control in pulmonary function testing?',
    answer: 'A biological control is a healthy, non-smoking laboratory staff member who performs periodic testing on the equipment under standardized conditions. Their results are tracked over time to detect instrument drift or systematic errors that calibration verification alone may not reveal. Results outside two standard deviations of their mean should trigger investigation.',
    difficulty: 2,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 55,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is linearity testing for a spirometer, and how is it performed?',
    answer: 'Linearity testing verifies that the spirometer measures accurately across its full range of volumes, not just at one calibration point. A calibrating syringe is injected in incremental volumes (e.g., 1L, 2L, 3L) and at different flow rates. The spirometer must maintain accuracy within 3.5% across all tested volumes and flows.',
    difficulty: 3,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 56,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How is a leak test performed on a volume-displacement spirometer?',
    answer: 'A constant positive pressure (at least 3 cmH2O) is applied to the spirometer with all ports sealed. Volume loss is monitored over at least one minute. The leak must not exceed 30 mL per minute. Any greater leak requires repair before the device can be used for patient testing.',
    difficulty: 2,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 57,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is BTPS correction, and why is it necessary in pulmonary function testing?',
    answer: 'BTPS stands for Body Temperature (37 degrees C), ambient Pressure, and Saturated with water vapor. Exhaled gas cools as it enters the spirometer, causing the volume to decrease. BTPS correction adjusts measured volumes to body conditions so results reflect actual lung volumes. Without correction, volumes would be underestimated by approximately 5-10%.',
    difficulty: 2,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 58,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What factors are needed to calculate the BTPS correction factor?',
    answer: 'Three factors are required: the ambient temperature of the gas in the spirometer (to determine the water vapor pressure at that temperature), the barometric pressure, and the assumption that body temperature is 37 degrees C with the gas fully saturated (water vapor pressure of 47 mmHg). The correction factor = (310 / (273 + T)) x ((PB - PH2O at T) / (PB - 47)).',
    difficulty: 3,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 59,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What minimum volume and flow accuracy specifications are required for diagnostic spirometers per ATS/ERS?',
    answer: 'Volume accuracy must be within plus or minus 3.5% or 65 mL (whichever is greater) over a range of 0.5 to 8 liters. Flow accuracy must be within plus or minus 5% or 0.200 L/s (whichever is greater) over a range of up to 14 L/s. Time resolution must be 10 milliseconds or better.',
    difficulty: 3,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 60,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What infection control practices should be followed between patients during spirometry testing?',
    answer: 'Single-use disposable mouthpieces and in-line bacterial/viral filters should be used for each patient. Tubing and sensors should be cleaned or replaced per manufacturer guidelines. The spirometer surfaces should be disinfected between patients. Staff should follow standard precautions including hand hygiene and glove use when indicated.',
    difficulty: 1,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 61,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does condensation affect pneumotachometer accuracy, and how is it prevented?',
    answer: 'Condensation from warm exhaled air on the cooler pneumotachometer element narrows the capillary tubes, increasing resistance and causing erroneously high flow readings. This is prevented by heating the pneumotachometer to body temperature (37 degrees C) or slightly above, which keeps moisture from condensing on the flow sensor.',
    difficulty: 3,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 62,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the purpose of the DLCO gas analyzer, and what gases does it measure?',
    answer: 'The DLCO gas analyzer measures the concentrations of carbon monoxide (CO) and the tracer gas (helium or methane) in both the inspired and expired gas samples. CO is typically measured with an infrared analyzer or electrochemical cell, while helium is measured with a thermal conductivity analyzer and methane with an infrared analyzer.',
    difficulty: 2,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 63,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What quality control procedures are specific to body plethysmography equipment?',
    answer: 'The body box requires daily calibration of the box pressure transducer and mouth pressure transducer using known reference pressures. A leak test of the sealed chamber should be performed. The door seal must be verified for integrity. The isothermal conditions inside the box should be confirmed, and biological controls should be run periodically.',
    difficulty: 3,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 64,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the difference between calibration and calibration verification?',
    answer: 'Calibration is the process of adjusting the instrument to match a known standard (physically modifying the instrument\'s output). Calibration verification is the process of checking the instrument\'s accuracy against a known standard without making adjustments. Daily checks with a 3-liter syringe are calibration verification, not calibration.',
    difficulty: 2,
    topic: 'Equipment & Quality Control',
    isFree: false,
    orderIndex: 65,
  },

  // ============================================================
  // BRONCHODILATOR RESPONSE (cards 66-80)
  // ============================================================
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the standard protocol for pre- and post-bronchodilator spirometry testing?',
    answer: 'Baseline (pre-bronchodilator) spirometry is performed first. Then a short-acting bronchodilator (typically albuterol 400 mcg via MDI with spacer) is administered. Post-bronchodilator spirometry is performed after a waiting period of 10-15 minutes for short-acting beta-agonists or 30 minutes for short-acting anticholinergics.',
    difficulty: 1,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 66,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What defines a significant (positive) bronchodilator response for FEV1 or FVC?',
    answer: 'A significant response is defined as an increase of both 12% AND 200 mL above the pre-bronchodilator value for either FEV1 or FVC. Both thresholds must be met simultaneously. This dual criterion prevents small percentage changes in patients with very low baseline values from being considered significant.',
    difficulty: 1,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 67,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Why is it important to withhold bronchodilator medications before pulmonary function testing?',
    answer: 'Withholding bronchodilators allows measurement of the patient\'s baseline airway caliber without the masking effect of medication. This is essential for detecting the true degree of airflow limitation and for assessing bronchodilator responsiveness. Testing while medicated may underestimate the severity of obstruction.',
    difficulty: 1,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 68,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How long should short-acting beta-agonists (such as albuterol) be withheld before baseline spirometry?',
    answer: 'Short-acting beta-agonists (SABAs) should be withheld for at least 4-6 hours before baseline testing. This allows the medication\'s bronchodilator effect to wear off so the baseline measurement reflects the patient\'s underlying airway caliber.',
    difficulty: 1,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 69,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How long should long-acting beta-agonists (LABAs) be withheld before baseline spirometry?',
    answer: 'Long-acting beta-agonists such as salmeterol and formoterol should be withheld for at least 12 hours before testing. Ultra-long-acting agents such as indacaterol, vilanterol, and olodaterol should be withheld for at least 24 hours due to their extended duration of action.',
    difficulty: 2,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 70,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How long should short-acting anticholinergics (such as ipratropium) be withheld before testing?',
    answer: 'Short-acting anticholinergics should be withheld for at least 12 hours before baseline testing. Their duration of action is longer than SABAs (6-8 hours), so a 12-hour washout period is needed to ensure the medication effect has fully dissipated.',
    difficulty: 2,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 71,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How long should long-acting anticholinergics (such as tiotropium) be withheld before baseline spirometry?',
    answer: 'Long-acting anticholinergics (LAMAs) such as tiotropium, umeclidinium, and glycopyrrolate should be withheld for at least 24-48 hours before baseline testing due to their very long duration of action (24 hours or more).',
    difficulty: 2,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 72,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Can a patient with no bronchodilator response still have asthma?',
    answer: 'Yes. A negative bronchodilator response on a single test does not rule out asthma. Bronchodilator responsiveness can vary day to day, and some asthma patients may not show significant reversibility if their airways are not significantly constricted at the time of testing. Serial testing, bronchoprovocation challenge, or clinical response to a treatment trial may be needed.',
    difficulty: 3,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 73,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Does a significant bronchodilator response definitively distinguish asthma from COPD?',
    answer: 'No. While significant bronchodilator responsiveness is more characteristic of asthma, many COPD patients also demonstrate significant bronchodilator responses. Up to 50% of stable COPD patients may show a positive response on any given test day. Bronchodilator testing alone cannot differentiate asthma from COPD.',
    difficulty: 3,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 74,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How is the percent change in FEV1 after bronchodilator calculated?',
    answer: 'Percent change = ((Post-BD FEV1 - Pre-BD FEV1) / Pre-BD FEV1) x 100. For example, if pre-BD FEV1 is 2.00 L and post-BD FEV1 is 2.30 L, the percent change is ((2.30 - 2.00) / 2.00) x 100 = 15%. The absolute change would be 300 mL. Both the 12% and 200 mL criteria are met in this example.',
    difficulty: 3,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 75,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What dose of albuterol is typically administered for bronchodilator response testing?',
    answer: 'The standard dose is 400 mcg (4 puffs of 100 mcg each) of albuterol delivered via metered-dose inhaler with a spacer device. Each puff should be inhaled separately with a 30-second interval between puffs. A spacer improves medication delivery to the lower airways.',
    difficulty: 1,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 76,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Should the same quality and acceptability criteria apply to post-bronchodilator spirometry as to pre-bronchodilator spirometry?',
    answer: 'Yes. The same ATS/ERS acceptability and repeatability criteria must be applied to both pre- and post-bronchodilator maneuvers. At least three acceptable maneuvers meeting reproducibility criteria are required for each phase. Relaxing standards for post-bronchodilator testing would compromise data reliability.',
    difficulty: 1,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 77,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What should a technologist do if a patient uses their rescue inhaler shortly before arriving for PFT testing?',
    answer: 'The technologist should document the medication used, the time it was taken, and the number of puffs. Depending on laboratory protocol and the ordering physician\'s intent, testing may proceed as post-bronchodilator only, be rescheduled, or proceed with documentation of the recent bronchodilator use in the report.',
    difficulty: 3,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 78,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What potential side effects of inhaled bronchodilator should a PFT technologist monitor for during testing?',
    answer: 'The technologist should watch for tachycardia, palpitations, tremor, headache, nervousness, and dizziness. In rare cases, paradoxical bronchospasm can occur. The patient\'s heart rate should be checked before and after bronchodilator administration, and the test should be postponed if the resting heart rate exceeds safe thresholds.',
    difficulty: 2,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 79,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the clinical significance of a bronchodilator response seen only in FVC but not FEV1?',
    answer: 'An isolated FVC improvement without FEV1 improvement suggests volume response, indicating a reduction in air trapping and hyperinflation rather than improvement in airway caliber. The bronchodilator allows more complete lung emptying by reducing premature airway closure, manifesting as increased FVC and possibly decreased RV.',
    difficulty: 3,
    topic: 'Bronchodilator Response',
    isFree: false,
    orderIndex: 80,
  },

  // ============================================================
  // INTERPRETATION BASICS (cards 81-100)
  // ============================================================
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What spirometric pattern defines an obstructive ventilatory defect?',
    answer: 'An obstructive pattern is defined by a reduced FEV1/FVC ratio (below the lower limit of normal). FEV1 is reduced disproportionately relative to FVC. The FVC may be normal or reduced. The hallmark is that airflow is impaired relative to the volume of air in the lungs.',
    difficulty: 1,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 81,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What defines a restrictive ventilatory defect, and can it be diagnosed by spirometry alone?',
    answer: 'A restrictive defect is confirmed by a reduced TLC below the lower limit of normal. Spirometry alone can suggest restriction (reduced FVC with a normal or elevated FEV1/FVC ratio) but cannot confirm it because a reduced FVC may also result from air trapping in obstructive disease. Lung volume measurement is required for definitive diagnosis.',
    difficulty: 2,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 82,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is a mixed obstructive-restrictive pattern?',
    answer: 'A mixed pattern shows both a reduced FEV1/FVC ratio (indicating obstruction) and a reduced TLC (indicating restriction). Both conditions coexist. This can occur when a patient has both COPD and a restrictive condition such as obesity, chest wall deformity, or interstitial lung disease simultaneously.',
    difficulty: 2,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 83,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the ATS/ERS severity classification for airflow obstruction based on FEV1?',
    answer: 'Severity is graded using percent predicted FEV1 after confirming obstruction by a low FEV1/FVC ratio: Mild is FEV1 greater than 70% predicted; Moderate is 60-69% predicted; Moderately severe is 50-59% predicted; Severe is 35-49% predicted; Very severe is less than 35% predicted.',
    difficulty: 2,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 84,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the Lower Limit of Normal (LLN), and how is it determined?',
    answer: 'The LLN is the value below which results are considered abnormally low, statistically defined as the lower 5th percentile of a healthy reference population matched for age, sex, height, and ethnicity. It is calculated from reference equations and accounts for the natural variation in lung function among healthy individuals.',
    difficulty: 2,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 85,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the fixed-ratio criterion for defining airflow obstruction, and what is its main limitation?',
    answer: 'The fixed-ratio criterion uses FEV1/FVC less than 0.70 (70%) to define obstruction, regardless of age. Its main limitation is that the FEV1/FVC ratio naturally declines with aging, causing overdiagnosis of obstruction in elderly patients and potential underdiagnosis in younger adults. Using the LLN avoids this age-related bias.',
    difficulty: 2,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 86,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What are the GLI-2012 reference equations?',
    answer: 'The Global Lung Function Initiative 2012 equations are multi-ethnic, all-age (3-95 years) spirometry reference equations endorsed by ATS and ERS. They use lambda-mu-sigma (LMS) modeling to express results as Z-scores, providing continuous predicted values and LLN across age, sex, height, and ethnicity without arbitrary age-group cutoffs.',
    difficulty: 2,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 87,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is a Z-score in pulmonary function testing, and what Z-score corresponds to the LLN?',
    answer: 'A Z-score expresses how many standard deviations a measured value falls from the predicted mean for a matched reference population. A Z-score of -1.645 corresponds to the 5th percentile and defines the lower limit of normal. A Z-score of zero means the value equals the predicted mean. More negative values indicate more severe impairment.',
    difficulty: 3,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 88,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What factors are used to calculate predicted values for pulmonary function parameters?',
    answer: 'The primary factors are age, sex, standing height, and race/ethnicity. These are entered into validated reference equations to generate predicted normal values. Weight is not routinely used for spirometry prediction but may affect lung volumes. The predicted value represents the mean expected value for a healthy person with those characteristics.',
    difficulty: 1,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 89,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How is percent predicted calculated, and what is its limitation compared to Z-scores?',
    answer: 'Percent predicted = (measured value / predicted value) x 100. Its limitation is that the same percent predicted can have different clinical significance depending on age and sex because the spread (standard deviation) of normal values is not constant. Z-scores account for this by normalizing to the distribution, providing a more statistically valid comparison.',
    difficulty: 3,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 90,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does the flow-volume loop appear in a patient with a fixed upper airway obstruction?',
    answer: 'A fixed upper airway obstruction produces flattening of both the inspiratory and expiratory limbs of the flow-volume loop, creating a characteristic box-like appearance. Both maximal inspiratory and expiratory flows are equally limited because the fixed obstruction does not change with airway pressure changes during breathing phases.',
    difficulty: 3,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 91,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does a variable extrathoracic upper airway obstruction appear on the flow-volume loop?',
    answer: 'A variable extrathoracic obstruction flattens the inspiratory limb while the expiratory limb remains relatively normal. During inspiration, negative intraluminal pressure causes the extrathoracic airway to narrow at the obstruction site. During expiration, positive intraluminal pressure splints the airway open past the obstruction.',
    difficulty: 3,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 92,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does a variable intrathoracic upper airway obstruction appear on the flow-volume loop?',
    answer: 'A variable intrathoracic obstruction flattens the expiratory limb while the inspiratory limb remains relatively normal. During forced expiration, increased intrathoracic pressure compresses the airway at the obstruction site, limiting expiratory flow. During inspiration, negative intrathoracic pressure opens the airway at the site.',
    difficulty: 3,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 93,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'In an obstructive pattern, what happens to RV, TLC, and FRC?',
    answer: 'In obstruction with air trapping, RV increases (air cannot be fully exhaled), FRC increases (the resting balance point shifts toward a larger lung volume), and TLC may be normal or increased (hyperinflation). The RV/TLC ratio is elevated. These changes are most pronounced in emphysema.',
    difficulty: 2,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 94,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the expected DLCO pattern in emphysema versus asthma?',
    answer: 'In emphysema, DLCO is characteristically reduced because alveolar wall destruction decreases the gas exchange surface area and capillary bed volume. In asthma, DLCO is typically normal or may even be slightly elevated due to increased pulmonary blood volume during bronchoconstriction. This distinction helps differentiate the two obstructive diseases.',
    difficulty: 2,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 95,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the typical pulmonary function pattern in interstitial lung disease?',
    answer: 'Interstitial lung disease shows a restrictive pattern: reduced TLC, reduced VC, normal or elevated FEV1/FVC ratio, and reduced DLCO (due to thickened alveolar-capillary membrane). Flow rates relative to lung volume may actually be supranormal because increased elastic recoil maintains airway patency at lower lung volumes.',
    difficulty: 3,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 96,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the nonspecific ventilatory pattern, and what does it suggest?',
    answer: 'The nonspecific pattern shows a reduced FVC and FEV1 with a normal FEV1/FVC ratio and a normal TLC. It does not fit the classic obstructive or restrictive categories. This pattern may be seen in early disease processes, obesity, submaximal effort, neuromuscular weakness, or as a normal variant.',
    difficulty: 3,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 97,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'How does obesity affect pulmonary function testing results?',
    answer: 'Obesity primarily reduces ERV and FRC due to the mass loading effect on the diaphragm and chest wall. In morbid obesity, TLC may also decrease (creating a true restrictive pattern). FEV1/FVC ratio is typically preserved or elevated. DLCO is usually normal. The reduced ERV can cause airway closure during tidal breathing, particularly in the supine position.',
    difficulty: 2,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 98,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'What is the GOLD classification system for COPD severity based on spirometry?',
    answer: 'The GOLD (Global Initiative for Obstructive Lung Disease) system classifies COPD severity after confirming a post-bronchodilator FEV1/FVC below 0.70: GOLD 1 (Mild) is FEV1 at or above 80% predicted; GOLD 2 (Moderate) is 50-79%; GOLD 3 (Severe) is 30-49%; GOLD 4 (Very Severe) is below 30% predicted.',
    difficulty: 2,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 99,
  },
  {
    divisionId: CPFT_DIVISION_ID,
    question: 'Why should pulmonary function test interpretation consider the clinical context rather than rely solely on numerical cutoffs?',
    answer: 'Numerical values alone may mislead. A result just above or below a threshold may not be clinically meaningful given test variability. Trends over time are often more informative than a single measurement. Patient effort, cooperation, and testing conditions affect data quality. Correlating PFT results with symptoms, imaging, history, and physical examination ensures accurate clinical interpretation.',
    difficulty: 1,
    topic: 'Interpretation Basics',
    isFree: false,
    orderIndex: 100,
  },
]

async function main() {
  console.log('Seeding CPFT flashcards (Batch 1: cards 1-100)...')

  // Verify the division exists
  const division = await prisma.division.findUnique({
    where: { id: CPFT_DIVISION_ID },
  })

  if (!division) {
    console.error(
      `Division ${CPFT_DIVISION_ID} not found. Run seed-divisions.ts first.`
    )
    process.exit(1)
  }

  console.log(`Found division: ${division.name}`)

  // Delete existing flashcards for this division to avoid duplicates on re-run
  const deleted = await prisma.flashcard.deleteMany({
    where: { divisionId: CPFT_DIVISION_ID },
  })
  console.log(`Cleared ${deleted.count} existing flashcards for CPFT division.`)

  // Insert all flashcards
  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })

  console.log(`Successfully inserted ${result.count} CPFT flashcards.`)

  // Log summary by topic
  const topicCounts: Record<string, number> = {}
  const difficultyCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0 }
  let freeCount = 0

  for (const card of flashcards) {
    topicCounts[card.topic] = (topicCounts[card.topic] || 0) + 1
    difficultyCounts[card.difficulty]++
    if (card.isFree) freeCount++
  }

  console.log('\n--- Summary ---')
  console.log('By topic:')
  for (const [topic, count] of Object.entries(topicCounts)) {
    console.log(`  ${topic}: ${count} cards`)
  }
  console.log('By difficulty:')
  console.log(`  Easy (1): ${difficultyCounts[1]}`)
  console.log(`  Medium (2): ${difficultyCounts[2]}`)
  console.log(`  Hard (3): ${difficultyCounts[3]}`)
  console.log(`Free cards: ${freeCount}`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
