import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const RPFT_DIVISION_ID = 'cmsm41fyp0005zf54vrwow6p4'

const flashcards = [
  // ============================================================
  // ADVANCED SPIROMETRY & FLOW-VOLUME (cards 1-15)
  // ============================================================
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the characteristic shape of an obstructive flow-volume loop?',
    answer: 'An obstructive flow-volume loop shows a concave (scooped-out) appearance on the expiratory limb with reduced peak expiratory flow. The concavity results from dynamic airway compression during forced expiration, causing progressively decreasing flow rates at lower lung volumes. Inspiratory flow is typically preserved.',
    difficulty: 1,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 1,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How does a restrictive flow-volume loop differ from a normal loop?',
    answer: 'A restrictive flow-volume loop appears as a smaller, narrower version of a normal loop with proportionally reduced volumes but preserved or even supranormal flow rates relative to lung volume. Peak expiratory flow may be normal or slightly reduced, but the loop terminates earlier because total lung capacity and vital capacity are diminished.',
    difficulty: 1,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 2,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What flow-volume loop pattern indicates a fixed upper airway obstruction?',
    answer: 'A fixed upper airway obstruction produces a flattened plateau on both the inspiratory and expiratory limbs of the flow-volume loop, creating a characteristic box-like shape. Because the obstruction does not change with transmural pressure variations during the respiratory cycle, both phases are equally limited.',
    difficulty: 2,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 3,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How does a variable extrathoracic obstruction appear on a flow-volume loop and why?',
    answer: 'A variable extrathoracic obstruction flattens the inspiratory limb while preserving normal expiratory flow. During inspiration, negative intraluminal pressure relative to atmospheric pressure causes the compliant extrathoracic lesion to narrow further, limiting inspiratory flow. During expiration, positive intraluminal pressure splints the lesion open, maintaining normal expiratory flow.',
    difficulty: 2,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 4,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What flow-volume pattern is produced by a variable intrathoracic obstruction?',
    answer: 'A variable intrathoracic obstruction flattens the expiratory limb while maintaining a normal inspiratory curve. During forced expiration, positive pleural pressure compresses the intrathoracic airway around the lesion, worsening the obstruction. During inspiration, negative pleural pressure pulls the airway open, allowing near-normal inspiratory flow past the lesion.',
    difficulty: 2,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 5,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is maximum voluntary ventilation (MVV) and how is it performed?',
    answer: 'MVV measures the maximum volume of air a patient can breathe in and out during a sustained period, typically 12-15 seconds, while breathing as deeply and rapidly as possible. The measured volume is extrapolated to one minute and expressed in liters per minute. It reflects respiratory muscle strength, airway resistance, and thoracic compliance.',
    difficulty: 1,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 6,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How can MVV be estimated from FEV1 and when is the estimate useful?',
    answer: 'MVV can be estimated by multiplying FEV1 by 35 to 40 (commonly FEV1 times 40). This estimate is useful for patients who cannot perform the physically demanding MVV maneuver, and it serves as a comparison point: when measured MVV is significantly lower than estimated MVV, poor patient effort, respiratory muscle weakness, or upper airway obstruction should be considered.',
    difficulty: 2,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 7,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What does forced oscillation technique (FOT) measure and how does it work?',
    answer: 'FOT measures respiratory system impedance by superimposing small-amplitude pressure oscillations at various frequencies onto tidal breathing. It requires only passive cooperation, making it ideal for children and patients unable to perform forced maneuvers. FOT partitions impedance into resistance (the in-phase component) and reactance (the out-of-phase component).',
    difficulty: 2,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 8,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How does impulse oscillometry (IOS) differ from standard FOT?',
    answer: 'IOS uses a loudspeaker to deliver a rectangular impulse waveform containing all frequencies simultaneously, rather than individual sinusoidal frequencies applied sequentially. This allows rapid assessment across the entire frequency spectrum in a single measurement. IOS can differentiate central from peripheral airway obstruction by comparing resistance at 5 Hz (total airway resistance) and 20 Hz (proximal airway resistance).',
    difficulty: 3,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 9,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What does frequency dependence of resistance in FOT/IOS indicate?',
    answer: 'Frequency dependence of resistance, where resistance at low frequencies (e.g., 5 Hz) is substantially greater than at higher frequencies (e.g., 20 Hz), indicates peripheral or small airway obstruction. The difference between R5 and R20 isolates the contribution of distal airways because low-frequency oscillations penetrate deeper into the lung periphery while high-frequency oscillations reflect primarily central airway properties.',
    difficulty: 3,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 10,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the resonant frequency in FOT/IOS and what does an elevated value suggest?',
    answer: 'The resonant frequency (Fres) is the frequency at which respiratory reactance equals zero, meaning elastic and inertive forces are balanced. Normal Fres is typically 7 to 12 Hz. An elevated resonant frequency suggests increased peripheral airway resistance or decreased lung compliance, shifting the balance point to a higher frequency.',
    difficulty: 3,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 11,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What quality control criteria must be met for an acceptable FVC maneuver?',
    answer: 'An acceptable FVC maneuver requires a rapid start with back-extrapolated volume less than 5% of FVC or 100 mL (whichever is greater), no cough in the first second, no glottis closure or leak, and exhalation for at least 6 seconds or until a plateau is reached (volume change less than 25 mL over the final 1 second). The effort must be free of variable effort artifacts.',
    difficulty: 1,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 12,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are the ATS/ERS repeatability criteria for FEV1 and FVC?',
    answer: 'The two largest acceptable FEV1 values must be within 150 mL of each other, and the two largest acceptable FVC values must also be within 150 mL of each other. A minimum of three acceptable maneuvers is required, and a maximum of eight should be attempted. The best FEV1 and best FVC are reported, even if they come from different maneuvers.',
    difficulty: 1,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 13,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What does back-extrapolated volume assess and what is the acceptability threshold?',
    answer: 'Back-extrapolated volume (BEV) quantifies the hesitancy or slow start of a forced expiratory maneuver. It is determined by extending the steepest slope of the volume-time curve back to zero flow onset. BEV must be less than 5% of FVC or 100 mL, whichever is greater. Excessive BEV indicates the patient did not begin expiration with a sufficiently explosive blast effort.',
    difficulty: 2,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 14,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How is the area under the reactance curve (AX) interpreted in oscillometry?',
    answer: 'AX represents the integrated area of negative reactance values between 5 Hz and the resonant frequency. It serves as a single summary measure of peripheral airway mechanics combining both resistive and elastic abnormalities. Elevated AX indicates peripheral airway dysfunction, and it is more sensitive to bronchodilator response and small airway changes than resistance alone.',
    difficulty: 3,
    topic: 'Advanced Spirometry & Flow-Volume',
    isFree: true,
    orderIndex: 15,
  },

  // ============================================================
  // CARDIOPULMONARY EXERCISE TESTING (cards 16-35)
  // ============================================================
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the primary purpose of cardiopulmonary exercise testing (CPET)?',
    answer: 'CPET integrates cardiac, pulmonary, and metabolic responses to incremental exercise to determine the cause of exercise limitation. It simultaneously measures gas exchange, ventilation, heart rate, blood pressure, and oxygen saturation to differentiate cardiac from pulmonary causes of dyspnea and objectively quantify exercise capacity.',
    difficulty: 1,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: true,
    orderIndex: 16,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are the stages and speed/grade increments of the standard Bruce treadmill protocol?',
    answer: 'The Bruce protocol starts at 1.7 mph and 10% grade (Stage 1), increasing every 3 minutes. Stage 2 is 2.5 mph at 12%, Stage 3 is 3.4 mph at 14%, Stage 4 is 4.2 mph at 16%, and Stage 5 is 5.0 mph at 18%. Each stage raises workload by approximately 2-3 METs, with the test continuing until the patient reaches symptom limitation or predetermined endpoints.',
    difficulty: 2,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: true,
    orderIndex: 17,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What advantages does cycle ergometry offer over treadmill testing for CPET?',
    answer: 'Cycle ergometry provides a precisely quantifiable external work rate independent of body weight, produces less upper body motion artifact for ECG and blood pressure monitoring, allows easier arterial blood sampling during exercise, and is safer because patients can stop instantly. It also permits more accurate calculation of mechanical efficiency and oxygen kinetics.',
    difficulty: 1,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: true,
    orderIndex: 18,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How is peak VO2 different from VO2max and what clinical significance does each have?',
    answer: 'VO2max is the true physiological maximum oxygen consumption where a plateau in VO2 occurs despite increasing work rate, confirming cardiovascular limitation. Peak VO2 is the highest VO2 achieved during a symptom-limited test without necessarily demonstrating a plateau. In clinical testing, most patients achieve peak VO2 rather than true VO2max because disease, deconditioning, or symptoms halt the test first.',
    difficulty: 2,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: true,
    orderIndex: 19,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the anaerobic threshold (AT) and how is it identified using the V-slope method?',
    answer: 'The anaerobic threshold is the exercise intensity above which anaerobic metabolism supplements aerobic energy production, marked by accelerated lactate accumulation. Using the V-slope method, VCO2 is plotted against VO2, and the AT is identified as the breakpoint where VCO2 begins to rise disproportionately faster than VO2, creating a steeper slope above the point of transition.',
    difficulty: 2,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: true,
    orderIndex: 20,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are ventilatory equivalents and how are VE/VO2 and VE/VCO2 used to identify the anaerobic threshold?',
    answer: 'Ventilatory equivalents express the liters of ventilation needed per liter of gas exchanged. At the anaerobic threshold, VE/VO2 begins to rise while VE/VCO2 remains stable or continues to decrease. This occurs because increased CO2 production from bicarbonate buffering of lactic acid drives ventilation up relative to oxygen consumption, but CO2 output has also increased proportionally.',
    difficulty: 3,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 21,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How is dead space ventilation during exercise calculated and what is a normal response?',
    answer: 'Dead space to tidal volume ratio (VD/VT) is calculated as (PaCO2 minus mixed expired PCO2) divided by PaCO2. At rest, VD/VT is approximately 0.30-0.35 and normally decreases to below 0.20 during exercise due to tidal volume expansion, improved ventilation-perfusion matching, and pulmonary vascular recruitment. Failure to decrease VD/VT during exercise suggests pulmonary vascular disease.',
    difficulty: 3,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 22,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What criteria define a positive test for exercise-induced bronchospasm (EIB)?',
    answer: 'A positive EIB test is defined by a decrease in FEV1 of 10% or greater from baseline following exercise, with a decrease of 15% or more considered diagnostic. FEV1 is measured at 5, 10, 15, 20, and 30 minutes post-exercise. The exercise target is 80-90% of predicted maximum heart rate sustained for 6-8 minutes with dry air inhalation to maximize airway cooling and drying.',
    difficulty: 2,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 23,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How do you distinguish cardiac limitation from pulmonary limitation during CPET?',
    answer: 'Cardiac limitation is characterized by reduced peak VO2, low anaerobic threshold, heart rate reaching predicted maximum, normal breathing reserve, and oxygen pulse plateau. Pulmonary limitation shows reduced breathing reserve (MVV minus peak VE less than 11 L/min or less than 15% of MVV), possible exercise desaturation, elevated VE/VCO2 slope, and heart rate not reaching predicted maximum.',
    difficulty: 3,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 24,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is a metabolic equivalent (MET) and what MET levels correspond to common activities?',
    answer: 'One MET equals resting oxygen consumption of approximately 3.5 mL O2/kg/min. Light housework corresponds to 2-3 METs, walking at 3 mph is about 3-4 METs, climbing two flights of stairs is roughly 4-5 METs, and jogging at 5 mph is approximately 7-8 METs. Functional capacity below 5 METs is associated with increased surgical and cardiovascular risk.',
    difficulty: 1,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 25,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are the standardization requirements for a valid 6-minute walk test (6MWT)?',
    answer: 'The 6MWT requires a flat, straight corridor at least 30 meters long with turnaround cones, standardized encouragement phrases given at each minute, no warm-up period, supplemental oxygen at prescribed flow if applicable, and the patient walking at their own pace with the option to rest. Baseline and post-test vital signs, SpO2, dyspnea, and fatigue scores must be recorded.',
    difficulty: 1,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 26,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the clinical significance of a 6MWT distance below 350 meters?',
    answer: 'A 6MWT distance below 350 meters is associated with increased mortality risk in patients with COPD and heart failure. This threshold has been identified as a prognostic marker for poor outcomes and is used in composite indices like the BODE index. Additionally, distances below 200 meters may indicate the need for listing evaluation for lung transplantation.',
    difficulty: 2,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 27,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is oxygen pulse and how is it interpreted during CPET?',
    answer: 'Oxygen pulse is calculated as VO2 divided by heart rate and reflects the product of stroke volume and arteriovenous oxygen difference. Normal oxygen pulse increases progressively during exercise. A plateau or decline in oxygen pulse suggests cardiac stroke volume limitation, which may indicate ischemic heart disease, cardiomyopathy, or severe deconditioning.',
    difficulty: 2,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 28,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is breathing reserve and how is it calculated?',
    answer: 'Breathing reserve represents the difference between maximum voluntary ventilation (MVV) and peak exercise ventilation (VEmax), expressed either in absolute terms (MVV minus VEmax) or as a percentage of MVV. Normal breathing reserve is greater than 15% of MVV or greater than 11 L/min. Reduced breathing reserve indicates the patient reached a ventilatory ceiling, suggesting pulmonary limitation to exercise.',
    difficulty: 2,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 29,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the VE/VCO2 slope and what does an elevated value indicate?',
    answer: 'The VE/VCO2 slope represents the rate of increase in minute ventilation relative to carbon dioxide output during exercise. Normal values are 25-30. An elevated slope (greater than 34) indicates ventilatory inefficiency due to increased dead space ventilation, V/Q mismatch, or excessive chemoreceptor drive. It is a powerful prognostic marker in heart failure and pulmonary hypertension.',
    difficulty: 3,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 30,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the respiratory exchange ratio (RER) and what does an RER above 1.10 at peak exercise indicate?',
    answer: 'RER is the ratio of CO2 output to O2 consumption (VCO2/VO2). At rest, RER is approximately 0.80-0.85 depending on substrate utilization. An RER exceeding 1.10 at peak exercise indicates adequate patient effort and significant anaerobic metabolism, as excess CO2 is generated from bicarbonate buffering of lactic acid beyond metabolic CO2 production.',
    difficulty: 2,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 31,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How are exercise flow-volume loops used to detect dynamic hyperinflation during CPET?',
    answer: 'Tidal flow-volume loops measured during exercise are superimposed on the maximal resting flow-volume envelope. If the end-expiratory lung volume shifts toward total lung capacity (leftward shift on the volume axis) and tidal expiratory flows approach or impinge upon the maximal envelope, dynamic hyperinflation is present. This confirms ventilatory limitation by demonstrating mechanical flow constraint during exercise.',
    difficulty: 3,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 32,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are absolute contraindications to cardiopulmonary exercise testing?',
    answer: 'Absolute contraindications include acute myocardial infarction within the past 3-5 days, unstable angina, uncontrolled cardiac arrhythmias causing hemodynamic compromise, symptomatic severe aortic stenosis, acute pulmonary embolism, acute myocarditis or pericarditis, acute aortic dissection, and resting SpO2 below 85% on room air in patients with known desaturation risk.',
    difficulty: 1,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 33,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What criteria should be used to terminate a CPET?',
    answer: 'Termination criteria include patient request to stop, chest pain suggestive of ischemia, significant ST-segment changes on ECG, complex ventricular arrhythmias, drop in systolic blood pressure greater than 20 mmHg from peak during exercise, hypertensive response exceeding 250/120 mmHg, severe desaturation (SpO2 below 80%), signs of inadequate perfusion (cyanosis, pallor), and loss of coordination or mental confusion.',
    difficulty: 2,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 34,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How does the modified Borg scale function during exercise testing and what score ranges are significant?',
    answer: 'The modified Borg scale rates perceived dyspnea and leg fatigue from 0 (nothing at all) to 10 (maximal). It is administered at baseline, during each stage, and at peak exercise. Scores of 3-4 indicate moderate symptoms, 5-6 indicate severe symptoms, and 7-10 indicate very severe to maximal symptoms. The scale provides standardized subjective effort assessment and helps determine the primary symptom limiting exercise.',
    difficulty: 1,
    topic: 'Cardiopulmonary Exercise Testing',
    isFree: false,
    orderIndex: 35,
  },

  // ============================================================
  // BRONCHIAL CHALLENGE TESTING (cards 36-55)
  // ============================================================
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the purpose of a methacholine challenge test?',
    answer: 'The methacholine challenge test assesses bronchial hyperresponsiveness by administering incrementally increasing concentrations of methacholine, a direct cholinergic agonist, and measuring the FEV1 response after each dose. It is primarily used to support or exclude a diagnosis of asthma when baseline spirometry is normal and the clinical picture is ambiguous.',
    difficulty: 1,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 36,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'Describe the standard dosing protocol for a methacholine challenge using the five-breath dosimeter method.',
    answer: 'The five-breath dosimeter method delivers methacholine starting at 0.0625 mg/mL with quadrupling concentrations (0.0625, 0.25, 1, 4, 16 mg/mL). At each concentration, five inspiratory-capacity breaths are taken from functional residual capacity. FEV1 is measured at 30 and 90 seconds after each dose. Testing continues until FEV1 drops 20% or more from post-diluent baseline or the maximum concentration is reached.',
    difficulty: 2,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 37,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How is PC20 calculated and what does it represent?',
    answer: 'PC20 is the provocative concentration of methacholine causing a 20% fall in FEV1. It is calculated by logarithmic interpolation between the last two concentrations using the formula: PC20 = antilog[log C1 + (log C2 minus log C1)(20 minus R1) / (R2 minus R1)], where C1 and C2 are concentrations and R1 and R2 are corresponding percent falls in FEV1. A PC20 less than or equal to 4 mg/mL indicates moderate to severe hyperresponsiveness.',
    difficulty: 3,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 38,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What clinical interpretation is given to different PC20 thresholds?',
    answer: 'PC20 less than 1 mg/mL indicates severe bronchial hyperresponsiveness strongly consistent with active asthma. PC20 of 1-4 mg/mL indicates moderate hyperresponsiveness and is usually clinically significant. PC20 of 4-16 mg/mL indicates mild or borderline hyperresponsiveness with less certain clinical significance. PC20 greater than 16 mg/mL indicates normal airway responsiveness, effectively ruling out current asthma.',
    difficulty: 1,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 39,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How does a histamine challenge differ from a methacholine challenge?',
    answer: 'Both are direct bronchial challenge agents that act on airway smooth muscle, but histamine acts through H1 receptors while methacholine acts through muscarinic M3 receptors. Histamine causes more systemic side effects including headache, flushing, and tachycardia because it has broader receptor distribution beyond the airways. Methacholine is preferred clinically due to its superior safety profile and airway specificity.',
    difficulty: 1,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 40,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the mannitol challenge test and what makes it an indirect challenge?',
    answer: 'The mannitol challenge uses inhaled dry powder mannitol in escalating doses (0 to 635 mg cumulative). It is an indirect challenge because mannitol acts by creating an osmotic stimulus that draws water from the airway surface, triggering mast cell degranulation and mediator release, which then causes bronchoconstriction. A positive response is a 15% fall in FEV1 from baseline or a 10% fall between consecutive doses.',
    difficulty: 2,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 41,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is eucapnic voluntary hyperventilation (EVH) and how is it used in challenge testing?',
    answer: 'EVH requires the patient to hyperventilate dry air containing 5% CO2 (to prevent hypocapnia) at 85% of MVV for 6 minutes. FEV1 is measured at 3, 5, 10, 15, and 20 minutes post-challenge. A 10% or greater fall in FEV1 is positive. EVH is considered the gold standard surrogate for exercise-induced bronchoconstriction because dry air hyperventilation mimics the airway drying that occurs during intense exercise.',
    difficulty: 3,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 42,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What exercise challenge protocol is used to diagnose exercise-induced bronchoconstriction?',
    answer: 'The patient exercises on a treadmill or cycle ergometer at an intensity sufficient to achieve 80-90% of predicted maximum heart rate within 2-4 minutes, then sustains this level for 6-8 minutes while breathing dry air (less than 10 mg H2O per liter). FEV1 is measured before and at 5, 10, 15, 20, and 30 minutes after exercise. A fall of 10% or greater in FEV1 confirms exercise-induced bronchoconstriction.',
    difficulty: 2,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 43,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What medications must be withheld before methacholine challenge testing and for how long?',
    answer: 'Short-acting beta-agonists must be withheld for at least 8 hours, long-acting beta-agonists for 48 hours, ultra-long-acting agents like tiotropium for at least one week, leukotriene modifiers for 24 hours, antihistamines for 72 hours, and inhaled corticosteroids may need 1-2 weeks of withdrawal. Caffeine-containing beverages should be avoided the day of the test because of their mild bronchodilator effect.',
    difficulty: 3,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 44,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are the absolute contraindications for bronchial challenge testing?',
    answer: 'Absolute contraindications include FEV1 less than 60% predicted or less than 1.5 liters, myocardial infarction or stroke within the past 3 months, uncontrolled hypertension (systolic greater than 200 mmHg or diastolic greater than 100 mmHg), known aortic aneurysm, inability to perform acceptable spirometry, and current use of cholinesterase inhibitor medication (for methacholine specifically).',
    difficulty: 1,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 45,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What safety equipment and medications must be immediately available during bronchial challenge testing?',
    answer: 'A short-acting bronchodilator (albuterol MDI with spacer or nebulizer setup) must be at the bedside. Resuscitation equipment including oxygen, suction, bag-valve mask, emergency medications (epinephrine), and a crash cart or defibrillator must be accessible. A physician must be available within the facility, and the technologist must be trained in emergency response. Continuous oximetry monitoring is required.',
    difficulty: 1,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 46,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the significance of the dose-response slope in methacholine testing beyond PC20?',
    answer: 'The dose-response slope describes the steepness of FEV1 decline per unit increase in methacholine concentration. A steep slope indicates that once bronchoconstriction begins, it progresses rapidly with small dose increments, reflecting more severe or labile airway disease. The dose-response slope may provide additional clinical information about disease severity and risk of severe bronchoconstriction that PC20 alone does not capture.',
    difficulty: 3,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 47,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What baseline spirometry criterion must be met before proceeding with a methacholine challenge?',
    answer: 'Baseline FEV1 must be at least 60% of predicted and preferably at least 1.5 liters to ensure the patient can safely tolerate a 20% reduction without developing dangerous levels of airflow obstruction. Additionally, the patient should demonstrate acceptable and repeatable spirometry at baseline to ensure reliable detection of a 20% decline during the challenge.',
    difficulty: 1,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 48,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How do direct and indirect bronchial challenges differ in clinical utility?',
    answer: 'Direct challenges (methacholine, histamine) act on smooth muscle receptors and have high sensitivity but lower specificity for asthma, making them excellent for ruling out disease. Indirect challenges (mannitol, EVH, exercise) trigger bronchoconstriction through inflammatory mediator release and have high specificity but lower sensitivity, making them better for confirming active airway inflammation and predicting response to anti-inflammatory therapy.',
    difficulty: 3,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 49,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the negative predictive value of a methacholine challenge and how does this guide clinical decisions?',
    answer: 'The negative predictive value of a methacholine challenge is very high, approximately 95% or greater. This means a negative result (PC20 greater than 16 mg/mL) effectively excludes current asthma with a high degree of certainty. Clinically, the test is most valuable when used to rule out asthma in patients with symptoms suggestive of the disease but normal baseline spirometry.',
    difficulty: 1,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 50,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How should a technologist manage a patient who develops severe bronchoconstriction during a methacholine challenge?',
    answer: 'Immediately discontinue the challenge and administer a short-acting beta-agonist (albuterol 2-4 puffs via spacer or 2.5 mg via nebulizer). Apply supplemental oxygen to maintain SpO2 above 90%. Monitor FEV1 every 5-10 minutes until it returns to within 10% of baseline. If FEV1 does not recover adequately or symptoms worsen, repeat bronchodilator and consider contacting the supervising physician for additional interventions.',
    difficulty: 2,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 51,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the provocative dose (PD20) and how does it differ from PC20?',
    answer: 'PD20 is the cumulative delivered dose of methacholine (in micromoles or milligrams) that causes a 20% fall in FEV1, whereas PC20 refers to the concentration (mg/mL). PD20 accounts for the total amount of agonist delivered to the airways and may be more physiologically relevant because it incorporates differences in nebulizer output, breathing pattern, and number of breaths. PD20 is commonly used with the tidal breathing protocol.',
    difficulty: 3,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 52,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What environmental conditions must be controlled in the bronchial challenge laboratory?',
    answer: 'Temperature should be maintained at 20-25 degrees Celsius and relative humidity kept below 50% to prevent degradation of methacholine solutions and ensure consistent aerosol delivery. The nebulizer output must be calibrated (typically 0.13 mL/min for the tidal breathing method). Solutions must be stored at 4 degrees Celsius, brought to room temperature before use, and discarded after two weeks of refrigerated storage.',
    difficulty: 3,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 53,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the tidal breathing method for methacholine challenge and how does it compare to the dosimeter method?',
    answer: 'In the tidal breathing method, the patient breathes normally from the nebulizer for 2 minutes at each concentration, inhaling methacholine continuously during both phases of respiration. Compared to the dosimeter method (five inspiratory-capacity breaths), the tidal breathing method delivers a more variable dose depending on breathing pattern and requires standardized nebulizer output. Both methods produce clinically equivalent PC20 results when properly standardized.',
    difficulty: 2,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 54,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How should post-challenge recovery be monitored and when can the patient be safely discharged?',
    answer: 'After a positive challenge, administer a short-acting bronchodilator and monitor FEV1 at 10-15 minute intervals. The patient should not be discharged until FEV1 has recovered to within 90% of the pre-challenge baseline value. Monitor for late-phase responses by instructing the patient to watch for recurring symptoms 4-8 hours later and provide a bronchodilator prescription or inhaler for home use if needed.',
    difficulty: 2,
    topic: 'Bronchial Challenge Testing',
    isFree: false,
    orderIndex: 55,
  },

  // ============================================================
  // ADVANCED LUNG VOLUME MEASUREMENT (cards 56-70)
  // ============================================================
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How does body plethysmography measure thoracic gas volume?',
    answer: 'The patient sits inside a sealed, rigid box and pants against a closed shutter at the airway opening. Boyle\'s law (P1V1 = P2V2) is applied: as the patient makes breathing efforts against the shutter, thoracic gas compresses and decompresses, causing reciprocal pressure changes in the box. Mouth pressure reflects alveolar pressure, and box pressure changes reflect thoracic volume changes, allowing calculation of thoracic gas volume.',
    difficulty: 2,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 56,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the recommended panting frequency for body plethysmography and why?',
    answer: 'The recommended panting frequency is 0.5 to 1.0 Hz (approximately one pant per second). Panting too rapidly (above 2 Hz) can cause thermal artifacts from gas compression heating and also allows cheek puffing to introduce error. Panting too slowly may allow the glottis to close. Supporting the cheeks with the hands during panting helps minimize upper airway compliance artifacts.',
    difficulty: 2,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 57,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How is Boyle\'s law applied in calculating thoracic gas volume in a plethysmograph?',
    answer: 'Boyle\'s law states that at constant temperature, the product of pressure and volume remains constant. When the shutter closes and the patient pants, mouth pressure (Pm) approximates alveolar pressure, and box pressure changes reflect volume shifts. The equation is: TGV = Vbox times (change in box pressure / change in mouth pressure), where the ratio of pressure changes derives from the slope of the mouth pressure versus box pressure plot during panting.',
    difficulty: 3,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 58,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the purpose of shutter occlusion in body plethysmography?',
    answer: 'Shutter occlusion at the mouthpiece blocks airflow and creates a closed system where mouth pressure equals alveolar pressure during panting efforts. Without the shutter, alveolar pressure cannot be directly measured. The occlusion must be precisely timed to occur at end-expiration (functional residual capacity) so that the measured thoracic gas volume corresponds to FRC.',
    difficulty: 2,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 59,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the relationship between mouth pressure and box pressure during plethysmographic measurement?',
    answer: 'During panting against the closed shutter, mouth pressure and box pressure form an S-shaped (sigmoid) loop when plotted against each other. The tangent of the angle of this loop is used to calculate thoracic gas volume. A closed, narrow loop indicates proper technique. Wide or irregular loops suggest air leaks, thermal drift, upper airway artifact, or improper panting frequency.',
    difficulty: 3,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 60,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How is airway resistance (Raw) measured in a body plethysmograph?',
    answer: 'Raw is measured by having the patient pant with the shutter open while recording flow at the mouth and box pressure changes simultaneously. Box pressure changes reflect thoracic volume shifts that correspond to alveolar pressure swings driving airflow. Raw is calculated as the ratio of alveolar pressure change to airflow, derived from the slope of the pressure-flow loop. Normal Raw is 0.6 to 2.4 cmH2O/L/sec.',
    difficulty: 2,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 61,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is specific airway conductance (sGaw) and why is it preferred over Raw alone?',
    answer: 'sGaw is the reciprocal of airway resistance (conductance = 1/Raw) divided by thoracic gas volume at which it was measured: sGaw = Gaw/TGV. It normalizes conductance for lung volume because airway caliber changes with lung inflation. This correction makes sGaw a more reliable measure of intrinsic airway caliber across patients with different lung volumes and between measurements where volume may have shifted.',
    difficulty: 2,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 62,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'Why does body plethysmography measure higher lung volumes in patients with severe obstruction compared to gas dilution methods?',
    answer: 'Plethysmography measures all compressible gas within the thorax, including trapped gas behind closed airways, whereas gas dilution methods (helium dilution and nitrogen washout) only measure gas that communicates with the airway opening during the test. In severe obstruction with significant air trapping, poorly ventilated regions do not equilibrate with the tracer gas, causing gas dilution to underestimate true lung volume.',
    difficulty: 2,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 63,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How does the helium dilution technique measure functional residual capacity?',
    answer: 'The patient breathes on a closed circuit containing a known concentration of helium (a metabolically inert, insoluble gas) starting at end-tidal expiration (FRC). Helium equilibrates between the spirometer and the lungs over several minutes. FRC is calculated using the conservation of mass equation: FRC = Vs times (He1 minus He2) / He2, where Vs is the spirometer volume, He1 is starting concentration, and He2 is final equilibrated concentration.',
    difficulty: 1,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 64,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the nitrogen washout technique for measuring FRC?',
    answer: 'The patient breathes 100% oxygen through an open circuit starting at FRC. All exhaled nitrogen is collected and measured. Since the lungs start at approximately 78% nitrogen and the volume of nitrogen washed out equals the volume of N2 in the lungs at FRC, the calculation is: FRC = total volume of N2 washed out divided by the initial alveolar N2 concentration. Washout continues until end-tidal N2 falls below 1.5% for three consecutive breaths.',
    difficulty: 2,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 65,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What sources of error are specific to body plethysmography?',
    answer: 'Key error sources include incomplete thermal equilibration of panted gas (BTPS conditions not maintained), upper airway compliance causing cheek puffing, air leaks around the mouthpiece, improper panting frequency, failure to close the shutter at true FRC, abdominal gas contributing to measured thoracic gas volume, and patient anxiety causing irregular breathing or inability to maintain a seal. Equipment drift and inadequate box calibration also introduce error.',
    difficulty: 3,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 66,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How is residual volume (RV) calculated from plethysmographic measurements?',
    answer: 'RV is calculated as FRC minus expiratory reserve volume (ERV). FRC is measured by plethysmography, and ERV is measured during a linked slow vital capacity maneuver. Alternatively, RV can be derived as TLC minus vital capacity. The plethysmograph directly measures FRC (thoracic gas volume at end-expiration), and the other subdivisions are determined from the associated spirometric maneuvers.',
    difficulty: 1,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 67,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What does an elevated RV/TLC ratio indicate and what is the normal range?',
    answer: 'The normal RV/TLC ratio is approximately 25-35% in younger adults and increases with age. An elevated ratio above 35-40% indicates air trapping, where gas is retained in the lungs at end-expiration. This is a hallmark of obstructive lung disease, particularly emphysema and chronic bronchitis, where loss of elastic recoil or airway closure during expiration prevents complete lung emptying.',
    difficulty: 1,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 68,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How do lung volume measurements distinguish between obstructive and restrictive patterns?',
    answer: 'Obstruction typically shows increased TLC (hyperinflation), markedly increased RV (air trapping), elevated FRC, and elevated RV/TLC ratio with relatively preserved or increased TLC. Restriction shows decreased TLC (the defining criterion), decreased RV, decreased FRC, and a normal or slightly elevated RV/TLC ratio. Mixed patterns show reduced TLC with disproportionately elevated RV/TLC ratio.',
    difficulty: 1,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 69,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the BTPS correction and why is it critical for plethysmographic volume measurements?',
    answer: 'BTPS stands for Body Temperature (37 degrees Celsius), ambient Pressure, Saturated with water vapor. Gas volumes must be corrected to BTPS conditions because gas in the lungs exists at body temperature and is fully humidified, while measuring instruments operate at room temperature. Failure to apply BTPS correction underestimates lung volumes because gas contracts as it cools from body to ambient temperature.',
    difficulty: 1,
    topic: 'Advanced Lung Volume Measurement',
    isFree: false,
    orderIndex: 70,
  },

  // ============================================================
  // ADVANCED DIFFUSION & GAS EXCHANGE (cards 71-85)
  // ============================================================
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How does the single-breath DLCO test measure diffusing capacity?',
    answer: 'The patient exhales to RV, then rapidly inhales a gas mixture containing 0.3% carbon monoxide and a tracer gas (helium or methane) to TLC, holds the breath for approximately 10 seconds, then exhales. The initial portion of exhaled gas (dead space) is discarded and an alveolar sample is collected. DLCO is calculated from the rate of CO disappearance during breath-hold relative to the initial alveolar CO concentration and alveolar volume.',
    difficulty: 2,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 71,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the DLCO/VA ratio (KCO) and how does its interpretation differ from DLCO alone?',
    answer: 'KCO (also called the transfer coefficient) is DLCO divided by alveolar volume (VA), representing diffusing capacity per unit of accessible lung volume. It distinguishes between a low DLCO caused by reduced lung volume (where KCO is normal or elevated, as in pneumonectomy or chest wall restriction) versus a low DLCO caused by intrinsic parenchymal or vascular disease (where KCO is reduced, as in emphysema or pulmonary vascular disease).',
    difficulty: 2,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 72,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are membrane diffusing capacity (Dm) and pulmonary capillary blood volume (Vc), and how are they measured?',
    answer: 'Dm represents the conductance of the alveolar-capillary membrane to gas transfer, and Vc is the volume of blood in pulmonary capillaries available for gas exchange. They are measured by performing DLCO at two or more different inspired oxygen concentrations (e.g., 21% and high-oxygen mixtures). The Roughton-Forster equation (1/DLCO = 1/Dm + 1/theta times Vc) is solved simultaneously because changing FIO2 alters the CO reaction rate with hemoglobin (theta) without affecting Dm.',
    difficulty: 3,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 73,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How should DLCO be adjusted for hemoglobin and what is the rationale?',
    answer: 'DLCO must be adjusted for hemoglobin because CO transfer depends on binding to hemoglobin in pulmonary capillary blood. The adjustment formula for males is: adjusted DLCO = measured DLCO times (10.22 + Hb) / (1.7 times Hb). For females: adjusted DLCO = measured DLCO times (9.38 + Hb) / (1.7 times Hb). Anemia causes falsely low DLCO and polycythemia causes falsely high DLCO without reflecting actual membrane function.',
    difficulty: 3,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 74,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What conditions cause an elevated DLCO and what is the mechanism?',
    answer: 'Elevated DLCO is seen in asthma (air trapping increases capillary blood volume), obesity (increased pulmonary blood volume), left-to-right cardiac shunts (increased pulmonary blood flow and capillary volume), polycythemia (more hemoglobin available for CO binding), pulmonary hemorrhage (extravasated hemoglobin in alveoli absorbs CO), and exercise (capillary recruitment and distension). All mechanisms increase the amount of hemoglobin accessible to CO in the pulmonary vasculature or alveolar space.',
    difficulty: 1,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 75,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is fractional exhaled nitric oxide (FeNO) and what does it indicate?',
    answer: 'FeNO measures the concentration of nitric oxide in exhaled breath in parts per billion (ppb). Nitric oxide is produced by epithelial cells in response to eosinophilic airway inflammation, making FeNO a noninvasive biomarker of type 2 (eosinophilic) airway inflammation. It is primarily used to diagnose and monitor eosinophilic asthma and to assess likely responsiveness to inhaled corticosteroid therapy.',
    difficulty: 1,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 76,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are the accepted FeNO thresholds for clinical interpretation in adults?',
    answer: 'In adults, FeNO less than 25 ppb is considered normal and eosinophilic inflammation is unlikely. FeNO between 25 and 50 ppb is intermediate and should be interpreted in clinical context. FeNO greater than 50 ppb indicates significant eosinophilic inflammation and predicts a favorable response to corticosteroid therapy. These thresholds must be interpreted alongside symptoms, spirometry, and clinical history.',
    difficulty: 1,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 77,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What technical standards must be met for valid FeNO measurement?',
    answer: 'The patient inhales to TLC through a NO-scrubbing filter, then exhales at a constant flow rate of 50 mL/sec maintained by visual feedback against a target pressure. Exhalation must last at least 6 seconds to achieve a stable NO plateau. The plateau must be sustained for at least 3 seconds, and two measurements must agree within 10% or 2 ppb (whichever is greater). Nasal contamination is prevented by maintaining expiratory pressure above 5 cmH2O to close the velum.',
    difficulty: 2,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 78,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What factors other than asthma can elevate or reduce FeNO levels?',
    answer: 'FeNO can be elevated by allergic rhinitis, eosinophilic bronchitis, dietary nitrate intake, and viral upper respiratory infections. FeNO can be reduced by cigarette smoking, bronchoconstriction (reduced airway caliber limits NO diffusion), alcohol ingestion, and high-altitude exposure. Corticosteroid use suppresses FeNO, making it useful for monitoring treatment adherence.',
    difficulty: 2,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 79,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How is an intrapulmonary shunt study performed and what constitutes a significant shunt fraction?',
    answer: 'A shunt study requires simultaneous arterial and mixed venous blood sampling while the patient breathes 100% oxygen for at least 20-30 minutes to wash out all alveolar nitrogen. Shunt fraction (Qs/Qt) is calculated using the classic shunt equation: Qs/Qt = (CcO2 minus CaO2) / (CcO2 minus CvO2), where CcO2 is end-capillary oxygen content (estimated from PAO2 on the oxygen dissociation curve). A shunt fraction greater than 5% is abnormal.',
    difficulty: 3,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 80,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What quality control criteria apply to acceptable DLCO measurements?',
    answer: 'Inspired volume must be at least 85% of the largest measured VC. Breath-hold time should be 10 plus or minus 2 seconds using the Jones-Meade method. Inspiratory time should be less than 4 seconds. The washout volume must be 0.75-1.0 liters, and sample collection volume should be 0.5-1.0 liters. At least two acceptable tests within 2 mL/min/mmHg of each other are required, with the mean reported. A minimum of 4 minutes should separate repeated tests.',
    difficulty: 3,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 81,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How does the alveolar volume (VA) measured during DLCO differ from TLC measured by plethysmography?',
    answer: 'VA measured during DLCO is derived from single-breath tracer gas dilution (helium or methane) and only measures the volume of lung that the inspired gas reaches during the maneuver. In patients with significant airway obstruction, VA underestimates true TLC because gas does not distribute evenly to poorly ventilated regions. Plethysmographic TLC measures all thoracic gas including trapped gas, making it consistently larger in obstructive disease.',
    difficulty: 3,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 82,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How should DLCO be corrected for elevated carboxyhemoglobin (COHb)?',
    answer: 'Elevated COHb from smoking or environmental exposure reduces DLCO by occupying hemoglobin binding sites and increasing CO back-pressure, which decreases the driving gradient for CO transfer. The correction increases measured DLCO by approximately 1% for each 1% increase in COHb above baseline. Some labs measure COHb directly; others use a standard correction based on smoking history (e.g., assume 3-5% COHb for active smokers).',
    difficulty: 3,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 83,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What pattern of DLCO and KCO findings is characteristic of emphysema versus pulmonary fibrosis?',
    answer: 'In emphysema, both DLCO and KCO are reduced because alveolar-capillary surface area is destroyed by parenchymal loss. In pulmonary fibrosis, DLCO is reduced due to membrane thickening and loss of lung volume, but KCO may be normal or only mildly reduced because the remaining lung units still have intact gas exchange surfaces, and reduced alveolar volume concentrates the available capillary blood volume per unit volume of lung.',
    difficulty: 3,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 84,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What does an elevated alveolar-arterial oxygen gradient (A-a gradient) indicate and how is it calculated?',
    answer: 'The A-a gradient is calculated as PAO2 minus PaO2, where PAO2 is estimated using the alveolar gas equation: PAO2 = FIO2(Pb minus PH2O) minus PaCO2/R. Normal A-a gradient is approximately 5-15 mmHg in young adults breathing room air and increases with age. An elevated A-a gradient indicates V/Q mismatch, diffusion impairment, or right-to-left shunt, while a normal A-a gradient with hypoxemia suggests hypoventilation.',
    difficulty: 1,
    topic: 'Advanced Diffusion & Gas Exchange',
    isFree: false,
    orderIndex: 85,
  },

  // ============================================================
  // QUALITY MANAGEMENT & RESEARCH (cards 86-100)
  // ============================================================
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is proficiency testing in a pulmonary function laboratory?',
    answer: 'Proficiency testing involves analyzing standardized samples or performing measurements on calibrated reference devices provided by an external agency to verify laboratory accuracy and precision. The laboratory\'s results are compared to established target values and peer laboratory data. Satisfactory proficiency testing performance is typically required for laboratory accreditation and demonstrates ongoing analytical competency.',
    difficulty: 1,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 86,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What requirements must a pulmonary function laboratory meet for accreditation?',
    answer: 'Accreditation requirements include documented policies and procedures for all tests performed, equipment calibration and maintenance logs, quality control programs with biological controls and trending, staff credentialing and continuing education records, proficiency testing participation and satisfactory performance, infection control protocols, patient safety procedures, and medical director oversight. Laboratory space, ventilation, and equipment must meet professional society standards.',
    difficulty: 2,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 87,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is biological quality control in pulmonary function testing?',
    answer: 'Biological quality control uses healthy, nonsmoking laboratory staff as control subjects who perform pulmonary function tests at regular intervals (typically weekly). Their results are tracked over time and compared to their established personal baseline. Deviations beyond expected biological variability (typically more than 5% for FEV1 and FVC, or more than 10% for DLCO) may indicate equipment malfunction, calibration drift, or technical problems that mechanical calibration checks cannot detect.',
    difficulty: 2,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 88,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How is trending analysis used for quality management in pulmonary function laboratories?',
    answer: 'Trending analysis tracks quality control data points over time on control charts to identify systematic changes or drift in equipment performance. Each biological control measurement is plotted against the subject\'s established mean and standard deviation. Patterns such as progressive drift in one direction, sudden shifts, or values consistently on one side of the mean can detect subtle equipment deterioration before results fall outside acceptable limits.',
    difficulty: 2,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 89,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are the Westgard rules and how do they apply to pulmonary function laboratory quality control?',
    answer: 'Westgard rules are statistical decision criteria applied to quality control charts. Key rules include: 1-2s (single observation beyond 2 SD as a warning), 1-3s (single observation beyond 3 SD rejects the run), 2-2s (two consecutive observations beyond 2 SD in the same direction indicates systematic error), R-4s (range between two consecutive values exceeds 4 SD indicates random error), and trend rules for multiple sequential observations drifting in one direction.',
    difficulty: 3,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 90,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What factors should guide the selection of reference equations for a pulmonary function laboratory?',
    answer: 'Reference equations should be selected based on the demographics of the patient population served (age range, sex, race/ethnicity, height range). The equations should be derived from studies using the same equipment type and testing methodology currently employed by the laboratory. ATS/ERS recommends the Global Lung Initiative (GLI-2012) equations because they span ages 3-95 and multiple ethnic groups using a unified statistical approach.',
    difficulty: 2,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 91,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are the advantages of the GLI-2012 reference equations over older reference sets?',
    answer: 'GLI-2012 equations use lambda-mu-sigma (LMS) methodology that accounts for age-dependent changes in variability, eliminating the need for separate equations at different ages. They provide continuous prediction from age 3 to 95, use z-scores rather than percent predicted for more statistically valid interpretation, include multiple ethnic groups within one model, and derive from a large pooled dataset of over 70,000 subjects to improve statistical power.',
    difficulty: 3,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 92,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'Why are z-scores preferred over percent predicted for interpreting pulmonary function results?',
    answer: 'Percent predicted uses a fixed threshold (e.g., 80% predicted) that does not account for age, height, and sex-related differences in normal variability. Z-scores express the result as the number of standard deviations from the predicted mean, providing a statistically consistent threshold (e.g., less than minus 1.645 equals below the 5th percentile) regardless of patient demographics. This prevents the over-diagnosis of abnormality in elderly and tall individuals and under-diagnosis in younger patients.',
    difficulty: 3,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 93,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What elements must be included in an informed consent document for a pulmonary function research study?',
    answer: 'Informed consent must include a description of the study purpose and procedures, expected duration of participation, potential risks and discomforts (including specific risks of each test), potential benefits, alternatives to participation, confidentiality protections, compensation details if applicable, contact information for questions, a statement that participation is voluntary with the right to withdraw at any time without penalty, and an explanation of how adverse events will be managed.',
    difficulty: 1,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 94,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What role does an Institutional Review Board (IRB) play in pulmonary function research?',
    answer: 'The IRB reviews all research protocols involving human subjects to ensure ethical standards are met before the study begins. It evaluates the risk-benefit ratio, ensures informed consent is adequate, monitors subject recruitment methods for equity, reviews data safety monitoring plans, and conducts ongoing oversight of active studies including adverse event review and protocol modification approval. No human subject research may begin without IRB approval.',
    difficulty: 1,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 95,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How should adverse events during pulmonary function testing be documented and managed?',
    answer: 'Each adverse event requires immediate clinical assessment and stabilization, documentation of the event type, timing, severity, and resolution, notification of the supervising physician, and entry into an incident reporting system. For research studies, adverse events must also be reported to the IRB within specified timeframes (immediately for serious events). Root cause analysis should be performed to identify preventable factors, and corrective actions must be implemented and documented.',
    difficulty: 2,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 96,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What is the purpose of a standard operating procedure (SOP) manual in a pulmonary function laboratory?',
    answer: 'The SOP manual provides detailed, step-by-step written instructions for every test performed, calibration procedure, quality control process, equipment maintenance task, and emergency protocol in the laboratory. SOPs ensure consistency across different technologists, serve as the authoritative reference for proper technique, satisfy accreditation requirements, facilitate training of new staff, and provide documentation for quality assurance review.',
    difficulty: 2,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 97,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How is a Levey-Jennings chart constructed and interpreted for pulmonary function equipment monitoring?',
    answer: 'A Levey-Jennings chart plots sequential quality control measurements over time with the established mean as the center line and lines at plus or minus 1, 2, and 3 standard deviations. Data points falling within 2 SD indicate acceptable performance. Points beyond 2 SD trigger investigation, and beyond 3 SD requires corrective action before patient testing. Patterns such as trends (7 consecutive points in one direction), shifts (7 points on one side of the mean), and excessive scatter indicate systematic or random error.',
    difficulty: 2,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 98,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'What are the key components of a clinical research protocol for a pulmonary function study?',
    answer: 'A research protocol must include a clear hypothesis and objectives, study design (randomized, controlled, blinded), inclusion and exclusion criteria, sample size calculation with statistical justification, detailed description of all measurements and their standardization, data collection and management plan, statistical analysis plan, safety monitoring procedures, stopping rules for the study, timeline, and budget. The protocol must be reviewed and approved by the IRB before enrollment begins.',
    difficulty: 2,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 99,
  },
  {
    divisionId: RPFT_DIVISION_ID,
    question: 'How does the coefficient of variation (CV) function as a quality metric in pulmonary function testing?',
    answer: 'The CV expresses measurement variability as a percentage of the mean (CV = standard deviation divided by mean times 100). In biological quality control, acceptable within-subject CV for FEV1 and FVC is typically less than 5%, while DLCO may have a higher acceptable CV around 10% due to greater inherent test variability. Equipment precision CV should be less than 3% for flow and volume measurements. Tracking CV over time detects increases in measurement variability that may signal deteriorating equipment or inconsistent technique.',
    difficulty: 3,
    topic: 'Quality Management & Research',
    isFree: false,
    orderIndex: 100,
  },
]

async function main() {
  console.log('Seeding RPFT flashcards (Batch 1: cards 1-100)...')
  console.log(`Total cards to insert: ${flashcards.length}`)

  // Verify the division exists
  const division = await prisma.division.findUnique({
    where: { id: RPFT_DIVISION_ID },
  })

  if (!division) {
    console.error(
      `Division ${RPFT_DIVISION_ID} not found. Run seed-divisions.ts first.`
    )
    process.exit(1)
  }

  console.log(`Found division: ${division.name}`)

  // Delete existing flashcards for this division to avoid duplicates on re-run
  const deleted = await prisma.flashcard.deleteMany({
    where: { divisionId: RPFT_DIVISION_ID },
  })
  console.log(`Cleared ${deleted.count} existing flashcards for RPFT division.`)

  // Insert all flashcards
  const result = await prisma.flashcard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })

  console.log(`Successfully inserted ${result.count} RPFT flashcards.`)

  // Log summary by topic
  const topicCounts: Record<string, number> = {}
  const difficultyCounts: Record<number, number> = { 1: 0, 2: 0, 3: 0 }
  let freeCount = 0

  for (const card of flashcards) {
    topicCounts[card.topic] = (topicCounts[card.topic] || 0) + 1
    difficultyCounts[card.difficulty]++
    if (card.isFree) freeCount++
  }

  console.log('\n--- Summary ---')
  console.log('By topic:')
  for (const [topic, count] of Object.entries(topicCounts)) {
    console.log(`  ${topic}: ${count} cards`)
  }
  console.log('By difficulty:')
  console.log(`  Easy (1): ${difficultyCounts[1]}`)
  console.log(`  Medium (2): ${difficultyCounts[2]}`)
  console.log(`  Hard (3): ${difficultyCounts[3]}`)
  console.log(`Free cards: ${freeCount}`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
